CREATE TABLE [base_tx_crh_2_dwh].[DIM_INVENTTABLE](
	[DW_Id] [bigint] NOT NULL,
	[ADUASCHWITEMGROUP2] [nvarchar](10) NULL,
	[ADUASCHWITEMGROUP2DESCRIPTION] [nvarchar](60) NULL,
	[ADUASCHWITEMGROUP3] [varchar](50) NULL,
	[ADUASCHWITEMGROUP4] [nvarchar](10) NULL,
	[ADUASCHWITEMGROUP4DESCRIPTION] [nvarchar](60) NULL,
	[BOMUNITID] [nvarchar](10) NULL,
	[ITEMGROUPID] [nvarchar](10) NULL,
	[ITEMID] [nvarchar](20) NULL,
	[ITEMNAME] [nvarchar](60) NULL,
	[ADUTYPEMATERIAL] [nvarchar](20) NULL,
	[ADUTYPECRHCA] [nvarchar](20) NULL,
	[ITEMTYPE] [bigint] NULL,
	[ADUITEMCLASSIFICATION] [bigint] NULL,
	[ADUCATAREF] [nvarchar](10) NULL,
	[ADUINNOVATIVE] [bigint] NULL,
	[ADUMARKETLAUNCHDATE] [datetime] NULL,
	[DATAAREAID] [nvarchar](4) NULL,
	[ItemGroupName] [nvarchar](60) NULL,
	[PRODPOOLID] [nvarchar](10) NULL,
	[DIMGROUPID] [nvarchar](10) NULL,
	[DimGroupFrance] [varchar](50) NULL,
	[StockUnit] [varchar](10) NULL,
	[PurchaseUnit] [varchar](10) NULL,
	[SalesUnit] [varchar](10) NULL,
	[INVENTSIZEID] [nvarchar](10) NULL,
	[REQGROUPID] [nvarchar](10) NULL,
	[QSS] [varchar](50) NULL,
	[StockPrice] [decimal](38, 2) NULL,
	[PurchasePrice] [decimal](38, 2) NULL,
	[ABCVALUE] [int] NULL,
	[ABCREVENUE] [int] NULL,
	[ABCCONTRIBUTIONMARGIN] [int] NULL,
	[StockPriceUnit] [decimal](38, 2) NULL,
	[PurchasePriceUnit] [decimal](38, 2) NULL,
	[SalesPriceUnit] [decimal](38, 2) NULL,
	[Active/Inactive] [varchar](8) NULL,
	[InventoryStoppedYN] [varchar](3) NULL,
	[PurchaseStoppedYN] [varchar](3) NULL,
	[SalesStoppedYN] [varchar](3) NULL,
	[DW_Batch] [bigint] NULL,
	[DW_SourceCode] [varchar](15) NOT NULL,
	[DW_TimeStamp] [datetime] NOT NULL,
	[t_applicationId] VARCHAR    (32)  NULL,
    [t_jobId]         VARCHAR    (36)  NULL,
    [t_jobDtm]        DATETIME,
    [t_jobBy]         NVARCHAR  (128)  NULL,
    [t_extractionDtm] DATETIME,
    [t_filePath]      NVARCHAR (1024)  NULL
 CONSTRAINT [PK_DIM_INVENTTABLE] PRIMARY KEY NONCLUSTERED 
(
	[DW_Id] ASC
)NOT ENFORCED
) WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);