CREATE TABLE [base_tx_crh_2_dwh].[FACT_SALESLINE](
	[DW_Id] [bigint] NOT NULL,
	[CUSTACCOUNT] [nvarchar](20) NULL,
	[DATAAREAID] [nvarchar](4) NULL,
	[ITEMID] [nvarchar](20) NULL,
	[ADUBUILDINGSITEID] [nvarchar](20) NULL,
	[DIMENSION] [nvarchar](10) NULL,
	[DIMENSION2_] [nvarchar](10) NULL,
	[DIMENSION3_] [nvarchar](10) NULL,
	[DIMENSION4_] [nvarchar](10) NULL,
	[DELIVERYSTATE] [nvarchar](10) NULL,
	[DELIVERYCOUNTRYREGIONID] [nvarchar](10) NULL,
	[DELIVERYCOUNTY] [nvarchar](10) NULL,
	[RealCounty] [nvarchar](10) NULL,
	[RealState] [nvarchar](10) NULL,
	[INVENTDIMID] [nvarchar](20) NULL,
	[INVENTSITEID] [nvarchar](10) NULL,
	[INVENTLOCATIONID] [nvarchar](10) NULL,
	[INVENTCOLORID] [nvarchar](10) NULL,
	[INVENTSIZEID] [nvarchar](10) NULL,
	[CONFIGID] [nvarchar](10) NULL,
	[CREATEDDATETIME] [datetime] NULL,
	[SALESGROUP] [nvarchar](10) NULL,
	[SalesGroupName] [nvarchar](60) NULL,
	[DLVMODE] [nvarchar](10) NULL,
	[SALESID] [nvarchar](20) NULL,
	[PRICEUNIT] [decimal](38, 12) NULL,
	[SALESQTY] [decimal](38, 12) NULL,
	[SALESSTATUS] [bigint] NULL,
	[SALESPRICE] [decimal](38, 12) NULL,
	[SHIPPINGDATEREQUESTED] [datetime] NULL,
	[COSTPRICE] [decimal](38, 12) NULL,
	[LINEAMOUNT] [decimal](38, 12) NULL,
	[LineAmount_MST_TransDate] [decimal](38, 12) NULL,
	[DateKey_CreatedDateTime] [bigint] NULL,
	[DataArea_DW_Id] [bigint] NULL,
	[CURRENCYCODE] [nvarchar](3) NULL,
	[adm_CompCurrency] [nvarchar](3) NULL,
	[ExchRate_MST_CurrentDate] [decimal](38, 12) NULL,
	[CurrentDate] [datetime] NULL,
	[SALESSTATUSNAME] [nvarchar](1999) NULL,
	[DELIVERYZIPCODE] [nvarchar](10) NULL,
	[SHIPPINGDATECONFIRMED] [datetime] NULL,
	[INVENTTRANSID] [nvarchar](24) NULL,
	[ADMIN_VirtualDataAreaId_Country] [nvarchar](4) NULL,
	[ADMIN_VirtualDataAreaID_County] [nvarchar](4) NULL,
	[ADMIN_VirtualDataAread_State] [nvarchar](4) NULL,
	[REMAINSALESFINANCIAL] [decimal](38, 12) NULL,
	[REMAINSALESPHYSICAL] [decimal](38, 12) NULL,
	[SALESPRICEPERUNIT] [decimal](38, 12) NULL,
	[REMAINAMOUNTPHYSICAL] [decimal](38, 12) NULL,
	[REMAINAMOUNTFINANCIAL] [decimal](38, 12) NULL,
	[CountryRegion_DW_Id] [bigint] NULL,
	[State_DW_Id] [bigint] NULL,
	[County_DW_Id] [bigint] NULL,
	[ADUASSGROUP4] [nvarchar](10) NULL,
	[ADUASSGROUP4_DW_Id] [bigint] NULL,
	[ADUASSGROUP2] [nvarchar](10) NULL,
	[ADUASSGROUP2_DW_Id] [bigint] NULL,
	[LedgerCostPrice] [decimal](38, 12) NULL,
	[ADUADDGROUP3] [varchar](50) NULL,
	[ADUADDGROUP3_DW_Id] [bigint] NULL,
	[SalesGroup_DW_Id] [bigint] NULL,
	[ADUBACKUPNETPRICE] [bigint] NULL,
	[AduBackupNetPrice_Label] [nvarchar](5) NULL,
	[InvoicedAmount_FromCustInvoiceTrans] [decimal](38, 12) NULL,
	[CostPrice_Calculated] [decimal](38, 18) NULL,
	[aduAschwSuppAmount] [decimal](38, 12) NULL,
	[SALESGROUP_FromZipCode] [nvarchar](10) NULL,
	[CommissionSalesGroup_FromZipCode_DW_Id] [bigint] NULL,
	[QuoteA] [decimal](38, 0) NULL,
	[QuoteB] [decimal](38, 0) NULL,
	[LINEAMOUNTWITHTOESLAG] [decimal](38, 2) NULL,
	[QuoteDimession] [varchar](3) NULL,
	[INVOICECITY] [nvarchar](60) NULL,
	[DELIVERYCITY2] [nvarchar](60) NULL,
	[CONFIRMEDDLV] [datetime] NULL,
	[CostAmount] [decimal](38, 12) NULL,
	[ADUNETWEIGHT] [decimal](38, 12) NULL,
	[DELIVERYDATEleverbon] [datetime] NULL,
	[INVENTREFID] [nvarchar](20) NULL,
	[PACKINGSLIPID] [nvarchar](20) NULL,
	[ADUTOINVOICE] [varchar](50) NULL,
	[SALESRESPONSIBLE] [nvarchar](20) NULL,
	[PURCHORDERFORMNUM] [nvarchar](30) NULL,
	[ADUFILEREFERENCE] [nvarchar](20) NULL,
	[ADUIGNORECREDITLIMTTEXT] [varchar](3) NULL,
	[RECEIPTDATEREQUESTED] [datetime] NULL,
	[DW_Batch] [bigint] NULL,
	[DW_SourceCode] [varchar](15) NOT NULL,
	[DW_TimeStamp] [datetime] NOT NULL,
	[t_applicationId] VARCHAR    (32)  NULL,
    [t_jobId]         VARCHAR    (36)  NULL,
    [t_jobDtm]        DATETIME,
    [t_jobBy]         NVARCHAR  (128)  NULL,
    [t_extractionDtm] DATETIME,
    [t_filePath]      NVARCHAR (1024)  NULL
 CONSTRAINT [PK_FACT_SALESLINE] PRIMARY KEY NONCLUSTERED 
(
	[DW_Id] ASC
)NOT ENFORCED
) WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);