CREATE TABLE [base_tx_crh_2_dwh].[FACT_CUSTINVOICETRANS](
	[DW_Id] [bigint] NOT NULL,
	[DATAAREAID] [nvarchar](4) NULL,
	[INVOICEACCOUNT] [nvarchar](20) NULL,
	[BUILDINGSITEID] [nvarchar](20) NULL,
	[DIMENSION] [nvarchar](10) NULL,
	[DIMENSION2_] [nvarchar](10) NULL,
	[DIMENSION3_] [nvarchar](10) NULL,
	[DIMENSION4_] [nvarchar](10) NULL,
	[DLVZIPCODE] [nvarchar](10) NULL,
	[DLVCOUNTRYREGIONID] [nvarchar](10) NULL,
	[DLVCOUNTY] [nvarchar](10) NULL,
	[DLVSTATE] [nvarchar](10) NULL,
	[RealCounty] [nvarchar](10) NULL,
	[RealState] [nvarchar](10) NULL,
	[INVENTDIMID] [nvarchar](20) NULL,
	[INVENTSITEID] [nvarchar](10) NULL,
	[INVENTLOCATIONID] [nvarchar](10) NULL,
	[CONFIGID] [nvarchar](10) NULL,
	[INVENTSIZEID] [nvarchar](10) NULL,
	[INVENTCOLORID] [nvarchar](10) NULL,
	[INVOICEID] [nvarchar](20) NULL,
	[ITEMID] [nvarchar](20) NULL,
	[INVOICEDATE] [datetime] NULL,
	[INVENTTRANSID] [nvarchar](24) NULL,
	[LINEAMOUNTMST] [decimal](38, 2) NULL,
	[ORIGSALESID] [nvarchar](20) NULL,
	[QTY] [decimal](38, 0) NULL,
	[SALESCONTRIBUTIONMARGINMST] [decimal](38, 12) NULL,
	[SALESGROUP] [nvarchar](10) NULL,
	[SalesGroupName] [nvarchar](60) NULL,
	[DateKey_InvoiceDate] [bigint] NULL,
	[DataArea_DW_Id] [bigint] NULL,
	[SALESPRICE] [decimal](38, 12) NULL,
	[SALESUNIT] [nvarchar](10) NULL,
	[DiscountAmount] [decimal](38, 12) NULL,
	[DlvMode] [nvarchar](10) NULL,
	[ADMIN_VirtualDataAreaId_Country] [nvarchar](4) NULL,
	[CountryRegion_DW_Id] [bigint] NULL,
	[ADMIN_VirtualDataAreaId_County] [nvarchar](4) NULL,
	[ADMIN_VirtualDataAreaId_State] [nvarchar](4) NULL,
	[County_DW_Id] [bigint] NULL,
	[State_DW_Id] [bigint] NULL,
	[ADUITEMGROUP2] [nvarchar](10) NULL,
	[ADUITEMGROUP4] [nvarchar](10) NULL,
	[ADUASSGROUP4_DW_Id] [bigint] NULL,
	[ADUASSGROUP2_DW_Id] [bigint] NULL,
	[ADUADDGROUP3] [varchar](50) NULL,
	[ADUADDGROUP3_DW_Id] [bigint] NULL,
	[SalesGroup_DW_Id] [bigint] NULL,
	[CostPrice_Calculated] [decimal](38, 18) NULL,
	[aduAschwSuppAmount] [decimal](38, 12) NULL,
	[CommissionSalesGroup_FromZipCode_DW_Id] [bigint] NULL,
	[NETWEIGHT] [decimal](38, 12) NULL,
	[COSTAMOUNTPOSTED] [decimal](38, 12) NULL,
	[COUNTRYREGIONID] [nvarchar](10) NULL,
	[CostAmount] [decimal](38, 18) NULL,
	[CostAmountExclFreight] [decimal](38, 2) NULL,
	[ItemGroupName] [nvarchar](60) NULL,
	[DIVISION] [varchar](50) NULL,
	[STATE] [varchar](50) NULL,
	[DiscountPrice] [decimal](38, 12) NULL,
	[DATEPHYSICAL] [datetime] NULL,
	[AnalyticCodePLF] [varchar](50) NULL,
	[Margin_FACT] [decimal](38, 2) NULL,
	[LINENUM] [decimal](38, 12) NULL,
	[Voucher] [nvarchar](20) NULL,
	[AmountWithVAT] [decimal](38, 2) NULL,
	[ADUPURCHORDERFORMNUM] [nvarchar](30) NULL,
	[DW_Batch] [bigint] NULL,
	[DW_SourceCode] [varchar](15) NOT NULL,
	[DW_TimeStamp] [datetime] NOT NULL,
	[t_applicationId] VARCHAR    (32)  NULL,
    [t_jobId]         VARCHAR    (36)  NULL,
    [t_jobDtm]        DATETIME,
    [t_jobBy]         NVARCHAR  (128)  NULL,
    [t_extractionDtm] DATETIME,
    [t_filePath]      NVARCHAR (1024)  NULL
 CONSTRAINT [PK_FACT_CUSTINVOICETRANS] PRIMARY KEY NONCLUSTERED 
(
	[DW_Id] ASC
)NOT ENFORCED
) WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);