-- SELECT From Parquet file(FuLL File) in the DataLake directly
-- Need to correctly mount and see appropriate access are granted for Synapse to do this.
-- We might have to check if this is Okay and gives no issues in checksums/ Create External table first alternatively.

--SELECT
--    TOP 100 *
--FROM
--    OPENROWSET(
--        BULK 'https://stxxxxslsdeuw001.dfs.core.windows.net/tx-ca-0-hlp-uat/CUSTINVOICETRANS/Out/2022/07/13/CUSTINVOICETRANS_2022_07_13_14_27_23_820.parquet',
--        FORMAT = 'PARQUET'
--    ) AS [result]

-- GENERATING DELTA
-- [pgr].[FACT_HGDAWA_delta]  is the source(External) table and [pgr].[FACT_HGDAWA_] is the Destination Table.
-- Edgecases where checksum might not be effective can be found in the below article.
-- https://docs.microsoft.com/en-us/sql/t-sql/functions/checksum-transact-sql?view=sql-server-ver16
-- Notice Checksum is not a persisted value any more hence no column to hold checksum column
-- Only the Fact table/Dim Table will have an additional columns 
		--LastUpdatedDate - Touch date for the record
		--Flg - I(Insert),U(Update),D(Soft Delete)
-- Base Table/Source table to have a flag for convinience and to enable simple debugging 
		--Flg (Lookup Flag) To denote if a source record has to be updated/inserted or deleted at its destination. 

-- Mark Updates (ExecTime 13s, updated 4712 records of 25M)


UPDATE
    src
SET
    src.Flg='U'
FROM
    [pgr].[FACT_HGDAWA_delta] AS src
INNER JOIN
    [pgr].[FACT_HGDAWA_] dest
    ON 
        src.[Invoiceno] = dest.[Invoiceno]
        AND
        src.[Posno] = dest.[Posno]
	    AND
		CHECKSUM( 
            src.[Company],
            src.[Distributioncompany],
            src.[Salesarea],
            src.[Inside_Outside],
            src.[Inside_Outside-Text],
            src.[Site],
            -- src.[Invoiceno],
            src.[Invoicedate],
            src.[Accountingdate],
            src.[Year],
            src.[Month],
            src.[Day],
            src.[Orderno],
            src.[Deliveryno],
            -- src.[Posno],
            src.[Orderdate],
            src.[Deldateplan],
            src.[Deldateconfirmed],
            src.[Deldateact],
            src.[SalesType],
            src.[Customerno],
            src.[Country],
            src.[Postalcode],
            src.[DlvCountry],
            src.[DlvState],
            src.[DlvCounty],
            src.[Mainsalesperson],
            src.[Salesperson],
            src.[Maindistrict],
            src.[Salesdistrict],
            src.[Lineofbusiness],
            src.[Concern],
            src.[I_E_V],
            src.[I_E_V-Text],
            src.[Responsible],
            src.[Warehouse],
            src.[Aquisitioncode],
            src.[Aquisitioncode-Text],
            src.[Originwarehouse],
            src.[OriginAquisitioncode],
            src.[OriginAquisitioncode-Text],
            src.[Itemno],
            src.[Productsub_group],
            src.[Itemtype],
            src.[Productgroup],
            src.[Productline],
            src.[Productrange],
            src.[CRHProductGroupID],
            src.[Production_Purchase],
            src.[Stainlesssteelflag],
            src.[Stainlesssteel-Text],
            src.[MainProductclass],
            src.[Productclass],
            src.[Configno],
            src.[Pricelistno],
            src.[Projectno],
            src.[ProjectPos],
            src.[Kitheaderno],
            src.[Bruttosaleslocal],
            src.[BruttosalesCRHEUR],
            src.[Brutto2saleslocal],
            src.[Brutto2salesCRHEUR],
            src.[Nettosalesposlocal],
            src.[NettosalesposCRHEUR],
            src.[Linepercentweighted],
            src.[Invoicedsaleslocal],
            src.[InvoicedsalesCRHEUR],
            src.[Othersaleslocal],
            src.[OthersalesCRHEUR],
            src.[Allowanceslocal],
            src.[AllowancesCRHEUR],
            src.[Sales100%local],
            src.[Sales100%CRHEUR],
            src.[TZlocal],
            src.[TZCRHEUR],
            src.[TZpercent],
            src.[LZlocal],
            src.[LZCRHEUR],
            src.[LZpercent],
            src.[Linediscount1local],
            src.[Linediscount1CRHEUR],
            src.[Linediscount1percent],
            src.[Linediscount2local],
            src.[Linediscount2CRHEUR],
            src.[Linediscount2percent],
            src.[Orderdiscountlocal],
            src.[OrderdiscountCRHEUR],
            src.[Orderdiscountpercent],
            src.[Productsaleslocal],
            src.[ProductsalesCRHEUR],
            src.[Plantsellingpricelocal],
            src.[PlantsellingpriceCRHEUR],
            src.[ICPlocal],
            src.[ICPCRHEUR],
            src.[SMClocal],
            src.[SMCCRHEUR],
            src.[SMCsumlocal],
            src.[SMCsumCRHEUR],
            src.[Variablesellingcostslocal],
            src.[VariablesellingcostsCRHEUR],
            src.[Netsaleslocal],
            src.[NetsalesCRHEUR],
            src.[Grossmarginlocal],
            src.[GrossmarginCRHEUR],
            src.[contribmarginIIdclocal],
            src.[contribmarginIIdcCRHEUR],
            src.[contribmarginIIholocal],
            src.[contribmarginIIhoCRHEUR],
            src.[Plantoverheadcostslocal],
            src.[PlantoverheadcostsCRHEUR],
            src.[contribmarginIIIlocal],
            src.[contribmarginIIICRHEUR],
            src.[Invoicequantity],
            src.[Orderquantity],
            src.[Netweight],
            src.[Freightinvoicedlocal],
            src.[FreightinvoicedCRHEUR],
            src.[Tollinvoicedlocal],
            src.[TollinvoicedCRHEUR],
            src.[Packingsinvoicedlocal],
            src.[PackingsinvoicedCRHEUR],
            src.[Surchargeonshortquantitylocal],
            src.[SurchargeonshortquantityCRHEUR],
            src.[Planningcostsinvoicedlocal],
            src.[PlanningcostsinvoicedCRHEUR],
            src.[Packingdepositlocal],
            src.[PackingdepositCRHEUR],
            src.[Miscellaneousproceedsinvoicedlocal],
            src.[MiscellaneousproceedsinvoicedCRHEUR],
            src.[Reservecustomerbonuslocal],
            src.[ReservecustomerbonusCRHEUR],
            src.[Warrentieslocal],
            src.[WarrentiesCRHEUR],
            src.[Marketingcostsallowanceslocal],
            src.[MarketingcostsallowancesCRHEUR],
            src.[Reservecustomerdiscountlocal],
            src.[ReservecustomerdiscountCRHEUR],
            src.[Freightcostslocal],
            src.[FreightcostsCRHEUR],
            src.[Packingcostslocal],
            src.[PackingcostsCRHEUR],
            src.[Dutieslocal],
            src.[DutiesCRHEUR],
            src.[Insurancelocal],
            src.[InsuranceCRHEUR],
            src.[Commissionslocal],
            src.[CommissionsCRHEUR],
            src.[Licenceslocal],
            src.[LicencesCRHEUR],
            src.[SMCordinarysteellocal],
            src.[SMCordinarysteelCRHEUR],
            src.[SMCstainlesssteellocal],
            src.[SMCstainlesssteelCRHEUR],
            src.[SMCotherrawmateriallocal],
            src.[SMCotherrawmaterialCRHEUR],
            src.[SMCmaterialoverheadcostslocal],
            src.[SMCmaterialoverheadcostsCRHEUR],
            src.[SMCalloysurchargelocal],
            src.[SMCalloysurchargeCRHEUR],
            src.[SMCexternalproductioncostslocal],
            src.[SMCexternalproductioncostsCRHEUR],
            src.[SMCvariableproductioncostslocal],
            src.[SMCvariableproductioncostsCRHEUR],
            src.[SMCfixedproductioncostslocal],
            src.[SMCfixedproductioncostsCRHEUR],
            src.[CostsofcapitalE01local],
            src.[CostsofcapitalE01CRHEUR],
            src.[WarehousechargesE02local],
            src.[WarhousechargesE02CRHEUR],
            src.[HandlingchargesE03local],
            src.[HandlingchargesE03CRHEUR],
            src.[PackagingchargesE04local],
            src.[PackagingchargesE04CRHEUR],
            src.[PlantoverheadE05local],
            src.[PlantoverheadE05CRHEUR],
            src.[E06local],
            src.[E06CRHEUR],
            src.[E07local],
            src.[E07CRHEUR],
            src.[PlantprofitE08local],
            src.[PlantprofitE08CRHEUR],
            src.[ICsurchargeE09local],
            src.[ICsurchargeE09CRHEUR],
            src.[FreightsurchargeE10local],
            src.[FreightsurchargeE10CRHEUR],
            src.[Freightdctocustomerlocal],
            src.[FreightdctocustomerCRHEUR],
            src.[FreightAR_LAtodclocal],
            src.[FreightAR_LAtodcCRHEUR],
            src.[FreightPNtoAR_LAlocal],
            src.[FreightPNtoAR_LACRHEUR],
            src.[DAN502],
            src.[DAN503],
            src.[DAA705],
            src.[LengthinMper1],
            src.[LengthinM],
            src.[Freight_Tollinvoicedlocal],
            src.[Freight_TollinvoicedCRHEUR],
            src.[Packaginginvoicedlocal],
            src.[PackaginginvoicedCRHEUR],
            src.[Grosssaleslocal],
            src.[GrosssalesCRHEUR],
            src.[CostCenter],
            src.[DAGRWE],
            src.[CurrencyRatelocaltoCRH1EUR],
            src.[CurrencyEUR],
            src.[Currencylocal],
            src.[Salespersonname],
            src.[Salesdistrictname],
            src.[Projectname],
            src.[Projectdeliverycountry],
            src.[Projectdeliverycity],
            src.[Companycountrycode],
            src.[Companycountryname],
            src.[DW_Batch],
            src.[DW_SourceCode],
            src.[DW_TimeStamp]
        ) <> 
		CHECKSUM( 
			dest.[Company],
            dest.[Distributioncompany],
            dest.[Salesarea],
            dest.[Inside_Outside],
            dest.[Inside_Outside-Text],
            dest.[Site],
            -- dest.[Invoiceno],
            dest.[Invoicedate],
            dest.[Accountingdate],
            dest.[Year],
            dest.[Month],
            dest.[Day],
            dest.[Orderno],
            dest.[Deliveryno],
            -- dest.[Posno],
            dest.[Orderdate],
            dest.[Deldateplan],
            dest.[Deldateconfirmed],
            dest.[Deldateact],
            dest.[SalesType],
            dest.[Customerno],
            dest.[Country],
            dest.[Postalcode],
            dest.[DlvCountry],
            dest.[DlvState],
            dest.[DlvCounty],
            dest.[Mainsalesperson],
            dest.[Salesperson],
            dest.[Maindistrict],
            dest.[Salesdistrict],
            dest.[Lineofbusiness],
            dest.[Concern],
            dest.[I_E_V],
            dest.[I_E_V-Text],
            dest.[Responsible],
            dest.[Warehouse],
            dest.[Aquisitioncode],
            dest.[Aquisitioncode-Text],
            dest.[Originwarehouse],
            dest.[OriginAquisitioncode],
            dest.[OriginAquisitioncode-Text],
            dest.[Itemno],
            dest.[Productsub_group],
            dest.[Itemtype],
            dest.[Productgroup],
            dest.[Productline],
            dest.[Productrange],
            dest.[CRHProductGroupID],
            dest.[Production_Purchase],
            dest.[Stainlesssteelflag],
            dest.[Stainlesssteel-Text],
            dest.[MainProductclass],
            dest.[Productclass],
            dest.[Configno],
            dest.[Pricelistno],
            dest.[Projectno],
            dest.[ProjectPos],
            dest.[Kitheaderno],
            dest.[Bruttosaleslocal],
            dest.[BruttosalesCRHEUR],
            dest.[Brutto2saleslocal],
            dest.[Brutto2salesCRHEUR],
            dest.[Nettosalesposlocal],
            dest.[NettosalesposCRHEUR],
            dest.[Linepercentweighted],
            dest.[Invoicedsaleslocal],
            dest.[InvoicedsalesCRHEUR],
            dest.[Othersaleslocal],
            dest.[OthersalesCRHEUR],
            dest.[Allowanceslocal],
            dest.[AllowancesCRHEUR],
            dest.[Sales100%local],
            dest.[Sales100%CRHEUR],
            dest.[TZlocal],
            dest.[TZCRHEUR],
            dest.[TZpercent],
            dest.[LZlocal],
            dest.[LZCRHEUR],
            dest.[LZpercent],
            dest.[Linediscount1local],
            dest.[Linediscount1CRHEUR],
            dest.[Linediscount1percent],
            dest.[Linediscount2local],
            dest.[Linediscount2CRHEUR],
            dest.[Linediscount2percent],
            dest.[Orderdiscountlocal],
            dest.[OrderdiscountCRHEUR],
            dest.[Orderdiscountpercent],
            dest.[Productsaleslocal],
            dest.[ProductsalesCRHEUR],
            dest.[Plantsellingpricelocal],
            dest.[PlantsellingpriceCRHEUR],
            dest.[ICPlocal],
            dest.[ICPCRHEUR],
            dest.[SMClocal],
            dest.[SMCCRHEUR],
            dest.[SMCsumlocal],
            dest.[SMCsumCRHEUR],
            dest.[Variablesellingcostslocal],
            dest.[VariablesellingcostsCRHEUR],
            dest.[Netsaleslocal],
            dest.[NetsalesCRHEUR],
            dest.[Grossmarginlocal],
            dest.[GrossmarginCRHEUR],
            dest.[contribmarginIIdclocal],
            dest.[contribmarginIIdcCRHEUR],
            dest.[contribmarginIIholocal],
            dest.[contribmarginIIhoCRHEUR],
            dest.[Plantoverheadcostslocal],
            dest.[PlantoverheadcostsCRHEUR],
            dest.[contribmarginIIIlocal],
            dest.[contribmarginIIICRHEUR],
            dest.[Invoicequantity],
            dest.[Orderquantity],
            dest.[Netweight],
            dest.[Freightinvoicedlocal],
            dest.[FreightinvoicedCRHEUR],
            dest.[Tollinvoicedlocal],
            dest.[TollinvoicedCRHEUR],
            dest.[Packingsinvoicedlocal],
            dest.[PackingsinvoicedCRHEUR],
            dest.[Surchargeonshortquantitylocal],
            dest.[SurchargeonshortquantityCRHEUR],
            dest.[Planningcostsinvoicedlocal],
            dest.[PlanningcostsinvoicedCRHEUR],
            dest.[Packingdepositlocal],
            dest.[PackingdepositCRHEUR],
            dest.[Miscellaneousproceedsinvoicedlocal],
            dest.[MiscellaneousproceedsinvoicedCRHEUR],
            dest.[Reservecustomerbonuslocal],
            dest.[ReservecustomerbonusCRHEUR],
            dest.[Warrentieslocal],
            dest.[WarrentiesCRHEUR],
            dest.[Marketingcostsallowanceslocal],
            dest.[MarketingcostsallowancesCRHEUR],
            dest.[Reservecustomerdiscountlocal],
            dest.[ReservecustomerdiscountCRHEUR],
            dest.[Freightcostslocal],
            dest.[FreightcostsCRHEUR],
            dest.[Packingcostslocal],
            dest.[PackingcostsCRHEUR],
            dest.[Dutieslocal],
            dest.[DutiesCRHEUR],
            dest.[Insurancelocal],
            dest.[InsuranceCRHEUR],
            dest.[Commissionslocal],
            dest.[CommissionsCRHEUR],
            dest.[Licenceslocal],
            dest.[LicencesCRHEUR],
            dest.[SMCordinarysteellocal],
            dest.[SMCordinarysteelCRHEUR],
            dest.[SMCstainlesssteellocal],
            dest.[SMCstainlesssteelCRHEUR],
            dest.[SMCotherrawmateriallocal],
            dest.[SMCotherrawmaterialCRHEUR],
            dest.[SMCmaterialoverheadcostslocal],
            dest.[SMCmaterialoverheadcostsCRHEUR],
            dest.[SMCalloysurchargelocal],
            dest.[SMCalloysurchargeCRHEUR],
            dest.[SMCexternalproductioncostslocal],
            dest.[SMCexternalproductioncostsCRHEUR],
            dest.[SMCvariableproductioncostslocal],
            dest.[SMCvariableproductioncostsCRHEUR],
            dest.[SMCfixedproductioncostslocal],
            dest.[SMCfixedproductioncostsCRHEUR],
            dest.[CostsofcapitalE01local],
            dest.[CostsofcapitalE01CRHEUR],
            dest.[WarehousechargesE02local],
            dest.[WarhousechargesE02CRHEUR],
            dest.[HandlingchargesE03local],
            dest.[HandlingchargesE03CRHEUR],
            dest.[PackagingchargesE04local],
            dest.[PackagingchargesE04CRHEUR],
            dest.[PlantoverheadE05local],
            dest.[PlantoverheadE05CRHEUR],
            dest.[E06local],
            dest.[E06CRHEUR],
            dest.[E07local],
            dest.[E07CRHEUR],
            dest.[PlantprofitE08local],
            dest.[PlantprofitE08CRHEUR],
            dest.[ICsurchargeE09local],
            dest.[ICsurchargeE09CRHEUR],
            dest.[FreightsurchargeE10local],
            dest.[FreightsurchargeE10CRHEUR],
            dest.[Freightdctocustomerlocal],
            dest.[FreightdctocustomerCRHEUR],
            dest.[FreightAR_LAtodclocal],
            dest.[FreightAR_LAtodcCRHEUR],
            dest.[FreightPNtoAR_LAlocal],
            dest.[FreightPNtoAR_LACRHEUR],
            dest.[DAN502],
            dest.[DAN503],
            dest.[DAA705],
            dest.[LengthinMper1],
            dest.[LengthinM],
            dest.[Freight_Tollinvoicedlocal],
            dest.[Freight_TollinvoicedCRHEUR],
            dest.[Packaginginvoicedlocal],
            dest.[PackaginginvoicedCRHEUR],
            dest.[Grosssaleslocal],
            dest.[GrosssalesCRHEUR],
            dest.[CostCenter],
            dest.[DAGRWE],
            dest.[CurrencyRatelocaltoCRH1EUR],
            dest.[CurrencyEUR],
            dest.[Currencylocal],
            dest.[Salespersonname],
            dest.[Salesdistrictname],
            dest.[Projectname],
            dest.[Projectdeliverycountry],
            dest.[Projectdeliverycity],
            dest.[Companycountrycode],
            dest.[Companycountryname],
            dest.[DW_Batch],
            dest.[DW_SourceCode],
            dest.[DW_TimeStamp]
        )


-- Mark Inserts 
UPDATE
    src
SET
    src.Flg='I'
FROM
    [pgr].[FACT_HGDAWA_delta] src
LEFT JOIN
    [pgr].[FACT_HGDAWA_] dest
    ON
        src.[Invoiceno] = dest.[Invoiceno]
        AND
        src.[Posno] = dest.[Posno]
WHERE 
    dest.[Invoiceno] IS NULL
    AND
    dest.[Posno] IS NULL


-- MARK Deletes
UPDATE
    src
SET
    src.Flg='D'
FROM
    [pgr].[FACT_HGDAWA_] src 
LEFT JOIN
    [pgr].[FACT_HGDAWA_delta] dest
    ON
        src.[Invoiceno] = dest.[Invoiceno]
        AND
        src.[Posno] = dest.[Posno]
WHERE 
    dest.[Invoiceno] IS NULL
    AND
    dest.[Posno] IS NULL

-- Now Insert whats marked for Insert
INSERT INTO [pgr].[FACT_HGDAWA_] (
    [DW_Id],
    [Company],
    [Distributioncompany],
    [Salesarea],
    [Inside_Outside],
    [Inside_Outside-Text],
    [Site],
    [Invoiceno],
    [Invoicedate],
    [Accountingdate],
    [Year],
    [Month],
    [Day],
    [Orderno],
    [Deliveryno],
    [Posno],
    [Orderdate],
    [Deldateplan],
    [Deldateconfirmed],
    [Deldateact],
    [SalesType],
    [Customerno],
    [Country],
    [Postalcode],
    [DlvCountry],
    [DlvState],
    [DlvCounty],
    [Mainsalesperson],
    [Salesperson],
    [Maindistrict],
    [Salesdistrict],
    [Lineofbusiness],
    [Concern],
    [I_E_V],
    [I_E_V-Text],
    [Responsible],
    [Warehouse],
    [Aquisitioncode],
    [Aquisitioncode-Text],
    [Originwarehouse],
    [OriginAquisitioncode],
    [OriginAquisitioncode-Text],
    [Itemno],
    [Productsub_group],
    [Itemtype],
    [Productgroup],
    [Productline],
    [Productrange],
    [CRHProductGroupID],
    [Production_Purchase],
    [Stainlesssteelflag],
    [Stainlesssteel-Text],
    [MainProductclass],
    [Productclass],
    [Configno],
    [Pricelistno],
    [Projectno],
    [ProjectPos],
    [Kitheaderno],
    [Bruttosaleslocal],
    [BruttosalesCRHEUR],
    [Brutto2saleslocal],
    [Brutto2salesCRHEUR],
    [Nettosalesposlocal],
    [NettosalesposCRHEUR],
    [Linepercentweighted],
    [Invoicedsaleslocal],
    [InvoicedsalesCRHEUR],
    [Othersaleslocal],
    [OthersalesCRHEUR],
    [Allowanceslocal],
    [AllowancesCRHEUR],
    [Sales100%local],
    [Sales100%CRHEUR],
    [TZlocal],
    [TZCRHEUR],
    [TZpercent],
    [LZlocal],
    [LZCRHEUR],
    [LZpercent],
    [Linediscount1local],
    [Linediscount1CRHEUR],
    [Linediscount1percent],
    [Linediscount2local],
    [Linediscount2CRHEUR],
    [Linediscount2percent],
    [Orderdiscountlocal],
    [OrderdiscountCRHEUR],
    [Orderdiscountpercent],
    [Productsaleslocal],
    [ProductsalesCRHEUR],
    [Plantsellingpricelocal],
    [PlantsellingpriceCRHEUR],
    [ICPlocal],
    [ICPCRHEUR],
    [SMClocal],
    [SMCCRHEUR],
    [SMCsumlocal],
    [SMCsumCRHEUR],
    [Variablesellingcostslocal],
    [VariablesellingcostsCRHEUR],
    [Netsaleslocal],
    [NetsalesCRHEUR],
    [Grossmarginlocal],
    [GrossmarginCRHEUR],
    [contribmarginIIdclocal],
    [contribmarginIIdcCRHEUR],
    [contribmarginIIholocal],
    [contribmarginIIhoCRHEUR],
    [Plantoverheadcostslocal],
    [PlantoverheadcostsCRHEUR],
    [contribmarginIIIlocal],
    [contribmarginIIICRHEUR],
    [Invoicequantity],
    [Orderquantity],
    [Netweight],
    [Freightinvoicedlocal],
    [FreightinvoicedCRHEUR],
    [Tollinvoicedlocal],
    [TollinvoicedCRHEUR],
    [Packingsinvoicedlocal],
    [PackingsinvoicedCRHEUR],
    [Surchargeonshortquantitylocal],
    [SurchargeonshortquantityCRHEUR],
    [Planningcostsinvoicedlocal],
    [PlanningcostsinvoicedCRHEUR],
    [Packingdepositlocal],
    [PackingdepositCRHEUR],
    [Miscellaneousproceedsinvoicedlocal],
    [MiscellaneousproceedsinvoicedCRHEUR],
    [Reservecustomerbonuslocal],
    [ReservecustomerbonusCRHEUR],
    [Warrentieslocal],
    [WarrentiesCRHEUR],
    [Marketingcostsallowanceslocal],
    [MarketingcostsallowancesCRHEUR],
    [Reservecustomerdiscountlocal],
    [ReservecustomerdiscountCRHEUR],
    [Freightcostslocal],
    [FreightcostsCRHEUR],
    [Packingcostslocal],
    [PackingcostsCRHEUR],
    [Dutieslocal],
    [DutiesCRHEUR],
    [Insurancelocal],
    [InsuranceCRHEUR],
    [Commissionslocal],
    [CommissionsCRHEUR],
    [Licenceslocal],
    [LicencesCRHEUR],
    [SMCordinarysteellocal],
    [SMCordinarysteelCRHEUR],
    [SMCstainlesssteellocal],
    [SMCstainlesssteelCRHEUR],
    [SMCotherrawmateriallocal],
    [SMCotherrawmaterialCRHEUR],
    [SMCmaterialoverheadcostslocal],
    [SMCmaterialoverheadcostsCRHEUR],
    [SMCalloysurchargelocal],
    [SMCalloysurchargeCRHEUR],
    [SMCexternalproductioncostslocal],
    [SMCexternalproductioncostsCRHEUR],
    [SMCvariableproductioncostslocal],
    [SMCvariableproductioncostsCRHEUR],
    [SMCfixedproductioncostslocal],
    [SMCfixedproductioncostsCRHEUR],
    [CostsofcapitalE01local],
    [CostsofcapitalE01CRHEUR],
    [WarehousechargesE02local],
    [WarhousechargesE02CRHEUR],
    [HandlingchargesE03local],
    [HandlingchargesE03CRHEUR],
    [PackagingchargesE04local],
    [PackagingchargesE04CRHEUR],
    [PlantoverheadE05local],
    [PlantoverheadE05CRHEUR],
    [E06local],
    [E06CRHEUR],
    [E07local],
    [E07CRHEUR],
    [PlantprofitE08local],
    [PlantprofitE08CRHEUR],
    [ICsurchargeE09local],
    [ICsurchargeE09CRHEUR],
    [FreightsurchargeE10local],
    [FreightsurchargeE10CRHEUR],
    [Freightdctocustomerlocal],
    [FreightdctocustomerCRHEUR],
    [FreightAR_LAtodclocal],
    [FreightAR_LAtodcCRHEUR],
    [FreightPNtoAR_LAlocal],
    [FreightPNtoAR_LACRHEUR],
    [DAN502],
    [DAN503],
    [DAA705],
    [LengthinMper1],
    [LengthinM],
    [Freight_Tollinvoicedlocal],
    [Freight_TollinvoicedCRHEUR],
    [Packaginginvoicedlocal],
    [PackaginginvoicedCRHEUR],
    [Grosssaleslocal],
    [GrosssalesCRHEUR],
    [CostCenter],
    [DAGRWE],
    [CurrencyRatelocaltoCRH1EUR],
    [CurrencyEUR],
    [Currencylocal],
    [Salespersonname],
    [Salesdistrictname],
    [Projectname],
    [Projectdeliverycountry],
    [Projectdeliverycity],
    [Companycountrycode],
    [Companycountryname],
    [DW_Batch],
    [DW_SourceCode],
    [DW_TimeStamp],
    [t_applicationId],
    [t_jobId],
    [t_jobDtm],
    [t_jobBy],
    [t_extractionDtm],
    [t_filePath],
    [LastUpdatedDate],
    [Flg]
)
SELECT 
    [DW_Id],
    [Company],
    [Distributioncompany],
    [Salesarea],
    [Inside_Outside],
    [Inside_Outside-Text],
    [Site],
    [Invoiceno],
    [Invoicedate],
    [Accountingdate],
    [Year],
    [Month],
    [Day],
    [Orderno],
    [Deliveryno],
    [Posno],
    [Orderdate],
    [Deldateplan],
    [Deldateconfirmed],
    [Deldateact],
    [SalesType],
    [Customerno],
    [Country],
    [Postalcode],
    [DlvCountry],
    [DlvState],
    [DlvCounty],
    [Mainsalesperson],
    [Salesperson],
    [Maindistrict],
    [Salesdistrict],
    [Lineofbusiness],
    [Concern],
    [I_E_V],
    [I_E_V-Text],
    [Responsible],
    [Warehouse],
    [Aquisitioncode],
    [Aquisitioncode-Text],
    [Originwarehouse],
    [OriginAquisitioncode],
    [OriginAquisitioncode-Text],
    [Itemno],
    [Productsub_group],
    [Itemtype],
    [Productgroup],
    [Productline],
    [Productrange],
    [CRHProductGroupID],
    [Production_Purchase],
    [Stainlesssteelflag],
    [Stainlesssteel-Text],
    [MainProductclass],
    [Productclass],
    [Configno],
    [Pricelistno],
    [Projectno],
    [ProjectPos],
    [Kitheaderno],
    [Bruttosaleslocal],
    [BruttosalesCRHEUR],
    [Brutto2saleslocal],
    [Brutto2salesCRHEUR],
    [Nettosalesposlocal],
    [NettosalesposCRHEUR],
    [Linepercentweighted],
    [Invoicedsaleslocal],
    [InvoicedsalesCRHEUR],
    [Othersaleslocal],
    [OthersalesCRHEUR],
    [Allowanceslocal],
    [AllowancesCRHEUR],
    [Sales100%local],
    [Sales100%CRHEUR],
    [TZlocal],
    [TZCRHEUR],
    [TZpercent],
    [LZlocal],
    [LZCRHEUR],
    [LZpercent],
    [Linediscount1local],
    [Linediscount1CRHEUR],
    [Linediscount1percent],
    [Linediscount2local],
    [Linediscount2CRHEUR],
    [Linediscount2percent],
    [Orderdiscountlocal],
    [OrderdiscountCRHEUR],
    [Orderdiscountpercent],
    [Productsaleslocal],
    [ProductsalesCRHEUR],
    [Plantsellingpricelocal],
    [PlantsellingpriceCRHEUR],
    [ICPlocal],
    [ICPCRHEUR],
    [SMClocal],
    [SMCCRHEUR],
    [SMCsumlocal],
    [SMCsumCRHEUR],
    [Variablesellingcostslocal],
    [VariablesellingcostsCRHEUR],
    [Netsaleslocal],
    [NetsalesCRHEUR],
    [Grossmarginlocal],
    [GrossmarginCRHEUR],
    [contribmarginIIdclocal],
    [contribmarginIIdcCRHEUR],
    [contribmarginIIholocal],
    [contribmarginIIhoCRHEUR],
    [Plantoverheadcostslocal],
    [PlantoverheadcostsCRHEUR],
    [contribmarginIIIlocal],
    [contribmarginIIICRHEUR],
    [Invoicequantity],
    [Orderquantity],
    [Netweight],
    [Freightinvoicedlocal],
    [FreightinvoicedCRHEUR],
    [Tollinvoicedlocal],
    [TollinvoicedCRHEUR],
    [Packingsinvoicedlocal],
    [PackingsinvoicedCRHEUR],
    [Surchargeonshortquantitylocal],
    [SurchargeonshortquantityCRHEUR],
    [Planningcostsinvoicedlocal],
    [PlanningcostsinvoicedCRHEUR],
    [Packingdepositlocal],
    [PackingdepositCRHEUR],
    [Miscellaneousproceedsinvoicedlocal],
    [MiscellaneousproceedsinvoicedCRHEUR],
    [Reservecustomerbonuslocal],
    [ReservecustomerbonusCRHEUR],
    [Warrentieslocal],
    [WarrentiesCRHEUR],
    [Marketingcostsallowanceslocal],
    [MarketingcostsallowancesCRHEUR],
    [Reservecustomerdiscountlocal],
    [ReservecustomerdiscountCRHEUR],
    [Freightcostslocal],
    [FreightcostsCRHEUR],
    [Packingcostslocal],
    [PackingcostsCRHEUR],
    [Dutieslocal],
    [DutiesCRHEUR],
    [Insurancelocal],
    [InsuranceCRHEUR],
    [Commissionslocal],
    [CommissionsCRHEUR],
    [Licenceslocal],
    [LicencesCRHEUR],
    [SMCordinarysteellocal],
    [SMCordinarysteelCRHEUR],
    [SMCstainlesssteellocal],
    [SMCstainlesssteelCRHEUR],
    [SMCotherrawmateriallocal],
    [SMCotherrawmaterialCRHEUR],
    [SMCmaterialoverheadcostslocal],
    [SMCmaterialoverheadcostsCRHEUR],
    [SMCalloysurchargelocal],
    [SMCalloysurchargeCRHEUR],
    [SMCexternalproductioncostslocal],
    [SMCexternalproductioncostsCRHEUR],
    [SMCvariableproductioncostslocal],
    [SMCvariableproductioncostsCRHEUR],
    [SMCfixedproductioncostslocal],
    [SMCfixedproductioncostsCRHEUR],
    [CostsofcapitalE01local],
    [CostsofcapitalE01CRHEUR],
    [WarehousechargesE02local],
    [WarhousechargesE02CRHEUR],
    [HandlingchargesE03local],
    [HandlingchargesE03CRHEUR],
    [PackagingchargesE04local],
    [PackagingchargesE04CRHEUR],
    [PlantoverheadE05local],
    [PlantoverheadE05CRHEUR],
    [E06local],
    [E06CRHEUR],
    [E07local],
    [E07CRHEUR],
    [PlantprofitE08local],
    [PlantprofitE08CRHEUR],
    [ICsurchargeE09local],
    [ICsurchargeE09CRHEUR],
    [FreightsurchargeE10local],
    [FreightsurchargeE10CRHEUR],
    [Freightdctocustomerlocal],
    [FreightdctocustomerCRHEUR],
    [FreightAR_LAtodclocal],
    [FreightAR_LAtodcCRHEUR],
    [FreightPNtoAR_LAlocal],
    [FreightPNtoAR_LACRHEUR],
    [DAN502],
    [DAN503],
    [DAA705],
    [LengthinMper1],
    [LengthinM],
    [Freight_Tollinvoicedlocal],
    [Freight_TollinvoicedCRHEUR],
    [Packaginginvoicedlocal],
    [PackaginginvoicedCRHEUR],
    [Grosssaleslocal],
    [GrosssalesCRHEUR],
    [CostCenter],
    [DAGRWE],
    [CurrencyRatelocaltoCRH1EUR],
    [CurrencyEUR],
    [Currencylocal],
    [Salespersonname],
    [Salesdistrictname],
    [Projectname],
    [Projectdeliverycountry],
    [Projectdeliverycity],
    [Companycountrycode],
    [Companycountryname],
    [DW_Batch],
    [DW_SourceCode],
    [DW_TimeStamp],
    [t_applicationId],
    [t_jobId],
    [t_jobDtm],
    [t_jobBy],
    [t_extractionDtm],
    [t_filePath],
    GETDATE(),
    'I'
FROM
    [pgr].[FACT_HGDAWA_delta]
WHERE
    Flg='I'

-- Updates For Updates Marked
UPDATE dest
SET
    dest.[DW_Id] = src.[DW_Id],
    dest.[Company] = src.[Company],
    dest.[Distributioncompany] = src.[Distributioncompany],
    dest.[Salesarea] = src.[Salesarea],
    dest.[Inside_Outside] = src.[Inside_Outside],
    dest.[Inside_Outside-Text] = src.[Inside_Outside-Text],
    dest.[Site] = src.[Site],
    -- dest.[Invoiceno] = src.[Invoiceno],
    dest.[Invoicedate] = src.[Invoicedate],
    dest.[Accountingdate] = src.[Accountingdate],
    dest.[Year] = src.[Year],
    dest.[Month] = src.[Month],
    dest.[Day] = src.[Day],
    dest.[Orderno] = src.[Orderno],
    dest.[Deliveryno] = src.[Deliveryno],
    -- dest.[Posno] = src.[Posno],
    dest.[Orderdate] = src.[Orderdate],
    dest.[Deldateplan] = src.[Deldateplan],
    dest.[Deldateconfirmed] = src.[Deldateconfirmed],
    dest.[Deldateact] = src.[Deldateact],
    dest.[SalesType] = src.[SalesType],
    dest.[Customerno] = src.[Customerno],
    dest.[Country] = src.[Country],
    dest.[Postalcode] = src.[Postalcode],
    dest.[DlvCountry] = src.[DlvCountry],
    dest.[DlvState] = src.[DlvState],
    dest.[DlvCounty] = src.[DlvCounty],
    dest.[Mainsalesperson] = src.[Mainsalesperson],
    dest.[Salesperson] = src.[Salesperson],
    dest.[Maindistrict] = src.[Maindistrict],
    dest.[Salesdistrict] = src.[Salesdistrict],
    dest.[Lineofbusiness] = src.[Lineofbusiness],
    dest.[Concern] = src.[Concern],
    dest.[I_E_V] = src.[I_E_V],
    dest.[I_E_V-Text] = src.[I_E_V-Text],
    dest.[Responsible] = src.[Responsible],
    dest.[Warehouse] = src.[Warehouse],
    dest.[Aquisitioncode] = src.[Aquisitioncode],
    dest.[Aquisitioncode-Text] = src.[Aquisitioncode-Text],
    dest.[Originwarehouse] = src.[Originwarehouse],
    dest.[OriginAquisitioncode] = src.[OriginAquisitioncode],
    dest.[OriginAquisitioncode-Text] = src.[OriginAquisitioncode-Text],
    dest.[Itemno] = src.[Itemno],
    dest.[Productsub_group] = src.[Productsub_group],
    dest.[Itemtype] = src.[Itemtype],
    dest.[Productgroup] = src.[Productgroup],
    dest.[Productline] = src.[Productline],
    dest.[Productrange] = src.[Productrange],
    dest.[CRHProductGroupID] = src.[CRHProductGroupID],
    dest.[Production_Purchase] = src.[Production_Purchase],
    dest.[Stainlesssteelflag] = src.[Stainlesssteelflag],
    dest.[Stainlesssteel-Text] = src.[Stainlesssteel-Text],
    dest.[MainProductclass] = src.[MainProductclass],
    dest.[Productclass] = src.[Productclass],
    dest.[Configno] = src.[Configno],
    dest.[Pricelistno] = src.[Pricelistno],
    dest.[Projectno] = src.[Projectno],
    dest.[ProjectPos] = src.[ProjectPos],
    dest.[Kitheaderno] = src.[Kitheaderno],
    dest.[Bruttosaleslocal] = src.[Bruttosaleslocal],
    dest.[BruttosalesCRHEUR] = src.[BruttosalesCRHEUR],
    dest.[Brutto2saleslocal] = src.[Brutto2saleslocal],
    dest.[Brutto2salesCRHEUR] = src.[Brutto2salesCRHEUR],
    dest.[Nettosalesposlocal] = src.[Nettosalesposlocal],
    dest.[NettosalesposCRHEUR] = src.[NettosalesposCRHEUR],
    dest.[Linepercentweighted] = src.[Linepercentweighted],
    dest.[Invoicedsaleslocal] = src.[Invoicedsaleslocal],
    dest.[InvoicedsalesCRHEUR] = src.[InvoicedsalesCRHEUR],
    dest.[Othersaleslocal] = src.[Othersaleslocal],
    dest.[OthersalesCRHEUR] = src.[OthersalesCRHEUR],
    dest.[Allowanceslocal] = src.[Allowanceslocal],
    dest.[AllowancesCRHEUR] = src.[AllowancesCRHEUR],
    dest.[Sales100%local] = src.[Sales100%local],
    dest.[Sales100%CRHEUR] = src.[Sales100%CRHEUR],
    dest.[TZlocal] = src.[TZlocal],
    dest.[TZCRHEUR] = src.[TZCRHEUR],
    dest.[TZpercent] = src.[TZpercent],
    dest.[LZlocal] = src.[LZlocal],
    dest.[LZCRHEUR] = src.[LZCRHEUR],
    dest.[LZpercent] = src.[LZpercent],
    dest.[Linediscount1local] = src.[Linediscount1local],
    dest.[Linediscount1CRHEUR] = src.[Linediscount1CRHEUR],
    dest.[Linediscount1percent] = src.[Linediscount1percent],
    dest.[Linediscount2local] = src.[Linediscount2local],
    dest.[Linediscount2CRHEUR] = src.[Linediscount2CRHEUR],
    dest.[Linediscount2percent] = src.[Linediscount2percent],
    dest.[Orderdiscountlocal] = src.[Orderdiscountlocal],
    dest.[OrderdiscountCRHEUR] = src.[OrderdiscountCRHEUR],
    dest.[Orderdiscountpercent] = src.[Orderdiscountpercent],
    dest.[Productsaleslocal] = src.[Productsaleslocal],
    dest.[ProductsalesCRHEUR] = src.[ProductsalesCRHEUR],
    dest.[Plantsellingpricelocal] = src.[Plantsellingpricelocal],
    dest.[PlantsellingpriceCRHEUR] = src.[PlantsellingpriceCRHEUR],
    dest.[ICPlocal] = src.[ICPlocal],
    dest.[ICPCRHEUR] = src.[ICPCRHEUR],
    dest.[SMClocal] = src.[SMClocal],
    dest.[SMCCRHEUR] = src.[SMCCRHEUR],
    dest.[SMCsumlocal] = src.[SMCsumlocal],
    dest.[SMCsumCRHEUR] = src.[SMCsumCRHEUR],
    dest.[Variablesellingcostslocal] = src.[Variablesellingcostslocal],
    dest.[VariablesellingcostsCRHEUR] = src.[VariablesellingcostsCRHEUR],
    dest.[Netsaleslocal] = src.[Netsaleslocal],
    dest.[NetsalesCRHEUR] = src.[NetsalesCRHEUR],
    dest.[Grossmarginlocal] = src.[Grossmarginlocal],
    dest.[GrossmarginCRHEUR] = src.[GrossmarginCRHEUR],
    dest.[contribmarginIIdclocal] = src.[contribmarginIIdclocal],
    dest.[contribmarginIIdcCRHEUR] = src.[contribmarginIIdcCRHEUR],
    dest.[contribmarginIIholocal] = src.[contribmarginIIholocal],
    dest.[contribmarginIIhoCRHEUR] = src.[contribmarginIIhoCRHEUR],
    dest.[Plantoverheadcostslocal] = src.[Plantoverheadcostslocal],
    dest.[PlantoverheadcostsCRHEUR] = src.[PlantoverheadcostsCRHEUR],
    dest.[contribmarginIIIlocal] = src.[contribmarginIIIlocal],
    dest.[contribmarginIIICRHEUR] = src.[contribmarginIIICRHEUR],
    dest.[Invoicequantity] = src.[Invoicequantity],
    dest.[Orderquantity] = src.[Orderquantity],
    dest.[Netweight] = src.[Netweight],
    dest.[Freightinvoicedlocal] = src.[Freightinvoicedlocal],
    dest.[FreightinvoicedCRHEUR] = src.[FreightinvoicedCRHEUR],
    dest.[Tollinvoicedlocal] = src.[Tollinvoicedlocal],
    dest.[TollinvoicedCRHEUR] = src.[TollinvoicedCRHEUR],
    dest.[Packingsinvoicedlocal] = src.[Packingsinvoicedlocal],
    dest.[PackingsinvoicedCRHEUR] = src.[PackingsinvoicedCRHEUR],
    dest.[Surchargeonshortquantitylocal] = src.[Surchargeonshortquantitylocal],
    dest.[SurchargeonshortquantityCRHEUR] = src.[SurchargeonshortquantityCRHEUR],
    dest.[Planningcostsinvoicedlocal] = src.[Planningcostsinvoicedlocal],
    dest.[PlanningcostsinvoicedCRHEUR] = src.[PlanningcostsinvoicedCRHEUR],
    dest.[Packingdepositlocal] = src.[Packingdepositlocal],
    dest.[PackingdepositCRHEUR] = src.[PackingdepositCRHEUR],
    dest.[Miscellaneousproceedsinvoicedlocal] = src.[Miscellaneousproceedsinvoicedlocal],
    dest.[MiscellaneousproceedsinvoicedCRHEUR] = src.[MiscellaneousproceedsinvoicedCRHEUR],
    dest.[Reservecustomerbonuslocal] = src.[Reservecustomerbonuslocal],
    dest.[ReservecustomerbonusCRHEUR] = src.[ReservecustomerbonusCRHEUR],
    dest.[Warrentieslocal] = src.[Warrentieslocal],
    dest.[WarrentiesCRHEUR] = src.[WarrentiesCRHEUR],
    dest.[Marketingcostsallowanceslocal] = src.[Marketingcostsallowanceslocal],
    dest.[MarketingcostsallowancesCRHEUR] = src.[MarketingcostsallowancesCRHEUR],
    dest.[Reservecustomerdiscountlocal] = src.[Reservecustomerdiscountlocal],
    dest.[ReservecustomerdiscountCRHEUR] = src.[ReservecustomerdiscountCRHEUR],
    dest.[Freightcostslocal] = src.[Freightcostslocal],
    dest.[FreightcostsCRHEUR] = src.[FreightcostsCRHEUR],
    dest.[Packingcostslocal] = src.[Packingcostslocal],
    dest.[PackingcostsCRHEUR] = src.[PackingcostsCRHEUR],
    dest.[Dutieslocal] = src.[Dutieslocal],
    dest.[DutiesCRHEUR] = src.[DutiesCRHEUR],
    dest.[Insurancelocal] = src.[Insurancelocal],
    dest.[InsuranceCRHEUR] = src.[InsuranceCRHEUR],
    dest.[Commissionslocal] = src.[Commissionslocal],
    dest.[CommissionsCRHEUR] = src.[CommissionsCRHEUR],
    dest.[Licenceslocal] = src.[Licenceslocal],
    dest.[LicencesCRHEUR] = src.[LicencesCRHEUR],
    dest.[SMCordinarysteellocal] = src.[SMCordinarysteellocal],
    dest.[SMCordinarysteelCRHEUR] = src.[SMCordinarysteelCRHEUR],
    dest.[SMCstainlesssteellocal] = src.[SMCstainlesssteellocal],
    dest.[SMCstainlesssteelCRHEUR] = src.[SMCstainlesssteelCRHEUR],
    dest.[SMCotherrawmateriallocal] = src.[SMCotherrawmateriallocal],
    dest.[SMCotherrawmaterialCRHEUR] = src.[SMCotherrawmaterialCRHEUR],
    dest.[SMCmaterialoverheadcostslocal] = src.[SMCmaterialoverheadcostslocal],
    dest.[SMCmaterialoverheadcostsCRHEUR] = src.[SMCmaterialoverheadcostsCRHEUR],
    dest.[SMCalloysurchargelocal] = src.[SMCalloysurchargelocal],
    dest.[SMCalloysurchargeCRHEUR] = src.[SMCalloysurchargeCRHEUR],
    dest.[SMCexternalproductioncostslocal] = src.[SMCexternalproductioncostslocal],
    dest.[SMCexternalproductioncostsCRHEUR] = src.[SMCexternalproductioncostsCRHEUR],
    dest.[SMCvariableproductioncostslocal] = src.[SMCvariableproductioncostslocal],
    dest.[SMCvariableproductioncostsCRHEUR] = src.[SMCvariableproductioncostsCRHEUR],
    dest.[SMCfixedproductioncostslocal] = src.[SMCfixedproductioncostslocal],
    dest.[SMCfixedproductioncostsCRHEUR] = src.[SMCfixedproductioncostsCRHEUR],
    dest.[CostsofcapitalE01local] = src.[CostsofcapitalE01local],
    dest.[CostsofcapitalE01CRHEUR] = src.[CostsofcapitalE01CRHEUR],
    dest.[WarehousechargesE02local] = src.[WarehousechargesE02local],
    dest.[WarhousechargesE02CRHEUR] = src.[WarhousechargesE02CRHEUR],
    dest.[HandlingchargesE03local] = src.[HandlingchargesE03local],
    dest.[HandlingchargesE03CRHEUR] = src.[HandlingchargesE03CRHEUR],
    dest.[PackagingchargesE04local] = src.[PackagingchargesE04local],
    dest.[PackagingchargesE04CRHEUR] = src.[PackagingchargesE04CRHEUR],
    dest.[PlantoverheadE05local] = src.[PlantoverheadE05local],
    dest.[PlantoverheadE05CRHEUR] = src.[PlantoverheadE05CRHEUR],
    dest.[E06local] = src.[E06local],
    dest.[E06CRHEUR] = src.[E06CRHEUR],
    dest.[E07local] = src.[E07local],
    dest.[E07CRHEUR] = src.[E07CRHEUR],
    dest.[PlantprofitE08local] = src.[PlantprofitE08local],
    dest.[PlantprofitE08CRHEUR] = src.[PlantprofitE08CRHEUR],
    dest.[ICsurchargeE09local] = src.[ICsurchargeE09local],
    dest.[ICsurchargeE09CRHEUR] = src.[ICsurchargeE09CRHEUR],
    dest.[FreightsurchargeE10local] = src.[FreightsurchargeE10local],
    dest.[FreightsurchargeE10CRHEUR] = src.[FreightsurchargeE10CRHEUR],
    dest.[Freightdctocustomerlocal] = src.[Freightdctocustomerlocal],
    dest.[FreightdctocustomerCRHEUR] = src.[FreightdctocustomerCRHEUR],
    dest.[FreightAR_LAtodclocal] = src.[FreightAR_LAtodclocal],
    dest.[FreightAR_LAtodcCRHEUR] = src.[FreightAR_LAtodcCRHEUR],
    dest.[FreightPNtoAR_LAlocal] = src.[FreightPNtoAR_LAlocal],
    dest.[FreightPNtoAR_LACRHEUR] = src.[FreightPNtoAR_LACRHEUR],
    dest.[DAN502] = src.[DAN502],
    dest.[DAN503] = src.[DAN503],
    dest.[DAA705] = src.[DAA705],
    dest.[LengthinMper1] = src.[LengthinMper1],
    dest.[LengthinM] = src.[LengthinM],
    dest.[Freight_Tollinvoicedlocal] = src.[Freight_Tollinvoicedlocal],
    dest.[Freight_TollinvoicedCRHEUR] = src.[Freight_TollinvoicedCRHEUR],
    dest.[Packaginginvoicedlocal] = src.[Packaginginvoicedlocal],
    dest.[PackaginginvoicedCRHEUR] = src.[PackaginginvoicedCRHEUR],
    dest.[Grosssaleslocal] = src.[Grosssaleslocal],
    dest.[GrosssalesCRHEUR] = src.[GrosssalesCRHEUR],
    dest.[CostCenter] = src.[CostCenter],
    dest.[DAGRWE] = src.[DAGRWE],
    dest.[CurrencyRatelocaltoCRH1EUR] = src.[CurrencyRatelocaltoCRH1EUR],
    dest.[CurrencyEUR] = src.[CurrencyEUR],
    dest.[Currencylocal] = src.[Currencylocal],
    dest.[Salespersonname] = src.[Salespersonname],
    dest.[Salesdistrictname] = src.[Salesdistrictname],
    dest.[Projectname] = src.[Projectname],
    dest.[Projectdeliverycountry] = src.[Projectdeliverycountry],
    dest.[Projectdeliverycity] = src.[Projectdeliverycity],
    dest.[Companycountrycode] = src.[Companycountrycode],
    dest.[Companycountryname] = src.[Companycountryname],
    dest.[DW_Batch] = src.[DW_Batch],
    dest.[DW_SourceCode] = src.[DW_SourceCode],
    dest.[DW_TimeStamp] = src.[DW_TimeStamp],
    dest.[t_applicationId] = src.[t_applicationId],
    dest.[t_jobId] = src.[t_jobId],
    dest.[t_jobDtm] = src.[t_jobDtm],
    dest.[t_jobBy] = src.[t_jobBy],
    dest.[t_extractionDtm] = src.[t_extractionDtm],
    dest.[t_filePath] = src.[t_filePath],
    dest.[LastUpdatedDate] = GETDATE(),
    dest.[Flg] = 'U'		
FROM
    [pgr].[FACT_HGDAWA_] AS dest  
INNER JOIN
    [pgr].[FACT_HGDAWA_delta] AS src
    ON
        src.[Invoiceno] = dest.[Invoiceno]
        AND
        src.[Posno] = dest.[Posno]
WHERE
    src.Flg='U'

-- For Deletes
-- TODO this is already done as deletes are defined directly on destination
-- UPDATE
--     dest
-- SET
--     dest.[LastUpdatedDate] = GETDATE(),
--     dest.[Flg] = 'D'		
-- FROM
--     [pgr].[FACT_HGDAWA_] AS dest  
-- INNER JOIN
--     [pgr].[FACT_HGDAWA_delta] AS src
-- ON
--     src.[Invoiceno] = dest.[Invoiceno]
--     AND
--     src.[Posno] = dest.[Posno]
-- WHERE src.Flg='D'