-- SELECT From Parquet file(FuLL File) in the DataLake directly
-- Need to correctly mount and see appropriate access are granted for Synapse to do this.
-- We might have to check if this is Okay and gives no issues in checksums/ Create External table first alternatively.

--SELECT
--    TOP 100 *
--FROM
--    OPENROWSET(
--        BULK 'https://stxxxxslsdeuw001.dfs.core.windows.net/tx-ca-0-hlp-uat/CUSTINVOICETRANS/Out/2022/07/13/CUSTINVOICETRANS_2022_07_13_14_27_23_820.parquet',
--        FORMAT = 'PARQUET'
--    ) AS [result]

-- GENERATING DELTA
-- [pgr].[FACT_HGDAWA_delta]  is the source(External) table and [pgr].[FACT_HGDAWA_] is the Destination Table.
-- Edgecases where checksum might not be effective can be found in the below article.
-- https://docs.microsoft.com/en-us/sql/t-sql/functions/checksum-transact-sql?view=sql-server-ver16
-- Notice Checksum is not a persisted value any more hence no column to hold checksum column
-- Only the Fact table/Dim Table will have an additional columns 
		--LastUpdatedDate - Touch date for the record
		--Flg - I(Insert),U(Update),D(Soft Delete)
-- Base Table/Source table to have a flag for convinience and to enable simple debugging 
		--Flg (Lookup Flag) To denote if a source record has to be updated/inserted or deleted at its destination. 

-- Mark Updates (ExecTime 13s, updated 4712 records of 25M)

select top(100) *
from [pgr].[FACT_HGDAWA_active] 

--Merge statements with a WHEN NOT MATCHED [BY TARGET] clause must target a hash distributed table.
MERGE
    [pgr].[FACT_HGDAWA_active] AS dest
USING (
    SELECT
        [DW_Id],
        [Company],
        [Distributioncompany],
        [Salesarea],
        [Inside_Outside],
        [Inside_Outside-Text],
        [Site],
        [Invoiceno],
        [Invoicedate],
        [Accountingdate],
        [Year],
        [Month],
        [Day],
        [Orderno],
        [Deliveryno],
        [Posno],
        [Orderdate],
        [Deldateplan],
        [Deldateconfirmed],
        [Deldateact],
        [SalesType],
        [Customerno],
        [Country],
        [Postalcode],
        [DlvCountry],
        [DlvState],
        [DlvCounty],
        [Mainsalesperson],
        [Salesperson],
        [Maindistrict],
        [Salesdistrict],
        [Lineofbusiness],
        [Concern],
        [I_E_V],
        [I_E_V-Text],
        [Responsible],
        [Warehouse],
        [Aquisitioncode],
        [Aquisitioncode-Text],
        [Originwarehouse],
        [OriginAquisitioncode],
        [OriginAquisitioncode-Text],
        [Itemno],
        [Productsub_group],
        [Itemtype],
        [Productgroup],
        [Productline],
        [Productrange],
        [CRHProductGroupID],
        [Production_Purchase],
        [Stainlesssteelflag],
        [Stainlesssteel-Text],
        [MainProductclass],
        [Productclass],
        [Configno],
        [Pricelistno],
        [Projectno],
        [ProjectPos],
        [Kitheaderno],
        [Bruttosaleslocal],
        [BruttosalesCRHEUR],
        [Brutto2saleslocal],
        [Brutto2salesCRHEUR],
        [Nettosalesposlocal],
        [NettosalesposCRHEUR],
        [Linepercentweighted],
        [Invoicedsaleslocal],
        [InvoicedsalesCRHEUR],
        [Othersaleslocal],
        [OthersalesCRHEUR],
        [Allowanceslocal],
        [AllowancesCRHEUR],
        [Sales100%local],
        [Sales100%CRHEUR],
        [TZlocal],
        [TZCRHEUR],
        [TZpercent],
        [LZlocal],
        [LZCRHEUR],
        [LZpercent],
        [Linediscount1local],
        [Linediscount1CRHEUR],
        [Linediscount1percent],
        [Linediscount2local],
        [Linediscount2CRHEUR],
        [Linediscount2percent],
        [Orderdiscountlocal],
        [OrderdiscountCRHEUR],
        [Orderdiscountpercent],
        [Productsaleslocal],
        [ProductsalesCRHEUR],
        [Plantsellingpricelocal],
        [PlantsellingpriceCRHEUR],
        [ICPlocal],
        [ICPCRHEUR],
        [SMClocal],
        [SMCCRHEUR],
        [SMCsumlocal],
        [SMCsumCRHEUR],
        [Variablesellingcostslocal],
        [VariablesellingcostsCRHEUR],
        [Netsaleslocal],
        [NetsalesCRHEUR],
        [Grossmarginlocal],
        [GrossmarginCRHEUR],
        [contribmarginIIdclocal],
        [contribmarginIIdcCRHEUR],
        [contribmarginIIholocal],
        [contribmarginIIhoCRHEUR],
        [Plantoverheadcostslocal],
        [PlantoverheadcostsCRHEUR],
        [contribmarginIIIlocal],
        [contribmarginIIICRHEUR],
        [Invoicequantity],
        [Orderquantity],
        [Netweight],
        [Freightinvoicedlocal],
        [FreightinvoicedCRHEUR],
        [Tollinvoicedlocal],
        [TollinvoicedCRHEUR],
        [Packingsinvoicedlocal],
        [PackingsinvoicedCRHEUR],
        [Surchargeonshortquantitylocal],
        [SurchargeonshortquantityCRHEUR],
        [Planningcostsinvoicedlocal],
        [PlanningcostsinvoicedCRHEUR],
        [Packingdepositlocal],
        [PackingdepositCRHEUR],
        [Miscellaneousproceedsinvoicedlocal],
        [MiscellaneousproceedsinvoicedCRHEUR],
        [Reservecustomerbonuslocal],
        [ReservecustomerbonusCRHEUR],
        [Warrentieslocal],
        [WarrentiesCRHEUR],
        [Marketingcostsallowanceslocal],
        [MarketingcostsallowancesCRHEUR],
        [Reservecustomerdiscountlocal],
        [ReservecustomerdiscountCRHEUR],
        [Freightcostslocal],
        [FreightcostsCRHEUR],
        [Packingcostslocal],
        [PackingcostsCRHEUR],
        [Dutieslocal],
        [DutiesCRHEUR],
        [Insurancelocal],
        [InsuranceCRHEUR],
        [Commissionslocal],
        [CommissionsCRHEUR],
        [Licenceslocal],
        [LicencesCRHEUR],
        [SMCordinarysteellocal],
        [SMCordinarysteelCRHEUR],
        [SMCstainlesssteellocal],
        [SMCstainlesssteelCRHEUR],
        [SMCotherrawmateriallocal],
        [SMCotherrawmaterialCRHEUR],
        [SMCmaterialoverheadcostslocal],
        [SMCmaterialoverheadcostsCRHEUR],
        [SMCalloysurchargelocal],
        [SMCalloysurchargeCRHEUR],
        [SMCexternalproductioncostslocal],
        [SMCexternalproductioncostsCRHEUR],
        [SMCvariableproductioncostslocal],
        [SMCvariableproductioncostsCRHEUR],
        [SMCfixedproductioncostslocal],
        [SMCfixedproductioncostsCRHEUR],
        [CostsofcapitalE01local],
        [CostsofcapitalE01CRHEUR],
        [WarehousechargesE02local],
        [WarhousechargesE02CRHEUR],
        [HandlingchargesE03local],
        [HandlingchargesE03CRHEUR],
        [PackagingchargesE04local],
        [PackagingchargesE04CRHEUR],
        [PlantoverheadE05local],
        [PlantoverheadE05CRHEUR],
        [E06local],
        [E06CRHEUR],
        [E07local],
        [E07CRHEUR],
        [PlantprofitE08local],
        [PlantprofitE08CRHEUR],
        [ICsurchargeE09local],
        [ICsurchargeE09CRHEUR],
        [FreightsurchargeE10local],
        [FreightsurchargeE10CRHEUR],
        [Freightdctocustomerlocal],
        [FreightdctocustomerCRHEUR],
        [FreightAR_LAtodclocal],
        [FreightAR_LAtodcCRHEUR],
        [FreightPNtoAR_LAlocal],
        [FreightPNtoAR_LACRHEUR],
        [DAN502],
        [DAN503],
        [DAA705],
        [LengthinMper1],
        [LengthinM],
        [Freight_Tollinvoicedlocal],
        [Freight_TollinvoicedCRHEUR],
        [Packaginginvoicedlocal],
        [PackaginginvoicedCRHEUR],
        [Grosssaleslocal],
        [GrosssalesCRHEUR],
        [CostCenter],
        [DAGRWE],
        [CurrencyRatelocaltoCRH1EUR],
        [CurrencyEUR],
        [Currencylocal],
        [Salespersonname],
        [Salesdistrictname],
        [Projectname],
        [Projectdeliverycountry],
        [Projectdeliverycity],
        [Companycountrycode],
        [Companycountryname],
        [DW_Batch],
        [DW_SourceCode],
        [DW_TimeStamp],
        [t_applicationId],
        [t_jobId],
        [t_jobDtm],
        [t_jobBy],
        [t_extractionDtm],
        [t_filePath]
    FROM
        [pgr].[FACT_HGDAWA_new]
    -- GROUP BY
    --     Invoiceno,
    --     Posno
) AS new (
    [DW_Id],
    [Company],
    [Distributioncompany],
    [Salesarea],
    [Inside_Outside],
    [Inside_Outside-Text],
    [Site],
    [Invoiceno],
    [Invoicedate],
    [Accountingdate],
    [Year],
    [Month],
    [Day],
    [Orderno],
    [Deliveryno],
    [Posno],
    [Orderdate],
    [Deldateplan],
    [Deldateconfirmed],
    [Deldateact],
    [SalesType],
    [Customerno],
    [Country],
    [Postalcode],
    [DlvCountry],
    [DlvState],
    [DlvCounty],
    [Mainsalesperson],
    [Salesperson],
    [Maindistrict],
    [Salesdistrict],
    [Lineofbusiness],
    [Concern],
    [I_E_V],
    [I_E_V-Text],
    [Responsible],
    [Warehouse],
    [Aquisitioncode],
    [Aquisitioncode-Text],
    [Originwarehouse],
    [OriginAquisitioncode],
    [OriginAquisitioncode-Text],
    [Itemno],
    [Productsub_group],
    [Itemtype],
    [Productgroup],
    [Productline],
    [Productrange],
    [CRHProductGroupID],
    [Production_Purchase],
    [Stainlesssteelflag],
    [Stainlesssteel-Text],
    [MainProductclass],
    [Productclass],
    [Configno],
    [Pricelistno],
    [Projectno],
    [ProjectPos],
    [Kitheaderno],
    [Bruttosaleslocal],
    [BruttosalesCRHEUR],
    [Brutto2saleslocal],
    [Brutto2salesCRHEUR],
    [Nettosalesposlocal],
    [NettosalesposCRHEUR],
    [Linepercentweighted],
    [Invoicedsaleslocal],
    [InvoicedsalesCRHEUR],
    [Othersaleslocal],
    [OthersalesCRHEUR],
    [Allowanceslocal],
    [AllowancesCRHEUR],
    [Sales100%local],
    [Sales100%CRHEUR],
    [TZlocal],
    [TZCRHEUR],
    [TZpercent],
    [LZlocal],
    [LZCRHEUR],
    [LZpercent],
    [Linediscount1local],
    [Linediscount1CRHEUR],
    [Linediscount1percent],
    [Linediscount2local],
    [Linediscount2CRHEUR],
    [Linediscount2percent],
    [Orderdiscountlocal],
    [OrderdiscountCRHEUR],
    [Orderdiscountpercent],
    [Productsaleslocal],
    [ProductsalesCRHEUR],
    [Plantsellingpricelocal],
    [PlantsellingpriceCRHEUR],
    [ICPlocal],
    [ICPCRHEUR],
    [SMClocal],
    [SMCCRHEUR],
    [SMCsumlocal],
    [SMCsumCRHEUR],
    [Variablesellingcostslocal],
    [VariablesellingcostsCRHEUR],
    [Netsaleslocal],
    [NetsalesCRHEUR],
    [Grossmarginlocal],
    [GrossmarginCRHEUR],
    [contribmarginIIdclocal],
    [contribmarginIIdcCRHEUR],
    [contribmarginIIholocal],
    [contribmarginIIhoCRHEUR],
    [Plantoverheadcostslocal],
    [PlantoverheadcostsCRHEUR],
    [contribmarginIIIlocal],
    [contribmarginIIICRHEUR],
    [Invoicequantity],
    [Orderquantity],
    [Netweight],
    [Freightinvoicedlocal],
    [FreightinvoicedCRHEUR],
    [Tollinvoicedlocal],
    [TollinvoicedCRHEUR],
    [Packingsinvoicedlocal],
    [PackingsinvoicedCRHEUR],
    [Surchargeonshortquantitylocal],
    [SurchargeonshortquantityCRHEUR],
    [Planningcostsinvoicedlocal],
    [PlanningcostsinvoicedCRHEUR],
    [Packingdepositlocal],
    [PackingdepositCRHEUR],
    [Miscellaneousproceedsinvoicedlocal],
    [MiscellaneousproceedsinvoicedCRHEUR],
    [Reservecustomerbonuslocal],
    [ReservecustomerbonusCRHEUR],
    [Warrentieslocal],
    [WarrentiesCRHEUR],
    [Marketingcostsallowanceslocal],
    [MarketingcostsallowancesCRHEUR],
    [Reservecustomerdiscountlocal],
    [ReservecustomerdiscountCRHEUR],
    [Freightcostslocal],
    [FreightcostsCRHEUR],
    [Packingcostslocal],
    [PackingcostsCRHEUR],
    [Dutieslocal],
    [DutiesCRHEUR],
    [Insurancelocal],
    [InsuranceCRHEUR],
    [Commissionslocal],
    [CommissionsCRHEUR],
    [Licenceslocal],
    [LicencesCRHEUR],
    [SMCordinarysteellocal],
    [SMCordinarysteelCRHEUR],
    [SMCstainlesssteellocal],
    [SMCstainlesssteelCRHEUR],
    [SMCotherrawmateriallocal],
    [SMCotherrawmaterialCRHEUR],
    [SMCmaterialoverheadcostslocal],
    [SMCmaterialoverheadcostsCRHEUR],
    [SMCalloysurchargelocal],
    [SMCalloysurchargeCRHEUR],
    [SMCexternalproductioncostslocal],
    [SMCexternalproductioncostsCRHEUR],
    [SMCvariableproductioncostslocal],
    [SMCvariableproductioncostsCRHEUR],
    [SMCfixedproductioncostslocal],
    [SMCfixedproductioncostsCRHEUR],
    [CostsofcapitalE01local],
    [CostsofcapitalE01CRHEUR],
    [WarehousechargesE02local],
    [WarhousechargesE02CRHEUR],
    [HandlingchargesE03local],
    [HandlingchargesE03CRHEUR],
    [PackagingchargesE04local],
    [PackagingchargesE04CRHEUR],
    [PlantoverheadE05local],
    [PlantoverheadE05CRHEUR],
    [E06local],
    [E06CRHEUR],
    [E07local],
    [E07CRHEUR],
    [PlantprofitE08local],
    [PlantprofitE08CRHEUR],
    [ICsurchargeE09local],
    [ICsurchargeE09CRHEUR],
    [FreightsurchargeE10local],
    [FreightsurchargeE10CRHEUR],
    [Freightdctocustomerlocal],
    [FreightdctocustomerCRHEUR],
    [FreightAR_LAtodclocal],
    [FreightAR_LAtodcCRHEUR],
    [FreightPNtoAR_LAlocal],
    [FreightPNtoAR_LACRHEUR],
    [DAN502],
    [DAN503],
    [DAA705],
    [LengthinMper1],
    [LengthinM],
    [Freight_Tollinvoicedlocal],
    [Freight_TollinvoicedCRHEUR],
    [Packaginginvoicedlocal],
    [PackaginginvoicedCRHEUR],
    [Grosssaleslocal],
    [GrosssalesCRHEUR],
    [CostCenter],
    [DAGRWE],
    [CurrencyRatelocaltoCRH1EUR],
    [CurrencyEUR],
    [Currencylocal],
    [Salespersonname],
    [Salesdistrictname],
    [Projectname],
    [Projectdeliverycountry],
    [Projectdeliverycity],
    [Companycountrycode],
    [Companycountryname],
    [DW_Batch],
    [DW_SourceCode],
    [DW_TimeStamp],
    [t_applicationId],
    [t_jobId],
    [t_jobDtm],
    [t_jobBy],
    [t_extractionDtm],
    [t_filePath]
)
ON (
    new.[Invoiceno] = dest.[Invoiceno]
    AND
    new.[Posno] = dest.[Posno]
)
WHEN MATCHED THEN
    UPDATE SET
        dest.[DW_Id] = new.[DW_Id],
        dest.[Company] = new.[Company],
        dest.[Distributioncompany] = new.[Distributioncompany],
        dest.[Salesarea] = new.[Salesarea],
        dest.[Inside_Outside] = new.[Inside_Outside],
        dest.[Inside_Outside-Text] = new.[Inside_Outside-Text],
        dest.[Site] = new.[Site],
        -- dest.[Invoiceno] = new.[Invoiceno],
        dest.[Invoicedate] = new.[Invoicedate],
        dest.[Accountingdate] = new.[Accountingdate],
        dest.[Year] = new.[Year],
        dest.[Month] = new.[Month],
        dest.[Day] = new.[Day],
        dest.[Orderno] = new.[Orderno],
        dest.[Deliveryno] = new.[Deliveryno],
        -- dest.[Posno] = new.[Posno],
        dest.[Orderdate] = new.[Orderdate],
        dest.[Deldateplan] = new.[Deldateplan],
        dest.[Deldateconfirmed] = new.[Deldateconfirmed],
        dest.[Deldateact] = new.[Deldateact],
        dest.[SalesType] = new.[SalesType],
        dest.[Customerno] = new.[Customerno],
        dest.[Country] = new.[Country],
        dest.[Postalcode] = new.[Postalcode],
        dest.[DlvCountry] = new.[DlvCountry],
        dest.[DlvState] = new.[DlvState],
        dest.[DlvCounty] = new.[DlvCounty],
        dest.[Mainsalesperson] = new.[Mainsalesperson],
        dest.[Salesperson] = new.[Salesperson],
        dest.[Maindistrict] = new.[Maindistrict],
        dest.[Salesdistrict] = new.[Salesdistrict],
        dest.[Lineofbusiness] = new.[Lineofbusiness],
        dest.[Concern] = new.[Concern],
        dest.[I_E_V] = new.[I_E_V],
        dest.[I_E_V-Text] = new.[I_E_V-Text],
        dest.[Responsible] = new.[Responsible],
        dest.[Warehouse] = new.[Warehouse],
        dest.[Aquisitioncode] = new.[Aquisitioncode],
        dest.[Aquisitioncode-Text] = new.[Aquisitioncode-Text],
        dest.[Originwarehouse] = new.[Originwarehouse],
        dest.[OriginAquisitioncode] = new.[OriginAquisitioncode],
        dest.[OriginAquisitioncode-Text] = new.[OriginAquisitioncode-Text],
        dest.[Itemno] = new.[Itemno],
        dest.[Productsub_group] = new.[Productsub_group],
        dest.[Itemtype] = new.[Itemtype],
        dest.[Productgroup] = new.[Productgroup],
        dest.[Productline] = new.[Productline],
        dest.[Productrange] = new.[Productrange],
        dest.[CRHProductGroupID] = new.[CRHProductGroupID],
        dest.[Production_Purchase] = new.[Production_Purchase],
        dest.[Stainlesssteelflag] = new.[Stainlesssteelflag],
        dest.[Stainlesssteel-Text] = new.[Stainlesssteel-Text],
        dest.[MainProductclass] = new.[MainProductclass],
        dest.[Productclass] = new.[Productclass],
        dest.[Configno] = new.[Configno],
        dest.[Pricelistno] = new.[Pricelistno],
        dest.[Projectno] = new.[Projectno],
        dest.[ProjectPos] = new.[ProjectPos],
        dest.[Kitheaderno] = new.[Kitheaderno],
        dest.[Bruttosaleslocal] = new.[Bruttosaleslocal],
        dest.[BruttosalesCRHEUR] = new.[BruttosalesCRHEUR],
        dest.[Brutto2saleslocal] = new.[Brutto2saleslocal],
        dest.[Brutto2salesCRHEUR] = new.[Brutto2salesCRHEUR],
        dest.[Nettosalesposlocal] = new.[Nettosalesposlocal],
        dest.[NettosalesposCRHEUR] = new.[NettosalesposCRHEUR],
        dest.[Linepercentweighted] = new.[Linepercentweighted],
        dest.[Invoicedsaleslocal] = new.[Invoicedsaleslocal],
        dest.[InvoicedsalesCRHEUR] = new.[InvoicedsalesCRHEUR],
        dest.[Othersaleslocal] = new.[Othersaleslocal],
        dest.[OthersalesCRHEUR] = new.[OthersalesCRHEUR],
        dest.[Allowanceslocal] = new.[Allowanceslocal],
        dest.[AllowancesCRHEUR] = new.[AllowancesCRHEUR],
        dest.[Sales100%local] = new.[Sales100%local],
        dest.[Sales100%CRHEUR] = new.[Sales100%CRHEUR],
        dest.[TZlocal] = new.[TZlocal],
        dest.[TZCRHEUR] = new.[TZCRHEUR],
        dest.[TZpercent] = new.[TZpercent],
        dest.[LZlocal] = new.[LZlocal],
        dest.[LZCRHEUR] = new.[LZCRHEUR],
        dest.[LZpercent] = new.[LZpercent],
        dest.[Linediscount1local] = new.[Linediscount1local],
        dest.[Linediscount1CRHEUR] = new.[Linediscount1CRHEUR],
        dest.[Linediscount1percent] = new.[Linediscount1percent],
        dest.[Linediscount2local] = new.[Linediscount2local],
        dest.[Linediscount2CRHEUR] = new.[Linediscount2CRHEUR],
        dest.[Linediscount2percent] = new.[Linediscount2percent],
        dest.[Orderdiscountlocal] = new.[Orderdiscountlocal],
        dest.[OrderdiscountCRHEUR] = new.[OrderdiscountCRHEUR],
        dest.[Orderdiscountpercent] = new.[Orderdiscountpercent],
        dest.[Productsaleslocal] = new.[Productsaleslocal],
        dest.[ProductsalesCRHEUR] = new.[ProductsalesCRHEUR],
        dest.[Plantsellingpricelocal] = new.[Plantsellingpricelocal],
        dest.[PlantsellingpriceCRHEUR] = new.[PlantsellingpriceCRHEUR],
        dest.[ICPlocal] = new.[ICPlocal],
        dest.[ICPCRHEUR] = new.[ICPCRHEUR],
        dest.[SMClocal] = new.[SMClocal],
        dest.[SMCCRHEUR] = new.[SMCCRHEUR],
        dest.[SMCsumlocal] = new.[SMCsumlocal],
        dest.[SMCsumCRHEUR] = new.[SMCsumCRHEUR],
        dest.[Variablesellingcostslocal] = new.[Variablesellingcostslocal],
        dest.[VariablesellingcostsCRHEUR] = new.[VariablesellingcostsCRHEUR],
        dest.[Netsaleslocal] = new.[Netsaleslocal],
        dest.[NetsalesCRHEUR] = new.[NetsalesCRHEUR],
        dest.[Grossmarginlocal] = new.[Grossmarginlocal],
        dest.[GrossmarginCRHEUR] = new.[GrossmarginCRHEUR],
        dest.[contribmarginIIdclocal] = new.[contribmarginIIdclocal],
        dest.[contribmarginIIdcCRHEUR] = new.[contribmarginIIdcCRHEUR],
        dest.[contribmarginIIholocal] = new.[contribmarginIIholocal],
        dest.[contribmarginIIhoCRHEUR] = new.[contribmarginIIhoCRHEUR],
        dest.[Plantoverheadcostslocal] = new.[Plantoverheadcostslocal],
        dest.[PlantoverheadcostsCRHEUR] = new.[PlantoverheadcostsCRHEUR],
        dest.[contribmarginIIIlocal] = new.[contribmarginIIIlocal],
        dest.[contribmarginIIICRHEUR] = new.[contribmarginIIICRHEUR],
        dest.[Invoicequantity] = new.[Invoicequantity],
        dest.[Orderquantity] = new.[Orderquantity],
        dest.[Netweight] = new.[Netweight],
        dest.[Freightinvoicedlocal] = new.[Freightinvoicedlocal],
        dest.[FreightinvoicedCRHEUR] = new.[FreightinvoicedCRHEUR],
        dest.[Tollinvoicedlocal] = new.[Tollinvoicedlocal],
        dest.[TollinvoicedCRHEUR] = new.[TollinvoicedCRHEUR],
        dest.[Packingsinvoicedlocal] = new.[Packingsinvoicedlocal],
        dest.[PackingsinvoicedCRHEUR] = new.[PackingsinvoicedCRHEUR],
        dest.[Surchargeonshortquantitylocal] = new.[Surchargeonshortquantitylocal],
        dest.[SurchargeonshortquantityCRHEUR] = new.[SurchargeonshortquantityCRHEUR],
        dest.[Planningcostsinvoicedlocal] = new.[Planningcostsinvoicedlocal],
        dest.[PlanningcostsinvoicedCRHEUR] = new.[PlanningcostsinvoicedCRHEUR],
        dest.[Packingdepositlocal] = new.[Packingdepositlocal],
        dest.[PackingdepositCRHEUR] = new.[PackingdepositCRHEUR],
        dest.[Miscellaneousproceedsinvoicedlocal] = new.[Miscellaneousproceedsinvoicedlocal],
        dest.[MiscellaneousproceedsinvoicedCRHEUR] = new.[MiscellaneousproceedsinvoicedCRHEUR],
        dest.[Reservecustomerbonuslocal] = new.[Reservecustomerbonuslocal],
        dest.[ReservecustomerbonusCRHEUR] = new.[ReservecustomerbonusCRHEUR],
        dest.[Warrentieslocal] = new.[Warrentieslocal],
        dest.[WarrentiesCRHEUR] = new.[WarrentiesCRHEUR],
        dest.[Marketingcostsallowanceslocal] = new.[Marketingcostsallowanceslocal],
        dest.[MarketingcostsallowancesCRHEUR] = new.[MarketingcostsallowancesCRHEUR],
        dest.[Reservecustomerdiscountlocal] = new.[Reservecustomerdiscountlocal],
        dest.[ReservecustomerdiscountCRHEUR] = new.[ReservecustomerdiscountCRHEUR],
        dest.[Freightcostslocal] = new.[Freightcostslocal],
        dest.[FreightcostsCRHEUR] = new.[FreightcostsCRHEUR],
        dest.[Packingcostslocal] = new.[Packingcostslocal],
        dest.[PackingcostsCRHEUR] = new.[PackingcostsCRHEUR],
        dest.[Dutieslocal] = new.[Dutieslocal],
        dest.[DutiesCRHEUR] = new.[DutiesCRHEUR],
        dest.[Insurancelocal] = new.[Insurancelocal],
        dest.[InsuranceCRHEUR] = new.[InsuranceCRHEUR],
        dest.[Commissionslocal] = new.[Commissionslocal],
        dest.[CommissionsCRHEUR] = new.[CommissionsCRHEUR],
        dest.[Licenceslocal] = new.[Licenceslocal],
        dest.[LicencesCRHEUR] = new.[LicencesCRHEUR],
        dest.[SMCordinarysteellocal] = new.[SMCordinarysteellocal],
        dest.[SMCordinarysteelCRHEUR] = new.[SMCordinarysteelCRHEUR],
        dest.[SMCstainlesssteellocal] = new.[SMCstainlesssteellocal],
        dest.[SMCstainlesssteelCRHEUR] = new.[SMCstainlesssteelCRHEUR],
        dest.[SMCotherrawmateriallocal] = new.[SMCotherrawmateriallocal],
        dest.[SMCotherrawmaterialCRHEUR] = new.[SMCotherrawmaterialCRHEUR],
        dest.[SMCmaterialoverheadcostslocal] = new.[SMCmaterialoverheadcostslocal],
        dest.[SMCmaterialoverheadcostsCRHEUR] = new.[SMCmaterialoverheadcostsCRHEUR],
        dest.[SMCalloysurchargelocal] = new.[SMCalloysurchargelocal],
        dest.[SMCalloysurchargeCRHEUR] = new.[SMCalloysurchargeCRHEUR],
        dest.[SMCexternalproductioncostslocal] = new.[SMCexternalproductioncostslocal],
        dest.[SMCexternalproductioncostsCRHEUR] = new.[SMCexternalproductioncostsCRHEUR],
        dest.[SMCvariableproductioncostslocal] = new.[SMCvariableproductioncostslocal],
        dest.[SMCvariableproductioncostsCRHEUR] = new.[SMCvariableproductioncostsCRHEUR],
        dest.[SMCfixedproductioncostslocal] = new.[SMCfixedproductioncostslocal],
        dest.[SMCfixedproductioncostsCRHEUR] = new.[SMCfixedproductioncostsCRHEUR],
        dest.[CostsofcapitalE01local] = new.[CostsofcapitalE01local],
        dest.[CostsofcapitalE01CRHEUR] = new.[CostsofcapitalE01CRHEUR],
        dest.[WarehousechargesE02local] = new.[WarehousechargesE02local],
        dest.[WarhousechargesE02CRHEUR] = new.[WarhousechargesE02CRHEUR],
        dest.[HandlingchargesE03local] = new.[HandlingchargesE03local],
        dest.[HandlingchargesE03CRHEUR] = new.[HandlingchargesE03CRHEUR],
        dest.[PackagingchargesE04local] = new.[PackagingchargesE04local],
        dest.[PackagingchargesE04CRHEUR] = new.[PackagingchargesE04CRHEUR],
        dest.[PlantoverheadE05local] = new.[PlantoverheadE05local],
        dest.[PlantoverheadE05CRHEUR] = new.[PlantoverheadE05CRHEUR],
        dest.[E06local] = new.[E06local],
        dest.[E06CRHEUR] = new.[E06CRHEUR],
        dest.[E07local] = new.[E07local],
        dest.[E07CRHEUR] = new.[E07CRHEUR],
        dest.[PlantprofitE08local] = new.[PlantprofitE08local],
        dest.[PlantprofitE08CRHEUR] = new.[PlantprofitE08CRHEUR],
        dest.[ICsurchargeE09local] = new.[ICsurchargeE09local],
        dest.[ICsurchargeE09CRHEUR] = new.[ICsurchargeE09CRHEUR],
        dest.[FreightsurchargeE10local] = new.[FreightsurchargeE10local],
        dest.[FreightsurchargeE10CRHEUR] = new.[FreightsurchargeE10CRHEUR],
        dest.[Freightdctocustomerlocal] = new.[Freightdctocustomerlocal],
        dest.[FreightdctocustomerCRHEUR] = new.[FreightdctocustomerCRHEUR],
        dest.[FreightAR_LAtodclocal] = new.[FreightAR_LAtodclocal],
        dest.[FreightAR_LAtodcCRHEUR] = new.[FreightAR_LAtodcCRHEUR],
        dest.[FreightPNtoAR_LAlocal] = new.[FreightPNtoAR_LAlocal],
        dest.[FreightPNtoAR_LACRHEUR] = new.[FreightPNtoAR_LACRHEUR],
        dest.[DAN502] = new.[DAN502],
        dest.[DAN503] = new.[DAN503],
        dest.[DAA705] = new.[DAA705],
        dest.[LengthinMper1] = new.[LengthinMper1],
        dest.[LengthinM] = new.[LengthinM],
        dest.[Freight_Tollinvoicedlocal] = new.[Freight_Tollinvoicedlocal],
        dest.[Freight_TollinvoicedCRHEUR] = new.[Freight_TollinvoicedCRHEUR],
        dest.[Packaginginvoicedlocal] = new.[Packaginginvoicedlocal],
        dest.[PackaginginvoicedCRHEUR] = new.[PackaginginvoicedCRHEUR],
        dest.[Grosssaleslocal] = new.[Grosssaleslocal],
        dest.[GrosssalesCRHEUR] = new.[GrosssalesCRHEUR],
        dest.[CostCenter] = new.[CostCenter],
        dest.[DAGRWE] = new.[DAGRWE],
        dest.[CurrencyRatelocaltoCRH1EUR] = new.[CurrencyRatelocaltoCRH1EUR],
        dest.[CurrencyEUR] = new.[CurrencyEUR],
        dest.[Currencylocal] = new.[Currencylocal],
        dest.[Salespersonname] = new.[Salespersonname],
        dest.[Salesdistrictname] = new.[Salesdistrictname],
        dest.[Projectname] = new.[Projectname],
        dest.[Projectdeliverycountry] = new.[Projectdeliverycountry],
        dest.[Projectdeliverycity] = new.[Projectdeliverycity],
        dest.[Companycountrycode] = new.[Companycountrycode],
        dest.[Companycountryname] = new.[Companycountryname],
        dest.[DW_Batch] = new.[DW_Batch],
        dest.[DW_SourceCode] = new.[DW_SourceCode],
        dest.[DW_TimeStamp] = new.[DW_TimeStamp],
        dest.[t_applicationId] = new.[t_applicationId],
        dest.[t_jobId] = new.[t_jobId],
        dest.[t_jobDtm] = new.[t_jobDtm],
        dest.[t_jobBy] = new.[t_jobBy],
        dest.[t_extractionDtm] = new.[t_extractionDtm],
        dest.[t_filePath] = new.[t_filePath],
        dest.[t_lastActionDtm] = GETDATE(),
        dest.[t_lastActionCd] = 'U',
        dest.[t_lastActionBy] = 'adm_mpors@crhemea.onmicrosoft.com'
WHEN NOT MATCHED BY SOURCE THEN
-- An action of type 'Update' is not allowed in the 'WHEN NOT MATCHED' clause of a MERGE statement.
    UPDATE SET
        dest.[t_lastActionDtm] = GETDATE(),
        dest.[t_lastActionCd] = 'D',
        dest.[t_lastActionBy] = 'adm_mpors@crhemea.onmicrosoft.com'
WHEN NOT MATCHED BY TARGET THEN
    INSERT (
        [DW_Id],
        [Company],
        [Distributioncompany],
        [Salesarea],
        [Inside_Outside],
        [Inside_Outside-Text],
        [Site],
        [Invoiceno],
        [Invoicedate],
        [Accountingdate],
        [Year],
        [Month],
        [Day],
        [Orderno],
        [Deliveryno],
        [Posno],
        [Orderdate],
        [Deldateplan],
        [Deldateconfirmed],
        [Deldateact],
        [SalesType],
        [Customerno],
        [Country],
        [Postalcode],
        [DlvCountry],
        [DlvState],
        [DlvCounty],
        [Mainsalesperson],
        [Salesperson],
        [Maindistrict],
        [Salesdistrict],
        [Lineofbusiness],
        [Concern],
        [I_E_V],
        [I_E_V-Text],
        [Responsible],
        [Warehouse],
        [Aquisitioncode],
        [Aquisitioncode-Text],
        [Originwarehouse],
        [OriginAquisitioncode],
        [OriginAquisitioncode-Text],
        [Itemno],
        [Productsub_group],
        [Itemtype],
        [Productgroup],
        [Productline],
        [Productrange],
        [CRHProductGroupID],
        [Production_Purchase],
        [Stainlesssteelflag],
        [Stainlesssteel-Text],
        [MainProductclass],
        [Productclass],
        [Configno],
        [Pricelistno],
        [Projectno],
        [ProjectPos],
        [Kitheaderno],
        [Bruttosaleslocal],
        [BruttosalesCRHEUR],
        [Brutto2saleslocal],
        [Brutto2salesCRHEUR],
        [Nettosalesposlocal],
        [NettosalesposCRHEUR],
        [Linepercentweighted],
        [Invoicedsaleslocal],
        [InvoicedsalesCRHEUR],
        [Othersaleslocal],
        [OthersalesCRHEUR],
        [Allowanceslocal],
        [AllowancesCRHEUR],
        [Sales100%local],
        [Sales100%CRHEUR],
        [TZlocal],
        [TZCRHEUR],
        [TZpercent],
        [LZlocal],
        [LZCRHEUR],
        [LZpercent],
        [Linediscount1local],
        [Linediscount1CRHEUR],
        [Linediscount1percent],
        [Linediscount2local],
        [Linediscount2CRHEUR],
        [Linediscount2percent],
        [Orderdiscountlocal],
        [OrderdiscountCRHEUR],
        [Orderdiscountpercent],
        [Productsaleslocal],
        [ProductsalesCRHEUR],
        [Plantsellingpricelocal],
        [PlantsellingpriceCRHEUR],
        [ICPlocal],
        [ICPCRHEUR],
        [SMClocal],
        [SMCCRHEUR],
        [SMCsumlocal],
        [SMCsumCRHEUR],
        [Variablesellingcostslocal],
        [VariablesellingcostsCRHEUR],
        [Netsaleslocal],
        [NetsalesCRHEUR],
        [Grossmarginlocal],
        [GrossmarginCRHEUR],
        [contribmarginIIdclocal],
        [contribmarginIIdcCRHEUR],
        [contribmarginIIholocal],
        [contribmarginIIhoCRHEUR],
        [Plantoverheadcostslocal],
        [PlantoverheadcostsCRHEUR],
        [contribmarginIIIlocal],
        [contribmarginIIICRHEUR],
        [Invoicequantity],
        [Orderquantity],
        [Netweight],
        [Freightinvoicedlocal],
        [FreightinvoicedCRHEUR],
        [Tollinvoicedlocal],
        [TollinvoicedCRHEUR],
        [Packingsinvoicedlocal],
        [PackingsinvoicedCRHEUR],
        [Surchargeonshortquantitylocal],
        [SurchargeonshortquantityCRHEUR],
        [Planningcostsinvoicedlocal],
        [PlanningcostsinvoicedCRHEUR],
        [Packingdepositlocal],
        [PackingdepositCRHEUR],
        [Miscellaneousproceedsinvoicedlocal],
        [MiscellaneousproceedsinvoicedCRHEUR],
        [Reservecustomerbonuslocal],
        [ReservecustomerbonusCRHEUR],
        [Warrentieslocal],
        [WarrentiesCRHEUR],
        [Marketingcostsallowanceslocal],
        [MarketingcostsallowancesCRHEUR],
        [Reservecustomerdiscountlocal],
        [ReservecustomerdiscountCRHEUR],
        [Freightcostslocal],
        [FreightcostsCRHEUR],
        [Packingcostslocal],
        [PackingcostsCRHEUR],
        [Dutieslocal],
        [DutiesCRHEUR],
        [Insurancelocal],
        [InsuranceCRHEUR],
        [Commissionslocal],
        [CommissionsCRHEUR],
        [Licenceslocal],
        [LicencesCRHEUR],
        [SMCordinarysteellocal],
        [SMCordinarysteelCRHEUR],
        [SMCstainlesssteellocal],
        [SMCstainlesssteelCRHEUR],
        [SMCotherrawmateriallocal],
        [SMCotherrawmaterialCRHEUR],
        [SMCmaterialoverheadcostslocal],
        [SMCmaterialoverheadcostsCRHEUR],
        [SMCalloysurchargelocal],
        [SMCalloysurchargeCRHEUR],
        [SMCexternalproductioncostslocal],
        [SMCexternalproductioncostsCRHEUR],
        [SMCvariableproductioncostslocal],
        [SMCvariableproductioncostsCRHEUR],
        [SMCfixedproductioncostslocal],
        [SMCfixedproductioncostsCRHEUR],
        [CostsofcapitalE01local],
        [CostsofcapitalE01CRHEUR],
        [WarehousechargesE02local],
        [WarhousechargesE02CRHEUR],
        [HandlingchargesE03local],
        [HandlingchargesE03CRHEUR],
        [PackagingchargesE04local],
        [PackagingchargesE04CRHEUR],
        [PlantoverheadE05local],
        [PlantoverheadE05CRHEUR],
        [E06local],
        [E06CRHEUR],
        [E07local],
        [E07CRHEUR],
        [PlantprofitE08local],
        [PlantprofitE08CRHEUR],
        [ICsurchargeE09local],
        [ICsurchargeE09CRHEUR],
        [FreightsurchargeE10local],
        [FreightsurchargeE10CRHEUR],
        [Freightdctocustomerlocal],
        [FreightdctocustomerCRHEUR],
        [FreightAR_LAtodclocal],
        [FreightAR_LAtodcCRHEUR],
        [FreightPNtoAR_LAlocal],
        [FreightPNtoAR_LACRHEUR],
        [DAN502],
        [DAN503],
        [DAA705],
        [LengthinMper1],
        [LengthinM],
        [Freight_Tollinvoicedlocal],
        [Freight_TollinvoicedCRHEUR],
        [Packaginginvoicedlocal],
        [PackaginginvoicedCRHEUR],
        [Grosssaleslocal],
        [GrosssalesCRHEUR],
        [CostCenter],
        [DAGRWE],
        [CurrencyRatelocaltoCRH1EUR],
        [CurrencyEUR],
        [Currencylocal],
        [Salespersonname],
        [Salesdistrictname],
        [Projectname],
        [Projectdeliverycountry],
        [Projectdeliverycity],
        [Companycountrycode],
        [Companycountryname],
        [DW_Batch],
        [DW_SourceCode],
        [DW_TimeStamp],
        [t_applicationId],
        [t_jobId],
        [t_jobDtm],
        [t_jobBy],
        [t_extractionDtm],
        [t_lastActionBy],
        [t_lastActionCd],
        [t_lastActionDtm],
        [t_filePath]
    )
    VALUES (
        [DW_Id],
        [Company],
        [Distributioncompany],
        [Salesarea],
        [Inside_Outside],
        [Inside_Outside-Text],
        [Site],
        [Invoiceno],
        [Invoicedate],
        [Accountingdate],
        [Year],
        [Month],
        [Day],
        [Orderno],
        [Deliveryno],
        [Posno],
        [Orderdate],
        [Deldateplan],
        [Deldateconfirmed],
        [Deldateact],
        [SalesType],
        [Customerno],
        [Country],
        [Postalcode],
        [DlvCountry],
        [DlvState],
        [DlvCounty],
        [Mainsalesperson],
        [Salesperson],
        [Maindistrict],
        [Salesdistrict],
        [Lineofbusiness],
        [Concern],
        [I_E_V],
        [I_E_V-Text],
        [Responsible],
        [Warehouse],
        [Aquisitioncode],
        [Aquisitioncode-Text],
        [Originwarehouse],
        [OriginAquisitioncode],
        [OriginAquisitioncode-Text],
        [Itemno],
        [Productsub_group],
        [Itemtype],
        [Productgroup],
        [Productline],
        [Productrange],
        [CRHProductGroupID],
        [Production_Purchase],
        [Stainlesssteelflag],
        [Stainlesssteel-Text],
        [MainProductclass],
        [Productclass],
        [Configno],
        [Pricelistno],
        [Projectno],
        [ProjectPos],
        [Kitheaderno],
        [Bruttosaleslocal],
        [BruttosalesCRHEUR],
        [Brutto2saleslocal],
        [Brutto2salesCRHEUR],
        [Nettosalesposlocal],
        [NettosalesposCRHEUR],
        [Linepercentweighted],
        [Invoicedsaleslocal],
        [InvoicedsalesCRHEUR],
        [Othersaleslocal],
        [OthersalesCRHEUR],
        [Allowanceslocal],
        [AllowancesCRHEUR],
        [Sales100%local],
        [Sales100%CRHEUR],
        [TZlocal],
        [TZCRHEUR],
        [TZpercent],
        [LZlocal],
        [LZCRHEUR],
        [LZpercent],
        [Linediscount1local],
        [Linediscount1CRHEUR],
        [Linediscount1percent],
        [Linediscount2local],
        [Linediscount2CRHEUR],
        [Linediscount2percent],
        [Orderdiscountlocal],
        [OrderdiscountCRHEUR],
        [Orderdiscountpercent],
        [Productsaleslocal],
        [ProductsalesCRHEUR],
        [Plantsellingpricelocal],
        [PlantsellingpriceCRHEUR],
        [ICPlocal],
        [ICPCRHEUR],
        [SMClocal],
        [SMCCRHEUR],
        [SMCsumlocal],
        [SMCsumCRHEUR],
        [Variablesellingcostslocal],
        [VariablesellingcostsCRHEUR],
        [Netsaleslocal],
        [NetsalesCRHEUR],
        [Grossmarginlocal],
        [GrossmarginCRHEUR],
        [contribmarginIIdclocal],
        [contribmarginIIdcCRHEUR],
        [contribmarginIIholocal],
        [contribmarginIIhoCRHEUR],
        [Plantoverheadcostslocal],
        [PlantoverheadcostsCRHEUR],
        [contribmarginIIIlocal],
        [contribmarginIIICRHEUR],
        [Invoicequantity],
        [Orderquantity],
        [Netweight],
        [Freightinvoicedlocal],
        [FreightinvoicedCRHEUR],
        [Tollinvoicedlocal],
        [TollinvoicedCRHEUR],
        [Packingsinvoicedlocal],
        [PackingsinvoicedCRHEUR],
        [Surchargeonshortquantitylocal],
        [SurchargeonshortquantityCRHEUR],
        [Planningcostsinvoicedlocal],
        [PlanningcostsinvoicedCRHEUR],
        [Packingdepositlocal],
        [PackingdepositCRHEUR],
        [Miscellaneousproceedsinvoicedlocal],
        [MiscellaneousproceedsinvoicedCRHEUR],
        [Reservecustomerbonuslocal],
        [ReservecustomerbonusCRHEUR],
        [Warrentieslocal],
        [WarrentiesCRHEUR],
        [Marketingcostsallowanceslocal],
        [MarketingcostsallowancesCRHEUR],
        [Reservecustomerdiscountlocal],
        [ReservecustomerdiscountCRHEUR],
        [Freightcostslocal],
        [FreightcostsCRHEUR],
        [Packingcostslocal],
        [PackingcostsCRHEUR],
        [Dutieslocal],
        [DutiesCRHEUR],
        [Insurancelocal],
        [InsuranceCRHEUR],
        [Commissionslocal],
        [CommissionsCRHEUR],
        [Licenceslocal],
        [LicencesCRHEUR],
        [SMCordinarysteellocal],
        [SMCordinarysteelCRHEUR],
        [SMCstainlesssteellocal],
        [SMCstainlesssteelCRHEUR],
        [SMCotherrawmateriallocal],
        [SMCotherrawmaterialCRHEUR],
        [SMCmaterialoverheadcostslocal],
        [SMCmaterialoverheadcostsCRHEUR],
        [SMCalloysurchargelocal],
        [SMCalloysurchargeCRHEUR],
        [SMCexternalproductioncostslocal],
        [SMCexternalproductioncostsCRHEUR],
        [SMCvariableproductioncostslocal],
        [SMCvariableproductioncostsCRHEUR],
        [SMCfixedproductioncostslocal],
        [SMCfixedproductioncostsCRHEUR],
        [CostsofcapitalE01local],
        [CostsofcapitalE01CRHEUR],
        [WarehousechargesE02local],
        [WarhousechargesE02CRHEUR],
        [HandlingchargesE03local],
        [HandlingchargesE03CRHEUR],
        [PackagingchargesE04local],
        [PackagingchargesE04CRHEUR],
        [PlantoverheadE05local],
        [PlantoverheadE05CRHEUR],
        [E06local],
        [E06CRHEUR],
        [E07local],
        [E07CRHEUR],
        [PlantprofitE08local],
        [PlantprofitE08CRHEUR],
        [ICsurchargeE09local],
        [ICsurchargeE09CRHEUR],
        [FreightsurchargeE10local],
        [FreightsurchargeE10CRHEUR],
        [Freightdctocustomerlocal],
        [FreightdctocustomerCRHEUR],
        [FreightAR_LAtodclocal],
        [FreightAR_LAtodcCRHEUR],
        [FreightPNtoAR_LAlocal],
        [FreightPNtoAR_LACRHEUR],
        [DAN502],
        [DAN503],
        [DAA705],
        [LengthinMper1],
        [LengthinM],
        [Freight_Tollinvoicedlocal],
        [Freight_TollinvoicedCRHEUR],
        [Packaginginvoicedlocal],
        [PackaginginvoicedCRHEUR],
        [Grosssaleslocal],
        [GrosssalesCRHEUR],
        [CostCenter],
        [DAGRWE],
        [CurrencyRatelocaltoCRH1EUR],
        [CurrencyEUR],
        [Currencylocal],
        [Salespersonname],
        [Salesdistrictname],
        [Projectname],
        [Projectdeliverycountry],
        [Projectdeliverycity],
        [Companycountrycode],
        [Companycountryname],
        [DW_Batch],
        [DW_SourceCode],
        [DW_TimeStamp],
        [t_applicationId],
        [t_jobId],
        [t_jobDtm],
        [t_jobBy],
        [t_extractionDtm],
        'adm_mpors@crhemea.onmicrosoft.com',
        'I',
        GETDATE(),
        [t_filePath]        
    )
;

select top 100
*
from [pgr].[FACT_HGDAWA_active]
where t_lastActionCd = 'I'


select 
    *
from pgr.FACT_HGDAWA_active
where 
-- Invoiceno = '5316SIN037237       '
CONCAT(Invoiceno, Posno) IN (
select CONCAT(Invoiceno, Posno)
from pgr.FACT_HGDAWA_active
group by 
Invoiceno, Posno
Having COUNT(*) > 1
) 

delete from pgr.FACT_HGDAWA_new
where Invoiceno = '9999999999999       '

delete from pgr.FACT_HGDAWA_active
where DW_Id in (1231106)


UPDATE
    new
SET
    new.Flg='U'
FROM
    [pgr].[FACT_HGDAWA_new] AS new
INNER JOIN
    [pgr].[FACT_HGDAWA_active] dest
    ON 
        new.[Invoiceno] = dest.[Invoiceno]
        AND
        new.[Posno] = dest.[Posno]
	    AND
		CHECKSUM( 
            new.[Company],
            new.[Distributioncompany],
            new.[Salesarea],
            new.[Inside_Outside],
            new.[Inside_Outside-Text],
            new.[Site],
            -- new.[Invoiceno],
            new.[Invoicedate],
            new.[Accountingdate],
            new.[Year],
            new.[Month],
            new.[Day],
            new.[Orderno],
            new.[Deliveryno],
            -- new.[Posno],
            new.[Orderdate],
            new.[Deldateplan],
            new.[Deldateconfirmed],
            new.[Deldateact],
            new.[SalesType],
            new.[Customerno],
            new.[Country],
            new.[Postalcode],
            new.[DlvCountry],
            new.[DlvState],
            new.[DlvCounty],
            new.[Mainsalesperson],
            new.[Salesperson],
            new.[Maindistrict],
            new.[Salesdistrict],
            new.[Lineofbusiness],
            new.[Concern],
            new.[I_E_V],
            new.[I_E_V-Text],
            new.[Responsible],
            new.[Warehouse],
            new.[Aquisitioncode],
            new.[Aquisitioncode-Text],
            new.[Originwarehouse],
            new.[OriginAquisitioncode],
            new.[OriginAquisitioncode-Text],
            new.[Itemno],
            new.[Productsub_group],
            new.[Itemtype],
            new.[Productgroup],
            new.[Productline],
            new.[Productrange],
            new.[CRHProductGroupID],
            new.[Production_Purchase],
            new.[Stainlesssteelflag],
            new.[Stainlesssteel-Text],
            new.[MainProductclass],
            new.[Productclass],
            new.[Configno],
            new.[Pricelistno],
            new.[Projectno],
            new.[ProjectPos],
            new.[Kitheaderno],
            new.[Bruttosaleslocal],
            new.[BruttosalesCRHEUR],
            new.[Brutto2saleslocal],
            new.[Brutto2salesCRHEUR],
            new.[Nettosalesposlocal],
            new.[NettosalesposCRHEUR],
            new.[Linepercentweighted],
            new.[Invoicedsaleslocal],
            new.[InvoicedsalesCRHEUR],
            new.[Othersaleslocal],
            new.[OthersalesCRHEUR],
            new.[Allowanceslocal],
            new.[AllowancesCRHEUR],
            new.[Sales100%local],
            new.[Sales100%CRHEUR],
            new.[TZlocal],
            new.[TZCRHEUR],
            new.[TZpercent],
            new.[LZlocal],
            new.[LZCRHEUR],
            new.[LZpercent],
            new.[Linediscount1local],
            new.[Linediscount1CRHEUR],
            new.[Linediscount1percent],
            new.[Linediscount2local],
            new.[Linediscount2CRHEUR],
            new.[Linediscount2percent],
            new.[Orderdiscountlocal],
            new.[OrderdiscountCRHEUR],
            new.[Orderdiscountpercent],
            new.[Productsaleslocal],
            new.[ProductsalesCRHEUR],
            new.[Plantsellingpricelocal],
            new.[PlantsellingpriceCRHEUR],
            new.[ICPlocal],
            new.[ICPCRHEUR],
            new.[SMClocal],
            new.[SMCCRHEUR],
            new.[SMCsumlocal],
            new.[SMCsumCRHEUR],
            new.[Variablesellingcostslocal],
            new.[VariablesellingcostsCRHEUR],
            new.[Netsaleslocal],
            new.[NetsalesCRHEUR],
            new.[Grossmarginlocal],
            new.[GrossmarginCRHEUR],
            new.[contribmarginIIdclocal],
            new.[contribmarginIIdcCRHEUR],
            new.[contribmarginIIholocal],
            new.[contribmarginIIhoCRHEUR],
            new.[Plantoverheadcostslocal],
            new.[PlantoverheadcostsCRHEUR],
            new.[contribmarginIIIlocal],
            new.[contribmarginIIICRHEUR],
            new.[Invoicequantity],
            new.[Orderquantity],
            new.[Netweight],
            new.[Freightinvoicedlocal],
            new.[FreightinvoicedCRHEUR],
            new.[Tollinvoicedlocal],
            new.[TollinvoicedCRHEUR],
            new.[Packingsinvoicedlocal],
            new.[PackingsinvoicedCRHEUR],
            new.[Surchargeonshortquantitylocal],
            new.[SurchargeonshortquantityCRHEUR],
            new.[Planningcostsinvoicedlocal],
            new.[PlanningcostsinvoicedCRHEUR],
            new.[Packingdepositlocal],
            new.[PackingdepositCRHEUR],
            new.[Miscellaneousproceedsinvoicedlocal],
            new.[MiscellaneousproceedsinvoicedCRHEUR],
            new.[Reservecustomerbonuslocal],
            new.[ReservecustomerbonusCRHEUR],
            new.[Warrentieslocal],
            new.[WarrentiesCRHEUR],
            new.[Marketingcostsallowanceslocal],
            new.[MarketingcostsallowancesCRHEUR],
            new.[Reservecustomerdiscountlocal],
            new.[ReservecustomerdiscountCRHEUR],
            new.[Freightcostslocal],
            new.[FreightcostsCRHEUR],
            new.[Packingcostslocal],
            new.[PackingcostsCRHEUR],
            new.[Dutieslocal],
            new.[DutiesCRHEUR],
            new.[Insurancelocal],
            new.[InsuranceCRHEUR],
            new.[Commissionslocal],
            new.[CommissionsCRHEUR],
            new.[Licenceslocal],
            new.[LicencesCRHEUR],
            new.[SMCordinarysteellocal],
            new.[SMCordinarysteelCRHEUR],
            new.[SMCstainlesssteellocal],
            new.[SMCstainlesssteelCRHEUR],
            new.[SMCotherrawmateriallocal],
            new.[SMCotherrawmaterialCRHEUR],
            new.[SMCmaterialoverheadcostslocal],
            new.[SMCmaterialoverheadcostsCRHEUR],
            new.[SMCalloysurchargelocal],
            new.[SMCalloysurchargeCRHEUR],
            new.[SMCexternalproductioncostslocal],
            new.[SMCexternalproductioncostsCRHEUR],
            new.[SMCvariableproductioncostslocal],
            new.[SMCvariableproductioncostsCRHEUR],
            new.[SMCfixedproductioncostslocal],
            new.[SMCfixedproductioncostsCRHEUR],
            new.[CostsofcapitalE01local],
            new.[CostsofcapitalE01CRHEUR],
            new.[WarehousechargesE02local],
            new.[WarhousechargesE02CRHEUR],
            new.[HandlingchargesE03local],
            new.[HandlingchargesE03CRHEUR],
            new.[PackagingchargesE04local],
            new.[PackagingchargesE04CRHEUR],
            new.[PlantoverheadE05local],
            new.[PlantoverheadE05CRHEUR],
            new.[E06local],
            new.[E06CRHEUR],
            new.[E07local],
            new.[E07CRHEUR],
            new.[PlantprofitE08local],
            new.[PlantprofitE08CRHEUR],
            new.[ICsurchargeE09local],
            new.[ICsurchargeE09CRHEUR],
            new.[FreightsurchargeE10local],
            new.[FreightsurchargeE10CRHEUR],
            new.[Freightdctocustomerlocal],
            new.[FreightdctocustomerCRHEUR],
            new.[FreightAR_LAtodclocal],
            new.[FreightAR_LAtodcCRHEUR],
            new.[FreightPNtoAR_LAlocal],
            new.[FreightPNtoAR_LACRHEUR],
            new.[DAN502],
            new.[DAN503],
            new.[DAA705],
            new.[LengthinMper1],
            new.[LengthinM],
            new.[Freight_Tollinvoicedlocal],
            new.[Freight_TollinvoicedCRHEUR],
            new.[Packaginginvoicedlocal],
            new.[PackaginginvoicedCRHEUR],
            new.[Grosssaleslocal],
            new.[GrosssalesCRHEUR],
            new.[CostCenter],
            new.[DAGRWE],
            new.[CurrencyRatelocaltoCRH1EUR],
            new.[CurrencyEUR],
            new.[Currencylocal],
            new.[Salespersonname],
            new.[Salesdistrictname],
            new.[Projectname],
            new.[Projectdeliverycountry],
            new.[Projectdeliverycity],
            new.[Companycountrycode],
            new.[Companycountryname],
            new.[DW_Batch],
            new.[DW_SourceCode],
            new.[DW_TimeStamp]
        ) <> 
		CHECKSUM( 
			dest.[Company],
            dest.[Distributioncompany],
            dest.[Salesarea],
            dest.[Inside_Outside],
            dest.[Inside_Outside-Text],
            dest.[Site],
            -- dest.[Invoiceno],
            dest.[Invoicedate],
            dest.[Accountingdate],
            dest.[Year],
            dest.[Month],
            dest.[Day],
            dest.[Orderno],
            dest.[Deliveryno],
            -- dest.[Posno],
            dest.[Orderdate],
            dest.[Deldateplan],
            dest.[Deldateconfirmed],
            dest.[Deldateact],
            dest.[SalesType],
            dest.[Customerno],
            dest.[Country],
            dest.[Postalcode],
            dest.[DlvCountry],
            dest.[DlvState],
            dest.[DlvCounty],
            dest.[Mainsalesperson],
            dest.[Salesperson],
            dest.[Maindistrict],
            dest.[Salesdistrict],
            dest.[Lineofbusiness],
            dest.[Concern],
            dest.[I_E_V],
            dest.[I_E_V-Text],
            dest.[Responsible],
            dest.[Warehouse],
            dest.[Aquisitioncode],
            dest.[Aquisitioncode-Text],
            dest.[Originwarehouse],
            dest.[OriginAquisitioncode],
            dest.[OriginAquisitioncode-Text],
            dest.[Itemno],
            dest.[Productsub_group],
            dest.[Itemtype],
            dest.[Productgroup],
            dest.[Productline],
            dest.[Productrange],
            dest.[CRHProductGroupID],
            dest.[Production_Purchase],
            dest.[Stainlesssteelflag],
            dest.[Stainlesssteel-Text],
            dest.[MainProductclass],
            dest.[Productclass],
            dest.[Configno],
            dest.[Pricelistno],
            dest.[Projectno],
            dest.[ProjectPos],
            dest.[Kitheaderno],
            dest.[Bruttosaleslocal],
            dest.[BruttosalesCRHEUR],
            dest.[Brutto2saleslocal],
            dest.[Brutto2salesCRHEUR],
            dest.[Nettosalesposlocal],
            dest.[NettosalesposCRHEUR],
            dest.[Linepercentweighted],
            dest.[Invoicedsaleslocal],
            dest.[InvoicedsalesCRHEUR],
            dest.[Othersaleslocal],
            dest.[OthersalesCRHEUR],
            dest.[Allowanceslocal],
            dest.[AllowancesCRHEUR],
            dest.[Sales100%local],
            dest.[Sales100%CRHEUR],
            dest.[TZlocal],
            dest.[TZCRHEUR],
            dest.[TZpercent],
            dest.[LZlocal],
            dest.[LZCRHEUR],
            dest.[LZpercent],
            dest.[Linediscount1local],
            dest.[Linediscount1CRHEUR],
            dest.[Linediscount1percent],
            dest.[Linediscount2local],
            dest.[Linediscount2CRHEUR],
            dest.[Linediscount2percent],
            dest.[Orderdiscountlocal],
            dest.[OrderdiscountCRHEUR],
            dest.[Orderdiscountpercent],
            dest.[Productsaleslocal],
            dest.[ProductsalesCRHEUR],
            dest.[Plantsellingpricelocal],
            dest.[PlantsellingpriceCRHEUR],
            dest.[ICPlocal],
            dest.[ICPCRHEUR],
            dest.[SMClocal],
            dest.[SMCCRHEUR],
            dest.[SMCsumlocal],
            dest.[SMCsumCRHEUR],
            dest.[Variablesellingcostslocal],
            dest.[VariablesellingcostsCRHEUR],
            dest.[Netsaleslocal],
            dest.[NetsalesCRHEUR],
            dest.[Grossmarginlocal],
            dest.[GrossmarginCRHEUR],
            dest.[contribmarginIIdclocal],
            dest.[contribmarginIIdcCRHEUR],
            dest.[contribmarginIIholocal],
            dest.[contribmarginIIhoCRHEUR],
            dest.[Plantoverheadcostslocal],
            dest.[PlantoverheadcostsCRHEUR],
            dest.[contribmarginIIIlocal],
            dest.[contribmarginIIICRHEUR],
            dest.[Invoicequantity],
            dest.[Orderquantity],
            dest.[Netweight],
            dest.[Freightinvoicedlocal],
            dest.[FreightinvoicedCRHEUR],
            dest.[Tollinvoicedlocal],
            dest.[TollinvoicedCRHEUR],
            dest.[Packingsinvoicedlocal],
            dest.[PackingsinvoicedCRHEUR],
            dest.[Surchargeonshortquantitylocal],
            dest.[SurchargeonshortquantityCRHEUR],
            dest.[Planningcostsinvoicedlocal],
            dest.[PlanningcostsinvoicedCRHEUR],
            dest.[Packingdepositlocal],
            dest.[PackingdepositCRHEUR],
            dest.[Miscellaneousproceedsinvoicedlocal],
            dest.[MiscellaneousproceedsinvoicedCRHEUR],
            dest.[Reservecustomerbonuslocal],
            dest.[ReservecustomerbonusCRHEUR],
            dest.[Warrentieslocal],
            dest.[WarrentiesCRHEUR],
            dest.[Marketingcostsallowanceslocal],
            dest.[MarketingcostsallowancesCRHEUR],
            dest.[Reservecustomerdiscountlocal],
            dest.[ReservecustomerdiscountCRHEUR],
            dest.[Freightcostslocal],
            dest.[FreightcostsCRHEUR],
            dest.[Packingcostslocal],
            dest.[PackingcostsCRHEUR],
            dest.[Dutieslocal],
            dest.[DutiesCRHEUR],
            dest.[Insurancelocal],
            dest.[InsuranceCRHEUR],
            dest.[Commissionslocal],
            dest.[CommissionsCRHEUR],
            dest.[Licenceslocal],
            dest.[LicencesCRHEUR],
            dest.[SMCordinarysteellocal],
            dest.[SMCordinarysteelCRHEUR],
            dest.[SMCstainlesssteellocal],
            dest.[SMCstainlesssteelCRHEUR],
            dest.[SMCotherrawmateriallocal],
            dest.[SMCotherrawmaterialCRHEUR],
            dest.[SMCmaterialoverheadcostslocal],
            dest.[SMCmaterialoverheadcostsCRHEUR],
            dest.[SMCalloysurchargelocal],
            dest.[SMCalloysurchargeCRHEUR],
            dest.[SMCexternalproductioncostslocal],
            dest.[SMCexternalproductioncostsCRHEUR],
            dest.[SMCvariableproductioncostslocal],
            dest.[SMCvariableproductioncostsCRHEUR],
            dest.[SMCfixedproductioncostslocal],
            dest.[SMCfixedproductioncostsCRHEUR],
            dest.[CostsofcapitalE01local],
            dest.[CostsofcapitalE01CRHEUR],
            dest.[WarehousechargesE02local],
            dest.[WarhousechargesE02CRHEUR],
            dest.[HandlingchargesE03local],
            dest.[HandlingchargesE03CRHEUR],
            dest.[PackagingchargesE04local],
            dest.[PackagingchargesE04CRHEUR],
            dest.[PlantoverheadE05local],
            dest.[PlantoverheadE05CRHEUR],
            dest.[E06local],
            dest.[E06CRHEUR],
            dest.[E07local],
            dest.[E07CRHEUR],
            dest.[PlantprofitE08local],
            dest.[PlantprofitE08CRHEUR],
            dest.[ICsurchargeE09local],
            dest.[ICsurchargeE09CRHEUR],
            dest.[FreightsurchargeE10local],
            dest.[FreightsurchargeE10CRHEUR],
            dest.[Freightdctocustomerlocal],
            dest.[FreightdctocustomerCRHEUR],
            dest.[FreightAR_LAtodclocal],
            dest.[FreightAR_LAtodcCRHEUR],
            dest.[FreightPNtoAR_LAlocal],
            dest.[FreightPNtoAR_LACRHEUR],
            dest.[DAN502],
            dest.[DAN503],
            dest.[DAA705],
            dest.[LengthinMper1],
            dest.[LengthinM],
            dest.[Freight_Tollinvoicedlocal],
            dest.[Freight_TollinvoicedCRHEUR],
            dest.[Packaginginvoicedlocal],
            dest.[PackaginginvoicedCRHEUR],
            dest.[Grosssaleslocal],
            dest.[GrosssalesCRHEUR],
            dest.[CostCenter],
            dest.[DAGRWE],
            dest.[CurrencyRatelocaltoCRH1EUR],
            dest.[CurrencyEUR],
            dest.[Currencylocal],
            dest.[Salespersonname],
            dest.[Salesdistrictname],
            dest.[Projectname],
            dest.[Projectdeliverycountry],
            dest.[Projectdeliverycity],
            dest.[Companycountrycode],
            dest.[Companycountryname],
            dest.[DW_Batch],
            dest.[DW_SourceCode],
            dest.[DW_TimeStamp]
        )


-- Mark Inserts 
UPDATE
    new
SET
    new.Flg='I'
FROM
    [pgr].[FACT_HGDAWA_new] new
LEFT JOIN
    [pgr].[FACT_HGDAWA_active] dest
    ON
        new.[Invoiceno] = dest.[Invoiceno]
        AND
        new.[Posno] = dest.[Posno]
WHERE 
    dest.[Invoiceno] IS NULL
    AND
    dest.[Posno] IS NULL


-- MARK Deletes
UPDATE
    dest
SET
    dest.Flg='D'
FROM
    [pgr].[FACT_HGDAWA_active] dest
LEFT JOIN
    [pgr].[FACT_HGDAWA_new] new
    ON
        new.[Invoiceno] = dest.[Invoiceno]
        AND
        new.[Posno] = dest.[Posno]
WHERE 
    new.[Invoiceno] IS NULL
    AND
    new.[Posno] IS NULL

-- Now Insert whats marked for Insert
INSERT INTO [pgr].[FACT_HGDAWA_active] (
    [DW_Id],
    [Company],
    [Distributioncompany],
    [Salesarea],
    [Inside_Outside],
    [Inside_Outside-Text],
    [Site],
    [Invoiceno],
    [Invoicedate],
    [Accountingdate],
    [Year],
    [Month],
    [Day],
    [Orderno],
    [Deliveryno],
    [Posno],
    [Orderdate],
    [Deldateplan],
    [Deldateconfirmed],
    [Deldateact],
    [SalesType],
    [Customerno],
    [Country],
    [Postalcode],
    [DlvCountry],
    [DlvState],
    [DlvCounty],
    [Mainsalesperson],
    [Salesperson],
    [Maindistrict],
    [Salesdistrict],
    [Lineofbusiness],
    [Concern],
    [I_E_V],
    [I_E_V-Text],
    [Responsible],
    [Warehouse],
    [Aquisitioncode],
    [Aquisitioncode-Text],
    [Originwarehouse],
    [OriginAquisitioncode],
    [OriginAquisitioncode-Text],
    [Itemno],
    [Productsub_group],
    [Itemtype],
    [Productgroup],
    [Productline],
    [Productrange],
    [CRHProductGroupID],
    [Production_Purchase],
    [Stainlesssteelflag],
    [Stainlesssteel-Text],
    [MainProductclass],
    [Productclass],
    [Configno],
    [Pricelistno],
    [Projectno],
    [ProjectPos],
    [Kitheaderno],
    [Bruttosaleslocal],
    [BruttosalesCRHEUR],
    [Brutto2saleslocal],
    [Brutto2salesCRHEUR],
    [Nettosalesposlocal],
    [NettosalesposCRHEUR],
    [Linepercentweighted],
    [Invoicedsaleslocal],
    [InvoicedsalesCRHEUR],
    [Othersaleslocal],
    [OthersalesCRHEUR],
    [Allowanceslocal],
    [AllowancesCRHEUR],
    [Sales100%local],
    [Sales100%CRHEUR],
    [TZlocal],
    [TZCRHEUR],
    [TZpercent],
    [LZlocal],
    [LZCRHEUR],
    [LZpercent],
    [Linediscount1local],
    [Linediscount1CRHEUR],
    [Linediscount1percent],
    [Linediscount2local],
    [Linediscount2CRHEUR],
    [Linediscount2percent],
    [Orderdiscountlocal],
    [OrderdiscountCRHEUR],
    [Orderdiscountpercent],
    [Productsaleslocal],
    [ProductsalesCRHEUR],
    [Plantsellingpricelocal],
    [PlantsellingpriceCRHEUR],
    [ICPlocal],
    [ICPCRHEUR],
    [SMClocal],
    [SMCCRHEUR],
    [SMCsumlocal],
    [SMCsumCRHEUR],
    [Variablesellingcostslocal],
    [VariablesellingcostsCRHEUR],
    [Netsaleslocal],
    [NetsalesCRHEUR],
    [Grossmarginlocal],
    [GrossmarginCRHEUR],
    [contribmarginIIdclocal],
    [contribmarginIIdcCRHEUR],
    [contribmarginIIholocal],
    [contribmarginIIhoCRHEUR],
    [Plantoverheadcostslocal],
    [PlantoverheadcostsCRHEUR],
    [contribmarginIIIlocal],
    [contribmarginIIICRHEUR],
    [Invoicequantity],
    [Orderquantity],
    [Netweight],
    [Freightinvoicedlocal],
    [FreightinvoicedCRHEUR],
    [Tollinvoicedlocal],
    [TollinvoicedCRHEUR],
    [Packingsinvoicedlocal],
    [PackingsinvoicedCRHEUR],
    [Surchargeonshortquantitylocal],
    [SurchargeonshortquantityCRHEUR],
    [Planningcostsinvoicedlocal],
    [PlanningcostsinvoicedCRHEUR],
    [Packingdepositlocal],
    [PackingdepositCRHEUR],
    [Miscellaneousproceedsinvoicedlocal],
    [MiscellaneousproceedsinvoicedCRHEUR],
    [Reservecustomerbonuslocal],
    [ReservecustomerbonusCRHEUR],
    [Warrentieslocal],
    [WarrentiesCRHEUR],
    [Marketingcostsallowanceslocal],
    [MarketingcostsallowancesCRHEUR],
    [Reservecustomerdiscountlocal],
    [ReservecustomerdiscountCRHEUR],
    [Freightcostslocal],
    [FreightcostsCRHEUR],
    [Packingcostslocal],
    [PackingcostsCRHEUR],
    [Dutieslocal],
    [DutiesCRHEUR],
    [Insurancelocal],
    [InsuranceCRHEUR],
    [Commissionslocal],
    [CommissionsCRHEUR],
    [Licenceslocal],
    [LicencesCRHEUR],
    [SMCordinarysteellocal],
    [SMCordinarysteelCRHEUR],
    [SMCstainlesssteellocal],
    [SMCstainlesssteelCRHEUR],
    [SMCotherrawmateriallocal],
    [SMCotherrawmaterialCRHEUR],
    [SMCmaterialoverheadcostslocal],
    [SMCmaterialoverheadcostsCRHEUR],
    [SMCalloysurchargelocal],
    [SMCalloysurchargeCRHEUR],
    [SMCexternalproductioncostslocal],
    [SMCexternalproductioncostsCRHEUR],
    [SMCvariableproductioncostslocal],
    [SMCvariableproductioncostsCRHEUR],
    [SMCfixedproductioncostslocal],
    [SMCfixedproductioncostsCRHEUR],
    [CostsofcapitalE01local],
    [CostsofcapitalE01CRHEUR],
    [WarehousechargesE02local],
    [WarhousechargesE02CRHEUR],
    [HandlingchargesE03local],
    [HandlingchargesE03CRHEUR],
    [PackagingchargesE04local],
    [PackagingchargesE04CRHEUR],
    [PlantoverheadE05local],
    [PlantoverheadE05CRHEUR],
    [E06local],
    [E06CRHEUR],
    [E07local],
    [E07CRHEUR],
    [PlantprofitE08local],
    [PlantprofitE08CRHEUR],
    [ICsurchargeE09local],
    [ICsurchargeE09CRHEUR],
    [FreightsurchargeE10local],
    [FreightsurchargeE10CRHEUR],
    [Freightdctocustomerlocal],
    [FreightdctocustomerCRHEUR],
    [FreightAR_LAtodclocal],
    [FreightAR_LAtodcCRHEUR],
    [FreightPNtoAR_LAlocal],
    [FreightPNtoAR_LACRHEUR],
    [DAN502],
    [DAN503],
    [DAA705],
    [LengthinMper1],
    [LengthinM],
    [Freight_Tollinvoicedlocal],
    [Freight_TollinvoicedCRHEUR],
    [Packaginginvoicedlocal],
    [PackaginginvoicedCRHEUR],
    [Grosssaleslocal],
    [GrosssalesCRHEUR],
    [CostCenter],
    [DAGRWE],
    [CurrencyRatelocaltoCRH1EUR],
    [CurrencyEUR],
    [Currencylocal],
    [Salespersonname],
    [Salesdistrictname],
    [Projectname],
    [Projectdeliverycountry],
    [Projectdeliverycity],
    [Companycountrycode],
    [Companycountryname],
    [DW_Batch],
    [DW_SourceCode],
    [DW_TimeStamp],
    [t_applicationId],
    [t_jobId],
    [t_jobDtm],
    [t_jobBy],
    [t_extractionDtm],
    [t_filePath],
    [LastUpdatedDate],
    [Flg]
)
SELECT 
    [DW_Id],
    [Company],
    [Distributioncompany],
    [Salesarea],
    [Inside_Outside],
    [Inside_Outside-Text],
    [Site],
    [Invoiceno],
    [Invoicedate],
    [Accountingdate],
    [Year],
    [Month],
    [Day],
    [Orderno],
    [Deliveryno],
    [Posno],
    [Orderdate],
    [Deldateplan],
    [Deldateconfirmed],
    [Deldateact],
    [SalesType],
    [Customerno],
    [Country],
    [Postalcode],
    [DlvCountry],
    [DlvState],
    [DlvCounty],
    [Mainsalesperson],
    [Salesperson],
    [Maindistrict],
    [Salesdistrict],
    [Lineofbusiness],
    [Concern],
    [I_E_V],
    [I_E_V-Text],
    [Responsible],
    [Warehouse],
    [Aquisitioncode],
    [Aquisitioncode-Text],
    [Originwarehouse],
    [OriginAquisitioncode],
    [OriginAquisitioncode-Text],
    [Itemno],
    [Productsub_group],
    [Itemtype],
    [Productgroup],
    [Productline],
    [Productrange],
    [CRHProductGroupID],
    [Production_Purchase],
    [Stainlesssteelflag],
    [Stainlesssteel-Text],
    [MainProductclass],
    [Productclass],
    [Configno],
    [Pricelistno],
    [Projectno],
    [ProjectPos],
    [Kitheaderno],
    [Bruttosaleslocal],
    [BruttosalesCRHEUR],
    [Brutto2saleslocal],
    [Brutto2salesCRHEUR],
    [Nettosalesposlocal],
    [NettosalesposCRHEUR],
    [Linepercentweighted],
    [Invoicedsaleslocal],
    [InvoicedsalesCRHEUR],
    [Othersaleslocal],
    [OthersalesCRHEUR],
    [Allowanceslocal],
    [AllowancesCRHEUR],
    [Sales100%local],
    [Sales100%CRHEUR],
    [TZlocal],
    [TZCRHEUR],
    [TZpercent],
    [LZlocal],
    [LZCRHEUR],
    [LZpercent],
    [Linediscount1local],
    [Linediscount1CRHEUR],
    [Linediscount1percent],
    [Linediscount2local],
    [Linediscount2CRHEUR],
    [Linediscount2percent],
    [Orderdiscountlocal],
    [OrderdiscountCRHEUR],
    [Orderdiscountpercent],
    [Productsaleslocal],
    [ProductsalesCRHEUR],
    [Plantsellingpricelocal],
    [PlantsellingpriceCRHEUR],
    [ICPlocal],
    [ICPCRHEUR],
    [SMClocal],
    [SMCCRHEUR],
    [SMCsumlocal],
    [SMCsumCRHEUR],
    [Variablesellingcostslocal],
    [VariablesellingcostsCRHEUR],
    [Netsaleslocal],
    [NetsalesCRHEUR],
    [Grossmarginlocal],
    [GrossmarginCRHEUR],
    [contribmarginIIdclocal],
    [contribmarginIIdcCRHEUR],
    [contribmarginIIholocal],
    [contribmarginIIhoCRHEUR],
    [Plantoverheadcostslocal],
    [PlantoverheadcostsCRHEUR],
    [contribmarginIIIlocal],
    [contribmarginIIICRHEUR],
    [Invoicequantity],
    [Orderquantity],
    [Netweight],
    [Freightinvoicedlocal],
    [FreightinvoicedCRHEUR],
    [Tollinvoicedlocal],
    [TollinvoicedCRHEUR],
    [Packingsinvoicedlocal],
    [PackingsinvoicedCRHEUR],
    [Surchargeonshortquantitylocal],
    [SurchargeonshortquantityCRHEUR],
    [Planningcostsinvoicedlocal],
    [PlanningcostsinvoicedCRHEUR],
    [Packingdepositlocal],
    [PackingdepositCRHEUR],
    [Miscellaneousproceedsinvoicedlocal],
    [MiscellaneousproceedsinvoicedCRHEUR],
    [Reservecustomerbonuslocal],
    [ReservecustomerbonusCRHEUR],
    [Warrentieslocal],
    [WarrentiesCRHEUR],
    [Marketingcostsallowanceslocal],
    [MarketingcostsallowancesCRHEUR],
    [Reservecustomerdiscountlocal],
    [ReservecustomerdiscountCRHEUR],
    [Freightcostslocal],
    [FreightcostsCRHEUR],
    [Packingcostslocal],
    [PackingcostsCRHEUR],
    [Dutieslocal],
    [DutiesCRHEUR],
    [Insurancelocal],
    [InsuranceCRHEUR],
    [Commissionslocal],
    [CommissionsCRHEUR],
    [Licenceslocal],
    [LicencesCRHEUR],
    [SMCordinarysteellocal],
    [SMCordinarysteelCRHEUR],
    [SMCstainlesssteellocal],
    [SMCstainlesssteelCRHEUR],
    [SMCotherrawmateriallocal],
    [SMCotherrawmaterialCRHEUR],
    [SMCmaterialoverheadcostslocal],
    [SMCmaterialoverheadcostsCRHEUR],
    [SMCalloysurchargelocal],
    [SMCalloysurchargeCRHEUR],
    [SMCexternalproductioncostslocal],
    [SMCexternalproductioncostsCRHEUR],
    [SMCvariableproductioncostslocal],
    [SMCvariableproductioncostsCRHEUR],
    [SMCfixedproductioncostslocal],
    [SMCfixedproductioncostsCRHEUR],
    [CostsofcapitalE01local],
    [CostsofcapitalE01CRHEUR],
    [WarehousechargesE02local],
    [WarhousechargesE02CRHEUR],
    [HandlingchargesE03local],
    [HandlingchargesE03CRHEUR],
    [PackagingchargesE04local],
    [PackagingchargesE04CRHEUR],
    [PlantoverheadE05local],
    [PlantoverheadE05CRHEUR],
    [E06local],
    [E06CRHEUR],
    [E07local],
    [E07CRHEUR],
    [PlantprofitE08local],
    [PlantprofitE08CRHEUR],
    [ICsurchargeE09local],
    [ICsurchargeE09CRHEUR],
    [FreightsurchargeE10local],
    [FreightsurchargeE10CRHEUR],
    [Freightdctocustomerlocal],
    [FreightdctocustomerCRHEUR],
    [FreightAR_LAtodclocal],
    [FreightAR_LAtodcCRHEUR],
    [FreightPNtoAR_LAlocal],
    [FreightPNtoAR_LACRHEUR],
    [DAN502],
    [DAN503],
    [DAA705],
    [LengthinMper1],
    [LengthinM],
    [Freight_Tollinvoicedlocal],
    [Freight_TollinvoicedCRHEUR],
    [Packaginginvoicedlocal],
    [PackaginginvoicedCRHEUR],
    [Grosssaleslocal],
    [GrosssalesCRHEUR],
    [CostCenter],
    [DAGRWE],
    [CurrencyRatelocaltoCRH1EUR],
    [CurrencyEUR],
    [Currencylocal],
    [Salespersonname],
    [Salesdistrictname],
    [Projectname],
    [Projectdeliverycountry],
    [Projectdeliverycity],
    [Companycountrycode],
    [Companycountryname],
    [DW_Batch],
    [DW_SourceCode],
    [DW_TimeStamp],
    [t_applicationId],
    [t_jobId],
    [t_jobDtm],
    [t_jobBy],
    [t_extractionDtm],
    [t_filePath],
    GETDATE(),
    'I'
FROM
    [pgr].[FACT_HGDAWA_new]
WHERE
    Flg='I'

-- Updates For Updates Marked
UPDATE dest
SET
    dest.[DW_Id] = new.[DW_Id],
    dest.[Company] = new.[Company],
    dest.[Distributioncompany] = new.[Distributioncompany],
    dest.[Salesarea] = new.[Salesarea],
    dest.[Inside_Outside] = new.[Inside_Outside],
    dest.[Inside_Outside-Text] = new.[Inside_Outside-Text],
    dest.[Site] = new.[Site],
    -- dest.[Invoiceno] = new.[Invoiceno],
    dest.[Invoicedate] = new.[Invoicedate],
    dest.[Accountingdate] = new.[Accountingdate],
    dest.[Year] = new.[Year],
    dest.[Month] = new.[Month],
    dest.[Day] = new.[Day],
    dest.[Orderno] = new.[Orderno],
    dest.[Deliveryno] = new.[Deliveryno],
    -- dest.[Posno] = new.[Posno],
    dest.[Orderdate] = new.[Orderdate],
    dest.[Deldateplan] = new.[Deldateplan],
    dest.[Deldateconfirmed] = new.[Deldateconfirmed],
    dest.[Deldateact] = new.[Deldateact],
    dest.[SalesType] = new.[SalesType],
    dest.[Customerno] = new.[Customerno],
    dest.[Country] = new.[Country],
    dest.[Postalcode] = new.[Postalcode],
    dest.[DlvCountry] = new.[DlvCountry],
    dest.[DlvState] = new.[DlvState],
    dest.[DlvCounty] = new.[DlvCounty],
    dest.[Mainsalesperson] = new.[Mainsalesperson],
    dest.[Salesperson] = new.[Salesperson],
    dest.[Maindistrict] = new.[Maindistrict],
    dest.[Salesdistrict] = new.[Salesdistrict],
    dest.[Lineofbusiness] = new.[Lineofbusiness],
    dest.[Concern] = new.[Concern],
    dest.[I_E_V] = new.[I_E_V],
    dest.[I_E_V-Text] = new.[I_E_V-Text],
    dest.[Responsible] = new.[Responsible],
    dest.[Warehouse] = new.[Warehouse],
    dest.[Aquisitioncode] = new.[Aquisitioncode],
    dest.[Aquisitioncode-Text] = new.[Aquisitioncode-Text],
    dest.[Originwarehouse] = new.[Originwarehouse],
    dest.[OriginAquisitioncode] = new.[OriginAquisitioncode],
    dest.[OriginAquisitioncode-Text] = new.[OriginAquisitioncode-Text],
    dest.[Itemno] = new.[Itemno],
    dest.[Productsub_group] = new.[Productsub_group],
    dest.[Itemtype] = new.[Itemtype],
    dest.[Productgroup] = new.[Productgroup],
    dest.[Productline] = new.[Productline],
    dest.[Productrange] = new.[Productrange],
    dest.[CRHProductGroupID] = new.[CRHProductGroupID],
    dest.[Production_Purchase] = new.[Production_Purchase],
    dest.[Stainlesssteelflag] = new.[Stainlesssteelflag],
    dest.[Stainlesssteel-Text] = new.[Stainlesssteel-Text],
    dest.[MainProductclass] = new.[MainProductclass],
    dest.[Productclass] = new.[Productclass],
    dest.[Configno] = new.[Configno],
    dest.[Pricelistno] = new.[Pricelistno],
    dest.[Projectno] = new.[Projectno],
    dest.[ProjectPos] = new.[ProjectPos],
    dest.[Kitheaderno] = new.[Kitheaderno],
    dest.[Bruttosaleslocal] = new.[Bruttosaleslocal],
    dest.[BruttosalesCRHEUR] = new.[BruttosalesCRHEUR],
    dest.[Brutto2saleslocal] = new.[Brutto2saleslocal],
    dest.[Brutto2salesCRHEUR] = new.[Brutto2salesCRHEUR],
    dest.[Nettosalesposlocal] = new.[Nettosalesposlocal],
    dest.[NettosalesposCRHEUR] = new.[NettosalesposCRHEUR],
    dest.[Linepercentweighted] = new.[Linepercentweighted],
    dest.[Invoicedsaleslocal] = new.[Invoicedsaleslocal],
    dest.[InvoicedsalesCRHEUR] = new.[InvoicedsalesCRHEUR],
    dest.[Othersaleslocal] = new.[Othersaleslocal],
    dest.[OthersalesCRHEUR] = new.[OthersalesCRHEUR],
    dest.[Allowanceslocal] = new.[Allowanceslocal],
    dest.[AllowancesCRHEUR] = new.[AllowancesCRHEUR],
    dest.[Sales100%local] = new.[Sales100%local],
    dest.[Sales100%CRHEUR] = new.[Sales100%CRHEUR],
    dest.[TZlocal] = new.[TZlocal],
    dest.[TZCRHEUR] = new.[TZCRHEUR],
    dest.[TZpercent] = new.[TZpercent],
    dest.[LZlocal] = new.[LZlocal],
    dest.[LZCRHEUR] = new.[LZCRHEUR],
    dest.[LZpercent] = new.[LZpercent],
    dest.[Linediscount1local] = new.[Linediscount1local],
    dest.[Linediscount1CRHEUR] = new.[Linediscount1CRHEUR],
    dest.[Linediscount1percent] = new.[Linediscount1percent],
    dest.[Linediscount2local] = new.[Linediscount2local],
    dest.[Linediscount2CRHEUR] = new.[Linediscount2CRHEUR],
    dest.[Linediscount2percent] = new.[Linediscount2percent],
    dest.[Orderdiscountlocal] = new.[Orderdiscountlocal],
    dest.[OrderdiscountCRHEUR] = new.[OrderdiscountCRHEUR],
    dest.[Orderdiscountpercent] = new.[Orderdiscountpercent],
    dest.[Productsaleslocal] = new.[Productsaleslocal],
    dest.[ProductsalesCRHEUR] = new.[ProductsalesCRHEUR],
    dest.[Plantsellingpricelocal] = new.[Plantsellingpricelocal],
    dest.[PlantsellingpriceCRHEUR] = new.[PlantsellingpriceCRHEUR],
    dest.[ICPlocal] = new.[ICPlocal],
    dest.[ICPCRHEUR] = new.[ICPCRHEUR],
    dest.[SMClocal] = new.[SMClocal],
    dest.[SMCCRHEUR] = new.[SMCCRHEUR],
    dest.[SMCsumlocal] = new.[SMCsumlocal],
    dest.[SMCsumCRHEUR] = new.[SMCsumCRHEUR],
    dest.[Variablesellingcostslocal] = new.[Variablesellingcostslocal],
    dest.[VariablesellingcostsCRHEUR] = new.[VariablesellingcostsCRHEUR],
    dest.[Netsaleslocal] = new.[Netsaleslocal],
    dest.[NetsalesCRHEUR] = new.[NetsalesCRHEUR],
    dest.[Grossmarginlocal] = new.[Grossmarginlocal],
    dest.[GrossmarginCRHEUR] = new.[GrossmarginCRHEUR],
    dest.[contribmarginIIdclocal] = new.[contribmarginIIdclocal],
    dest.[contribmarginIIdcCRHEUR] = new.[contribmarginIIdcCRHEUR],
    dest.[contribmarginIIholocal] = new.[contribmarginIIholocal],
    dest.[contribmarginIIhoCRHEUR] = new.[contribmarginIIhoCRHEUR],
    dest.[Plantoverheadcostslocal] = new.[Plantoverheadcostslocal],
    dest.[PlantoverheadcostsCRHEUR] = new.[PlantoverheadcostsCRHEUR],
    dest.[contribmarginIIIlocal] = new.[contribmarginIIIlocal],
    dest.[contribmarginIIICRHEUR] = new.[contribmarginIIICRHEUR],
    dest.[Invoicequantity] = new.[Invoicequantity],
    dest.[Orderquantity] = new.[Orderquantity],
    dest.[Netweight] = new.[Netweight],
    dest.[Freightinvoicedlocal] = new.[Freightinvoicedlocal],
    dest.[FreightinvoicedCRHEUR] = new.[FreightinvoicedCRHEUR],
    dest.[Tollinvoicedlocal] = new.[Tollinvoicedlocal],
    dest.[TollinvoicedCRHEUR] = new.[TollinvoicedCRHEUR],
    dest.[Packingsinvoicedlocal] = new.[Packingsinvoicedlocal],
    dest.[PackingsinvoicedCRHEUR] = new.[PackingsinvoicedCRHEUR],
    dest.[Surchargeonshortquantitylocal] = new.[Surchargeonshortquantitylocal],
    dest.[SurchargeonshortquantityCRHEUR] = new.[SurchargeonshortquantityCRHEUR],
    dest.[Planningcostsinvoicedlocal] = new.[Planningcostsinvoicedlocal],
    dest.[PlanningcostsinvoicedCRHEUR] = new.[PlanningcostsinvoicedCRHEUR],
    dest.[Packingdepositlocal] = new.[Packingdepositlocal],
    dest.[PackingdepositCRHEUR] = new.[PackingdepositCRHEUR],
    dest.[Miscellaneousproceedsinvoicedlocal] = new.[Miscellaneousproceedsinvoicedlocal],
    dest.[MiscellaneousproceedsinvoicedCRHEUR] = new.[MiscellaneousproceedsinvoicedCRHEUR],
    dest.[Reservecustomerbonuslocal] = new.[Reservecustomerbonuslocal],
    dest.[ReservecustomerbonusCRHEUR] = new.[ReservecustomerbonusCRHEUR],
    dest.[Warrentieslocal] = new.[Warrentieslocal],
    dest.[WarrentiesCRHEUR] = new.[WarrentiesCRHEUR],
    dest.[Marketingcostsallowanceslocal] = new.[Marketingcostsallowanceslocal],
    dest.[MarketingcostsallowancesCRHEUR] = new.[MarketingcostsallowancesCRHEUR],
    dest.[Reservecustomerdiscountlocal] = new.[Reservecustomerdiscountlocal],
    dest.[ReservecustomerdiscountCRHEUR] = new.[ReservecustomerdiscountCRHEUR],
    dest.[Freightcostslocal] = new.[Freightcostslocal],
    dest.[FreightcostsCRHEUR] = new.[FreightcostsCRHEUR],
    dest.[Packingcostslocal] = new.[Packingcostslocal],
    dest.[PackingcostsCRHEUR] = new.[PackingcostsCRHEUR],
    dest.[Dutieslocal] = new.[Dutieslocal],
    dest.[DutiesCRHEUR] = new.[DutiesCRHEUR],
    dest.[Insurancelocal] = new.[Insurancelocal],
    dest.[InsuranceCRHEUR] = new.[InsuranceCRHEUR],
    dest.[Commissionslocal] = new.[Commissionslocal],
    dest.[CommissionsCRHEUR] = new.[CommissionsCRHEUR],
    dest.[Licenceslocal] = new.[Licenceslocal],
    dest.[LicencesCRHEUR] = new.[LicencesCRHEUR],
    dest.[SMCordinarysteellocal] = new.[SMCordinarysteellocal],
    dest.[SMCordinarysteelCRHEUR] = new.[SMCordinarysteelCRHEUR],
    dest.[SMCstainlesssteellocal] = new.[SMCstainlesssteellocal],
    dest.[SMCstainlesssteelCRHEUR] = new.[SMCstainlesssteelCRHEUR],
    dest.[SMCotherrawmateriallocal] = new.[SMCotherrawmateriallocal],
    dest.[SMCotherrawmaterialCRHEUR] = new.[SMCotherrawmaterialCRHEUR],
    dest.[SMCmaterialoverheadcostslocal] = new.[SMCmaterialoverheadcostslocal],
    dest.[SMCmaterialoverheadcostsCRHEUR] = new.[SMCmaterialoverheadcostsCRHEUR],
    dest.[SMCalloysurchargelocal] = new.[SMCalloysurchargelocal],
    dest.[SMCalloysurchargeCRHEUR] = new.[SMCalloysurchargeCRHEUR],
    dest.[SMCexternalproductioncostslocal] = new.[SMCexternalproductioncostslocal],
    dest.[SMCexternalproductioncostsCRHEUR] = new.[SMCexternalproductioncostsCRHEUR],
    dest.[SMCvariableproductioncostslocal] = new.[SMCvariableproductioncostslocal],
    dest.[SMCvariableproductioncostsCRHEUR] = new.[SMCvariableproductioncostsCRHEUR],
    dest.[SMCfixedproductioncostslocal] = new.[SMCfixedproductioncostslocal],
    dest.[SMCfixedproductioncostsCRHEUR] = new.[SMCfixedproductioncostsCRHEUR],
    dest.[CostsofcapitalE01local] = new.[CostsofcapitalE01local],
    dest.[CostsofcapitalE01CRHEUR] = new.[CostsofcapitalE01CRHEUR],
    dest.[WarehousechargesE02local] = new.[WarehousechargesE02local],
    dest.[WarhousechargesE02CRHEUR] = new.[WarhousechargesE02CRHEUR],
    dest.[HandlingchargesE03local] = new.[HandlingchargesE03local],
    dest.[HandlingchargesE03CRHEUR] = new.[HandlingchargesE03CRHEUR],
    dest.[PackagingchargesE04local] = new.[PackagingchargesE04local],
    dest.[PackagingchargesE04CRHEUR] = new.[PackagingchargesE04CRHEUR],
    dest.[PlantoverheadE05local] = new.[PlantoverheadE05local],
    dest.[PlantoverheadE05CRHEUR] = new.[PlantoverheadE05CRHEUR],
    dest.[E06local] = new.[E06local],
    dest.[E06CRHEUR] = new.[E06CRHEUR],
    dest.[E07local] = new.[E07local],
    dest.[E07CRHEUR] = new.[E07CRHEUR],
    dest.[PlantprofitE08local] = new.[PlantprofitE08local],
    dest.[PlantprofitE08CRHEUR] = new.[PlantprofitE08CRHEUR],
    dest.[ICsurchargeE09local] = new.[ICsurchargeE09local],
    dest.[ICsurchargeE09CRHEUR] = new.[ICsurchargeE09CRHEUR],
    dest.[FreightsurchargeE10local] = new.[FreightsurchargeE10local],
    dest.[FreightsurchargeE10CRHEUR] = new.[FreightsurchargeE10CRHEUR],
    dest.[Freightdctocustomerlocal] = new.[Freightdctocustomerlocal],
    dest.[FreightdctocustomerCRHEUR] = new.[FreightdctocustomerCRHEUR],
    dest.[FreightAR_LAtodclocal] = new.[FreightAR_LAtodclocal],
    dest.[FreightAR_LAtodcCRHEUR] = new.[FreightAR_LAtodcCRHEUR],
    dest.[FreightPNtoAR_LAlocal] = new.[FreightPNtoAR_LAlocal],
    dest.[FreightPNtoAR_LACRHEUR] = new.[FreightPNtoAR_LACRHEUR],
    dest.[DAN502] = new.[DAN502],
    dest.[DAN503] = new.[DAN503],
    dest.[DAA705] = new.[DAA705],
    dest.[LengthinMper1] = new.[LengthinMper1],
    dest.[LengthinM] = new.[LengthinM],
    dest.[Freight_Tollinvoicedlocal] = new.[Freight_Tollinvoicedlocal],
    dest.[Freight_TollinvoicedCRHEUR] = new.[Freight_TollinvoicedCRHEUR],
    dest.[Packaginginvoicedlocal] = new.[Packaginginvoicedlocal],
    dest.[PackaginginvoicedCRHEUR] = new.[PackaginginvoicedCRHEUR],
    dest.[Grosssaleslocal] = new.[Grosssaleslocal],
    dest.[GrosssalesCRHEUR] = new.[GrosssalesCRHEUR],
    dest.[CostCenter] = new.[CostCenter],
    dest.[DAGRWE] = new.[DAGRWE],
    dest.[CurrencyRatelocaltoCRH1EUR] = new.[CurrencyRatelocaltoCRH1EUR],
    dest.[CurrencyEUR] = new.[CurrencyEUR],
    dest.[Currencylocal] = new.[Currencylocal],
    dest.[Salespersonname] = new.[Salespersonname],
    dest.[Salesdistrictname] = new.[Salesdistrictname],
    dest.[Projectname] = new.[Projectname],
    dest.[Projectdeliverycountry] = new.[Projectdeliverycountry],
    dest.[Projectdeliverycity] = new.[Projectdeliverycity],
    dest.[Companycountrycode] = new.[Companycountrycode],
    dest.[Companycountryname] = new.[Companycountryname],
    dest.[DW_Batch] = new.[DW_Batch],
    dest.[DW_SourceCode] = new.[DW_SourceCode],
    dest.[DW_TimeStamp] = new.[DW_TimeStamp],
    dest.[t_applicationId] = new.[t_applicationId],
    dest.[t_jobId] = new.[t_jobId],
    dest.[t_jobDtm] = new.[t_jobDtm],
    dest.[t_jobBy] = new.[t_jobBy],
    dest.[t_extractionDtm] = new.[t_extractionDtm],
    dest.[t_filePath] = new.[t_filePath],
    dest.[LastUpdatedDate] = GETDATE(),
    dest.[Flg] = 'U'		
FROM
    [pgr].[FACT_HGDAWA_active] AS dest  
INNER JOIN
    [pgr].[FACT_HGDAWA_new] AS new
    ON
        new.[Invoiceno] = dest.[Invoiceno]
        AND
        new.[Posno] = dest.[Posno]
WHERE
    new.Flg='U'

-- For Deletes
-- TODO this is already done as deletes are defined directly on destination
-- UPDATE
--     dest
-- SET
--     dest.[LastUpdatedDate] = GETDATE(),
--     dest.[Flg] = 'D'		
-- FROM
--     [pgr].[FACT_HGDAWA_] AS dest  
-- INNER JOIN
--     [pgr].[FACT_HGDAWA_delta] AS new
-- ON
--     new.[Invoiceno] = dest.[Invoiceno]
--     AND
--     new.[Posno] = dest.[Posno]
-- WHERE new.Flg='D'