CREATE VIEW [dm_scm].[vw_fact_MaterialInventoryStockLevel]
AS
SELECT
  [MaterialID]
, [PlantID]
, [StorageLocationID]
, [InventorySpecialStockTypeID]
, [InventoryStockTypeID]
, [StockOwner]
, [CostCenterID]
, [CompanyCodeID]
, [SalesDocumentTypeID]
, [SalesDocumentItemCategoryID]
, [MaterialBaseUnitID]
, [PurchaseOrderTypeID]
, [InventoryValuationTypeID]
, [ReportingDate]
, [YearWeek]
, [YearMonth]
, [StockPricePerUnit]
, [StockPricePerUnit_EUR]
, [StockPricePerUnit_USD]
, [MatlStkChangeQtyInBaseUnit]
, [StockLevelQtyInBaseUnit]
, [StockLevelStandardPPU]
, [StockLevelStandardPPU_EUR]
, [StockLevelStandardPPU_USD]
, [ConsumptionQtyICPOInStandardValue_EUR]
, [ConsumptionQtyICPOInStandardValue_USD]
, [ConsumptionQtyOBDProStandardValue]
, [ConsumptionQtyOBDProStandardValue_EUR]
, [ConsumptionQtyOBDProStandardValue_USD]
, [ConsumptionQtySOStandardValue]
, [ConsumptionQtySOStandardValue_EUR]
, [ConsumptionQtySOStandardValue_USD]
, [ConsumptionQty]
, [ConsumptionValueByLatestPriceInBaseValue]
, [ConsumptionValueByLatestPrice_EUR]
, [ConsumptionValueByLatestPrice_USD]
FROM
  [edw].[vw_fact_MaterialInventoryStockLevel]
