CREATE TABLE [base_tx_crh_1_stg].[AX_CRH_A_dbo_INVENTTRANS](
	[DW_Id] [bigint] NOT NULL,
	[DATAAREAID] [nvarchar](4) NULL,
	[DATEPHYSICAL] [datetime] NULL,
	[DATEFINANCIAL] [datetime] NULL,
	[ITEMID] [nvarchar](20) NULL,
	[INVENTDIMID] [nvarchar](20) NULL,
	[QTY] [decimal](38, 12) NULL,
	[TRANSTYPE] [int] NULL,
	[STATUSISSUE] [int] NULL,
	[INVENTTRANSID] [nvarchar](24) NULL,
	[INVOICEID] [nvarchar](20) NULL,
	[COSTAMOUNTPOSTED] [decimal](38, 12) NULL,
	[COSTAMOUNTADJUSTMENT] [decimal](38, 12) NULL,
	[STATUSRECEIPT] [int] NULL,
	[COSTAMOUNTPHYSICAL] [decimal](38, 12) NULL,
	[CostAmount] [decimal](38, 18) NULL,
	[CostofSales] [decimal](38, 2) NULL,
	[PhysicalQuanity] [decimal](38, 2) NULL,
	[InboundQty] [decimal](38, 2) NULL,
	[OutboundQty] [decimal](38, 2) NULL,
	[Orderedintotal] [decimal](38, 2) NULL,
	[OrderedReseverd] [decimal](38, 2) NULL,
	[TotalAvailable] [decimal](38, 2) NULL,
	[PhysicalReserved] [decimal](38, 2) NULL,
	[OnOrder] [decimal](38, 2) NULL,
	[Availablephysical] [decimal](38, 2) NULL,
	[INVENTSIZEID] [nvarchar](10) NULL,
	[TRANSREFID] [nvarchar](20) NULL,
	[PACKINGSLIPID] [nvarchar](20) NULL,
	[DW_Batch] [bigint] NULL,
	[DW_SourceCode] [varchar](15) NOT NULL,
	[DW_TimeStamp] [datetime] NOT NULL,
 CONSTRAINT [PK_AX_CRH_A_dbo_INVENTTRANS] PRIMARY KEY NONCLUSTERED 
(
	[DW_Id] ASC
)NOT ENFORCED
) WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);