CREATE PROCEDURE [base_s4h_cax].[sp_load_C_BillingDocumentItemBasicDEX]
AS
BEGIN

-- Update or Delete(marks as Delete - 'D') records the base table based on the delta dataset
  UPDATE
    [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active]
  SET
    [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[SalesDocumentItemCategory] = src.[SalesDocumentItemCategory]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[SalesDocumentItemType] = src.[SalesDocumentItemType]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ReturnItemProcessingType] = src.[ReturnItemProcessingType]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillingDocumentType] = src.[BillingDocumentType]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillingDocumentCategory] = src.[BillingDocumentCategory]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[SDDocumentCategory] = src.[SDDocumentCategory]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CreationDate] = src.[CreationDate]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CreationTime] = src.[CreationTime]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[LastChangeDate] = src.[LastChangeDate]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillingDocumentDate] = src.[BillingDocumentDate]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillingDocumentIsTemporary] = src.[BillingDocumentIsTemporary]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[OrganizationDivision] = src.[OrganizationDivision]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[Division] = src.[Division]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[SalesOffice] = src.[SalesOffice]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[SalesOrganization] = src.[SalesOrganization]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[DistributionChannel] = src.[DistributionChannel]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[Material] = src.[Material]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[OriginallyRequestedMaterial] = src.[OriginallyRequestedMaterial]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[InternationalArticleNumber] = src.[InternationalArticleNumber]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[PricingReferenceMaterial] = src.[PricingReferenceMaterial]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[Batch] = src.[Batch]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[MaterialGroup] = src.[MaterialGroup]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[AdditionalMaterialGroup1] = src.[AdditionalMaterialGroup1]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[AdditionalMaterialGroup2] = src.[AdditionalMaterialGroup2]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[AdditionalMaterialGroup3] = src.[AdditionalMaterialGroup3]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[AdditionalMaterialGroup4] = src.[AdditionalMaterialGroup4]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[AdditionalMaterialGroup5] = src.[AdditionalMaterialGroup5]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[MaterialCommissionGroup] = src.[MaterialCommissionGroup]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[Plant] = src.[Plant]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[StorageLocation] = src.[StorageLocation]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillingDocumentIsCancelled] = src.[BillingDocumentIsCancelled]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CancelledBillingDocument] = src.[CancelledBillingDocument]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillingDocumentItemText] = src.[BillingDocumentItemText]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ServicesRenderedDate] = src.[ServicesRenderedDate]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillingQuantity] = src.[BillingQuantity]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillingQuantityUnit] = src.[BillingQuantityUnit]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillingQuantityInBaseUnit] = src.[BillingQuantityInBaseUnit]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BaseUnit] = src.[BaseUnit]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[MRPRequiredQuantityInBaseUnit] = src.[MRPRequiredQuantityInBaseUnit]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillingToBaseQuantityDnmntr] = src.[BillingToBaseQuantityDnmntr]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillingToBaseQuantityNmrtr] = src.[BillingToBaseQuantityNmrtr]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ItemGrossWeight] = src.[ItemGrossWeight]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ItemNetWeight] = src.[ItemNetWeight]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ItemWeightUnit] = src.[ItemWeightUnit]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ItemVolume] = src.[ItemVolume]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ItemVolumeUnit] = src.[ItemVolumeUnit]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillToPartyCountry] = src.[BillToPartyCountry]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillToPartyRegion] = src.[BillToPartyRegion]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillingPlanRule] = src.[BillingPlanRule]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillingPlan] = src.[BillingPlan]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillingPlanItem] = src.[BillingPlanItem]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CustomerPriceGroup] = src.[CustomerPriceGroup]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[PriceListType] = src.[PriceListType]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[TaxDepartureCountry] = src.[TaxDepartureCountry]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[VATRegistration] = src.[VATRegistration]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[VATRegistrationCountry] = src.[VATRegistrationCountry]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[VATRegistrationOrigin] = src.[VATRegistrationOrigin]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CustomerTaxClassification1] = src.[CustomerTaxClassification1]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CustomerTaxClassification2] = src.[CustomerTaxClassification2]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CustomerTaxClassification3] = src.[CustomerTaxClassification3]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CustomerTaxClassification4] = src.[CustomerTaxClassification4]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CustomerTaxClassification5] = src.[CustomerTaxClassification5]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CustomerTaxClassification6] = src.[CustomerTaxClassification6]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CustomerTaxClassification7] = src.[CustomerTaxClassification7]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CustomerTaxClassification8] = src.[CustomerTaxClassification8]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CustomerTaxClassification9] = src.[CustomerTaxClassification9]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[SDPricingProcedure] = src.[SDPricingProcedure]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[NetAmount] = src.[NetAmount]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[TransactionCurrency] = src.[TransactionCurrency]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[GrossAmount] = src.[GrossAmount]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[PricingDate] = src.[PricingDate]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[PriceDetnExchangeRate] = src.[PriceDetnExchangeRate]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[PricingScaleQuantityInBaseUnit] = src.[PricingScaleQuantityInBaseUnit]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[TaxAmount] = src.[TaxAmount]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CostAmount] = src.[CostAmount]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[Subtotal1Amount] = src.[Subtotal1Amount]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[Subtotal2Amount] = src.[Subtotal2Amount]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[Subtotal3Amount] = src.[Subtotal3Amount]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[Subtotal4Amount] = src.[Subtotal4Amount]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[Subtotal5Amount] = src.[Subtotal5Amount]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[Subtotal6Amount] = src.[Subtotal6Amount]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[StatisticalValueControl] = src.[StatisticalValueControl]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[StatisticsExchangeRate] = src.[StatisticsExchangeRate]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[StatisticsCurrency] = src.[StatisticsCurrency]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[SalesOrganizationCurrency] = src.[SalesOrganizationCurrency]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[EligibleAmountForCashDiscount] = src.[EligibleAmountForCashDiscount]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ContractAccount] = src.[ContractAccount]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CustomerPaymentTerms] = src.[CustomerPaymentTerms]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[PaymentMethod] = src.[PaymentMethod]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[PaymentReference] = src.[PaymentReference]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[FixedValueDate] = src.[FixedValueDate]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[AdditionalValueDays] = src.[AdditionalValueDays]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[PayerParty] = src.[PayerParty]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CompanyCode] = src.[CompanyCode]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[FiscalYear] = src.[FiscalYear]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[FiscalPeriod] = src.[FiscalPeriod]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CustomerAccountAssignmentGroup] = src.[CustomerAccountAssignmentGroup]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BusinessArea] = src.[BusinessArea]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ProfitCenter] = src.[ProfitCenter]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[OrderID] = src.[OrderID]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ControllingArea] = src.[ControllingArea]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ProfitabilitySegment] = src.[ProfitabilitySegment]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CostCenter] = src.[CostCenter]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[OriginSDDocument] = src.[OriginSDDocument]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[OriginSDDocumentItem] = src.[OriginSDDocumentItem]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[PriceDetnExchangeRateDate] = src.[PriceDetnExchangeRateDate]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ExchangeRateType] = src.[ExchangeRateType]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[FiscalYearVariant] = src.[FiscalYearVariant]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[Currency] = src.[Currency]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[AccountingExchangeRate] = src.[AccountingExchangeRate]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[AccountingExchangeRateIsSet] = src.[AccountingExchangeRateIsSet]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ReferenceSDDocument] = src.[ReferenceSDDocument]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ReferenceSDDocumentItem] = src.[ReferenceSDDocumentItem]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ReferenceSDDocumentCategory] = src.[ReferenceSDDocumentCategory]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[SalesDocument] = src.[SalesDocument]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[SalesDocumentItem] = src.[SalesDocumentItem]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[SalesSDDocumentCategory] = src.[SalesSDDocumentCategory]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[HigherLevelItem] = src.[HigherLevelItem]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillingDocumentItemInPartSgmt] = src.[BillingDocumentItemInPartSgmt]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[SalesGroup] = src.[SalesGroup]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[AdditionalCustomerGroup1] = src.[AdditionalCustomerGroup1]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[AdditionalCustomerGroup2] = src.[AdditionalCustomerGroup2]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[AdditionalCustomerGroup3] = src.[AdditionalCustomerGroup3]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[AdditionalCustomerGroup4] = src.[AdditionalCustomerGroup4]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[AdditionalCustomerGroup5] = src.[AdditionalCustomerGroup5]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[SDDocumentReason] = src.[SDDocumentReason]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ItemIsRelevantForCredit] = src.[ItemIsRelevantForCredit]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CreditRelatedPrice] = src.[CreditRelatedPrice]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[SalesDistrict] = src.[SalesDistrict]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[CustomerGroup] = src.[CustomerGroup]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[SoldToParty] = src.[SoldToParty]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[Country] = src.[Country]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ShipToParty] = src.[ShipToParty]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillToParty] = src.[BillToParty]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ShippingPoint] = src.[ShippingPoint]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[IncotermsVersion] = src.[IncotermsVersion]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[IncotermsClassification] = src.[IncotermsClassification]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[IncotermsTransferLocation] = src.[IncotermsTransferLocation]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[IncotermsLocation1] = src.[IncotermsLocation1]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[IncotermsLocation2] = src.[IncotermsLocation2]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[ShippingCondition] = src.[ShippingCondition]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[t_applicationId] = src.[t_applicationId]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[t_jobId] = src.[t_jobId]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[t_jobDtm] = src.[t_jobDtm]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[t_jobBy] = src.[t_jobBy]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[t_filePath] = src.[t_filePath]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[t_extractionDtm] = src.[t_extractionDtm]
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[t_lastActionBy] = SYSTEM_USER
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[t_lastActionCd] = (
        CASE
          WHEN
            src.[ODQ_CHANGEMODE] = 'U'
            AND
            src.[ODQ_ENTITYCNTR] = 1
          THEN 'U'
          WHEN
            src.[ODQ_CHANGEMODE] = 'D'
            AND
            src.[ODQ_ENTITYCNTR] = -1
          THEN 'D'
        END
      )
    , [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[t_lastActionDtm] = GETUTCDATE()
  FROM
    [base_s4h_cax].[vw_C_BillingDocumentItemBasicDEX_delta] AS src
  WHERE
    [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[MANDT] = src.[MANDT]
    AND
    [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillingDocument] = src.[BillingDocument]
    AND
    [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].[BillingDocumentItem] = src.[BillingDocumentItem]
  -- INNER JOIN
  --   [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active] AS tgt
  --   ON
  --     [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].MANDT = src.MANDT
  --     AND
  --     [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].BillingDocument = src.BillingDocument
  --     AND
  --     [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active].BillingDocumentItem = src.BillingDocumentItem
      -- AND 
      -- (
      --   (
      --     src.[ODQ_CHANGEMODE] = 'U'
      --     AND 
      --     src.[ODQ_ENTITYCNTR] = 1
      --   )
      --   OR
      --   (
      --     src.[ODQ_CHANGEMODE] = 'D'
      --     AND 
      --     src.[ODQ_ENTITYCNTR] = -1
      --   )
      -- )

-- Insert new records in the base table based on the delta dataset


  INSERT INTO
    [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active] (
      [MANDT]
    , [BillingDocument]
    , [BillingDocumentItem]
    , [SalesDocumentItemCategory]
    , [SalesDocumentItemType]
    , [ReturnItemProcessingType]
    , [BillingDocumentType]
    , [BillingDocumentCategory]
    , [SDDocumentCategory]
    , [CreationDate]
    , [CreationTime]
    , [LastChangeDate]
    , [BillingDocumentDate]
    , [BillingDocumentIsTemporary]
    , [OrganizationDivision]
    , [Division]
    , [SalesOffice]
    , [SalesOrganization]
    , [DistributionChannel]
    , [Material]
    , [OriginallyRequestedMaterial]
    , [InternationalArticleNumber]
    , [PricingReferenceMaterial]
    , [Batch]
    , [MaterialGroup]
    , [AdditionalMaterialGroup1]
    , [AdditionalMaterialGroup2]
    , [AdditionalMaterialGroup3]
    , [AdditionalMaterialGroup4]
    , [AdditionalMaterialGroup5]
    , [MaterialCommissionGroup]
    , [Plant]
    , [StorageLocation]
    , [BillingDocumentIsCancelled]
    , [CancelledBillingDocument]
    , [BillingDocumentItemText]
    , [ServicesRenderedDate]
    , [BillingQuantity]
    , [BillingQuantityUnit]
    , [BillingQuantityInBaseUnit]
    , [BaseUnit]
    , [MRPRequiredQuantityInBaseUnit]
    , [BillingToBaseQuantityDnmntr]
    , [BillingToBaseQuantityNmrtr]
    , [ItemGrossWeight]
    , [ItemNetWeight]
    , [ItemWeightUnit]
    , [ItemVolume]
    , [ItemVolumeUnit]
    , [BillToPartyCountry]
    , [BillToPartyRegion]
    , [BillingPlanRule]
    , [BillingPlan]
    , [BillingPlanItem]
    , [CustomerPriceGroup]
    , [PriceListType]
    , [TaxDepartureCountry]
    , [VATRegistration]
    , [VATRegistrationCountry]
    , [VATRegistrationOrigin]
    , [CustomerTaxClassification1]
    , [CustomerTaxClassification2]
    , [CustomerTaxClassification3]
    , [CustomerTaxClassification4]
    , [CustomerTaxClassification5]
    , [CustomerTaxClassification6]
    , [CustomerTaxClassification7]
    , [CustomerTaxClassification8]
    , [CustomerTaxClassification9]
    , [SDPricingProcedure]
    , [NetAmount]
    , [TransactionCurrency]
    , [GrossAmount]
    , [PricingDate]
    , [PriceDetnExchangeRate]
    , [PricingScaleQuantityInBaseUnit]
    , [TaxAmount]
    , [CostAmount]
    , [Subtotal1Amount]
    , [Subtotal2Amount]
    , [Subtotal3Amount]
    , [Subtotal4Amount]
    , [Subtotal5Amount]
    , [Subtotal6Amount]
    , [StatisticalValueControl]
    , [StatisticsExchangeRate]
    , [StatisticsCurrency]
    , [SalesOrganizationCurrency]
    , [EligibleAmountForCashDiscount]
    , [ContractAccount]
    , [CustomerPaymentTerms]
    , [PaymentMethod]
    , [PaymentReference]
    , [FixedValueDate]
    , [AdditionalValueDays]
    , [PayerParty]
    , [CompanyCode]
    , [FiscalYear]
    , [FiscalPeriod]
    , [CustomerAccountAssignmentGroup]
    , [BusinessArea]
    , [ProfitCenter]
    , [OrderID]
    , [ControllingArea]
    , [ProfitabilitySegment]
    , [CostCenter]
    , [OriginSDDocument]
    , [OriginSDDocumentItem]
    , [PriceDetnExchangeRateDate]
    , [ExchangeRateType]
    , [FiscalYearVariant]
    , [Currency]
    , [AccountingExchangeRate]
    , [AccountingExchangeRateIsSet]
    , [ReferenceSDDocument]
    , [ReferenceSDDocumentItem]
    , [ReferenceSDDocumentCategory]
    , [SalesDocument]
    , [SalesDocumentItem]
    , [SalesSDDocumentCategory]
    , [HigherLevelItem]
    , [BillingDocumentItemInPartSgmt]
    , [SalesGroup]
    , [AdditionalCustomerGroup1]
    , [AdditionalCustomerGroup2]
    , [AdditionalCustomerGroup3]
    , [AdditionalCustomerGroup4]
    , [AdditionalCustomerGroup5]
    , [SDDocumentReason]
    , [ItemIsRelevantForCredit]
    , [CreditRelatedPrice]
    , [SalesDistrict]
    , [CustomerGroup]
    , [SoldToParty]
    , [Country]
    , [ShipToParty]
    , [BillToParty]
    , [ShippingPoint]
    , [IncotermsVersion]
    , [IncotermsClassification]
    , [IncotermsTransferLocation]
    , [IncotermsLocation1]
    , [IncotermsLocation2]
    , [ShippingCondition]
    , [t_applicationId]
    , [t_jobId]
    , [t_jobDtm]
    , [t_jobBy]
    , [t_filePath]
    , [t_extractionDtm]
    , [t_lastActionBy]
    , [t_lastActionCd]
    , [t_lastActionDtm]
  )
  SELECT
    [MANDT]
  , [BillingDocument]
  , [BillingDocumentItem]
  , [SalesDocumentItemCategory]
  , [SalesDocumentItemType]
  , [ReturnItemProcessingType]
  , [BillingDocumentType]
  , [BillingDocumentCategory]
  , [SDDocumentCategory]
  , [CreationDate]
  , [CreationTime]
  , [LastChangeDate]
  , [BillingDocumentDate]
  , [BillingDocumentIsTemporary]
  , [OrganizationDivision]
  , [Division]
  , [SalesOffice]
  , [SalesOrganization]
  , [DistributionChannel]
  , [Material]
  , [OriginallyRequestedMaterial]
  , [InternationalArticleNumber]
  , [PricingReferenceMaterial]
  , [Batch]
  , [MaterialGroup]
  , [AdditionalMaterialGroup1]
  , [AdditionalMaterialGroup2]
  , [AdditionalMaterialGroup3]
  , [AdditionalMaterialGroup4]
  , [AdditionalMaterialGroup5]
  , [MaterialCommissionGroup]
  , [Plant]
  , [StorageLocation]
  , [BillingDocumentIsCancelled]
  , [CancelledBillingDocument]
  , [BillingDocumentItemText]
  , [ServicesRenderedDate]
  , [BillingQuantity]
  , [BillingQuantityUnit]
  , [BillingQuantityInBaseUnit]
  , [BaseUnit]
  , [MRPRequiredQuantityInBaseUnit]
  , [BillingToBaseQuantityDnmntr]
  , [BillingToBaseQuantityNmrtr]
  , [ItemGrossWeight]
  , [ItemNetWeight]
  , [ItemWeightUnit]
  , [ItemVolume]
  , [ItemVolumeUnit]
  , [BillToPartyCountry]
  , [BillToPartyRegion]
  , [BillingPlanRule]
  , [BillingPlan]
  , [BillingPlanItem]
  , [CustomerPriceGroup]
  , [PriceListType]
  , [TaxDepartureCountry]
  , [VATRegistration]
  , [VATRegistrationCountry]
  , [VATRegistrationOrigin]
  , [CustomerTaxClassification1]
  , [CustomerTaxClassification2]
  , [CustomerTaxClassification3]
  , [CustomerTaxClassification4]
  , [CustomerTaxClassification5]
  , [CustomerTaxClassification6]
  , [CustomerTaxClassification7]
  , [CustomerTaxClassification8]
  , [CustomerTaxClassification9]
  , [SDPricingProcedure]
  , [NetAmount]
  , [TransactionCurrency]
  , [GrossAmount]
  , [PricingDate]
  , [PriceDetnExchangeRate]
  , [PricingScaleQuantityInBaseUnit]
  , [TaxAmount]
  , [CostAmount]
  , [Subtotal1Amount]
  , [Subtotal2Amount]
  , [Subtotal3Amount]
  , [Subtotal4Amount]
  , [Subtotal5Amount]
  , [Subtotal6Amount]
  , [StatisticalValueControl]
  , [StatisticsExchangeRate]
  , [StatisticsCurrency]
  , [SalesOrganizationCurrency]
  , [EligibleAmountForCashDiscount]
  , [ContractAccount]
  , [CustomerPaymentTerms]
  , [PaymentMethod]
  , [PaymentReference]
  , [FixedValueDate]
  , [AdditionalValueDays]
  , [PayerParty]
  , [CompanyCode]
  , [FiscalYear]
  , [FiscalPeriod]
  , [CustomerAccountAssignmentGroup]
  , [BusinessArea]
  , [ProfitCenter]
  , [OrderID]
  , [ControllingArea]
  , [ProfitabilitySegment]
  , [CostCenter]
  , [OriginSDDocument]
  , [OriginSDDocumentItem]
  , [PriceDetnExchangeRateDate]
  , [ExchangeRateType]
  , [FiscalYearVariant]
  , [Currency]
  , [AccountingExchangeRate]
  , [AccountingExchangeRateIsSet]
  , [ReferenceSDDocument]
  , [ReferenceSDDocumentItem]
  , [ReferenceSDDocumentCategory]
  , [SalesDocument]
  , [SalesDocumentItem]
  , [SalesSDDocumentCategory]
  , [HigherLevelItem]
  , [BillingDocumentItemInPartSgmt]
  , [SalesGroup]
  , [AdditionalCustomerGroup1]
  , [AdditionalCustomerGroup2]
  , [AdditionalCustomerGroup3]
  , [AdditionalCustomerGroup4]
  , [AdditionalCustomerGroup5]
  , [SDDocumentReason]
  , [ItemIsRelevantForCredit]
  , [CreditRelatedPrice]
  , [SalesDistrict]
  , [CustomerGroup]
  , [SoldToParty]
  , [Country]
  , [ShipToParty]
  , [BillToParty]
  , [ShippingPoint]
  , [IncotermsVersion]
  , [IncotermsClassification]
  , [IncotermsTransferLocation]
  , [IncotermsLocation1]
  , [IncotermsLocation2]
  , [ShippingCondition]
  , [t_applicationId]
  , [t_jobId]
  , [t_jobDtm]
  , [t_jobBy]
  , [t_filePath]
  , [t_extractionDtm]
  , SYSTEM_USER AS [t_lastActionBy]
  , (
      CASE
        WHEN src.[ODQ_CHANGEMODE] = '' AND src.[ODQ_ENTITYCNTR] = 0
          THEN 'I'
        WHEN src.[ODQ_CHANGEMODE] = 'U' AND src.[ODQ_ENTITYCNTR] = 1
          THEN 'I'
        WHEN src.[ODQ_CHANGEMODE] = 'D' AND src.[ODQ_ENTITYCNTR] = -1
          THEN 'D'
        WHEN src.[ODQ_CHANGEMODE] = 'С' AND src.[ODQ_ENTITYCNTR] = 1
          THEN 'I'
      END
    ) AS [t_lastActionCd]
  , GETUTCDATE() AS [t_lastActionDtm]
  FROM
    [base_s4h_cax].[vw_C_BillingDocumentItemBasicDEX_delta] AS src
  WHERE NOT EXISTS (
    SELECT
      MANDT
      ,BillingDocument
      ,BillingDocumentItem
    FROM 
      [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active] tgt2
    WHERE 
      tgt2.MANDT = src.MANDT
      AND
      tgt2.BillingDocument = src.BillingDocument
      AND
      tgt2.BillingDocumentItem = src.BillingDocumentItem
  )
  
END