CREATE PROC [base_s4h_cax].[sp_load_I_GLAccountLineItemRawData]
AS
BEGIN

    -- Update or Delete(marks as Delete - 'D') records the base table based on the delta dataset
    UPDATE tgt
    SET 
          tgt.[SourceLedger] = src.[SourceLedger]
        , tgt.[CompanyCode] = src.[CompanyCode]
        , tgt.[FiscalYear] = src.[FiscalYear]
        , tgt.[AccountingDocument] = src.[AccountingDocument]
        , tgt.[LedgerGLLineItem] = src.[LedgerGLLineItem]
        , tgt.[LedgerFiscalYear] = src.[LedgerFiscalYear]
        , tgt.[GLRecordType] = src.[GLRecordType]
        , tgt.[ChartOfAccounts] = src.[ChartOfAccounts]
        , tgt.[ControllingArea] = src.[ControllingArea]
        , tgt.[FinancialTransactionType] = src.[FinancialTransactionType]
        , tgt.[BusinessTransactionType] = src.[BusinessTransactionType]
        , tgt.[ControllingBusTransacType] = src.[ControllingBusTransacType]
        , tgt.[ReferenceDocumentType] = src.[ReferenceDocumentType]
        , tgt.[LogicalSystem] = src.[LogicalSystem]
        , tgt.[ReferenceDocumentContext] = src.[ReferenceDocumentContext]
        , tgt.[ReferenceDocument] = src.[ReferenceDocument]
        , tgt.[ReferenceDocumentItem] = src.[ReferenceDocumentItem]
        , tgt.[ReferenceDocumentItemGroup] = src.[ReferenceDocumentItemGroup]
        , tgt.[IsReversal] = src.[IsReversal]
        , tgt.[IsReversed] = src.[IsReversed]
        , tgt.[ReversalReferenceDocumentCntxt] = src.[ReversalReferenceDocumentCntxt]
        , tgt.[ReversalReferenceDocument] = src.[ReversalReferenceDocument]
        , tgt.[IsSettlement] = src.[IsSettlement]
        , tgt.[IsSettled] = src.[IsSettled]
        , tgt.[PredecessorReferenceDocType] = src.[PredecessorReferenceDocType]
        , tgt.[PredecessorReferenceDocCntxt] = src.[PredecessorReferenceDocCntxt]
        , tgt.[PredecessorReferenceDocument] = src.[PredecessorReferenceDocument]
        , tgt.[PredecessorReferenceDocItem] = src.[PredecessorReferenceDocItem]
        , tgt.[SourceReferenceDocumentType] = src.[SourceReferenceDocumentType]
        , tgt.[SourceLogicalSystem] = src.[SourceLogicalSystem]
        , tgt.[SourceReferenceDocumentCntxt] = src.[SourceReferenceDocumentCntxt]
        , tgt.[SourceReferenceDocument] = src.[SourceReferenceDocument]
        , tgt.[SourceReferenceDocumentItem] = src.[SourceReferenceDocumentItem]
        , tgt.[SourceReferenceDocSubitem] = src.[SourceReferenceDocSubitem]
        , tgt.[IsCommitment] = src.[IsCommitment]
        , tgt.[JrnlEntryItemObsoleteReason] = src.[JrnlEntryItemObsoleteReason]
        , tgt.[GLAccount] = src.[GLAccount]
        , tgt.[CostCenter] = src.[CostCenter]
        , tgt.[ProfitCenter] = src.[ProfitCenter]
        , tgt.[FunctionalArea] = src.[FunctionalArea]
        , tgt.[BusinessArea] = src.[BusinessArea]
        , tgt.[Segment] = src.[Segment]
        , tgt.[PartnerCostCenter] = src.[PartnerCostCenter]
        , tgt.[PartnerProfitCenter] = src.[PartnerProfitCenter]
        , tgt.[PartnerFunctionalArea] = src.[PartnerFunctionalArea]
        , tgt.[PartnerBusinessArea] = src.[PartnerBusinessArea]
        , tgt.[PartnerCompany] = src.[PartnerCompany]
        , tgt.[PartnerSegment] = src.[PartnerSegment]
        , tgt.[BalanceTransactionCurrency] = src.[BalanceTransactionCurrency]
        , tgt.[AmountInBalanceTransacCrcy] = src.[AmountInBalanceTransacCrcy]
        , tgt.[TransactionCurrency] = src.[TransactionCurrency]
        , tgt.[AmountInTransactionCurrency] = src.[AmountInTransactionCurrency]
        , tgt.[CompanyCodeCurrency] = src.[CompanyCodeCurrency]
        , tgt.[AmountInCompanyCodeCurrency] = src.[AmountInCompanyCodeCurrency]
        , tgt.[GlobalCurrency] = src.[GlobalCurrency]
        , tgt.[AmountInGlobalCurrency] = src.[AmountInGlobalCurrency]
        , tgt.[FreeDefinedCurrency1] = src.[FreeDefinedCurrency1]
        , tgt.[AmountInFreeDefinedCurrency1] = src.[AmountInFreeDefinedCurrency1]
        , tgt.[FreeDefinedCurrency2] = src.[FreeDefinedCurrency2]
        , tgt.[AmountInFreeDefinedCurrency2] = src.[AmountInFreeDefinedCurrency2]
        , tgt.[FreeDefinedCurrency3] = src.[FreeDefinedCurrency3]
        , tgt.[AmountInFreeDefinedCurrency3] = src.[AmountInFreeDefinedCurrency3]
        , tgt.[FreeDefinedCurrency4] = src.[FreeDefinedCurrency4]
        , tgt.[AmountInFreeDefinedCurrency4] = src.[AmountInFreeDefinedCurrency4]
        , tgt.[FreeDefinedCurrency5] = src.[FreeDefinedCurrency5]
        , tgt.[AmountInFreeDefinedCurrency5] = src.[AmountInFreeDefinedCurrency5]
        , tgt.[FreeDefinedCurrency6] = src.[FreeDefinedCurrency6]
        , tgt.[AmountInFreeDefinedCurrency6] = src.[AmountInFreeDefinedCurrency6]
        , tgt.[FreeDefinedCurrency7] = src.[FreeDefinedCurrency7]
        , tgt.[AmountInFreeDefinedCurrency7] = src.[AmountInFreeDefinedCurrency7]
        , tgt.[FreeDefinedCurrency8] = src.[FreeDefinedCurrency8]
        , tgt.[AmountInFreeDefinedCurrency8] = src.[AmountInFreeDefinedCurrency8]
        , tgt.[FixedAmountInGlobalCrcy] = src.[FixedAmountInGlobalCrcy]
        , tgt.[GrpValnFixedAmtInGlobCrcy] = src.[GrpValnFixedAmtInGlobCrcy]
        , tgt.[PrftCtrValnFxdAmtInGlobCrcy] = src.[PrftCtrValnFxdAmtInGlobCrcy]
        , tgt.[FixedAmountInCoCoDeCrcy] = src.[FixedAmountInCoCoDeCrcy]
        , tgt.[TotalPriceVarcInGlobalCrcy] = src.[TotalPriceVarcInGlobalCrcy]
        , tgt.[GrpValnTotPrcVarcInGlobCrcy] = src.[GrpValnTotPrcVarcInGlobCrcy]
        , tgt.[PrftCtrValnTotPrcVarcInGlbCrcy] = src.[PrftCtrValnTotPrcVarcInGlbCrcy]
        , tgt.[FixedPriceVarcInGlobalCrcy] = src.[FixedPriceVarcInGlobalCrcy]
        , tgt.[GrpValnFixedPrcVarcInGlobCrcy] = src.[GrpValnFixedPrcVarcInGlobCrcy]
        , tgt.[PrftCtrValnFxdPrcVarcInGlbCrcy] = src.[PrftCtrValnFxdPrcVarcInGlbCrcy]
        , tgt.[ControllingObjectCurrency] = src.[ControllingObjectCurrency]
        , tgt.[AmountInObjectCurrency] = src.[AmountInObjectCurrency]
        , tgt.[BaseUnit] = src.[BaseUnit]
        , tgt.[Quantity] = src.[Quantity]
        , tgt.[FixedQuantity] = src.[FixedQuantity]
        , tgt.[CostSourceUnit] = src.[CostSourceUnit]
        , tgt.[ValuationQuantity] = src.[ValuationQuantity]
        , tgt.[ValuationFixedQuantity] = src.[ValuationFixedQuantity]
        , tgt.[AdditionalQuantity1Unit] = src.[AdditionalQuantity1Unit]
        , tgt.[AdditionalQuantity1] = src.[AdditionalQuantity1]
        , tgt.[AdditionalQuantity2Unit] = src.[AdditionalQuantity2Unit]
        , tgt.[AdditionalQuantity2] = src.[AdditionalQuantity2]
        , tgt.[AdditionalQuantity3Unit] = src.[AdditionalQuantity3Unit]
        , tgt.[AdditionalQuantity3] = src.[AdditionalQuantity3]
        , tgt.[DebitCreditCode] = src.[DebitCreditCode]
        , tgt.[FiscalPeriod] = src.[FiscalPeriod]
        , tgt.[FiscalYearVariant] = src.[FiscalYearVariant]
        , tgt.[FiscalYearPeriod] = src.[FiscalYearPeriod]
        , tgt.[PostingDate] = src.[PostingDate]
        , tgt.[DocumentDate] = src.[DocumentDate]
        , tgt.[AccountingDocumentType] = src.[AccountingDocumentType]
        , tgt.[AccountingDocumentItem] = src.[AccountingDocumentItem]
        , tgt.[AssignmentReference] = src.[AssignmentReference]
        , tgt.[AccountingDocumentCategory] = src.[AccountingDocumentCategory]
        , tgt.[PostingKey] = src.[PostingKey]
        , tgt.[TransactionTypeDetermination] = src.[TransactionTypeDetermination]
        , tgt.[SubLedgerAcctLineItemType] = src.[SubLedgerAcctLineItemType]
        , tgt.[AccountingDocCreatedByUser] = src.[AccountingDocCreatedByUser]
        , tgt.[LastChangeDateTime] = src.[LastChangeDateTime]
        , tgt.[CreationDateTime] = src.[CreationDateTime]
        , tgt.[CreationDate] = src.[CreationDate]
        , tgt.[EliminationProfitCenter] = src.[EliminationProfitCenter]
        , tgt.[OriginObjectType] = src.[OriginObjectType]
        , tgt.[GLAccountType] = src.[GLAccountType]
        , tgt.[AlternativeGLAccount] = src.[AlternativeGLAccount]
        , tgt.[CountryChartOfAccounts] = src.[CountryChartOfAccounts]
        , tgt.[InvoiceReference] = src.[InvoiceReference]
        , tgt.[InvoiceReferenceFiscalYear] = src.[InvoiceReferenceFiscalYear]
        , tgt.[FollowOnDocumentType] = src.[FollowOnDocumentType]
        , tgt.[InvoiceItemReference] = src.[InvoiceItemReference]
        , tgt.[ReferencePurchaseOrderCategory] = src.[ReferencePurchaseOrderCategory]
        , tgt.[PurchasingDocument] = src.[PurchasingDocument]
        , tgt.[PurchasingDocumentItem] = src.[PurchasingDocumentItem]
        , tgt.[AccountAssignmentNumber] = src.[AccountAssignmentNumber]
        , tgt.[DocumentItemText] = src.[DocumentItemText]
        , tgt.[SalesDocument] = src.[SalesDocument]
        , tgt.[SalesDocumentItem] = src.[SalesDocumentItem]
        , tgt.[Product] = src.[Product]
        , tgt.[Plant] = src.[Plant]
        , tgt.[Supplier] = src.[Supplier]
        , tgt.[Customer] = src.[Customer]
        , tgt.[ServicesRenderedDate] = src.[ServicesRenderedDate]
        , tgt.[ConditionContract] = src.[ConditionContract]
        , tgt.[ExchangeRateDate] = src.[ExchangeRateDate]
        , tgt.[FinancialAccountType] = src.[FinancialAccountType]
        , tgt.[SpecialGLCode] = src.[SpecialGLCode]
        , tgt.[TaxCode] = src.[TaxCode]
        , tgt.[HouseBank] = src.[HouseBank]
        , tgt.[HouseBankAccount] = src.[HouseBankAccount]
        , tgt.[IsOpenItemManaged] = src.[IsOpenItemManaged]
        , tgt.[ClearingDate] = src.[ClearingDate]
        , tgt.[ClearingAccountingDocument] = src.[ClearingAccountingDocument]
        , tgt.[ClearingDocFiscalYear] = src.[ClearingDocFiscalYear]
        , tgt.[AssetDepreciationArea] = src.[AssetDepreciationArea]
        , tgt.[MasterFixedAsset] = src.[MasterFixedAsset]
        , tgt.[FixedAsset] = src.[FixedAsset]
        , tgt.[AssetValueDate] = src.[AssetValueDate]
        , tgt.[AssetTransactionType] = src.[AssetTransactionType]
        , tgt.[AssetAcctTransClassfctn] = src.[AssetAcctTransClassfctn]
        , tgt.[DepreciationFiscalPeriod] = src.[DepreciationFiscalPeriod]
        , tgt.[GroupMasterFixedAsset] = src.[GroupMasterFixedAsset]
        , tgt.[GroupFixedAsset] = src.[GroupFixedAsset]
        , tgt.[AssetClass] = src.[AssetClass]
        , tgt.[CostEstimate] = src.[CostEstimate]
        , tgt.[InventorySpecialStockValnType] = src.[InventorySpecialStockValnType]
        , tgt.[InventorySpecialStockType] = src.[InventorySpecialStockType]
        , tgt.[InventorySpclStkSalesDocument] = src.[InventorySpclStkSalesDocument]
        , tgt.[InventorySpclStkSalesDocItm] = src.[InventorySpclStkSalesDocItm]
        , tgt.[InvtrySpclStockWBSElmntIntID] = src.[InvtrySpclStockWBSElmntIntID]
        , tgt.[InventorySpclStockWBSElement] = src.[InventorySpclStockWBSElement]
        , tgt.[InventorySpecialStockSupplier] = src.[InventorySpecialStockSupplier]
        , tgt.[InventoryValuationType] = src.[InventoryValuationType]
        , tgt.[ValuationArea] = src.[ValuationArea]
        , tgt.[SenderCompanyCode] = src.[SenderCompanyCode]
        , tgt.[SenderGLAccount] = src.[SenderGLAccount]
        , tgt.[SenderAccountAssignment] = src.[SenderAccountAssignment]
        , tgt.[SenderAccountAssignmentType] = src.[SenderAccountAssignmentType]
        , tgt.[ControllingObject] = src.[ControllingObject]
        , tgt.[CostOriginGroup] = src.[CostOriginGroup]
        , tgt.[OriginSenderObject] = src.[OriginSenderObject]
        , tgt.[ControllingDebitCreditCode] = src.[ControllingDebitCreditCode]
        , tgt.[ControllingObjectDebitType] = src.[ControllingObjectDebitType]
        , tgt.[QuantityIsIncomplete] = src.[QuantityIsIncomplete]
        , tgt.[OffsettingAccount] = src.[OffsettingAccount]
        , tgt.[OffsettingAccountType] = src.[OffsettingAccountType]
        , tgt.[OffsettingChartOfAccounts] = src.[OffsettingChartOfAccounts]
        , tgt.[LineItemIsCompleted] = src.[LineItemIsCompleted]
        , tgt.[PersonnelNumber] = src.[PersonnelNumber]
        , tgt.[ControllingObjectClass] = src.[ControllingObjectClass]
        , tgt.[PartnerCompanyCode] = src.[PartnerCompanyCode]
        , tgt.[PartnerControllingObjectClass] = src.[PartnerControllingObjectClass]
        , tgt.[OriginCostCenter] = src.[OriginCostCenter]
        , tgt.[OriginProfitCenter] = src.[OriginProfitCenter]
        , tgt.[OriginCostCtrActivityType] = src.[OriginCostCtrActivityType]
        , tgt.[AccountAssignment] = src.[AccountAssignment]
        , tgt.[AccountAssignmentType] = src.[AccountAssignmentType]
        , tgt.[CostCtrActivityType] = src.[CostCtrActivityType]
        , tgt.[OrderID] = src.[OrderID]
        , tgt.[OrderCategory] = src.[OrderCategory]
        , tgt.[WBSElementInternalID] = src.[WBSElementInternalID]
        , tgt.[WBSElement] = src.[WBSElement]
        , tgt.[PartnerWBSElementInternalID] = src.[PartnerWBSElementInternalID]
        , tgt.[PartnerWBSElement] = src.[PartnerWBSElement]
        , tgt.[ProjectInternalID] = src.[ProjectInternalID]
        , tgt.[Project] = src.[Project]
        , tgt.[PartnerProjectInternalID] = src.[PartnerProjectInternalID]
        , tgt.[PartnerProject] = src.[PartnerProject]
        , tgt.[OperatingConcern] = src.[OperatingConcern]
        , tgt.[ProjectNetwork] = src.[ProjectNetwork]
        , tgt.[RelatedNetworkActivity] = src.[RelatedNetworkActivity]
        , tgt.[BusinessProcess] = src.[BusinessProcess]
        , tgt.[CostObject] = src.[CostObject]
        , tgt.[BillableControl] = src.[BillableControl]
        , tgt.[CostAnalysisResource] = src.[CostAnalysisResource]
        , tgt.[CustomerServiceNotification] = src.[CustomerServiceNotification]
        , tgt.[ServiceDocumentType] = src.[ServiceDocumentType]
        , tgt.[ServiceDocument] = src.[ServiceDocument]
        , tgt.[ServiceDocumentItem] = src.[ServiceDocumentItem]
        , tgt.[PartnerServiceDocumentType] = src.[PartnerServiceDocumentType]
        , tgt.[PartnerServiceDocument] = src.[PartnerServiceDocument]
        , tgt.[PartnerServiceDocumentItem] = src.[PartnerServiceDocumentItem]
        , tgt.[ServiceContractType] = src.[ServiceContractType]
        , tgt.[ServiceContract] = src.[ServiceContract]
        , tgt.[ServiceContractItem] = src.[ServiceContractItem]
        , tgt.[TimeSheetOvertimeCategory] = src.[TimeSheetOvertimeCategory]
        , tgt.[PartnerAccountAssignment] = src.[PartnerAccountAssignment]
        , tgt.[PartnerAccountAssignmentType] = src.[PartnerAccountAssignmentType]
        , tgt.[WorkPackage] = src.[WorkPackage]
        , tgt.[WorkItem] = src.[WorkItem]
        , tgt.[PartnerCostCtrActivityType] = src.[PartnerCostCtrActivityType]
        , tgt.[PartnerOrder] = src.[PartnerOrder]
        , tgt.[PartnerOrderCategory] = src.[PartnerOrderCategory]
        , tgt.[PartnerSalesDocument] = src.[PartnerSalesDocument]
        , tgt.[PartnerSalesDocumentItem] = src.[PartnerSalesDocumentItem]
        , tgt.[PartnerProjectNetwork] = src.[PartnerProjectNetwork]
        , tgt.[PartnerProjectNetworkActivity] = src.[PartnerProjectNetworkActivity]
        , tgt.[PartnerBusinessProcess] = src.[PartnerBusinessProcess]
        , tgt.[PartnerCostObject] = src.[PartnerCostObject]
        , tgt.[BillingDocumentType] = src.[BillingDocumentType]
        , tgt.[SalesOrganization] = src.[SalesOrganization]
        , tgt.[DistributionChannel] = src.[DistributionChannel]
        , tgt.[OrganizationDivision] = src.[OrganizationDivision]
        , tgt.[SoldProduct] = src.[SoldProduct]
        , tgt.[SoldProductGroup] = src.[SoldProductGroup]
        , tgt.[CustomerGroup] = src.[CustomerGroup]
        , tgt.[CustomerSupplierCountry] = src.[CustomerSupplierCountry]
        , tgt.[CustomerSupplierIndustry] = src.[CustomerSupplierIndustry]
        , tgt.[SalesDistrict] = src.[SalesDistrict]
        , tgt.[BillToParty] = src.[BillToParty]
        , tgt.[ShipToParty] = src.[ShipToParty]
        , tgt.[CustomerSupplierCorporateGroup] = src.[CustomerSupplierCorporateGroup]
        , tgt.[CashLedgerCompanyCode] = src.[CashLedgerCompanyCode]
        , tgt.[CashLedgerAccount] = src.[CashLedgerAccount]
        , tgt.[FinancialManagementArea] = src.[FinancialManagementArea]
        , tgt.[FundsCenter] = src.[FundsCenter]
        , tgt.[FundedProgram] = src.[FundedProgram]
        , tgt.[Fund] = src.[Fund]
        , tgt.[GrantID] = src.[GrantID]
        , tgt.[BudgetPeriod] = src.[BudgetPeriod]
        , tgt.[PartnerFund] = src.[PartnerFund]
        , tgt.[PartnerGrant] = src.[PartnerGrant]
        , tgt.[PartnerBudgetPeriod] = src.[PartnerBudgetPeriod]
        , tgt.[PubSecBudgetAccount] = src.[PubSecBudgetAccount]
        , tgt.[PubSecBudgetAccountCoCode] = src.[PubSecBudgetAccountCoCode]
        , tgt.[PubSecBudgetCnsmpnDate] = src.[PubSecBudgetCnsmpnDate]
        , tgt.[PubSecBudgetCnsmpnFsclPeriod] = src.[PubSecBudgetCnsmpnFsclPeriod]
        , tgt.[PubSecBudgetCnsmpnFsclYear] = src.[PubSecBudgetCnsmpnFsclYear]
        , tgt.[PubSecBudgetIsRelevant] = src.[PubSecBudgetIsRelevant]
        , tgt.[PubSecBudgetCnsmpnType] = src.[PubSecBudgetCnsmpnType]
        , tgt.[PubSecBudgetCnsmpnAmtType] = src.[PubSecBudgetCnsmpnAmtType]
        , tgt.[JointVenture] = src.[JointVenture]
        , tgt.[JointVentureEquityGroup] = src.[JointVentureEquityGroup]
        , tgt.[JointVentureCostRecoveryCode] = src.[JointVentureCostRecoveryCode]
        , tgt.[JointVenturePartner] = src.[JointVenturePartner]
        , tgt.[JointVentureBillingType] = src.[JointVentureBillingType]
        , tgt.[JointVentureEquityType] = src.[JointVentureEquityType]
        , tgt.[JointVentureProductionDate] = src.[JointVentureProductionDate]
        , tgt.[JointVentureBillingDate] = src.[JointVentureBillingDate]
        , tgt.[JointVentureOperationalDate] = src.[JointVentureOperationalDate]
        , tgt.[CutbackRun] = src.[CutbackRun]
        , tgt.[JointVentureAccountingActivity] = src.[JointVentureAccountingActivity]
        , tgt.[PartnerVenture] = src.[PartnerVenture]
        , tgt.[PartnerEquityGroup] = src.[PartnerEquityGroup]
        , tgt.[SenderCostRecoveryCode] = src.[SenderCostRecoveryCode]
        , tgt.[CutbackAccount] = src.[CutbackAccount]
        , tgt.[CutbackCostObject] = src.[CutbackCostObject]
        , tgt.[SettlementReferenceDate] = src.[SettlementReferenceDate]
        , tgt.[AccrualObjectType] = src.[AccrualObjectType]
        , tgt.[AccrualObject] = src.[AccrualObject]
        , tgt.[AccrualSubobject] = src.[AccrualSubobject]
        , tgt.[AccrualItemType] = src.[AccrualItemType]
        , tgt.[AccrualValueDate] = src.[AccrualValueDate]
        , tgt.[FinancialValuationObjectType] = src.[FinancialValuationObjectType]
        , tgt.[FinancialValuationObject] = src.[FinancialValuationObject]
        , tgt.[FinancialValuationSubobject] = src.[FinancialValuationSubobject]
        , tgt.[NetDueDate] = src.[NetDueDate]
        , tgt.[CreditRiskClass] = src.[CreditRiskClass]
        , tgt.[WorkCenterInternalID] = src.[WorkCenterInternalID]
        , tgt.[OrderOperation] = src.[OrderOperation]
        , tgt.[OrderItem] = src.[OrderItem]
        , tgt.[OrderSuboperation] = src.[OrderSuboperation]
        , tgt.[Equipment] = src.[Equipment]
        , tgt.[FunctionalLocation] = src.[FunctionalLocation]
        , tgt.[Assembly] = src.[Assembly]
        , tgt.[MaintenanceActivityType] = src.[MaintenanceActivityType]
        , tgt.[MaintenanceOrderPlanningCode] = src.[MaintenanceOrderPlanningCode]
        , tgt.[MaintPriorityType] = src.[MaintPriorityType]
        , tgt.[MaintPriority] = src.[MaintPriority]
        , tgt.[SuperiorOrder] = src.[SuperiorOrder]
        , tgt.[ProductGroup] = src.[ProductGroup]
        , tgt.[MaintenanceOrderIsPlanned] = src.[MaintenanceOrderIsPlanned]
        , tgt.[t_applicationId] = src.[t_applicationId]
        , tgt.[t_jobId] = src.[t_jobId]
        , tgt.[t_jobDtm] = src.[t_jobDtm]
        , tgt.[t_jobBy] = src.[t_jobBy]
        , tgt.[t_filePath] = src.[t_filePath]
        , tgt.[t_extractionDtm] = src.[t_extractionDtm]
        , tgt.[t_lastActionBy] = CURRENT_USER
        , tgt.[t_lastActionCd] = (case
                                     when src.[ODQ_CHANGEMODE] = 'U' and src.[ODQ_ENTITYCNTR] = 1
                                         then 'U'
                                     when src.[ODQ_CHANGEMODE] = 'D' and src.[ODQ_ENTITYCNTR] = -1
                                         then 'D'
                                 end)
        , tgt.[t_lastActionDtm] = GETUTCDATE()
    FROM
        [base_s4h_cax].[I_GLAccountLineItemRawData_active] as tgt
    INNER JOIN
        [base_s4h_cax].[vw_I_GLAccountLineItemRawData] as src
        ON
            tgt.MANDT                   = src.MANDT
            AND
            tgt.[SourceLedger]          = src.[SourceLedger]
            AND
            tgt.[CompanyCode]           = src.[CompanyCode]
            AND
            tgt.[FiscalYear]            = src.[FiscalYear]
            AND
            tgt.[AccountingDocument]    = src.[AccountingDocument]
            AND
            tgt.[LedgerGLLineItem]      = src.[LedgerGLLineItem]
            AND
            (
                (
                    src.[ODQ_CHANGEMODE]  = 'U'
                    AND 
                    src.[ODQ_ENTITYCNTR] = 1
                )
                OR
                (
                    src.[ODQ_CHANGEMODE] = 'D'
                    AND 
                    src.[ODQ_ENTITYCNTR] = -1
                )
            )
   


    -- Insert new records in the base table based on the delta dataset

    INSERT INTO
        [base_s4h_cax].[I_GLAccountLineItemRawData_active] (
                [MANDT]
            ,   [SourceLedger]
            ,   [CompanyCode]
            ,   [FiscalYear]
            ,   [AccountingDocument]
            ,   [LedgerGLLineItem]
            ,   [LedgerFiscalYear]
            ,   [GLRecordType]
            ,   [ChartOfAccounts]
            ,   [ControllingArea]
            ,   [FinancialTransactionType]
            ,   [BusinessTransactionType]
            ,   [ControllingBusTransacType]
            ,   [ReferenceDocumentType]
            ,   [LogicalSystem]
            ,   [ReferenceDocumentContext]
            ,   [ReferenceDocument]
            ,   [ReferenceDocumentItem]
            ,   [ReferenceDocumentItemGroup]
            ,   [IsReversal]
            ,   [IsReversed]
            ,   [ReversalReferenceDocumentCntxt]
            ,   [ReversalReferenceDocument]
            ,   [IsSettlement]
            ,   [IsSettled]
            ,   [PredecessorReferenceDocType]
            ,   [PredecessorReferenceDocCntxt]
            ,   [PredecessorReferenceDocument]
            ,   [PredecessorReferenceDocItem]
            ,   [SourceReferenceDocumentType]
            ,   [SourceLogicalSystem]
            ,   [SourceReferenceDocumentCntxt]
            ,   [SourceReferenceDocument]
            ,   [SourceReferenceDocumentItem]
            ,   [SourceReferenceDocSubitem]
            ,   [IsCommitment]
            ,   [JrnlEntryItemObsoleteReason]
            ,   [GLAccount]
            ,   [CostCenter]
            ,   [ProfitCenter]
            ,   [FunctionalArea]
            ,   [BusinessArea]
            ,   [Segment]
            ,   [PartnerCostCenter]
            ,   [PartnerProfitCenter]
            ,   [PartnerFunctionalArea]
            ,   [PartnerBusinessArea]
            ,   [PartnerCompany]
            ,   [PartnerSegment]
            ,   [BalanceTransactionCurrency]
            ,   [AmountInBalanceTransacCrcy]
            ,   [TransactionCurrency]
            ,   [AmountInTransactionCurrency]
            ,   [CompanyCodeCurrency]
            ,   [AmountInCompanyCodeCurrency]
            ,   [GlobalCurrency]
            ,   [AmountInGlobalCurrency]
            ,   [FreeDefinedCurrency1]
            ,   [AmountInFreeDefinedCurrency1]
            ,   [FreeDefinedCurrency2]
            ,   [AmountInFreeDefinedCurrency2]
            ,   [FreeDefinedCurrency3]
            ,   [AmountInFreeDefinedCurrency3]
            ,   [FreeDefinedCurrency4]
            ,   [AmountInFreeDefinedCurrency4]
            ,   [FreeDefinedCurrency5]
            ,   [AmountInFreeDefinedCurrency5]
            ,   [FreeDefinedCurrency6]
            ,   [AmountInFreeDefinedCurrency6]
            ,   [FreeDefinedCurrency7]
            ,   [AmountInFreeDefinedCurrency7]
            ,   [FreeDefinedCurrency8]
            ,   [AmountInFreeDefinedCurrency8]
            ,   [FixedAmountInGlobalCrcy]
            ,   [GrpValnFixedAmtInGlobCrcy]
            ,   [PrftCtrValnFxdAmtInGlobCrcy]
            ,   [FixedAmountInCoCoDeCrcy]
            ,   [TotalPriceVarcInGlobalCrcy]
            ,   [GrpValnTotPrcVarcInGlobCrcy]
            ,   [PrftCtrValnTotPrcVarcInGlbCrcy]
            ,   [FixedPriceVarcInGlobalCrcy]
            ,   [GrpValnFixedPrcVarcInGlobCrcy]
            ,   [PrftCtrValnFxdPrcVarcInGlbCrcy]
            ,   [ControllingObjectCurrency]
            ,   [AmountInObjectCurrency]
            ,   [BaseUnit]
            ,   [Quantity]
            ,   [FixedQuantity]
            ,   [CostSourceUnit]
            ,   [ValuationQuantity]
            ,   [ValuationFixedQuantity]
            ,   [AdditionalQuantity1Unit]
            ,   [AdditionalQuantity1]
            ,   [AdditionalQuantity2Unit]
            ,   [AdditionalQuantity2]
            ,   [AdditionalQuantity3Unit]
            ,   [AdditionalQuantity3]
            ,   [DebitCreditCode]
            ,   [FiscalPeriod]
            ,   [FiscalYearVariant]
            ,   [FiscalYearPeriod]
            ,   [PostingDate]
            ,   [DocumentDate]
            ,   [AccountingDocumentType]
            ,   [AccountingDocumentItem]
            ,   [AssignmentReference]
            ,   [AccountingDocumentCategory]
            ,   [PostingKey]
            ,   [TransactionTypeDetermination]
            ,   [SubLedgerAcctLineItemType]
            ,   [AccountingDocCreatedByUser]
            ,   [LastChangeDateTime]
            ,   [CreationDateTime]
            ,   [CreationDate]
            ,   [EliminationProfitCenter]
            ,   [OriginObjectType]
            ,   [GLAccountType]
            ,   [AlternativeGLAccount]
            ,   [CountryChartOfAccounts]
            ,   [InvoiceReference]
            ,   [InvoiceReferenceFiscalYear]
            ,   [FollowOnDocumentType]
            ,   [InvoiceItemReference]
            ,   [ReferencePurchaseOrderCategory]
            ,   [PurchasingDocument]
            ,   [PurchasingDocumentItem]
            ,   [AccountAssignmentNumber]
            ,   [DocumentItemText]
            ,   [SalesDocument]
            ,   [SalesDocumentItem]
            ,   [Product]
            ,   [Plant]
            ,   [Supplier]
            ,   [Customer]
            ,   [ServicesRenderedDate]
            ,   [ConditionContract]
            ,   [ExchangeRateDate]
            ,   [FinancialAccountType]
            ,   [SpecialGLCode]
            ,   [TaxCode]
            ,   [HouseBank]
            ,   [HouseBankAccount]
            ,   [IsOpenItemManaged]
            ,   [ClearingDate]
            ,   [ClearingAccountingDocument]
            ,   [ClearingDocFiscalYear]
            ,   [AssetDepreciationArea]
            ,   [MasterFixedAsset]
            ,   [FixedAsset]
            ,   [AssetValueDate]
            ,   [AssetTransactionType]
            ,   [AssetAcctTransClassfctn]
            ,   [DepreciationFiscalPeriod]
            ,   [GroupMasterFixedAsset]
            ,   [GroupFixedAsset]
            ,   [AssetClass]
            ,   [CostEstimate]
            ,   [InventorySpecialStockValnType]
            ,   [InventorySpecialStockType]
            ,   [InventorySpclStkSalesDocument]
            ,   [InventorySpclStkSalesDocItm]
            ,   [InvtrySpclStockWBSElmntIntID]
            ,   [InventorySpclStockWBSElement]
            ,   [InventorySpecialStockSupplier]
            ,   [InventoryValuationType]
            ,   [ValuationArea]
            ,   [SenderCompanyCode]
            ,   [SenderGLAccount]
            ,   [SenderAccountAssignment]
            ,   [SenderAccountAssignmentType]
            ,   [ControllingObject]
            ,   [CostOriginGroup]
            ,   [OriginSenderObject]
            ,   [ControllingDebitCreditCode]
            ,   [ControllingObjectDebitType]
            ,   [QuantityIsIncomplete]
            ,   [OffsettingAccount]
            ,   [OffsettingAccountType]
            ,   [OffsettingChartOfAccounts]
            ,   [LineItemIsCompleted]
            ,   [PersonnelNumber]
            ,   [ControllingObjectClass]
            ,   [PartnerCompanyCode]
            ,   [PartnerControllingObjectClass]
            ,   [OriginCostCenter]
            ,   [OriginProfitCenter]
            ,   [OriginCostCtrActivityType]
            ,   [AccountAssignment]
            ,   [AccountAssignmentType]
            ,   [CostCtrActivityType]
            ,   [OrderID]
            ,   [OrderCategory]
            ,   [WBSElementInternalID]
            ,   [WBSElement]
            ,   [PartnerWBSElementInternalID]
            ,   [PartnerWBSElement]
            ,   [ProjectInternalID]
            ,   [Project]
            ,   [PartnerProjectInternalID]
            ,   [PartnerProject]
            ,   [OperatingConcern]
            ,   [ProjectNetwork]
            ,   [RelatedNetworkActivity]
            ,   [BusinessProcess]
            ,   [CostObject]
            ,   [BillableControl]
            ,   [CostAnalysisResource]
            ,   [CustomerServiceNotification]
            ,   [ServiceDocumentType]
            ,   [ServiceDocument]
            ,   [ServiceDocumentItem]
            ,   [PartnerServiceDocumentType]
            ,   [PartnerServiceDocument]
            ,   [PartnerServiceDocumentItem]
            ,   [ServiceContractType]
            ,   [ServiceContract]
            ,   [ServiceContractItem]
            ,   [TimeSheetOvertimeCategory]
            ,   [PartnerAccountAssignment]
            ,   [PartnerAccountAssignmentType]
            ,   [WorkPackage]
            ,   [WorkItem]
            ,   [PartnerCostCtrActivityType]
            ,   [PartnerOrder]
            ,   [PartnerOrderCategory]
            ,   [PartnerSalesDocument]
            ,   [PartnerSalesDocumentItem]
            ,   [PartnerProjectNetwork]
            ,   [PartnerProjectNetworkActivity]
            ,   [PartnerBusinessProcess]
            ,   [PartnerCostObject]
            ,   [BillingDocumentType]
            ,   [SalesOrganization]
            ,   [DistributionChannel]
            ,   [OrganizationDivision]
            ,   [SoldProduct]
            ,   [SoldProductGroup]
            ,   [CustomerGroup]
            ,   [CustomerSupplierCountry]
            ,   [CustomerSupplierIndustry]
            ,   [SalesDistrict]
            ,   [BillToParty]
            ,   [ShipToParty]
            ,   [CustomerSupplierCorporateGroup]
            ,   [CashLedgerCompanyCode]
            ,   [CashLedgerAccount]
            ,   [FinancialManagementArea]
            ,   [FundsCenter]
            ,   [FundedProgram]
            ,   [Fund]
            ,   [GrantID]
            ,   [BudgetPeriod]
            ,   [PartnerFund]
            ,   [PartnerGrant]
            ,   [PartnerBudgetPeriod]
            ,   [PubSecBudgetAccount]
            ,   [PubSecBudgetAccountCoCode]
            ,   [PubSecBudgetCnsmpnDate]
            ,   [PubSecBudgetCnsmpnFsclPeriod]
            ,   [PubSecBudgetCnsmpnFsclYear]
            ,   [PubSecBudgetIsRelevant]
            ,   [PubSecBudgetCnsmpnType]
            ,   [PubSecBudgetCnsmpnAmtType]
            ,   [JointVenture]
            ,   [JointVentureEquityGroup]
            ,   [JointVentureCostRecoveryCode]
            ,   [JointVenturePartner]
            ,   [JointVentureBillingType]
            ,   [JointVentureEquityType]
            ,   [JointVentureProductionDate]
            ,   [JointVentureBillingDate]
            ,   [JointVentureOperationalDate]
            ,   [CutbackRun]
            ,   [JointVentureAccountingActivity]
            ,   [PartnerVenture]
            ,   [PartnerEquityGroup]
            ,   [SenderCostRecoveryCode]
            ,   [CutbackAccount]
            ,   [CutbackCostObject]
            ,   [SettlementReferenceDate]
            ,   [AccrualObjectType]
            ,   [AccrualObject]
            ,   [AccrualSubobject]
            ,   [AccrualItemType]
            ,   [AccrualValueDate]
            ,   [FinancialValuationObjectType]
            ,   [FinancialValuationObject]
            ,   [FinancialValuationSubobject]
            ,   [NetDueDate]
            ,   [CreditRiskClass]
            ,   [WorkCenterInternalID]
            ,   [OrderOperation]
            ,   [OrderItem]
            ,   [OrderSuboperation]
            ,   [Equipment]
            ,   [FunctionalLocation]
            ,   [Assembly]
            ,   [MaintenanceActivityType]
            ,   [MaintenanceOrderPlanningCode]
            ,   [MaintPriorityType]
            ,   [MaintPriority]
            ,   [SuperiorOrder]
            ,   [ProductGroup]
            ,   [MaintenanceOrderIsPlanned]
            ,   [t_applicationId]
            ,   [t_jobId]
            ,   [t_jobDtm]
            ,   [t_jobBy]
            ,   [t_filePath]
            ,   [t_extractionDtm]
            ,   [t_lastActionBy]
            ,   [t_lastActionCd]
            ,   [t_lastActionDtm]
        )
        SELECT
                [MANDT]
            ,   [SourceLedger]
            ,   [CompanyCode]
            ,   [FiscalYear]
            ,   [AccountingDocument]
            ,   [LedgerGLLineItem]
            ,   [LedgerFiscalYear]
            ,   [GLRecordType]
            ,   [ChartOfAccounts]
            ,   [ControllingArea]
            ,   [FinancialTransactionType]
            ,   [BusinessTransactionType]
            ,   [ControllingBusTransacType]
            ,   [ReferenceDocumentType]
            ,   [LogicalSystem]
            ,   [ReferenceDocumentContext]
            ,   [ReferenceDocument]
            ,   [ReferenceDocumentItem]
            ,   [ReferenceDocumentItemGroup]
            ,   [IsReversal]
            ,   [IsReversed]
            ,   [ReversalReferenceDocumentCntxt]
            ,   [ReversalReferenceDocument]
            ,   [IsSettlement]
            ,   [IsSettled]
            ,   [PredecessorReferenceDocType]
            ,   [PredecessorReferenceDocCntxt]
            ,   [PredecessorReferenceDocument]
            ,   [PredecessorReferenceDocItem]
            ,   [SourceReferenceDocumentType]
            ,   [SourceLogicalSystem]
            ,   [SourceReferenceDocumentCntxt]
            ,   [SourceReferenceDocument]
            ,   [SourceReferenceDocumentItem]
            ,   [SourceReferenceDocSubitem]
            ,   [IsCommitment]
            ,   [JrnlEntryItemObsoleteReason]
            ,   [GLAccount]
            ,   [CostCenter]
            ,   [ProfitCenter]
            ,   [FunctionalArea]
            ,   [BusinessArea]
            ,   [Segment]
            ,   [PartnerCostCenter]
            ,   [PartnerProfitCenter]
            ,   [PartnerFunctionalArea]
            ,   [PartnerBusinessArea]
            ,   [PartnerCompany]
            ,   [PartnerSegment]
            ,   [BalanceTransactionCurrency]
            ,   [AmountInBalanceTransacCrcy]
            ,   [TransactionCurrency]
            ,   [AmountInTransactionCurrency]
            ,   [CompanyCodeCurrency]
            ,   [AmountInCompanyCodeCurrency]
            ,   [GlobalCurrency]
            ,   [AmountInGlobalCurrency]
            ,   [FreeDefinedCurrency1]
            ,   [AmountInFreeDefinedCurrency1]
            ,   [FreeDefinedCurrency2]
            ,   [AmountInFreeDefinedCurrency2]
            ,   [FreeDefinedCurrency3]
            ,   [AmountInFreeDefinedCurrency3]
            ,   [FreeDefinedCurrency4]
            ,   [AmountInFreeDefinedCurrency4]
            ,   [FreeDefinedCurrency5]
            ,   [AmountInFreeDefinedCurrency5]
            ,   [FreeDefinedCurrency6]
            ,   [AmountInFreeDefinedCurrency6]
            ,   [FreeDefinedCurrency7]
            ,   [AmountInFreeDefinedCurrency7]
            ,   [FreeDefinedCurrency8]
            ,   [AmountInFreeDefinedCurrency8]
            ,   [FixedAmountInGlobalCrcy]
            ,   [GrpValnFixedAmtInGlobCrcy]
            ,   [PrftCtrValnFxdAmtInGlobCrcy]
            ,   [FixedAmountInCoCoDeCrcy]
            ,   [TotalPriceVarcInGlobalCrcy]
            ,   [GrpValnTotPrcVarcInGlobCrcy]
            ,   [PrftCtrValnTotPrcVarcInGlbCrcy]
            ,   [FixedPriceVarcInGlobalCrcy]
            ,   [GrpValnFixedPrcVarcInGlobCrcy]
            ,   [PrftCtrValnFxdPrcVarcInGlbCrcy]
            ,   [ControllingObjectCurrency]
            ,   [AmountInObjectCurrency]
            ,   [BaseUnit]
            ,   [Quantity]
            ,   [FixedQuantity]
            ,   [CostSourceUnit]
            ,   [ValuationQuantity]
            ,   [ValuationFixedQuantity]
            ,   [AdditionalQuantity1Unit]
            ,   [AdditionalQuantity1]
            ,   [AdditionalQuantity2Unit]
            ,   [AdditionalQuantity2]
            ,   [AdditionalQuantity3Unit]
            ,   [AdditionalQuantity3]
            ,   [DebitCreditCode]
            ,   [FiscalPeriod]
            ,   [FiscalYearVariant]
            ,   [FiscalYearPeriod]
            ,   [PostingDate]
            ,   [DocumentDate]
            ,   [AccountingDocumentType]
            ,   [AccountingDocumentItem]
            ,   [AssignmentReference]
            ,   [AccountingDocumentCategory]
            ,   [PostingKey]
            ,   [TransactionTypeDetermination]
            ,   [SubLedgerAcctLineItemType]
            ,   [AccountingDocCreatedByUser]
            ,   [LastChangeDateTime]
            ,   [CreationDateTime]
            ,   [CreationDate]
            ,   [EliminationProfitCenter]
            ,   [OriginObjectType]
            ,   [GLAccountType]
            ,   [AlternativeGLAccount]
            ,   [CountryChartOfAccounts]
            ,   [InvoiceReference]
            ,   [InvoiceReferenceFiscalYear]
            ,   [FollowOnDocumentType]
            ,   [InvoiceItemReference]
            ,   [ReferencePurchaseOrderCategory]
            ,   [PurchasingDocument]
            ,   [PurchasingDocumentItem]
            ,   [AccountAssignmentNumber]
            ,   [DocumentItemText]
            ,   [SalesDocument]
            ,   [SalesDocumentItem]
            ,   [Product]
            ,   [Plant]
            ,   [Supplier]
            ,   [Customer]
            ,   [ServicesRenderedDate]
            ,   [ConditionContract]
            ,   [ExchangeRateDate]
            ,   [FinancialAccountType]
            ,   [SpecialGLCode]
            ,   [TaxCode]
            ,   [HouseBank]
            ,   [HouseBankAccount]
            ,   [IsOpenItemManaged]
            ,   [ClearingDate]
            ,   [ClearingAccountingDocument]
            ,   [ClearingDocFiscalYear]
            ,   [AssetDepreciationArea]
            ,   [MasterFixedAsset]
            ,   [FixedAsset]
            ,   [AssetValueDate]
            ,   [AssetTransactionType]
            ,   [AssetAcctTransClassfctn]
            ,   [DepreciationFiscalPeriod]
            ,   [GroupMasterFixedAsset]
            ,   [GroupFixedAsset]
            ,   [AssetClass]
            ,   [CostEstimate]
            ,   [InventorySpecialStockValnType]
            ,   [InventorySpecialStockType]
            ,   [InventorySpclStkSalesDocument]
            ,   [InventorySpclStkSalesDocItm]
            ,   [InvtrySpclStockWBSElmntIntID]
            ,   [InventorySpclStockWBSElement]
            ,   [InventorySpecialStockSupplier]
            ,   [InventoryValuationType]
            ,   [ValuationArea]
            ,   [SenderCompanyCode]
            ,   [SenderGLAccount]
            ,   [SenderAccountAssignment]
            ,   [SenderAccountAssignmentType]
            ,   [ControllingObject]
            ,   [CostOriginGroup]
            ,   [OriginSenderObject]
            ,   [ControllingDebitCreditCode]
            ,   [ControllingObjectDebitType]
            ,   [QuantityIsIncomplete]
            ,   [OffsettingAccount]
            ,   [OffsettingAccountType]
            ,   [OffsettingChartOfAccounts]
            ,   [LineItemIsCompleted]
            ,   [PersonnelNumber]
            ,   [ControllingObjectClass]
            ,   [PartnerCompanyCode]
            ,   [PartnerControllingObjectClass]
            ,   [OriginCostCenter]
            ,   [OriginProfitCenter]
            ,   [OriginCostCtrActivityType]
            ,   [AccountAssignment]
            ,   [AccountAssignmentType]
            ,   [CostCtrActivityType]
            ,   [OrderID]
            ,   [OrderCategory]
            ,   [WBSElementInternalID]
            ,   [WBSElement]
            ,   [PartnerWBSElementInternalID]
            ,   [PartnerWBSElement]
            ,   [ProjectInternalID]
            ,   [Project]
            ,   [PartnerProjectInternalID]
            ,   [PartnerProject]
            ,   [OperatingConcern]
            ,   [ProjectNetwork]
            ,   [RelatedNetworkActivity]
            ,   [BusinessProcess]
            ,   [CostObject]
            ,   [BillableControl]
            ,   [CostAnalysisResource]
            ,   [CustomerServiceNotification]
            ,   [ServiceDocumentType]
            ,   [ServiceDocument]
            ,   [ServiceDocumentItem]
            ,   [PartnerServiceDocumentType]
            ,   [PartnerServiceDocument]
            ,   [PartnerServiceDocumentItem]
            ,   [ServiceContractType]
            ,   [ServiceContract]
            ,   [ServiceContractItem]
            ,   [TimeSheetOvertimeCategory]
            ,   [PartnerAccountAssignment]
            ,   [PartnerAccountAssignmentType]
            ,   [WorkPackage]
            ,   [WorkItem]
            ,   [PartnerCostCtrActivityType]
            ,   [PartnerOrder]
            ,   [PartnerOrderCategory]
            ,   [PartnerSalesDocument]
            ,   [PartnerSalesDocumentItem]
            ,   [PartnerProjectNetwork]
            ,   [PartnerProjectNetworkActivity]
            ,   [PartnerBusinessProcess]
            ,   [PartnerCostObject]
            ,   [BillingDocumentType]
            ,   [SalesOrganization]
            ,   [DistributionChannel]
            ,   [OrganizationDivision]
            ,   [SoldProduct]
            ,   [SoldProductGroup]
            ,   [CustomerGroup]
            ,   [CustomerSupplierCountry]
            ,   [CustomerSupplierIndustry]
            ,   [SalesDistrict]
            ,   [BillToParty]
            ,   [ShipToParty]
            ,   [CustomerSupplierCorporateGroup]
            ,   [CashLedgerCompanyCode]
            ,   [CashLedgerAccount]
            ,   [FinancialManagementArea]
            ,   [FundsCenter]
            ,   [FundedProgram]
            ,   [Fund]
            ,   [GrantID]
            ,   [BudgetPeriod]
            ,   [PartnerFund]
            ,   [PartnerGrant]
            ,   [PartnerBudgetPeriod]
            ,   [PubSecBudgetAccount]
            ,   [PubSecBudgetAccountCoCode]
            ,   [PubSecBudgetCnsmpnDate]
            ,   [PubSecBudgetCnsmpnFsclPeriod]
            ,   [PubSecBudgetCnsmpnFsclYear]
            ,   [PubSecBudgetIsRelevant]
            ,   [PubSecBudgetCnsmpnType]
            ,   [PubSecBudgetCnsmpnAmtType]
            ,   [JointVenture]
            ,   [JointVentureEquityGroup]
            ,   [JointVentureCostRecoveryCode]
            ,   [JointVenturePartner]
            ,   [JointVentureBillingType]
            ,   [JointVentureEquityType]
            ,   [JointVentureProductionDate]
            ,   [JointVentureBillingDate]
            ,   [JointVentureOperationalDate]
            ,   [CutbackRun]
            ,   [JointVentureAccountingActivity]
            ,   [PartnerVenture]
            ,   [PartnerEquityGroup]
            ,   [SenderCostRecoveryCode]
            ,   [CutbackAccount]
            ,   [CutbackCostObject]
            ,   [SettlementReferenceDate]
            ,   [AccrualObjectType]
            ,   [AccrualObject]
            ,   [AccrualSubobject]
            ,   [AccrualItemType]
            ,   [AccrualValueDate]
            ,   [FinancialValuationObjectType]
            ,   [FinancialValuationObject]
            ,   [FinancialValuationSubobject]
            ,   [NetDueDate]
            ,   [CreditRiskClass]
            ,   [WorkCenterInternalID]
            ,   [OrderOperation]
            ,   [OrderItem]
            ,   [OrderSuboperation]
            ,   [Equipment]
            ,   [FunctionalLocation]
            ,   [Assembly]
            ,   [MaintenanceActivityType]
            ,   [MaintenanceOrderPlanningCode]
            ,   [MaintPriorityType]
            ,   [MaintPriority]
            ,   [SuperiorOrder]
            ,   [ProductGroup]
            ,   [MaintenanceOrderIsPlanned]
            ,   [t_applicationId]
            ,   [t_jobId]
            ,   [t_jobDtm]
            ,   [t_jobBy]
            ,   [t_filePath]
            ,   [t_extractionDtm]
            ,   CURRENT_USER as [t_lastActionBy]
            ,   (case
                      when src.[ODQ_CHANGEMODE] = '' and src.[ODQ_ENTITYCNTR] = 0
                          then 'I'
                      when src.[ODQ_CHANGEMODE] = 'U' and src.[ODQ_ENTITYCNTR] = 1
                          then 'I'
                      when src.[ODQ_CHANGEMODE] = 'D' and src.[ODQ_ENTITYCNTR] = -1
                          then 'D'
                      when src.[ODQ_CHANGEMODE] = 'С' and src.[ODQ_ENTITYCNTR] = 1
                          then 'I'
                  end) as [t_lastActionCd]
            ,   GETUTCDATE() as [t_lastActionDtm]
        FROM [base_s4h_cax].[vw_I_GLAccountLineItemRawData] as src
        WHERE NOT EXISTS (
            SELECT 
                [MANDT],
                [SourceLedger],
                [CompanyCode],
                [FiscalYear],
                [AccountingDocument],
                [LedgerGLLineItem]
            FROM 
                [base_s4h_cax].[I_GLAccountLineItemRawData_active] tgt2
            WHERE 
            tgt2.MANDT                   = src.MANDT
            AND
            tgt2.[SourceLedger]          = src.[SourceLedger]
            AND
            tgt2.[CompanyCode]           = src.[CompanyCode]
            AND
            tgt2.[FiscalYear]            = src.[FiscalYear]
            AND
            tgt2.[AccountingDocument]    = src.[AccountingDocument]
            AND
            tgt2.[LedgerGLLineItem]      = src.[LedgerGLLineItem]
        )

END
