CREATE PROC [base_s4h_uat_caa].[sp_load_CustomerReturnDeliveryItem_base]
	@t_applicationId [varchar](7),
	@t_jobId [varchar](36),
	@t_lastDtm [datetime],
	@t_lastActionBy [nvarchar](20),
	@t_filePath [nvarchar](1024)
AS
BEGIN
	
	TRUNCATE TABLE [base_s4h_uat_caa].[I_CustomerReturnDeliveryItem]

	INSERT INTO [base_s4h_uat_caa].[I_CustomerReturnDeliveryItem](
		[CustomerReturnDelivery]
		,[CustomerReturnDeliveryItem]
		,[DeliveryDocumentItemCategory]
		,[SalesDocumentItemType]
		,[HigherLvlItmOfBatSpltItm]
		,[CreatedByUser]
		,[CreationDate]
		,[CreationTime]
		,[LastChangeDate]
		,[DistributionChannel]
		,[Division]
		,[SalesGroup]
		,[SalesOffice]
		,[DepartmentClassificationByCust]
		,[Material]
		,[MaterialByCustomer]
		,[OriginallyRequestedMaterial]
		,[InternationalArticleNumber]
		,[Batch]
		,[BatchClassification]
		,[BatchBySupplier]
		,[MaterialIsIntBatchManaged]
		,[MaterialIsBatchManaged]
		,[MaterialGroup]
		,[MaterialFreightGroup]
		,[AdditionalMaterialGroup1]
		,[AdditionalMaterialGroup2]
		,[AdditionalMaterialGroup3]
		,[AdditionalMaterialGroup4]
		,[AdditionalMaterialGroup5]
		,[Plant]
		,[Warehouse]
		,[StorageLocation]
		,[StorageBin]
		,[StorageType]
		,[InventorySpecialStockType]
		,[ShelfLifeExpirationDate]
		,[NumberOfSerialNumbers]
		,[ProductConfiguration]
		,[ProductHierarchyNode]
		,[ManufactureDate]
		,[DeliveryDocumentItemText]
		,[HigherLevelItem]
		,[ActualDeliveryQuantity]
		,[QuantityIsFixed]
		,[OriginalDeliveryQuantity]
		,[DeliveryQuantityUnit]
		,[ActualDeliveredQtyInBaseUnit]
		,[BaseUnit]
		,[DeliveryToBaseQuantityDnmntr]
		,[DeliveryToBaseQuantityNmrtr]
		,[ProductAvailabilityDate]
		,[ProductAvailabilityTime]
		,[DeliveryGroup]
		,[ItemGrossWeight]
		,[ItemNetWeight]
		,[ItemWeightUnit]
		,[ItemVolume]
		,[ItemVolumeUnit]
		,[InspectionLot]
		,[InspectionPartialLot]
		,[PartialDeliveryIsAllowed]
		,[UnlimitedOverdeliveryIsAllowed]
		,[OverdelivTolrtdLmtRatioInPct]
		,[UnderdelivTolrtdLmtRatioInPct]
		,[BOMExplosion]
		,[WarehouseStockCategory]
		,[IsNotGoodsMovementsRelevant]
		,[StockType]
		,[GLAccount]
		,[GoodsMovementReasonCode]
		,[IsCompletelyDelivered]
		,[PickingControl]
		,[LoadingGroup]
		,[GoodsMovementType]
		,[TransportationGroup]
		,[ReceivingPoint]
		,[FixedShipgProcgDurationInDays]
		,[VarblShipgProcgDurationInDays]
		,[ProofOfDeliveryRelevanceCode]
		,[ItemIsBillingRelevant]
		,[ItemBillingBlockReason]
		,[BusinessArea]
		,[ControllingArea]
		,[ProfitabilitySegment]
		,[ProfitCenter]
		,[InventoryValuationType]
		,[IsSeparateValuation]
		,[ConsumptionPosting]
		,[OrderID]
		,[OrderItem]
		,[CostCenter]
		,[ReferenceSDDocument]
		,[ReferenceSDDocumentItem]
		,[ReferenceSDDocumentCategory]
		,[ReferenceDocumentLogicalSystem]
		,[AdditionalCustomerGroup1]
		,[AdditionalCustomerGroup2]
		,[AdditionalCustomerGroup3]
		,[AdditionalCustomerGroup4]
		,[AdditionalCustomerGroup5]
		,[RetailPromotion]
		,[SDProcessStatus]
		,[PickingConfirmationStatus]
		,[PickingStatus]
		,[PutawayStatus]
		,[WarehouseActivityStatus]
		,[PackingStatus]
		,[GoodsMovementStatus]
		,[DeliveryRelatedBillingStatus]
		,[ProofOfDeliveryStatus]
		,[ItemGeneralIncompletionStatus]
		,[ItemDeliveryIncompletionStatus]
		,[ItemPickingIncompletionStatus]
		,[ItemGdsMvtIncompletionSts]
		,[ItemPackingIncompletionStatus]
		,[ItemBillingIncompletionStatus]
		,[IntercompanyBillingStatus]
		,[ChmlCmplncStatus]
		,[DangerousGoodsStatus]
		,[SafetyDataSheetStatus]
		,[RequirementSegment]
		,[StockSegment]
		,[ProductSeasonYear]
		,[ProductSeason]
		,[ProductCollection]
		,[ProductTheme]
		,[ProductCharacteristic1]
		,[ProductCharacteristic2]
		,[ProductCharacteristic3]
		,[t_applicationId]
		,[t_jobId]
		,[t_lastDtm]
		,[t_lastActionBy]
		,[t_filePath]
	)
	SELECT
		[CustomerReturnDelivery]
		,CONVERT([char](6), [CustomerReturnDeliveryItem]) AS [CustomerReturnDeliveryItem]
		,[DeliveryDocumentItemCategory]
		,[SalesDocumentItemType]
		,CONVERT([char](6), [HigherLvlItmOfBatSpltItm]) AS [HigherLvlItmOfBatSpltItm]
		,[CreatedByUser]
		,CASE [CreationDate]
			WHEN '00000000' THEN '19000101' 
			ELSE CONVERT([date], [CreationDate], 112) 
		 END AS [CreationDate]
		,CASE LEN([CreationTime])
			WHEN 6 THEN CONVERT([time](0), LEFT([CreationTime], 2)+':'+SUBSTRING([CreationTime],3,2)+':'+SUBSTRING([CreationTime],5,2))
			WHEN 5 THEN CONVERT([time](0), LEFT([CreationTime], 1)+':'+SUBSTRING([CreationTime],2,2)+':'+SUBSTRING([CreationTime],4,2))
		 END AS [CreationTime]
		,CASE [LastChangeDate]
			WHEN '00000000' THEN '19000101' 
			ELSE CONVERT([date], [LastChangeDate], 112) 
		 END AS [LastChangeDate]
		,[DistributionChannel]
		,[Division]
		,[SalesGroup]
		,[SalesOffice]
		,[DepartmentClassificationByCust]
		,[Material]
		,[MaterialByCustomer]
		,[OriginallyRequestedMaterial]
		,[InternationalArticleNumber]
		,[Batch]
		,CONVERT([char](18), [BatchClassification]) AS [BatchClassification]
		,[BatchBySupplier]
		,[MaterialIsIntBatchManaged]
		,[MaterialIsBatchManaged]
		,[MaterialGroup]
		,[MaterialFreightGroup]
		,[AdditionalMaterialGroup1]
		,[AdditionalMaterialGroup2]
		,[AdditionalMaterialGroup3]
		,[AdditionalMaterialGroup4]
		,[AdditionalMaterialGroup5]
		,[Plant]
		,[Warehouse]
		,[StorageLocation]
		,[StorageBin]
		,[StorageType]
		,[InventorySpecialStockType]
		,CASE [ShelfLifeExpirationDate]
			WHEN '00000000' THEN '19000101' 
			ELSE CONVERT([date], [ShelfLifeExpirationDate], 112) 
		 END AS [ShelfLifeExpirationDate]
		,CONVERT([int], [NumberOfSerialNumbers]) AS [NumberOfSerialNumbers]
		,CONVERT([char](18), [ProductConfiguration]) AS [ProductConfiguration]
		,[ProductHierarchyNode]
		,CASE [ManufactureDate]
			WHEN '00000000' THEN '19000101' 
			ELSE CONVERT([date], [ManufactureDate], 112) 
		 END AS [ManufactureDate]
		,[DeliveryDocumentItemText]
		,CONVERT([char](6), [HigherLevelItem]) AS [HigherLevelItem]
		,CONVERT([decimal](13,3), CASE 
									WHEN RIGHT(RTRIM([ActualDeliveryQuantity]), 1) = '-'
									THEN '-' + REPLACE([ActualDeliveryQuantity], '-','')
									ELSE [ActualDeliveryQuantity]
								  END) AS [ActualDeliveryQuantity]
		,[QuantityIsFixed]
		,CONVERT([decimal](13,3), CASE 
									WHEN RIGHT(RTRIM([OriginalDeliveryQuantity]), 1) = '-'
									THEN '-' + REPLACE([OriginalDeliveryQuantity], '-','')
									ELSE [OriginalDeliveryQuantity]
								  END) AS [OriginalDeliveryQuantity]
		,[DeliveryQuantityUnit]
		,CONVERT([decimal](13,3), CASE 
									WHEN RIGHT(RTRIM([ActualDeliveredQtyInBaseUnit]), 1) = '-'
									THEN '-' + REPLACE([ActualDeliveredQtyInBaseUnit], '-','')
									ELSE [ActualDeliveredQtyInBaseUnit]
								  END) AS [ActualDeliveredQtyInBaseUnit]
		,[BaseUnit]
		,CONVERT([decimal](5), CASE 
									WHEN RIGHT(RTRIM([DeliveryToBaseQuantityDnmntr]), 1) = '-'
									THEN '-' + REPLACE([DeliveryToBaseQuantityDnmntr], '-','')
									ELSE [DeliveryToBaseQuantityDnmntr]
								  END) AS [DeliveryToBaseQuantityDnmntr]
		,CONVERT([decimal](5), CASE 
									WHEN RIGHT(RTRIM([DeliveryToBaseQuantityNmrtr]), 1) = '-'
									THEN '-' + REPLACE([DeliveryToBaseQuantityNmrtr], '-','')
									ELSE [DeliveryToBaseQuantityNmrtr]
								  END) AS [DeliveryToBaseQuantityNmrtr]
		,CASE [ProductAvailabilityDate]
			WHEN '00000000' THEN '19000101' 
			ELSE CONVERT([date], [ProductAvailabilityDate], 112) 
		 END AS [ProductAvailabilityDate]
		,CASE LEN([ProductAvailabilityTime])
			WHEN 6 THEN CONVERT([time](0), LEFT([ProductAvailabilityTime], 2)+':'+SUBSTRING([ProductAvailabilityTime],3,2)+':'+SUBSTRING([ProductAvailabilityTime],5,2))
			WHEN 5 THEN CONVERT([time](0), LEFT([ProductAvailabilityTime], 1)+':'+SUBSTRING([ProductAvailabilityTime],2,2)+':'+SUBSTRING([ProductAvailabilityTime],4,2))
		 END AS [ProductAvailabilityTime]
		,CONVERT([char](3), [DeliveryGroup]) AS [DeliveryGroup]
		,CONVERT([decimal](15,3), CASE 
									WHEN RIGHT(RTRIM([ItemGrossWeight]), 1) = '-'
									THEN '-' + REPLACE([ItemGrossWeight], '-','')
									ELSE [ItemGrossWeight]
								  END) AS [ItemGrossWeight]
		,CONVERT([decimal](15,3), CASE 
									WHEN RIGHT(RTRIM([ItemNetWeight]), 1) = '-'
									THEN '-' + REPLACE([ItemNetWeight], '-','')
									ELSE [ItemNetWeight]
								  END) AS [ItemNetWeight]
		,[ItemWeightUnit]
		,CONVERT([decimal](15,3), CASE 
									WHEN RIGHT(RTRIM([ItemVolume]), 1) = '-'
									THEN '-' + REPLACE([ItemVolume], '-','')
									ELSE [ItemVolume]
								  END) AS [ItemVolume]
		,[ItemVolumeUnit]
		,CONVERT([char](12), [InspectionLot]) AS [InspectionLot]
		,CONVERT([char](6), [InspectionPartialLot]) AS [InspectionPartialLot]
		,[PartialDeliveryIsAllowed]
		,[UnlimitedOverdeliveryIsAllowed]
		,CONVERT([decimal](3,1), CASE 
									WHEN RIGHT(RTRIM([OverdelivTolrtdLmtRatioInPct]), 1) = '-'
									THEN '-' + REPLACE([OverdelivTolrtdLmtRatioInPct], '-','')
									ELSE [OverdelivTolrtdLmtRatioInPct]
								  END) AS [OverdelivTolrtdLmtRatioInPct]
		,CONVERT([decimal](3,1), CASE 
									WHEN RIGHT(RTRIM([UnderdelivTolrtdLmtRatioInPct]), 1) = '-'
									THEN '-' + REPLACE([UnderdelivTolrtdLmtRatioInPct], '-','')
									ELSE [UnderdelivTolrtdLmtRatioInPct]
								  END) AS [UnderdelivTolrtdLmtRatioInPct]
		,[BOMExplosion]
		,[WarehouseStockCategory]
		,[IsNotGoodsMovementsRelevant]
		,[StockType]
		,[GLAccount]
		,CONVERT([char](4), [GoodsMovementReasonCode]) AS [GoodsMovementReasonCode]
		,[IsCompletelyDelivered]
		,[PickingControl]
		,[LoadingGroup]
		,[GoodsMovementType]
		,[TransportationGroup]
		,[ReceivingPoint]
		,CONVERT([decimal](5,2), CASE 
									WHEN RIGHT(RTRIM([FixedShipgProcgDurationInDays]), 1) = '-'
									THEN '-' + REPLACE([FixedShipgProcgDurationInDays], '-','')
									ELSE [FixedShipgProcgDurationInDays]
								  END) AS [FixedShipgProcgDurationInDays]
		,CONVERT([decimal](5,2), CASE 
									WHEN RIGHT(RTRIM([VarblShipgProcgDurationInDays]), 1) = '-'
									THEN '-' + REPLACE([VarblShipgProcgDurationInDays], '-','')
									ELSE [VarblShipgProcgDurationInDays]
								  END) AS [VarblShipgProcgDurationInDays]
		,[ProofOfDeliveryRelevanceCode]
		,[ItemIsBillingRelevant]
		,[ItemBillingBlockReason]
		,[BusinessArea]
		,[ControllingArea]
		,CONVERT([char](10), [ProfitabilitySegment]) AS [ProfitabilitySegment]
		,[ProfitCenter]
		,[InventoryValuationType]
		,[IsSeparateValuation]
		,[ConsumptionPosting]
		,[OrderID]
		,CONVERT([char](4), [OrderItem]) AS [OrderItem]
		,[CostCenter]
		,[ReferenceSDDocument]
		,CONVERT([char](6), [ReferenceSDDocumentItem]) AS [ReferenceSDDocumentItem]
		,[ReferenceSDDocumentCategory]
		,[ReferenceDocumentLogicalSystem]
		,[AdditionalCustomerGroup1]
		,[AdditionalCustomerGroup2]
		,[AdditionalCustomerGroup3]
		,[AdditionalCustomerGroup4]
		,[AdditionalCustomerGroup5]
		,[RetailPromotion]
		,[SDProcessStatus]
		,[PickingConfirmationStatus]
		,[PickingStatus]
		,[PutawayStatus]
		,[WarehouseActivityStatus]
		,[PackingStatus]
		,[GoodsMovementStatus]
		,[DeliveryRelatedBillingStatus]
		,[ProofOfDeliveryStatus]
		,[ItemGeneralIncompletionStatus]
		,[ItemDeliveryIncompletionStatus]
		,[ItemPickingIncompletionStatus]
		,[ItemGdsMvtIncompletionSts]
		,[ItemPackingIncompletionStatus]
		,[ItemBillingIncompletionStatus]
		,[IntercompanyBillingStatus]
		,[ChmlCmplncStatus]
		,[DangerousGoodsStatus]
		,[SafetyDataSheetStatus]
		,[RequirementSegment]
		,[StockSegment]
		,[ProductSeasonYear]
		,[ProductSeason]
		,[ProductCollection]
		,[ProductTheme]
		,[ProductCharacteristic1]
		,[ProductCharacteristic2]
		,[ProductCharacteristic3]
		,@t_applicationId AS t_applicationId
		,@t_jobId AS t_jobId
		,@t_lastDtm AS t_lastDtm
		,@t_lastActionBy AS t_lastActionBy
		,@t_filePath AS t_filePath
	FROM [base_s4h_uat_caa].[I_CustomerReturnDeliveryItem_staging]
END
