CREATE PROC [base_s4h_uat_caa].[sp_load_ProductSalesDelivery_base]
	@t_applicationId [varchar](7),
	@t_jobId [varchar](36),
	@t_lastDtm [datetime],
	@t_lastActionBy [nvarchar](20),
	@t_filePath [nvarchar](1024)
AS
BEGIN
	TRUNCATE TABLE [base_s4h_uat_caa].[I_ProductSalesDelivery]

	INSERT INTO [base_s4h_uat_caa].[I_ProductSalesDelivery](
		 [Product]
		,[ProductSalesOrg]
		,[ProductDistributionChnl]
		,[MinimumOrderQuantity]
		,[SupplyingPlant]
		,[PriceSpecificationProductGroup]
		,[AccountDetnProductGroup]
		,[DeliveryNoteProcMinDelivQty]
		,[ItemCategoryGroup]
		,[DeliveryQuantityUnit]
		,[DeliveryQuantity]
		,[ProductSalesStatus]
		,[ProductSalesStatusValidityDate]
		,[SalesMeasureUnit]
		,[IsMarkedForDeletion]
		,[ProductHierarchy]
		,[FirstSalesSpecProductGroup]
		,[SecondSalesSpecProductGroup]
		,[ThirdSalesSpecProductGroup]
		,[FourthSalesSpecProductGroup]
		,[FifthSalesSpecProductGroup]
		,[MinimumMakeToOrderOrderQty]
		,[LogisticsStatisticsGroup]
		,[VolumeRebateGroup]
		,[ProductCommissionGroup]
		,[CashDiscountIsDeductible]
		,[PricingReferenceProduct]
		,[AssortmentGrade]
		,[StoreListingProcedure]
		,[DistrCntrListingProcedure]
		,[StoreListingStartDate]
		,[StoreListingEndDate]
		,[DistrCntrListingStartDate]
		,[DistrCntrListingEndDate]
		,[StoreSaleStartDate]
		,[StoreSaleEndDate]
		,[DistrCntrSaleStartDate]
		,[DistrCntrSaleEndDate]
		,[RoundingProfile]
		,[ProductUnitGroup]
		,[MaxDeliveryQtyStoreOrder]
		,[PriceFixingCategory]
		,[VariableSalesUnitIsNotAllowed]
		,[CompetitionPressureCategory]
		,[ProductHasAttributeID01]
		,[ProductHasAttributeID02]
		,[ProductHasAttributeID03]
		,[ProductHasAttributeID04]
		,[ProductHasAttributeID05]
		,[ProductHasAttributeID06]
		,[ProductHasAttributeID07]
		,[ProductHasAttributeID08]
		,[ProductHasAttributeID09]
		,[ProductHasAttributeID10]
		,[IsActiveEntity]
		,[ProdExtAssortmentPriority]
		--,[BaseUnit]
		,[SubscrpnContrDfltDuration]
		,[SubscrpnContrAltvDuration1]
		,[SubscrpnContrAltvDuration2]
		,[SubscrpnContrDurationUnit]
		,[SubscrpnContrDfltExtnDurn]
		,[SubscrpnContrAltvExtnDurn1]
		,[SubscrpnContrAltvExtnDurn2]
		,[SubscrpnContrExtnDurnUnit]
		,[t_applicationId]
		,[t_jobId]
		,[t_lastDtm]
		,[t_lastActionBy]
		,[t_filePath]
	)
	SELECT 	
		 [Product]
		,[ProductSalesOrg]
		,[ProductDistributionChnl]
		,CONVERT([decimal](13,3), [MinimumOrderQuantity]) AS [MinimumOrderQuantity]
		,[SupplyingPlant]
		,[PriceSpecificationProductGroup]
		,[AccountDetnProductGroup]
		,CONVERT([decimal](13,3), [DeliveryNoteProcMinDelivQty]) AS [DeliveryNoteProcMinDelivQty]
		,[ItemCategoryGroup]
		,[DeliveryQuantityUnit]
		,CONVERT([decimal](13,3), [DeliveryQuantity]) AS [DeliveryQuantity]
		,[ProductSalesStatus]
		,CASE [ProductSalesStatusValidityDate]
			WHEN '00000000' THEN '19000101' 
			ELSE CONVERT([date], [ProductSalesStatusValidityDate], 112) 
		 END AS [ProductSalesStatusValidityDate]
		,[SalesMeasureUnit]
		,[IsMarkedForDeletion]
		,[ProductHierarchy]
		,[FirstSalesSpecProductGroup]
		,[SecondSalesSpecProductGroup]
		,[ThirdSalesSpecProductGroup]
		,[FourthSalesSpecProductGroup]
		,[FifthSalesSpecProductGroup]
		,CONVERT([decimal](13,3), [MinimumMakeToOrderOrderQty]) AS [MinimumMakeToOrderOrderQty]
		,[LogisticsStatisticsGroup]
		,[VolumeRebateGroup]
		,[ProductCommissionGroup]
		,[CashDiscountIsDeductible]
		,[PricingReferenceProduct]
		,[AssortmentGrade]
		,[StoreListingProcedure]
		,[DistrCntrListingProcedure]
		,CASE [StoreListingStartDate]
			WHEN '00000000' THEN '19000101' 
			ELSE CONVERT([date], [StoreListingStartDate], 112) 
		 END AS [StoreListingStartDate]
		,CASE [StoreListingEndDate]
			WHEN '00000000' THEN '19000101' 
			ELSE CONVERT([date], [StoreListingEndDate], 112) 
		 END AS [StoreListingEndDate]
		,CASE [DistrCntrListingStartDate]
			WHEN '00000000' THEN '19000101' 
			ELSE CONVERT([date], [DistrCntrListingStartDate], 112) 
		 END AS [DistrCntrListingStartDate]
		,CASE [DistrCntrListingEndDate]
			WHEN '00000000' THEN '19000101' 
			ELSE CONVERT([date], [DistrCntrListingEndDate], 112) 
		 END AS [DistrCntrListingEndDate]
		,CASE [StoreSaleStartDate]
			WHEN '00000000' THEN '19000101' 
			ELSE CONVERT([date], [StoreSaleStartDate], 112) 
		 END AS [StoreSaleStartDate]
		,CASE [StoreSaleEndDate]
			WHEN '00000000' THEN '19000101' 
			ELSE CONVERT([date], [StoreSaleEndDate], 112) 
		 END AS [StoreSaleEndDate]
		,CASE [DistrCntrSaleStartDate]
			WHEN '00000000' THEN '19000101' 
			ELSE CONVERT([date], [DistrCntrSaleStartDate], 112) 
		 END AS [DistrCntrSaleStartDate]
		,CASE [DistrCntrSaleEndDate]
			WHEN '00000000' THEN '19000101' 
			ELSE CONVERT([date], [DistrCntrSaleEndDate], 112) 
		 END AS [DistrCntrSaleEndDate]
		,[RoundingProfile]
		,[ProductUnitGroup]
		,CONVERT([decimal](13,3), [MaxDeliveryQtyStoreOrder]) AS [MaxDeliveryQtyStoreOrder]
		,[PriceFixingCategory]
		,[VariableSalesUnitIsNotAllowed]
		,[CompetitionPressureCategory]
		,[ProductHasAttributeID01]
		,[ProductHasAttributeID02]
		,[ProductHasAttributeID03]
		,[ProductHasAttributeID04]
		,[ProductHasAttributeID05]
		,[ProductHasAttributeID06]
		,[ProductHasAttributeID07]
		,[ProductHasAttributeID08]
		,[ProductHasAttributeID09]
		,[ProductHasAttributeID10]
		,[IsActiveEntity]
		,[ProdExtAssortmentPriority]
		--,[BaseUnit]
		,[SubscrpnContrDfltDuration]
		,[SubscrpnContrAltvDuration1]
		,[SubscrpnContrAltvDuration2]
		,[SubscrpnContrDurationUnit]
		,[SubscrpnContrDfltExtnDurn]
		,[SubscrpnContrAltvExtnDurn1]
		,[SubscrpnContrAltvExtnDurn2]
		,[SubscrpnContrExtnDurnUnit]
		,@t_applicationId AS t_applicationId
		,@t_jobId AS t_jobId
		,@t_lastDtm AS t_lastDtm
		,@t_lastActionBy AS t_lastActionBy
		,@t_filePath AS t_filePath
	FROM [base_s4h_uat_caa].[I_ProductSalesDelivery_staging]
END