CREATE PROC [base_s4h_cax].[sp_load_C_SalesDocumentItemDEX]
AS
BEGIN

    -- Update or Delete(marks as Delete - 'D') records the base table based on the delta dataset
  UPDATE
    [base_s4h_cax].[C_SalesDocumentItemDEX_active]
  SET
    [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SDDocumentCategory] = src.[SDDocumentCategory]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SalesDocumentType] = src.[SalesDocumentType]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SalesDocumentItemCategory] = src.[SalesDocumentItemCategory]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[IsReturnsItem] = src.[IsReturnsItem]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[CreationDate] = src.[CreationDate]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[CreationTime] = src.[CreationTime]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[LastChangeDate] = src.[LastChangeDate]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SalesOrganization] = src.[SalesOrganization]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[DistributionChannel] = src.[DistributionChannel]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[Division] = src.[Division]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SalesGroup] = src.[SalesGroup]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SalesOffice] = src.[SalesOffice]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[InternationalArticleNumber] = src.[InternationalArticleNumber]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[Batch] = src.[Batch]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[Material] = src.[Material]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[OriginallyRequestedMaterial] = src.[OriginallyRequestedMaterial]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[MaterialSubstitutionReason] = src.[MaterialSubstitutionReason]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[MaterialGroup] = src.[MaterialGroup]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[AdditionalMaterialGroup1] = src.[AdditionalMaterialGroup1]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[AdditionalMaterialGroup2] = src.[AdditionalMaterialGroup2]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[AdditionalMaterialGroup3] = src.[AdditionalMaterialGroup3]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[AdditionalMaterialGroup4] = src.[AdditionalMaterialGroup4]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[AdditionalMaterialGroup5] = src.[AdditionalMaterialGroup5]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SoldToParty] = src.[SoldToParty]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[AdditionalCustomerGroup1] = src.[AdditionalCustomerGroup1]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[AdditionalCustomerGroup2] = src.[AdditionalCustomerGroup2]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[AdditionalCustomerGroup3] = src.[AdditionalCustomerGroup3]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[AdditionalCustomerGroup4] = src.[AdditionalCustomerGroup4]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[AdditionalCustomerGroup5] = src.[AdditionalCustomerGroup5]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ShipToParty] = src.[ShipToParty]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[PayerParty] = src.[PayerParty]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[BillToParty] = src.[BillToParty]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SDDocumentReason] = src.[SDDocumentReason]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SalesDocumentDate] = src.[SalesDocumentDate]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[OrderQuantity] = src.[OrderQuantity]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[OrderQuantityUnit] = src.[OrderQuantityUnit]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[TargetQuantity] = src.[TargetQuantity]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[TargetQuantityUnit] = src.[TargetQuantityUnit]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[TargetToBaseQuantityDnmntr] = src.[TargetToBaseQuantityDnmntr]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[TargetToBaseQuantityNmrtr] = src.[TargetToBaseQuantityNmrtr]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[OrderToBaseQuantityDnmntr] = src.[OrderToBaseQuantityDnmntr]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[OrderToBaseQuantityNmrtr] = src.[OrderToBaseQuantityNmrtr]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ConfdDelivQtyInOrderQtyUnit] = src.[ConfdDelivQtyInOrderQtyUnit]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[TargetDelivQtyInOrderQtyUnit] = src.[TargetDelivQtyInOrderQtyUnit]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ConfdDeliveryQtyInBaseUnit] = src.[ConfdDeliveryQtyInBaseUnit]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[BaseUnit] = src.[BaseUnit]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ItemGrossWeight] = src.[ItemGrossWeight]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ItemNetWeight] = src.[ItemNetWeight]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ItemWeightUnit] = src.[ItemWeightUnit]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ItemVolume] = src.[ItemVolume]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ItemVolumeUnit] = src.[ItemVolumeUnit]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ServicesRenderedDate] = src.[ServicesRenderedDate]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SalesDistrict] = src.[SalesDistrict]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[CustomerGroup] = src.[CustomerGroup]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[HdrOrderProbabilityInPercent] = src.[HdrOrderProbabilityInPercent]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ItemOrderProbabilityInPercent] = src.[ItemOrderProbabilityInPercent]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SalesDocumentRjcnReason] = src.[SalesDocumentRjcnReason]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[PricingDate] = src.[PricingDate]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ExchangeRateDate] = src.[ExchangeRateDate]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[PriceDetnExchangeRate] = src.[PriceDetnExchangeRate]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[StatisticalValueControl] = src.[StatisticalValueControl]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[NetAmount] = src.[NetAmount]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[TransactionCurrency] = src.[TransactionCurrency]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SalesOrganizationCurrency] = src.[SalesOrganizationCurrency]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[NetPriceAmount] = src.[NetPriceAmount]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[NetPriceQuantity] = src.[NetPriceQuantity]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[NetPriceQuantityUnit] = src.[NetPriceQuantityUnit]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[TaxAmount] = src.[TaxAmount]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[CostAmount] = src.[CostAmount]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[Subtotal1Amount] = src.[Subtotal1Amount]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[Subtotal2Amount] = src.[Subtotal2Amount]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[Subtotal3Amount] = src.[Subtotal3Amount]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[Subtotal4Amount] = src.[Subtotal4Amount]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[Subtotal5Amount] = src.[Subtotal5Amount]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[Subtotal6Amount] = src.[Subtotal6Amount]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ShippingPoint] = src.[ShippingPoint]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ShippingType] = src.[ShippingType]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[DeliveryPriority] = src.[DeliveryPriority]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[InventorySpecialStockType] = src.[InventorySpecialStockType]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[RequestedDeliveryDate] = src.[RequestedDeliveryDate]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ShippingCondition] = src.[ShippingCondition]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[DeliveryBlockReason] = src.[DeliveryBlockReason]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[Plant] = src.[Plant]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[StorageLocation] = src.[StorageLocation]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[Route] = src.[Route]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[IncotermsClassification] = src.[IncotermsClassification]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[IncotermsVersion] = src.[IncotermsVersion]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[IncotermsTransferLocation] = src.[IncotermsTransferLocation]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[IncotermsLocation1] = src.[IncotermsLocation1]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[IncotermsLocation2] = src.[IncotermsLocation2]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[MinDeliveryQtyInBaseUnit] = src.[MinDeliveryQtyInBaseUnit]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[UnlimitedOverdeliveryIsAllowed] = src.[UnlimitedOverdeliveryIsAllowed]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[OverdelivTolrtdLmtRatioInPct] = src.[OverdelivTolrtdLmtRatioInPct]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[UnderdelivTolrtdLmtRatioInPct] = src.[UnderdelivTolrtdLmtRatioInPct]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[PartialDeliveryIsAllowed] = src.[PartialDeliveryIsAllowed]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[BindingPeriodValidityStartDate] = src.[BindingPeriodValidityStartDate]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[BindingPeriodValidityEndDate] = src.[BindingPeriodValidityEndDate]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[OutlineAgreementTargetAmount] = src.[OutlineAgreementTargetAmount]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[BillingDocumentDate] = src.[BillingDocumentDate]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[BillingCompanyCode] = src.[BillingCompanyCode]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[HeaderBillingBlockReason] = src.[HeaderBillingBlockReason]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ItemBillingBlockReason] = src.[ItemBillingBlockReason]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[FiscalYear] = src.[FiscalYear]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[FiscalPeriod] = src.[FiscalPeriod]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[CustomerAccountAssignmentGroup] = src.[CustomerAccountAssignmentGroup]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ExchangeRateType] = src.[ExchangeRateType]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[Currency] = src.[Currency]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[FiscalYearVariant] = src.[FiscalYearVariant]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[BusinessArea] = src.[BusinessArea]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ProfitCenter] = src.[ProfitCenter]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[OrderID] = src.[OrderID]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ProfitabilitySegment] = src.[ProfitabilitySegment]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ControllingArea] = src.[ControllingArea]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ReferenceSDDocument] = src.[ReferenceSDDocument]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ReferenceSDDocumentItem] = src.[ReferenceSDDocumentItem]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ReferenceSDDocumentCategory] = src.[ReferenceSDDocumentCategory]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[OriginSDDocument] = src.[OriginSDDocument]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[OriginSDDocumentItem] = src.[OriginSDDocumentItem]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[OverallSDProcessStatus] = src.[OverallSDProcessStatus]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[OverallTotalDeliveryStatus] = src.[OverallTotalDeliveryStatus]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[OverallOrdReltdBillgStatus] = src.[OverallOrdReltdBillgStatus]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[TotalCreditCheckStatus] = src.[TotalCreditCheckStatus]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[DeliveryBlockStatus] = src.[DeliveryBlockStatus]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[BillingBlockStatus] = src.[BillingBlockStatus]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[TotalSDDocReferenceStatus] = src.[TotalSDDocReferenceStatus]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SDDocReferenceStatus] = src.[SDDocReferenceStatus]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[OverallSDDocumentRejectionSts] = src.[OverallSDDocumentRejectionSts]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SDDocumentRejectionStatus] = src.[SDDocumentRejectionStatus]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[OverallTotalSDDocRefStatus] = src.[OverallTotalSDDocRefStatus]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[OverallSDDocReferenceStatus] = src.[OverallSDDocReferenceStatus]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ItemGeneralIncompletionStatus] = src.[ItemGeneralIncompletionStatus]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ItemBillingIncompletionStatus] = src.[ItemBillingIncompletionStatus]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[PricingIncompletionStatus] = src.[PricingIncompletionStatus]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[ItemDeliveryIncompletionStatus] = src.[ItemDeliveryIncompletionStatus]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SDoc_ControllingObject] = src.[SDoc_ControllingObject]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SDItem_ControllingObject] = src.[SDItem_ControllingObject]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[CorrespncExternalReference] = src.[CorrespncExternalReference]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[t_jobId] = src.[t_jobId]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[t_jobDtm] = src.[t_jobDtm]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[t_jobBy] = src.[t_jobBy]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[t_filePath] = src.[t_filePath]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[t_extractionDtm] = src.[t_extractionDtm]
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[t_lastActionBy] = SYSTEM_USER
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[t_lastActionCd] = (
      CASE
        WHEN
          src.[ODQ_CHANGEMODE] = 'U' 
          AND
          src.[ODQ_ENTITYCNTR] = 1
        THEN 'U'
        WHEN 
          src.[ODQ_CHANGEMODE] = 'D'
          AND
          src.[ODQ_ENTITYCNTR] = -1
        THEN 'D'
      END
    )
  , [base_s4h_cax].[C_SalesDocumentItemDEX_active].[t_lastActionDtm] = GETUTCDATE()
  FROM
    [base_s4h_cax].[vw_C_SalesDocumentItemDEX_delta] AS src
  WHERE
    [base_s4h_cax].[C_SalesDocumentItemDEX_active].[MANDT] = src.[MANDT]
    AND
    [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SalesDocument] = src.[SalesDocument]
    AND
    [base_s4h_cax].[C_SalesDocumentItemDEX_active].[SalesDocumentItem] = src.[SalesDocumentItem]

        -- [base_s4h_cax].[vw_C_SalesDocumentItemDEX] as src
        -- ON
        --     [base_s4h_cax].[C_SalesDocumentItemDEX_active].MANDT = src.MANDT
        --     AND
        --     [base_s4h_cax].[C_SalesDocumentItemDEX_active].SalesDocument = src.SalesDocument
        --     AND
        --     [base_s4h_cax].[C_SalesDocumentItemDEX_active].SalesDocumentItem = src.SalesDocumentItem
        --     and
        --     (
        --         (
        --             src.[ODQ_CHANGEMODE]  = 'U'
        --             AND
        --             src.[ODQ_ENTITYCNTR] = 1
        --         )
        --         OR
        --         (
        --             src.[ODQ_CHANGEMODE] = 'D'
        --             AND
        --             src.[ODQ_ENTITYCNTR] = -1
        --         )
        --     )

   -- Insert new records in the base table based on the delta dataset

  INSERT INTO
    [base_s4h_cax].[C_SalesDocumentItemDEX_active] (
      [MANDT]
    , [SalesDocument]
    , [SalesDocumentItem]
    , [SDDocumentCategory]
    , [SalesDocumentType]
    , [SalesDocumentItemCategory]
    , [IsReturnsItem]
    , [CreationDate]
    , [CreationTime]
    , [LastChangeDate]
    , [SalesOrganization]
    , [DistributionChannel]
    , [Division]
    , [SalesGroup]
    , [SalesOffice]
    , [InternationalArticleNumber]
    , [Batch]
    , [Material]
    , [OriginallyRequestedMaterial]
    , [MaterialSubstitutionReason]
    , [MaterialGroup]
    , [AdditionalMaterialGroup1]
    , [AdditionalMaterialGroup2]
    , [AdditionalMaterialGroup3]
    , [AdditionalMaterialGroup4]
    , [AdditionalMaterialGroup5]
    , [SoldToParty]
    , [AdditionalCustomerGroup1]
    , [AdditionalCustomerGroup2]
    , [AdditionalCustomerGroup3]
    , [AdditionalCustomerGroup4]
    , [AdditionalCustomerGroup5]
    , [ShipToParty]
    , [PayerParty]
    , [BillToParty]
    , [SDDocumentReason]
    , [SalesDocumentDate]
    , [OrderQuantity]
    , [OrderQuantityUnit]
    , [TargetQuantity]
    , [TargetQuantityUnit]
    , [TargetToBaseQuantityDnmntr]
    , [TargetToBaseQuantityNmrtr]
    , [OrderToBaseQuantityDnmntr]
    , [OrderToBaseQuantityNmrtr]
    , [ConfdDelivQtyInOrderQtyUnit]
    , [TargetDelivQtyInOrderQtyUnit]
    , [ConfdDeliveryQtyInBaseUnit]
    , [BaseUnit]
    , [ItemGrossWeight]
    , [ItemNetWeight]
    , [ItemWeightUnit]
    , [ItemVolume]
    , [ItemVolumeUnit]
    , [ServicesRenderedDate]
    , [SalesDistrict]
    , [CustomerGroup]
    , [HdrOrderProbabilityInPercent]
    , [ItemOrderProbabilityInPercent]
    , [SalesDocumentRjcnReason]
    , [PricingDate]
    , [ExchangeRateDate]
    , [PriceDetnExchangeRate]
    , [StatisticalValueControl]
    , [NetAmount]
    , [TransactionCurrency]
    , [SalesOrganizationCurrency]
    , [NetPriceAmount]
    , [NetPriceQuantity]
    , [NetPriceQuantityUnit]
    , [TaxAmount]
    , [CostAmount]
    , [Subtotal1Amount]
    , [Subtotal2Amount]
    , [Subtotal3Amount]
    , [Subtotal4Amount]
    , [Subtotal5Amount]
    , [Subtotal6Amount]
    , [ShippingPoint]
    , [ShippingType]
    , [DeliveryPriority]
    , [InventorySpecialStockType]
    , [RequestedDeliveryDate]
    , [ShippingCondition]
    , [DeliveryBlockReason]
    , [Plant]
    , [StorageLocation]
    , [Route]
    , [IncotermsClassification]
    , [IncotermsVersion]
    , [IncotermsTransferLocation]
    , [IncotermsLocation1]
    , [IncotermsLocation2]
    , [MinDeliveryQtyInBaseUnit]
    , [UnlimitedOverdeliveryIsAllowed]
    , [OverdelivTolrtdLmtRatioInPct]
    , [UnderdelivTolrtdLmtRatioInPct]
    , [PartialDeliveryIsAllowed]
    , [BindingPeriodValidityStartDate]
    , [BindingPeriodValidityEndDate]
    , [OutlineAgreementTargetAmount]
    , [BillingDocumentDate]
    , [BillingCompanyCode]
    , [HeaderBillingBlockReason]
    , [ItemBillingBlockReason]
    , [FiscalYear]
    , [FiscalPeriod]
    , [CustomerAccountAssignmentGroup]
    , [ExchangeRateType]
    , [Currency]
    , [FiscalYearVariant]
    , [BusinessArea]
    , [ProfitCenter]
    , [OrderID]
    , [ProfitabilitySegment]
    , [ControllingArea]
    , [ReferenceSDDocument]
    , [ReferenceSDDocumentItem]
    , [ReferenceSDDocumentCategory]
    , [OriginSDDocument]
    , [OriginSDDocumentItem]
    , [OverallSDProcessStatus]
    , [OverallTotalDeliveryStatus]
    , [OverallOrdReltdBillgStatus]
    , [TotalCreditCheckStatus]
    , [DeliveryBlockStatus]
    , [BillingBlockStatus]
    , [TotalSDDocReferenceStatus]
    , [SDDocReferenceStatus]
    , [OverallSDDocumentRejectionSts]
    , [SDDocumentRejectionStatus]
    , [OverallTotalSDDocRefStatus]
    , [OverallSDDocReferenceStatus]
    , [ItemGeneralIncompletionStatus]
    , [ItemBillingIncompletionStatus]
    , [PricingIncompletionStatus]
    , [ItemDeliveryIncompletionStatus]
    , [SDoc_ControllingObject]
    , [SDItem_ControllingObject]
    , [CorrespncExternalReference]
    , [t_applicationId]
    , [t_jobId]
    , [t_jobDtm]
    , [t_jobBy]
    , [t_filePath]
    , [t_extractionDtm]
    , [t_lastActionBy]
    , [t_lastActionCd]
    , [t_lastActionDtm]
  )
  SELECT
    [MANDT]
  , [SalesDocument]
  , [SalesDocumentItem]
  , [SDDocumentCategory]
  , [SalesDocumentType]
  , [SalesDocumentItemCategory]
  , [IsReturnsItem]
  , [CreationDate]
  , [CreationTime]
  , [LastChangeDate]
  , [SalesOrganization]
  , [DistributionChannel]
  , [Division]
  , [SalesGroup]
  , [SalesOffice]
  , [InternationalArticleNumber]
  , [Batch]
  , [Material]
  , [OriginallyRequestedMaterial]
  , [MaterialSubstitutionReason]
  , [MaterialGroup]
  , [AdditionalMaterialGroup1]
  , [AdditionalMaterialGroup2]
  , [AdditionalMaterialGroup3]
  , [AdditionalMaterialGroup4]
  , [AdditionalMaterialGroup5]
  , [SoldToParty]
  , [AdditionalCustomerGroup1]
  , [AdditionalCustomerGroup2]
  , [AdditionalCustomerGroup3]
  , [AdditionalCustomerGroup4]
  , [AdditionalCustomerGroup5]
  , [ShipToParty]
  , [PayerParty]
  , [BillToParty]
  , [SDDocumentReason]
  , [SalesDocumentDate]
  , [OrderQuantity]
  , [OrderQuantityUnit]
  , [TargetQuantity]
  , [TargetQuantityUnit]
  , [TargetToBaseQuantityDnmntr]
  , [TargetToBaseQuantityNmrtr]
  , [OrderToBaseQuantityDnmntr]
  , [OrderToBaseQuantityNmrtr]
  , [ConfdDelivQtyInOrderQtyUnit]
  , [TargetDelivQtyInOrderQtyUnit]
  , [ConfdDeliveryQtyInBaseUnit]
  , [BaseUnit]
  , [ItemGrossWeight]
  , [ItemNetWeight]
  , [ItemWeightUnit]
  , [ItemVolume]
  , [ItemVolumeUnit]
  , [ServicesRenderedDate]
  , [SalesDistrict]
  , [CustomerGroup]
  , [HdrOrderProbabilityInPercent]
  , [ItemOrderProbabilityInPercent]
  , [SalesDocumentRjcnReason]
  , [PricingDate]
  , [ExchangeRateDate]
  , [PriceDetnExchangeRate]
  , [StatisticalValueControl]
  , [NetAmount]
  , [TransactionCurrency]
  , [SalesOrganizationCurrency]
  , [NetPriceAmount]
  , [NetPriceQuantity]
  , [NetPriceQuantityUnit]
  , [TaxAmount]
  , [CostAmount]
  , [Subtotal1Amount]
  , [Subtotal2Amount]
  , [Subtotal3Amount]
  , [Subtotal4Amount]
  , [Subtotal5Amount]
  , [Subtotal6Amount]
  , [ShippingPoint]
  , [ShippingType]
  , [DeliveryPriority]
  , [InventorySpecialStockType]
  , [RequestedDeliveryDate]
  , [ShippingCondition]
  , [DeliveryBlockReason]
  , [Plant]
  , [StorageLocation]
  , [Route]
  , [IncotermsClassification]
  , [IncotermsVersion]
  , [IncotermsTransferLocation]
  , [IncotermsLocation1]
  , [IncotermsLocation2]
  , [MinDeliveryQtyInBaseUnit]
  , [UnlimitedOverdeliveryIsAllowed]
  , [OverdelivTolrtdLmtRatioInPct]
  , [UnderdelivTolrtdLmtRatioInPct]
  , [PartialDeliveryIsAllowed]
  , [BindingPeriodValidityStartDate]
  , [BindingPeriodValidityEndDate]
  , [OutlineAgreementTargetAmount]
  , [BillingDocumentDate]
  , [BillingCompanyCode]
  , [HeaderBillingBlockReason]
  , [ItemBillingBlockReason]
  , [FiscalYear]
  , [FiscalPeriod]
  , [CustomerAccountAssignmentGroup]
  , [ExchangeRateType]
  , [Currency]
  , [FiscalYearVariant]
  , [BusinessArea]
  , [ProfitCenter]
  , [OrderID]
  , [ProfitabilitySegment]
  , [ControllingArea]
  , [ReferenceSDDocument]
  , [ReferenceSDDocumentItem]
  , [ReferenceSDDocumentCategory]
  , [OriginSDDocument]
  , [OriginSDDocumentItem]
  , [OverallSDProcessStatus]
  , [OverallTotalDeliveryStatus]
  , [OverallOrdReltdBillgStatus]
  , [TotalCreditCheckStatus]
  , [DeliveryBlockStatus]
  , [BillingBlockStatus]
  , [TotalSDDocReferenceStatus]
  , [SDDocReferenceStatus]
  , [OverallSDDocumentRejectionSts]
  , [SDDocumentRejectionStatus]
  , [OverallTotalSDDocRefStatus]
  , [OverallSDDocReferenceStatus]
  , [ItemGeneralIncompletionStatus]
  , [ItemBillingIncompletionStatus]
  , [PricingIncompletionStatus]
  , [ItemDeliveryIncompletionStatus]
  , [SDoc_ControllingObject]
  , [SDItem_ControllingObject]
  , [CorrespncExternalReference]
  , [t_applicationId]
  , [t_jobId]
  , [t_jobDtm]
  , [t_jobBy]
  , [t_filePath]
  , [t_extractionDtm]
  , SYSTEM_USER AS [t_lastActionBy]
  , ( CASE
        WHEN src.[ODQ_CHANGEMODE] = '' AND src.[ODQ_ENTITYCNTR] = 0
          THEN 'I'
        WHEN src.[ODQ_CHANGEMODE] = 'U' AND src.[ODQ_ENTITYCNTR] = 1
          THEN 'I'
        WHEN src.[ODQ_CHANGEMODE] = 'D' AND src.[ODQ_ENTITYCNTR] = -1
          THEN 'D'
        WHEN src.[ODQ_CHANGEMODE] = 'С' AND src.[ODQ_ENTITYCNTR] = 1
          THEN 'I'
      END
    ) AS [t_lastActionCd]
  , GETUTCDATE() AS [t_lastActionDtm]
  FROM
    [base_s4h_cax].[vw_C_SalesDocumentItemDEX_delta] AS src
  WHERE NOT EXISTS (
    SELECT
      MANDT
      ,SalesDocument
      ,SalesDocumentItem
    FROM
      [base_s4h_cax].[C_SalesDocumentItemDEX_active] tgt2
    WHERE
      tgt2.MANDT = src.MANDT
      AND
      tgt2.SalesDocument = src.SalesDocument
      AND
      tgt2.SalesDocumentItem = src.SalesDocumentItem
  )

END