CREATE PROC [base_s4h_cax].[sp_load_C_BillingDocumentItemBasicDEX]
AS
BEGIN

    -- Update or Delete(marks as Delete - 'D') records the base table based on the delta dataset
    UPDATE tgt
    SET 
          tgt.[SalesDocumentItemCategory] = src.[SalesDocumentItemCategory]
        , tgt.[SalesDocumentItemType] = src.[SalesDocumentItemType]
        , tgt.[ReturnItemProcessingType] = src.[ReturnItemProcessingType]
        , tgt.[BillingDocumentType] = src.[BillingDocumentType]
        , tgt.[BillingDocumentCategory] = src.[BillingDocumentCategory]
        , tgt.[SDDocumentCategory] = src.[SDDocumentCategory]
        , tgt.[CreationDate] = src.[CreationDate]
        , tgt.[CreationTime] = src.[CreationTime]
        , tgt.[LastChangeDate] = src.[LastChangeDate]
        , tgt.[BillingDocumentDate] = src.[BillingDocumentDate]
        , tgt.[BillingDocumentIsTemporary] = src.[BillingDocumentIsTemporary]
        , tgt.[OrganizationDivision] = src.[OrganizationDivision]
        , tgt.[Division] = src.[Division]
        , tgt.[SalesOffice] = src.[SalesOffice]
        , tgt.[SalesOrganization] = src.[SalesOrganization]
        , tgt.[DistributionChannel] = src.[DistributionChannel]
        , tgt.[Material] = src.[Material]
        , tgt.[OriginallyRequestedMaterial] = src.[OriginallyRequestedMaterial]
        , tgt.[InternationalArticleNumber] = src.[InternationalArticleNumber]
        , tgt.[PricingReferenceMaterial] = src.[PricingReferenceMaterial]
        , tgt.[Batch] = src.[Batch]
        , tgt.[MaterialGroup] = src.[MaterialGroup]
        , tgt.[AdditionalMaterialGroup1] = src.[AdditionalMaterialGroup1]
        , tgt.[AdditionalMaterialGroup2] = src.[AdditionalMaterialGroup2]
        , tgt.[AdditionalMaterialGroup3] = src.[AdditionalMaterialGroup3]
        , tgt.[AdditionalMaterialGroup4] = src.[AdditionalMaterialGroup4]
        , tgt.[AdditionalMaterialGroup5] = src.[AdditionalMaterialGroup5]
        , tgt.[MaterialCommissionGroup] = src.[MaterialCommissionGroup]
        , tgt.[Plant] = src.[Plant]
        , tgt.[StorageLocation] = src.[StorageLocation]
        , tgt.[BillingDocumentIsCancelled] = src.[BillingDocumentIsCancelled]
        , tgt.[CancelledBillingDocument] = src.[CancelledBillingDocument]
        , tgt.[BillingDocumentItemText] = src.[BillingDocumentItemText]
        , tgt.[ServicesRenderedDate] = src.[ServicesRenderedDate]
        , tgt.[BillingQuantity] = src.[BillingQuantity]
        , tgt.[BillingQuantityUnit] = src.[BillingQuantityUnit]
        , tgt.[BillingQuantityInBaseUnit] = src.[BillingQuantityInBaseUnit]
        , tgt.[BaseUnit] = src.[BaseUnit]
        , tgt.[MRPRequiredQuantityInBaseUnit] = src.[MRPRequiredQuantityInBaseUnit]
        , tgt.[BillingToBaseQuantityDnmntr] = src.[BillingToBaseQuantityDnmntr]
        , tgt.[BillingToBaseQuantityNmrtr] = src.[BillingToBaseQuantityNmrtr]
        , tgt.[ItemGrossWeight] = src.[ItemGrossWeight]
        , tgt.[ItemNetWeight] = src.[ItemNetWeight]
        , tgt.[ItemWeightUnit] = src.[ItemWeightUnit]
        , tgt.[ItemVolume] = src.[ItemVolume]
        , tgt.[ItemVolumeUnit] = src.[ItemVolumeUnit]
        , tgt.[BillToPartyCountry] = src.[BillToPartyCountry]
        , tgt.[BillToPartyRegion] = src.[BillToPartyRegion]
        , tgt.[BillingPlanRule] = src.[BillingPlanRule]
        , tgt.[BillingPlan] = src.[BillingPlan]
        , tgt.[BillingPlanItem] = src.[BillingPlanItem]
        , tgt.[CustomerPriceGroup] = src.[CustomerPriceGroup]
        , tgt.[PriceListType] = src.[PriceListType]
        , tgt.[TaxDepartureCountry] = src.[TaxDepartureCountry]
        , tgt.[VATRegistration] = src.[VATRegistration]
        , tgt.[VATRegistrationCountry] = src.[VATRegistrationCountry]
        , tgt.[VATRegistrationOrigin] = src.[VATRegistrationOrigin]
        , tgt.[CustomerTaxClassification1] = src.[CustomerTaxClassification1]
        , tgt.[CustomerTaxClassification2] = src.[CustomerTaxClassification2]
        , tgt.[CustomerTaxClassification3] = src.[CustomerTaxClassification3]
        , tgt.[CustomerTaxClassification4] = src.[CustomerTaxClassification4]
        , tgt.[CustomerTaxClassification5] = src.[CustomerTaxClassification5]
        , tgt.[CustomerTaxClassification6] = src.[CustomerTaxClassification6]
        , tgt.[CustomerTaxClassification7] = src.[CustomerTaxClassification7]
        , tgt.[CustomerTaxClassification8] = src.[CustomerTaxClassification8]
        , tgt.[CustomerTaxClassification9] = src.[CustomerTaxClassification9]
        , tgt.[SDPricingProcedure] = src.[SDPricingProcedure]
        , tgt.[NetAmount] = src.[NetAmount]
        , tgt.[TransactionCurrency] = src.[TransactionCurrency]
        , tgt.[GrossAmount] = src.[GrossAmount]
        , tgt.[PricingDate] = src.[PricingDate]
        , tgt.[PriceDetnExchangeRate] = src.[PriceDetnExchangeRate]
        , tgt.[PricingScaleQuantityInBaseUnit] = src.[PricingScaleQuantityInBaseUnit]
        , tgt.[TaxAmount] = src.[TaxAmount]
        , tgt.[CostAmount] = src.[CostAmount]
        , tgt.[Subtotal1Amount] = src.[Subtotal1Amount]
        , tgt.[Subtotal2Amount] = src.[Subtotal2Amount]
        , tgt.[Subtotal3Amount] = src.[Subtotal3Amount]
        , tgt.[Subtotal4Amount] = src.[Subtotal4Amount]
        , tgt.[Subtotal5Amount] = src.[Subtotal5Amount]
        , tgt.[Subtotal6Amount] = src.[Subtotal6Amount]
        , tgt.[StatisticalValueControl] = src.[StatisticalValueControl]
        , tgt.[StatisticsExchangeRate] = src.[StatisticsExchangeRate]
        , tgt.[StatisticsCurrency] = src.[StatisticsCurrency]
        , tgt.[SalesOrganizationCurrency] = src.[SalesOrganizationCurrency]
        , tgt.[EligibleAmountForCashDiscount] = src.[EligibleAmountForCashDiscount]
        , tgt.[ContractAccount] = src.[ContractAccount]
        , tgt.[CustomerPaymentTerms] = src.[CustomerPaymentTerms]
        , tgt.[PaymentMethod] = src.[PaymentMethod]
        , tgt.[PaymentReference] = src.[PaymentReference]
        , tgt.[FixedValueDate] = src.[FixedValueDate]
        , tgt.[AdditionalValueDays] = src.[AdditionalValueDays]
        , tgt.[PayerParty] = src.[PayerParty]
        , tgt.[CompanyCode] = src.[CompanyCode]
        , tgt.[FiscalYear] = src.[FiscalYear]
        , tgt.[FiscalPeriod] = src.[FiscalPeriod]
        , tgt.[CustomerAccountAssignmentGroup] = src.[CustomerAccountAssignmentGroup]
        , tgt.[BusinessArea] = src.[BusinessArea]
        , tgt.[ProfitCenter] = src.[ProfitCenter]
        , tgt.[OrderID] = src.[OrderID]
        , tgt.[ControllingArea] = src.[ControllingArea]
        , tgt.[ProfitabilitySegment] = src.[ProfitabilitySegment]
        , tgt.[CostCenter] = src.[CostCenter]
        , tgt.[OriginSDDocument] = src.[OriginSDDocument]
        , tgt.[OriginSDDocumentItem] = src.[OriginSDDocumentItem]
        , tgt.[PriceDetnExchangeRateDate] = src.[PriceDetnExchangeRateDate]
        , tgt.[ExchangeRateType] = src.[ExchangeRateType]
        , tgt.[FiscalYearVariant] = src.[FiscalYearVariant]
        , tgt.[Currency] = src.[Currency]
        , tgt.[AccountingExchangeRate] = src.[AccountingExchangeRate]
        , tgt.[AccountingExchangeRateIsSet] = src.[AccountingExchangeRateIsSet]
        , tgt.[ReferenceSDDocument] = src.[ReferenceSDDocument]
        , tgt.[ReferenceSDDocumentItem] = src.[ReferenceSDDocumentItem]
        , tgt.[ReferenceSDDocumentCategory] = src.[ReferenceSDDocumentCategory]
        , tgt.[SalesDocument] = src.[SalesDocument]
        , tgt.[SalesDocumentItem] = src.[SalesDocumentItem]
        , tgt.[SalesSDDocumentCategory] = src.[SalesSDDocumentCategory]
        , tgt.[HigherLevelItem] = src.[HigherLevelItem]
        , tgt.[BillingDocumentItemInPartSgmt] = src.[BillingDocumentItemInPartSgmt]
        , tgt.[SalesGroup] = src.[SalesGroup]
        , tgt.[AdditionalCustomerGroup1] = src.[AdditionalCustomerGroup1]
        , tgt.[AdditionalCustomerGroup2] = src.[AdditionalCustomerGroup2]
        , tgt.[AdditionalCustomerGroup3] = src.[AdditionalCustomerGroup3]
        , tgt.[AdditionalCustomerGroup4] = src.[AdditionalCustomerGroup4]
        , tgt.[AdditionalCustomerGroup5] = src.[AdditionalCustomerGroup5]
        , tgt.[SDDocumentReason] = src.[SDDocumentReason]
        , tgt.[ItemIsRelevantForCredit] = src.[ItemIsRelevantForCredit]
        , tgt.[CreditRelatedPrice] = src.[CreditRelatedPrice]
        , tgt.[SalesDistrict] = src.[SalesDistrict]
        , tgt.[CustomerGroup] = src.[CustomerGroup]
        , tgt.[SoldToParty] = src.[SoldToParty]
        , tgt.[Country] = src.[Country]
        , tgt.[ShipToParty] = src.[ShipToParty]
        , tgt.[BillToParty] = src.[BillToParty]
        , tgt.[ShippingPoint] = src.[ShippingPoint]
        , tgt.[IncotermsVersion] = src.[IncotermsVersion]
        , tgt.[IncotermsClassification] = src.[IncotermsClassification]
        , tgt.[IncotermsTransferLocation] = src.[IncotermsTransferLocation]
        , tgt.[IncotermsLocation1] = src.[IncotermsLocation1]
        , tgt.[IncotermsLocation2] = src.[IncotermsLocation2]
        , tgt.[ShippingCondition] = src.[ShippingCondition]
        , tgt.[t_applicationId] = src.[t_applicationId]
        , tgt.[t_jobId] = src.[t_jobId]
        , tgt.[t_jobDtm] = src.[t_jobDtm]
        , tgt.[t_jobBy] = src.[t_jobBy]
        , tgt.[t_filePath] = src.[t_filePath]
        , tgt.[t_extractionDtm] = src.[t_extractionDtm]
        , tgt.[t_lastActionBy] = CURRENT_USER
        , tgt.[t_lastActionCd] = (case
                                     when src.[ODQ_CHANGEMODE] = 'U' and src.[ODQ_ENTITYCNTR] = 1
                                         then 'U'
                                     when src.[ODQ_CHANGEMODE] = 'D' and src.[ODQ_ENTITYCNTR] = -1
                                         then 'D'
                                 end)
        , tgt.[t_lastActionDtm] = GETUTCDATE()
    FROM
        [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active] as tgt
    INNER JOIN
        [base_s4h_cax].[vw_C_BillingDocumentItemBasicDEX] as src
        ON
            tgt.MANDT = src.MANDT
            AND
            tgt.BillingDocument = src.BillingDocument
            AND
            tgt.BillingDocumentItem = src.BillingDocumentItem
            and 
            (
                (
                    src.[ODQ_CHANGEMODE]  = 'U'
                    AND 
                    src.[ODQ_ENTITYCNTR] = 1
                )
                OR
                (
                    src.[ODQ_CHANGEMODE] = 'D'
                    AND 
                    src.[ODQ_ENTITYCNTR] = -1
                )
            )

   


    -- Insert new records in the base table based on the delta dataset

    INSERT INTO
        [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active] (
              [MANDT]
            , [BillingDocument]
            , [BillingDocumentItem]
            , [SalesDocumentItemCategory]
            , [SalesDocumentItemType]
            , [ReturnItemProcessingType]
            , [BillingDocumentType]
            , [BillingDocumentCategory]
            , [SDDocumentCategory]
            , [CreationDate]
            , [CreationTime]
            , [LastChangeDate]
            , [BillingDocumentDate]
            , [BillingDocumentIsTemporary]
            , [OrganizationDivision]
            , [Division]
            , [SalesOffice]
            , [SalesOrganization]
            , [DistributionChannel]
            , [Material]
            , [OriginallyRequestedMaterial]
            , [InternationalArticleNumber]
            , [PricingReferenceMaterial]
            , [Batch]
            , [MaterialGroup]
            , [AdditionalMaterialGroup1]
            , [AdditionalMaterialGroup2]
            , [AdditionalMaterialGroup3]
            , [AdditionalMaterialGroup4]
            , [AdditionalMaterialGroup5]
            , [MaterialCommissionGroup]
            , [Plant]
            , [StorageLocation]
            , [BillingDocumentIsCancelled]
            , [CancelledBillingDocument]
            , [BillingDocumentItemText]
            , [ServicesRenderedDate]
            , [BillingQuantity]
            , [BillingQuantityUnit]
            , [BillingQuantityInBaseUnit]
            , [BaseUnit]
            , [MRPRequiredQuantityInBaseUnit]
            , [BillingToBaseQuantityDnmntr]
            , [BillingToBaseQuantityNmrtr]
            , [ItemGrossWeight]
            , [ItemNetWeight]
            , [ItemWeightUnit]
            , [ItemVolume]
            , [ItemVolumeUnit]
            , [BillToPartyCountry]
            , [BillToPartyRegion]
            , [BillingPlanRule]
            , [BillingPlan]
            , [BillingPlanItem]
            , [CustomerPriceGroup]
            , [PriceListType]
            , [TaxDepartureCountry]
            , [VATRegistration]
            , [VATRegistrationCountry]
            , [VATRegistrationOrigin]
            , [CustomerTaxClassification1]
            , [CustomerTaxClassification2]
            , [CustomerTaxClassification3]
            , [CustomerTaxClassification4]
            , [CustomerTaxClassification5]
            , [CustomerTaxClassification6]
            , [CustomerTaxClassification7]
            , [CustomerTaxClassification8]
            , [CustomerTaxClassification9]
            , [SDPricingProcedure]
            , [NetAmount]
            , [TransactionCurrency]
            , [GrossAmount]
            , [PricingDate]
            , [PriceDetnExchangeRate]
            , [PricingScaleQuantityInBaseUnit]
            , [TaxAmount]
            , [CostAmount]
            , [Subtotal1Amount]
            , [Subtotal2Amount]
            , [Subtotal3Amount]
            , [Subtotal4Amount]
            , [Subtotal5Amount]
            , [Subtotal6Amount]
            , [StatisticalValueControl]
            , [StatisticsExchangeRate]
            , [StatisticsCurrency]
            , [SalesOrganizationCurrency]
            , [EligibleAmountForCashDiscount]
            , [ContractAccount]
            , [CustomerPaymentTerms]
            , [PaymentMethod]
            , [PaymentReference]
            , [FixedValueDate]
            , [AdditionalValueDays]
            , [PayerParty]
            , [CompanyCode]
            , [FiscalYear]
            , [FiscalPeriod]
            , [CustomerAccountAssignmentGroup]
            , [BusinessArea]
            , [ProfitCenter]
            , [OrderID]
            , [ControllingArea]
            , [ProfitabilitySegment]
            , [CostCenter]
            , [OriginSDDocument]
            , [OriginSDDocumentItem]
            , [PriceDetnExchangeRateDate]
            , [ExchangeRateType]
            , [FiscalYearVariant]
            , [Currency]
            , [AccountingExchangeRate]
            , [AccountingExchangeRateIsSet]
            , [ReferenceSDDocument]
            , [ReferenceSDDocumentItem]
            , [ReferenceSDDocumentCategory]
            , [SalesDocument]
            , [SalesDocumentItem]
            , [SalesSDDocumentCategory]
            , [HigherLevelItem]
            , [BillingDocumentItemInPartSgmt]
            , [SalesGroup]
            , [AdditionalCustomerGroup1]
            , [AdditionalCustomerGroup2]
            , [AdditionalCustomerGroup3]
            , [AdditionalCustomerGroup4]
            , [AdditionalCustomerGroup5]
            , [SDDocumentReason]
            , [ItemIsRelevantForCredit]
            , [CreditRelatedPrice]
            , [SalesDistrict]
            , [CustomerGroup]
            , [SoldToParty]
            , [Country]
            , [ShipToParty]
            , [BillToParty]
            , [ShippingPoint]
            , [IncotermsVersion]
            , [IncotermsClassification]
            , [IncotermsTransferLocation]
            , [IncotermsLocation1]
            , [IncotermsLocation2]
            , [ShippingCondition]
            , [t_applicationId]
            , [t_jobId]
            , [t_jobDtm]
            , [t_jobBy]
            , [t_filePath]
            , [t_extractionDtm]
            , [t_lastActionBy]
            , [t_lastActionCd]
            , [t_lastActionDtm]
        )
        SELECT
              [MANDT]
            , [BillingDocument]
            , [BillingDocumentItem]
            , [SalesDocumentItemCategory]
            , [SalesDocumentItemType]
            , [ReturnItemProcessingType]
            , [BillingDocumentType]
            , [BillingDocumentCategory]
            , [SDDocumentCategory]
            , [CreationDate]
            , [CreationTime]
            , [LastChangeDate]
            , [BillingDocumentDate]
            , [BillingDocumentIsTemporary]
            , [OrganizationDivision]
            , [Division]
            , [SalesOffice]
            , [SalesOrganization]
            , [DistributionChannel]
            , [Material]
            , [OriginallyRequestedMaterial]
            , [InternationalArticleNumber]
            , [PricingReferenceMaterial]
            , [Batch]
            , [MaterialGroup]
            , [AdditionalMaterialGroup1]
            , [AdditionalMaterialGroup2]
            , [AdditionalMaterialGroup3]
            , [AdditionalMaterialGroup4]
            , [AdditionalMaterialGroup5]
            , [MaterialCommissionGroup]
            , [Plant]
            , [StorageLocation]
            , [BillingDocumentIsCancelled]
            , [CancelledBillingDocument]
            , [BillingDocumentItemText]
            , [ServicesRenderedDate]
            , [BillingQuantity]
            , [BillingQuantityUnit]
            , [BillingQuantityInBaseUnit]
            , [BaseUnit]
            , [MRPRequiredQuantityInBaseUnit]
            , [BillingToBaseQuantityDnmntr]
            , [BillingToBaseQuantityNmrtr]
            , [ItemGrossWeight]
            , [ItemNetWeight]
            , [ItemWeightUnit]
            , [ItemVolume]
            , [ItemVolumeUnit]
            , [BillToPartyCountry]
            , [BillToPartyRegion]
            , [BillingPlanRule]
            , [BillingPlan]
            , [BillingPlanItem]
            , [CustomerPriceGroup]
            , [PriceListType]
            , [TaxDepartureCountry]
            , [VATRegistration]
            , [VATRegistrationCountry]
            , [VATRegistrationOrigin]
            , [CustomerTaxClassification1]
            , [CustomerTaxClassification2]
            , [CustomerTaxClassification3]
            , [CustomerTaxClassification4]
            , [CustomerTaxClassification5]
            , [CustomerTaxClassification6]
            , [CustomerTaxClassification7]
            , [CustomerTaxClassification8]
            , [CustomerTaxClassification9]
            , [SDPricingProcedure]
            , [NetAmount]
            , [TransactionCurrency]
            , [GrossAmount]
            , [PricingDate]
            , [PriceDetnExchangeRate]
            , [PricingScaleQuantityInBaseUnit]
            , [TaxAmount]
            , [CostAmount]
            , [Subtotal1Amount]
            , [Subtotal2Amount]
            , [Subtotal3Amount]
            , [Subtotal4Amount]
            , [Subtotal5Amount]
            , [Subtotal6Amount]
            , [StatisticalValueControl]
            , [StatisticsExchangeRate]
            , [StatisticsCurrency]
            , [SalesOrganizationCurrency]
            , [EligibleAmountForCashDiscount]
            , [ContractAccount]
            , [CustomerPaymentTerms]
            , [PaymentMethod]
            , [PaymentReference]
            , [FixedValueDate]
            , [AdditionalValueDays]
            , [PayerParty]
            , [CompanyCode]
            , [FiscalYear]
            , [FiscalPeriod]
            , [CustomerAccountAssignmentGroup]
            , [BusinessArea]
            , [ProfitCenter]
            , [OrderID]
            , [ControllingArea]
            , [ProfitabilitySegment]
            , [CostCenter]
            , [OriginSDDocument]
            , [OriginSDDocumentItem]
            , [PriceDetnExchangeRateDate]
            , [ExchangeRateType]
            , [FiscalYearVariant]
            , [Currency]
            , [AccountingExchangeRate]
            , [AccountingExchangeRateIsSet]
            , [ReferenceSDDocument]
            , [ReferenceSDDocumentItem]
            , [ReferenceSDDocumentCategory]
            , [SalesDocument]
            , [SalesDocumentItem]
            , [SalesSDDocumentCategory]
            , [HigherLevelItem]
            , [BillingDocumentItemInPartSgmt]
            , [SalesGroup]
            , [AdditionalCustomerGroup1]
            , [AdditionalCustomerGroup2]
            , [AdditionalCustomerGroup3]
            , [AdditionalCustomerGroup4]
            , [AdditionalCustomerGroup5]
            , [SDDocumentReason]
            , [ItemIsRelevantForCredit]
            , [CreditRelatedPrice]
            , [SalesDistrict]
            , [CustomerGroup]
            , [SoldToParty]
            , [Country]
            , [ShipToParty]
            , [BillToParty]
            , [ShippingPoint]
            , [IncotermsVersion]
            , [IncotermsClassification]
            , [IncotermsTransferLocation]
            , [IncotermsLocation1]
            , [IncotermsLocation2]
            , [ShippingCondition]
            , [t_applicationId]
            , [t_jobId]
            , [t_jobDtm]
            , [t_jobBy]
            , [t_filePath]
            , [t_extractionDtm]
            , CURRENT_USER as [t_lastActionBy]
            , (case
                    when src.[ODQ_CHANGEMODE] = '' and src.[ODQ_ENTITYCNTR] = 0
                        then 'I'
                    when src.[ODQ_CHANGEMODE] = 'U' and src.[ODQ_ENTITYCNTR] = 1
                        then 'I'
                    when src.[ODQ_CHANGEMODE] = 'D' and src.[ODQ_ENTITYCNTR] = -1
                        then 'D'
                    when src.[ODQ_CHANGEMODE] = 'С' and src.[ODQ_ENTITYCNTR] = 1
                        then 'I'
                end) as [t_lastActionCd]
            , GETUTCDATE() as [t_lastActionDtm]
        FROM [base_s4h_cax].[vw_C_BillingDocumentItemBasicDEX] as src
        WHERE NOT EXISTS (
            SELECT 
                MANDT
                ,BillingDocument
                ,BillingDocumentItem
            FROM 
                [base_s4h_cax].[C_BillingDocumentItemBasicDEX_active] tgt2
            WHERE 
                tgt2.MANDT = src.MANDT
                AND
                tgt2.BillingDocument = src.BillingDocument
                AND
                tgt2.BillingDocumentItem = src.BillingDocumentItem
        )

END
