CREATE PROC [base_s4h_cax].[sp_load_I_GLAccountLineItemRawData]
AS
BEGIN

  -- Update or Delete(marks as Delete - 'D') records the base table based on the delta dataset
  UPDATE
    [base_s4h_cax].[I_GLAccountLineItemRawData_active]
  SET 
    [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SourceLedger] = src.[SourceLedger]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CompanyCode] = src.[CompanyCode]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FiscalYear] = src.[FiscalYear]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AccountingDocument] = src.[AccountingDocument]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[LedgerGLLineItem] = src.[LedgerGLLineItem]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[LedgerFiscalYear] = src.[LedgerFiscalYear]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[GLRecordType] = src.[GLRecordType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ChartOfAccounts] = src.[ChartOfAccounts]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ControllingArea] = src.[ControllingArea]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FinancialTransactionType] = src.[FinancialTransactionType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[BusinessTransactionType] = src.[BusinessTransactionType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ControllingBusTransacType] = src.[ControllingBusTransacType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ReferenceDocumentType] = src.[ReferenceDocumentType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[LogicalSystem] = src.[LogicalSystem]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ReferenceDocumentContext] = src.[ReferenceDocumentContext]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ReferenceDocument] = src.[ReferenceDocument]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ReferenceDocumentItem] = src.[ReferenceDocumentItem]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ReferenceDocumentItemGroup] = src.[ReferenceDocumentItemGroup]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[IsReversal] = src.[IsReversal]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[IsReversed] = src.[IsReversed]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ReversalReferenceDocumentCntxt] = src.[ReversalReferenceDocumentCntxt]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ReversalReferenceDocument] = src.[ReversalReferenceDocument]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[IsSettlement] = src.[IsSettlement]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[IsSettled] = src.[IsSettled]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PredecessorReferenceDocType] = src.[PredecessorReferenceDocType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PredecessorReferenceDocCntxt] = src.[PredecessorReferenceDocCntxt]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PredecessorReferenceDocument] = src.[PredecessorReferenceDocument]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PredecessorReferenceDocItem] = src.[PredecessorReferenceDocItem]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SourceReferenceDocumentType] = src.[SourceReferenceDocumentType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SourceLogicalSystem] = src.[SourceLogicalSystem]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SourceReferenceDocumentCntxt] = src.[SourceReferenceDocumentCntxt]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SourceReferenceDocument] = src.[SourceReferenceDocument]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SourceReferenceDocumentItem] = src.[SourceReferenceDocumentItem]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SourceReferenceDocSubitem] = src.[SourceReferenceDocSubitem]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[IsCommitment] = src.[IsCommitment]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[JrnlEntryItemObsoleteReason] = src.[JrnlEntryItemObsoleteReason]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[GLAccount] = src.[GLAccount]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CostCenter] = src.[CostCenter]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ProfitCenter] = src.[ProfitCenter]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FunctionalArea] = src.[FunctionalArea]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[BusinessArea] = src.[BusinessArea]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[Segment] = src.[Segment]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerCostCenter] = src.[PartnerCostCenter]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerProfitCenter] = src.[PartnerProfitCenter]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerFunctionalArea] = src.[PartnerFunctionalArea]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerBusinessArea] = src.[PartnerBusinessArea]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerCompany] = src.[PartnerCompany]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerSegment] = src.[PartnerSegment]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[BalanceTransactionCurrency] = src.[BalanceTransactionCurrency]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AmountInBalanceTransacCrcy] = src.[AmountInBalanceTransacCrcy]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[TransactionCurrency] = src.[TransactionCurrency]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AmountInTransactionCurrency] = src.[AmountInTransactionCurrency]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CompanyCodeCurrency] = src.[CompanyCodeCurrency]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AmountInCompanyCodeCurrency] = src.[AmountInCompanyCodeCurrency]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[GlobalCurrency] = src.[GlobalCurrency]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AmountInGlobalCurrency] = src.[AmountInGlobalCurrency]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FreeDefinedCurrency1] = src.[FreeDefinedCurrency1]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AmountInFreeDefinedCurrency1] = src.[AmountInFreeDefinedCurrency1]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FreeDefinedCurrency2] = src.[FreeDefinedCurrency2]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AmountInFreeDefinedCurrency2] = src.[AmountInFreeDefinedCurrency2]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FreeDefinedCurrency3] = src.[FreeDefinedCurrency3]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AmountInFreeDefinedCurrency3] = src.[AmountInFreeDefinedCurrency3]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FreeDefinedCurrency4] = src.[FreeDefinedCurrency4]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AmountInFreeDefinedCurrency4] = src.[AmountInFreeDefinedCurrency4]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FreeDefinedCurrency5] = src.[FreeDefinedCurrency5]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AmountInFreeDefinedCurrency5] = src.[AmountInFreeDefinedCurrency5]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FreeDefinedCurrency6] = src.[FreeDefinedCurrency6]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AmountInFreeDefinedCurrency6] = src.[AmountInFreeDefinedCurrency6]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FreeDefinedCurrency7] = src.[FreeDefinedCurrency7]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AmountInFreeDefinedCurrency7] = src.[AmountInFreeDefinedCurrency7]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FreeDefinedCurrency8] = src.[FreeDefinedCurrency8]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AmountInFreeDefinedCurrency8] = src.[AmountInFreeDefinedCurrency8]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FixedAmountInGlobalCrcy] = src.[FixedAmountInGlobalCrcy]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[GrpValnFixedAmtInGlobCrcy] = src.[GrpValnFixedAmtInGlobCrcy]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PrftCtrValnFxdAmtInGlobCrcy] = src.[PrftCtrValnFxdAmtInGlobCrcy]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FixedAmountInCoCoDeCrcy] = src.[FixedAmountInCoCoDeCrcy]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[TotalPriceVarcInGlobalCrcy] = src.[TotalPriceVarcInGlobalCrcy]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[GrpValnTotPrcVarcInGlobCrcy] = src.[GrpValnTotPrcVarcInGlobCrcy]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PrftCtrValnTotPrcVarcInGlbCrcy] = src.[PrftCtrValnTotPrcVarcInGlbCrcy]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FixedPriceVarcInGlobalCrcy] = src.[FixedPriceVarcInGlobalCrcy]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[GrpValnFixedPrcVarcInGlobCrcy] = src.[GrpValnFixedPrcVarcInGlobCrcy]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PrftCtrValnFxdPrcVarcInGlbCrcy] = src.[PrftCtrValnFxdPrcVarcInGlbCrcy]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ControllingObjectCurrency] = src.[ControllingObjectCurrency]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AmountInObjectCurrency] = src.[AmountInObjectCurrency]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[BaseUnit] = src.[BaseUnit]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[Quantity] = src.[Quantity]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FixedQuantity] = src.[FixedQuantity]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CostSourceUnit] = src.[CostSourceUnit]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ValuationQuantity] = src.[ValuationQuantity]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ValuationFixedQuantity] = src.[ValuationFixedQuantity]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AdditionalQuantity1Unit] = src.[AdditionalQuantity1Unit]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AdditionalQuantity1] = src.[AdditionalQuantity1]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AdditionalQuantity2Unit] = src.[AdditionalQuantity2Unit]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AdditionalQuantity2] = src.[AdditionalQuantity2]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AdditionalQuantity3Unit] = src.[AdditionalQuantity3Unit]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AdditionalQuantity3] = src.[AdditionalQuantity3]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[DebitCreditCode] = src.[DebitCreditCode]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FiscalPeriod] = src.[FiscalPeriod]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FiscalYearVariant] = src.[FiscalYearVariant]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FiscalYearPeriod] = src.[FiscalYearPeriod]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PostingDate] = src.[PostingDate]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[DocumentDate] = src.[DocumentDate]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AccountingDocumentType] = src.[AccountingDocumentType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AccountingDocumentItem] = src.[AccountingDocumentItem]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AssignmentReference] = src.[AssignmentReference]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AccountingDocumentCategory] = src.[AccountingDocumentCategory]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PostingKey] = src.[PostingKey]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[TransactionTypeDetermination] = src.[TransactionTypeDetermination]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SubLedgerAcctLineItemType] = src.[SubLedgerAcctLineItemType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AccountingDocCreatedByUser] = src.[AccountingDocCreatedByUser]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[LastChangeDateTime] = src.[LastChangeDateTime]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CreationDateTime] = src.[CreationDateTime]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CreationDate] = src.[CreationDate]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[EliminationProfitCenter] = src.[EliminationProfitCenter]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[OriginObjectType] = src.[OriginObjectType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[GLAccountType] = src.[GLAccountType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AlternativeGLAccount] = src.[AlternativeGLAccount]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CountryChartOfAccounts] = src.[CountryChartOfAccounts]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[InvoiceReference] = src.[InvoiceReference]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[InvoiceReferenceFiscalYear] = src.[InvoiceReferenceFiscalYear]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FollowOnDocumentType] = src.[FollowOnDocumentType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[InvoiceItemReference] = src.[InvoiceItemReference]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ReferencePurchaseOrderCategory] = src.[ReferencePurchaseOrderCategory]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PurchasingDocument] = src.[PurchasingDocument]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PurchasingDocumentItem] = src.[PurchasingDocumentItem]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AccountAssignmentNumber] = src.[AccountAssignmentNumber]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[DocumentItemText] = src.[DocumentItemText]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SalesDocument] = src.[SalesDocument]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SalesDocumentItem] = src.[SalesDocumentItem]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[Product] = src.[Product]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[Plant] = src.[Plant]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[Supplier] = src.[Supplier]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[Customer] = src.[Customer]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ServicesRenderedDate] = src.[ServicesRenderedDate]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ConditionContract] = src.[ConditionContract]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ExchangeRateDate] = src.[ExchangeRateDate]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FinancialAccountType] = src.[FinancialAccountType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SpecialGLCode] = src.[SpecialGLCode]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[TaxCode] = src.[TaxCode]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[HouseBank] = src.[HouseBank]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[HouseBankAccount] = src.[HouseBankAccount]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[IsOpenItemManaged] = src.[IsOpenItemManaged]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ClearingDate] = src.[ClearingDate]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ClearingAccountingDocument] = src.[ClearingAccountingDocument]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ClearingDocFiscalYear] = src.[ClearingDocFiscalYear]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AssetDepreciationArea] = src.[AssetDepreciationArea]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[MasterFixedAsset] = src.[MasterFixedAsset]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FixedAsset] = src.[FixedAsset]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AssetValueDate] = src.[AssetValueDate]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AssetTransactionType] = src.[AssetTransactionType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AssetAcctTransClassfctn] = src.[AssetAcctTransClassfctn]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[DepreciationFiscalPeriod] = src.[DepreciationFiscalPeriod]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[GroupMasterFixedAsset] = src.[GroupMasterFixedAsset]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[GroupFixedAsset] = src.[GroupFixedAsset]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AssetClass] = src.[AssetClass]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CostEstimate] = src.[CostEstimate]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[InventorySpecialStockValnType] = src.[InventorySpecialStockValnType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[InventorySpecialStockType] = src.[InventorySpecialStockType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[InventorySpclStkSalesDocument] = src.[InventorySpclStkSalesDocument]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[InventorySpclStkSalesDocItm] = src.[InventorySpclStkSalesDocItm]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[InvtrySpclStockWBSElmntIntID] = src.[InvtrySpclStockWBSElmntIntID]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[InventorySpclStockWBSElement] = src.[InventorySpclStockWBSElement]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[InventorySpecialStockSupplier] = src.[InventorySpecialStockSupplier]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[InventoryValuationType] = src.[InventoryValuationType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ValuationArea] = src.[ValuationArea]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SenderCompanyCode] = src.[SenderCompanyCode]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SenderGLAccount] = src.[SenderGLAccount]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SenderAccountAssignment] = src.[SenderAccountAssignment]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SenderAccountAssignmentType] = src.[SenderAccountAssignmentType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ControllingObject] = src.[ControllingObject]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CostOriginGroup] = src.[CostOriginGroup]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[OriginSenderObject] = src.[OriginSenderObject]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ControllingDebitCreditCode] = src.[ControllingDebitCreditCode]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ControllingObjectDebitType] = src.[ControllingObjectDebitType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[QuantityIsIncomplete] = src.[QuantityIsIncomplete]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[OffsettingAccount] = src.[OffsettingAccount]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[OffsettingAccountType] = src.[OffsettingAccountType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[OffsettingChartOfAccounts] = src.[OffsettingChartOfAccounts]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[LineItemIsCompleted] = src.[LineItemIsCompleted]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PersonnelNumber] = src.[PersonnelNumber]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ControllingObjectClass] = src.[ControllingObjectClass]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerCompanyCode] = src.[PartnerCompanyCode]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerControllingObjectClass] = src.[PartnerControllingObjectClass]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[OriginCostCenter] = src.[OriginCostCenter]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[OriginProfitCenter] = src.[OriginProfitCenter]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[OriginCostCtrActivityType] = src.[OriginCostCtrActivityType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AccountAssignment] = src.[AccountAssignment]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AccountAssignmentType] = src.[AccountAssignmentType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CostCtrActivityType] = src.[CostCtrActivityType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[OrderID] = src.[OrderID]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[OrderCategory] = src.[OrderCategory]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[WBSElementInternalID] = src.[WBSElementInternalID]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[WBSElement] = src.[WBSElement]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerWBSElementInternalID] = src.[PartnerWBSElementInternalID]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerWBSElement] = src.[PartnerWBSElement]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ProjectInternalID] = src.[ProjectInternalID]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[Project] = src.[Project]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerProjectInternalID] = src.[PartnerProjectInternalID]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerProject] = src.[PartnerProject]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[OperatingConcern] = src.[OperatingConcern]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ProjectNetwork] = src.[ProjectNetwork]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[RelatedNetworkActivity] = src.[RelatedNetworkActivity]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[BusinessProcess] = src.[BusinessProcess]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CostObject] = src.[CostObject]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[BillableControl] = src.[BillableControl]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CostAnalysisResource] = src.[CostAnalysisResource]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CustomerServiceNotification] = src.[CustomerServiceNotification]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ServiceDocumentType] = src.[ServiceDocumentType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ServiceDocument] = src.[ServiceDocument]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ServiceDocumentItem] = src.[ServiceDocumentItem]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerServiceDocumentType] = src.[PartnerServiceDocumentType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerServiceDocument] = src.[PartnerServiceDocument]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerServiceDocumentItem] = src.[PartnerServiceDocumentItem]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ServiceContractType] = src.[ServiceContractType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ServiceContract] = src.[ServiceContract]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ServiceContractItem] = src.[ServiceContractItem]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[TimeSheetOvertimeCategory] = src.[TimeSheetOvertimeCategory]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerAccountAssignment] = src.[PartnerAccountAssignment]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerAccountAssignmentType] = src.[PartnerAccountAssignmentType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[WorkPackage] = src.[WorkPackage]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[WorkItem] = src.[WorkItem]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerCostCtrActivityType] = src.[PartnerCostCtrActivityType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerOrder] = src.[PartnerOrder]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerOrderCategory] = src.[PartnerOrderCategory]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerSalesDocument] = src.[PartnerSalesDocument]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerSalesDocumentItem] = src.[PartnerSalesDocumentItem]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerProjectNetwork] = src.[PartnerProjectNetwork]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerProjectNetworkActivity] = src.[PartnerProjectNetworkActivity]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerBusinessProcess] = src.[PartnerBusinessProcess]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerCostObject] = src.[PartnerCostObject]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[BillingDocumentType] = src.[BillingDocumentType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SalesOrganization] = src.[SalesOrganization]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[DistributionChannel] = src.[DistributionChannel]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[OrganizationDivision] = src.[OrganizationDivision]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SoldProduct] = src.[SoldProduct]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SoldProductGroup] = src.[SoldProductGroup]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CustomerGroup] = src.[CustomerGroup]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CustomerSupplierCountry] = src.[CustomerSupplierCountry]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CustomerSupplierIndustry] = src.[CustomerSupplierIndustry]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SalesDistrict] = src.[SalesDistrict]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[BillToParty] = src.[BillToParty]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ShipToParty] = src.[ShipToParty]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CustomerSupplierCorporateGroup] = src.[CustomerSupplierCorporateGroup]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CashLedgerCompanyCode] = src.[CashLedgerCompanyCode]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CashLedgerAccount] = src.[CashLedgerAccount]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FinancialManagementArea] = src.[FinancialManagementArea]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FundsCenter] = src.[FundsCenter]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FundedProgram] = src.[FundedProgram]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[Fund] = src.[Fund]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[GrantID] = src.[GrantID]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[BudgetPeriod] = src.[BudgetPeriod]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerFund] = src.[PartnerFund]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerGrant] = src.[PartnerGrant]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerBudgetPeriod] = src.[PartnerBudgetPeriod]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PubSecBudgetAccount] = src.[PubSecBudgetAccount]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PubSecBudgetAccountCoCode] = src.[PubSecBudgetAccountCoCode]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PubSecBudgetCnsmpnDate] = src.[PubSecBudgetCnsmpnDate]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PubSecBudgetCnsmpnFsclPeriod] = src.[PubSecBudgetCnsmpnFsclPeriod]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PubSecBudgetCnsmpnFsclYear] = src.[PubSecBudgetCnsmpnFsclYear]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PubSecBudgetIsRelevant] = src.[PubSecBudgetIsRelevant]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PubSecBudgetCnsmpnType] = src.[PubSecBudgetCnsmpnType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PubSecBudgetCnsmpnAmtType] = src.[PubSecBudgetCnsmpnAmtType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[JointVenture] = src.[JointVenture]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[JointVentureEquityGroup] = src.[JointVentureEquityGroup]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[JointVentureCostRecoveryCode] = src.[JointVentureCostRecoveryCode]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[JointVenturePartner] = src.[JointVenturePartner]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[JointVentureBillingType] = src.[JointVentureBillingType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[JointVentureEquityType] = src.[JointVentureEquityType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[JointVentureProductionDate] = src.[JointVentureProductionDate]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[JointVentureBillingDate] = src.[JointVentureBillingDate]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[JointVentureOperationalDate] = src.[JointVentureOperationalDate]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CutbackRun] = src.[CutbackRun]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[JointVentureAccountingActivity] = src.[JointVentureAccountingActivity]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerVenture] = src.[PartnerVenture]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[PartnerEquityGroup] = src.[PartnerEquityGroup]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SenderCostRecoveryCode] = src.[SenderCostRecoveryCode]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CutbackAccount] = src.[CutbackAccount]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CutbackCostObject] = src.[CutbackCostObject]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SettlementReferenceDate] = src.[SettlementReferenceDate]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AccrualObjectType] = src.[AccrualObjectType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AccrualObject] = src.[AccrualObject]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AccrualSubobject] = src.[AccrualSubobject]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AccrualItemType] = src.[AccrualItemType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AccrualValueDate] = src.[AccrualValueDate]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FinancialValuationObjectType] = src.[FinancialValuationObjectType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FinancialValuationObject] = src.[FinancialValuationObject]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FinancialValuationSubobject] = src.[FinancialValuationSubobject]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[NetDueDate] = src.[NetDueDate]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CreditRiskClass] = src.[CreditRiskClass]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[WorkCenterInternalID] = src.[WorkCenterInternalID]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[OrderOperation] = src.[OrderOperation]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[OrderItem] = src.[OrderItem]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[OrderSuboperation] = src.[OrderSuboperation]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[Equipment] = src.[Equipment]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FunctionalLocation] = src.[FunctionalLocation]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[Assembly] = src.[Assembly]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[MaintenanceActivityType] = src.[MaintenanceActivityType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[MaintenanceOrderPlanningCode] = src.[MaintenanceOrderPlanningCode]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[MaintPriorityType] = src.[MaintPriorityType]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[MaintPriority] = src.[MaintPriority]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SuperiorOrder] = src.[SuperiorOrder]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[ProductGroup] = src.[ProductGroup]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[MaintenanceOrderIsPlanned] = src.[MaintenanceOrderIsPlanned]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[t_applicationId] = src.[t_applicationId]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[t_jobId] = src.[t_jobId]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[t_jobDtm] = src.[t_jobDtm]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[t_jobBy] = src.[t_jobBy]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[t_filePath] = src.[t_filePath]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[t_extractionDtm] = src.[t_extractionDtm]
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[t_lastActionBy] = SYSTEM_USER
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[t_lastActionCd] = (
      CASE
        WHEN src.[ODQ_CHANGEMODE] = 'U' AND src.[ODQ_ENTITYCNTR] =  1 THEN 'U'
        WHEN src.[ODQ_CHANGEMODE] = 'D' AND src.[ODQ_ENTITYCNTR] = -1 THEN 'D'
      END
    )
  , [base_s4h_cax].[I_GLAccountLineItemRawData_active].[t_lastActionDtm] = GETUTCDATE()
  FROM
    [base_s4h_cax].[vw_I_GLAccountLineItemRawData_delta] as src
  WHERE
    [base_s4h_cax].[I_GLAccountLineItemRawData_active].[MANDT]                 = src.MANDT
    AND
    [base_s4h_cax].[I_GLAccountLineItemRawData_active].[SourceLedger]       = src.[SourceLedger]
    AND
    [base_s4h_cax].[I_GLAccountLineItemRawData_active].[CompanyCode]        = src.[CompanyCode]
    AND
    [base_s4h_cax].[I_GLAccountLineItemRawData_active].[FiscalYear]         = src.[FiscalYear]
    AND
    [base_s4h_cax].[I_GLAccountLineItemRawData_active].[AccountingDocument] = src.[AccountingDocument]
    AND
    [base_s4h_cax].[I_GLAccountLineItemRawData_active].[LedgerGLLineItem]   = src.[LedgerGLLineItem]

    -- Insert new records in the base table based on the delta dataset

  INSERT INTO
    [base_s4h_cax].[I_GLAccountLineItemRawData_active] (
      [MANDT]
    , [SourceLedger]
    , [CompanyCode]
    , [FiscalYear]
    , [AccountingDocument]
    , [LedgerGLLineItem]
    , [LedgerFiscalYear]
    , [GLRecordType]
    , [ChartOfAccounts]
    , [ControllingArea]
    , [FinancialTransactionType]
    , [BusinessTransactionType]
    , [ControllingBusTransacType]
    , [ReferenceDocumentType]
    , [LogicalSystem]
    , [ReferenceDocumentContext]
    , [ReferenceDocument]
    , [ReferenceDocumentItem]
    , [ReferenceDocumentItemGroup]
    , [IsReversal]
    , [IsReversed]
    , [ReversalReferenceDocumentCntxt]
    , [ReversalReferenceDocument]
    , [IsSettlement]
    , [IsSettled]
    , [PredecessorReferenceDocType]
    , [PredecessorReferenceDocCntxt]
    , [PredecessorReferenceDocument]
    , [PredecessorReferenceDocItem]
    , [SourceReferenceDocumentType]
    , [SourceLogicalSystem]
    , [SourceReferenceDocumentCntxt]
    , [SourceReferenceDocument]
    , [SourceReferenceDocumentItem]
    , [SourceReferenceDocSubitem]
    , [IsCommitment]
    , [JrnlEntryItemObsoleteReason]
    , [GLAccount]
    , [CostCenter]
    , [ProfitCenter]
    , [FunctionalArea]
    , [BusinessArea]
    , [Segment]
    , [PartnerCostCenter]
    , [PartnerProfitCenter]
    , [PartnerFunctionalArea]
    , [PartnerBusinessArea]
    , [PartnerCompany]
    , [PartnerSegment]
    , [BalanceTransactionCurrency]
    , [AmountInBalanceTransacCrcy]
    , [TransactionCurrency]
    , [AmountInTransactionCurrency]
    , [CompanyCodeCurrency]
    , [AmountInCompanyCodeCurrency]
    , [GlobalCurrency]
    , [AmountInGlobalCurrency]
    , [FreeDefinedCurrency1]
    , [AmountInFreeDefinedCurrency1]
    , [FreeDefinedCurrency2]
    , [AmountInFreeDefinedCurrency2]
    , [FreeDefinedCurrency3]
    , [AmountInFreeDefinedCurrency3]
    , [FreeDefinedCurrency4]
    , [AmountInFreeDefinedCurrency4]
    , [FreeDefinedCurrency5]
    , [AmountInFreeDefinedCurrency5]
    , [FreeDefinedCurrency6]
    , [AmountInFreeDefinedCurrency6]
    , [FreeDefinedCurrency7]
    , [AmountInFreeDefinedCurrency7]
    , [FreeDefinedCurrency8]
    , [AmountInFreeDefinedCurrency8]
    , [FixedAmountInGlobalCrcy]
    , [GrpValnFixedAmtInGlobCrcy]
    , [PrftCtrValnFxdAmtInGlobCrcy]
    , [FixedAmountInCoCoDeCrcy]
    , [TotalPriceVarcInGlobalCrcy]
    , [GrpValnTotPrcVarcInGlobCrcy]
    , [PrftCtrValnTotPrcVarcInGlbCrcy]
    , [FixedPriceVarcInGlobalCrcy]
    , [GrpValnFixedPrcVarcInGlobCrcy]
    , [PrftCtrValnFxdPrcVarcInGlbCrcy]
    , [ControllingObjectCurrency]
    , [AmountInObjectCurrency]
    , [BaseUnit]
    , [Quantity]
    , [FixedQuantity]
    , [CostSourceUnit]
    , [ValuationQuantity]
    , [ValuationFixedQuantity]
    , [AdditionalQuantity1Unit]
    , [AdditionalQuantity1]
    , [AdditionalQuantity2Unit]
    , [AdditionalQuantity2]
    , [AdditionalQuantity3Unit]
    , [AdditionalQuantity3]
    , [DebitCreditCode]
    , [FiscalPeriod]
    , [FiscalYearVariant]
    , [FiscalYearPeriod]
    , [PostingDate]
    , [DocumentDate]
    , [AccountingDocumentType]
    , [AccountingDocumentItem]
    , [AssignmentReference]
    , [AccountingDocumentCategory]
    , [PostingKey]
    , [TransactionTypeDetermination]
    , [SubLedgerAcctLineItemType]
    , [AccountingDocCreatedByUser]
    , [LastChangeDateTime]
    , [CreationDateTime]
    , [CreationDate]
    , [EliminationProfitCenter]
    , [OriginObjectType]
    , [GLAccountType]
    , [AlternativeGLAccount]
    , [CountryChartOfAccounts]
    , [InvoiceReference]
    , [InvoiceReferenceFiscalYear]
    , [FollowOnDocumentType]
    , [InvoiceItemReference]
    , [ReferencePurchaseOrderCategory]
    , [PurchasingDocument]
    , [PurchasingDocumentItem]
    , [AccountAssignmentNumber]
    , [DocumentItemText]
    , [SalesDocument]
    , [SalesDocumentItem]
    , [Product]
    , [Plant]
    , [Supplier]
    , [Customer]
    , [ServicesRenderedDate]
    , [ConditionContract]
    , [ExchangeRateDate]
    , [FinancialAccountType]
    , [SpecialGLCode]
    , [TaxCode]
    , [HouseBank]
    , [HouseBankAccount]
    , [IsOpenItemManaged]
    , [ClearingDate]
    , [ClearingAccountingDocument]
    , [ClearingDocFiscalYear]
    , [AssetDepreciationArea]
    , [MasterFixedAsset]
    , [FixedAsset]
    , [AssetValueDate]
    , [AssetTransactionType]
    , [AssetAcctTransClassfctn]
    , [DepreciationFiscalPeriod]
    , [GroupMasterFixedAsset]
    , [GroupFixedAsset]
    , [AssetClass]
    , [CostEstimate]
    , [InventorySpecialStockValnType]
    , [InventorySpecialStockType]
    , [InventorySpclStkSalesDocument]
    , [InventorySpclStkSalesDocItm]
    , [InvtrySpclStockWBSElmntIntID]
    , [InventorySpclStockWBSElement]
    , [InventorySpecialStockSupplier]
    , [InventoryValuationType]
    , [ValuationArea]
    , [SenderCompanyCode]
    , [SenderGLAccount]
    , [SenderAccountAssignment]
    , [SenderAccountAssignmentType]
    , [ControllingObject]
    , [CostOriginGroup]
    , [OriginSenderObject]
    , [ControllingDebitCreditCode]
    , [ControllingObjectDebitType]
    , [QuantityIsIncomplete]
    , [OffsettingAccount]
    , [OffsettingAccountType]
    , [OffsettingChartOfAccounts]
    , [LineItemIsCompleted]
    , [PersonnelNumber]
    , [ControllingObjectClass]
    , [PartnerCompanyCode]
    , [PartnerControllingObjectClass]
    , [OriginCostCenter]
    , [OriginProfitCenter]
    , [OriginCostCtrActivityType]
    , [AccountAssignment]
    , [AccountAssignmentType]
    , [CostCtrActivityType]
    , [OrderID]
    , [OrderCategory]
    , [WBSElementInternalID]
    , [WBSElement]
    , [PartnerWBSElementInternalID]
    , [PartnerWBSElement]
    , [ProjectInternalID]
    , [Project]
    , [PartnerProjectInternalID]
    , [PartnerProject]
    , [OperatingConcern]
    , [ProjectNetwork]
    , [RelatedNetworkActivity]
    , [BusinessProcess]
    , [CostObject]
    , [BillableControl]
    , [CostAnalysisResource]
    , [CustomerServiceNotification]
    , [ServiceDocumentType]
    , [ServiceDocument]
    , [ServiceDocumentItem]
    , [PartnerServiceDocumentType]
    , [PartnerServiceDocument]
    , [PartnerServiceDocumentItem]
    , [ServiceContractType]
    , [ServiceContract]
    , [ServiceContractItem]
    , [TimeSheetOvertimeCategory]
    , [PartnerAccountAssignment]
    , [PartnerAccountAssignmentType]
    , [WorkPackage]
    , [WorkItem]
    , [PartnerCostCtrActivityType]
    , [PartnerOrder]
    , [PartnerOrderCategory]
    , [PartnerSalesDocument]
    , [PartnerSalesDocumentItem]
    , [PartnerProjectNetwork]
    , [PartnerProjectNetworkActivity]
    , [PartnerBusinessProcess]
    , [PartnerCostObject]
    , [BillingDocumentType]
    , [SalesOrganization]
    , [DistributionChannel]
    , [OrganizationDivision]
    , [SoldProduct]
    , [SoldProductGroup]
    , [CustomerGroup]
    , [CustomerSupplierCountry]
    , [CustomerSupplierIndustry]
    , [SalesDistrict]
    , [BillToParty]
    , [ShipToParty]
    , [CustomerSupplierCorporateGroup]
    , [CashLedgerCompanyCode]
    , [CashLedgerAccount]
    , [FinancialManagementArea]
    , [FundsCenter]
    , [FundedProgram]
    , [Fund]
    , [GrantID]
    , [BudgetPeriod]
    , [PartnerFund]
    , [PartnerGrant]
    , [PartnerBudgetPeriod]
    , [PubSecBudgetAccount]
    , [PubSecBudgetAccountCoCode]
    , [PubSecBudgetCnsmpnDate]
    , [PubSecBudgetCnsmpnFsclPeriod]
    , [PubSecBudgetCnsmpnFsclYear]
    , [PubSecBudgetIsRelevant]
    , [PubSecBudgetCnsmpnType]
    , [PubSecBudgetCnsmpnAmtType]
    , [JointVenture]
    , [JointVentureEquityGroup]
    , [JointVentureCostRecoveryCode]
    , [JointVenturePartner]
    , [JointVentureBillingType]
    , [JointVentureEquityType]
    , [JointVentureProductionDate]
    , [JointVentureBillingDate]
    , [JointVentureOperationalDate]
    , [CutbackRun]
    , [JointVentureAccountingActivity]
    , [PartnerVenture]
    , [PartnerEquityGroup]
    , [SenderCostRecoveryCode]
    , [CutbackAccount]
    , [CutbackCostObject]
    , [SettlementReferenceDate]
    , [AccrualObjectType]
    , [AccrualObject]
    , [AccrualSubobject]
    , [AccrualItemType]
    , [AccrualValueDate]
    , [FinancialValuationObjectType]
    , [FinancialValuationObject]
    , [FinancialValuationSubobject]
    , [NetDueDate]
    , [CreditRiskClass]
    , [WorkCenterInternalID]
    , [OrderOperation]
    , [OrderItem]
    , [OrderSuboperation]
    , [Equipment]
    , [FunctionalLocation]
    , [Assembly]
    , [MaintenanceActivityType]
    , [MaintenanceOrderPlanningCode]
    , [MaintPriorityType]
    , [MaintPriority]
    , [SuperiorOrder]
    , [ProductGroup]
    , [MaintenanceOrderIsPlanned]
    , [t_applicationId]
    , [t_jobId]
    , [t_jobDtm]
    , [t_jobBy]
    , [t_filePath]
    , [t_extractionDtm]
    , [t_lastActionBy]
    , [t_lastActionCd]
    , [t_lastActionDtm]
  )
  SELECT
    [MANDT]
  , [SourceLedger]
  , [CompanyCode]
  , [FiscalYear]
  , [AccountingDocument]
  , [LedgerGLLineItem]
  , [LedgerFiscalYear]
  , [GLRecordType]
  , [ChartOfAccounts]
  , [ControllingArea]
  , [FinancialTransactionType]
  , [BusinessTransactionType]
  , [ControllingBusTransacType]
  , [ReferenceDocumentType]
  , [LogicalSystem]
  , [ReferenceDocumentContext]
  , [ReferenceDocument]
  , [ReferenceDocumentItem]
  , [ReferenceDocumentItemGroup]
  , [IsReversal]
  , [IsReversed]
  , [ReversalReferenceDocumentCntxt]
  , [ReversalReferenceDocument]
  , [IsSettlement]
  , [IsSettled]
  , [PredecessorReferenceDocType]
  , [PredecessorReferenceDocCntxt]
  , [PredecessorReferenceDocument]
  , [PredecessorReferenceDocItem]
  , [SourceReferenceDocumentType]
  , [SourceLogicalSystem]
  , [SourceReferenceDocumentCntxt]
  , [SourceReferenceDocument]
  , [SourceReferenceDocumentItem]
  , [SourceReferenceDocSubitem]
  , [IsCommitment]
  , [JrnlEntryItemObsoleteReason]
  , [GLAccount]
  , [CostCenter]
  , [ProfitCenter]
  , [FunctionalArea]
  , [BusinessArea]
  , [Segment]
  , [PartnerCostCenter]
  , [PartnerProfitCenter]
  , [PartnerFunctionalArea]
  , [PartnerBusinessArea]
  , [PartnerCompany]
  , [PartnerSegment]
  , [BalanceTransactionCurrency]
  , [AmountInBalanceTransacCrcy]
  , [TransactionCurrency]
  , [AmountInTransactionCurrency]
  , [CompanyCodeCurrency]
  , [AmountInCompanyCodeCurrency]
  , [GlobalCurrency]
  , [AmountInGlobalCurrency]
  , [FreeDefinedCurrency1]
  , [AmountInFreeDefinedCurrency1]
  , [FreeDefinedCurrency2]
  , [AmountInFreeDefinedCurrency2]
  , [FreeDefinedCurrency3]
  , [AmountInFreeDefinedCurrency3]
  , [FreeDefinedCurrency4]
  , [AmountInFreeDefinedCurrency4]
  , [FreeDefinedCurrency5]
  , [AmountInFreeDefinedCurrency5]
  , [FreeDefinedCurrency6]
  , [AmountInFreeDefinedCurrency6]
  , [FreeDefinedCurrency7]
  , [AmountInFreeDefinedCurrency7]
  , [FreeDefinedCurrency8]
  , [AmountInFreeDefinedCurrency8]
  , [FixedAmountInGlobalCrcy]
  , [GrpValnFixedAmtInGlobCrcy]
  , [PrftCtrValnFxdAmtInGlobCrcy]
  , [FixedAmountInCoCoDeCrcy]
  , [TotalPriceVarcInGlobalCrcy]
  , [GrpValnTotPrcVarcInGlobCrcy]
  , [PrftCtrValnTotPrcVarcInGlbCrcy]
  , [FixedPriceVarcInGlobalCrcy]
  , [GrpValnFixedPrcVarcInGlobCrcy]
  , [PrftCtrValnFxdPrcVarcInGlbCrcy]
  , [ControllingObjectCurrency]
  , [AmountInObjectCurrency]
  , [BaseUnit]
  , [Quantity]
  , [FixedQuantity]
  , [CostSourceUnit]
  , [ValuationQuantity]
  , [ValuationFixedQuantity]
  , [AdditionalQuantity1Unit]
  , [AdditionalQuantity1]
  , [AdditionalQuantity2Unit]
  , [AdditionalQuantity2]
  , [AdditionalQuantity3Unit]
  , [AdditionalQuantity3]
  , [DebitCreditCode]
  , [FiscalPeriod]
  , [FiscalYearVariant]
  , [FiscalYearPeriod]
  , [PostingDate]
  , [DocumentDate]
  , [AccountingDocumentType]
  , [AccountingDocumentItem]
  , [AssignmentReference]
  , [AccountingDocumentCategory]
  , [PostingKey]
  , [TransactionTypeDetermination]
  , [SubLedgerAcctLineItemType]
  , [AccountingDocCreatedByUser]
  , [LastChangeDateTime]
  , [CreationDateTime]
  , [CreationDate]
  , [EliminationProfitCenter]
  , [OriginObjectType]
  , [GLAccountType]
  , [AlternativeGLAccount]
  , [CountryChartOfAccounts]
  , [InvoiceReference]
  , [InvoiceReferenceFiscalYear]
  , [FollowOnDocumentType]
  , [InvoiceItemReference]
  , [ReferencePurchaseOrderCategory]
  , [PurchasingDocument]
  , [PurchasingDocumentItem]
  , [AccountAssignmentNumber]
  , [DocumentItemText]
  , [SalesDocument]
  , [SalesDocumentItem]
  , [Product]
  , [Plant]
  , [Supplier]
  , [Customer]
  , [ServicesRenderedDate]
  , [ConditionContract]
  , [ExchangeRateDate]
  , [FinancialAccountType]
  , [SpecialGLCode]
  , [TaxCode]
  , [HouseBank]
  , [HouseBankAccount]
  , [IsOpenItemManaged]
  , [ClearingDate]
  , [ClearingAccountingDocument]
  , [ClearingDocFiscalYear]
  , [AssetDepreciationArea]
  , [MasterFixedAsset]
  , [FixedAsset]
  , [AssetValueDate]
  , [AssetTransactionType]
  , [AssetAcctTransClassfctn]
  , [DepreciationFiscalPeriod]
  , [GroupMasterFixedAsset]
  , [GroupFixedAsset]
  , [AssetClass]
  , [CostEstimate]
  , [InventorySpecialStockValnType]
  , [InventorySpecialStockType]
  , [InventorySpclStkSalesDocument]
  , [InventorySpclStkSalesDocItm]
  , [InvtrySpclStockWBSElmntIntID]
  , [InventorySpclStockWBSElement]
  , [InventorySpecialStockSupplier]
  , [InventoryValuationType]
  , [ValuationArea]
  , [SenderCompanyCode]
  , [SenderGLAccount]
  , [SenderAccountAssignment]
  , [SenderAccountAssignmentType]
  , [ControllingObject]
  , [CostOriginGroup]
  , [OriginSenderObject]
  , [ControllingDebitCreditCode]
  , [ControllingObjectDebitType]
  , [QuantityIsIncomplete]
  , [OffsettingAccount]
  , [OffsettingAccountType]
  , [OffsettingChartOfAccounts]
  , [LineItemIsCompleted]
  , [PersonnelNumber]
  , [ControllingObjectClass]
  , [PartnerCompanyCode]
  , [PartnerControllingObjectClass]
  , [OriginCostCenter]
  , [OriginProfitCenter]
  , [OriginCostCtrActivityType]
  , [AccountAssignment]
  , [AccountAssignmentType]
  , [CostCtrActivityType]
  , [OrderID]
  , [OrderCategory]
  , [WBSElementInternalID]
  , [WBSElement]
  , [PartnerWBSElementInternalID]
  , [PartnerWBSElement]
  , [ProjectInternalID]
  , [Project]
  , [PartnerProjectInternalID]
  , [PartnerProject]
  , [OperatingConcern]
  , [ProjectNetwork]
  , [RelatedNetworkActivity]
  , [BusinessProcess]
  , [CostObject]
  , [BillableControl]
  , [CostAnalysisResource]
  , [CustomerServiceNotification]
  , [ServiceDocumentType]
  , [ServiceDocument]
  , [ServiceDocumentItem]
  , [PartnerServiceDocumentType]
  , [PartnerServiceDocument]
  , [PartnerServiceDocumentItem]
  , [ServiceContractType]
  , [ServiceContract]
  , [ServiceContractItem]
  , [TimeSheetOvertimeCategory]
  , [PartnerAccountAssignment]
  , [PartnerAccountAssignmentType]
  , [WorkPackage]
  , [WorkItem]
  , [PartnerCostCtrActivityType]
  , [PartnerOrder]
  , [PartnerOrderCategory]
  , [PartnerSalesDocument]
  , [PartnerSalesDocumentItem]
  , [PartnerProjectNetwork]
  , [PartnerProjectNetworkActivity]
  , [PartnerBusinessProcess]
  , [PartnerCostObject]
  , [BillingDocumentType]
  , [SalesOrganization]
  , [DistributionChannel]
  , [OrganizationDivision]
  , [SoldProduct]
  , [SoldProductGroup]
  , [CustomerGroup]
  , [CustomerSupplierCountry]
  , [CustomerSupplierIndustry]
  , [SalesDistrict]
  , [BillToParty]
  , [ShipToParty]
  , [CustomerSupplierCorporateGroup]
  , [CashLedgerCompanyCode]
  , [CashLedgerAccount]
  , [FinancialManagementArea]
  , [FundsCenter]
  , [FundedProgram]
  , [Fund]
  , [GrantID]
  , [BudgetPeriod]
  , [PartnerFund]
  , [PartnerGrant]
  , [PartnerBudgetPeriod]
  , [PubSecBudgetAccount]
  , [PubSecBudgetAccountCoCode]
  , [PubSecBudgetCnsmpnDate]
  , [PubSecBudgetCnsmpnFsclPeriod]
  , [PubSecBudgetCnsmpnFsclYear]
  , [PubSecBudgetIsRelevant]
  , [PubSecBudgetCnsmpnType]
  , [PubSecBudgetCnsmpnAmtType]
  , [JointVenture]
  , [JointVentureEquityGroup]
  , [JointVentureCostRecoveryCode]
  , [JointVenturePartner]
  , [JointVentureBillingType]
  , [JointVentureEquityType]
  , [JointVentureProductionDate]
  , [JointVentureBillingDate]
  , [JointVentureOperationalDate]
  , [CutbackRun]
  , [JointVentureAccountingActivity]
  , [PartnerVenture]
  , [PartnerEquityGroup]
  , [SenderCostRecoveryCode]
  , [CutbackAccount]
  , [CutbackCostObject]
  , [SettlementReferenceDate]
  , [AccrualObjectType]
  , [AccrualObject]
  , [AccrualSubobject]
  , [AccrualItemType]
  , [AccrualValueDate]
  , [FinancialValuationObjectType]
  , [FinancialValuationObject]
  , [FinancialValuationSubobject]
  , [NetDueDate]
  , [CreditRiskClass]
  , [WorkCenterInternalID]
  , [OrderOperation]
  , [OrderItem]
  , [OrderSuboperation]
  , [Equipment]
  , [FunctionalLocation]
  , [Assembly]
  , [MaintenanceActivityType]
  , [MaintenanceOrderPlanningCode]
  , [MaintPriorityType]
  , [MaintPriority]
  , [SuperiorOrder]
  , [ProductGroup]
  , [MaintenanceOrderIsPlanned]
  , [t_applicationId]
  , [t_jobId]
  , [t_jobDtm]
  , [t_jobBy]
  , [t_filePath]
  , [t_extractionDtm]
  , SYSTEM_USER AS [t_lastActionBy]
  , ( CASE
        WHEN src.[ODQ_CHANGEMODE] = ''  AND src.[ODQ_ENTITYCNTR] = 0
          THEN 'I'
        WHEN src.[ODQ_CHANGEMODE] = 'U' AND src.[ODQ_ENTITYCNTR] = 1
          THEN 'I'
        WHEN src.[ODQ_CHANGEMODE] = 'D' AND src.[ODQ_ENTITYCNTR] = -1
          THEN 'D'
        WHEN src.[ODQ_CHANGEMODE] = 'С' AND src.[ODQ_ENTITYCNTR] = 1
          THEN 'I'
    END) AS [t_lastActionCd]
  , GETUTCDATE() AS [t_lastActionDtm]
  FROM
    [base_s4h_cax].[vw_I_GLAccountLineItemRawData_delta] AS src
  WHERE NOT EXISTS (
    SELECT 
      [MANDT],
      [SourceLedger],
      [CompanyCode],
      [FiscalYear],
      [AccountingDocument],
      [LedgerGLLineItem]
    FROM 
      [base_s4h_cax].[I_GLAccountLineItemRawData_active] tgt2
    WHERE 
      tgt2.MANDT = src.MANDT
      AND
      tgt2.[SourceLedger] = src.[SourceLedger]
      AND
      tgt2.[CompanyCode] = src.[CompanyCode]
      AND
      tgt2.[FiscalYear] = src.[FiscalYear]
      AND
      tgt2.[AccountingDocument] = src.[AccountingDocument]
      AND
      tgt2.[LedgerGLLineItem] = src.[LedgerGLLineItem]
  )

END
