CREATE PROC [base_s4h_cax].[sp_load_C_SalesDocumentItemDEX]
AS
BEGIN

    -- Update or Delete(marks as Delete - 'D') records the base table based on the delta dataset
    UPDATE tgt
    SET
          tgt.[SDDocumentCategory] = src.[SDDocumentCategory]
        , tgt.[SalesDocumentType] = src.[SalesDocumentType]
        , tgt.[SalesDocumentItemCategory] = src.[SalesDocumentItemCategory]
        , tgt.[IsReturnsItem] = src.[IsReturnsItem]
        , tgt.[CreationDate] = src.[CreationDate]
        , tgt.[CreationTime] = src.[CreationTime]
        , tgt.[LastChangeDate] = src.[LastChangeDate]
        , tgt.[SalesOrganization] = src.[SalesOrganization]
        , tgt.[DistributionChannel] = src.[DistributionChannel]
        , tgt.[Division] = src.[Division]
        , tgt.[SalesGroup] = src.[SalesGroup]
        , tgt.[SalesOffice] = src.[SalesOffice]
        , tgt.[InternationalArticleNumber] = src.[InternationalArticleNumber]
        , tgt.[Batch] = src.[Batch]
        , tgt.[Material] = src.[Material]
        , tgt.[OriginallyRequestedMaterial] = src.[OriginallyRequestedMaterial]
        , tgt.[MaterialSubstitutionReason] = src.[MaterialSubstitutionReason]
        , tgt.[MaterialGroup] = src.[MaterialGroup]
        , tgt.[AdditionalMaterialGroup1] = src.[AdditionalMaterialGroup1]
        , tgt.[AdditionalMaterialGroup2] = src.[AdditionalMaterialGroup2]
        , tgt.[AdditionalMaterialGroup3] = src.[AdditionalMaterialGroup3]
        , tgt.[AdditionalMaterialGroup4] = src.[AdditionalMaterialGroup4]
        , tgt.[AdditionalMaterialGroup5] = src.[AdditionalMaterialGroup5]
        , tgt.[SoldToParty] = src.[SoldToParty]
        , tgt.[AdditionalCustomerGroup1] = src.[AdditionalCustomerGroup1]
        , tgt.[AdditionalCustomerGroup2] = src.[AdditionalCustomerGroup2]
        , tgt.[AdditionalCustomerGroup3] = src.[AdditionalCustomerGroup3]
        , tgt.[AdditionalCustomerGroup4] = src.[AdditionalCustomerGroup4]
        , tgt.[AdditionalCustomerGroup5] = src.[AdditionalCustomerGroup5]
        , tgt.[ShipToParty] = src.[ShipToParty]
        , tgt.[PayerParty] = src.[PayerParty]
        , tgt.[BillToParty] = src.[BillToParty]
        , tgt.[SDDocumentReason] = src.[SDDocumentReason]
        , tgt.[SalesDocumentDate] = src.[SalesDocumentDate]
        , tgt.[OrderQuantity] = src.[OrderQuantity]
        , tgt.[OrderQuantityUnit] = src.[OrderQuantityUnit]
        , tgt.[TargetQuantity] = src.[TargetQuantity]
        , tgt.[TargetQuantityUnit] = src.[TargetQuantityUnit]
        , tgt.[TargetToBaseQuantityDnmntr] = src.[TargetToBaseQuantityDnmntr]
        , tgt.[TargetToBaseQuantityNmrtr] = src.[TargetToBaseQuantityNmrtr]
        , tgt.[OrderToBaseQuantityDnmntr] = src.[OrderToBaseQuantityDnmntr]
        , tgt.[OrderToBaseQuantityNmrtr] = src.[OrderToBaseQuantityNmrtr]
        , tgt.[ConfdDelivQtyInOrderQtyUnit] = src.[ConfdDelivQtyInOrderQtyUnit]
        , tgt.[TargetDelivQtyInOrderQtyUnit] = src.[TargetDelivQtyInOrderQtyUnit]
        , tgt.[ConfdDeliveryQtyInBaseUnit] = src.[ConfdDeliveryQtyInBaseUnit]
        , tgt.[BaseUnit] = src.[BaseUnit]
        , tgt.[ItemGrossWeight] = src.[ItemGrossWeight]
        , tgt.[ItemNetWeight] = src.[ItemNetWeight]
        , tgt.[ItemWeightUnit] = src.[ItemWeightUnit]
        , tgt.[ItemVolume] = src.[ItemVolume]
        , tgt.[ItemVolumeUnit] = src.[ItemVolumeUnit]
        , tgt.[ServicesRenderedDate] = src.[ServicesRenderedDate]
        , tgt.[SalesDistrict] = src.[SalesDistrict]
        , tgt.[CustomerGroup] = src.[CustomerGroup]
        , tgt.[HdrOrderProbabilityInPercent] = src.[HdrOrderProbabilityInPercent]
        , tgt.[ItemOrderProbabilityInPercent] = src.[ItemOrderProbabilityInPercent]
        , tgt.[SalesDocumentRjcnReason] = src.[SalesDocumentRjcnReason]
        , tgt.[PricingDate] = src.[PricingDate]
        , tgt.[ExchangeRateDate] = src.[ExchangeRateDate]
        , tgt.[PriceDetnExchangeRate] = src.[PriceDetnExchangeRate]
        , tgt.[StatisticalValueControl] = src.[StatisticalValueControl]
        , tgt.[NetAmount] = src.[NetAmount]
        , tgt.[TransactionCurrency] = src.[TransactionCurrency]
        , tgt.[SalesOrganizationCurrency] = src.[SalesOrganizationCurrency]
        , tgt.[NetPriceAmount] = src.[NetPriceAmount]
        , tgt.[NetPriceQuantity] = src.[NetPriceQuantity]
        , tgt.[NetPriceQuantityUnit] = src.[NetPriceQuantityUnit]
        , tgt.[TaxAmount] = src.[TaxAmount]
        , tgt.[CostAmount] = src.[CostAmount]
        , tgt.[Subtotal1Amount] = src.[Subtotal1Amount]
        , tgt.[Subtotal2Amount] = src.[Subtotal2Amount]
        , tgt.[Subtotal3Amount] = src.[Subtotal3Amount]
        , tgt.[Subtotal4Amount] = src.[Subtotal4Amount]
        , tgt.[Subtotal5Amount] = src.[Subtotal5Amount]
        , tgt.[Subtotal6Amount] = src.[Subtotal6Amount]
        , tgt.[ShippingPoint] = src.[ShippingPoint]
        , tgt.[ShippingType] = src.[ShippingType]
        , tgt.[DeliveryPriority] = src.[DeliveryPriority]
        , tgt.[InventorySpecialStockType] = src.[InventorySpecialStockType]
        , tgt.[RequestedDeliveryDate] = src.[RequestedDeliveryDate]
        , tgt.[ShippingCondition] = src.[ShippingCondition]
        , tgt.[DeliveryBlockReason] = src.[DeliveryBlockReason]
        , tgt.[Plant] = src.[Plant]
        , tgt.[StorageLocation] = src.[StorageLocation]
        , tgt.[Route] = src.[Route]
        , tgt.[IncotermsClassification] = src.[IncotermsClassification]
        , tgt.[IncotermsVersion] = src.[IncotermsVersion]
        , tgt.[IncotermsTransferLocation] = src.[IncotermsTransferLocation]
        , tgt.[IncotermsLocation1] = src.[IncotermsLocation1]
        , tgt.[IncotermsLocation2] = src.[IncotermsLocation2]
        , tgt.[MinDeliveryQtyInBaseUnit] = src.[MinDeliveryQtyInBaseUnit]
        , tgt.[UnlimitedOverdeliveryIsAllowed] = src.[UnlimitedOverdeliveryIsAllowed]
        , tgt.[OverdelivTolrtdLmtRatioInPct] = src.[OverdelivTolrtdLmtRatioInPct]
        , tgt.[UnderdelivTolrtdLmtRatioInPct] = src.[UnderdelivTolrtdLmtRatioInPct]
        , tgt.[PartialDeliveryIsAllowed] = src.[PartialDeliveryIsAllowed]
        , tgt.[BindingPeriodValidityStartDate] = src.[BindingPeriodValidityStartDate]
        , tgt.[BindingPeriodValidityEndDate] = src.[BindingPeriodValidityEndDate]
        , tgt.[OutlineAgreementTargetAmount] = src.[OutlineAgreementTargetAmount]
        , tgt.[BillingDocumentDate] = src.[BillingDocumentDate]
        , tgt.[BillingCompanyCode] = src.[BillingCompanyCode]
        , tgt.[HeaderBillingBlockReason] = src.[HeaderBillingBlockReason]
        , tgt.[ItemBillingBlockReason] = src.[ItemBillingBlockReason]
        , tgt.[FiscalYear] = src.[FiscalYear]
        , tgt.[FiscalPeriod] = src.[FiscalPeriod]
        , tgt.[CustomerAccountAssignmentGroup] = src.[CustomerAccountAssignmentGroup]
        , tgt.[ExchangeRateType] = src.[ExchangeRateType]
        , tgt.[Currency] = src.[Currency]
        , tgt.[FiscalYearVariant] = src.[FiscalYearVariant]
        , tgt.[BusinessArea] = src.[BusinessArea]
        , tgt.[ProfitCenter] = src.[ProfitCenter]
        , tgt.[OrderID] = src.[OrderID]
        , tgt.[ProfitabilitySegment] = src.[ProfitabilitySegment]
        , tgt.[ControllingArea] = src.[ControllingArea]
        , tgt.[ReferenceSDDocument] = src.[ReferenceSDDocument]
        , tgt.[ReferenceSDDocumentItem] = src.[ReferenceSDDocumentItem]
        , tgt.[ReferenceSDDocumentCategory] = src.[ReferenceSDDocumentCategory]
        , tgt.[OriginSDDocument] = src.[OriginSDDocument]
        , tgt.[OriginSDDocumentItem] = src.[OriginSDDocumentItem]
        , tgt.[OverallSDProcessStatus] = src.[OverallSDProcessStatus]
        , tgt.[OverallTotalDeliveryStatus] = src.[OverallTotalDeliveryStatus]
        , tgt.[OverallOrdReltdBillgStatus] = src.[OverallOrdReltdBillgStatus]
        , tgt.[TotalCreditCheckStatus] = src.[TotalCreditCheckStatus]
        , tgt.[DeliveryBlockStatus] = src.[DeliveryBlockStatus]
        , tgt.[BillingBlockStatus] = src.[BillingBlockStatus]
        , tgt.[TotalSDDocReferenceStatus] = src.[TotalSDDocReferenceStatus]
        , tgt.[SDDocReferenceStatus] = src.[SDDocReferenceStatus]
        , tgt.[OverallSDDocumentRejectionSts] = src.[OverallSDDocumentRejectionSts]
        , tgt.[SDDocumentRejectionStatus] = src.[SDDocumentRejectionStatus]
        , tgt.[OverallTotalSDDocRefStatus] = src.[OverallTotalSDDocRefStatus]
        , tgt.[OverallSDDocReferenceStatus] = src.[OverallSDDocReferenceStatus]
        , tgt.[ItemGeneralIncompletionStatus] = src.[ItemGeneralIncompletionStatus]
        , tgt.[ItemBillingIncompletionStatus] = src.[ItemBillingIncompletionStatus]
        , tgt.[PricingIncompletionStatus] = src.[PricingIncompletionStatus]
        , tgt.[ItemDeliveryIncompletionStatus] = src.[ItemDeliveryIncompletionStatus]
        , tgt.[SDoc_ControllingObject] = src.[SDoc_ControllingObject]
        , tgt.[SDItem_ControllingObject] = src.[SDItem_ControllingObject]
        , tgt.[t_jobId] = src.[t_jobId]
        , tgt.[t_jobDtm] = src.[t_jobDtm]
        , tgt.[t_jobBy] = src.[t_jobBy]
        , tgt.[t_filePath] = src.[t_filePath]
        , tgt.[t_extractionDtm] = src.[t_extractionDtm]
        , tgt.[t_lastActionBy] = CURRENT_USER
        , tgt.[t_lastActionCd] = (case
                                     when src.[ODQ_CHANGEMODE] = 'U' and src.[ODQ_ENTITYCNTR] = 1
                                         then 'U'
                                     when src.[ODQ_CHANGEMODE] = 'D' and src.[ODQ_ENTITYCNTR] = -1
                                         then 'D'
                                 end)
        , tgt.[t_lastActionDtm] = GETUTCDATE()
    FROM
        [base_s4h_cax].[C_SalesDocumentItemDEX_active] as tgt
    INNER JOIN
        [base_s4h_cax].[vw_C_SalesDocumentItemDEX] as src
        ON
            tgt.MANDT = src.MANDT
            AND
            tgt.SalesDocument = src.SalesDocument
            AND
            tgt.SalesDocumentItem = src.SalesDocumentItem
            and
            (
                (
                    src.[ODQ_CHANGEMODE]  = 'U'
                    AND
                    src.[ODQ_ENTITYCNTR] = 1
                )
                OR
                (
                    src.[ODQ_CHANGEMODE] = 'D'
                    AND
                    src.[ODQ_ENTITYCNTR] = -1
                )
            )

   -- Insert new records in the base table based on the delta dataset

    INSERT INTO
        [base_s4h_cax].[C_SalesDocumentItemDEX_active] (
              [MANDT]
            , [SalesDocument]
            , [SalesDocumentItem]
            , [SDDocumentCategory]
            , [SalesDocumentType]
            , [SalesDocumentItemCategory]
            , [IsReturnsItem]
            , [CreationDate]
            , [CreationTime]
            , [LastChangeDate]
            , [SalesOrganization]
            , [DistributionChannel]
            , [Division]
            , [SalesGroup]
            , [SalesOffice]
            , [InternationalArticleNumber]
            , [Batch]
            , [Material]
            , [OriginallyRequestedMaterial]
            , [MaterialSubstitutionReason]
            , [MaterialGroup]
            , [AdditionalMaterialGroup1]
            , [AdditionalMaterialGroup2]
            , [AdditionalMaterialGroup3]
            , [AdditionalMaterialGroup4]
            , [AdditionalMaterialGroup5]
            , [SoldToParty]
            , [AdditionalCustomerGroup1]
            , [AdditionalCustomerGroup2]
            , [AdditionalCustomerGroup3]
            , [AdditionalCustomerGroup4]
            , [AdditionalCustomerGroup5]
            , [ShipToParty]
            , [PayerParty]
            , [BillToParty]
            , [SDDocumentReason]
            , [SalesDocumentDate]
            , [OrderQuantity]
            , [OrderQuantityUnit]
            , [TargetQuantity]
            , [TargetQuantityUnit]
            , [TargetToBaseQuantityDnmntr]
            , [TargetToBaseQuantityNmrtr]
            , [OrderToBaseQuantityDnmntr]
            , [OrderToBaseQuantityNmrtr]
            , [ConfdDelivQtyInOrderQtyUnit]
            , [TargetDelivQtyInOrderQtyUnit]
            , [ConfdDeliveryQtyInBaseUnit]
            , [BaseUnit]
            , [ItemGrossWeight]
            , [ItemNetWeight]
            , [ItemWeightUnit]
            , [ItemVolume]
            , [ItemVolumeUnit]
            , [ServicesRenderedDate]
            , [SalesDistrict]
            , [CustomerGroup]
            , [HdrOrderProbabilityInPercent]
            , [ItemOrderProbabilityInPercent]
            , [SalesDocumentRjcnReason]
            , [PricingDate]
            , [ExchangeRateDate]
            , [PriceDetnExchangeRate]
            , [StatisticalValueControl]
            , [NetAmount]
            , [TransactionCurrency]
            , [SalesOrganizationCurrency]
            , [NetPriceAmount]
            , [NetPriceQuantity]
            , [NetPriceQuantityUnit]
            , [TaxAmount]
            , [CostAmount]
            , [Subtotal1Amount]
            , [Subtotal2Amount]
            , [Subtotal3Amount]
            , [Subtotal4Amount]
            , [Subtotal5Amount]
            , [Subtotal6Amount]
            , [ShippingPoint]
            , [ShippingType]
            , [DeliveryPriority]
            , [InventorySpecialStockType]
            , [RequestedDeliveryDate]
            , [ShippingCondition]
            , [DeliveryBlockReason]
            , [Plant]
            , [StorageLocation]
            , [Route]
            , [IncotermsClassification]
            , [IncotermsVersion]
            , [IncotermsTransferLocation]
            , [IncotermsLocation1]
            , [IncotermsLocation2]
            , [MinDeliveryQtyInBaseUnit]
            , [UnlimitedOverdeliveryIsAllowed]
            , [OverdelivTolrtdLmtRatioInPct]
            , [UnderdelivTolrtdLmtRatioInPct]
            , [PartialDeliveryIsAllowed]
            , [BindingPeriodValidityStartDate]
            , [BindingPeriodValidityEndDate]
            , [OutlineAgreementTargetAmount]
            , [BillingDocumentDate]
            , [BillingCompanyCode]
            , [HeaderBillingBlockReason]
            , [ItemBillingBlockReason]
            , [FiscalYear]
            , [FiscalPeriod]
            , [CustomerAccountAssignmentGroup]
            , [ExchangeRateType]
            , [Currency]
            , [FiscalYearVariant]
            , [BusinessArea]
            , [ProfitCenter]
            , [OrderID]
            , [ProfitabilitySegment]
            , [ControllingArea]
            , [ReferenceSDDocument]
            , [ReferenceSDDocumentItem]
            , [ReferenceSDDocumentCategory]
            , [OriginSDDocument]
            , [OriginSDDocumentItem]
            , [OverallSDProcessStatus]
            , [OverallTotalDeliveryStatus]
            , [OverallOrdReltdBillgStatus]
            , [TotalCreditCheckStatus]
            , [DeliveryBlockStatus]
            , [BillingBlockStatus]
            , [TotalSDDocReferenceStatus]
            , [SDDocReferenceStatus]
            , [OverallSDDocumentRejectionSts]
            , [SDDocumentRejectionStatus]
            , [OverallTotalSDDocRefStatus]
            , [OverallSDDocReferenceStatus]
            , [ItemGeneralIncompletionStatus]
            , [ItemBillingIncompletionStatus]
            , [PricingIncompletionStatus]
            , [ItemDeliveryIncompletionStatus]
            , [SDoc_ControllingObject]
            , [SDItem_ControllingObject]
            , [t_applicationId]
            , [t_jobId]
            , [t_jobDtm]
            , [t_jobBy]
            , [t_filePath]
            , [t_extractionDtm]
            , [t_lastActionBy]
            , [t_lastActionCd]
            , [t_lastActionDtm]
        )
        SELECT
              [MANDT]
            , [SalesDocument]
            , [SalesDocumentItem]
            , [SDDocumentCategory]
            , [SalesDocumentType]
            , [SalesDocumentItemCategory]
            , [IsReturnsItem]
            , [CreationDate]
            , [CreationTime]
            , [LastChangeDate]
            , [SalesOrganization]
            , [DistributionChannel]
            , [Division]
            , [SalesGroup]
            , [SalesOffice]
            , [InternationalArticleNumber]
            , [Batch]
            , [Material]
            , [OriginallyRequestedMaterial]
            , [MaterialSubstitutionReason]
            , [MaterialGroup]
            , [AdditionalMaterialGroup1]
            , [AdditionalMaterialGroup2]
            , [AdditionalMaterialGroup3]
            , [AdditionalMaterialGroup4]
            , [AdditionalMaterialGroup5]
            , [SoldToParty]
            , [AdditionalCustomerGroup1]
            , [AdditionalCustomerGroup2]
            , [AdditionalCustomerGroup3]
            , [AdditionalCustomerGroup4]
            , [AdditionalCustomerGroup5]
            , [ShipToParty]
            , [PayerParty]
            , [BillToParty]
            , [SDDocumentReason]
            , [SalesDocumentDate]
            , [OrderQuantity]
            , [OrderQuantityUnit]
            , [TargetQuantity]
            , [TargetQuantityUnit]
            , [TargetToBaseQuantityDnmntr]
            , [TargetToBaseQuantityNmrtr]
            , [OrderToBaseQuantityDnmntr]
            , [OrderToBaseQuantityNmrtr]
            , [ConfdDelivQtyInOrderQtyUnit]
            , [TargetDelivQtyInOrderQtyUnit]
            , [ConfdDeliveryQtyInBaseUnit]
            , [BaseUnit]
            , [ItemGrossWeight]
            , [ItemNetWeight]
            , [ItemWeightUnit]
            , [ItemVolume]
            , [ItemVolumeUnit]
            , [ServicesRenderedDate]
            , [SalesDistrict]
            , [CustomerGroup]
            , [HdrOrderProbabilityInPercent]
            , [ItemOrderProbabilityInPercent]
            , [SalesDocumentRjcnReason]
            , [PricingDate]
            , [ExchangeRateDate]
            , [PriceDetnExchangeRate]
            , [StatisticalValueControl]
            , [NetAmount]
            , [TransactionCurrency]
            , [SalesOrganizationCurrency]
            , [NetPriceAmount]
            , [NetPriceQuantity]
            , [NetPriceQuantityUnit]
            , [TaxAmount]
            , [CostAmount]
            , [Subtotal1Amount]
            , [Subtotal2Amount]
            , [Subtotal3Amount]
            , [Subtotal4Amount]
            , [Subtotal5Amount]
            , [Subtotal6Amount]
            , [ShippingPoint]
            , [ShippingType]
            , [DeliveryPriority]
            , [InventorySpecialStockType]
            , [RequestedDeliveryDate]
            , [ShippingCondition]
            , [DeliveryBlockReason]
            , [Plant]
            , [StorageLocation]
            , [Route]
            , [IncotermsClassification]
            , [IncotermsVersion]
            , [IncotermsTransferLocation]
            , [IncotermsLocation1]
            , [IncotermsLocation2]
            , [MinDeliveryQtyInBaseUnit]
            , [UnlimitedOverdeliveryIsAllowed]
            , [OverdelivTolrtdLmtRatioInPct]
            , [UnderdelivTolrtdLmtRatioInPct]
            , [PartialDeliveryIsAllowed]
            , [BindingPeriodValidityStartDate]
            , [BindingPeriodValidityEndDate]
            , [OutlineAgreementTargetAmount]
            , [BillingDocumentDate]
            , [BillingCompanyCode]
            , [HeaderBillingBlockReason]
            , [ItemBillingBlockReason]
            , [FiscalYear]
            , [FiscalPeriod]
            , [CustomerAccountAssignmentGroup]
            , [ExchangeRateType]
            , [Currency]
            , [FiscalYearVariant]
            , [BusinessArea]
            , [ProfitCenter]
            , [OrderID]
            , [ProfitabilitySegment]
            , [ControllingArea]
            , [ReferenceSDDocument]
            , [ReferenceSDDocumentItem]
            , [ReferenceSDDocumentCategory]
            , [OriginSDDocument]
            , [OriginSDDocumentItem]
            , [OverallSDProcessStatus]
            , [OverallTotalDeliveryStatus]
            , [OverallOrdReltdBillgStatus]
            , [TotalCreditCheckStatus]
            , [DeliveryBlockStatus]
            , [BillingBlockStatus]
            , [TotalSDDocReferenceStatus]
            , [SDDocReferenceStatus]
            , [OverallSDDocumentRejectionSts]
            , [SDDocumentRejectionStatus]
            , [OverallTotalSDDocRefStatus]
            , [OverallSDDocReferenceStatus]
            , [ItemGeneralIncompletionStatus]
            , [ItemBillingIncompletionStatus]
            , [PricingIncompletionStatus]
            , [ItemDeliveryIncompletionStatus]
            , [SDoc_ControllingObject]
            , [SDItem_ControllingObject]
            , [t_applicationId]
            , [t_jobId]
            , [t_jobDtm]
            , [t_jobBy]
            , [t_filePath]
            , [t_extractionDtm]
            , CURRENT_USER as [t_lastActionBy]
            , (case
                    when src.[ODQ_CHANGEMODE] = '' and src.[ODQ_ENTITYCNTR] = 0
                        then 'I'
                    when src.[ODQ_CHANGEMODE] = 'U' and src.[ODQ_ENTITYCNTR] = 1
                        then 'I'
                    when src.[ODQ_CHANGEMODE] = 'D' and src.[ODQ_ENTITYCNTR] = -1
                        then 'D'
                end) as [t_lastActionCd]
            , GETUTCDATE() as [t_lastActionDtm]
        FROM [base_s4h_cax].[vw_C_SalesDocumentItemDEX] as src
        WHERE NOT EXISTS (
            SELECT
                MANDT
                ,SalesDocument
                ,SalesDocumentItem
            FROM
                [base_s4h_cax].[C_SalesDocumentItemDEX_active] tgt2
            WHERE
                tgt2.MANDT = src.MANDT
                AND
                tgt2.SalesDocument = src.SalesDocument
                AND
                tgt2.SalesDocumentItem = src.SalesDocumentItem
        )
END
