CREATE PROC [base_s4h_uat_caa].[sp_load_Customer_base]
	@t_applicationId [varchar](7),
	@t_jobId [varchar](36),
	@t_lastDtm [datetime],
	@t_lastActionBy [nvarchar](20),
	@t_filePath [nvarchar](1024)
AS
BEGIN
	
	TRUNCATE TABLE [base_s4h_uat_caa].[I_Customer]

	INSERT INTO [base_s4h_uat_caa].[I_Customer](
		[Customer]
		,[CustomerName]
		,[CustomerFullName]
		,[CreatedByUser]
		,[CreationDate]
		,[AddressID]
		,[CustomerClassification]
		,[VATRegistration]
		,[CustomerAccountGroup]
		,[AuthorizationGroup]
		,[DeliveryIsBlocked]
		,[PostingIsBlocked]
		,[BillingIsBlockedForCustomer]
		,[OrderIsBlockedForCustomer]
		,[InternationalLocationNumber1]
		,[IsOneTimeAccount]
		,[TaxJurisdiction]
		,[Industry]
		,[TaxNumberType]
		,[TaxNumber1]
		,[TaxNumber2]
		,[TaxNumber3]
		,[TaxNumber4]
		,[TaxNumber5]
		,[CustomerCorporateGroup]
		,[Supplier]
		,[NielsenRegion]
		,[IndustryCode1]
		,[IndustryCode2]
		,[IndustryCode3]
		,[IndustryCode4]
		,[IndustryCode5]
		,[Country]
		,[OrganizationBPName1]
		,[OrganizationBPName2]
		,[CityName]
		,[PostalCode]
		,[StreetName]
		,[SortField]
		,[FaxNumber]
		,[BR_SUFRAMACode]
		,[Region]
		,[TelephoneNumber1]
		,[TelephoneNumber2]
		,[AlternativePayerAccount]
		,[DataMediumExchangeIndicator]
		,[VATLiability]
		,[IsBusinessPurposeCompleted]
		,[ResponsibleType]
		,[FiscalAddress]
		,[NFPartnerIsNaturalPerson]
		,[DeletionIndicator]
		,[Language]
		,[TradingPartner]
		--,[DeliveryDateTypeRule] doesn't exist in source file
		,[TaxInvoiceRepresentativeName]
		,[BusinessType]
		,[IndustryType]
		--,[TW_CollvBillingIsSupported] doesn't exist in source file
		--,[AlternativePayeeIsAllowed] doesn't exist in source file
		,[t_applicationId]
		,[t_jobId]
		,[t_lastDtm]
		,[t_lastActionBy]
		,[t_filePath]
	)
	SELECT 	
		[Customer]
		,[CustomerName]
		,[CustomerFullName]
		,[CreatedByUser]
		,CASE [CreationDate]
			WHEN '00000000' THEN '19000101' 
			ELSE CONVERT([date], [CreationDate], 112) 
		 END AS [CreationDate]
		,[AddressID]
		,[CustomerClassification]
		,[VATRegistration]
		,[CustomerAccountGroup]
		,[AuthorizationGroup]
		,[DeliveryIsBlocked]
		,[PostingIsBlocked]
		,[BillingIsBlockedForCustomer]
		,[OrderIsBlockedForCustomer]
		,CONVERT([char](7), [InternationalLocationNumber1]) AS [InternationalLocationNumber1]
		,[IsOneTimeAccount]
		,[TaxJurisdiction]
		,[Industry]
		,[TaxNumberType]
		,[TaxNumber1]
		,[TaxNumber2]
		,[TaxNumber3]
		,[TaxNumber4]
		,[TaxNumber5]
		,[CustomerCorporateGroup]
		,[Supplier]
		,[NielsenRegion]
		,[IndustryCode1]
		,[IndustryCode2]
		,[IndustryCode3]
		,[IndustryCode4]
		,[IndustryCode5]
		,[Country]
		,[OrganizationBPName1]
		,[OrganizationBPName2]
		,[CityName]
		,[PostalCode]
		,[StreetName]
		,[SortField]
		,[FaxNumber]
		,[BR_SUFRAMACode]
		,[Region]
		,[TelephoneNumber1]
		,[TelephoneNumber2]
		,[AlternativePayerAccount]
		,[DataMediumExchangeIndicator]
		,[VATLiability]
		,[IsBusinessPurposeCompleted]
		,[ResponsibleType]
		,[FiscalAddress]
		,[NFPartnerIsNaturalPerson]
		,[DeletionIndicator]
		,CONVERT([char](1), [Language]) AS [Language]
		,[TradingPartner]
		,[TaxInvoiceRepresentativeName]
		,[BusinessType]
		,[IndustryType]
		,@t_applicationId AS t_applicationId
		,@t_jobId AS t_jobId
		,@t_lastDtm AS t_lastDtm
		,@t_lastActionBy AS t_lastActionBy
		,@t_filePath AS t_filePath
	FROM [base_s4h_uat_caa].[I_Customer_staging]
END
