CREATE PROC [base_s4h_uat_caa].[sp_load_CostCenter_base]
    @t_applicationId [varchar](7),
    @t_jobId [varchar](36),
    @t_lastDtm [datetime],
    @t_lastActionBy [nvarchar](20),
    @t_filePath [nvarchar](1024) 
AS
BEGIN
	
	TRUNCATE TABLE [base_s4h_uat_caa].[I_CostCenter]

	INSERT INTO [base_s4h_uat_caa].[I_CostCenter](
	   [ControllingArea]
      ,[CostCenter]
      ,[ValidityEndDate]
      ,[ValidityStartDate]
      ,[IsBlkdForPrimaryCostsPosting]
      ,[IsBlockedForPlanPrimaryCosts]
      ,[CompanyCode]
      ,[BusinessArea]
      ,[CostCenterCategory]
      ,[CostCtrResponsiblePersonName]
      ,[CostCtrResponsibleUser]
      ,[CostCenterCurrency]
      ,[CostingSheet]
      ,[TaxJurisdiction]
      ,[ProfitCenter]
      ,[Plant]
      ,[LogicalSystem]
      ,[CostCenterCreationDate]
      ,[CostCenterCreatedByUser]
      ,[IsBlkdForSecondaryCostsPosting]
      ,[IsBlockedForRevenuePosting]
      ,[IsBlockedForCommitmentPosting]
      ,[IsBlockedForPlanSecondaryCosts]
      ,[IsBlockedForPlanRevenues]
      ,[CostCenterAllocationMethod]
      ,[ConsumptionQtyIsRecorded]
      ,[Department]
      ,[SubsequentCostCenter]
      ,[ConditionUsage]
      ,[ConditionApplication]
      ,[CostCenterAccountingOverhead]
      ,[Country]
      ,[FormOfAddress]
      ,[AddressName]
      ,[AddressAdditionalName]
      ,[CostCenterAddrName3]
      ,[CostCenterAddrName4]
      ,[CityName]
      ,[District]
      ,[StreetAddressName]
      ,[POBox]
      ,[PostalCode]
      ,[POBoxPostalCode]
      ,[Region]
      ,[Language]
      ,[TeleboxNumber]
      ,[PhoneNumber1]
      ,[PhoneNumber2]
      ,[FaxNumber]
      ,[TeletexNumber]
      ,[TelexNumber]
      ,[DataCommunicationPhoneNumber]
      ,[CostCenterPrinterDestination]
      ,[CostCenterStandardHierArea]
      ,[CostCollector]
      ,[CostCenterIsComplete]
      ,[IsStatisticalCostCenter]
      ,[ObjectInternalID]
      ,[CostCenterFunction]
      ,[CostCenterAlternativeFunction]
      ,[FunctionalArea]
      ,[ActyIndepFormulaPlanningTmpl]
      ,[ActyDepdntFormulaPlanningTmpl]
      ,[ActyIndependentAllocationTmpl]
      ,[ActyDependentAllocationTmpl]
      ,[ActlIndepStatisticalKeyFigures]
      ,[ActlDepStatisticalKeyFigures]
      ,[JointVenture]
      ,[JointVentureRecoveryCode]
      ,[JointVentureEquityType]
      ,[JointVentureObjectType]
      ,[JointVentureClass]
      ,[JointVentureSubClass]
      ,[BudgetCarryingCostCenter]
      ,[AvailabilityControlProfile]
      ,[AvailabilityControlIsActive]
      ,[Fund]
      ,[GrantID]
      ,[FundIsFixAssigned]
      ,[GrantIDIsFixAssigned]
      ,[FunctionalAreaIsFixAssigned]
      ,[t_applicationId]
      ,[t_jobId]
      ,[t_lastDtm]
      ,[t_lastActionBy]
      ,[t_filePath]
	)
	SELECT
	 [ControllingArea]
    ,[CostCenter]
    ,CASE [ValidityEndDate]
	 WHEN '00000000' THEN '19000101' 
	 ELSE CONVERT([date], [ValidityEndDate], 112) 
	 END AS [ValidityEndDate]
	,CASE [ValidityStartDate]
	 WHEN '00000000' THEN '19000101' 
	 ELSE CONVERT([date], [ValidityStartDate], 112) 
	 END AS [ValidityStartDate]
    ,[IsBlkdForPrimaryCostsPosting]
    ,[IsBlockedForPlanPrimaryCosts]
    ,[CompanyCode]
    ,[BusinessArea]
    ,[CostCenterCategory]
    ,[CostCtrResponsiblePersonName]
    ,[CostCtrResponsibleUser]
    ,CONVERT([char](5), [CostCenterCurrency]) AS [CostCenterCurrency]
    ,[CostingSheet]
    ,[TaxJurisdiction]
    ,[ProfitCenter]
    ,[Plant]
    ,[LogicalSystem]
    ,CASE [CostCenterCreationDate]
	 WHEN '00000000' THEN '19000101' 
	 ELSE CONVERT([date], [CostCenterCreationDate], 112) 
	 END AS [CostCenterCreationDate]
    ,[CostCenterCreatedByUser]
    ,[IsBlkdForSecondaryCostsPosting]
    ,[IsBlockedForRevenuePosting]
    ,[IsBlockedForCommitmentPosting]
    ,[IsBlockedForPlanSecondaryCosts]
    ,[IsBlockedForPlanRevenues]
    ,[CostCenterAllocationMethod]
    ,[ConsumptionQtyIsRecorded]
    ,[Department]
    ,[SubsequentCostCenter]
    ,[ConditionUsage]
    ,[ConditionApplication]
    ,[CostCenterAccountingOverhead]
    ,[Country]
    ,[FormOfAddress]
    ,[AddressName]
    ,[AddressAdditionalName]
    ,[CostCenterAddrName3]
    ,[CostCenterAddrName4]
    ,[CityName]
    ,[District]
    ,[StreetAddressName]
    ,[POBox]
    ,[PostalCode]
    ,[POBoxPostalCode]
    ,[Region]
    ,CONVERT([char](1), [Language]) AS [Language]
    ,[TeleboxNumber]
    ,[PhoneNumber1]
    ,[PhoneNumber2]
    ,[FaxNumber]
    ,[TeletexNumber]
    ,[TelexNumber]
    ,[DataCommunicationPhoneNumber]
    ,[CostCenterPrinterDestination]
    ,[CostCenterStandardHierArea]
    ,[CostCollector]
    ,[CostCenterIsComplete]
    ,[IsStatisticalCostCenter]
    ,[ObjectInternalID]
    ,[CostCenterFunction]
    ,[CostCenterAlternativeFunction]
    ,[FunctionalArea]
    ,[ActyIndepFormulaPlanningTmpl]
    ,[ActyDepdntFormulaPlanningTmpl]
    ,[ActyIndependentAllocationTmpl]
    ,[ActyDependentAllocationTmpl]
    ,[ActlIndepStatisticalKeyFigures]
    ,[ActlDepStatisticalKeyFigures]
    ,[JointVenture]
    ,[JointVentureRecoveryCode]
    ,[JointVentureEquityType]
    ,[JointVentureObjectType]
    ,[JointVentureClass]
    ,[JointVentureSubClass]
    ,[BudgetCarryingCostCenter]
    ,[AvailabilityControlProfile]
    ,[AvailabilityControlIsActive]
    ,[Fund]
    ,[GrantID]
    ,[FundIsFixAssigned]
    ,[GrantIDIsFixAssigned]
    ,[FunctionalAreaIsFixAssigned]
	,@t_applicationId AS t_applicationId
	,@t_jobId AS t_jobId
	,@t_lastDtm AS t_lastDtm
	,@t_lastActionBy AS t_lastActionBy
	,@t_filePath AS t_filePath
	FROM [base_s4h_uat_caa].[I_CostCenter_staging]
END