CREATE VIEW [dm_procurement].[vw_dim_ProductPlant]
AS
SELECT
        PP.[Product]
    ,   PP.[Plant]
    ,   PP.[PurchasingGroup]
    ,   PP.[CountryOfOrigin]
    ,   PP.[RegionOfOrigin]
    ,   PP.[ProductionInvtryManagedLoc]
    ,   PP.[ProfileCode]
    ,   PP.[ProfileValidityStartDate]
    ,   PP.[AvailabilityCheckType]
    ,   PP.[FiscalYearVariant]
    ,   PP.[PeriodType]
    ,   PP.[ProfitCenter]
    ,   PP.[Commodity]
    ,   PP.[GoodsReceiptDuration]
    ,   PP.[MaintenanceStatusName]
    ,   PP.[IsMarkedForDeletion]
    ,   PP.[MRPType]
    ,   PP.[MRPResponsible]
    ,   PP.[ABCIndicator]
    ,   PP.[MinimumLotSizeQuantity]
    ,   PP.[MaximumLotSizeQuantity]
    ,   PP.[FixedLotSizeQuantity]
    ,   PP.[ConsumptionTaxCtrlCode]
    ,   PP.[IsCoProduct]
    ,   PP.[ProductIsConfigurable]
    ,   PP.[ConfigurableProduct]
    ,   PP.[StockDeterminationGroup]
    ,   PP.[StockInTransferQuantity]
    ,   PP.[StockInTransitQuantity]
    ,   PP.[HasPostToInspectionStock]
    ,   PP.[IsBatchManagementRequired]
    ,   PP.[SerialNumberProfile]
    ,   PP.[IsNegativeStockAllowed]
    ,   PP.[GoodsReceiptBlockedStockQty]
    ,   PP.[HasConsignmentCtrl]
    ,   PP.[FiscalYearCurrentPeriod]
    ,   PP.[FiscalMonthCurrentPeriod]
    ,   PP.[IsPurgAcrossPurgGroup]
    ,   PP.[IsInternalBatchManaged]
    ,   PP.[ProductCFOPCategory]
    ,   PP.[ProductIsExciseTaxRelevant]
    ,   PP.[UnderDelivToleranceLimit]
    ,   PP.[OverDelivToleranceLimit]
    ,   PP.[ProcurementType]
    ,   PP.[SpecialProcurementType]
    ,   PP.[ProductionSchedulingProfile]
    ,   PP.[ProductionSupervisor]
    ,   PP.[SafetyStockQuantity]
    ,   PP.[GoodsIssueUnit]
    ,   PP.[SourceOfSupplyCategory]
    ,   PP.[ConsumptionReferenceProduct]
    ,   PP.[ConsumptionReferencePlant]
    ,   PP.[ConsumptionRefUsageEndDate]
    ,   PP.[ConsumptionQtyMultiplier]
    ,   PP.[ProductUnitGroup]
    ,   PP.[DistrCntrDistributionProfile]
    ,   PP.[ConsignmentControl]
    ,   PP.[GoodIssueProcessingDays]
    ,   PP.[PlannedDeliveryDurationInDays]
    ,   PP.[IsActiveEntity]
    ,   PP.[ProductIsCriticalPrt]
    ,   PP.[ProductLogisticsHandlingGroup]
    ,   PP.[MaterialFreightGroup]
    ,   PP.[OriginalBatchReferenceMaterial]
    ,   PP.[OriglBatchManagementIsRequired]
    ,   PP.[ProductConfiguration]
    ,   NVM.[PLIFZ] AS [PlannedDeliveryTime]
    ,   PP.[t_applicationId]
    ,   PP.[t_extractionDtm]
FROM
    [edw].[vw_ProductPlant] PP
LEFT JOIN
    [base_s4h_cax].[NSDM_V_MARC] NVM
    ON PP.Plant = NVM.WERKS