CREATE VIEW [dm_procurement].[vw_dim_ProductPlant]
AS
SELECT
        [Product]
    ,   [Plant]
    ,   [PurchasingGroup]
    ,   [CountryOfOrigin]
    ,   [RegionOfOrigin]
    ,   [ProductionInvtryManagedLoc]
    ,   [ProfileCode]
    ,   [ProfileValidityStartDate]
    ,   [AvailabilityCheckType]
    ,   [FiscalYearVariant]
    ,   [PeriodType]
    ,   [ProfitCenter]
    ,   [Commodity]
    ,   [GoodsReceiptDuration]
    ,   [MaintenanceStatusName]
    ,   [IsMarkedForDeletion]
    ,   [MRPType]
    ,   [MRPResponsible]
    ,   [ABCIndicator]
    ,   [MinimumLotSizeQuantity]
    ,   [MaximumLotSizeQuantity]
    ,   [FixedLotSizeQuantity]
    ,   [ConsumptionTaxCtrlCode]
    ,   [IsCoProduct]
    ,   [ProductIsConfigurable]
    ,   [ConfigurableProduct]
    ,   [StockDeterminationGroup]
    ,   [StockInTransferQuantity]
    ,   [StockInTransitQuantity]
    ,   [HasPostToInspectionStock]
    ,   [IsBatchManagementRequired]
    ,   [SerialNumberProfile]
    ,   [IsNegativeStockAllowed]
    ,   [GoodsReceiptBlockedStockQty]
    ,   [HasConsignmentCtrl]
    ,   [FiscalYearCurrentPeriod]
    ,   [FiscalMonthCurrentPeriod]
    ,   [IsPurgAcrossPurgGroup]
    ,   [IsInternalBatchManaged]
    ,   [ProductCFOPCategory]
    ,   [ProductIsExciseTaxRelevant]
    ,   [UnderDelivToleranceLimit]
    ,   [OverDelivToleranceLimit]
    ,   [ProcurementType]
    ,   [SpecialProcurementType]
    ,   [ProductionSchedulingProfile]
    ,   [ProductionSupervisor]
    ,   [SafetyStockQuantity]
    ,   [GoodsIssueUnit]
    ,   [SourceOfSupplyCategory]
    ,   [ConsumptionReferenceProduct]
    ,   [ConsumptionReferencePlant]
    ,   [ConsumptionRefUsageEndDate]
    ,   [ConsumptionQtyMultiplier]
    ,   [ProductUnitGroup]
    ,   [DistrCntrDistributionProfile]
    ,   [ConsignmentControl]
    ,   [GoodIssueProcessingDays]
    ,   [PlannedDeliveryDurationInDays]
    ,   [IsActiveEntity]
    ,   [ProductIsCriticalPrt]
    ,   [ProductLogisticsHandlingGroup]
    ,   [MaterialFreightGroup]
    ,   [OriginalBatchReferenceMaterial]
    ,   [OriglBatchManagementIsRequired]
    ,   [ProductConfiguration]
    ,   NVM.[PLIFZ] AS [PlannedDeliveryTime]
    ,   [t_applicationId]
    ,   [t_extractionDtm]
FROM
    [edw].[vw_ProductPlant] PP
LEFT JOIN
    [base_s4h_cax].[NSDM_V_MARC] NVM
    ON PP.Plant = NVM.WERKS