CREATE TABLE [edw].[dim_VariantConfigurator]
(
    [SalesDocument]                 NVARCHAR(20) NOT NULL,
    [SalesDocumentItem]             NVARCHAR(24) collate Latin1_General_100_BIN2 NOT NULL,
    [ProductID]                     NVARCHAR(40),
    [ProductExternalID]             NVARCHAR(40),
    [SO_ITEM_PROD_HIERARCHY]        NVARCHAR(30),
    [SO_ITEM_PROD_HIERARCHY1]       NVARCHAR(30),
    [HM_LENGTH]                     NVARCHAR(30),
    [HM_MATERIAL]                   NVARCHAR(30),
    [HM_PROFILE]                    NVARCHAR(30),
    [HTA_ANCHOR]                    NVARCHAR(30),
    [HTA_FILLER]                    NVARCHAR(30),
    [HTA_LENGTH]                    NVARCHAR(30),
    [HTA_MATERIAL]                  NVARCHAR(30),
    [HTA_PROFILE]                   NVARCHAR(30),
    [HZA_ANCHOR]                    NVARCHAR(30),
    [HZA_PROFILE]                   NVARCHAR(30),
    [HZA_PS_ANCHOR]                 NVARCHAR(30),
    [HZA_PS_MATERIAL]               NVARCHAR(30),
    [HZA_PS_PROFILE]                NVARCHAR(30),
    [HDB_DIAM]                      NVARCHAR(30),
    [HDB_HEIGHT]                    NVARCHAR(30),
    [HDB_LENGTH]                    NVARCHAR(30),
    [HDB_STUD_TYPE]                 NVARCHAR(30),
    [HDB_STUDQTY]                   NVARCHAR(30),
    [HDB_TYPE]                      NVARCHAR(30),
    [HIT_CON_COV]                   NVARCHAR(30),
    [HIT_CSB_QTY]                   NVARCHAR(30),
    [HIT_HEIGHT]                    NVARCHAR(30),
    [HIT_MVX_ES]                    NVARCHAR(30),
    [HIT_TB_QTY]                    NVARCHAR(30),
    [HIT_TYPE]                      NVARCHAR(30),
    [HIT_WIDTH]                     NVARCHAR(30),
    [HDBZ_STUD_DIAM]                NVARCHAR(30),
    [HDBZ_STUD_LENGTH]              NVARCHAR(30),
    [HIT_QS_DIAM]                   NVARCHAR(30),
    [HIT_QS_QTY]                    NVARCHAR(30),
    [HIT_QS_TYPE]                   NVARCHAR(30),
    [HIT_VARRIANT]                  NVARCHAR(30),
    [HBS05_BAR_DESIGN]              NVARCHAR(30),
    [HDBZ_CC_BOTTOM]                NVARCHAR(30),
    [HDBZ_CC_TOP]                   NVARCHAR(30),
    [HDBZ_DIAM]                     NVARCHAR(30),
    [HDBZ_HEIGHT]                   NVARCHAR(30),
    [HIT_STUFFE]                    NVARCHAR(30),
    [t_applicationId]               VARCHAR(32),
    [t_extractionDtm]               DATETIME,
    [t_jobId]                       VARCHAR(36),
    [t_jobDtm]                      DATETIME,
    [t_lastActionCd]                varchar(1),
    [t_jobBy]                       VARCHAR(128),
    CONSTRAINT [PK_dim_VariantConfigurator] PRIMARY KEY NONCLUSTERED
        ([SalesDocument],
         [SalesDocumentItem])
        NOT ENFORCED
)
    WITH
        (
        DISTRIBUTION = REPLICATE, HEAP )
GO