CREATE TABLE [edw].[dim_PurchasingDocument]
(
    [PurchasingDocumentID]           nvarchar(10) NOT NULL,
    [PurchasingDocumentCategory]     nvarchar(1),
    [PurchasingDocumentType]         nvarchar(4),/* -- not actually need at this moment
    [PurchasingDocumentSubtype]      nvarchar(1),
    [CompanyCode]                    nvarchar(4),
    [PurchasingDocumentDeletionCode] nvarchar(1),
    [PurchasingDocumentIsAged]       nvarchar(1),
    [ItemNumberInterval]             char(5),
    [ItemNumberIntervalForSubItems]  char(5),
    [PurchasingDocumentOrigin]       nvarchar(1),
    [ReleaseIsNotCompleted]          nvarchar(1),
    [ReleaseCode]                    nvarchar(1),
    [PurchasingReleaseStrategy]      nvarchar(2),
    [PurgReleaseSequenceStatus]      nvarchar(8),
    [TaxReturnCountry]               nvarchar(3),
    [CreationDate]                   date,
    [LastChangeDateTime]             decimal(21, 7),
    [CreatedByUser]                  nvarchar(12),
    [Supplier]                       nvarchar(10),
    [SupplierRespSalesPersonName]    nvarchar(30),
    [SupplierPhoneNumber]            nvarchar(16),
    [SupplierAddressID]              nvarchar(10),
    [ManualSupplierAddressID]        nvarchar(10),
    [CorrespncExternalReference]     nvarchar(12),
    [CorrespncInternalReference]     nvarchar(12),
    [PurchasingOrganization]         nvarchar(4),
    [PurchasingGroup]                nvarchar(3),
    [DocumentCurrency]               nchar(5),
    [ExchangeRate]                   decimal(9, 5),
    [PurchasingDocumentOrderDate]    date,
    [SupplyingSupplier]              nvarchar(10),
    [SupplyingPlant]                 nvarchar(4),
    [InvoicingParty]                 nvarchar(10),
    [Customer]                       nvarchar(10),
    [PurchaseContract]               nvarchar(10),
    [Language]                       nchar(1),
    [PurgReasonForDocCancellation]   char(2),
    [PurchasingCompletenessStatus]   nvarchar(1),
    [IncotermsClassification]        nvarchar(3),
    [IncotermsTransferLocation]      nvarchar(28),
    [PaymentTerms]                   nvarchar(4),
    [CashDiscount1Days]              decimal(3),
    [CashDiscount2Days]              decimal(3),
    [NetPaymentDays]                 decimal(3),
    [CashDiscount1Percent]           decimal(5, 3),
    [CashDiscount2Percent]           decimal(5, 3),
    [PricingProcedure]               nvarchar(6),
    [TargetAmount]                   decimal(15, 2),
    [PurgDocumentDistributionType]   nvarchar(1),
    [PurchasingDocumentCondition]    nvarchar(10),
    [ValidityStartDate]              date,
    [ValidityEndDate]                date,
    [ScheduleAgreementHasReleaseDoc] nvarchar(1),
    [QuotationLatestSubmissionDate]  date,
    [BindingPeriodValidityEndDate]   date,
    [QuotationSubmissionDate]        date,
    [SupplierQuotationExternalID]    nvarchar(10),
    [RequestForQuotation]            nvarchar(10),
    [ExchangeRateIsFixed]            nvarchar(1),
    [IncotermsVersion]               nvarchar(4),
    [IncotermsLocation1]             nvarchar(70),
    [IncotermsLocation2]             nvarchar(70),
    [PurchasingProcessingStatus]     nvarchar(2),
    [PurgReleaseTimeTotalAmount]     decimal(15, 2),
    [DownPaymentType]                nvarchar(4),
    [DownPaymentPercentageOfTotAmt]  decimal(5, 2),
    [DownPaymentAmount]              decimal(11, 2),
    [DownPaymentDueDate]             date,
    [PurchasingDocumentName]         nvarchar(40),
    [QuotationEarliestSubmsnDate]    date,
    [LatestRegistrationDate]         date,
    [FollowOnDocumentCategory]       nvarchar(1),
    [FollowOnDocumentType]           nvarchar(4),
    [VATRegistration]                nvarchar(20),
    [VATRegistrationCountry]         nvarchar(3),
    [IsIntrastatReportingRelevant]   nvarchar(1),
    [IsIntrastatReportingExcluded]   nvarchar(1),
    [IsEndOfPurposeBlocked]          nvarchar(1),*/
    [t_applicationId]        VARCHAR(32),
    [t_jobId]                VARCHAR(36),
    [t_jobDtm]               DATETIME,
    [t_lastActionCd]         VARCHAR(1),
    [t_jobBy]                NVARCHAR(128),
    CONSTRAINT [PK_dim_PurchasingDocument] PRIMARY KEY NONCLUSTERED (PurchasingDocumentID, PurchasingDocumentCategory) NOT ENFORCED
)
WITH
    (DISTRIBUTION = REPLICATE, HEAP )
GO