CREATE TABLE [edw].[dim_Address](
  AddressID NVARCHAR(10) NOT NULL,
  Region NVARCHAR(3),
  CountryID NVARCHAR(3),
  CityName NVARCHAR(40),
  PostalCode NVARCHAR(10),
  StreetName NVARCHAR(60),
  HouseNumber NVARCHAR(10),
  FullAddress NVARCHAR(170),
  CONSTRAINT [PK_dim_Address] PRIMARY KEY NONCLUSTERED ([AddressID]) NOT ENFORCED
)
WITH (
  DISTRIBUTION = REPLICATE, HEAP
)
