CREATE TABLE [edw].[dim_CostCenter] (
-- Cost Center
  [ControllingArea] nvarchar(8) NOT NULL
, [CostCenterID] nvarchar(20) NOT NULL --renamed (ex CostCenter)
, [CostCenter] nvarchar(40) --renamed (ex CostCenterName) from [base_s4h_cax].[I_CostCenterText]
, [CostCenterDescription] nvarchar(80) --from [base_s4h_cax].[I_CostCenterText]
, [ValidityEndDate] date NOT NULL
, [ValidityStartDate] date
, [IsBlkdForPrimaryCostsPosting] nvarchar(2)
, [IsBlockedForPlanPrimaryCosts] nvarchar(2)
, [CompanyCode] nvarchar(8)
, [BusinessArea] nvarchar(8)
, [CostCenterCategory] nvarchar(2)
, [CostCtrResponsiblePersonName] nvarchar(40)
, [CostCtrResponsibleUser] nvarchar(24)
, [CostCenterCurrency] char(5) -- collate Latin1_General_100_BIN2
, [CostingSheet] nvarchar(12)
, [TaxJurisdiction] nvarchar(30)
, [ProfitCenter] nvarchar(20)
, [Plant] nvarchar(8)
, [LogicalSystem] nvarchar(20)
, [CostCenterCreationDate] date
, [CostCenterCreatedByUser] nvarchar(24)
, [IsBlkdForSecondaryCostsPosting] nvarchar(2)
, [IsBlockedForRevenuePosting] nvarchar(2)
, [IsBlockedForCommitmentPosting] nvarchar(2)
, [IsBlockedForPlanSecondaryCosts] nvarchar(2)
, [IsBlockedForPlanRevenues] nvarchar(2)
, [CostCenterAllocationMethod] nvarchar(4)
, [ConsumptionQtyIsRecorded] nvarchar(2)
, [Department] nvarchar(24)
, [SubsequentCostCenter] nvarchar(20)
, [ConditionUsage] nvarchar(2)
, [ConditionApplication] nvarchar(4)
, [CostCenterAccountingOverhead] nvarchar(12)
, [Country] nvarchar(6)
, [FormOfAddress] nvarchar(30)
, [AddressName] nvarchar(70)
, [AddressAdditionalName] nvarchar(70)
, [CostCenterAddrName3] nvarchar(70)
, [CostCenterAddrName4] nvarchar(70)
, [CityName] nvarchar(70)
, [District] nvarchar(70)
, [StreetAddressName] nvarchar(70)
, [POBox] nvarchar(20)
, [PostalCode] nvarchar(20)
, [POBoxPostalCode] nvarchar(20)
, [Region] nvarchar(6)
, [Language] char(1) -- collate Latin1_General_100_BIN2
, [TeleboxNumber] nvarchar(30)
, [PhoneNumber1] nvarchar(32)
, [PhoneNumber2] nvarchar(32)
, [FaxNumber] nvarchar(62)
, [TeletexNumber] nvarchar(60)
, [TelexNumber] nvarchar(60)
, [DataCommunicationPhoneNumber] nvarchar(28)
, [CostCenterPrinterDestination] nvarchar(8)
, [CostCenterStandardHierArea] nvarchar(24)
, [CostCollector] nvarchar(46)
, [CostCenterIsComplete] nvarchar(2)
, [IsStatisticalCostCenter] nvarchar(2)
, [ObjectInternalID] nvarchar(44)
, [CostCenterFunction] nvarchar(6)
, [CostCenterAlternativeFunction] nvarchar(6)
, [FunctionalArea] nvarchar(32)
, [ActyIndepFormulaPlanningTmpl] nvarchar(20)
, [ActyDepdntFormulaPlanningTmpl] nvarchar(20)
, [ActyIndependentAllocationTmpl] nvarchar(20)
, [ActyDependentAllocationTmpl] nvarchar(20)
, [ActlIndepStatisticalKeyFigures] nvarchar(20)
, [ActlDepStatisticalKeyFigures] nvarchar(20)
, [JointVenture] nvarchar(12)
, [JointVentureRecoveryCode] nvarchar(4)
, [JointVentureEquityType] nvarchar(6)
, [JointVentureObjectType] nvarchar(8)
, [JointVentureClass] nvarchar(6)
, [JointVentureSubClass] nvarchar(10)
, [BudgetCarryingCostCenter] nvarchar(20)
, [AvailabilityControlProfile] nvarchar(12)
, [AvailabilityControlIsActive] nvarchar(2)
, [Fund] nvarchar(20)
, [GrantID] nvarchar(40)
, [FundIsFixAssigned] nvarchar(2)
, [GrantIDIsFixAssigned] nvarchar(2)
, [FunctionalAreaIsFixAssigned] nvarchar(2)
, [t_applicationId]       VARCHAR (32)
, [t_jobId]               VARCHAR (36)
, [t_jobDtm]              DATETIME
, [t_lastActionCd]        VARCHAR(1)
, [t_jobBy]               NVARCHAR(128)
,    CONSTRAINT [PK_dim_CostCenter] PRIMARY KEY NONCLUSTERED ([ControllingArea],[CostCenterID],[ValidityEndDate]) NOT ENFORCED
)
WITH
(
    DISTRIBUTION = REPLICATE,
    HEAP
)
GO
