CREATE TABLE [edw].[fact_MaterialDocumentItem]
(
    [_hash]                           nvarchar(32) collate DATABASE_DEFAULT NOT NULL,
    [MaterialDocumentYear]            char(4) collate DATABASE_DEFAULT      NOT NULL,
    [MaterialDocument]                nvarchar(10) collate DATABASE_DEFAULT NOT NULL,
    [MaterialDocumentItem]            char(10) collate DATABASE_DEFAULT      NOT NULL,
    [MaterialID]                      nvarchar(40) collate DATABASE_DEFAULT,
    [PlantID]                         nvarchar(8) collate DATABASE_DEFAULT,
    [StorageLocationID]               nvarchar(10) collate DATABASE_DEFAULT,
    [StorageTypeID]                   nvarchar(3) collate DATABASE_DEFAULT,
    [StorageBin]                      nvarchar(10) collate DATABASE_DEFAULT,
    [Batch]                           nvarchar(10) collate DATABASE_DEFAULT,
    [ShelfLifeExpirationDate]         date,
    [ManufactureDate]                 date,
    [SupplierID]                      nvarchar(10) collate DATABASE_DEFAULT,
    [SalesOrder]                      nvarchar(14) collate DATABASE_DEFAULT,
    [SalesOrderItem]                  nvarchar(12) collate DATABASE_DEFAULT,
    [SalesOrderScheduleLine]          char(4) collate DATABASE_DEFAULT,
    [WBSElementInternalID]            char(8) collate DATABASE_DEFAULT,
    [CustomerID]                      nvarchar(10) collate DATABASE_DEFAULT,
    [InventorySpecialStockTypeID]     nvarchar(1) collate DATABASE_DEFAULT,
    [InventoryStockTypeID]            nvarchar(2) collate DATABASE_DEFAULT,
    [StockOwner]                      nvarchar(10) collate DATABASE_DEFAULT,
    [GoodsMovementTypeID]             nvarchar(3) collate DATABASE_DEFAULT,
    [DebitCreditCode]                 nvarchar(1) collate DATABASE_DEFAULT,
    [InventoryUsabilityCode]          nvarchar(1) collate DATABASE_DEFAULT,
    [QuantityInBaseUnit]              decimal(13, 3),
    [MaterialBaseUnitID]              nvarchar(3) collate DATABASE_DEFAULT,
    [QuantityInEntryUnit]             decimal(13, 3),
    [EntryUnitID]                     nvarchar(3) collate DATABASE_DEFAULT,
    [HDR_PostingDate]                 date,
    [DocumentDate]                    date,
    [TotalGoodsMvtAmtInCCCrcy]        decimal(13, 2),
    [CompanyCodeCurrency]             nchar(5) collate DATABASE_DEFAULT,
    [InventoryValuationTypeID]        nvarchar(10) collate DATABASE_DEFAULT,
    [ReservationIsFinallyIssued]      nvarchar(1) collate DATABASE_DEFAULT,
    [PurchaseOrder]                   nvarchar(14) collate DATABASE_DEFAULT,
    [PurchaseOrderItem]               nvarchar(12) collate DATABASE_DEFAULT,
    [ProjectNetwork]                  nvarchar(12) collate DATABASE_DEFAULT,
    [Order]                           nvarchar(14) collate DATABASE_DEFAULT,
    [OrderItem]                       nvarchar(12) collate DATABASE_DEFAULT,
    [SalesDocumentItemCategoryID]     nvarchar(8) collate DATABASE_DEFAULT,
    [SalesDocumentItemCategory]       nvarchar(120) collate DATABASE_DEFAULT,
    [Reservation]                     char(10) collate DATABASE_DEFAULT,
    [ReservationItem]                 char(4) collate DATABASE_DEFAULT,
    [DeliveryDocument]                char(10) collate DATABASE_DEFAULT,
    [DeliveryDocumentItem]            char(6) collate DATABASE_DEFAULT,
    [ReversedMaterialDocumentYear]    char(4) collate DATABASE_DEFAULT,
    [ReversedMaterialDocument]        nvarchar(10) collate DATABASE_DEFAULT,
    [ReversedMaterialDocumentItem]    char(4) collate DATABASE_DEFAULT,
    [RvslOfGoodsReceiptIsAllowed]     nvarchar(1) collate DATABASE_DEFAULT,
    [GoodsRecipientName]              nvarchar(12) collate DATABASE_DEFAULT,
    [UnloadingPointName]              nvarchar(25) collate DATABASE_DEFAULT,
    [CostCenterID]                    nvarchar(10) collate DATABASE_DEFAULT,
    [GLAccountID]                     nvarchar(10) collate DATABASE_DEFAULT,
    [ServicePerformer]                nvarchar(10) collate DATABASE_DEFAULT,
    [EmploymentInternalID]            char(8) collate DATABASE_DEFAULT,
    [AccountAssignmentCategory]       nvarchar(1) collate DATABASE_DEFAULT,
    [WorkItem]                        nvarchar(10) collate DATABASE_DEFAULT,
    [ServicesRenderedDate]            date,
    [IssgOrRcvgMaterial]              nvarchar(40) collate DATABASE_DEFAULT,
    [CompanyCodeID]                   nvarchar(4) collate DATABASE_DEFAULT,
    [GoodsMovementRefDocTypeID]       nvarchar(1) collate DATABASE_DEFAULT,
    [IsAutomaticallyCreated]          nvarchar(1) collate DATABASE_DEFAULT,
    [IsCompletelyDelivered]           nvarchar(50) collate DATABASE_DEFAULT,
    [IssuingOrReceivingPlantID]       nvarchar(4) collate DATABASE_DEFAULT,
    [IssuingOrReceivingStorageLocID]  nvarchar(4) collate DATABASE_DEFAULT,
    [BusinessAreaID]                  nvarchar(4) collate DATABASE_DEFAULT,
    [ControllingAreaID]               nvarchar(4) collate DATABASE_DEFAULT,
    [FiscalYearPeriod]                char(7) collate DATABASE_DEFAULT,
    [FiscalYearVariant]               char(2) collate DATABASE_DEFAULT,
    [IssgOrRcvgBatch]                 nvarchar(10) collate DATABASE_DEFAULT,
    [IssgOrRcvgSpclStockInd]          nvarchar(1) collate DATABASE_DEFAULT,
    [MaterialDocumentItemText]        nvarchar(50) collate DATABASE_DEFAULT,
    [CurrencyTypeID]                  CHAR(2),
    [HDR_AccountingDocumentTypeID]    nvarchar(2) collate DATABASE_DEFAULT,
    [HDR_InventoryTransactionTypeID]  nvarchar(2) collate DATABASE_DEFAULT,
    [HDR_CreatedByUser]               nvarchar(12) collate DATABASE_DEFAULT,
    [HDR_CreationDate]                date,
    [HDR_CreationTime]                time(0),
    [HDR_MaterialDocumentHeaderText]  nvarchar(25) collate DATABASE_DEFAULT,
    [HDR_ReferenceDocument]           nvarchar(16) collate DATABASE_DEFAULT,
    [HDR_BillOfLading]                nvarchar(16) collate DATABASE_DEFAULT,
    [MatlStkChangeQtyInBaseUnit]      decimal(31, 14),
    [ConsumptionQtyICPOInBaseUnit]    decimal(31, 14),
    [ConsumptionQtyOBDProInBaseUnit]  decimal(31, 14),
    [ConsumptionQtySOInBaseUnit]      decimal(31, 14),
    [MatlCnsmpnQtyInMatlBaseUnit]     decimal(31, 14),
    [GoodsReceiptQtyInOrderUnit]      decimal(13, 3),
    [GoodsMovementIsCancelled]        nvarchar(1) collate DATABASE_DEFAULT,
    [GoodsMovementCancellationType]   nvarchar(1) collate DATABASE_DEFAULT,
    [ConsumptionPosting]              nvarchar(1) collate DATABASE_DEFAULT,
    [ManufacturingOrder]              nvarchar(14) collate DATABASE_DEFAULT,
    [ManufacturingOrderItem]          nvarchar(12) collate DATABASE_DEFAULT,
    [IsReversalMovementType]          nvarchar(1) collate DATABASE_DEFAULT,
    [t_applicationId]                 VARCHAR(32),
    [t_extractionDtm]                 DATETIME,
    [nk_dim_ProductValuationPUP]      nvarchar(54) collate DATABASE_DEFAULT,
    [StockPricePerUnit]               decimal(38,6),
    [StockPricePerUnit_EUR]           decimal(38,6),
    [StockPricePerUnit_USD]           decimal(38,6),
    [SalesDocumentTypeID]             nvarchar(4) collate DATABASE_DEFAULT,
    [SalesDocumentType]               nvarchar(20) collate DATABASE_DEFAULT,
    [PurchaseOrderTypeID]             nvarchar(4) collate DATABASE_DEFAULT,
    [PurchaseOrderType]               nvarchar(20) collate DATABASE_DEFAULT,
    [t_jobId]                         VARCHAR(36),
    [t_jobDtm]                        DATETIME,
    [t_lastActionCd]                  varchar(1),
    [t_jobBy]                         VARCHAR(128),
    CONSTRAINT [PK_fact_MaterialDocumentItem] PRIMARY KEY NONCLUSTERED (
        [MaterialDocumentYear],
        [MaterialDocument],
        [MaterialDocumentItem]
    ) NOT ENFORCED
)
WITH ( DISTRIBUTION = HASH ([MaterialDocument]), CLUSTERED COLUMNSTORE INDEX )