CREATE TABLE [edw].[fact_SupplierInvoiceItemPurOrdRef]
(
    [SupplierInvoice]                           nvarchar(10) NOT NULL, -- collate Latin1_General_100_BIN2 NOT NULL,
    [FiscalYear]                                char(4) NOT NULL, -- collate Latin1_General_100_BIN2      NOT NULL,
    [SupplierInvoiceItem]                       char(6) NOT NULL, -- collate Latin1_General_100_BIN2      NOT NULL,
    [sk_fact_PurchasingDocumentItem]            bigint,
    [PurchaseOrder]                             nvarchar(10), -- collate Latin1_General_100_BIN2,
    [PurchaseOrderItem]                         char(5), -- collate Latin1_General_100_BIN2,
    [Plant]                                     nvarchar(4), -- collate Latin1_General_100_BIN2,
    [PurchasingDocumentItemShortText]           nvarchar(40), -- collate Latin1_General_100_BIN2,
    [SupplierInvoiceItemText]                   nvarchar(50), -- collate Latin1_General_100_BIN2,
    [PurchaseOrderItemMaterial]                 nvarchar(40), -- collate Latin1_General_100_BIN2,
    [PurchaseOrderQuantityUnit]                 nvarchar(3), -- collate Latin1_General_100_BIN2,
    [QuantityInPurchaseOrderUnit]               decimal(13, 3),
    [PurchaseOrderPriceUnit]                    nvarchar(3), -- collate Latin1_General_100_BIN2,
    [QtyInPurchaseOrderPriceUnit]               decimal(13, 3),
    [SuplrInvcDeliveryCostCndnType]             nvarchar(4), -- collate Latin1_General_100_BIN2,
    [SuplrInvcDeliveryCostCndnStep]             char(3), -- collate Latin1_General_100_BIN2,
    [SuplrInvcDeliveryCostCndnCount]            char(3), -- collate Latin1_General_100_BIN2,
    [DocumentCurrencyID]                        nchar(5), -- collate Latin1_General_100_BIN2,
    [SupplierInvoiceItemAmount]                 decimal(13, 2),
    [IsSubsequentDebitCredit]                   nvarchar(1), -- collate Latin1_General_100_BIN2,
    [TaxCode]                                   nvarchar(2), -- collate Latin1_General_100_BIN2,
    [TaxJurisdiction]                           nvarchar(15), -- collate Latin1_General_100_BIN2,
    [ReferenceDocument]                         nvarchar(10), -- collate Latin1_General_100_BIN2,
    [ReferenceDocumentFiscalYear]               char(4), -- collate Latin1_General_100_BIN2,
    [ReferenceDocumentItem]                     char(4), -- collate Latin1_General_100_BIN2,
    [DebitCreditCode]                           nvarchar(1), -- collate Latin1_General_100_BIN2,
    [FreightSupplier]                           nvarchar(10), -- collate Latin1_General_100_BIN2,
    [IsNotCashDiscountLiable]                   nvarchar(1), -- collate Latin1_General_100_BIN2,
    [SuplrInvcItemHasPriceVariance]             nvarchar(1), -- collate Latin1_General_100_BIN2,
    [SuplrInvcItemHasQtyVariance]               nvarchar(1), -- collate Latin1_General_100_BIN2,
    [SuplrInvcItemHasDateVariance]              nvarchar(1), -- collate Latin1_General_100_BIN2,
    [SuplrInvcItemHasOrdPrcQtyVarc]             nvarchar(1), -- collate Latin1_General_100_BIN2,
    [SuplrInvcItemHasOtherVariance]             nvarchar(1), -- collate Latin1_General_100_BIN2,
    [SuplrInvcItemHasAmountOutsdTol]            nvarchar(1), -- collate Latin1_General_100_BIN2,
    [SuplrInvcItmHasQualityVariance]            nvarchar(1), -- collate Latin1_General_100_BIN2,
    [IsOnlineSupplierInvoiceItem]               nvarchar(1), -- collate Latin1_General_100_BIN2,
    [t_applicationId]                           VARCHAR(32),    
    [t_jobId]                                   VARCHAR(36),
    [t_jobDtm]                                  DATETIME,
    [t_jobBy]                                   NVARCHAR(128),
    [t_extractionDtm]                           DATETIME,
    [t_lastActionCd]                            VARCHAR(1),
    [t_filePath]                                NVARCHAR(1024),
    CONSTRAINT [PK_fact_SupplierInvoiceItemPurOrdRef] PRIMARY KEY NONCLUSTERED ([SupplierInvoice], [FiscalYear], [SupplierInvoiceItem]) NOT ENFORCED
)
WITH ( DISTRIBUTION = HASH (SupplierInvoice), CLUSTERED COLUMNSTORE INDEX )
GO

