CREATE TABLE [edw].[fact_ManufacturingOrder]
(
    [ManufacturingOrder]            NVARCHAR(12)    NOT NULL,
    [ManufacturingOrderCategory]    CHAR(2),
    [ManufacturingOrderOperation]   NVARCHAR(4)     NOT NULL,
    [OpActualExecutionStartDate]    DATE,
    [OpActualExecutionStartTime]    TIME(0),
    [OpActualExecutionEndDate]      DATE,
    [OpActualExecutionEndTime]      TIME(0),
    [OrderIsDelivered]              NVARCHAR(1),
    [OrderIsPartiallyDelivered]     NVARCHAR(1),
    [SalesOrder]                    NVARCHAR(10),
    [SalesOrderItem]                NVARCHAR(6),
    [Material]                      NVARCHAR(40),
    [MfgOrderPlannedTotalQty]       DECIMAL(13,3),
    [MfgOrderPlannedScrapQty]       DECIMAL(13,3),
    [MfgOrderConfirmedYieldQty]     DECIMAL(13,3),
    [MfgOrderConfirmedScrapQty]     DECIMAL(13,3),
    [ActualDeliveredQuantity]       DECIMAL(13,3),
    [ProductConfiguration]          CHAR(18),
    [WorkCenterID]                  CHAR(8),
    [WorkCenter]                    NVARCHAR(8),
    [OrderIsClosed]                 NVARCHAR(1),
    [OrderIsMarkedForDeletion]      NVARCHAR(1),
    [OrderIsCreated]                NVARCHAR(1),
    [OrderIsReleased]               NVARCHAR(1),
    [OrderIsPrinted]                NVARCHAR(1),
    [OrderIsConfirmed]              NVARCHAR(1),
    [OrderIsPartiallyConfirmed]     NVARCHAR(1),
    [OrderIsLocked]                 NVARCHAR(1),
    [MfgOrderCreationDate]          DATE,
    [MfgOrderCreationTime]          TIME(0),
    [OpErlstSchedldExecStrtTme]     TIME(0),
    [OpErlstSchedldExecStrtDte]     DATE,
    [OpErlstSchedldExecEndDte]      DATE,
    [OpErlstSchedldExecEndTme]      TIME(0),
    [ProductionPlant]               NVARCHAR(4),
    [OperationUnit]                 NVARCHAR(3),
    [t_applicationId]               VARCHAR(32),
    [t_extractionDtm]               DATETIME,
    [t_jobId]                       VARCHAR(36),
    [t_jobDtm]                      DATETIME,
    [t_lastActionCd]                varchar(1),
    [t_jobBy]                       VARCHAR(128),
    CONSTRAINT [PK_fact_ManufacturingOrder] PRIMARY KEY NONCLUSTERED (
        [ManufacturingOrder],
        [ManufacturingOrderOperation]
    ) NOT ENFORCED
)
WITH ( DISTRIBUTION = HASH ([ManufacturingOrder]), CLUSTERED COLUMNSTORE INDEX )