
CREATE TABLE [edw].[fact_MaterialDocumentItem_axbi]
(
    [MaterialDocumentYear]                      CHAR(4) COLLATE Latin1_General_100_BIN2      NOT NULL,
    [MaterialDocument]                          NVARCHAR(10) COLLATE Latin1_General_100_BIN2 NOT NULL,
    [MaterialDocumentItem]                      BIGINT                                       NOT NULL,
    [MaterialID]                                NVARCHAR(40) COLLATE Latin1_General_100_BIN2,
    [PlantID]                                   NVARCHAR(5) COLLATE Latin1_General_100_BIN2,
    [StorageLocationID]                         NVARCHAR(10) COLLATE Latin1_General_100_BIN2,
    --[StorageTypeID]                             nvarchar(3) COLLATE Latin1_General_100_BIN2,
    --[StorageBin]                                nvarchar(10) COLLATE Latin1_General_100_BIN2,
    --[Batch]                                     nvarchar(10) COLLATE Latin1_General_100_BIN2,
    --[ShelfLifeExpirationDate]                   date,
    --[ManufactureDate]                           date,
    --[SupplierID]                                nvarchar(10) COLLATE Latin1_General_100_BIN2,
    [SalesOrder]                                NVARCHAR(13) COLLATE Latin1_General_100_BIN2,
    [SalesOrderItem]                            CHAR(12) COLLATE Latin1_General_100_BIN2,
    --[SalesOrderScheduleLine]                    char(4) COLLATE Latin1_General_100_BIN2,
    --[WBSElementInternalID]                      char(8) COLLATE Latin1_General_100_BIN2,
    --[CustomerID]                                nvarchar(10) COLLATE Latin1_General_100_BIN2,
    --[InventorySpecialStockTypeID]               nvarchar(1) COLLATE Latin1_General_100_BIN2,
    --[InventoryStockTypeID]                      nvarchar(2) COLLATE Latin1_General_100_BIN2,
    --[StockOwner]                                nvarchar(10) COLLATE Latin1_General_100_BIN2,
    [GoodsMovementTypeID]                       NVARCHAR(3) COLLATE Latin1_General_100_BIN2,
    [GoodsMovementTypeName]                     NVARCHAR(1999) COLLATE Latin1_General_100_BIN2,
    --[DebitCreditCode]                 nvarchar(1) COLLATE Latin1_General_100_BIN2,
    --[InventoryUsabilityCode]          nvarchar(1) COLLATE Latin1_General_100_BIN2,
    --[QuantityInBaseUnit]              decimal(13, 3),
    [MaterialBaseUnitID]                        NVARCHAR(4) COLLATE Latin1_General_100_BIN2,
    --[QuantityInEntryUnit]             decimal(13, 3),
    --[EntryUnitID]                     nvarchar(3) COLLATE Latin1_General_100_BIN2,
    [HDR_PostingDate]                           DATE,
    [DocumentDate]                              DATE,
    --[TotalGoodsMvtAmtInCCCrcy]                  decimal(13, 2),
    [CompanyCodeCurrency]                       NCHAR(5) COLLATE Latin1_General_100_BIN2,
    --[InventoryValuationTypeID]                  nvarchar(10) COLLATE Latin1_General_100_BIN2,
    --[ReservationIsFinallyIssued]                nvarchar(1) COLLATE Latin1_General_100_BIN2,
    [PurchaseOrder]                             NVARCHAR(12) COLLATE Latin1_General_100_BIN2,
    [PurchaseOrderItem]                         NVARCHAR(12) COLLATE Latin1_General_100_BIN2,
    --[ProjectNetwork]                            nvarchar(12) COLLATE Latin1_General_100_BIN2,
    [Order]                                     NVARCHAR(13) COLLATE Latin1_General_100_BIN2,
    [OrderItem]                                 NVARCHAR(12) COLLATE Latin1_General_100_BIN2,
    --[Reservation]                               char(10) COLLATE Latin1_General_100_BIN2,
    --[ReservationItem]                           char(4) COLLATE Latin1_General_100_BIN2,
    [DeliveryDocument]                          NVARCHAR(13) COLLATE Latin1_General_100_BIN2,
    [DeliveryDocumentItem]                      NVARCHAR(12) COLLATE Latin1_General_100_BIN2,
    --[ReversedMaterialDocumentYear]    char(4) COLLATE Latin1_General_100_BIN2,
    --[ReversedMaterialDocument]        nvarchar(10) COLLATE Latin1_General_100_BIN2,
    --[ReversedMaterialDocumentItem]    char(4) COLLATE Latin1_General_100_BIN2,
    --[RvslOfGoodsReceiptIsAllowed]     nvarchar(1) COLLATE Latin1_General_100_BIN2,
    --[GoodsRecipientName]              nvarchar(12) COLLATE Latin1_General_100_BIN2,
    --[UnloadingPointName]              nvarchar(25) COLLATE Latin1_General_100_BIN2,
    --[CostCenterID]                    nvarchar(10) COLLATE Latin1_General_100_BIN2,
    --[GLAccountID]                     nvarchar(10) COLLATE Latin1_General_100_BIN2,
    --[ServicePerformer]                nvarchar(10) COLLATE Latin1_General_100_BIN2,
    --[EmploymentInternalID]            char(8) COLLATE Latin1_General_100_BIN2,
    --[AccountAssignmentCategory]       nvarchar(1) COLLATE Latin1_General_100_BIN2,
    --[WorkItem]                        nvarchar(10) COLLATE Latin1_General_100_BIN2,
    --[ServicesRenderedDate]            date,
    --[IssgOrRcvgMaterial]              nvarchar(40) COLLATE Latin1_General_100_BIN2,
    --[CompanyCodeID]                   nvarchar(4) COLLATE Latin1_General_100_BIN2,
    --[GoodsMovementRefDocTypeID]       nvarchar(1) COLLATE Latin1_General_100_BIN2,
    --[IsAutomaticallyCreated]          nvarchar(1) COLLATE Latin1_General_100_BIN2,
    --[IsCompletelyDelivered]           nvarchar(50) COLLATE Latin1_General_100_BIN2,
    --[IssuingOrReceivingPlantID]       nvarchar(4) COLLATE Latin1_General_100_BIN2,
    --[IssuingOrReceivingStorageLocID]  nvarchar(4) COLLATE Latin1_General_100_BIN2,
    --[BusinessAreaID]                  nvarchar(4) COLLATE Latin1_General_100_BIN2,
    --[ControllingAreaID]               nvarchar(4) COLLATE Latin1_General_100_BIN2,
    --[FiscalYearPeriod]                char(7) COLLATE Latin1_General_100_BIN2,
    --[FiscalYearVariant]               char(2) COLLATE Latin1_General_100_BIN2,
    --[IssgOrRcvgBatch]                 nvarchar(10) COLLATE Latin1_General_100_BIN2,
    --[IssgOrRcvgSpclStockInd]          nvarchar(1) COLLATE Latin1_General_100_BIN2,
    --[MaterialDocumentItemText]        nvarchar(50) COLLATE Latin1_General_100_BIN2,
    [SalesDocumentItemCategoryID]               CHAR(1),
    [SalesDocumentItemCategory]                 NVARCHAR(120),
    [StandardPricePerUnit]                      DECIMAL(38, 16)         NULL,
    [StandardPricePerUnit_EUR]                  DECIMAL(38, 16)         NULL,
    [PriceControlIndicatorID]                   CHAR(1),
    [PriceControlIndicator]                     CHAR(13),
    [ConsumptionQtyICPOInStandardValue]         DECIMAL(31, 14),
    [ConsumptionQtyICPOInStandardValue_EUR]     DECIMAL(31, 14),
    [ConsumptionQtySOStandardValue]             DECIMAL(31, 14),
    [ConsumptionQtySOStandardValue_EUR]         DECIMAL(31, 14),
    [MatlStkChangeStandardValue]                DECIMAL(31, 14),
    [MatlStkChangeStandardValue_EUR]            DECIMAL(31, 14),
    [ConsumptionQtyProStandardValue]            DECIMAL(31, 14),
    [ConsumptionQtyProStandardValue_EUR]        DECIMAL(31, 14),
    [CurrencyTypeID]                            CHAR(2),
    --[HDR_AccountingDocumentTypeID]    nvarchar(2) COLLATE Latin1_General_100_BIN2,
    --[HDR_InventoryTransactionTypeID]  nvarchar(2) COLLATE Latin1_General_100_BIN2,
    --[HDR_CreatedByUser]               nvarchar(12) COLLATE Latin1_General_100_BIN2,
    --[HDR_CreationDate]                date,
    --[HDR_CreationTime]                time(0),
    --[HDR_MaterialDocumentHeaderText]  nvarchar(25) COLLATE Latin1_General_100_BIN2,
    --[HDR_ReferenceDocument]           nvarchar(16) COLLATE Latin1_General_100_BIN2,
    --[HDR_BillOfLading]                nvarchar(16) COLLATE Latin1_General_100_BIN2,
    [MatlStkChangeQtyInBaseUnit]                DECIMAL(31, 14),
    [ConsumptionQtyICPOInBaseUnit]              DECIMAL(31, 14),
    [ConsumptionQtyOBDProInBaseUnit]            DECIMAL(31, 14),
    [ConsumptionQtySOInBaseUnit]                DECIMAL(31, 14),
    [MatlCnsmpnQtyInMatlBaseUnit]               DECIMAL(31, 14),
    --[GoodsReceiptQtyInOrderUnit]      decimal(13, 3),
    --[GoodsMovementIsCancelled]        nvarchar(1) COLLATE Latin1_General_100_BIN2,
    --[GoodsMovementCancellationType]   nvarchar(1) COLLATE Latin1_General_100_BIN2,
    --[ConsumptionPosting]              nvarchar(1) COLLATE Latin1_General_100_BIN2,
    [ManufacturingOrder]                        CHAR(13) COLLATE Latin1_General_100_BIN2,
    [ManufacturingOrderItem]                    NVARCHAR(12) COLLATE Latin1_General_100_BIN2,
    --[IsReversalMovementType]                    nvarchar(1) COLLATE Latin1_General_100_BIN2,
    [t_applicationId]                           VARCHAR(32),
    [t_extractionDtm]                           DATETIME,
    [t_jobId]                                   VARCHAR(36),
    [t_jobDtm]                                  DATETIME,
    [t_lastActionCd]                            VARCHAR(1),
    [t_jobBy]                                   VARCHAR(128),
    CONSTRAINT [PK_fact_MaterialDocumentItem_axbi] PRIMARY KEY NONCLUSTERED (
        [MaterialDocumentYear],
        [MaterialDocument],
        [MaterialDocumentItem]
    )  NOT ENFORCED
)
    WITH (DISTRIBUTION = HASH ([MaterialDocument]), CLUSTERED COLUMNSTORE INDEX )