{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.754.0 (24.06)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"srv_MeasureTypes\",\"srv_Cogs_cost\",\"Calendar\",\"Product\",\"ProfitCenter\",\"CustomerSoldTo\",\"ACDOCA_EPMSalesView\",\"_Measures\",\"SalesOrganization\",\"Source\",\"DB\",\"SalesDistrict\",\"GLAccount\",\"RLS_GROUPS\",\"RLS_USERS\",\"ExQLReportingEntity\",\"exQL_Map\",\"CompanyCode\",\"RangeStart\",\"RangeEnd\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "__PBI_ServiceStoredInTmdl",
        "value": "reserved"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Source",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"ws-xxxx-sls-a-euw-001.sql.azuresynapse.net\" meta [IsParameterQuery=true, List={\"ws-xxxx-sls-p-euw-001.sql.azuresynapse.net\", \"ws-xxxx-sls-d-euw-001.sql.azuresynapse.net\", \"ws-xxxx-sls-a-euw-001.sql.azuresynapse.net\", \"ws-sleshchuk-d-euw-001.sql.azuresynapse.net\", \"ws-nkukhtenko-d-euw-001.sql.azuresynapse.net\"}, DefaultValue=\"ws-xxxx-sls-p-euw-001.sql.azuresynapse.net\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "51c1eca3-85e3-40a5-9886-bc7b2858932e"
      },
      {
        "name": "DB",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"syndw_xxxx_sls_a_euw_001\" meta [IsParameterQuery=true, List={\"syndw_xxxx_sls_p_euw_001\", \"syndw_xxxx_sls_d_euw_001\", \"syndw_xxxx_sls_a_euw_001\", \"syndw_sleshchuk_d_euw_001\", \"syndw_nkukhtenko_d_euw_001\"}, DefaultValue=\"syndw_xxxx_sls_p_euw_001\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "59565eac-ed26-41a4-b712-5d399b142541"
      },
      {
        "name": "RangeStart",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "DateTime"
          }
        ],
        "expression": "#datetime(2020, 3, 31, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=false]",
        "kind": "m",
        "lineageTag": "70dcad52-0d6d-4838-8bfd-809315f7999d"
      },
      {
        "name": "RangeEnd",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "DateTime"
          }
        ],
        "expression": "#datetime(2024, 6, 6, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=false]",
        "kind": "m",
        "lineageTag": "84c4084a-e952-4748-b180-64dbb1a39ea7"
      }
    ],
    "relationships": [
      {
        "name": "250c1e4d-afcf-49ab-ab17-a960cf5af5b6",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "SalesOrganizationID",
        "fromTable": "ACDOCA_EPMSalesView",
        "toColumn": "SalesOrganizationID",
        "toTable": "SalesOrganization"
      },
      {
        "name": "dcfafa3a-cb4b-4cd1-aaef-c7611eaf4071",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ProfitCenterID",
        "fromTable": "ACDOCA_EPMSalesView",
        "toColumn": "ProfitCenterID",
        "toTable": "ProfitCenter"
      },
      {
        "name": "004a4342-3665-49ad-bbff-801b057b8b69",
        "fromColumn": "SalesDistrictID",
        "fromTable": "ACDOCA_EPMSalesView",
        "toColumn": "SalesDistrictID",
        "toTable": "SalesDistrict"
      },
      {
        "name": "e59534fe-2b69-41f1-8743-19f6a26a6a83",
        "fromColumn": "PostingDate",
        "fromTable": "ACDOCA_EPMSalesView",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "447e5c85-f794-4e5b-9ac8-fbf058a3fae8",
        "fromColumn": "GLAccountID",
        "fromTable": "ACDOCA_EPMSalesView",
        "toColumn": "GLAccountID",
        "toTable": "GLAccount"
      },
      {
        "name": "7032ce89-7bd4-4bc6-bbbe-3c1ce0a0a94b",
        "fromColumn": "CustomerID",
        "fromTable": "ACDOCA_EPMSalesView",
        "toColumn": "CustomerID",
        "toTable": "CustomerSoldTo"
      },
      {
        "name": "a20c3188-5021-4ebf-8e01-2f313746a777",
        "fromColumn": "ShipToParty",
        "fromTable": "ACDOCA_EPMSalesView",
        "toColumn": "CustomerID",
        "toTable": "CustomerShippedTo"
      },
      {
        "name": "4108ec3a-b243-46f3-ad9f-eb854fc08894",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "GROUP",
        "fromTable": "RLS_USERS",
        "securityFilteringBehavior": "bothDirections",
        "toCardinality": "many",
        "toColumn": "GROUP",
        "toTable": "RLS_GROUPS"
      },
      {
        "name": "f7a0cc0a-615f-4c02-ac75-9a2f6274b886",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "CompanyCodeID",
        "fromTable": "ACDOCA_EPMSalesView",
        "toCardinality": "many",
        "toColumn": "СompanyCodeID",
        "toTable": "RLS_GROUPS"
      },
      {
        "name": "0e6905d6-0254-4524-9bf8-0a04d1d189ad",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ProductSurrogateKey",
        "fromTable": "ACDOCA_EPMSalesView",
        "securityFilteringBehavior": "bothDirections",
        "toColumn": "sk_dim_Product",
        "toTable": "Product"
      },
      {
        "name": "ebe5af17-ae49-4ac2-b555-e362ab7e4e50",
        "fromColumn": "nk_ExQLmap",
        "fromTable": "ACDOCA_EPMSalesView",
        "toColumn": "nk_ExQLmap",
        "toTable": "exQL_Map"
      },
      {
        "name": "f51756c3-af47-43ea-8bea-af79ee35cb4f",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "CompanyCodeID",
        "fromTable": "ACDOCA_EPMSalesView",
        "toColumn": "CompanyCodeID",
        "toTable": "CompanyCode"
      }
    ],
    "roles": [
      {
        "name": "RLS",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "59197cd22b8b496594338ae5264c4541"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "RLS_USERS",
            "filterExpression": "[USER]=userprincipalname()"
          }
        ]
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isKey": true,
            "lineageTag": "1d6951e1-d7db-487c-8c4c-a24d8aa7a0ca",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5fd7d45-5c4c-456b-b85c-10d6e36e8a40",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6dab0902-763b-4e00-a184-d643553a0094",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2487d343-e68b-486b-9219-cabcdbfd6979",
            "sourceColumn": "MonthNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69b64fa6-0674-49e6-95c9-6a6d642e0cad",
            "sortByColumn": "MonthNumber",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d15755fe-cf8a-4a30-bec0-7df73fb82723",
            "sourceColumn": "Week",
            "summarizeBy": "none"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ea9ae91-7991-4c01-b8df-2252aaee4257",
            "sourceColumn": "Day",
            "summarizeBy": "none"
          },
          {
            "name": "YearMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b8fea4a3-dbff-4a01-8654-eaabb7f5c1e3",
            "sourceColumn": "YearMonth",
            "summarizeBy": "none"
          },
          {
            "name": "YearQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e0faca08-398c-4132-b27d-46a8a379b5e2",
            "sourceColumn": "YearQuarter",
            "summarizeBy": "none"
          },
          {
            "name": "YearWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "43182401-34dc-4a32-9c3b-5474c04941d1",
            "sourceColumn": "YearWeek",
            "summarizeBy": "none"
          },
          {
            "name": "WeekDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "91e97c46-bbf2-4f49-93ab-5b8c24c49f9f",
            "sourceColumn": "WeekDay",
            "summarizeBy": "none"
          },
          {
            "name": "FirstDayOfWeekDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "c45add9d-1aca-421d-9046-9652e3288564",
            "sourceColumn": "FirstDayOfWeekDate",
            "summarizeBy": "none"
          },
          {
            "name": "FirstDayOfMonthDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "633af68f-d4ba-41de-a63d-b754ceeb5823",
            "sourceColumn": "FirstDayOfMonthDate",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarDayOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "948aca54-502d-4200-8563-43152ddfcf79",
            "sourceColumn": "CalendarDayOfYear",
            "summarizeBy": "none"
          },
          {
            "name": "YearDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a709a60f-b6aa-488f-adc1-569639e7dfe5",
            "sourceColumn": "YearDay",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKNUM([Date],2)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3c96f291-8bff-44ed-95b8-cea82f5a99da",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "12 months before date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "if(and(datediff('Calendar'[Date],'Calendar'[Today],DAY)>=0,datediff('Calendar'[Date],'Calendar'[Today],MONTH)<=12),1,0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9f620441-1390-4e72-9804-ad4fb973b4ff",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Today",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "expression": "date(year(today()),month(TODAY()),day(TODAY()))",
            "formatString": "Long Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2e039e2f-b086-484d-adc3-567812417ba5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Calendar'[Month]&\" \"&'Calendar'[Year]",
            "isDataTypeInferred": true,
            "lineageTag": "0235550e-b372-40e1-b443-360b58f0e94a",
            "sortByColumn": "YearMonth",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "YTD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "if(and(datediff('Calendar'[Date],'Calendar'[Today],DAY)>=0,year('Calendar'[Date])=year('Calendar'[Today])),1,0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "817185dc-1afc-4f05-8e1f-73f396f315f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CurrentDay_Filter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF ( 'Calendar'[Date] <= TODAY (), 1,0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f72baa5a-9cc5-4378-9e3b-3711e7e9be90",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month_Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Calendar'[Date],\"MMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "77686f9c-9172-4624-8921-b5df4353d5ab",
            "sortByColumn": "MonthNumber_oder",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNumber_oder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH('Calendar'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "369fa8e2-28b0-4cb5-96c3-ab400a8c8e13",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Calendar'[Date],\"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cbe3e855-4d39-4785-8647-bf6fe2fee2c0",
            "sortByColumn": "MonthNumber_oder",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trend Filter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "var maxBillingDate = max(ACDOCA_EPMSalesView[PostingDate])",
              "return",
              "if('Calendar'[Date]<=maxBillingDate,1,0)"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "819a290f-032a-4d2c-8bfe-c93bb58afff7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Week calc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "expression": "if(and(month('Calendar'[Date])=1,'Calendar'[Week]=\"52\"),\"01\",'Calendar'[Week])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "de369351-a54c-4cf4-ac08-cde8e55e381f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Previous year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "[Year]-1",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ba093d8c-9038-4408-828a-9692c2c1db38",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "isHidden": true,
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "28c3e042-dae6-4061-862f-f1c7d24d2e25",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "829e45c7-d79e-47d3-a73d-815e7200c79e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "472a0a37-14fb-4214-9e75-e641398549c6",
                "ordinal": 2
              },
              {
                "name": "Week",
                "column": "Week",
                "lineageTag": "558b6a16-a91e-47de-96f8-18862f3815a4",
                "ordinal": 3
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "739f3be3-1d4d-4bfd-8cd2-ef4f2cf8e0f7",
                "ordinal": 4
              }
            ],
            "lineageTag": "19c6a929-ba19-4785-9380-7541acc0265e"
          }
        ],
        "lineageTag": "23b61ee0-dd79-4c21-8026-6836ae54321c",
        "partitions": [
          {
            "name": "Calendar-fe7c89e6-d300-4e27-8a22-dced5b696b42",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&Source&\"\", \"\"&DB&\"\"),",
                "    dm_sales_vw_dim_Calendar = Source{[Schema=\"dm_sales\",Item=\"vw_dim_Calendar\"]}[Data],",
                "    #\"Filtered Rows1\" = Table.SelectRows(dm_sales_vw_dim_Calendar, each [Date] >= #date(2019, 01, 01)),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Filtered Rows1\", each [Date] < #date(2026, 01, 01))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "298219e9-33ac-4db2-a93e-2379eed4a9da",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "ProductExternalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8c524d6b-2731-4d1b-bdec-35cc6c845358",
            "sourceColumn": "ProductExternalID",
            "summarizeBy": "none"
          },
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2885daab-58b0-461a-bbaa-353eb288269e",
            "sourceColumn": "Product",
            "summarizeBy": "none"
          },
          {
            "name": "MaterialTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad32a4e9-7f1e-43e6-96d8-0642d05bf523",
            "sourceColumn": "MaterialTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "MaterialType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e827f20f-db18-485a-a9bb-2cfa6a880c93",
            "sourceColumn": "MaterialType",
            "summarizeBy": "none"
          },
          {
            "name": "IsMarkedForDeletion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "14560036-4bf3-41a0-966f-9be269943c48",
            "sourceColumn": "IsMarkedForDeletion",
            "summarizeBy": "none"
          },
          {
            "name": "CrossPlantStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "bdee69ec-827a-41f9-8bc1-b368ffab5ceb",
            "sourceColumn": "CrossPlantStatus",
            "summarizeBy": "none"
          },
          {
            "name": "GrossWeight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "d07871c3-e841-4751-afe5-5611822a1fe8",
            "sourceColumn": "GrossWeight",
            "summarizeBy": "sum"
          },
          {
            "name": "SourceOfSupply",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "68b7cbf9-2a71-4c2c-9c8a-7e37847fdf44",
            "sourceColumn": "SourceOfSupply",
            "summarizeBy": "none"
          },
          {
            "name": "CountryOfOrigin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2c091d40-8450-466e-b08c-b343892ad593",
            "sourceColumn": "CountryOfOrigin",
            "summarizeBy": "none"
          },
          {
            "name": "CompetitorID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b882e7ed-8a0c-4696-a69c-79bc4b6fafa9",
            "sourceColumn": "CompetitorID",
            "summarizeBy": "none"
          },
          {
            "name": "MaterialGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fcd1c949-9de8-4fab-92a8-5aa0865e94d5",
            "sourceColumn": "MaterialGroup",
            "summarizeBy": "none"
          },
          {
            "name": "BaseUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65e92f43-69cd-4f3a-bb28-52b08fadfa8b",
            "sourceColumn": "BaseUnit",
            "summarizeBy": "none"
          },
          {
            "name": "ItemCategoryGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "14de9bd4-66dc-46fc-a62b-b8492ae0508a",
            "sourceColumn": "ItemCategoryGroup",
            "summarizeBy": "none"
          },
          {
            "name": "ProductHierarchy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e90b40cc-116d-43bf-82d0-a22575572386",
            "sourceColumn": "ProductHierarchy",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L1_PillarID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f6e73e2-8902-4bd5-9273-85dd7468ded0",
            "sourceColumn": "Product_L1_PillarID",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L2_GroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79fab102-e2dd-4379-abf1-28822b15aacd",
            "sourceColumn": "Product_L2_GroupID",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L3_TypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "113634a5-a6d9-4a48-9943-35d3651027aa",
            "sourceColumn": "Product_L3_TypeID",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L4_FamilyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a19d6d99-d44b-431c-898c-587b70bb3dca",
            "sourceColumn": "Product_L4_FamilyID",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L5_SubFamilyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21811f31-ff30-49a7-b601-d668a464d0a7",
            "sourceColumn": "Product_L5_SubFamilyID",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L1_Pillar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9943029-91b0-43a3-8d0a-0f1ded269c18",
            "sourceColumn": "Product_L1_Pillar",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L2_Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66d4f894-01c5-43e6-8d18-4094a0a58903",
            "sourceColumn": "Product_L2_Group",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L3_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc29d6b2-57e0-425a-91c5-729b4555bb9d",
            "sourceColumn": "Product_L3_Type",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L4_Family",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93f554a2-484b-4860-b029-fda085328910",
            "sourceColumn": "Product_L4_Family",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L5_SubFamily",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6ce246f-5fd0-47c9-aea5-b8f58a564c32",
            "sourceColumn": "Product_L5_SubFamily",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "692cd762-f418-436e-9b56-c742d1cfcd1a",
            "sourceColumn": "ProductCategory",
            "summarizeBy": "none"
          },
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "afd5f1f3-312f-4860-a919-1266c3c47f74",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          },
          {
            "name": "IndustryStandardName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0d61e29a-1343-450f-b506-edeb29a34dbc",
            "sourceColumn": "IndustryStandardName",
            "summarizeBy": "none"
          },
          {
            "name": "ProductStandardID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2928b792-47db-4a38-b420-f408c7ec40ce",
            "sourceColumn": "ProductStandardID",
            "summarizeBy": "none"
          },
          {
            "name": "InternationalArticleNumberCat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9d2de0ac-bdc0-4e52-b698-46ff7fc3d5f7",
            "sourceColumn": "InternationalArticleNumberCat",
            "summarizeBy": "none"
          },
          {
            "name": "ProductIsConfigurable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7051de17-b9d3-4c4a-acf4-b3dd6dd20a02",
            "sourceColumn": "ProductIsConfigurable",
            "summarizeBy": "none"
          },
          {
            "name": "IsBatchManagementRequired",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a75dd014-4e52-4f18-86e4-52a1592e0797",
            "sourceColumn": "IsBatchManagementRequired",
            "summarizeBy": "none"
          },
          {
            "name": "ExternalProductGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5dbaa89c-1bd9-4057-8da6-e8ec10bd6f7d",
            "sourceColumn": "ExternalProductGroup",
            "summarizeBy": "none"
          },
          {
            "name": "CrossPlantConfigurableProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "71f018ff-1c87-4fea-87ae-1af8b0f33a94",
            "sourceColumn": "CrossPlantConfigurableProduct",
            "summarizeBy": "none"
          },
          {
            "name": "ProductManufacturerNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "06c61837-dda3-45eb-beed-c498e30484d9",
            "sourceColumn": "ProductManufacturerNumber",
            "summarizeBy": "none"
          },
          {
            "name": "ManufacturerNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f30c2da1-cac8-45e5-b5ac-71c8a19711ee",
            "sourceColumn": "ManufacturerNumber",
            "summarizeBy": "none"
          },
          {
            "name": "MaximumPackagingLength",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "9ba6266f-a1a3-40e4-970f-a84af75a2d19",
            "sourceColumn": "MaximumPackagingLength",
            "summarizeBy": "sum"
          },
          {
            "name": "MaximumPackagingWidth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "5611c7e8-0a7b-4785-b05c-c48eaf8d887b",
            "sourceColumn": "MaximumPackagingWidth",
            "summarizeBy": "sum"
          },
          {
            "name": "MaximumPackagingHeight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "690cb278-5f08-43e4-bd77-48f110e4e251",
            "sourceColumn": "MaximumPackagingHeight",
            "summarizeBy": "sum"
          },
          {
            "name": "MaximumCapacity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "bac66443-f30f-447d-b4cb-3a16c1d46c5a",
            "sourceColumn": "MaximumCapacity",
            "summarizeBy": "sum"
          },
          {
            "name": "OvercapacityTolerance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "7b216ef4-238f-4259-bce9-a0b7992d808f",
            "sourceColumn": "OvercapacityTolerance",
            "summarizeBy": "sum"
          },
          {
            "name": "UnitForMaxPackagingDimensions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "596e6628-63e1-40dc-bd64-69fbdf3f601f",
            "sourceColumn": "UnitForMaxPackagingDimensions",
            "summarizeBy": "none"
          },
          {
            "name": "BaseUnitSpecificProductLength",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "bdee2a63-2a16-4e80-b62b-c54d20285e76",
            "sourceColumn": "BaseUnitSpecificProductLength",
            "summarizeBy": "sum"
          },
          {
            "name": "BaseUnitSpecificProductWidth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "ae327246-5bc7-452d-ad79-4c7a32506472",
            "sourceColumn": "BaseUnitSpecificProductWidth",
            "summarizeBy": "sum"
          },
          {
            "name": "BaseUnitSpecificProductHeight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "c65a8006-fa1e-4f22-912c-d3ff01ed2b50",
            "sourceColumn": "BaseUnitSpecificProductHeight",
            "summarizeBy": "sum"
          },
          {
            "name": "ArticleCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5c0b5dde-b57d-4abb-ac55-26baf622b0a3",
            "sourceColumn": "ArticleCategory",
            "summarizeBy": "none"
          },
          {
            "name": "ProductIsLocked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d3d827d-30ba-43d0-96de-d6907a40776c",
            "sourceColumn": "ProductIsLocked",
            "summarizeBy": "none"
          },
          {
            "name": "BasicMaterial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a6701520-f72e-49f8-a7cf-378383b651d8",
            "sourceColumn": "BasicMaterial",
            "summarizeBy": "none"
          },
          {
            "name": "SalesProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a4f45ff9-28c4-4ea3-ab8f-2ebcef8de3c0",
            "sourceColumn": "SalesProduct",
            "summarizeBy": "none"
          },
          {
            "name": "ZZ1_CustomFieldRiskMit_PRD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7b2db7c9-8853-402b-b8be-99785ac4abb7",
            "sourceColumn": "ZZ1_CustomFieldRiskMit_PRD",
            "summarizeBy": "none"
          },
          {
            "name": "ZZ1_CustomFieldHighRis_PRD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "93d165ba-b28d-4a16-ab3e-9b6f54f6d43b",
            "sourceColumn": "ZZ1_CustomFieldHighRis_PRD",
            "summarizeBy": "none"
          },
          {
            "name": "ZZ1_CustomFieldRiskRea_PRD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5b55d529-f115-4771-8e03-043973bf5fdb",
            "sourceColumn": "ZZ1_CustomFieldRiskRea_PRD",
            "summarizeBy": "none"
          },
          {
            "name": "t_jobDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "d8409230-5722-42c6-8632-84aaf9f02e9a",
            "sourceColumn": "t_jobDtm",
            "summarizeBy": "none"
          },
          {
            "name": "ID_Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Product'[ProductID]&\"_\"&'Product'[Product]",
            "isDataTypeInferred": true,
            "lineageTag": "97c317eb-b1d7-4766-82a5-304efeb35308",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ProductID_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b21cc5a-e8d3-4972-8775-6d7d5582104c",
            "sourceColumn": "ProductID_Name",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2841c934-cdba-4d33-9bea-9457f3c9266d",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "fc15a0e0-0feb-4273-a9c3-201ca43fbbcb",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "sk_dim_Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "14511f79-4387-497f-8b05-937d41b046e8",
            "sourceColumn": "sk_dim_Product",
            "summarizeBy": "none"
          },
          {
            "name": "CreationDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "afffbf53-b167-41ef-82ae-283db60fe55c",
            "sourceColumn": "CreationDate",
            "summarizeBy": "none"
          },
          {
            "name": "NetWeight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "d18288f1-8bc0-40f9-92c8-5ebcf9af99ef",
            "sourceColumn": "NetWeight",
            "summarizeBy": "sum"
          },
          {
            "name": "IndustrySector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "12fc1260-10ef-466d-8fd9-58384c619daa",
            "sourceColumn": "IndustrySector",
            "summarizeBy": "none"
          },
          {
            "name": "WeightUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "593d99b8-ae79-4c93-abfb-d83b1fede80b",
            "sourceColumn": "WeightUnit",
            "summarizeBy": "none"
          },
          {
            "name": "Division",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "19f2c133-cf64-4b8f-be20-e2827eff3bf9",
            "sourceColumn": "Division",
            "summarizeBy": "none"
          },
          {
            "name": "TransportationGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d24bf421-23a3-43a5-8254-90deef7d944d",
            "sourceColumn": "TransportationGroup",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedByUser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4de5f3fe-371f-4e98-84a7-a0d8147d7073",
            "sourceColumn": "CreatedByUser",
            "summarizeBy": "none"
          },
          {
            "name": "CrossPlantStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0347e958-3d1d-475d-a8c7-bb521f0e3ba7",
            "sourceColumn": "CrossPlantStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "ItemCategoryGroupName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3e0fb9a-3ffe-4f81-a18c-8c17235534ae",
            "sourceColumn": "ItemCategoryGroupName",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Product Hierarchy",
            "isHidden": true,
            "levels": [
              {
                "name": "Product_L1_Pillar",
                "column": "Product_L1_Pillar",
                "lineageTag": "30d14195-62fa-4861-b0d7-78d08db1d56d",
                "ordinal": 0
              },
              {
                "name": "Product_L2_Group",
                "column": "Product_L2_Group",
                "lineageTag": "dabaae36-0236-431f-a52e-392ba64cb2f2",
                "ordinal": 1
              },
              {
                "name": "Product_L3_Type",
                "column": "Product_L3_Type",
                "lineageTag": "e51514ef-205b-47db-bd7a-458efc06904c",
                "ordinal": 2
              },
              {
                "name": "Product_L4_Family",
                "column": "Product_L4_Family",
                "lineageTag": "652db67f-9016-43ae-9e4b-7b093e4a063d",
                "ordinal": 3
              },
              {
                "name": "Product_L5_SubFamily",
                "column": "Product_L5_SubFamily",
                "lineageTag": "2c368a67-fc45-4c45-89e6-8d14070768bb",
                "ordinal": 4
              }
            ],
            "lineageTag": "57c96a21-b91a-447a-8dd5-be3a1b1ef5d6"
          }
        ],
        "lineageTag": "ab9cc8b5-914a-4ebf-b5b6-43dcd9261cb5",
        "partitions": [
          {
            "name": "Product-99de6899-b1ad-4fd2-a1a6-8e6211673f07",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&Source&\"\", \"\"&DB&\"\"),",
                "    dm_sales_vw_dim_Product = Source{[Schema=\"dm_finance\",Item=\"vw_dim_Product\"]}[Data],",
                "    #\"Removed Duplicates\" = Table.Distinct(dm_sales_vw_dim_Product)",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ProfitCenter",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ControllingArea",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d614847e-1b02-4785-ab26-d2d9920ce9cb",
            "sourceColumn": "ControllingArea",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenterID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2c26839-44cd-4c91-ba3e-38d9f9fc56df",
            "sourceColumn": "ProfitCenterID",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58ffa6d8-d4ec-4354-b2ed-b5090c2cc9f0",
            "sourceColumn": "ProfitCenter",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCtrResponsiblePersonName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "849265bd-1bea-46dd-9644-3a352f6128c6",
            "sourceColumn": "ProfitCtrResponsiblePersonName",
            "summarizeBy": "none"
          },
          {
            "name": "Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9e3ab212-3956-4182-b1d9-5d01baa63189",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenterIsBlocked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1d6e8e54-5b32-416b-b57c-bae569845c92",
            "sourceColumn": "ProfitCenterIsBlocked",
            "summarizeBy": "none"
          },
          {
            "name": "CityName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a65f39c1-80e0-4c83-9312-29408ddf05b6",
            "sourceColumn": "CityName",
            "summarizeBy": "none"
          },
          {
            "name": "PostalCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1b00332b-e02d-457a-aba2-5d580184755b",
            "sourceColumn": "PostalCode",
            "summarizeBy": "none"
          },
          {
            "name": "District",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "446879de-f1d5-4435-bd0c-d15f6ad538f1",
            "sourceColumn": "District",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "663d8fdd-f3d6-431a-b21f-598844dbc99d",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "93944469-b3d4-4179-a214-7d394bd4c803",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenterTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51bff716-7986-476c-af87-1a29a515f135",
            "sourceColumn": "ProfitCenterTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenterType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d992d0d-7669-4309-b463-b7b9afa88efe",
            "sourceColumn": "ProfitCenterType",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter_ID_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(ProfitCenter[ProfitCenterID], \" \"), ProfitCenter[ProfitCenter])",
            "isDataTypeInferred": true,
            "lineageTag": "cdd3d5c8-5df1-465a-97a5-1c89e3cf0b9b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "57d986f3-00f9-45c2-802b-caadf024a2c9",
        "partitions": [
          {
            "name": "ProfitCenter-4ef61fee-14b7-481b-a877-933519aecd7e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&Source&\"\", \"\"&DB&\"\"),",
                "    dm_sales_vw_dim_ProfitCenter = Source{[Schema=\"dm_sales\",Item=\"vw_dim_ProfitCenter\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_ProfitCenter"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CustomerSoldTo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "045f7f43-aebb-417d-aa6e-b44fc63b0340",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8a6da98-b2ab-4550-a9c4-3cf0dcbc2076",
            "sourceColumn": "Customer",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerAccountGroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec196e17-4c49-4ed3-932d-25dc4f2be6da",
            "sourceColumn": "CustomerAccountGroupID",
            "summarizeBy": "none"
          },
          {
            "name": "AccountGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1897c8d-e215-4882-a57d-969c098a14f1",
            "sourceColumn": "AccountGroup",
            "summarizeBy": "none"
          },
          {
            "name": "AuthorizationGroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4e808b5c-45c4-440a-bfc9-a530b1ed1a38",
            "sourceColumn": "AuthorizationGroupID",
            "summarizeBy": "none"
          },
          {
            "name": "AuthorizationGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9a006162-b8c6-4cf8-ba93-e8a2b9d49fc4",
            "sourceColumn": "AuthorizationGroup",
            "summarizeBy": "none"
          },
          {
            "name": "DeliveryIsBlocked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8010be3e-d0f3-47ce-94b1-7b7802a7ae6e",
            "sourceColumn": "DeliveryIsBlocked",
            "summarizeBy": "none"
          },
          {
            "name": "PostingIsBlocked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "bfcc456b-d119-4a61-8065-c7c0a1c00756",
            "sourceColumn": "PostingIsBlocked",
            "summarizeBy": "none"
          },
          {
            "name": "BillingIsBlockedForCustomer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "247a546e-3c73-4d6f-8c86-c05bbda05283",
            "sourceColumn": "BillingIsBlockedForCustomer",
            "summarizeBy": "none"
          },
          {
            "name": "OrderIsBlockedForCustomer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ed630abc-3fdb-4af9-bf04-13651c0b9068",
            "sourceColumn": "OrderIsBlockedForCustomer",
            "summarizeBy": "none"
          },
          {
            "name": "IsOneTimeAccount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a627846f-d20b-4a69-b798-3c840db6b2f5",
            "sourceColumn": "IsOneTimeAccount",
            "summarizeBy": "none"
          },
          {
            "name": "CountryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97622d64-4d45-433e-b91f-bb71c4a382de",
            "sourceColumn": "CountryID",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d82ec788-b232-4b77-a152-c2830bfb24d5",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "CityName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85d3dffd-faf2-4b13-9b5d-9eb0e1162794",
            "sourceColumn": "CityName",
            "summarizeBy": "none"
          },
          {
            "name": "PostalCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af247699-37f9-4f1c-a126-2c2d62f83d00",
            "sourceColumn": "PostalCode",
            "summarizeBy": "none"
          },
          {
            "name": "StreetName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a75d128d-a1ed-40bd-8c2c-ee6c7ed02cc8",
            "sourceColumn": "StreetName",
            "summarizeBy": "none"
          },
          {
            "name": "RegionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4442be0-4707-4c06-a1b6-6259eb1aafbf",
            "sourceColumn": "RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed4b2175-ee98-421e-bb9d-3737d980d921",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "DeletionIndicator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9f70aee4-b5db-4d21-8b45-debc1c5735f8",
            "sourceColumn": "DeletionIndicator",
            "summarizeBy": "none"
          },
          {
            "name": "TradingPartnerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "927dbe57-0f0a-43ba-b828-695b2dff600b",
            "sourceColumn": "TradingPartnerID",
            "summarizeBy": "none"
          },
          {
            "name": "TradingPartner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "280f2c57-4070-43a6-aae2-a0830c21eaa4",
            "sourceColumn": "TradingPartner",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6e36e5b7-af10-4270-90cd-c05f9d8e623b",
            "sourceColumn": "BusinessType",
            "summarizeBy": "none"
          },
          {
            "name": "IndustryType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8efaf7e3-350d-47bd-8e1d-d361dbd5fba6",
            "sourceColumn": "IndustryType",
            "summarizeBy": "none"
          },
          {
            "name": "t_jobDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "4cd81ddc-d29a-427f-bcbd-4fb5e4d4eeeb",
            "sourceColumn": "t_jobDtm",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerID_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48c44231-6116-4f67-95b8-726368307445",
            "sourceColumn": "CustomerID_Name",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "17c057d9-f32a-4627-bcfb-2404f9329560",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "90630ae9-3d8b-45e2-81c7-2bc16d1f7328",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "49eb6ddc-ac38-4451-b0b8-124f07671950",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "bcc1f273-d056-4fd3-978e-f13504899fed",
        "partitions": [
          {
            "name": "CustomerSoldTo-dbb215be-a845-4777-9472-de6fe32412d4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&Source&\"\", \"\"&DB&\"\"),",
                "    dm_finance_vw_dim_Customer = Source{[Schema=\"dm_finance\",Item=\"vw_dim_Customer\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dm_finance_vw_dim_Customer,{{\"AuthorizationGroup\", type text}, {\"TradingPartner\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ACDOCA_EPMSalesView",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_IsMQueryFoldable",
            "value": "True"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "BillingDocumentTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "b754ad95-fb1d-4eaa-8a03-dcf18d2be183",
            "sourceColumn": "BillingDocumentTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "CreationDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "72b5603d-ff43-4819-a574-c5b02da297fa",
            "sourceColumn": "CreationDate",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganizationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f6414cc-ace1-45ce-831b-a80fecc3db42",
            "sourceColumn": "SalesOrganizationID",
            "summarizeBy": "none"
          },
          {
            "name": "DistributionChannelID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "b994b0c9-e56b-4d21-80b9-a5ed6ab4c6c2",
            "sourceColumn": "DistributionChannelID",
            "summarizeBy": "none"
          },
          {
            "name": "PlantID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "331a5758-7314-4008-970b-8a2229d2eb6d",
            "sourceColumn": "PlantID",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "71f74eff-d2b1-459f-b674-91eb757b4e44",
            "sourceColumn": "FiscalYear",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2244e24-c25f-419f-af6b-51fc794a54e5",
            "sourceColumn": "FiscalPeriod",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "006a6e13-433d-4056-8087-1510636f5dec",
            "sourceColumn": "CurrencyID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDocumentID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd7e3a5b-b50a-4c75-ba04-a4d5e847e907",
            "sourceColumn": "SalesDocumentID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDocumentItemID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed9aa33b-5501-43bb-8a47-5810be1f8ac3",
            "sourceColumn": "SalesDocumentItemID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDistrictID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "456d9a34-fae0-4c2e-9c54-b6dca4346208",
            "sourceColumn": "SalesDistrictID",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "88d9fb6d-dcd8-4c9f-9d82-96309e7fe62d",
            "sourceColumn": "CustomerGroup",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "c682f9a5-c79b-4c7f-9fbe-e19584a8b7c2",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "Application",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "if(CONTAINSSTRING(ACDOCA_EPMSalesView[t_applicationId],\"s4h\"),\"S4H\", if(CONTAINSSTRING(ACDOCA_EPMSalesView[t_applicationId], \"HALFEN\"),\"AXBI HALFEN\", \"AXBI NON-HALFEN\"))",
            "isDataTypeInferred": true,
            "lineageTag": "0ae2a171-514b-49d3-b8f5-bbc0b9558e9a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "029d322d-08a3-4745-926c-a029f396a9bf",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "InOutID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7581a0a-5578-4f81-93b9-d798b08db201",
            "sourceColumn": "InOutID",
            "summarizeBy": "none"
          },
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "ceacdfcd-c78e-4d67-99fd-d8ed858c0aa8",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          },
          {
            "name": "SourceLedgerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "283be4d9-8f2f-4ddd-8c6d-a1df27be5bfc",
            "sourceColumn": "SourceLedgerID",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyCodeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "0da4021d-c3bd-4178-8d70-bba199e64e90",
            "sourceColumn": "CompanyCodeID",
            "summarizeBy": "none"
          },
          {
            "name": "AccountingDocument",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "836abf10-06e6-4880-b602-0d48592a5581",
            "sourceColumn": "AccountingDocument",
            "summarizeBy": "none"
          },
          {
            "name": "LedgerGLLineItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c8231c7-9178-4f5a-8931-bf627428da5e",
            "sourceColumn": "LedgerGLLineItem",
            "summarizeBy": "none"
          },
          {
            "name": "LedgerFiscalYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "d4462145-3061-42a2-88df-550b298215da",
            "sourceColumn": "LedgerFiscalYear",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessTransactionTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "02af5bd3-e15e-4f46-9b7d-99fc1d9a9d48",
            "sourceColumn": "BusinessTransactionTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "ReferenceDocumentTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "28df8f95-df64-469b-bf00-fb648d4ad9cc",
            "sourceColumn": "ReferenceDocumentTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "ReferenceDocument",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb2e5cdd-0b56-400a-986d-4e30dcf3af51",
            "sourceColumn": "ReferenceDocument",
            "summarizeBy": "none"
          },
          {
            "name": "ReferenceDocumentItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ae52b21-a831-4228-831e-750b130869d6",
            "sourceColumn": "ReferenceDocumentItem",
            "summarizeBy": "none"
          },
          {
            "name": "IsReversal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "b49ed0b2-fd29-4a8b-9961-31d8fd3531aa",
            "sourceColumn": "IsReversal",
            "summarizeBy": "none"
          },
          {
            "name": "IsReversed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "a502817a-194d-4cd0-8d7f-895a9c32d255",
            "sourceColumn": "IsReversed",
            "summarizeBy": "none"
          },
          {
            "name": "ReversalReferenceDocument",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b197d7e-92d0-42c9-ac09-a29da77ad86b",
            "sourceColumn": "ReversalReferenceDocument",
            "summarizeBy": "none"
          },
          {
            "name": "GLAccountID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a008517-8819-4ccf-86b9-f5b370248e01",
            "sourceColumn": "GLAccountID",
            "summarizeBy": "none"
          },
          {
            "name": "CostCenterID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ff0934c-8607-4955-9096-065344900402",
            "sourceColumn": "CostCenterID",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenterID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "9959db0d-1a15-43b9-8c0c-1112c814200b",
            "sourceColumn": "ProfitCenterID",
            "summarizeBy": "none"
          },
          {
            "name": "FunctionalAreaID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "c011af4a-767b-4728-b7f2-ee42c0bebeb6",
            "sourceColumn": "FunctionalAreaID",
            "summarizeBy": "none"
          },
          {
            "name": "PartnerCompanyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "2be0fe24-5d66-4e5f-ae1c-1dbc4463de7e",
            "sourceColumn": "PartnerCompanyID",
            "summarizeBy": "none"
          },
          {
            "name": "BalanceTransactionCurrency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "2919cc70-d243-4559-910e-83303b1f1aca",
            "sourceColumn": "BalanceTransactionCurrency",
            "summarizeBy": "none"
          },
          {
            "name": "AmountInGlobalCurrency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "3d425aae-8d8b-46a8-8016-1c9ddb33da98",
            "sourceColumn": "AmountInGlobalCurrency",
            "summarizeBy": "sum"
          },
          {
            "name": "BaseUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c4a7743-3401-46f0-a65e-61e31343c344",
            "sourceColumn": "BaseUnit",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "e08b8d2d-8647-49ea-b25c-350dac3918b6",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "DebitCreditID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc0d69ab-7dcf-4f5e-a5a6-5472e3d7fdc6",
            "sourceColumn": "DebitCreditID",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYearPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b5debdb-9f46-4352-a3bc-9c0081d263dd",
            "sourceColumn": "FiscalYearPeriod",
            "summarizeBy": "none"
          },
          {
            "name": "PostingDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d0f51709-1651-4534-a09c-575313e44077",
            "sourceColumn": "PostingDate",
            "summarizeBy": "none"
          },
          {
            "name": "DocumentDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "accce0cb-3e0e-43d6-b809-5ab75520504d",
            "sourceColumn": "DocumentDate",
            "summarizeBy": "none"
          },
          {
            "name": "AccountingDocumentTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "c13517df-0ca0-4dde-b33a-2b415e5330e3",
            "sourceColumn": "AccountingDocumentTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "GLAccountTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "277cb6d3-d282-4504-9320-4a6a853da01a",
            "sourceColumn": "GLAccountTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "PurchasingDocument",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "401f06d8-a085-40b4-94aa-4735be8701ae",
            "sourceColumn": "PurchasingDocument",
            "summarizeBy": "none"
          },
          {
            "name": "PurchasingDocumentItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "753c0697-b6ee-4b3b-becf-c21ad0e43eba",
            "sourceColumn": "PurchasingDocumentItem",
            "summarizeBy": "none"
          },
          {
            "name": "DocumentItemText",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "0cf5fe16-694a-48a1-ab97-0167472c1919",
            "sourceColumn": "DocumentItemText",
            "summarizeBy": "none"
          },
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc53c6b8-b821-4984-8306-297ea86b5cfc",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "SupplierID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "23ad20f5-8506-407a-a350-0dbed42fd843",
            "sourceColumn": "SupplierID",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9fb9bc0-e19c-48d2-aa35-a7938e915e47",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "ExchangeRateDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d8b67efb-77ab-4e25-b282-d04b802e9a31",
            "sourceColumn": "ExchangeRateDate",
            "summarizeBy": "none"
          },
          {
            "name": "ClearingDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8940526e-762a-4275-aa96-7d4199330616",
            "sourceColumn": "ClearingDate",
            "summarizeBy": "none"
          },
          {
            "name": "PartnerCompanyCodeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "3203ce3b-c68c-450f-96d4-b13298a235e8",
            "sourceColumn": "PartnerCompanyCodeID",
            "summarizeBy": "none"
          },
          {
            "name": "BillToPartyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "b74f12b2-eed4-483d-a1ee-44798ad81877",
            "sourceColumn": "BillToPartyID",
            "summarizeBy": "none"
          },
          {
            "name": "ShipToParty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "309bd8dd-694c-4a52-b496-eb87acbd5592",
            "sourceColumn": "ShipToParty",
            "summarizeBy": "none"
          },
          {
            "name": "ManualAdjustment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e67059d6-d2dc-4f65-add7-ea5b8ec0e69b",
            "sourceColumn": "ManualAdjustment",
            "summarizeBy": "sum"
          },
          {
            "name": "TPAdjustment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5714f298-7844-4a5d-8ce8-e17209858ea3",
            "sourceColumn": "TPAdjustment",
            "summarizeBy": "sum"
          },
          {
            "name": "CurrencyTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "bcc9504e-02c9-4411-8bd1-8762f407d7a3",
            "sourceColumn": "CurrencyTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "120b8689-f58e-45d4-97ff-974175b3bce6",
            "sourceColumn": "SalesAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "CurrencyType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3c3db12-ec72-4fa6-be2d-b2f2212a1063",
            "sourceColumn": "CurrencyType",
            "summarizeBy": "none"
          },
          {
            "name": "BillingDocumentType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c22a767-b74b-4bbc-8bec-ece2c6960ac6",
            "sourceColumn": "BillingDocumentType",
            "summarizeBy": "none"
          },
          {
            "name": "BrandID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e6cc44c-b48e-48ac-9709-8394e45a0884",
            "sourceColumn": "BrandID",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerGroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "1fef3b35-9bd5-4e92-b672-476253cd2047",
            "sourceColumn": "CustomerGroupID",
            "summarizeBy": "none"
          },
          {
            "name": "COGSActCostAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "bb6e88ff-219c-4e62-991f-e36ef5db908f",
            "sourceColumn": "COGSActCostAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "COGSStdCostAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "b81d7067-cd06-470a-bcf7-b3021b3c2950",
            "sourceColumn": "COGSStdCostAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "OtherCoSAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "a68cc3c1-2d88-4554-a989-bcb3f5869707",
            "sourceColumn": "OtherCoSAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "AmountCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "020911d4-4478-4e19-9344-9e055bede1db",
            "sourceColumn": "AmountCategory",
            "summarizeBy": "none"
          },
          {
            "name": "Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "ec60906a-65fc-4411-8419-98e519a42bbe",
            "sourceColumn": "Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF(OR(ACDOCA_EPMSalesView[ProductID]=\"\",CONTAINSSTRING(ACDOCA_EPMSalesView[ProductID],\"MA\")=TRUE()), \"Empty\", \"Not Empty\")",
            "isDataTypeInferred": true,
            "lineageTag": "52da9ffd-43c9-4442-8d53-c48d7a793c11",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CustomerFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF(or(ACDOCA_EPMSalesView[CustomerID]=\"\",CONTAINSSTRING(ACDOCA_EPMSalesView[CustomerID],\"MA\")=TRUE()), \"Empty\", \"Not Empty\")",
            "isDataTypeInferred": true,
            "lineageTag": "553bf6d6-b92e-4de8-8e85-49a5cef15782",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Source",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "/*IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"BKPF\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\")",
              ",\"Finance\",",
              "IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"BKPFF\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\"),",
              "\"Finance\", ",
              "IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"CTE\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\"),",
              "\"Finance\",",
              "IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"IBKPF\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\"),",
              "\"Billing\",",
              " IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"IBKPF\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Not Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Not Empty\"),",
              "\"Billing\",",
              " IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"MKPF\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\"),",
              "\"Billing\",",
              " IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"MKPF\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Not Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\"),",
              "\"Billing\",",
              " IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"MKPF\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Not Empty\"),ACDOCA_SalesView[CustomerFlag]=\"NotEmpty\"),",
              "\"Billing\",",
              "IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"MKPF\",ACDOCA_SalesView[BillingDocumentType]<>\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Not Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Not Empty\"),",
              "\"Billing\",",
              " IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"PRCHG\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Not Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\"),",
              "\"Billing\",",
              "IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"RMRP\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\"),",
              "\"Billing\",",
              " IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"RMRP\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Not Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\"),",
              "\"Billing\",",
              "IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"RMRP\",ACDOCA_SalesView[BillingDocumentType]<>\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Not Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Not Empty\"),",
              "\"Billing\",",
              "IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"VBRK\",ACDOCA_SalesView[BillingDocumentType]<>\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Not Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Not Empty\"),",
              "\"Billing\",BLANK())))))))))))))) */",
              "",
              "IF(ACDOCA_EPMSalesView[ReferenceDocumentTypeID] =\"VBRK\", \"Billing\", \"Finance\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "3393c9db-c5e4-48c1-98ad-2064c7ea988b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "OpexAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "7a23a030-51c3-4c9a-bb6d-e151eed8b814",
            "sourceColumn": "OpexAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "GrossMarginAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "ac3483a4-3dcb-400c-8e6b-3f89a8b20350",
            "sourceColumn": "GrossMarginAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "Subsource",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(AND(ACDOCA_EPMSalesView[ReferenceDocumentTypeID]=\"VBRK\",LEFT(ACDOCA_EPMSalesView[GLAccountID],5)=\"00418\"),\"Rebates\",",
              "IF(ACDOCA_EPMSalesView[ReferenceDocumentTypeID]=\"VBRK\",\"Net invoiced sales\",\"Finance\"))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "28a1d62e-d05e-42ef-b33b-094492442997",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "SKReportingEntityKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7f1fc33-3c38-4063-a305-4dc73964daf3",
            "sourceColumn": "SKReportingEntityKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSurrogateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1c213a6-f784-4912-ad4a-1b6c4ea4ebd3",
            "sourceColumn": "ProductSurrogateKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOfficeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ce60d8e-6e23-4824-829a-7f3237429e39",
            "sourceColumn": "SalesOfficeID",
            "summarizeBy": "none"
          },
          {
            "name": "SubSourceShort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "LEFT(ACDOCA_EPMSalesView[Subsource], 3)",
            "isDataTypeInferred": true,
            "lineageTag": "1bcce34a-17aa-4c09-9381-c15cf3506e8f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "nk_ExQLmap",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bbc4752-3d8c-49a6-9b14-3e80793dc6b3",
            "sourceColumn": "nk_ExQLmap",
            "summarizeBy": "none"
          },
          {
            "name": "SoldProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "7159139b-e6b1-4df3-8755-b50b0eb28fa5",
            "sourceColumn": "SoldProduct",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5ac3a0d-8036-473f-b8c6-47f974a9f262",
            "sourceColumn": "CustomerCategory",
            "summarizeBy": "none"
          },
          {
            "name": "AccountingDocumentItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd5a243b-762b-4e6a-a2ee-857cc0690452",
            "sourceColumn": "AccountingDocumentItem",
            "summarizeBy": "none"
          },
          {
            "name": "AccountingDocCreatedByUserID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "10e26e18-2fac-4345-8507-39cfa57b4745",
            "sourceColumn": "AccountingDocCreatedByUserID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesReferenceDocumentCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b1ae86a-8137-44e9-a26b-0872d1c5fdfd",
            "sourceColumn": "SalesReferenceDocumentCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "SalesReferenceDocumentItemCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "dab37762-9f28-47d1-98d3-494f5fd2fbb8",
            "sourceColumn": "SalesReferenceDocumentItemCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDocumentItemCategoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "459afc84-bc85-4080-ba34-6c87afce7061",
            "sourceColumn": "SalesDocumentItemCategoryID",
            "summarizeBy": "none"
          },
          {
            "name": "HigherLevelItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "786d3b90-1d2d-4742-9a44-66953b9c0bd8",
            "sourceColumn": "HigherLevelItem",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ac84624d-69b6-416c-8ecd-f006e24cdd3f",
        "partitions": [
          {
            "name": "ACDOCA_EPMSalesView-6af331e5-a7a8-4878-8bef-907afd35d5ed",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&Source&\"\", \"\"&DB&\"\"),",
                "    dm_finance_vw_fact_ACDOCA_Full_CH_AT = Source{[Schema=\"dm_finance\",Item=\"vw_fact_ACDOCA_Full_CH_AT\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dm_finance_vw_fact_ACDOCA_Full_CH_AT,{{\"PostingDate\", type datetime}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{",
                "\"AccountAssignmentID\",",
                "\"AccountAssignmentNumber\",",
                "\"AccountAssignmentTypeID\",",
                "\"AccountingDocumentCategoryID\",",
                "\"AmountInFreeDefinedCurrency1\",",
                "\"AmountInFreeDefinedCurrency2\",",
                "\"AssignmentReference\",",
                "\"BillableControlID\",",
                "\"BusinessAreaID\",",
                "\"BusinessProcessID\",",
                "\"ChartOfAccountsID\",",
                "\"ClearingAccountingDocument\",",
                "\"ClearingDocFiscalYear\",",
                "\"ControllingAreaID\",",
                "\"ControllingBusTransacTypeID\",",
                "\"CostCtrActivityTypeID\",",
                "\"CostObjectID\",",
                "\"CreationDateTime\",",
                "\"FinancialAccountTypeID\",",
                "\"FinancialTransactionTypeID\",",
                "\"FiscalYearVariant\",",
                "\"FreeDefinedCurrency1\",",
                "\"FreeDefinedCurrency2\",",
                "\"GLRecordTypeID\",",
                "\"InvoiceItemReference\",",
                "\"InvoiceReference\",",
                "\"InvoiceReferenceFiscalYear\",",
                "\"IsCommitment\",",
                "\"IsSettled\",",
                "\"IsSettlement\",",
                "\"JrnlEntryItemObsoleteReasonID\",",
                "\"LastChangeDateTime\",",
                "\"LineItemIsCompleted\",",
                "\"OperatingConcernID\",",
                "\"OrderCategoryID\",",
                "\"OrderID\",",
                "\"OriginCostCenterID\",",
                "\"OriginObjectTypeID\",",
                "\"OriginProfitCenterID\",",
                "\"PartnerBusinessAreaID\",",
                "\"PartnerCostCenterID\",",
                "\"PartnerFunctionalAreaID\",",
                "\"PartnerProfitCenterID\",",
                "\"PartnerSegmentID\",",
                "\"PersonnelNumber\",",
                "\"PostingKeyID\",",
                "\"PredecessorReferenceDocItem\",",
                "\"PredecessorReferenceDocTypeID\",",
                "\"PredecessorReferenceDocument\",",
                "\"ProjectID\",",
                "\"ProjectInternalID\",",
                "\"ReferenceDocumentContextID\",",
                "\"ReferenceDocumentItemGroupID\",",
                "\"ReferencePurchaseOrderCategoryID\",",
                "\"ReversalReferenceDocumentCntxtID\",",
                "\"SegmentID\",",
                "\"ServiceDocument\",",
                "\"ServiceDocumentItem\",",
                "\"ServiceDocumentTypeID\",",
                "\"SourceReferenceDocument\",",
                "\"SourceReferenceDocumentItem\",",
                "\"SourceReferenceDocumentTypeID\",",
                "\"SpecialGLCodeID\",",
                "\"SubLedgerAcctLineItemTypeID\",",
                "\"TaxCodeID\",",
                "\"TransactionTypeDeterminationID\",",
                "\"WBSElementID\"",
                "}",
                "),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns\", each [PostingDate] > RangeStart and [PostingDate] <= RangeEnd)",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ],
        "refreshPolicy": {
          "incrementalGranularity": "month",
          "incrementalPeriods": 3,
          "policyType": "basic",
          "rollingWindowGranularity": "year",
          "rollingWindowPeriods": 5,
          "sourceExpression": [
            "let",
            "    Source = Sql.Database(\"\"&Source&\"\", \"\"&DB&\"\"),",
            "    dm_finance_vw_fact_ACDOCA_Full_CH_AT = Source{[Schema=\"dm_finance\",Item=\"vw_fact_ACDOCA_Full_CH_AT\"]}[Data],",
            "    #\"Changed Type\" = Table.TransformColumnTypes(dm_finance_vw_fact_ACDOCA_Full_CH_AT,{{\"PostingDate\", type datetime}}),",
            "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{",
            "\"AccountAssignmentID\",",
            "\"AccountAssignmentNumber\",",
            "\"AccountAssignmentTypeID\",",
            "\"AccountingDocumentCategoryID\",",
            "\"AmountInFreeDefinedCurrency1\",",
            "\"AmountInFreeDefinedCurrency2\",",
            "\"AssignmentReference\",",
            "\"BillableControlID\",",
            "\"BusinessAreaID\",",
            "\"BusinessProcessID\",",
            "\"ChartOfAccountsID\",",
            "\"ClearingAccountingDocument\",",
            "\"ClearingDocFiscalYear\",",
            "\"ControllingAreaID\",",
            "\"ControllingBusTransacTypeID\",",
            "\"CostCtrActivityTypeID\",",
            "\"CostObjectID\",",
            "\"CreationDateTime\",",
            "\"FinancialAccountTypeID\",",
            "\"FinancialTransactionTypeID\",",
            "\"FiscalYearVariant\",",
            "\"FreeDefinedCurrency1\",",
            "\"FreeDefinedCurrency2\",",
            "\"GLRecordTypeID\",",
            "\"InvoiceItemReference\",",
            "\"InvoiceReference\",",
            "\"InvoiceReferenceFiscalYear\",",
            "\"IsCommitment\",",
            "\"IsSettled\",",
            "\"IsSettlement\",",
            "\"JrnlEntryItemObsoleteReasonID\",",
            "\"LastChangeDateTime\",",
            "\"LineItemIsCompleted\",",
            "\"OperatingConcernID\",",
            "\"OrderCategoryID\",",
            "\"OrderID\",",
            "\"OriginCostCenterID\",",
            "\"OriginObjectTypeID\",",
            "\"OriginProfitCenterID\",",
            "\"PartnerBusinessAreaID\",",
            "\"PartnerCostCenterID\",",
            "\"PartnerFunctionalAreaID\",",
            "\"PartnerProfitCenterID\",",
            "\"PartnerSegmentID\",",
            "\"PersonnelNumber\",",
            "\"PostingKeyID\",",
            "\"PredecessorReferenceDocItem\",",
            "\"PredecessorReferenceDocTypeID\",",
            "\"PredecessorReferenceDocument\",",
            "\"ProjectID\",",
            "\"ProjectInternalID\",",
            "\"ReferenceDocumentContextID\",",
            "\"ReferenceDocumentItemGroupID\",",
            "\"ReferencePurchaseOrderCategoryID\",",
            "\"ReversalReferenceDocumentCntxtID\",",
            "\"SegmentID\",",
            "\"ServiceDocument\",",
            "\"ServiceDocumentItem\",",
            "\"ServiceDocumentTypeID\",",
            "\"SourceReferenceDocument\",",
            "\"SourceReferenceDocumentItem\",",
            "\"SourceReferenceDocumentTypeID\",",
            "\"SpecialGLCodeID\",",
            "\"SubLedgerAcctLineItemTypeID\",",
            "\"TaxCodeID\",",
            "\"TransactionTypeDeterminationID\",",
            "\"WBSElementID\"",
            "}",
            "),",
            "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Columns\", each [PostingDate] > RangeStart and [PostingDate] <= RangeEnd)",
            "in",
            "    #\"Filtered Rows\""
          ]
        }
      },
      {
        "name": "CustomerShippedTo",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1025cfec47534c579821f0558d5e91c4"
          }
        ],
        "columns": [
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ad587b5c-c9d3-4a0f-bbfe-4c42fdfece41",
            "sourceColumn": "CustomerSoldTo[CustomerID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "36d84fe7-b29b-4697-bb9a-912d85f391c8",
            "sourceColumn": "CustomerSoldTo[Customer]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CustomerAccountGroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a6084c95-efcf-4959-baf0-c82861f5f360",
            "sourceColumn": "CustomerSoldTo[CustomerAccountGroupID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "AccountGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5a074d90-4404-4764-b4ad-3deca6782334",
            "sourceColumn": "CustomerSoldTo[AccountGroup]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "AuthorizationGroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "764ac8f8-df2b-4311-a2e3-0e19abe3393f",
            "sourceColumn": "CustomerSoldTo[AuthorizationGroupID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "AuthorizationGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "def74cda-c133-45cb-8402-8dfa76c22783",
            "sourceColumn": "CustomerSoldTo[AuthorizationGroup]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DeliveryIsBlocked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5f60b79a-fb1c-4d58-a6e3-215a01d00307",
            "sourceColumn": "CustomerSoldTo[DeliveryIsBlocked]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "PostingIsBlocked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d87b16f9-3005-4d2f-a0a4-e6742c342030",
            "sourceColumn": "CustomerSoldTo[PostingIsBlocked]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "BillingIsBlockedForCustomer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "83610b17-4b0f-4a66-a10d-1bcc4625051b",
            "sourceColumn": "CustomerSoldTo[BillingIsBlockedForCustomer]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "OrderIsBlockedForCustomer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3bf2eacb-26f4-437b-9cf7-9b06ce032d9c",
            "sourceColumn": "CustomerSoldTo[OrderIsBlockedForCustomer]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsOneTimeAccount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "26a06dbf-8b97-4070-ab6e-8a3ff2152a05",
            "sourceColumn": "CustomerSoldTo[IsOneTimeAccount]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CountryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c0ddb0a9-b58f-4dff-92e5-e5fefd8b968a",
            "sourceColumn": "CustomerSoldTo[CountryID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3f97eb9c-376c-4edc-be1f-68e0d2194b0e",
            "sourceColumn": "CustomerSoldTo[Country]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CityName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "41e852cf-8a4b-474b-890c-cc088a863f8d",
            "sourceColumn": "CustomerSoldTo[CityName]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "PostalCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "82209653-2cbe-4ca3-a31f-9f13f916675c",
            "sourceColumn": "CustomerSoldTo[PostalCode]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "StreetName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1bd48420-4ca4-4f3b-b1d6-9a5f96afe4fd",
            "sourceColumn": "CustomerSoldTo[StreetName]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "RegionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f78b7845-144a-4225-b24d-0b3248be5e90",
            "sourceColumn": "CustomerSoldTo[RegionID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "84a41be8-51be-48be-a165-184739bf9401",
            "sourceColumn": "CustomerSoldTo[Region]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DeletionIndicator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1d9e41eb-542c-4882-afe5-3391a24635bb",
            "sourceColumn": "CustomerSoldTo[DeletionIndicator]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "TradingPartnerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "262684d9-0435-4bd7-96b9-c31251e83ab6",
            "sourceColumn": "CustomerSoldTo[TradingPartnerID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "TradingPartner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "dcfc0303-7a97-4385-a712-4063d01b8310",
            "sourceColumn": "CustomerSoldTo[TradingPartner]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "BusinessType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8b5aa8ce-5147-4086-be9d-d5196cf1133b",
            "sourceColumn": "CustomerSoldTo[BusinessType]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IndustryType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e851f61f-7a91-4eda-9911-cb4ba36d3f71",
            "sourceColumn": "CustomerSoldTo[IndustryType]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "t_jobDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9b518cd6-a10f-40ba-9b7e-56370dad2b8b",
            "sourceColumn": "CustomerSoldTo[t_jobDtm]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ID_Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CustomerShippedTo[CustomerID]&\"_\"&CustomerShippedTo[Customer]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c7f78420-2a69-4ca5-b14c-107856d374df",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CustomerID_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b24a73cd-4f8e-4d06-96a3-267f8068f25f",
            "sourceColumn": "CustomerSoldTo[CustomerID_Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e8f96ae7-2425-4f61-a232-1fed50a3a53b",
            "sourceColumn": "CustomerSoldTo[t_applicationId]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "92474125-4103-471e-af20-9dd132c3c85d",
            "sourceColumn": "CustomerSoldTo[t_extractionDtm]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6fde8414-f524-4c98-aa62-9595744ad601",
            "sourceColumn": "CustomerSoldTo[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "c8a0a16f-3a5f-43bd-ba5b-768c9096368d",
        "partitions": [
          {
            "name": "CustomerShippedTo-4263f765-3968-477e-a5f2-9405d599f149",
            "mode": "import",
            "source": {
              "expression": "CALCULATETABLE(CustomerSoldTo)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Measures",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Other measures",
            "isHidden": true,
            "lineageTag": "61223085-13c0-4932-a217-dc0ae519aa58",
            "sourceColumn": "Measures",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d0c28a7a-3fae-4b09-bc56-55fb48bbc05e",
        "measures": [
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales and Margins",
            "expression": "round(SUM(ACDOCA_EPMSalesView[SalesAmount]),1)",
            "lineageTag": "4f1c9c8d-b459-48d1-9b88-2171e6aaa716"
          },
          {
            "name": "Sales PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales and Margins",
            "expression": "round(CALCULATE([AmountInCompanyCodeCurrency], DATEADD('Calendar'[Date],-1,YEAR)),1)",
            "lineageTag": "5a00f47c-de7b-4334-9268-97eb89839ff1"
          },
          {
            "name": "DeltaNetAmount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Deltas",
            "expression": "IF([Sales PY]<>BLANK(), [Sales]-[Sales PY], BLANK())",
            "formatString": "#,0",
            "lineageTag": "626f5c0a-8301-4ceb-b4ce-fb46f5f8e209"
          },
          {
            "name": "DeltaNetAmount%",
            "displayFolder": "Deltas",
            "expression": "DIVIDE([DeltaNetAmount], [Sales PY], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a68f2def-9803-4968-b320-d2834d271326"
          },
          {
            "name": "DeltaMargin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Deltas",
            "expression": "IF([GrossMargin PY]<>0, [GrossMargin] - [GrossMargin PY], BLANK())",
            "formatString": "#,0",
            "lineageTag": "430ac9d6-5014-41db-b421-b634bc941d4c"
          },
          {
            "name": "KPI",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "KPI dynamic",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE(srv_MeasureTypes[Choose KPI]),",
              "    SWITCH(",
              "        VALUES(srv_MeasureTypes[Choose KPI]),",
              "        ---- Analysis",
              "        \"1_Net Invoice Sales\", [1_Net Invoice Sales],",
              "        \"1a_Rebate Accruals\", [1a_Rebate Accruals], ",
              "        \"2_Net Revenue\", [2_Net Revenue],",
              "        \"2a_Fin Accr & Rebates\", [2a_Fin Accr & Rebates],",
              "        \"3_Reported Revenue\", [3_Reported Revenue],",
              "        \"3a_COGS Standard\", [3a_COGS Standard],",
              "        \"3b_COGS Actual\", [3b_COGS Actual],",
              "        \"5_Standard Finance Margin\", [5_Standard Finance Margin],",
              "        \"6_Actual Finance Margin\", [6_Actual Finance Margin],",
              "        \"7_Gross Margin\", [7_Gross Margin],",
              "        \"7%_Gross Margin %\",  DIVIDE([7_Gross Margin], [3_Reported Revenue], 0) *100, ",
              "        --- Predefined ",
              "        \"Sales\", [Sales],",
              "        \"COGS\", IF(SELECTEDVALUE(srv_Cogs_cost[Choose KPI])=\"At actual cost\",[Cogs a/c],[Cogs]),",
              "        \"Sales Margin\", [SalesMargin],",
              "        \"Other CoS\", [OtherCOS],",
              "        \"Gross Profit\", [GrossProfit],",
              "        \"Opex\", [Opex],",
              "        \"Gross Margin\", [GrossMargin],",
              "        \"MC %\", [MC %] *100,",
              "        \"Sales Margin %\", DIVIDE([SalesMargin],[Sales],0)  *100,",
              "        \"Profit Margin %\", DIVIDE([GrossProfit],[Sales],0)  *100",
              "            ),",
              "    [Sales]",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "c341e0e2-a7a9-4035-bb18-59c09b040c04"
          },
          {
            "name": "KPI PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "KPI dynamic",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE(srv_MeasureTypes[Choose KPI]),",
              "    SWITCH(",
              "        VALUES(srv_MeasureTypes[Choose KPI]),",
              "                ---- Analysis",
              "        \"1_Net Invoice Sales\", [1_Net Invoice Sales PY],",
              "        \"1a_Rebate Accruals\", [1a_Rebate Accruals PY], ",
              "        \"2_Net Revenue\", [2_Net Revenue PY],",
              "        \"2a_Fin Accr & Rebates\", [2a_Fin Accr & Rebates PY],",
              "        \"3_Reported Revenue\", [3_Reported Revenue PY],",
              "        \"3a_COGS Standard\", [3a_COGS Standard PY],",
              "        \"3b_COGS Actual\", [3b_COGS Actual PY],",
              "        \"5_Standard Finance Margin\", [5_Standard Finance Margin PY],",
              "        \"6_Actual Finance Margin\", [6_Actual Finance Margin PY],",
              "        \"7_Gross Margin\", [7_Gross Margin PY],",
              "        \"7%_Gross Margin %\", [7_Grosss Margin % PY] *100 ,",
              "        --- Predefined ",
              "        \"Sales\", [Sales PY],",
              "        \"COGS\", IF(SELECTEDVALUE(srv_Cogs_cost[Choose KPI])=\"At actual cost\",[COGS a/c PY],[COGS PY]),",
              "        \"Sales Margin\", [SalesMargin PY],",
              "        \"Other CoS\", [OtherCOS PY],",
              "        \"Gross Profit\", [GrossProfit PY],",
              "        \"Opex\", [Opex PY],",
              "        \"Gross Margin\", [GrossMargin PY],",
              "        \"MC %\", [MC % PY] *100,",
              "        \"Sales Margin %\", DIVIDE([SalesMargin Py],[Sales PY],0) *100,",
              "        \"Profit Margin %\", DIVIDE([GrossProfit PY],[Sales PY],0) *100",
              "            ),",
              "    [Sales PY]",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "21262827-f781-4e4e-aa40-0448da832329"
          },
          {
            "name": "LastUpdated",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "displayFolder": "Notifications",
            "expression": "CALCULATE(MAX(ACDOCA_EPMSalesView[t_extractionDtm]), ALL(ACDOCA_EPMSalesView))",
            "formatString": "d mmmm\\, yyyy",
            "isHidden": true,
            "lineageTag": "b6e98520-281d-4c38-bc93-8aed7a9bc1a8"
          },
          {
            "name": "DeltaMargin%",
            "displayFolder": "Deltas",
            "expression": "DIVIDE([DeltaMargin], [GrossMargin PY], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "93937cc7-75ed-4211-9b2a-dfabf451df31"
          },
          {
            "name": "BillingDocsNumber",
            "displayFolder": "BillingDocs",
            "expression": "CALCULATE(DISTINCTCOUNT(ACDOCA_EPMSalesView[ReferenceDocument]), ACDOCA_EPMSalesView[ReferenceDocument] <> BLANK())",
            "formatString": "#,0",
            "lineageTag": "6f49d0a1-8c77-4dbb-9224-1a29d91b774f"
          },
          {
            "name": "BillingDocsNumber PY",
            "displayFolder": "BillingDocs",
            "expression": "CALCULATE([BillingDocsNumber], DATEADD('Calendar'[Date], -1, year))",
            "formatString": "#,0",
            "lineageTag": "919cae90-694a-4389-b6ca-d874b99e6bd8"
          },
          {
            "name": "DeltaBillingDocsNumber%",
            "displayFolder": "Deltas",
            "expression": "DIVIDE([BillingDocsNumber]-[BillingDocsNumber PY], [BillingDocsNumber PY])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "68fdffec-168c-4004-8296-6dbce6bace55"
          },
          {
            "name": "OrderAmount",
            "displayFolder": "Other measures",
            "expression": "DISTINCTCOUNT(ACDOCA_EPMSalesView[SalesDocumentID])",
            "formatString": "0",
            "lineageTag": "283b567d-d716-4d59-8770-b4efbf3de86a"
          },
          {
            "name": "OrderAmount PY",
            "displayFolder": "Other measures",
            "expression": "CALCULATE([OrderAmount], DATEADD('Calendar'[Date], -1, year))",
            "formatString": "0",
            "lineageTag": "2f43185c-1204-4316-9fe5-9b68fd5d67a8"
          },
          {
            "name": "DeltaOrdersAmount%",
            "displayFolder": "Deltas",
            "expression": "DIVIDE([OrderAmount]-[OrderAmount PY], [OrderAmount PY])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f0d8cf1a-a048-4147-8e7e-dbf786ba62f3"
          },
          {
            "name": "Sales&MarginsK",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales and Margins",
            "expression": "DIVIDE([KPI],1000)",
            "isHidden": true,
            "lineageTag": "baf7d5ac-44e8-4046-8714-f3dc7b17ba09"
          },
          {
            "name": "DeltaSales&Margins%",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Deltas",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE(srv_MeasureTypes[Choose KPI]),",
              "    SWITCH(",
              "        VALUES(srv_MeasureTypes[Choose KPI]),",
              "        \"Sales\", [DeltaNetAmount%]",
              "    ),",
              "    [DeltaNetAmount%]",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "ac52aa54-5ad6-4ee1-bf41-6c94c52c5084"
          },
          {
            "name": "DeltaSales&MarginsNegative",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Deltas",
            "expression": "IF([DeltaSales&Margins%]<0, [DeltaSales&Margins%]*100)",
            "isHidden": true,
            "lineageTag": "c3912969-99dc-43ae-8f0b-4cbd6ccaeec0"
          },
          {
            "name": "DeltaSales&MarginsPositive",
            "displayFolder": "Deltas",
            "expression": "IF([DeltaSales&Margins%]>0, format([DeltaSales&Margins%]*100,\"+##.#\"))",
            "isHidden": true,
            "lineageTag": "e8af633f-23ba-42a0-a76b-a0f5398388c7"
          },
          {
            "name": "Sales&MarginsRank",
            "displayFolder": "Sales and Margins",
            "expression": "IF(ISBLANK([KPI]), BLANK(), RANKX(ALLSELECTED('Product'[Product_L3_Type]), CALCULATE([KPI])))",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cb5b0419-77d8-4f47-8b5e-944d2d5c1102"
          },
          {
            "name": "Sales&MarginsRank PY",
            "displayFolder": "Sales and Margins",
            "expression": "IF( ISBLANK([KPI]), BLANK(), RANKX(ALLSELECTED('Product'[Product_L3_Type]), CALCULATE([KPI PY])) )",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2bb608d9-5bd5-4a11-a7bd-b7f3ef892923"
          },
          {
            "name": "DeltaKPIRank",
            "displayFolder": "Deltas",
            "expression": "[Sales&MarginsRank PY]-[Sales&MarginsRank]",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5e386b4c-2d14-489e-b200-d0068254d9c0"
          },
          {
            "name": "DeltaSales&MarginsRankSign",
            "displayFolder": "Deltas",
            "expression": "IF( [DeltaKPIRank]<>0, IF([DeltaKPIRank]>0, \"+\"&[DeltaKPIRank], [DeltaKPIRank]) )",
            "isHidden": true,
            "lineageTag": "b9533f8b-c71f-4fad-852e-644c3baba3d7"
          },
          {
            "name": "CustomerAmount",
            "displayFolder": "Other measures",
            "expression": "DISTINCTCOUNT(ACDOCA_EPMSalesView[CustomerID])",
            "formatString": "0",
            "lineageTag": "d15449f3-25ba-4877-a487-6f037aa014a9"
          },
          {
            "name": "CustomerAmount PY",
            "displayFolder": "Other measures",
            "expression": "CALCULATE([CustomerAmount], DATEADD('Calendar'[Date], -1, year))",
            "formatString": "0",
            "lineageTag": "c65565f2-2149-4c2e-939d-b92f1fca4c69"
          },
          {
            "name": "DeltaCustomerAmount%",
            "displayFolder": "Deltas",
            "expression": "DIVIDE([CustomerAmount]-[CustomerAmount PY], [CustomerAmount PY])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "79d49806-7661-4861-8e65-ce0a744c47c0"
          },
          {
            "name": "MsgCurrentCurrency",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "var CurrencyCount = CALCULATE(DISTINCTCOUNT(ACDOCA_EPMSalesView[CurrencyID]))",
              "return",
              "IF(CurrencyCount<1,\"\",if(CurrencyCount=1, \"Values currency: \"&MAX(ACDOCA_EPMSalesView[CurrencyID]), \"Error: There are different currencies in the dataset\"))"
            ],
            "isHidden": true,
            "lineageTag": "59f0802e-f7f5-4401-b112-609150536274"
          },
          {
            "name": "CurrentCurrency_Int",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "if([MsgCurrentCurrency]=\"Error: There are different currencies in the dataset\", 0, 1)"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5ce025bf-aa93-4a24-9534-cf35a5a76a64"
          },
          {
            "name": "Slicer_filter",
            "displayFolder": "Other measures",
            "expression": "COUNTROWS(ACDOCA_EPMSalesView)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c33bc8a4-750e-4ffa-bac5-c43667731cf7"
          },
          {
            "name": "KPI Delta",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "KPI dynamic",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE(srv_MeasureTypes[Choose KPI]),",
              "    SWITCH(",
              "        VALUES(srv_MeasureTypes[Choose KPI]),",
              "                ---- Analysis",
              "        \"1_Net Invoice Sales\", [Delta 1_Net Invoice Sales],",
              "        \"1a_Rebate Accruals\", [Delta 1a_Rebate Accruals], ",
              "        \"2_Net Revenue\", [Delta 2_Net Revenue],",
              "        \"2a_Fin Accr & Rebates\", [Delta 2a_Fin Accr & Rebates],",
              "        \"3_Reported Revenue\", [Delta 3_Reported Revenue],",
              "        \"3a_COGS Standard\", [Delta 3a_COGS Standard],",
              "        \"3b_COGS Actual\", [Delta 3b_Cogs Actual],",
              "        \"5_Standard Finance Margin\", [Delta 5_Standard Finance Margin],",
              "        \"6_Actual Finance Margin\", [Delta 6_Actual Finance Margin],",
              "        \"7_Gross Margin\", [Delta 7_Gross Margin],",
              "        \"7%_Gross Margin %\", FORMAT([Delta 7_Gross Margin %], \"Percent\"), ",
              "        ----------- Predefined",
              "        \"Sales\", [DeltaNetAmount],",
              "        \"COGS\", IF(SELECTEDVALUE(srv_Cogs_cost[Choose KPI])=\"At actual cost\",[DeltaCogs],[DeltaCogs a/c]),",
              "        \"Sales Margin\", [DeltaSalesMargin],",
              "        \"Other CoS\", [DeltaOtherCOS],",
              "        \"Gross Profit\", [DeltaGrossProfit]",
              "            ),",
              "    [DeltaNetAmount]",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "87bbd84b-d45e-48a9-b292-1c5c9fe9ecb0"
          },
          {
            "name": "Title_SalesDistrict",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\" by Sales District\"",
            "isHidden": true,
            "lineageTag": "75d9d2b0-b8ea-4918-a695-ac2c262aa96e"
          },
          {
            "name": "Title_Country",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\" by Delivery Country\"",
            "isHidden": true,
            "lineageTag": "e627857b-b072-452c-9b13-06b20fb22e42"
          },
          {
            "name": "Sales&MarginsK PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales and Margins",
            "expression": "DIVIDE([KPI PY],1000)",
            "isHidden": true,
            "lineageTag": "c26b17a0-5a87-4f83-96aa-2208ce9c1782"
          },
          {
            "name": "MsgCurrentCountry",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "var CountryCount = CALCULATE(DISTINCTCOUNT(ACDOCA_EPMSalesView[SalesOrganizationID]),SalesOrganization[SalesOrganizationID]<>\"MA-Dummy\")",
              "return",
              "IF(CountryCount<1,\"\",if(CountryCount=1, \"Country: \"&CALCULATE(MAX(SalesOrganization[SalesOrganization]),SalesOrganization[SalesOrganizationID]<>\"MA-Dummy\"), \"Multiple countries\"))"
            ],
            "isHidden": true,
            "lineageTag": "8e1c80fa-ba08-4e48-a199-b5184a0930ba"
          },
          {
            "name": "Billing Docs per Order",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "BillingDocs",
            "expression": "DIVIDE([BillingDocsNumber],[OrderAmount])",
            "lineageTag": "2cb47249-5485-4d4e-825e-ca55ee73a751"
          },
          {
            "name": "Billing Docs per Order PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "BillingDocs",
            "expression": "CALCULATE([Billing Docs per Order], DATEADD('Calendar'[Date], -1, year))",
            "lineageTag": "3037583c-4e60-41bd-8973-c91f75d80bd1"
          },
          {
            "name": "Billing Docs per Order Delta",
            "displayFolder": "BillingDocs",
            "expression": "DIVIDE([Billing Docs per Order]-[Billing Docs per Order PY], [Billing Docs per Order PY])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7391fc2b-1ab8-474e-bf88-7f72261a93cc"
          },
          {
            "name": "Title_Project",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\" by Project\"",
            "isHidden": true,
            "lineageTag": "769a0239-5ce2-49c6-9e49-dd2fc2dc710d"
          },
          {
            "name": "Title_Product",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\" by Product\"",
            "isHidden": true,
            "lineageTag": "84159268-5b20-4256-999d-a61d072e4d0d"
          },
          {
            "name": "Title_Customer",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\" by Customer\"",
            "isHidden": true,
            "lineageTag": "4b030f43-95c5-48c3-aef6-6f0f1c78e38d"
          },
          {
            "name": "Title_tooltip_chart",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\" by Month\"",
            "isHidden": true,
            "lineageTag": "1e7f3fdf-89b4-4eed-aa75-34b406f8e46d"
          },
          {
            "name": "Title_tooltip_chart_week",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\" by Week\"",
            "isHidden": true,
            "lineageTag": "fa6f1fa7-8de6-448f-96d4-885dbb0f1e52"
          },
          {
            "name": "Title_YTD",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\": YTD vs PY by Month\"",
            "isHidden": true,
            "lineageTag": "d90466ff-5ad9-4b12-b8ba-7ea5d4a1471b"
          },
          {
            "name": "Title_YTD_week",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\": YTD vs PY by Week\"",
            "isHidden": true,
            "lineageTag": "725bf5f4-7069-44af-8ac4-48a46db73e6a"
          },
          {
            "name": "Title_YTD_Delta",
            "displayFolder": "Titles",
            "expression": "\"Delta \"&SELECTEDVALUE(srv_MeasureTypes[Choose KPI])",
            "isHidden": true,
            "lineageTag": "9da6b72a-fa86-4628-a65f-0368b43373e3"
          },
          {
            "name": "SelectedPeriod",
            "displayFolder": "Notifications",
            "expression": "SELECTEDVALUE('Calendar'[MonthName])",
            "isHidden": true,
            "lineageTag": "69352e4d-5afd-476d-8d26-270db67cdc74"
          },
          {
            "name": "SelectedValue_Application",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "",
              "IF (",
              "    ISFILTERED ( ACDOCA_EPMSalesView[Application] ),",
              "    CONCATENATEX ( FILTERS ( ACDOCA_EPMSalesView[Application]), ACDOCA_EPMSalesView[Application], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "ff50b1c4-9fb1-4116-a8c1-3dfc2589b871"
          },
          {
            "name": "SelectedValue_SalesOrganization",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( SalesOrganization[SalesOrganization] ),",
              "    CONCATENATEX ( FILTERS ( SalesOrganization[SalesOrganization]), SalesOrganization[SalesOrganization], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "e0298159-df4c-4cec-b4f3-0389bc0f028f"
          },
          {
            "name": "SelectedValue_Product",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Product'[Product]),",
              "    CONCATENATEX ( FILTERS ( 'Product'[Product]), 'Product'[Product], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "ca251011-0cef-45c4-8f79-29100bc2ccb7"
          },
          {
            "name": "SelectedValue_Period",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "var Year1 = ",
              "IF (",
              "    ISFILTERED ( 'Calendar'[Year] ),",
              "    CONCATENATEX ( FILTERS ( 'Calendar'[Year]), 'Calendar'[Year], \", \" ),",
              "    \"ALL Year\"",
              ")",
              "var Month1 = ",
              "IF (",
              "    ISFILTERED ( 'Calendar'[MonthName] ),",
              "    CONCATENATEX ( FILTERS ( 'Calendar'[MonthName]), 'Calendar'[MonthName], \", \" ),",
              "    \"All Month\"",
              ")",
              "var DateRange = ",
              "IF (",
              "    ISFILTERED ( 'Calendar'[Date] ),",
              "    CONCATENATEX ( FILTERS ( 'Calendar'[Date]), max('Calendar'[Date]), \", \" ),",
              "    \"ALL\"",
              ")",
              "return",
              "Year1&\" \"&Month1"
            ],
            "isHidden": true,
            "lineageTag": "b1c4cfd0-2e4b-478b-bc22-27376d3181e6"
          },
          {
            "name": "SelectedValue_SalesDistrict",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( ACDOCA_EPMSalesView[SalesDistrictID] ),",
              "    CONCATENATEX ( FILTERS ( ACDOCA_EPMSalesView[SalesDistrictID]), ACDOCA_EPMSalesView[SalesDistrictID], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "92f387fc-4450-4758-9090-4667f0b75dcb"
          },
          {
            "name": "SelectedYear",
            "displayFolder": "Notifications",
            "expression": "INT(SELECTEDVALUE('Calendar'[Year]))",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "11906298-af83-474a-86e5-700e14039687"
          },
          {
            "name": "SelectedValue_Region",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( SalesOrganization[RegionName] ),",
              "    CONCATENATEX ( FILTERS (SalesOrganization[RegionName]), SalesOrganization[RegionName], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "e220ad06-2e4f-4f83-a775-4a02ceb2a444"
          },
          {
            "name": "SelectedValue_KPI",
            "displayFolder": "Notifications",
            "expression": [
              "IF (",
              "    AND(ISFILTERED ( srv_MeasureTypes[Choose KPI] ), MAX(srv_MeasureTypes[Type]) = \"Analysis\"), ",
              "    CONCATENATEX ( FILTERS (srv_MeasureTypes[Choose KPI]), srv_MeasureTypes[Choose KPI], \", \" ),",
              "    \"Predefined KPI is chosen\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "1a4d18b1-dee5-4c82-b3ab-66510012e9d4"
          },
          {
            "name": "SelectedValue_Customer",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( CustomerSoldTo[Customer]),",
              "    CONCATENATEX ( FILTERS ( CustomerSoldTo[Customer]), CustomerSoldTo[Customer], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "7fe30e6a-cfc2-4c1b-8dff-9cdd7da137c4"
          },
          {
            "name": "SelectevValue_CurrencyType",
            "displayFolder": "Notifications",
            "expression": "SELECTEDVALUE(ACDOCA_EPMSalesView[CurrencyType])",
            "isHidden": true,
            "lineageTag": "2593a28b-6e14-4a0e-ba93-0878599d8e27"
          },
          {
            "name": "SelectedValue_MaterialType",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Product'[MaterialType]),",
              "    CONCATENATEX ( FILTERS ('Product'[MaterialType]),'Product'[MaterialType], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "5d22be37-cea2-4ca3-85c4-d7cfd55ac6e3"
          },
          {
            "name": "SelectedValue_BillingDocType",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( ACDOCA_EPMSalesView[BillingDocumentTypeID]),",
              "    CONCATENATEX ( FILTERS ( ACDOCA_EPMSalesView[BillingDocumentTypeID]), ACDOCA_EPMSalesView[BillingDocumentTypeID], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "d903ce52-8747-43fa-923c-68eddb3675e9"
          },
          {
            "name": "Sales&MarginsCustomerRank",
            "displayFolder": "Sales and Margins",
            "expression": [
              "",
              "IF([KPI]+[KPI PY]=0, BLANK(), --RANKX(ALLSELECTED(CustomerSoldTo[ID_Customer]), CALCULATE([KPI])))",
              "",
              "CALCULATE(RANKX(ALLselected(CustomerSoldTo),[KPI],,DESC,Dense),",
              "    ALLSELECTED(CustomerSoldTo[CityName])))"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "31fbeb8b-0240-4448-9583-8e8ac5393767"
          },
          {
            "name": "Sales&MarginsCustomerRank PY",
            "displayFolder": "Sales and Margins",
            "expression": [
              "",
              "--IF( ISBLANK([KPI]), BLANK(), RANKX(ALLSELECTED(CustomerSoldTo[ID_Customer]), CALCULATE([KPI PY])) )",
              "",
              "CALCULATE(RANKX(all(CustomerSoldTo[CustomerID]),CALCULATE([KPI PY]),,DESC),",
              "    ALLSELECTED(CustomerSoldTo[CityName]))"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "abf37b1f-1d43-448f-b25f-aefb3b0c9d97"
          },
          {
            "name": "DeltaSales&MarginsCustomerRankSign",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Deltas",
            "expression": "IF( [DeltaKPICustomerRank]<>0, IF([DeltaKPICustomerRank]>0, \"+\"&[DeltaKPICustomerRank], [DeltaKPICustomerRank]) )",
            "isHidden": true,
            "lineageTag": "bf45ebfe-ed0b-44f7-81aa-662297dac6a9"
          },
          {
            "name": "DeltaKPICustomerRank",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Deltas",
            "expression": "if([CustomerRankFilter]=1,[Sales&MarginsCustomerRank PY]-[Sales&MarginsCustomerRank])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1169a3c7-dd44-42c1-a570-d6540d067f88"
          },
          {
            "name": "CustomerSelected",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "var _filter = SELECTEDVALUE(CustomerSoldTo[CustomerID_Name])",
              "return",
              "if(count(CustomerSoldTo[CustomerID_Name])>1,\"\",\"Customer: \" & _filter)"
            ],
            "isHidden": true,
            "lineageTag": "68ce787d-6892-4a95-a7cc-6cc4ab5999f9"
          },
          {
            "name": "CitySelected",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "var _filter = SELECTEDVALUE(CustomerSoldTo[CityName])",
              "return",
              "if(count(CustomerSoldTo[CustomerID_Name])>1,\"\",\"City: \" & _filter)"
            ],
            "isHidden": true,
            "lineageTag": "393b1da6-736f-4f2c-95c5-121c079cf770"
          },
          {
            "name": "CustomerRankFilter",
            "displayFolder": "Other measures",
            "expression": "IF([KPI]+[KPI PY]=0, 0, 1)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "90f84fc7-e72c-4302-94f1-690fcbace409"
          },
          {
            "name": "KPI Delta color",
            "displayFolder": "KPI dynamic",
            "expression": "IF([KPI Delta]>=0,1,0)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c8cef6dc-e8ec-4206-8d25-4c75a8f74cb7"
          },
          {
            "name": "AmountInCompanyCodeCurrency",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Other measures",
            "expression": "CALCULATE(sum(ACDOCA_EPMSalesView[SalesAmount]))",
            "isHidden": true,
            "lineageTag": "ee0f4511-01ba-475d-8ea7-48ba36573da1"
          },
          {
            "name": "SelectedValue_inoutid",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( ACDOCA_EPMSalesView[InOutID]),",
              "    CONCATENATEX ( FILTERS ( ACDOCA_EPMSalesView[InOutID]), ACDOCA_EPMSalesView[InOutID], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "a329e7a3-6be2-49f4-a3e7-0c276c64c39f"
          },
          {
            "name": "SelectedValue_glaccountid",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( GLAccount[glaccountID_Name]),",
              "    CONCATENATEX ( FILTERS ( GLAccount[glaccountID_Name]), GLAccount[glaccountID_Name], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "d204d9c3-8a9a-4e52-853a-43ac11b85083"
          },
          {
            "name": "SelectedValue_acdoca_ledger",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( ACDOCA_EPMSalesView[SourceLedgerID]),",
              "    CONCATENATEX ( FILTERS ( ACDOCA_EPMSalesView[SourceLedgerID]), ACDOCA_EPMSalesView[SourceLedgerID], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "b02c560a-d8b4-47ef-8995-e1fd95694983"
          },
          {
            "name": "SelectedValue_acdoca_tpadjustment",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( ACDOCA_EPMSalesView[TPAdjustment]),",
              "    CONCATENATEX ( FILTERS ( ACDOCA_EPMSalesView[TPAdjustment]), ACDOCA_EPMSalesView[TPAdjustment], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "ffb1503e-12a2-451b-968c-3cf4ccd77131"
          },
          {
            "name": "SelectedValue_acdoca_ma_adjustment",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( ACDOCA_EPMSalesView[ManualAdjustment]),",
              "    CONCATENATEX ( FILTERS ( ACDOCA_EPMSalesView[ManualAdjustment]), ACDOCA_EPMSalesView[ManualAdjustment], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "6981f406-ff33-42e7-a758-701e98c7e35d"
          },
          {
            "name": "SelectedValue_profit_center",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( ProfitCenter[ProfitCenter]),",
              "    CONCATENATEX ( FILTERS ( ProfitCenter[ProfitCenter]), ProfitCenter[ProfitCenter], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "8d7170c7-3046-44ea-af9b-580077f3f616"
          },
          {
            "name": "SelectedValue_product_group",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Product'[Product_L2_Group]),",
              "    CONCATENATEX ( FILTERS (  'Product'[Product_L2_Group]),  'Product'[Product_L2_Group], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "57920142-aa13-408f-95a9-2ff76d4a8099"
          },
          {
            "name": "SelectedValue_product_pillar",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Product'[Product_L1_Pillar]),",
              "    CONCATENATEX ( FILTERS ( 'Product'[Product_L1_Pillar]), 'Product'[Product_L1_Pillar], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "86086cb1-c8cd-4d89-851f-03956e559482"
          },
          {
            "name": "SelectedValue_brand",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Product'[Brand]),",
              "    CONCATENATEX ( FILTERS ( 'Product'[Brand]), 'Product'[Brand], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "4277d929-8d47-49f4-9f94-9c26714f2366"
          },
          {
            "name": "NetAmount YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales and Margins",
            "expression": "round(TOTALYTD(sum(ACDOCA_EPMSalesView[SalesAmount]),'Calendar'[Date]),1)",
            "lineageTag": "03f0dfa6-c0dd-41f1-b288-f8819aa4bb2b"
          },
          {
            "name": "NetAmount PY YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales and Margins",
            "expression": "round(CALCULATE([NetAmount YTD], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "b5ae0be2-234b-4798-8b27-06b1505f420b"
          },
          {
            "name": "DeltaNetAmount YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Deltas",
            "expression": "IF([NetAmount PY YTD]<>BLANK(), [NetAmount YTD]-[NetAmount PY YTD], BLANK())",
            "lineageTag": "d956ccb3-5da7-444a-9bb0-65128f02a22a"
          },
          {
            "name": "SelectedValue_Companycode_ID",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( ACDOCA_EPMSalesView[CompanyCodeID] ),",
              "    CONCATENATEX ( FILTERS ( ACDOCA_EPMSalesView[CompanyCodeID]), ACDOCA_EPMSalesView[CompanyCodeID], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "e4b08cbd-0dde-43b0-8977-004a37cf50c8"
          },
          {
            "name": "Cogs",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Cogs",
            "expression": "CALCULATE(SUM(ACDOCA_EPMSalesView[COGSStdCostAmount])) ",
            "lineageTag": "0c39b5da-42b1-4e0d-b0d1-485b1889a7a5"
          },
          {
            "name": "Cogs a/c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Cogs",
            "expression": "CALCULATE(SUM(ACDOCA_EPMSalesView[COGSActCostAmount]))",
            "lineageTag": "49407efb-9ea1-493e-a9e6-aa75cc7955a6"
          },
          {
            "name": "SalesMargin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales and Margins",
            "expression": "[Sales]+[cogs_switch]  ",
            "lineageTag": "7126526f-7e41-4001-a881-05e324fe4586"
          },
          {
            "name": "OtherCOS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales and Margins",
            "expression": "CALCULATE(SUM(ACDOCA_EPMSalesView[OtherCoSAmount])) ",
            "lineageTag": "a79b5c50-269f-49bb-b6f3-dbebc48942bb"
          },
          {
            "name": "GrossProfit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales and Margins",
            "expression": "CALCULATE([SalesMargin]+[OtherCOS])",
            "lineageTag": "20a48e25-81bd-4c87-9ecd-0e721b8f7d3e"
          },
          {
            "name": "COGS PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Cogs",
            "expression": "round(CALCULATE([Cogs], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "76a18151-9fc1-4583-9575-2b0662496b4d"
          },
          {
            "name": "COGS a/c PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Cogs",
            "expression": "round(CALCULATE([Cogs a/c], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "76d6016d-69ab-4639-aa56-d5680c096aa0"
          },
          {
            "name": "SalesMargin PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales and Margins",
            "expression": "round(CALCULATE([SalesMargin], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "ad2b19eb-823f-4ce9-b33d-463ae31acba4"
          },
          {
            "name": "OtherCOS PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales and Margins",
            "expression": "round(CALCULATE([OtherCOS], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "5cbe6f5e-b52b-44f9-8921-d15770717a2c"
          },
          {
            "name": "GrossProfit PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales and Margins",
            "expression": "round(CALCULATE([GrossProfit], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "a9bd23cb-cbb2-4521-88e0-061b5469f966"
          },
          {
            "name": "MsgCogsCost",
            "displayFolder": "Notifications",
            "expression": "IF(SELECTEDVALUE(srv_Cogs_cost[Choose KPI]) =\"At Standard Cost\", \"Standard Cost\", \"Actual cost\")",
            "isHidden": true,
            "lineageTag": "664f180d-0ca7-4d9a-9180-23e80e31ed19"
          },
          {
            "name": "DeltaSalesMargint%",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Deltas",
            "expression": "DIVIDE(IF([SalesMargin PY]<>BLANK(), [SalesMargin]-[SalesMargin PY], BLANK()), [SalesMargin PY], BLANK())",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "8eb4dedc-84fd-4f6a-98e3-c19ccf2f40a3"
          },
          {
            "name": "DeltaCogs",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Deltas",
            "expression": "IF([Cogs]<>BLANK(), [Cogs]-[Cogs PY], BLANK())",
            "lineageTag": "d68135ee-90e4-47e3-a135-4f7ecf6c4635"
          },
          {
            "name": "DeltaCogs a/c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Deltas",
            "expression": "IF([Cogs a/c]<>BLANK(), [Cogs a/c]-[Cogs a/c], BLANK())",
            "lineageTag": "493ffe37-56f9-462b-9775-5d033b22d5ff"
          },
          {
            "name": "DeltaSalesMargin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Deltas",
            "expression": "IF([SalesMargin]<>BLANK(), [SalesMargin]-[SalesMargin PY], BLANK())",
            "lineageTag": "f7dd0402-7e31-44c2-be7c-926674be51a1"
          },
          {
            "name": "DeltaOtherCOS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Deltas",
            "expression": "IF([OtherCOS]<>BLANK(), [OtherCOS]-[OtherCOS PY], BLANK())",
            "lineageTag": "270b3026-f4d2-4efb-9861-d1497beac55b"
          },
          {
            "name": "DeltaProfitMargin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Deltas",
            "expression": "IF([GrossProfit]<>BLANK(), [GrossProfit]-[GrossProfit PY], BLANK())",
            "lineageTag": "1abc6c27-59aa-4d68-a581-34920263ee25"
          },
          {
            "name": "DeltaGrossProfit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Deltas",
            "expression": "IF([GrossProfit]<>BLANK(), [GrossProfit]-[GrossProfit PY], BLANK())",
            "lineageTag": "784ead95-aa28-4028-b012-6ccb7af2c2d4"
          },
          {
            "name": "cogs_switch",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Cogs",
            "expression": "IF(SELECTEDVALUE(srv_Cogs_cost[Choose KPI])=\"At standard cost\",[Cogs],[Cogs a/c])",
            "isHidden": true,
            "lineageTag": "fbe0d9c5-362d-4057-aba5-2d0ca1ba8d20"
          },
          {
            "name": "cogs_switch_py",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Cogs",
            "expression": "IF(SELECTEDVALUE(srv_Cogs_cost[Choose KPI])=\"At standard cost\", [Cogs a/c py],[COGS PY])",
            "isHidden": true,
            "lineageTag": "226d59c9-e1f4-4ee9-812b-c933c2a2c030"
          },
          {
            "name": "Amount cy",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Other measures",
            "expression": "CALCULATE(SUM(ACDOCA_EPMSalesView[Amount]))",
            "lineageTag": "a755adc1-51a0-4553-a616-0f51e48e0515"
          },
          {
            "name": "Amount PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Other measures",
            "expression": "round(CALCULATE([Amount cy], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "fe59f185-9016-487c-b66f-6804077d8c13"
          },
          {
            "name": "DeltaNetAmount_col",
            "displayFolder": "Deltas",
            "expression": "IF([DeltaNetAmount%]<0,0,1) ",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fb034030-ae83-4b4b-aff0-06c654a04635"
          },
          {
            "name": "DeltaSalesMargin_col",
            "displayFolder": "Deltas",
            "expression": "IF([DeltaSalesMargint%]<0,0,1) ",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b56683e1-2bfd-4b4f-b26e-ba95ee85f194"
          },
          {
            "name": "DeltaCustAmount_col",
            "displayFolder": "Deltas",
            "expression": "IF([DeltaCustomerAmount%]<0,0,1) ",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "273cd2d7-e3de-4f6f-ade4-28651b198061"
          },
          {
            "name": "GrossMargin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales and Margins",
            "expression": "CALCULATE(SUM(ACDOCA_EPMSalesView[GrossMarginAmount])) ",
            "lineageTag": "0b6511c5-5f5d-44b3-b3af-b308a3d9d734"
          },
          {
            "name": "DeltaKPI%",
            "displayFolder": "Deltas",
            "expression": "DIVIDE(IF([KPI PY]<>BLANK(), [KPI]-[KPI PY], BLANK()), [KPI PY], BLANK())",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "0cb73459-c7bc-45aa-8c91-ed427d7749d6"
          },
          {
            "name": "Opex",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales and Margins",
            "expression": "CALCULATE(SUM(ACDOCA_EPMSalesView[OpexAmount])) ",
            "lineageTag": "1d4872f2-531e-4cc1-8634-1786f777cf9c"
          },
          {
            "name": "Opex PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales and Margins",
            "expression": "round(CALCULATE([Opex], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "d37c49d2-877c-4644-9550-6353a4fdcb47"
          },
          {
            "name": "GrossMargin PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Sales and Margins",
            "expression": "round(CALCULATE([GrossMargin], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "a76d03b7-7414-4ae7-8870-ec52bfe364bb"
          },
          {
            "name": "MC %",
            "displayFolder": "Sales and Margins",
            "expression": "DIVIDE([GrossMargin],[Sales],0)",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "4d149eac-d423-4c38-9d1f-947aafd7ed43"
          },
          {
            "name": "MC % PY",
            "displayFolder": "Sales and Margins",
            "expression": "CALCULATE([MC %], DATEADD('Calendar'[Date], -1, year))",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "62283583-bfad-4ff4-95fc-932507f5969f"
          },
          {
            "name": "Sales Margin %",
            "displayFolder": "Sales and Margins",
            "expression": "DIVIDE([SalesMargin],[Sales],0) ",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "e58a745e-7a49-4fd4-b522-c7301c9a598f"
          },
          {
            "name": "Profit Margin %",
            "displayFolder": "Profit",
            "expression": "DIVIDE([GrossProfit],[Sales],0) ",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "bbe2fea2-cb07-47a5-b2b6-981f318a26a4"
          },
          {
            "name": "KPI_Tooltip_Title",
            "displayFolder": "KPI dynamic",
            "expression": "CONCATENATE(SELECTEDVALUE(srv_MeasureTypes[Choose KPI]),\" by Week\")",
            "lineageTag": "23d8adf0-e7b5-4d71-b875-33a45eb37fe2"
          },
          {
            "name": "Sales Margin % PY",
            "displayFolder": "Sales and Margins",
            "expression": "DIVIDE([SalesMargin PY],[Sales PY],0) ",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "f6814f94-25d9-4bf2-b94f-84aaf9ae7f38"
          },
          {
            "name": "Profit Margin % PY",
            "displayFolder": "Profit",
            "expression": "DIVIDE([GrossProfit PY],[Sales PY],0) ",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "2e100bc7-132b-4a03-ae7b-3544f4c06ff0"
          },
          {
            "name": "Profit Margin % Delta",
            "displayFolder": "Profit",
            "expression": "[Profit Margin %]-[Profit Margin % PY]",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "abecb395-2405-43da-9663-90b080c836df"
          },
          {
            "name": "Delta Gross Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Deltas",
            "expression": "[GrossMargin]-[GrossMargin PY]",
            "lineageTag": "c54dd845-d6db-4b9b-8379-8df390baaea6"
          },
          {
            "name": "Delta MC %",
            "displayFolder": "Deltas",
            "expression": "[MC %]-[MC % PY] ",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "d7ab77cf-5a0a-429d-8181-f68e71dcccc6"
          },
          {
            "name": "SelectedValue_Source",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( ACDOCA_EPMSalesView[Source]),",
              "    CONCATENATEX ( FILTERS ( ACDOCA_EPMSalesView[Source]), ACDOCA_EPMSalesView[Source], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "a56122bd-8b46-4608-af41-e49c1aca9127"
          },
          {
            "name": "SelectedValue_Subsource",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( ACDOCA_EPMSalesView[Subsource]),",
              "    CONCATENATEX ( FILTERS ( ACDOCA_EPMSalesView[Subsource]), ACDOCA_EPMSalesView[Subsource], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "793c10dc-45b9-45a8-a4c4-62be4f1b5297"
          },
          {
            "name": "SelectedValue_Predefined_KPI",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    AND(ISFILTERED (srv_MeasureTypes[Choose KPI] ), MAX(srv_MeasureTypes[Type]) = \"Predefined\"), ",
              "    CONCATENATEX ( FILTERS (srv_MeasureTypes[Choose KPI]), srv_MeasureTypes[Choose KPI], \", \" ),",
              "    \"Analysis KPI is chosen\"",
              ")"
            ],
            "lineageTag": "f1d2dc17-ffc2-4373-9de8-4e0fc39513e3"
          },
          {
            "name": "SelectedValue_PredefinedKPI_filters",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "SWITCH([SelectedValue_Predefined_KPI],",
              "        -- 1",
              "        \"1_Net Invoice Sales\", ",
              "        \"Source: Billing, Net invoice Sales;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Standard;\",",
              "        -- 2",
              "        \"1a_Rebate Accruals\", ",
              "        \"Source: Billing, Rebates;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Standard;\",",
              "        -- 3",
              "        \"2_Net Revenue\", ",
              "        \"Source: Billing, Net invoice Sales, Rebates;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Standard;\",",
              "        -- 4",
              "        \"2a_Fin Accr & Rebates\", ",
              "        \"Source: Finance, Finance;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Standard;\",",
              "        -- 5",
              "        \"3_Reported Revenue\", ",
              "        \"Source: All;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Standard;\",",
              "        -- 6",
              "        \"3a_COGS Standard\", ",
              "        \"Source: All;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Standard;\",",
              "        -- 7       ",
              "        \"3b_COGS Actual\", ",
              "        \"Source: All;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Actual;\",",
              "        -- 8",
              "        \"5_Standard Finance Margin\", ",
              "        \"Source: All;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Standard;\",",
              "        -- 9",
              "        \"6_Actual Finance Margin\", ",
              "        \"Source: All;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Actual;\",",
              "        -- 10",
              "        \"7_Gross Margin\", ",
              "        \"Source: All;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Actual;\")",
              ""
            ],
            "lineageTag": "9a29e809-3d7e-45fa-90a5-cbdd9bb28945"
          },
          {
            "name": "SelectedValue_KPI_type",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF(",
              "    AND([SelectedValue_KPI] = \"Predefined KPI is chosen\", [SelectedValue_Predefined_KPI] = \"Analysis KPI is chosen\"),",
              "    \"KPI has to be selected in main slicer pane respectively to type selected in hidden filter panel\", SELECTEDVALUE(srv_MeasureTypes[Type])",
              ")"
            ],
            "lineageTag": "111e3ae6-a288-4d88-b55c-1b652ee88219"
          },
          {
            "name": "1_Net Invoice Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE(",
              "    [Sales], ",
              "    ACDOCA_EPMSalesView[Source] = \"Billing\",",
              "    ACDOCA_EPMSalesView[SubSourceShort] = \"Net\",",
              "    ACDOCA_EPMSalesView[TPAdjustment] = 0,",
              "    ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\"},",
              "    ALL(GLAccount[glaccountID_Name]),",
              "    FILTER(ACDOCA_EPMSalesView, CONCATENATE(ACDOCA_EPMSalesView[CompanyCodeID],ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              "    )"
            ],
            "lineageTag": "90a3524b-cd8e-4fbe-b218-863114d2d211"
          },
          {
            "name": "1_Net Invoice Sales PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([1_Net Invoice Sales], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "d4093ff4-2451-4b79-ad48-c06c758d66a2"
          },
          {
            "name": "1_Net Invoice Sales PY_1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([1_Net Invoice Sales], SAMEPERIODLASTYEAR('Calendar'[Date])),1)"
            ],
            "lineageTag": "b9467b5e-0232-4ad2-80b0-3d1315c586d7"
          },
          {
            "name": "1a_Rebate Accruals",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([Sales], ",
              "    ACDOCA_EPMSalesView[Source] = \"Billing\",",
              "    ACDOCA_EPMSalesView[SubSourceShort] = \"Reb\",",
              "    ACDOCA_EPMSalesView[TPAdjustment] = 0,",
              "    ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "    ALL(GLAccount[glaccountID_Name]),",
              "    FILTER(ACDOCA_EPMSalesView, CONCATENATE(ACDOCA_EPMSalesView[CompanyCodeID],ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              ")"
            ],
            "lineageTag": "5911c532-0fe9-4767-90f2-242823720be7"
          },
          {
            "name": "1a_Rebate Accruals PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([1a_Rebate Accruals], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "c5d6ce75-d03c-4341-ae12-1f59b106df9b"
          },
          {
            "name": "2_Net Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([Sales], ",
              "    ACDOCA_EPMSalesView[Source] = \"Billing\",",
              "    ACDOCA_EPMSalesView[SubSourceShort] in {\"Reb\", \"Net\"},",
              "    ACDOCA_EPMSalesView[TPAdjustment] = 0,",
              "    ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "    ALL(GLAccount[glaccountID_Name]),",
              "    FILTER(ACDOCA_EPMSalesView, CONCATENATE(ACDOCA_EPMSalesView[CompanyCodeID],ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              ")"
            ],
            "lineageTag": "a93c7cae-4646-4b15-bd9a-0d5077eced16"
          },
          {
            "name": "2_Net Revenue PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([2_Net Revenue], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "f5829ec5-6961-46f3-89d4-246dd7da1319"
          },
          {
            "name": "2a_Fin Accr & Rebates",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([Sales], ",
              "    ACDOCA_EPMSalesView[Source] = \"Finance\",",
              "    ACDOCA_EPMSalesView[SubSourceShort] = \"Fin\",",
              "    ACDOCA_EPMSalesView[TPAdjustment] = 0,",
              "    ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "    ALL(GLAccount[glaccountID_Name]),",
              "    FILTER(ACDOCA_EPMSalesView, CONCATENATE(ACDOCA_EPMSalesView[CompanyCodeID],ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              ")"
            ],
            "lineageTag": "13b42e2e-7b9d-41de-9fb7-51406da6ce16"
          },
          {
            "name": "2a_Fin Accr & Rebates PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([2a_Fin Accr & Rebates], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "9ee5fd78-a241-42a3-811f-cb76766fa163"
          },
          {
            "name": "3_Reported Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([Sales], ",
              "    ALL(ACDOCA_EPMSalesView[Source]), ",
              "    ALL(ACDOCA_EPMSalesView[Subsource]),",
              "    ACDOCA_EPMSalesView[TPAdjustment] = 0,",
              "    ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "    ALL(GLAccount[glaccountID_Name]),",
              "    FILTER(ACDOCA_EPMSalesView, CONCATENATE(ACDOCA_EPMSalesView[CompanyCodeID],ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              ")"
            ],
            "lineageTag": "74e71ed8-ca58-4d59-826f-ccbbdfa72b8b"
          },
          {
            "name": "3_Reported Revenue PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([3_Reported Revenue], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "f38c3308-e01f-4144-9b1c-02246df462bc"
          },
          {
            "name": "3a_COGS Standard",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([Cogs], ",
              "            ACDOCA_EPMSalesView[TPAdjustment] = 0, ",
              "            ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "            ALL(GLAccount), ",
              "            ALL(ACDOCA_EPMSalesView[Source]), ",
              "            ALL(ACDOCA_EPMSalesView[Subsource]),",
              "            FILTER(ACDOCA_EPMSalesView, CONCATENATE(ACDOCA_EPMSalesView[CompanyCodeID],ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              "        )"
            ],
            "lineageTag": "ab8bba5c-f7c5-4516-8cb5-22d5eb7d024c"
          },
          {
            "name": "3a_COGS Standard PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([3a_COGS Standard], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "0f4d1e0d-d7bd-42bc-891c-8072127c3c9f"
          },
          {
            "name": "3b_COGS Actual",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([Cogs a/c], ",
              "            ACDOCA_EPMSalesView[TPAdjustment] = 0, ",
              "            ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "            ALL(GLAccount[GLAccountID]), ",
              "            ALL(ACDOCA_EPMSalesView[Source]), ",
              "            ALL(ACDOCA_EPMSalesView[Subsource]),",
              "            FILTER(ACDOCA_EPMSalesView, CONCATENATE(ACDOCA_EPMSalesView[CompanyCodeID],ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              "        )"
            ],
            "lineageTag": "ea60141e-37c2-492f-8d2c-bfdb424dd8b8"
          },
          {
            "name": "3b_COGS Actual PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([3b_COGS Actual], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "b3e90866-9782-438c-9c82-57dcdf9b7b8e"
          },
          {
            "name": "5_Standard Finance Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([Sales] + [Cogs], ",
              "            ACDOCA_EPMSalesView[TPAdjustment] = 0, ",
              "            ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "            ALL(GLAccount[GLAccountID]), ",
              "            ALL(ACDOCA_EPMSalesView[Source]), ",
              "            ALL(ACDOCA_EPMSalesView[Subsource]),",
              "            FILTER(ACDOCA_EPMSalesView, CONCATENATE(ACDOCA_EPMSalesView[CompanyCodeID],ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              "        )"
            ],
            "lineageTag": "2238eb59-f867-4adf-9320-90c9eb3abd11"
          },
          {
            "name": "5_Standard Finance Margin PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([5_Standard Finance Margin], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "00b6a25d-d39e-48c9-ab5b-d38c8386d44e"
          },
          {
            "name": "6_Actual Finance Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([Sales]+ [Cogs a/c], ",
              "            ACDOCA_EPMSalesView[TPAdjustment] = 0, ",
              "            ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "            ALL(GLAccount[GLAccountID]), ",
              "            ALL(ACDOCA_EPMSalesView[Source]), ",
              "            ALL(ACDOCA_EPMSalesView[Subsource]),",
              "            FILTER(ACDOCA_EPMSalesView, CONCATENATE(ACDOCA_EPMSalesView[CompanyCodeID],ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              "        )"
            ],
            "lineageTag": "deb58a71-556b-4d69-b920-721e617b0628"
          },
          {
            "name": "6_Actual Finance Margin PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([6_Actual Finance Margin], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "ccb99efa-4354-4ace-99ad-380bb5735bb4"
          },
          {
            "name": "7_Gross Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([GrossMargin], ",
              "            ACDOCA_EPMSalesView[TPAdjustment] = 0, ",
              "            ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "            ALL(GLAccount[GLAccountID]), ",
              "            ALL(ACDOCA_EPMSalesView[Source]), ",
              "            ALL(ACDOCA_EPMSalesView[Subsource]),",
              "            FILTER(ACDOCA_EPMSalesView, CONCATENATE(ACDOCA_EPMSalesView[CompanyCodeID],ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              "        )"
            ],
            "lineageTag": "90608482-35d9-426a-a3fc-33985223c8cc"
          },
          {
            "name": "7_Gross Margin PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([7_Gross Margin], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "640fed40-005f-4338-9820-f3132348f940"
          },
          {
            "name": "Notification_KPI_name",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF(",
              "    AND([SelectedValue_KPI] = \"Predefined KPI is chosen\", [SelectedValue_Predefined_KPI] = \"Analysis KPI is chosen\"),",
              "    \"select KPI respectively to KPI type\", SELECTEDVALUE(srv_MeasureTypes[Choose KPI])",
              ")"
            ],
            "lineageTag": "0c79e81c-6076-46a2-babf-f5150c374a59"
          },
          {
            "name": "Selected_Period",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "var Year1 = ",
              "IF (",
              "    ISFILTERED ( 'Calendar'[Year] ),",
              "    CONCATENATEX ( FILTERS ( 'Calendar'[Year]), 'Calendar'[Year], \", \" ),",
              "    \"ALL Year\"",
              ")",
              "var Month1 = ",
              "IF (",
              "    ISFILTERED ( 'Calendar'[MonthName] ),",
              "    CONCATENATEX ( FILTERS ( 'Calendar'[MonthName]), 'Calendar'[MonthName], \", \" ),",
              "    \"All Month\"",
              ")",
              "var DateCnt = DISTINCTCOUNT('Calendar'[Day])",
              "var DateRange = ",
              "IF (",
              "    ISFILTERED ( 'Calendar'[Day] ),",
              "    IF(DateCnt =1, ",
              "    CONCATENATEX ( FILTERS ( 'Calendar'[Day]), 'Calendar'[Day], \", \"), \"Multiple days\"),",
              "    \"All Days\"",
              ")",
              "return",
              "\"Selected period: \"&Year1&\", \"&Month1&\", \"&DateRange "
            ],
            "lineageTag": "e91ba393-caaa-4eff-84e3-ce743d3c8be5"
          },
          {
            "name": "Delta 1_Net Invoice Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[1_Net Invoice Sales] - [1_Net Invoice Sales PY]",
            "lineageTag": "50eb5a4a-dcd2-41a2-af0b-b9d9206cf27a"
          },
          {
            "name": "Delta 2_Net Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[2_Net Revenue] - [2_Net Revenue PY]",
            "lineageTag": "ce67dda2-d21a-4c6b-a126-ee2193e5c00d"
          },
          {
            "name": "Delta 1a_Rebate Accruals",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[1a_Rebate Accruals] - [1a_Rebate Accruals PY]",
            "lineageTag": "e31ecdb2-3c1f-4530-bb6f-e2f4eb4fee20"
          },
          {
            "name": "Delta 2a_Fin Accr & Rebates",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[2a_Fin Accr & Rebates] - [2a_Fin Accr & Rebates PY]",
            "lineageTag": "efcb1049-aad3-42db-a3fb-c7093943b50b"
          },
          {
            "name": "Delta 3_Reported Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[3_Reported Revenue] - [3_Reported Revenue PY]",
            "lineageTag": "820005fd-2df2-4140-ae0b-3739ef8df7e8"
          },
          {
            "name": "Delta 3a_COGS Standard",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[3a_COGS Standard] - [3a_COGS Standard PY]",
            "lineageTag": "00385fa3-e1d5-450f-8d33-82e8c2dc5e7b"
          },
          {
            "name": "Delta 3b_Cogs Actual",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[3b_COGS Actual] -[3b_COGS Actual PY]",
            "lineageTag": "468211c6-1717-4c92-9da4-416a6f142701"
          },
          {
            "name": "Delta 5_Standard Finance Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[5_Standard Finance Margin] -[5_Standard Finance Margin PY]",
            "lineageTag": "c52d6ac9-8226-4058-a9db-927847aaa44f"
          },
          {
            "name": "Delta 6_Actual Finance Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[6_Actual Finance Margin] -[6_Actual Finance Margin PY]",
            "lineageTag": "a9d45f07-a5df-4fec-a756-3ff38f4cc4d6"
          },
          {
            "name": "Delta 7_Gross Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[7_Gross Margin] -[7_Gross Margin PY]",
            "lineageTag": "224623a7-99be-447d-b637-c2e1e650e953"
          },
          {
            "name": "MsgCurrentRegion",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "var RegionCount = CALCULATE(DISTINCTCOUNT(CompanyCode[RegionID]))",
              "return",
              "IF(RegionCount<1,\"\",if(RegionCount=1, \"Region: \"&SELECTEDVALUE(CompanyCode[Region]), \"Multiple regions\"))"
            ],
            "lineageTag": "3bcd2d41-b518-45f3-8348-b937b57c907d"
          },
          {
            "name": "Notification_KPI_name_dynamic_left",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF(",
              "   [SelectedValue_KPI] = \"Predefined KPI is chosen\", \"3_Reported_Revenue\", \"Sales\"",
              ")"
            ],
            "lineageTag": "d57b8ad4-1013-4c31-8e55-518133f32fc0"
          },
          {
            "name": "KPI left",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "KPI dynamic",
            "expression": [
              "",
              "IF([SelectedValue_KPI] = \"Predefined KPI is chosen\", [3_Reported Revenue], [Sales])"
            ],
            "lineageTag": "189ce3c9-49cc-473e-a5dd-9d040abab634"
          },
          {
            "name": "Delta 3_Reported Revenue%",
            "displayFolder": "!Predefined KPIs",
            "expression": "IF([3_Reported Revenue PY] <> BLANK(), DIVIDE([3_Reported Revenue] - [3_Reported Revenue PY], [3_Reported Revenue PY]), BLANK())",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ec9f21ce-be55-44e6-8e62-b4fda789e880"
          },
          {
            "name": "7_Gross Margin %",
            "displayFolder": "!Predefined KPIs",
            "expression": "DIVIDE([7_Gross Margin], [3_Reported Revenue], 0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "139a4387-44c0-496d-ac4c-f607529f3534"
          },
          {
            "name": "7_Grosss Margin % PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "round(CALCULATE([7_Gross Margin %], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "466f93a2-8509-4abd-8f2b-1a0afa78280a"
          },
          {
            "name": "Delta 7_Gross Margin %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[7_Gross Margin %] - [7_Grosss Margin % PY]",
            "lineageTag": "87b7ac9a-3492-4070-8021-50b830132071"
          },
          {
            "name": "DeltaGrossMargin_col",
            "displayFolder": "Deltas",
            "expression": "IF([Delta 7_Gross Margin %]<0,0,1) ",
            "formatString": "0",
            "lineageTag": "df8ab6ac-b406-459a-8181-428ade52eed7"
          },
          {
            "name": "Delta 7_Gross Margin %%",
            "displayFolder": "!Predefined KPIs",
            "expression": "DIVIDE(IF([7_Grosss Margin % PY]<>BLANK(), [7_Gross Margin %] - [7_Grosss Margin % PY], BLANK()), [7_Grosss Margin % PY], BLANK())",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "edfd8421-9eb9-4201-b41d-c62459b0a9b6"
          },
          {
            "name": "7_Grosss Margin %% PY",
            "displayFolder": "!Predefined KPIs",
            "expression": "round(CALCULATE([7_Gross Margin %], DATEADD('Calendar'[Date], -1, year)),1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3e83a07c-b11e-4348-a56b-bb1cd4369c5a"
          },
          {
            "name": "6_Actual Finance Margin % PY",
            "displayFolder": "!Predefined KPIs",
            "expression": "round(CALCULATE([6_Actual Finance Margin %], DATEADD('Calendar'[Date], -1, year)),1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7c6ed9de-04cd-4c3e-bcbc-9e4c46c3d7b7"
          },
          {
            "name": "6_Actual Finance Margin %",
            "displayFolder": "!Predefined KPIs",
            "expression": "[6_Actual Finance Margin] / [3_Reported Revenue]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "18fe9af3-152c-4d46-9399-1953550c3db0"
          },
          {
            "name": "KPI left delta %",
            "displayFolder": "KPI dynamic",
            "expression": [
              "",
              "  IF([SelectedValue_KPI] = \"Predefined KPI is chosen\", [Delta 3_Reported Revenue%], [DeltaNetAmount%])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "961369b9-53a3-4098-b0ab-fb68f85886b0"
          },
          {
            "name": "KPI left PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "KPI dynamic",
            "expression": [
              "",
              "IF( [SelectedValue_KPI] = \"Predefined KPI is chosen\", [3_Reported Revenue PY], [Sales PY])"
            ],
            "lineageTag": "6637a45b-0a73-4c1f-829b-8bb8402fed45"
          },
          {
            "name": "Notification_TP Adj",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF(",
              "   [SelectedValue_KPI] = \"Predefined KPI is chosen\", \"TP adjustments are excluded\", \" \"",
              ")"
            ],
            "lineageTag": "88a7a70c-dabe-4b38-931a-06f2ed7a6d61"
          }
        ],
        "partitions": [
          {
            "name": "_Measures-a5b9e016-864d-4b35-a6ae-b7bb615c2ef1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Measures = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Measures\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "srv_MeasureTypes",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Choose KPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2f0174e0-8f35-4d5e-8fdc-b9a75f7762e2",
            "sortByColumn": "Sort",
            "sourceColumn": "Choose KPI",
            "summarizeBy": "none"
          },
          {
            "name": "MeasureDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "bff0290b-5a3d-4822-850f-73c5da5d8bff",
            "sourceColumn": "MeasureDescription",
            "summarizeBy": "none"
          },
          {
            "name": "KPI Name PY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8a60f691-dff1-4147-b22d-e4304a02891c",
            "sourceColumn": "KPI Name PY",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ab07d1e6-7753-4437-a8a7-e95cdf04e794",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b730b00f-eb26-45d5-a215-0a20a4056dba",
            "sourceColumn": "Sort",
            "summarizeBy": "sum"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a1744b8c-d1eb-436f-8580-a8fa8c1192c1",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "07abc236-5ff9-4eac-8734-3194df3cb2ff",
        "partitions": [
          {
            "name": "srv_MeasureTypes-0e808762-32ef-4eea-85a7-87e9f1d60fd7",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"jZRBb4IwFMe/SkPizQOgoh4NycwOzkVOi5qmQt1ITDGlmu22+77lPslaXkFoK+4A5b3+3++9V9put15CTrT0ht0Rvb7Jz0A+C0ZOX2Veevvh1ovXywRJZ2cEbWhqgbMi/D1nDdZpAmBkAtbig3IUF4mccH5D3NiMW/KilA3w4pgLOddjAmBiJT7TT5XnNoAwcmdqeuoxATDtWyM0MJfFdgBmZmJ0N62whx4gzU3SKq7Eq7h61bLAN3UBfqECPbNrkacU1Vun5cvA+fv9o+Jttd40QVUZzegxZzIG2ARv6IEIihZpyi/kpNC2x5ZpZuhghlUFG3ql7EJ1pRwsKLEj0KCRC0Twk1w/lRLtLr4fRgiqUCXJGcLSVkGW4n64zjl25BzJRs8FF9K+dWC6ZBs7tetssSZPXGSCqyOcCMIywrP6SLdsU6JpkYt2AOkiFbL7mtVY3WnNmTo4E9wkq1f0dm+4Z+An9gWGM0emCOtiLLnTD1nuBOmG5o40U9xzNQC0K9E3ou9iDbpKdVz/5dNM68Tt/wA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Choose KPI\" = _t, MeasureDescription = _t, #\"KPI Name PY\" = _t, Sort = _t, Type = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Choose KPI\", type text}, {\"MeasureDescription\", type text}, {\"KPI Name PY\", type text}}),",
                "    #\"Inserted Merged Column\" = Table.AddColumn(#\"Changed Type\", \"Title\", each Text.Combine({[Choose KPI], \" Analysis\"}), type text)",
                "in",
                "    #\"Inserted Merged Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SalesOrganization",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesOrganizationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5162b249-813f-4fdc-bd79-b2abc5af0df0",
            "sourceColumn": "SalesOrganizationID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "744e8009-1179-4fdf-ba8f-8fe06b2c6419",
            "sourceColumn": "SalesOrganization",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganizationCurrency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "27e5c768-0785-44f3-b51a-601a3bdf1408",
            "sourceColumn": "SalesOrganizationCurrency",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14861842-0fe8-4a98-b5d0-c71cd5ffd488",
            "sourceColumn": "CompanyCode",
            "summarizeBy": "none"
          },
          {
            "name": "CountryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f68ba1c-211d-43ef-99d5-90c215f93ad2",
            "sourceColumn": "CountryID",
            "summarizeBy": "none"
          },
          {
            "name": "CountryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa37d5d7-4915-43fc-97e2-6df49bf530a6",
            "sourceColumn": "CountryName",
            "summarizeBy": "none"
          },
          {
            "name": "RegionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e41da18-6629-4381-95d2-5a06bff12ffd",
            "sourceColumn": "RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "RegionName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5cf6b90-ad9c-4632-94fc-43e117a6fb52",
            "sourceColumn": "RegionName",
            "summarizeBy": "none"
          },
          {
            "name": "Access_Control_Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0efc68c0-bdb5-42a9-8b1d-af5e2eb24403",
            "sourceColumn": "Access_Control_Unit",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7b471447-fac8-43c4-9fab-2fe38939ab28",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "f3af1450-fb40-4fee-ae9e-99cde39a7d50",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3d06306b-7d70-4f5d-b569-2215846a10d4",
        "partitions": [
          {
            "name": "SalesOrganization-d124955c-435d-4d5c-93b9-6ca29ec16469",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&Source&\"\", \"\"&DB&\"\"),",
                "    dm_sales_vw_dim_SalesOrganization = Source{[Schema=\"dm_finance\",Item=\"vw_dim_SalesOrganization\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_SalesOrganization"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SalesDistrict",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "SalesDistrictID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf0d9839-32d7-485c-af0e-295cc2f34f84",
            "sourceColumn": "SalesDistrictID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDistrict",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1db4ba99-f7d6-4d7e-9aaf-6049f5e209a6",
            "sourceColumn": "SalesDistrict",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "72f73e55-b438-44fa-8f4e-45eba3dad9c5",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4489824b-f974-4f44-9470-b656ba969aa3",
        "partitions": [
          {
            "name": "SalesDistrict-accbddad-f4df-4806-aadf-629cabaadeea",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&#\"Source\"&\"\", \"\"&#\"DB\"&\"\"),",
                "    dm_sales_vw_dim_SalesOrganization = Source{[Schema=\"dm_finance\",Item=\"vw_dim_SalesDistrict\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_SalesOrganization"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "GLAccount",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "ChartOfAccounts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d28f36c4-56b6-413d-b9c3-7bce99b9ac56",
            "sourceColumn": "ChartOfAccounts",
            "summarizeBy": "none"
          },
          {
            "name": "GLAccountID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98e8e10a-01b7-45c6-b43c-b2285865e9f8",
            "sourceColumn": "GLAccountID",
            "summarizeBy": "none"
          },
          {
            "name": "GLAccount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "edcca78d-3bc6-4327-9180-f0b4b06f133e",
            "sourceColumn": "GLAccount",
            "summarizeBy": "none"
          },
          {
            "name": "GLAccountLongName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "546827fd-e90f-42ae-a9ed-02d79cf3d26b",
            "sourceColumn": "GLAccountLongName",
            "summarizeBy": "none"
          },
          {
            "name": "LastChangeDateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fccbe0b3-0cdc-4270-ae0f-9562303debd5",
            "sourceColumn": "LastChangeDateTime",
            "summarizeBy": "sum"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5eb60fba-138d-437c-ab75-731ff21f252c",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "420a9b21-fdcb-4980-ac37-e1a32999bec0",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "glaccountID_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(GLAccount[GLAccountID],\" \"), GLAccount[GLAccount])",
            "isDataTypeInferred": true,
            "lineageTag": "6b492aff-e6a7-4c2e-82af-516bf5a59185",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "75e48071-f068-4c8e-bf56-80cb381a6292",
        "partitions": [
          {
            "name": "GLAccount-96da0f41-2748-4540-b91e-901a95e1382a",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&#\"Source\"&\"\", \"\"&#\"DB\"&\"\"),",
                "    dm_sales_vw_fact_BillingDocumentItem = Source{[Schema=\"dm_sales\",Item=\"vw_dim_GLAccountText\"]}[Data]",
                "in",
                "    dm_sales_vw_fact_BillingDocumentItem"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "srv_Cogs_cost",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Choose KPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "44d13032-8b4a-4d56-b50c-0eefd79ec123",
            "sourceColumn": "Choose KPI",
            "summarizeBy": "none"
          },
          {
            "name": "MeasureDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4a415914-fcd8-4024-8c13-6a44887339f9",
            "sourceColumn": "MeasureDescription",
            "summarizeBy": "none"
          },
          {
            "name": "KPI Name PY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "950f790d-0755-4d2d-8165-545ab52d880d",
            "sourceColumn": "KPI Name PY",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c864552b-6bb1-4faa-8822-4f15984fe576",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d53be231-4048-45d8-ac45-f6105d75996c",
            "sourceColumn": "Short",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "b24b47e3-3bf5-4ed2-9441-be44ace69e7d",
        "partitions": [
          {
            "name": "srv_Cogs_cost-a65e4cf1-3658-4876-917e-845dac7bd2ee",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcixRSEwuKU3MUUjOLy5R0lFy9ncPVoDRCgGRQKajc4hSrA5YbXFJYl5KYlEKiupEIsUhpgWHuCjFxgIA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Choose KPI\" = _t, MeasureDescription = _t, #\"KPI Name PY\" = _t, Short = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Choose KPI\", type text}, {\"MeasureDescription\", type text}, {\"KPI Name PY\", type text}}),",
                "    #\"Inserted Merged Column\" = Table.AddColumn(#\"Changed Type\", \"Title\", each Text.Combine({[Choose KPI], \" Analysis\"}), type text)",
                "in",
                "    #\"Inserted Merged Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "RLS_GROUPS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "GROUP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c3b67332-8798-4210-893c-454e55adabb2",
            "sourceColumn": "GROUP",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganizationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ffffb9de-4e32-4054-8813-6ff01c159303",
            "sourceColumn": "SalesOrganizationID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrg",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4d32d87a-f9fe-4aa4-9dce-d0e83ec591b9",
            "sourceColumn": "SalesOrg",
            "summarizeBy": "none"
          },
          {
            "name": "СompanyCodeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c32651eb-5493-4abd-9953-7f29eb86bb01",
            "sourceColumn": "СompanyCodeID",
            "summarizeBy": "none"
          },
          {
            "name": "PlantID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ae18a0b4-09c8-4211-8371-36d0addd52bc",
            "sourceColumn": "PlantID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8a8f2bb8-80f6-478b-b9d2-6ad6504aef1f",
        "partitions": [
          {
            "name": "RLS_GROUPS-4ff76762-72b3-46ca-b344-e72487125e2e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://crhemea.sharepoint.com/sites/crh-group-cs-dataandanalyti-0010_DevOps/Shared%20Documents/0010_DevOps/RLS/RLS_assignmnts.xlsx\"), null, true),",
                "    RLS_GROUPS_Sheet = Source{[Item=\"RLS_GROUPS\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(RLS_GROUPS_Sheet, [PromoteAllScalars=true])",
                "in",
                "    #\"Promoted Headers\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "RLS_USERS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "USER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5462ac1d-542f-4ecb-b61e-3a9e3f5a3f01",
            "sourceColumn": "USER",
            "summarizeBy": "none"
          },
          {
            "name": "GROUP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f97edc9f-3aaf-4061-b3e6-be8027e8b49a",
            "sourceColumn": "GROUP",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ca4af54c-bd2a-4c46-9223-e3cb0b74043f",
        "partitions": [
          {
            "name": "RLS_USERS-473c886b-f8ad-4c1b-9074-04db5254a830",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://crhemea.sharepoint.com/sites/crh-group-cs-dataandanalyti-0010_DevOps/Shared%20Documents/0010_DevOps/RLS/RLS_assignmnts.xlsx\"), null, true),",
                "    RLS_USERS_Sheet = Source{[Item=\"RLS_USERS\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(RLS_USERS_Sheet, [PromoteAllScalars=true])",
                "in",
                "    #\"Promoted Headers\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ExQLReportingEntity",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ExQLReportingEntity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b48df20d-6e89-4e0a-86c5-829ac148ed60",
            "sourceColumn": "ExQLReportingEntity",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a070344f-2eb0-4c2b-b33b-8fece1073b1c",
        "partitions": [
          {
            "name": "ExQLReportingEntity-d1f422c2-c34c-4fcc-9f28-454155805f23",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_finance_vw_dim_ExQLReportingEntity = Source{[Schema=\"dm_finance\",Item=\"vw_dim_ExQLReportingEntity\"]}[Data]",
                "in",
                "    dm_finance_vw_dim_ExQLReportingEntity"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "exQL_Map",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "nk_ExQLmap",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0949bb73-0e0a-46b8-a8cb-6ff308516fe3",
            "sourceColumn": "nk_ExQLmap",
            "summarizeBy": "none"
          },
          {
            "name": "GLAccountID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "21cbef86-42fe-452f-8226-451bc8ea789d",
            "sourceColumn": "GLAccountID",
            "summarizeBy": "none"
          },
          {
            "name": "FunctionalAreaID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e02e7df3-1b06-41b6-83ad-c95be9eb4f77",
            "sourceColumn": "FunctionalAreaID",
            "summarizeBy": "none"
          },
          {
            "name": "ExQLNode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf97664a-8c7f-4aad-b1d3-6c3e69e68501",
            "sourceColumn": "ExQLNode",
            "summarizeBy": "none"
          },
          {
            "name": "ExQLAccount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9a38ebc-65b9-4efa-9ebd-51cfb4595ed7",
            "sourceColumn": "ExQLAccount",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2f91346d-b803-4547-a33d-0f6e3e161ede",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_jobDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "f8e8887b-7029-422e-ba3d-c58f18a31c93",
            "sourceColumn": "t_jobDtm",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "e2d34500-b387-47ad-b431-d9e4cc97a828",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4c50a867-1bae-493c-a484-b80a1880b9e8",
        "partitions": [
          {
            "name": "exQL_Map-4e04c11e-045f-48d8-8b84-079c9df54404",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&#\"Source\"&\"\", \"\"&#\"DB\"&\"\"),",
                "    dm_sales_vw_fact_BillingDocumentItem = Source{[Schema=\"dm_finance\",Item=\"vw_dim_ZE_EXQLMAP_DT\"]}[Data]",
                "in",
                "    dm_sales_vw_fact_BillingDocumentItem"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CompanyCode",
        "columns": [
          {
            "name": "CompanyCodeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77083303-be8d-4fde-b680-03e8e23dfbfb",
            "sourceColumn": "CompanyCodeID",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1f65fd7-f147-4b34-b813-a008589fce4d",
            "sourceColumn": "CompanyCode",
            "summarizeBy": "none"
          },
          {
            "name": "CityName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf7331b4-4bc9-465c-bf7d-07b3c2a88f85",
            "sourceColumn": "CityName",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a081be6b-f985-42fa-a23f-40556723a99d",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "CountryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70b94138-71a9-4ccb-9271-98fed4b62738",
            "sourceColumn": "CountryName",
            "summarizeBy": "none"
          },
          {
            "name": "Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "226dab70-e98b-4036-98a3-993097a8ecfd",
            "sourceColumn": "Currency",
            "summarizeBy": "none"
          },
          {
            "name": "ChartOfAccounts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee773557-3042-47ea-a3cb-a2007eee1431",
            "sourceColumn": "ChartOfAccounts",
            "summarizeBy": "none"
          },
          {
            "name": "Company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfbfd9fe-51e7-42c0-8cbf-493a34709aa9",
            "sourceColumn": "Company",
            "summarizeBy": "none"
          },
          {
            "name": "CashDiscountBaseAmtIsNetAmt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5258920a-88f4-4482-a2b3-9da5533c05c9",
            "sourceColumn": "CashDiscountBaseAmtIsNetAmt",
            "summarizeBy": "none"
          },
          {
            "name": "RegionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b428450c-810d-4559-b9e3-b2e28351bcde",
            "sourceColumn": "RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92a55a1e-1426-4175-a580-a9af08471764",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "t_jobDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d75d80c1-e25f-42a4-af0e-f5d135f9c5f8",
            "sourceColumn": "t_jobDtm",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyCodeDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a58fbd50-2162-4be0-9af0-8942f461081a",
            "sourceColumn": "CompanyCodeDescription",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a74996f9-43ea-4cff-bdb3-e0620eb83507",
        "partitions": [
          {
            "name": "CompanyCode-b6039867-5db3-4b82-942b-d04d0c6d6d22",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_dim_CompanyCode = Source{[Schema=\"dm_sales\",Item=\"vw_dim_CompanyCode\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_CompanyCode"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}