{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.2028.0 (23.12)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"MaterialStockLevel\",\"Calendar\",\"Customer\",\"Product\",\"SalesOrganization\",\"_Measures\",\"MaterialDocumentItem\",\"srv_TopFlop\",\"StorageLocation\",\"Plant\",\"UnitOfMeasure\",\"InventoryStockType\",\"InventorySpecialStockType\",\"BucketOrder\",\"srv_SelectKPI\",\"Currency\",\"ProductValuationPUP\",\"Source\",\"DB\",\"OrderItem\",\"dimProductCalculated\",\"dim_Application_manual\",\"srv_SlicerZero\",\"RangeStart\",\"RangeEnd\",\"ProductPlant\",\"ProductSalesDelivery\",\"ProductSalesThirdPartyDelivery\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "__BNorm",
        "value": "1"
      },
      {
        "name": "__LastRPTime",
        "value": "133524624840427971"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Source",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"ws-xxxx-sls-a-euw-001.sql.azuresynapse.net\" meta [IsParameterQuery=true, List={\"ws-xxxx-sls-p-euw-001.sql.azuresynapse.net\", \"ws-xxxx-sls-a-euw-001.sql.azuresynapse.net\", \"ws-xxxx-sls-d-euw-001.sql.azuresynapse.net\"}, DefaultValue=\"ws-xxxx-sls-p-euw-001.sql.azuresynapse.net\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "9c513671-d787-4eb3-8534-d7dc16836c0b"
      },
      {
        "name": "DB",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"syndw_xxxx_sls_a_euw_001\" meta [IsParameterQuery=true, List={\"syndw_xxxx_sls_p_euw_001\", \"syndw_xxxx_sls_a_euw_001\", \"syndw_xxxx_sls_d_euw_001\", \"syndw_nkukhtenko_d_euw_001\"}, DefaultValue=\"syndw_xxxx_sls_p_euw_001\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "80ea4060-0f75-4d4b-b547-6420f0651d33"
      },
      {
        "name": "RangeStart",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": "#datetime(2022, 1, 1, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "5bc65474-652b-4622-947b-244e5643e2e1"
      },
      {
        "name": "RangeEnd",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": "#datetime(2026, 1, 1, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "af7093b5-7e19-4b90-802b-6fce181965c7"
      }
    ],
    "perspectives": [
      {
        "name": "Default",
        "tables": [
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Date"
              },
              {
                "name": "Year"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "MonthNumber"
              },
              {
                "name": "Month"
              },
              {
                "name": "Week"
              },
              {
                "name": "Day"
              },
              {
                "name": "YearMonth"
              },
              {
                "name": "YearQuarter"
              },
              {
                "name": "YearWeek"
              },
              {
                "name": "WeekDay"
              },
              {
                "name": "FirstDayOfWeekDate"
              },
              {
                "name": "FirstDayOfMonthDate"
              },
              {
                "name": "CalendarDayOfYear"
              },
              {
                "name": "YearDay"
              },
              {
                "name": "MonthName"
              },
              {
                "name": "MonthName_Year"
              },
              {
                "name": "Month_Name_Short"
              },
              {
                "name": "12MonthFilter"
              },
              {
                "name": "6MonthFilter"
              }
            ]
          },
          {
            "name": "MaterialStockLevel",
            "columns": [
              {
                "name": "MaterialID"
              },
              {
                "name": "PlantID"
              },
              {
                "name": "StorageLocationID"
              },
              {
                "name": "InventorySpecialStockTypeID"
              },
              {
                "name": "InventoryStockTypeID"
              },
              {
                "name": "StockOwner"
              },
              {
                "name": "MaterialBaseUnitID"
              },
              {
                "name": "CostCenterID"
              },
              {
                "name": "CompanyCodeID"
              },
              {
                "name": "SalesDocumentTypeID"
              },
              {
                "name": "ReportingYear"
              },
              {
                "name": "ReportingMonth"
              },
              {
                "name": "ReportingDate"
              },
              {
                "name": "SalesDocumentItemCategoryID"
              },
              {
                "name": "PurchaseOrderTypeID"
              },
              {
                "name": "MatlStkChangeQtyInBaseUnit"
              },
              {
                "name": "StockLevelQtyInBaseUnit"
              },
              {
                "name": "Bucket"
              },
              {
                "name": "MonthDiff"
              },
              {
                "name": "MaxDate"
              },
              {
                "name": "StockLevel"
              },
              {
                "name": "StockLevelStandardPPU"
              },
              {
                "name": "StockLevelStandardPPU_EUR"
              }
            ]
          },
          {
            "name": "Product",
            "columns": [
              {
                "name": "ProductID"
              },
              {
                "name": "ProductExternalID"
              },
              {
                "name": "Product"
              },
              {
                "name": "ProductID_Name"
              },
              {
                "name": "MaterialTypeID"
              },
              {
                "name": "MaterialType"
              },
              {
                "name": "IsMarkedForDeletion"
              },
              {
                "name": "CrossPlantStatus"
              },
              {
                "name": "GrossWeight"
              },
              {
                "name": "SourceOfSupply"
              },
              {
                "name": "CountryOfOrigin"
              },
              {
                "name": "CompetitorID"
              },
              {
                "name": "MaterialGroup"
              },
              {
                "name": "BaseUnit"
              },
              {
                "name": "ItemCategoryGroup"
              },
              {
                "name": "ProductHierarchy"
              },
              {
                "name": "Product_L1_PillarID"
              },
              {
                "name": "Product_L2_GroupID"
              },
              {
                "name": "Product_L3_TypeID"
              },
              {
                "name": "Product_L4_FamilyID"
              },
              {
                "name": "Product_L5_SubFamilyID"
              },
              {
                "name": "Product_L1_Pillar"
              },
              {
                "name": "Product_L2_Group"
              },
              {
                "name": "Product_L3_Type"
              },
              {
                "name": "Product_L4_Family"
              },
              {
                "name": "Product_L5_SubFamily"
              },
              {
                "name": "ProductCategory"
              },
              {
                "name": "Brand"
              },
              {
                "name": "IndustryStandardName"
              },
              {
                "name": "ProductStandardID"
              },
              {
                "name": "InternationalArticleNumberCat"
              },
              {
                "name": "ProductIsConfigurable"
              },
              {
                "name": "IsBatchManagementRequired"
              },
              {
                "name": "ExternalProductGroup"
              },
              {
                "name": "CrossPlantConfigurableProduct"
              },
              {
                "name": "ProductManufacturerNumber"
              },
              {
                "name": "ManufacturerNumber"
              },
              {
                "name": "MaximumPackagingLength"
              },
              {
                "name": "MaximumPackagingWidth"
              },
              {
                "name": "MaximumPackagingHeight"
              },
              {
                "name": "MaximumCapacity"
              },
              {
                "name": "OvercapacityTolerance"
              },
              {
                "name": "UnitForMaxPackagingDimensions"
              },
              {
                "name": "BaseUnitSpecificProductLength"
              },
              {
                "name": "BaseUnitSpecificProductWidth"
              },
              {
                "name": "BaseUnitSpecificProductHeight"
              },
              {
                "name": "ArticleCategory"
              },
              {
                "name": "ProductIsLocked"
              },
              {
                "name": "BasicMaterial"
              },
              {
                "name": "SalesProduct"
              },
              {
                "name": "ZZ1_CustomFieldRiskMit_PRD"
              },
              {
                "name": "ZZ1_CustomFieldHighRis_PRD"
              },
              {
                "name": "ZZ1_CustomFieldRiskRea_PRD"
              },
              {
                "name": "t_jobDtm"
              },
              {
                "name": "t_applicationId"
              },
              {
                "name": "t_extractionDtm"
              },
              {
                "name": "Bucket"
              },
              {
                "name": "BucketOrder"
              },
              {
                "name": "sk_dim_Product"
              },
              {
                "name": "ProductID_Name_"
              },
              {
                "name": "Test_id"
              }
            ],
            "hierarchies": [
              {
                "name": "Product Hierarchy"
              }
            ]
          },
          {
            "name": "Plant",
            "columns": [
              {
                "name": "PlantID"
              },
              {
                "name": "Plant"
              },
              {
                "name": "ValuationArea"
              },
              {
                "name": "PlantCustomer"
              },
              {
                "name": "PlantSupplier"
              },
              {
                "name": "FactoryCalendar"
              },
              {
                "name": "DefaultPurchasingOrganization"
              },
              {
                "name": "SalesOrganizationID"
              },
              {
                "name": "SalesOrganization"
              },
              {
                "name": "AddressID"
              },
              {
                "name": "SalesOrg_CountryID"
              },
              {
                "name": "SalesOrg_Country"
              },
              {
                "name": "SalesOrg_RegionID"
              },
              {
                "name": "SalesOrg_Region"
              },
              {
                "name": "PlantCategory"
              },
              {
                "name": "DistributionChannel"
              },
              {
                "name": "Division"
              },
              {
                "name": "t_applicationId"
              },
              {
                "name": "t_extractionDtm"
              }
            ]
          },
          {
            "name": "_Measures",
            "measures": [
              {
                "name": "StockQuantity"
              },
              {
                "name": "ConsumptionQuantity"
              }
            ]
          },
          {
            "name": "ProductSalesDelivery",
            "columns": [
              {
                "name": "ItemCategoryGroup"
              },
              {
                "name": "ItemCategoryGroupName"
              }
            ]
          }
        ]
      },
      {
        "name": "Limited",
        "tables": [
          {
            "name": "MaterialStockLevel",
            "columns": [
              {
                "name": "MaterialID"
              },
              {
                "name": "PlantID"
              },
              {
                "name": "StorageLocationID"
              },
              {
                "name": "InventorySpecialStockTypeID"
              },
              {
                "name": "InventoryStockTypeID"
              },
              {
                "name": "StockOwner"
              },
              {
                "name": "MaterialBaseUnitID"
              },
              {
                "name": "CostCenterID"
              },
              {
                "name": "CompanyCodeID"
              },
              {
                "name": "SalesDocumentTypeID"
              },
              {
                "name": "ReportingYear"
              },
              {
                "name": "ReportingMonth"
              },
              {
                "name": "ReportingDate"
              },
              {
                "name": "SalesDocumentItemCategoryID"
              },
              {
                "name": "PurchaseOrderTypeID"
              },
              {
                "name": "MatlStkChangeQtyInBaseUnit"
              },
              {
                "name": "StockLevelQtyInBaseUnit"
              },
              {
                "name": "Bucket"
              },
              {
                "name": "MonthDiff"
              },
              {
                "name": "MaxDate"
              },
              {
                "name": "StockLevel"
              },
              {
                "name": "StockLevelStandardPPU"
              },
              {
                "name": "StockLevelStandardPPU_EUR"
              }
            ]
          },
          {
            "name": "ProductSalesDelivery",
            "columns": [
              {
                "name": "ItemCategoryGroup"
              },
              {
                "name": "ItemCategoryGroupName"
              }
            ]
          }
        ]
      },
      {
        "name": "Consumption Analysis",
        "tables": [
          {
            "name": "UnitOfMeasure",
            "columns": [
              {
                "name": "UnitOfMeasure"
              },
              {
                "name": "UnitOfMeasureID"
              },
              {
                "name": "UnitOfMeasureLongName"
              }
            ]
          },
          {
            "name": "SalesOrganization",
            "columns": [
              {
                "name": "CountryID"
              },
              {
                "name": "CountryName"
              },
              {
                "name": "RegionID"
              },
              {
                "name": "RegionName"
              },
              {
                "name": "SalesOrganization"
              },
              {
                "name": "SalesOrganizationID"
              }
            ]
          },
          {
            "name": "StorageLocation",
            "columns": [
              {
                "name": "DistributionChannel"
              },
              {
                "name": "Plant"
              },
              {
                "name": "SalesOrganization"
              },
              {
                "name": "StorageLocation"
              },
              {
                "name": "SalesOrganizationID"
              },
              {
                "name": "StorageLocationID"
              }
            ]
          },
          {
            "name": "Plant",
            "columns": [
              {
                "name": "Plant"
              },
              {
                "name": "PlantID"
              },
              {
                "name": "SalesOrganization"
              },
              {
                "name": "SalesOrganizationID"
              },
              {
                "name": "ValuationArea"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "MonthName"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "Year"
              }
            ]
          },
          {
            "name": "Product",
            "columns": [
              {
                "name": "CreatedByUser"
              },
              {
                "name": "CreationDate"
              },
              {
                "name": "CrossPlantStatus"
              },
              {
                "name": "GrossWeight"
              },
              {
                "name": "IsMarkedForDeletion"
              },
              {
                "name": "ItemCategoryGroup"
              },
              {
                "name": "MaterialType"
              },
              {
                "name": "MaterialTypeID"
              },
              {
                "name": "NetWeight"
              },
              {
                "name": "Product"
              },
              {
                "name": "Product_L1_Pillar"
              },
              {
                "name": "Product_L1_PillarID"
              },
              {
                "name": "Product_L2_Group"
              },
              {
                "name": "Product_L2_GroupID"
              },
              {
                "name": "Product_L3_Type"
              },
              {
                "name": "Product_L3_TypeID"
              },
              {
                "name": "Product_L4_Family"
              },
              {
                "name": "Product_L4_FamilyID"
              },
              {
                "name": "Product_L5_SubFamily"
              },
              {
                "name": "Product_L5_SubFamilyID"
              },
              {
                "name": "ProductExternalID"
              },
              {
                "name": "ProductHierarchy"
              },
              {
                "name": "WeightUnit"
              }
            ]
          },
          {
            "name": "MaterialStockLevel",
            "columns": [
              {
                "name": "CompanyCodeID"
              },
              {
                "name": "InventorySpecialStockTypeID"
              },
              {
                "name": "InventoryStockTypeID"
              },
              {
                "name": "LatestPricePerPiece_EUR"
              },
              {
                "name": "LatestPricePerPiece_Local"
              },
              {
                "name": "LatestPricePerPiece_USD"
              },
              {
                "name": "MaterialBaseUnitID"
              },
              {
                "name": "MaterialID"
              },
              {
                "name": "MatlStkChangeQtyInBaseUnit"
              },
              {
                "name": "PlantID"
              },
              {
                "name": "Prev12MConsumptionQty"
              },
              {
                "name": "ReportingDate"
              },
              {
                "name": "ReportingMonth"
              },
              {
                "name": "ReportingYear"
              },
              {
                "name": "StockLevelQtyInBaseUnit"
              },
              {
                "name": "StockLevelStandardLastPPU"
              },
              {
                "name": "StockLevelStandardLastPPU_EUR"
              },
              {
                "name": "StockLevelStandardLastPPU_USD"
              },
              {
                "name": "StorageLocationID"
              }
            ]
          },
          {
            "name": "ProductPlant",
            "columns": [
              {
                "name": "ABCIndicator"
              },
              {
                "name": "Commodity"
              },
              {
                "name": "IsActiveEntity"
              },
              {
                "name": "MaximumLotSizeQuantity"
              },
              {
                "name": "MinimumLotSizeQuantity"
              },
              {
                "name": "FixedLotSizeQuantity"
              },
              {
                "name": "MRPController"
              },
              {
                "name": "MRPResponsible"
              },
              {
                "name": "MRPType"
              },
              {
                "name": "PlannedDeliveryDurationInDays"
              },
              {
                "name": "Plant"
              },
              {
                "name": "ProcurementType"
              },
              {
                "name": "Product"
              },
              {
                "name": "ProfitCenter"
              },
              {
                "name": "Re-Order Point"
              },
              {
                "name": "Rounding Value"
              },
              {
                "name": "SafetyStockQuantity"
              },
              {
                "name": "SpecialProcurementType"
              }
            ]
          },
          {
            "name": "ProductSalesDelivery",
            "columns": [
              {
                "name": "ItemCategoryGroup"
              },
              {
                "name": "ItemCategoryGroupName"
              }
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "be71b2df-814c-42c9-894a-2d65447f786a",
        "fromColumn": "DocumentDate",
        "fromTable": "MaterialDocumentItem",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "af0ec094-c5e7-4c11-8906-7be238f9a831",
        "fromColumn": "PlantID",
        "fromTable": "MaterialStockLevel",
        "toColumn": "PlantID",
        "toTable": "Plant"
      },
      {
        "name": "f739ffd7-b896-4f48-ba28-4b6610c320b4",
        "fromColumn": "PlantID",
        "fromTable": "MaterialDocumentItem",
        "toColumn": "PlantID",
        "toTable": "Plant"
      },
      {
        "name": "5e069204-3dda-4a2e-88d4-4eb7b7492b07",
        "fromColumn": "InventoryStockTypeID",
        "fromTable": "MaterialStockLevel",
        "toColumn": "InventoryStockTypeID",
        "toTable": "InventoryStockType"
      },
      {
        "name": "f41f5d6a-1af8-4643-ab92-a76ba224efa3",
        "fromColumn": "InventoryStockTypeID",
        "fromTable": "MaterialDocumentItem",
        "toColumn": "InventoryStockTypeID",
        "toTable": "InventoryStockType"
      },
      {
        "name": "551ecb17-387f-455a-a11b-b72d9a4950eb",
        "fromColumn": "InventorySpecialStockTypeID",
        "fromTable": "MaterialDocumentItem",
        "toColumn": "InventorySpecialStockTypeID",
        "toTable": "InventorySpecialStockType"
      },
      {
        "name": "2020982b-87e3-4c2d-963f-40988f4c4d8b",
        "fromColumn": "InventorySpecialStockTypeID",
        "fromTable": "MaterialStockLevel",
        "toColumn": "InventorySpecialStockTypeID",
        "toTable": "InventorySpecialStockType"
      },
      {
        "name": "f62c01e8-9726-446d-8c77-e1cf5db2c21f",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "MaterialBaseUnitID",
        "fromTable": "MaterialDocumentItem",
        "toColumn": "UnitOfMeasureID",
        "toTable": "UnitOfMeasure"
      },
      {
        "name": "236c4231-bd9c-4a11-97a0-6781ee536de1",
        "fromColumn": "MaterialBaseUnitID",
        "fromTable": "MaterialStockLevel",
        "toColumn": "UnitOfMeasureID",
        "toTable": "UnitOfMeasure"
      },
      {
        "name": "7e1907a2-d91e-40f5-bb75-47fe9e42d42a",
        "fromColumn": "ProductID",
        "fromTable": "ProductValuationPUP",
        "toColumn": "ProductID",
        "toTable": "Product"
      },
      {
        "name": "32bd78fa-045d-44fc-b148-102e5c3ded75",
        "fromColumn": "SalesOrganizationID",
        "fromTable": "OrderItem",
        "toColumn": "SalesOrganizationID",
        "toTable": "SalesOrganization"
      },
      {
        "name": "92c08f22-dc21-4af4-9a87-59577a6fbcb5",
        "fromColumn": "CurrencyType",
        "fromTable": "OrderItem",
        "toColumn": "CurrencyType",
        "toTable": "Currency"
      },
      {
        "name": "253b7a5d-9ce5-4583-baeb-2725ee63833b",
        "fromColumn": "MaterialID",
        "fromTable": "OrderItem",
        "toColumn": "ProductID",
        "toTable": "Product"
      },
      {
        "name": "37f4f356-05c2-410a-9dc8-913b4598514c",
        "fromColumn": "Date",
        "fromTable": "ProductValuationPUP",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "1ed16524-c5a4-47c8-9574-48a0d64eba9a",
        "fromColumn": "MaterialID",
        "fromTable": "MaterialDocumentItem",
        "toColumn": "ProductIDCalculated",
        "toTable": "dimProductCalculated"
      },
      {
        "name": "1a261fa6-8c70-420a-a7d4-08d217504d2f",
        "fromColumn": "MaterialID",
        "fromTable": "MaterialStockLevel",
        "toColumn": "ProductIDCalculated",
        "toTable": "dimProductCalculated"
      },
      {
        "name": "f8de972b-d0ed-4085-ac9d-53a6de9e669a",
        "fromColumn": "MaterialID",
        "fromTable": "OrderItem",
        "toColumn": "ProductIDCalculated",
        "toTable": "dimProductCalculated"
      },
      {
        "name": "ee99ba18-1167-474a-b3c9-e78eb368fcb5",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ValuationAreaID",
        "fromTable": "ProductValuationPUP",
        "isActive": false,
        "toCardinality": "many",
        "toColumn": "PlantID",
        "toTable": "MaterialDocumentItem"
      },
      {
        "name": "cd498797-926b-43e7-b809-fabdb94f0128",
        "fromColumn": "ValuationAreaID",
        "fromTable": "ProductValuationPUP",
        "toColumn": "PlantID",
        "toTable": "Plant"
      },
      {
        "name": "295da43d-2bc1-4d66-b9ca-b872f413d05c",
        "fromColumn": "ReportingDate",
        "fromTable": "MaterialStockLevel",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "1738958b-f32f-46d9-81c2-dadc233996fc",
        "fromColumn": "ProductID",
        "fromTable": "ProductValuationPUP",
        "toColumn": "ProductIDCalculated",
        "toTable": "dimProductCalculated"
      },
      {
        "name": "75dc63fa-ce48-48a9-b9a3-29eab71bf1a5",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "ProductIDCalculated",
        "fromTable": "dimProductCalculated",
        "isActive": false,
        "toColumn": "ProductID",
        "toTable": "Product"
      },
      {
        "name": "6051766d-631d-4794-a962-6a3270389491",
        "fromColumn": "t_applicationId",
        "fromTable": "MaterialStockLevel",
        "toColumn": "t_application_id",
        "toTable": "dim_Application_manual"
      },
      {
        "name": "0686cfd6-35ff-4d3a-a497-a764e164f4aa",
        "fromColumn": "t_applicationId",
        "fromTable": "Customer",
        "toColumn": "t_application_id",
        "toTable": "dim_Application_manual"
      },
      {
        "name": "0a0e856a-e54b-43e5-a40a-eb8c20d3dafe",
        "fromColumn": "t_applicationId",
        "fromTable": "Product",
        "isActive": false,
        "toColumn": "t_application_id",
        "toTable": "dim_Application_manual"
      },
      {
        "name": "1a98de98-f4ef-4ced-a2c2-dc2abc77d01d",
        "fromColumn": "t_applicationId",
        "fromTable": "MaterialDocumentItem",
        "toColumn": "t_application_id",
        "toTable": "dim_Application_manual"
      },
      {
        "name": "7ac64192-ac38-4646-9926-f46d28198ffa",
        "fromColumn": "t_applicationId",
        "fromTable": "StorageLocation",
        "isActive": false,
        "toColumn": "t_application_id",
        "toTable": "dim_Application_manual"
      },
      {
        "name": "17c19edb-ae4b-434c-88cd-2424f4e017db",
        "fromColumn": "t_applicationId",
        "fromTable": "InventoryStockType",
        "isActive": false,
        "toColumn": "t_application_id",
        "toTable": "dim_Application_manual"
      },
      {
        "name": "a202e134-b9c2-4a47-a485-55e1616ed79f",
        "fromColumn": "t_applicationId",
        "fromTable": "InventorySpecialStockType",
        "isActive": false,
        "toColumn": "t_application_id",
        "toTable": "dim_Application_manual"
      },
      {
        "name": "11ddd87a-5648-4e29-9220-acb90060ac63",
        "fromColumn": "t_applicationId",
        "fromTable": "OrderItem",
        "toColumn": "t_application_id",
        "toTable": "dim_Application_manual"
      },
      {
        "name": "5a30e259-22d3-461b-9f60-e7f6cbf52598",
        "fromColumn": "Bucket",
        "fromTable": "Product",
        "toColumn": "Bucket",
        "toTable": "BucketOrder"
      },
      {
        "name": "5e9db3c4-41c7-4c8c-8053-dbfae14ef22f",
        "fromColumn": "t_applicationId",
        "fromTable": "ProductPlant",
        "toColumn": "t_application_id",
        "toTable": "dim_Application_manual"
      },
      {
        "name": "3fd79c00-a51f-446b-9d8a-2e9f6371df71",
        "fromColumn": "Plant",
        "fromTable": "ProductPlant",
        "toColumn": "PlantID",
        "toTable": "Plant"
      },
      {
        "name": "a168785f-4455-4b21-8e23-494f7bd0ffd5",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Product",
        "fromTable": "ProductPlant",
        "toColumn": "ProductID",
        "toTable": "Product"
      },
      {
        "name": "932ef8ad-c558-b0ce-09dd-739496d0da23",
        "fromColumn": "nk_StoragePlantID",
        "fromTable": "MaterialStockLevel",
        "toColumn": "nk_StoragePlantID",
        "toTable": "StorageLocation"
      },
      {
        "name": "6b097ee2-d6e5-49d9-1b69-e0f7b974172d",
        "fromColumn": "nk_StoragePlantID",
        "fromTable": "MaterialDocumentItem",
        "toColumn": "nk_StoragePlantID",
        "toTable": "StorageLocation"
      },
      {
        "name": "118bd372-5d1a-44a2-b911-95698d879e24",
        "fromColumn": "SalesOrganizationID",
        "fromTable": "ProductSalesDelivery",
        "toColumn": "SalesOrganizationID",
        "toTable": "SalesOrganization"
      },
      {
        "name": "20707149-95f1-4c6b-9e8f-0c0660bda9c0",
        "fromColumn": "Commodity",
        "fromTable": "ProductPlant",
        "isActive": false,
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "fa810a74-dc67-40cb-902a-3063630eec1b",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "MaterialID",
        "fromTable": "MaterialStockLevel",
        "isActive": false,
        "toCardinality": "many",
        "toColumn": "MaterialID",
        "toTable": "MaterialDocumentItem"
      },
      {
        "name": "63357dad-84ec-406a-9a1c-baaab9a66abe",
        "fromColumn": "t_applicationId",
        "fromTable": "ProductSalesDelivery",
        "isActive": false,
        "toColumn": "t_application_id",
        "toTable": "dim_Application_manual"
      },
      {
        "name": "8078bb85-92a7-4e48-ad4f-b0e9ab528533",
        "fromColumn": "t_applicationId",
        "fromTable": "ProductSalesThirdPartyDelivery",
        "isActive": false,
        "toColumn": "t_application_id",
        "toTable": "dim_Application_manual"
      },
      {
        "name": "3e61fd39-bd13-42c0-b49f-72afbea939f2",
        "fromColumn": "sk_ProductSalesOrg",
        "fromTable": "MaterialStockLevel",
        "toColumn": "sk_ProductSalesOrg",
        "toTable": "ProductSalesThirdPartyDelivery"
      },
      {
        "name": "3ed85a95-083c-4802-b0db-5d97f38e8f9b",
        "fromColumn": "sk_ProductSalesOrg",
        "fromTable": "MaterialDocumentItem",
        "toColumn": "sk_ProductSalesOrg",
        "toTable": "ProductSalesThirdPartyDelivery"
      },
      {
        "name": "1c0d0f16-95d0-4a91-8e81-8457de880af8",
        "fromColumn": "ProductID",
        "fromTable": "ProductSalesThirdPartyDelivery",
        "isActive": false,
        "toColumn": "ProductID",
        "toTable": "Product"
      },
      {
        "name": "afdb177c-9fb8-4386-99bf-88186ac84640",
        "fromColumn": "SalesOrganizationID",
        "fromTable": "ProductSalesThirdPartyDelivery",
        "isActive": false,
        "toColumn": "SalesOrganizationID",
        "toTable": "SalesOrganization"
      },
      {
        "name": "9399ea4f-a502-f858-ecb5-1cce6a038168",
        "fromColumn": "MaterialID",
        "fromTable": "MaterialDocumentItem",
        "toColumn": "ProductID",
        "toTable": "Product"
      },
      {
        "name": "af3f8937-5f7b-db03-4453-4d14ce7fe5b6",
        "fromColumn": "MaterialID",
        "fromTable": "MaterialStockLevel",
        "toColumn": "ProductID",
        "toTable": "Product"
      },
      {
        "name": "1429cf91-c972-5382-5015-f61d5920fbe4",
        "fromColumn": "sk_ProductSalesOrg",
        "fromTable": "MaterialStockLevel",
        "toColumn": "sk_ProductSalesDelivery",
        "toTable": "ProductSalesDelivery"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "MaterialStockLevel",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "MaterialID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "8670f595-fd9e-4637-8190-ee9027ae7c4e",
            "sortByColumn": "StockLevelQtyInBaseUnit",
            "sourceColumn": "MaterialID",
            "summarizeBy": "none"
          },
          {
            "name": "PlantID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79d2714b-9ff2-49b2-bc87-8779bb868dfc",
            "sourceColumn": "PlantID",
            "summarizeBy": "none"
          },
          {
            "name": "StorageLocationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e88d7c50-1fc3-4209-a1b5-ec554fc351d2",
            "sourceColumn": "StorageLocationID",
            "summarizeBy": "none"
          },
          {
            "name": "InventorySpecialStockTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bba7db4e-e66c-48a9-a812-5ad7c7414c6b",
            "sourceColumn": "InventorySpecialStockTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "InventoryStockTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "49315088-ab68-4f8c-9960-9b6c29c0afe9",
            "sourceColumn": "InventoryStockTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "StockOwner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a10832f-abc2-42ba-a51e-d85fe0afd2ee",
            "sourceColumn": "StockOwner",
            "summarizeBy": "none"
          },
          {
            "name": "MaterialBaseUnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ce0c4dd-a7b5-4c2c-ab25-7d49380f0232",
            "sourceColumn": "MaterialBaseUnitID",
            "summarizeBy": "none"
          },
          {
            "name": "CostCenterID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6839f46b-9edf-4e99-89af-bec93b8808ed",
            "sourceColumn": "CostCenterID",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyCodeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e04705d-5acc-478c-98ad-0b5ac650a2eb",
            "sourceColumn": "CompanyCodeID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDocumentTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d5ad7a11-949e-4b5c-bb18-a485b9551a3a",
            "sourceColumn": "SalesDocumentTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "ReportingYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9cb71553-0494-453e-8431-eea1adc6c510",
            "sourceColumn": "ReportingYear",
            "summarizeBy": "none"
          },
          {
            "name": "ReportingMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc7aec36-d9ba-4af0-8510-ace40ec5270e",
            "sourceColumn": "ReportingMonth",
            "summarizeBy": "none"
          },
          {
            "name": "ReportingDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mmmm yyyy",
            "lineageTag": "9c8a08c5-ea1d-439e-9706-7957eec96e51",
            "sourceColumn": "ReportingDate",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDocumentItemCategoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f75e661f-3b59-48bf-acd4-61f6960e3a2f",
            "sourceColumn": "SalesDocumentItemCategoryID",
            "summarizeBy": "none"
          },
          {
            "name": "PurchaseOrderTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc481b3c-7536-469c-9efd-310ed6ada6b1",
            "sourceColumn": "PurchaseOrderTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "MatlStkChangeQtyInBaseUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d51175fb-6a42-4957-a855-f14e514fb8ee",
            "sourceColumn": "MatlStkChangeQtyInBaseUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "StockLevelQtyInBaseUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e08c44d2-8b22-430c-8558-fe258462a9db",
            "sourceColumn": "StockLevelQtyInBaseUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "VAR remain = [MSL Remaining2]",
              "--[StockRemaining2]",
              "VAR consumption = [MSL Consumption12M]",
              "--[ConsumptionQuantity12M] ",
              "VAR stklvl = [QtyLatest]",
              "--[StockQuantityToDate] ",
              "RETURN",
              "",
              "if(NOT(ISBLANK(consumption)),",
              "//07/08/23",
              "    --if (consumption = 0.00, \"0) No movement\",",
              "        if (and(stklvl>0, remain < 3), \"0) <3 months\",",
              "            if(and(remain >=3, remain<6), \"1) 3-6 month\", ",
              "                if(and(remain >=6, remain<12), \"2) 6-12 month\", ",
              "                    if(and(remain >= 12, remain <18), \"3) 12-18 month\", ",
              "                        if(and(remain >= 18, remain <24), \"4) 18-24 month\",",
              "                            if(remain >=24, \"5) > 24 month\", ",
              "            \"6) No movement\")",
              "                        )         ",
              "                    )",
              "                )",
              "            --)",
              "        )",
              "    ),  \"6) No movement\"--\"6) No movement\"--",
              ")",
              "// 02/05/23",
              "// the buckets for stock remaining in months",
              "//< 3mnts, 3-6mnt, 6-12, 12-18, 18-24, >24, No movement",
              "// if(--AND(",
              "//     NOT(ISBLANK([ConsumptionQuantity]))",
              "//     --, cond = 0)",
              "//     , ",
              "//     // --AND(NOT(ISBLANK([ConsumptionQuantity])),NOT(ISBLANK(cond))),",
              "//      --if(NOT(ISBLANK([StockQuantityToDate])), ",
              "//         if (and(cond <>0, cond < 3), \" 0) <3 months\",",
              "//             if(and(cond >=3, cond<6), \"1) 3-6 month\", ",
              "//                 if(and(cond >=6, cond<12), \"2) 6-12 month\", ",
              "//                     if(and(cond >= 12, cond <18), \"3) 12-18 month\", ",
              "//                         if(and(cond >= 18, cond <24), \"4) 18-24 month\",",
              "//                             if(cond >=24, \"5) > 24 month\", ",
              "//             \"6) No movement\")",
              "",
              "//                                 )",
              "                                    ",
              "//                             )",
              "//                         )",
              "//                     )",
              "//                 --)",
              "//             --)",
              "//         ),",
              "//     \"test\"",
              "// )))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "90aa0aea-7732-4cf4-911c-e635ef4af471",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthDiff",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "DATEDIFF(MaterialStockLevel[MaxDate],today(),month)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "37e3369b-1ff2-4deb-9840-409d12e9a574",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "MaxDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "var CurrentProduct = MaterialStockLevel[MaterialID]",
              "return ",
              "maxx( filter( all(MaterialStockLevel), MaterialStockLevel[MaterialID] = CurrentProduct),MaterialStockLevel[ReportingDate]",
              ")"
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "6760a624-19e8-45af-a204-6a6505f77f0f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "StockLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "var CurrentProduct = MaterialStockLevel[MaterialID]",
              "var CurrentDate = MaterialStockLevel[ReportingDate]",
              "return ",
              " AVERAGEX( filter( ALL(MaterialStockLevel), AND(MaterialStockLevel[MaterialID] = CurrentProduct, MaterialStockLevel[ReportingDate] = CurrentDate)),MaterialStockLevel[StockLevelQtyInBaseUnit])",
              ""
            ],
            "formatString": "0.000000000000000",
            "isDataTypeInferred": true,
            "lineageTag": "f6e679ff-08e1-49ac-be18-c442fbe722f5",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "StockLevelStandardPPU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "19f44327-0913-4196-a520-1f15e4ec28a9",
            "sourceColumn": "StockLevelStandardPPU",
            "summarizeBy": "sum"
          },
          {
            "name": "StockLevelStandardPPU_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d0f46aeb-3521-4240-8974-31fb977d548e",
            "sourceColumn": "StockLevelStandardPPU_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "PriceControlIndicatorID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7d8b32d-7f9d-492a-9fb5-dc9c0627a9a6",
            "sourceColumn": "PriceControlIndicatorID",
            "summarizeBy": "none"
          },
          {
            "name": "PriceControlIndicator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a55aa45c-4501-441a-ad2f-e37dfd600965",
            "sourceColumn": "PriceControlIndicator",
            "summarizeBy": "none"
          },
          {
            "name": "sk_dim_ProductValuationPUP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d9fedef2-db6b-460a-87c6-45c640083a48",
            "sourceColumn": "sk_dim_ProductValuationPUP",
            "summarizeBy": "sum"
          },
          {
            "name": "StockLevelStandardPPU_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "130d7451-12aa-46fe-ba83-8c6ed439c23c",
            "sourceColumn": "StockLevelStandardPPU_USD",
            "summarizeBy": "sum"
          },
          {
            "name": "ReportingDateStart",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "expression": "STARTOFMONTH(MaterialStockLevel[ReportingDate])",
            "formatString": "dd/mm/yyyy",
            "isDataTypeInferred": true,
            "lineageTag": "5671dbf2-d84d-42e2-ae1d-a68ee52cc609",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "LastDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "var CurrentProduct = MaterialStockLevel[MaterialID]",
              "return ",
              "maxx( filter( all(MaterialStockLevel), MaterialStockLevel[MaterialID] = CurrentProduct),MaterialStockLevel[ReportingDate])"
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "3acebe6a-bf5a-46c5-9ab2-41aca52714ba",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c923a0ad-cfcf-46ea-9140-4ad2723e064d",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "198ca015-d114-4eca-a8b7-54781617bb18",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "StockLevelStandardLastPPU",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9550ce4e-d2a6-49eb-ba5e-6d5eb0f0fd82",
            "sourceColumn": "StockLevelStandardLastPPU",
            "summarizeBy": "sum"
          },
          {
            "name": "StockLevelStandardLastPPU_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "87c867e5-4929-4aca-8ad3-fe961ff7e94c",
            "sourceColumn": "StockLevelStandardLastPPU_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "StockLevelStandardLastPPU_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7932cab3-6c4a-4fae-a4b4-8dc692452de7",
            "sourceColumn": "StockLevelStandardLastPPU_USD",
            "summarizeBy": "sum"
          },
          {
            "name": "StockPricePerUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "31f0a645-4e0b-429d-8ca9-728297e2a60f",
            "sourceColumn": "StockPricePerUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "StockPricePerUnit_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6402edfd-42ee-42e6-9adf-f416718be54e",
            "sourceColumn": "StockPricePerUnit_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "StockPricePerUnit_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0a71f682-16a1-4743-942f-70c10ed94f18",
            "sourceColumn": "StockPricePerUnit_USD",
            "summarizeBy": "sum"
          },
          {
            "name": "LatestPricePerPiece_Local",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5a4ce23f-b8fe-413d-b17a-ccaadfaa03c5",
            "sourceColumn": "LatestPricePerPiece_Local",
            "summarizeBy": "sum"
          },
          {
            "name": "LatestPricePerPiece_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "989bf919-00b3-4e08-b7df-01e110c2069f",
            "sourceColumn": "LatestPricePerPiece_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "LatestPricePerPiece_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "164688eb-68c5-4c9d-914e-60777f5345d7",
            "sourceColumn": "LatestPricePerPiece_USD",
            "summarizeBy": "sum"
          },
          {
            "name": "Prev12MConsumptionQty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c0df6131-09f8-47dd-b1c9-264f6f36af41",
            "sourceColumn": "Prev12MConsumptionQty",
            "summarizeBy": "sum"
          },
          {
            "name": "RemainingM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "divide(MaterialStockLevel[StockLevel],MaterialStockLevel[Prev12MConsumptionQty], 0) * 12",
            "isDataTypeInferred": true,
            "lineageTag": "dc2007fa-cea5-4437-95c2-80e86397a0b8",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Bucket2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "",
              "VAR cond = MaterialStockLevel[RemainingM]--MaterialDocumentItem[StockRemainingMnths] --cond it is the short of condition ",
              "RETURN",
              "",
              "// 09/01/22",
              "// the buckets for stock remainig in months",
              "//< 3mnts, 3-6mnt, 6-12, 12-18, 18-24, 24-36, 36-60, 60-120, 120-9998 , No movement (9999)",
              "if(AND(NOT(ISBLANK(cond)), MaterialStockLevel[LastDate] = MaterialStockLevel[ReportingDate]), ",
              "    --(if (or(cond <> 0, cond < 3), \" 0) <3 months\", ",
              "    (if (cond < 3, \" 0) <3 months\",",
              "        if(and(cond >=3, cond<6), \"1) 3-6 month\", ",
              "            if(and(cond >=6, cond<12), \"2) 6-12 month\", ",
              "                if(and(cond >= 12, cond <18), \"3) 12-18 month\", ",
              "                    if(and(cond >= 18, cond <24), \"4) 18-24 month\",",
              "                        if(and(cond >=24, cond<36), \"5) 24-36 month\", ",
              "                            if(and(cond >= 36, cond < 60), \"6) 36-60 month\", ",
              "                                if(and(cond >= 60, cond <120), \"7) 60-120 month\",",
              "                                    if(and(cond >= 120, cond <9998), \"8) 120-9998 month\", \"9) 9999 (no consumption)\")",
              "                                        )",
              "                                    )",
              "                                )",
              "                            )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "07039bdc-dd91-4545-ab54-7163266c4672",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "StockLevel_ByMonths",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "",
              "var CurrentProduct = MaterialStockLevel[MaterialID]",
              "return ",
              "// sumx( filter( all(MaterialStockLevel),and( MaterialStockLevel[MaterialID] = CurrentProduct, MaterialStockLevel[ReportingDate]=MaterialStockLevel[MaxDate])),MaterialStockLevel[StockLevelQtyInBaseUnit])",
              "sumx(filter( all(MaterialStockLevel), MaterialStockLevel[MaterialID] = CurrentProduct),",
              "MaterialStockLevel[StockLevelQtyInBaseUnit])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "7ab2f842-008a-4246-b7e4-998411e1a63d",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "CurrencyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "000c68e6-0535-4d0a-8d30-9bb2a13f3586",
            "sourceColumn": "CurrencyID",
            "summarizeBy": "none"
          },
          {
            "name": "nk_StoragePlantID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "13018ac6-bef4-42e4-9c54-6ec3ed0132f2",
            "sourceColumn": "nk_StoragePlantID",
            "summarizeBy": "none"
          },
          {
            "name": "PlantSalesOrgID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1652cce1-fa49-4a3a-b2b2-6d0fffd637af",
            "sourceColumn": "PlantSalesOrgID",
            "summarizeBy": "none"
          },
          {
            "name": "sk_ProductSalesOrg",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "12dd6fe8-d9ff-4b7a-ab26-867171449a00",
            "sourceColumn": "sk_ProductSalesOrg",
            "summarizeBy": "none"
          },
          {
            "name": "RemainingByRows",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "divide(MaterialStockLevel[StockLevelQtyInBaseUnit], MaterialStockLevel[Prev12MConsumptionQty]) * 12",
            "isDataTypeInferred": true,
            "lineageTag": "50ffe75b-d50a-4d75-9095-12ecb6cb8721",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "d27ffcbd-6b97-43cf-bc1a-0c724769aee4",
        "measures": [
          {
            "name": "StockLevel_ByMonths_todelete",
            "expression": [
              "blank()",
              ""
            ],
            "formatString": "0",
            "lineageTag": "6b26ef25-f255-440a-9500-c8f52f8ec9d4"
          }
        ],
        "partitions": [
          {
            "name": "MaterialStockLevel-fe35333e-591e-4fc1-8ed5-16d305941a1a",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB, [Query=\"SELECT *#(lf)FROM dm_sales.vw_fact_MaterialStockLevel MSL #(lf)--WHERE MSL.StockLevelQtyInBaseUnit <> 0.0\"]),",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each [ReportingDate] >= RangeStart and [ReportingDate] <= RangeEnd),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Filtered Rows\", each ([t_applicationId] = \"s4h-cap-100\")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows1\",{\"nk_dim_ProductValuationPUP\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Calendar\",\"TableItemName\":\"Date (bins)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "3797a903-3a8a-4e29-9fd1-8a591bd0ee02",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80b85a2b-a33e-4f35-ae29-9eed0498e1f0",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93e66cb1-c48f-4fab-a5d8-d372ad256a8c",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "124bfada-7f02-45e2-802f-e3c16598a167",
            "sourceColumn": "MonthNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90447059-8322-48f9-9f24-2b2ef32d3067",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c261656-3267-4a60-bc5d-9b2c76007aaa",
            "sourceColumn": "Week",
            "summarizeBy": "none"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9474b8a3-7d5a-4b08-b52a-a7d7e97e35aa",
            "sourceColumn": "Day",
            "summarizeBy": "none"
          },
          {
            "name": "YearMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8591ac6f-0347-41b6-9707-0877847267cd",
            "sourceColumn": "YearMonth",
            "summarizeBy": "none"
          },
          {
            "name": "YearQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5f0cb61-dd8b-472b-8464-dd0eac9c12ba",
            "sourceColumn": "YearQuarter",
            "summarizeBy": "none"
          },
          {
            "name": "YearWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd872845-d84e-4f86-a440-fff70a0d8152",
            "sourceColumn": "YearWeek",
            "summarizeBy": "none"
          },
          {
            "name": "WeekDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4380cb2-943a-4a55-9995-1820ebce2790",
            "sourceColumn": "WeekDay",
            "summarizeBy": "none"
          },
          {
            "name": "FirstDayOfWeekDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "dfbf6645-e635-4126-84a3-d00042db7d8b",
            "sourceColumn": "FirstDayOfWeekDate",
            "summarizeBy": "none"
          },
          {
            "name": "FirstDayOfMonthDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "80a89912-cde0-4b01-94b4-ea7eb6072fe1",
            "sourceColumn": "FirstDayOfMonthDate",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarDayOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7bcbddd-6f73-48a2-9b9a-8ff0b3d7118f",
            "sourceColumn": "CalendarDayOfYear",
            "summarizeBy": "none"
          },
          {
            "name": "YearDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3e90a75-459a-4676-88ba-a570090d4aff",
            "sourceColumn": "YearDay",
            "summarizeBy": "none"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Calendar'[Date],\"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "10bab2ea-d747-4eef-aded-623b5768d989",
            "sortByColumn": "Month",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthName_Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "'Calendar'[Month_Name_Short]&\" \"& 'Calendar'[Year]",
            "isDataTypeInferred": true,
            "lineageTag": "e623c20d-0aca-4408-933a-02619e589279",
            "sortByColumn": "YearMonth",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month_Name_Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Calendar'[Date],\"MMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "ec025ca1-0dc7-4afb-9ebc-b2f6c949d008",
            "sortByColumn": "Month",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "12MonthFilter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "if(and(datediff('Calendar'[Date],today(),month)<=12,'Calendar'[Date]<=today()),1,0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "6c22dc99-70c2-4a0c-a5ba-6c48fccfc520",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "6MonthFilter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "if(and(datediff('Calendar'[Date],today(),month)<6,'Calendar'[Date]<=LASTDATE(MaterialStockLevel[ReportingDate])),1,0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "ccb8fb2f-7fe3-4d08-bcfe-2b80543216c7",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Date (bins)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"c\",\"Entity\":\"Calendar\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"c\"}},\"Property\":\"Date\"}}],\"BinItem\":{\"Expression\":{\"Floor\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"c\"}},\"Property\":\"Date\"}},\"Size\":1.0,\"TimeUnit\":2}}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "IF(",
              "  ISBLANK('Calendar'[Date]),",
              "  BLANK(),",
              "  DATE(",
              "    YEAR('Calendar'[Date]),",
              "    1 + (MONTH('Calendar'[Date]) - 1),",
              "    1",
              "  )",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "binningMetadata": {
                    "binSize": {
                      "unit": 6,
                      "value": 1.0
                    }
                  },
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Calendar"
                          }
                        },
                        "Property": "Date"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "formatString": "mmmm yyyy",
            "isDataTypeInferred": true,
            "lineageTag": "06842167-02d0-4e92-b86e-f40e3ef5de00",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "81aacf8a-71a2-45bd-8efc-0aa045e968a3",
        "partitions": [
          {
            "name": "Calendar-2d0e8367-85aa-4eca-b9bb-37982867943b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_dim_Calendar = Source{[Schema=\"dm_sales\",Item=\"vw_dim_Calendar\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_Calendar"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f81da38-9230-4124-8c18-dfa4f2487e46",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20827e50-1fe2-4c63-9d43-ab1ef2b69f87",
            "sourceColumn": "Customer",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerID_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "181c57f2-6502-40eb-ae9e-e7aecd10db18",
            "sourceColumn": "CustomerID_Name",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerAccountGroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c098579-a5b7-433a-9f6e-8d0c0a3fb785",
            "sourceColumn": "CustomerAccountGroupID",
            "summarizeBy": "none"
          },
          {
            "name": "AccountGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fffe3c2e-dcb7-4245-80c1-0e76a8a084e7",
            "sourceColumn": "AccountGroup",
            "summarizeBy": "none"
          },
          {
            "name": "AuthorizationGroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8e8dfd9-a836-4c32-8fec-5fe620eefa74",
            "sourceColumn": "AuthorizationGroupID",
            "summarizeBy": "none"
          },
          {
            "name": "AuthorizationGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "69a737ca-add4-41ea-a2bd-d6d8dc3a557a",
            "sourceColumn": "AuthorizationGroup",
            "summarizeBy": "sum"
          },
          {
            "name": "DeliveryIsBlocked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6af6d594-2078-4f0a-a401-b540662ec251",
            "sourceColumn": "DeliveryIsBlocked",
            "summarizeBy": "none"
          },
          {
            "name": "PostingIsBlocked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e050fd61-7ffd-4dff-9f2f-5bbfc2f6b8a7",
            "sourceColumn": "PostingIsBlocked",
            "summarizeBy": "none"
          },
          {
            "name": "BillingIsBlockedForCustomer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5ffd784-6259-4981-9015-d758a7b24099",
            "sourceColumn": "BillingIsBlockedForCustomer",
            "summarizeBy": "none"
          },
          {
            "name": "OrderIsBlockedForCustomer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6cde30d5-3c7f-4496-8e91-231d7991d7c3",
            "sourceColumn": "OrderIsBlockedForCustomer",
            "summarizeBy": "none"
          },
          {
            "name": "IsOneTimeAccount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1cc080d3-d2e2-4b4b-8187-123032b7dfff",
            "sourceColumn": "IsOneTimeAccount",
            "summarizeBy": "none"
          },
          {
            "name": "CountryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cff218c7-dc2f-47df-99e6-e75f04772a7d",
            "sourceColumn": "CountryID",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "692319b1-86ba-4332-be19-092a0c6b28f0",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "CityName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6875a61a-1180-4ee3-b865-7d4f4b988f0a",
            "sourceColumn": "CityName",
            "summarizeBy": "none"
          },
          {
            "name": "PostalCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48e1e311-ed95-4ea2-b1c9-4974293f3b1c",
            "sourceColumn": "PostalCode",
            "summarizeBy": "none"
          },
          {
            "name": "StreetName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3fb0692-5172-4cb8-8365-bd97b03941df",
            "sourceColumn": "StreetName",
            "summarizeBy": "none"
          },
          {
            "name": "RegionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "571c3cd6-97f1-47c8-8d29-e12593e1dd19",
            "sourceColumn": "RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b7f90e3-bdad-493f-b242-aa6ef11b341d",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "DeletionIndicator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7d9e29f-83a6-4156-bf55-78219017285c",
            "sourceColumn": "DeletionIndicator",
            "summarizeBy": "none"
          },
          {
            "name": "TradingPartnerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0fd3dbf2-41f3-4ef8-9d16-1e27b923e3c5",
            "sourceColumn": "TradingPartnerID",
            "summarizeBy": "none"
          },
          {
            "name": "TradingPartner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "04affdaf-9650-4504-bdd0-c06bc18e5945",
            "sourceColumn": "TradingPartner",
            "summarizeBy": "sum"
          },
          {
            "name": "BusinessType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e1fc7df-33a6-4378-a8a3-b937eec15c3d",
            "sourceColumn": "BusinessType",
            "summarizeBy": "none"
          },
          {
            "name": "IndustryType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bce5ad61-4c6f-474a-a2e6-4f0661d65dd3",
            "sourceColumn": "IndustryType",
            "summarizeBy": "none"
          },
          {
            "name": "t_jobDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "7e0d9990-e272-4e4d-ae4f-d125f49dfe2c",
            "sourceColumn": "t_jobDtm",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "463cf74d-b421-47fc-89e2-38351c74be95",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "80da703b-add7-4901-8b42-5925e71ba957",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "InOutID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a8e8589-0764-42a4-b50a-bbe51fa2c316",
            "sourceColumn": "InOutID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3026f5fa-185e-46fa-8da1-4c31fe3e45cf",
        "partitions": [
          {
            "name": "Customer-2b76bc66-903e-4950-b37f-ca3ff11d8aea",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_dim_Customer = Source{[Schema=\"dm_sales\",Item=\"vw_dim_Customer\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_Customer"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9adc523a-05e6-463a-b168-3db8ae1ee2a8",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "ProductExternalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "190e894d-1741-4035-aa44-94b1099210fd",
            "sourceColumn": "ProductExternalID",
            "summarizeBy": "none"
          },
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfbfa62c-9a3f-4bb4-8ac5-dbf1bf3270d5",
            "sourceColumn": "Product",
            "summarizeBy": "none"
          },
          {
            "name": "ProductID_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f79cd2e-e477-479a-a3f0-14e1713040f8",
            "sourceColumn": "ProductID_Name",
            "summarizeBy": "none"
          },
          {
            "name": "MaterialTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef75d5b3-99ba-45c6-be57-6282a91d04fb",
            "sourceColumn": "MaterialTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "MaterialType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c23578ca-8229-4427-95af-4fe6f0f6e67f",
            "sourceColumn": "MaterialType",
            "summarizeBy": "none"
          },
          {
            "name": "IsMarkedForDeletion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d97e085f-1f59-4dc4-b694-1fdd60b7d352",
            "sourceColumn": "IsMarkedForDeletion",
            "summarizeBy": "none"
          },
          {
            "name": "CrossPlantStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45b4d253-5335-4eb4-9b6a-fe07dcb29f09",
            "sourceColumn": "CrossPlantStatus",
            "summarizeBy": "none"
          },
          {
            "name": "GrossWeight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d77bcac1-d049-44de-b6eb-d5e0afcca83d",
            "sourceColumn": "GrossWeight",
            "summarizeBy": "sum"
          },
          {
            "name": "SourceOfSupply",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5378f3b8-26dd-4c40-8ecd-9ae154eea98f",
            "sourceColumn": "SourceOfSupply",
            "summarizeBy": "none"
          },
          {
            "name": "CountryOfOrigin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8fdc76b1-6b9e-47c8-a22f-de97f11d64b1",
            "sourceColumn": "CountryOfOrigin",
            "summarizeBy": "none"
          },
          {
            "name": "CompetitorID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba6d7a95-d1d1-425b-bc01-b6efe4e4dd9b",
            "sourceColumn": "CompetitorID",
            "summarizeBy": "none"
          },
          {
            "name": "MaterialGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddec700d-29d1-488c-a1d2-69bbae0504a7",
            "sourceColumn": "MaterialGroup",
            "summarizeBy": "none"
          },
          {
            "name": "BaseUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7dfd7a35-03dc-499d-a232-e056049cbabf",
            "sourceColumn": "BaseUnit",
            "summarizeBy": "none"
          },
          {
            "name": "ItemCategoryGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "319c9503-2de2-4fc0-8461-3f685e260c78",
            "sourceColumn": "ItemCategoryGroup",
            "summarizeBy": "none"
          },
          {
            "name": "ProductHierarchy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c3bf2d8-f30b-4daa-b348-97082747f2d7",
            "sourceColumn": "ProductHierarchy",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L1_PillarID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec32a929-65e6-4577-9752-dd350bd32fa0",
            "sourceColumn": "Product_L1_PillarID",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L2_GroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec3f0462-cbf1-46d8-8d30-1a8331029d8c",
            "sourceColumn": "Product_L2_GroupID",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L3_TypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ea2e8b7-40f8-4f86-98dc-e7041ea4f91f",
            "sourceColumn": "Product_L3_TypeID",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L4_FamilyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dde05332-b280-4198-a517-a094ac9b635a",
            "sourceColumn": "Product_L4_FamilyID",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L5_SubFamilyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6083ed9c-976d-4b17-8a8b-afee3f3b504e",
            "sourceColumn": "Product_L5_SubFamilyID",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L1_Pillar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aedab2b5-b12f-4c0e-8667-652bb667592d",
            "sourceColumn": "Product_L1_Pillar",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L2_Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d1b11a62-655b-49c5-9a32-970187d5fe25",
            "sourceColumn": "Product_L2_Group",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L3_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3190852c-31a4-4062-8f56-85f629846a9f",
            "sourceColumn": "Product_L3_Type",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L4_Family",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b8d8818-0b4d-46b4-8eb1-54c29d41fe56",
            "sourceColumn": "Product_L4_Family",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L5_SubFamily",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc0e4a3d-a444-459b-9a49-45ac5b2002cf",
            "sourceColumn": "Product_L5_SubFamily",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e004806a-d4d6-46c2-be5e-ae74fcae4c42",
            "sourceColumn": "ProductCategory",
            "summarizeBy": "none"
          },
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c7e3758-c8d1-486b-a242-253948d0eb83",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          },
          {
            "name": "IndustryStandardName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "df8b44d9-6ccd-47aa-9a80-9bcb0c87cd42",
            "sourceColumn": "IndustryStandardName",
            "summarizeBy": "none"
          },
          {
            "name": "ProductStandardID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f9e653a-f72c-4468-b66b-55f7052994c4",
            "sourceColumn": "ProductStandardID",
            "summarizeBy": "none"
          },
          {
            "name": "InternationalArticleNumberCat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d26b325-019f-4be9-854c-28640e351cd5",
            "sourceColumn": "InternationalArticleNumberCat",
            "summarizeBy": "none"
          },
          {
            "name": "ProductIsConfigurable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "575fb5cc-922f-46c9-ac76-ac17db825152",
            "sourceColumn": "ProductIsConfigurable",
            "summarizeBy": "none"
          },
          {
            "name": "IsBatchManagementRequired",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45a9fcc9-20a0-4f0d-b038-354cbdd8a751",
            "sourceColumn": "IsBatchManagementRequired",
            "summarizeBy": "none"
          },
          {
            "name": "ExternalProductGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3cf39347-f289-4136-98ee-3176a19b4fb1",
            "sourceColumn": "ExternalProductGroup",
            "summarizeBy": "none"
          },
          {
            "name": "CrossPlantConfigurableProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56026ed0-91db-4c78-8f29-e9151d862470",
            "sourceColumn": "CrossPlantConfigurableProduct",
            "summarizeBy": "none"
          },
          {
            "name": "ProductManufacturerNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d3aa8908-089d-4175-bf4e-74c5e46c3e77",
            "sourceColumn": "ProductManufacturerNumber",
            "summarizeBy": "none"
          },
          {
            "name": "ManufacturerNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d456d9a-9b03-411d-93ef-78326568eae3",
            "sourceColumn": "ManufacturerNumber",
            "summarizeBy": "none"
          },
          {
            "name": "MaximumPackagingLength",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6ad30604-b21b-457a-b0ca-5fff821b3fbe",
            "sourceColumn": "MaximumPackagingLength",
            "summarizeBy": "sum"
          },
          {
            "name": "MaximumPackagingWidth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b31210e3-db6f-438a-a9e1-dbcb2e9bdd3d",
            "sourceColumn": "MaximumPackagingWidth",
            "summarizeBy": "sum"
          },
          {
            "name": "MaximumPackagingHeight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "10bc12bb-6f0b-4e8f-9a3d-e09c1896bb6a",
            "sourceColumn": "MaximumPackagingHeight",
            "summarizeBy": "sum"
          },
          {
            "name": "MaximumCapacity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "09e3d330-b4b4-433b-92dd-20ff21654a8d",
            "sourceColumn": "MaximumCapacity",
            "summarizeBy": "sum"
          },
          {
            "name": "OvercapacityTolerance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ddc0d8ab-a804-4b6f-bbdc-3d5439580687",
            "sourceColumn": "OvercapacityTolerance",
            "summarizeBy": "sum"
          },
          {
            "name": "UnitForMaxPackagingDimensions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e0ac32e-0a56-44b2-987d-c65a3f9db6b0",
            "sourceColumn": "UnitForMaxPackagingDimensions",
            "summarizeBy": "none"
          },
          {
            "name": "BaseUnitSpecificProductLength",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4136b5a8-37f6-4c6b-9afb-15382fd2f711",
            "sourceColumn": "BaseUnitSpecificProductLength",
            "summarizeBy": "sum"
          },
          {
            "name": "BaseUnitSpecificProductWidth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c41bb270-4ed9-4884-8d03-f419da9cb237",
            "sourceColumn": "BaseUnitSpecificProductWidth",
            "summarizeBy": "sum"
          },
          {
            "name": "BaseUnitSpecificProductHeight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0864dcb4-2166-488f-bd8f-c302ed5cfbd3",
            "sourceColumn": "BaseUnitSpecificProductHeight",
            "summarizeBy": "sum"
          },
          {
            "name": "ArticleCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de3652c6-a7bb-436b-888f-afd2ee7b1aac",
            "sourceColumn": "ArticleCategory",
            "summarizeBy": "none"
          },
          {
            "name": "ProductIsLocked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "107b9f9f-087b-4721-a0e4-142e37b12e99",
            "sourceColumn": "ProductIsLocked",
            "summarizeBy": "none"
          },
          {
            "name": "BasicMaterial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ee7c457-ccf1-4fb5-b0b5-12776a0eab05",
            "sourceColumn": "BasicMaterial",
            "summarizeBy": "none"
          },
          {
            "name": "SalesProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4940bd96-21fb-4a0f-95a3-f73733e75be5",
            "sourceColumn": "SalesProduct",
            "summarizeBy": "none"
          },
          {
            "name": "ZZ1_CustomFieldRiskMit_PRD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e54ad08-d507-4f71-b2e8-d02d4b1c6985",
            "sourceColumn": "ZZ1_CustomFieldRiskMit_PRD",
            "summarizeBy": "none"
          },
          {
            "name": "ZZ1_CustomFieldHighRis_PRD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0343c7c8-207b-4846-ac69-8f541b8dac94",
            "sourceColumn": "ZZ1_CustomFieldHighRis_PRD",
            "summarizeBy": "none"
          },
          {
            "name": "ZZ1_CustomFieldRiskRea_PRD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b5a4788-5945-4bc1-8944-41ae9af4efdf",
            "sourceColumn": "ZZ1_CustomFieldRiskRea_PRD",
            "summarizeBy": "none"
          },
          {
            "name": "t_jobDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "66899436-477f-407a-bac3-40cad248432a",
            "sourceColumn": "t_jobDtm",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0571661e-7195-476e-b916-f465c5d33ba0",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6a42e354-591a-4eac-a342-4c2975e0ce56",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "var CurrentProduct = 'Product'[ProductID]",
              "return ",
              "maxx( filter( all(MaterialDocumentItem), MaterialDocumentItem[MaterialID] = CurrentProduct),MaterialDocumentItem[Bucket])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "b7d01b65-01b7-42d5-a8f1-eb34ba833c0b",
            "sortByColumn": "BucketOrder",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "BucketOrder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "related(BucketOrder[Order])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "61a2b954-fe35-4c65-b389-af291ba50aef",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "sk_dim_Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb601b4e-5c1d-44d6-bc8b-c6eaf527e050",
            "sourceColumn": "sk_dim_Product",
            "summarizeBy": "none"
          },
          {
            "name": "ProductID_Name_",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "if(not(ISBLANK('Product'[ProductID_Name])),'Product'[ProductID_Name],'Product'[ProductID]&\"-\"&'Product'[Product])",
            "isDataTypeInferred": true,
            "lineageTag": "a0b4bb25-d567-4332-bf91-b6c466a56021",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Test_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "expression": "if('Product'[ProductID_Name]='Product'[ProductID_Name_],true,false)",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "lineageTag": "bb652f11-60ff-4761-8062-28c23d56ee3a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CreationDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "81750641-6d22-4901-8211-b11beefa3b40",
            "sourceColumn": "CreationDate",
            "summarizeBy": "none"
          },
          {
            "name": "NetWeight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7308bef9-f46f-449f-8d3e-a6297e20702b",
            "sourceColumn": "NetWeight",
            "summarizeBy": "sum"
          },
          {
            "name": "IndustrySector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65aa276d-26e8-42f2-9fb7-70170a5d278f",
            "sourceColumn": "IndustrySector",
            "summarizeBy": "none"
          },
          {
            "name": "WeightUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6708d06c-eac2-4d8e-a65c-4382491699e4",
            "sourceColumn": "WeightUnit",
            "summarizeBy": "none"
          },
          {
            "name": "Division",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66731914-7817-4a06-bfee-e8d008636aba",
            "sourceColumn": "Division",
            "summarizeBy": "none"
          },
          {
            "name": "TransportationGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aba5fbbd-0dae-4278-afd0-65ae8dc738b1",
            "sourceColumn": "TransportationGroup",
            "summarizeBy": "none"
          },
          {
            "name": "CurrentStockValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "CALCULATE(SUM(MaterialStockLevel[StockLevel]))",
            "isDataTypeInferred": true,
            "lineageTag": "8b1a9f70-2db7-4a3b-8632-9a7e64dd36b0",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "CreatedByUser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1562ffe8-3994-4200-86e4-e22455a5a07b",
            "sourceColumn": "CreatedByUser",
            "summarizeBy": "none"
          },
          {
            "name": "CrossPlantStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fdb211c4-a791-49a3-ae37-84ae25824913",
            "sourceColumn": "CrossPlantStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "ItemCategoryGroupName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6503a455-bfea-473c-a686-82253e5ff02d",
            "sourceColumn": "ItemCategoryGroupName",
            "summarizeBy": "none"
          },
          {
            "name": "EClassCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1c12c58-f29f-45e5-93d9-ca4077c52c7f",
            "sourceColumn": "EClassCode",
            "summarizeBy": "none"
          },
          {
            "name": "EClassCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c23edabb-2f76-4db1-bea0-d8e21714e6ae",
            "sourceColumn": "EClassCategory",
            "summarizeBy": "none"
          },
          {
            "name": "EClassCategoryDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf658ff1-7f69-4540-9662-67867b515a2b",
            "sourceColumn": "EClassCategoryDescription",
            "summarizeBy": "none"
          },
          {
            "name": "Classification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83e39f29-9d9c-4c26-9616-6c44fcaa401f",
            "sourceColumn": "Classification",
            "summarizeBy": "none"
          },
          {
            "name": "Category_L1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14787872-c703-43f8-8d48-fc0f0eeff080",
            "sourceColumn": "Category_L1",
            "summarizeBy": "none"
          },
          {
            "name": "Category_L2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c9966b8-a33c-4c68-815b-bc7427510885",
            "sourceColumn": "Category_L2",
            "summarizeBy": "none"
          },
          {
            "name": "Category_L3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "884b432f-7443-4a3c-bb0e-9151bcee4b2e",
            "sourceColumn": "Category_L3",
            "summarizeBy": "none"
          },
          {
            "name": "Category_L4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "728b5f55-c83c-4535-acfb-201b3eb753ca",
            "sourceColumn": "Category_L4",
            "summarizeBy": "none"
          },
          {
            "name": "GrossWeight & Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE('Product'[GrossWeight], CONCATENATE(\" \", 'Product'[WeightUnit]))",
            "isDataTypeInferred": true,
            "lineageTag": "5c5513dc-100c-422f-ae91-4ddddda4e9bb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NetWeight & Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE('Product'[NetWeight], CONCATENATE(\" \", 'Product'[WeightUnit]))",
            "isDataTypeInferred": true,
            "lineageTag": "083897e4-7557-4747-83d4-959bab07b763",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CrossPlantStatusID_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE('Product'[CrossPlantStatusID], CONCATENATE(\" \", 'Product'[CrossPlantStatus]))",
            "isDataTypeInferred": true,
            "lineageTag": "7f827045-29c0-4f0d-b1f9-091f63861d53",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ItemCategoryGroupID_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE('Product'[ItemCategoryGroup], CONCATENATE(\" \", 'Product'[ItemCategoryGroupName]))",
            "isDataTypeInferred": true,
            "lineageTag": "e1c83b1f-8ff0-44cb-b1fa-fbf7abd2a8db",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ProductOldID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd724992-58d8-4ce5-919d-dc384a9ac418",
            "sourceColumn": "ProductOldID",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Product Hierarchy",
            "levels": [
              {
                "name": "Product_L1_Pillar",
                "column": "Product_L1_Pillar",
                "lineageTag": "6640e6f8-8b72-4f72-b3a4-786ebbe98f78",
                "ordinal": 0
              },
              {
                "name": "Product_L2_Group",
                "column": "Product_L2_Group",
                "lineageTag": "8deb4d87-b69b-46ac-a814-f4603eb5c6ed",
                "ordinal": 1
              },
              {
                "name": "Product_L3_Type",
                "column": "Product_L3_Type",
                "lineageTag": "783b8a5b-317b-49e0-a128-8080d0418c0a",
                "ordinal": 2
              },
              {
                "name": "Product_L4_Family",
                "column": "Product_L4_Family",
                "lineageTag": "19e270c8-0d46-43fe-b81a-dc352ecfe0eb",
                "ordinal": 3
              },
              {
                "name": "Product_L5_SubFamily",
                "column": "Product_L5_SubFamily",
                "lineageTag": "0d0b8a8d-bd56-44a6-bae9-9b688568ba00",
                "ordinal": 4
              },
              {
                "name": "ProductID_Name",
                "column": "ProductID_Name",
                "lineageTag": "9b20134e-59a2-4d4f-a60a-da276817e605",
                "ordinal": 5
              }
            ],
            "lineageTag": "c29f8335-03d0-4fa1-83e3-d3418ffa4142"
          }
        ],
        "lineageTag": "7284a0bb-5327-43e7-a695-18fbce91cf5f",
        "partitions": [
          {
            "name": "Product-5d013f67-1e15-4dd0-a026-5ec042b30530",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_dim_Product = Source{[Schema=\"dm_sales\",Item=\"vw_dim_Product\"]}[Data],",
                "    #\"Removed Duplicates\" = Table.Distinct(dm_sales_vw_dim_Product, {\"ProductID\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SalesOrganization",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesOrganizationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e02d218-aea3-4874-ad14-9c07543f7afe",
            "sourceColumn": "SalesOrganizationID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "22c52285-83be-4d44-b29a-2f18221dfa71",
            "sourceColumn": "SalesOrganization",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganizationCurrency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d256878-57db-48e0-ac48-41092b648145",
            "sourceColumn": "SalesOrganizationCurrency",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f4d5283-d065-4161-837a-45f7f733a11f",
            "sourceColumn": "CompanyCode",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7835817-b7ae-408a-b919-44ca52c82069",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6e767171-6a6e-4b41-a576-86f38a1b71dc",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "CountryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be58400a-3843-4ae2-9306-50fa3d0426c0",
            "sourceColumn": "CountryID",
            "summarizeBy": "none"
          },
          {
            "name": "CountryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02f075f9-0884-4a5e-b1c4-9785c0096d65",
            "sourceColumn": "CountryName",
            "summarizeBy": "none"
          },
          {
            "name": "RegionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9584e238-d71d-4a08-8fbc-3b89b6d1b4b3",
            "sourceColumn": "RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "RegionName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51f66103-4bf0-47d5-80fc-8cee38596c17",
            "sourceColumn": "RegionName",
            "summarizeBy": "none"
          },
          {
            "name": "Access_Control_Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "df1df2d3-9db6-4248-9cc2-8401bee00f35",
            "sourceColumn": "Access_Control_Unit",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cc974930-9e57-44ae-a7f8-24b1a489e877",
        "partitions": [
          {
            "name": "SalesOrganization-4c3b9a33-4657-413a-b205-6cbe2d5cc364",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_dim_SalesOrganization = Source{[Schema=\"dm_sales\",Item=\"vw_dim_SalesOrganization\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_SalesOrganization"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Measures",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e71758bc-d017-4e08-a584-8a09f81e73bc",
            "sourceColumn": "Measures",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "786a1ce6-31f4-451e-9a91-3528729a86a1",
        "measures": [
          {
            "name": "StockQuantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockQuantity_Qty",
            "expression": [
              "calculate(sum(MaterialStockLevel[StockLevelQtyInBaseUnit])",
              ",MaterialStockLevel[ReportingDate] = MaterialStockLevel[MaxDate]",
              ")"
            ],
            "lineageTag": "99f90f6c-2eda-463d-adc2-6031feaedd0b"
          },
          {
            "name": "ConsumptionQuantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Consumption",
            "expression": "[OBD Qty (ICPO)]+[OBD Qty (SO)]+[OBD Qty (Pro)] ",
            "lineageTag": "c9ef9576-4b10-4749-b0f2-e059aecec268"
          },
          {
            "name": "StockTurnInQty",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockTurn",
            "expression": "divide([ConsumptionQuantity12M],[StockQuantity],0)",
            "lineageTag": "ee39496e-8ff1-407a-ae71-18f761c2a949"
          },
          {
            "name": "StockCoverage",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "divide([StockQuantity],[ConsumptionQuantity12M]/12,0)",
            "lineageTag": "e24bb35e-f3be-4ccb-8833-92bb77d95630"
          },
          {
            "name": "NumberOfStockItems",
            "displayFolder": "NumberOfStockItems",
            "expression": [
              "calculate(DISTINCTCOUNT(MaterialStockLevel[MaterialID]),",
              "ROUND(MaterialStockLevel[StockLevel], 6) > 0,all('dimProductCalculated'[ProductID_NameCalculated]))"
            ],
            "formatString": "0",
            "lineageTag": "9ff81009-2c6e-41a0-bf17-33344e3e4a6e"
          },
          {
            "name": "OBD Qty (ICPO)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "OBD",
            "expression": "calculate(sum(MaterialDocumentItem[ConsumptionQtyICPOInBaseUnit]))",
            "lineageTag": "1f1a819c-fa15-42bd-b8ea-9a3ec4904700"
          },
          {
            "name": "OBD Qty (SO)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "OBD",
            "expression": "calculate(sum(MaterialDocumentItem[ConsumptionQtySOInBaseUnit]))",
            "lineageTag": "bc4cb425-2ef7-40c3-9fce-79f29ebf1783"
          },
          {
            "name": "StockRemaining",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Remainings",
            "expression": "divide([StockQuantity],[ConsumptionQuantity12M],0) *12",
            "lineageTag": "96f8d2d6-4bfd-4e3c-9db7-ab8200f14861"
          },
          {
            "name": "ConsumptionQuantity12M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Consumption",
            "expression": "calculate([ConsumptionQuantity],datediff('Calendar'[Date],TODAY(), month)<13)",
            "lineageTag": "3ec22994-6e8e-484a-8a00-65ca0e587fa2"
          },
          {
            "name": "StockRemainingWeeks",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Remainings",
            "expression": "divide([StockQuantity],[ConsumptionQuantity12M],0) *52",
            "lineageTag": "7fc0d34d-73c5-4c08-a429-0654b52c708a"
          },
          {
            "name": "OBD SO %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "OBD",
            "expression": "[OBD Qty (SO)]/[ConsumptionQuantity]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4893a7ca-bee7-4318-99ea-10f92172ee34"
          },
          {
            "name": "OBD ICPO %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "OBD",
            "expression": "[OBD Qty (ICPO)]/[ConsumptionQuantity]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "1a6d8037-37b0-4c2a-908f-a7b644e58047"
          },
          {
            "name": "StockQuantity2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockQuantity_Qty",
            "expression": "calculate(sum(MaterialDocumentItem[MatlStkChangeQtyInBaseUnit]),all(MaterialDocumentItem[HDR_PostingDate]))",
            "lineageTag": "fc88dc1f-a36a-46eb-bac5-70e6e3eb44cc"
          },
          {
            "name": "StockRemainingWeeks2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Remainings",
            "expression": [
              "",
              "--divide([StockQuantity2],[ConsumptionQuantity12M],0) *52",
              "divide([StockQuantityToDate],[ConsumptionQuantity12M],0)*52"
            ],
            "formatString": "0",
            "lineageTag": "22f6c0e0-c6f0-4111-a9df-d48eb72eada9"
          },
          {
            "name": "StockTurnInQty2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockTurn",
            "expression": "divide([ConsumptionQuantity12M],[StockQuantity2],0)",
            "lineageTag": "ec134660-9c51-4e40-9748-2122147082ff"
          },
          {
            "name": "SelectedValue_Plant",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( Plant[Plant] ),",
              "    CONCATENATEX ( FILTERS ( Plant[Plant]), Plant[Plant], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "a2d12943-cd4e-4430-8fe3-64ec45548761"
          },
          {
            "name": "SelectedValue_ProductID",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'dimProductCalculated'[ProductID_NameCalculated] ),",
              "    CONCATENATEX ( FILTERS ( 'dimProductCalculated'[ProductID_NameCalculated]), 'dimProductCalculated'[ProductID_NameCalculated], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "ed93c005-021c-4fc5-ba03-c0f112f95357"
          },
          {
            "name": "SelectedValue_SalesOrganization",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( Plant[SalesOrganization] ),",
              "    CONCATENATEX ( FILTERS ( Plant[SalesOrganization]), Plant[SalesOrganization], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "c1a033c7-33cd-4390-bc77-06dd022f4b63"
          },
          {
            "name": "SelectedValue_Application",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( dim_Application_manual[Application] ),",
              "    CONCATENATEX ( FILTERS ( dim_Application_manual[Application]), dim_Application_manual[Application], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "4c9f9f18-d720-4760-97a7-30acba569c99"
          },
          {
            "name": "SelectedValue_StorageLocation",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( StorageLocation[StorageLocationID_Name] ),",
              "    CONCATENATEX ( FILTERS ( StorageLocation[StorageLocationID_Name]), StorageLocation[StorageLocationID_Name], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "b5b50519-4336-491d-8e4b-66ea8f0bda97"
          },
          {
            "name": "SelectedValue_Units",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( UnitOfMeasure[UnitOfMeasureID] ),",
              "    CONCATENATEX ( FILTERS ( UnitOfMeasure[UnitOfMeasureID]),  UnitOfMeasure[UnitOfMeasureID], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "d7123dea-6369-4ae7-9d9e-360e16584d15"
          },
          {
            "name": "SelectedValue_StockType",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( InventoryStockType[InventoryStockTypeName] ),",
              "    CONCATENATEX ( FILTERS ( InventoryStockType[InventoryStockTypeName]),  InventoryStockType[InventoryStockTypeName], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "bf79c22d-24c9-4187-8a07-e3d84a6a2924"
          },
          {
            "name": "SelectedValue_SpecialStockType",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( InventorySpecialStockType[InventorySpecialStockTypeName] ),",
              "    CONCATENATEX ( FILTERS ( InventorySpecialStockType[InventorySpecialStockTypeName]),  InventorySpecialStockType[InventorySpecialStockTypeName], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "fb511470-6738-4958-aeb4-4c4b2ea3494e"
          },
          {
            "name": "SelectedValue_MaterialType",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Product'[MaterialType]),",
              "    CONCATENATEX ( FILTERS ('Product'[MaterialType]),  'Product'[MaterialType], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "83191b2b-785d-4887-9dd7-0026474f0c89"
          },
          {
            "name": "SelectedValue_SalesDocumentItemCategory",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( MaterialDocumentItem[SalesDocumentItemCategory]),",
              "    CONCATENATEX ( FILTERS (MaterialDocumentItem[SalesDocumentItemCategory]),  MaterialDocumentItem[SalesDocumentItemCategory], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "6588176e-fa40-4a6c-b2bf-852f5d265d02"
          },
          {
            "name": "SelectedValue_DeliveryDocumentType",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( MaterialDocumentItem[HDR_DeliveryDocumentTypeID]),",
              "    CONCATENATEX ( FILTERS (MaterialDocumentItem[HDR_DeliveryDocumentTypeID]),  MaterialDocumentItem[HDR_DeliveryDocumentTypeID], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "bf4e5626-cc2c-4892-9abe-3d5545212934"
          },
          {
            "name": "SelectedValue_GoodsMovementType",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( MaterialDocumentItem[GoodsMovementTypeName]),",
              "    CONCATENATEX ( FILTERS (MaterialDocumentItem[GoodsMovementTypeName]),  MaterialDocumentItem[GoodsMovementTypeName], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "ca103611-2a3a-41a5-9256-67d40ab3721f"
          },
          {
            "name": "SelectedValue_InventoryTransactionType",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( MaterialDocumentItem[HDR_InventoryTransactionTypeID]),",
              "    CONCATENATEX ( FILTERS (MaterialDocumentItem[HDR_InventoryTransactionTypeID]),  MaterialDocumentItem[HDR_InventoryTransactionTypeID], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "2ad1f94e-438b-419c-909b-bbf482d4eab4"
          },
          {
            "name": "SelectedValue_SalesOrder",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( MaterialDocumentItem[SalesOrder]),",
              "    CONCATENATEX ( FILTERS (MaterialDocumentItem[SalesOrder]),  MaterialDocumentItem[SalesOrder], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "ca88f6c6-c8b4-4f62-8720-5da90d6b98c6"
          },
          {
            "name": "SelectedValue_PurchaseOrder",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( MaterialDocumentItem[PurchaseOrder]),",
              "    CONCATENATEX ( FILTERS (MaterialDocumentItem[PurchaseOrder]),  MaterialDocumentItem[PurchaseOrder], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "bd90ac5f-2506-40d8-b469-8792c6d6ad60"
          },
          {
            "name": "SelectedValue_Period",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "var Year1 = ",
              "IF (",
              "    ISFILTERED ( 'Calendar'[Year] ),",
              "    CONCATENATEX ( FILTERS ( 'Calendar'[Year]), 'Calendar'[Year], \", \" ),",
              "    \"ALL Year\"",
              ")",
              "var Month1 = ",
              "IF (",
              "    ISFILTERED ( 'Calendar'[MonthName] ),",
              "    CONCATENATEX ( FILTERS ( 'Calendar'[MonthName]), 'Calendar'[MonthName], \", \" ),",
              "    \"All Month\"",
              ")",
              "var DateRange = ",
              "IF (",
              "    ISFILTERED ( 'Calendar'[Date] ),",
              "    CONCATENATEX ( FILTERS ( 'Calendar'[Date]), max('Calendar'[Date]), \", \" ),",
              "    \"ALL\"",
              ")",
              "return",
              "Year1&\" \"&Month1"
            ],
            "lineageTag": "8ffd4298-f2cb-4a23-bc8c-17e5441f089c"
          },
          {
            "name": "MsgCurrentUnit",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "var CurrencyCount = DISTINCTCOUNT(UnitOfMeasure[UnitOfMeasureID])",
              "return",
              "if(CurrencyCount<=1, \"Quantity unit: \"&MAX(UnitOfMeasure[UnitOfMeasureID]), \"Quantity unit: Multiple quantity units in data selection\")"
            ],
            "lineageTag": "30c00879-775d-4963-a8c3-b2fc656b5f73"
          },
          {
            "name": "CurrentUnit_int",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "if([MsgCurrentUnit]= \"Quantity unit: Multiple quantity units in data selection\",0,1)"
            ],
            "formatString": "0",
            "lineageTag": "a13c6b47-3c85-43b0-a34c-fc16539c69ed"
          },
          {
            "name": "NotificationProduct",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "var CurrencyCount = calculate(DISTINCTCOUNT(dimProductCalculated[ProductID_NameCalculated]),ALLSELECTED('Calendar'),ALLSELECTED(MaterialDocumentItem),ALLSELECTED(MaterialStockLevel),allselected('InventorySpecialStockType'),ALLSELECTED('InventoryStockType'),allselected('Plant'),allselected(StorageLocation))",
              "var CurrencyType_ = max(dimProductCalculated[ProductID_NameCalculated])",
              "return",
              "if(CurrencyCount=1, 0, 1)"
            ],
            "formatString": "0",
            "lineageTag": "d9887ae7-b539-4e1c-a486-f147788de203"
          },
          {
            "name": "TurnInQty_Product",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockTurn",
            "expression": "if([NotificationProduct]=0,[StockTurnInQty2])",
            "lineageTag": "e63e9eba-8bdd-4399-b166-a5f49cab02f1"
          },
          {
            "name": "#StockItems_Product",
            "displayFolder": "Notifications",
            "expression": "if([NotificationProduct]=0,[NumberOfStockItems])",
            "formatString": "0",
            "lineageTag": "bc233809-70d4-4629-bd57-dc869652da8a"
          },
          {
            "name": "StockRemainig_Product",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Remainings",
            "expression": "if([NotificationProduct]=0,[StockRemaining2])",
            "lineageTag": "64ae7705-709d-4662-9565-12e3c3f3394d"
          },
          {
            "name": "StockRemainongWeeks_Product",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Remainings",
            "expression": "if([NotificationProduct]=0,[StockRemainingWeeks2])",
            "lineageTag": "b202853c-93f5-42c9-adc9-b373b1790857"
          },
          {
            "name": "MessageProduct",
            "displayFolder": "Notifications",
            "expression": "if([NotificationProduct]=1,\"Please select one product\",_Measures[SelectedValue_ProductID])",
            "lineageTag": "4916eaef-aba5-4cca-9645-d7311c17e4eb"
          },
          {
            "name": "ConsumptionQty12M_Product",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Consumption",
            "expression": "if([NotificationProduct]=0,[ConsumptionQuantity12M])",
            "lineageTag": "dc0a770e-5cdc-4d37-bee6-6b3794f4b132"
          },
          {
            "name": "StockQuantity_Product",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockQuantity_Qty",
            "expression": "if([NotificationProduct]=0,[StockQuantity])",
            "lineageTag": "b2cc4a9a-810b-4a69-8c20-4cf7748932c7"
          },
          {
            "name": "Top N Sum Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR TopNSelected =                              -- capturing top value selected in the slicer",
              "    SELECTEDVALUE ( param_TopN[TopN] )",
              "VAR TopProdTable =",
              "    TOPN (",
              "        TopNSelected,",
              "        ALLSELECTED ( 'Pseudo Prod Table' ),",
              "        [StockQuantity]",
              "    )",
              "VAR TopProdSales =",
              "    CALCULATE (",
              "        sum(MaterialStockLevel[StockLevelQtyInBaseUnit]),",
              "        KEEPFILTERS ( TopProdTable )",
              "    )",
              "VAR OtherSales =",
              "    /*CALCULATE (",
              "        _Measures[StockQuantity],",
              "        ALLSELECTED ( 'Pseudo Prod Table' )",
              "    )",
              "        - CALCULATE (",
              "            _Measures[StockQuantity],",
              "            TopProdTable",
              "        )*/ 1",
              "VAR CurrentProd =",
              "    SELECTEDVALUE ( 'Pseudo Prod Table'[ProductID_NameCalculated] )",
              "RETURN",
              "    IF (",
              "        CurrentProd <> \"Others\",",
              "        TopProdSales,",
              "        OtherSales",
              "    ) "
            ],
            "lineageTag": "51b4b18b-7f99-4711-a865-708c88ab8294"
          },
          {
            "name": "Top Trading Partner and Other",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "if([Partner Rank] <= param_TopN[TopN Value], sum(MaterialStockLevel[StockLevelQtyInBaseUnit]),",
              "",
              "\tif(SELECTEDVALUE('Pseudo Prod Table'[ProductID_NameCalculated]) = \"Other\", sumx(filter(all('Pseudo Prod Table'[ProductID_NameCalculated]), [Partner Rank]  > param_TopN       [TopN Value]), sum(MaterialStockLevel[StockLevelQtyInBaseUnit]))",
              "    )",
              ")"
            ],
            "lineageTag": "d0159492-c2f3-4809-ab4f-d1220ae7b250"
          },
          {
            "name": "Partner Rank",
            "displayFolder": "Rank",
            "expression": [
              "",
              "IF(SELECTEDVALUE('Pseudo Prod Table'[ProductID_NameCalculated]) = \"Other\", param_TopN[TopN Value] + 1, ",
              "if( selectedvalue(srv_TopFlop[SelectValue]) = \"Top\",",
              "--RANKX(ALL('Pseudo Prod Table'), calculate( _Measures[StockQuantity], all('Calendar'[MonthName])),,DESC,skip),",
              "RANKX(summarize(allselected('dimProductCalculated'),'dimProductCalculated'[ProductID_NameCalculated]),  calculate( _Measures[StockQuantity], all('Calendar')),,DESC,skip),",
              "RANKX(summarize(allselected('dimProductCalculated'),'dimProductCalculated'[ProductID_NameCalculated]), calculate( _Measures[StockQuantity], all('Calendar')),,ASC,Skip)))"
            ],
            "formatString": "0",
            "lineageTag": "a6825b05-1006-47d1-ac82-3b8db2c1c50d"
          },
          {
            "name": "CurrentProduct_int",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "if([MsgCurrentUnit]= \"Please select one product\",0,1)"
            ],
            "formatString": "0",
            "lineageTag": "c01a8e8c-897a-4c49-9f0d-1b420f6901bb"
          },
          {
            "name": "StockValue2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockValue",
            "expression": [
              "IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Local Currency\", sum(MaterialDocumentItem[MatlStkChangeStandardValue]),",
              "        \"Group Currency EUR\", sum(MaterialDocumentItem[MatlStkChangeStandardValue_EUR]),",
              "        \"Group Currency USD\", sum(MaterialDocumentItem[MatlStkChangeStandardValue_USD])",
              "    ),",
              "   sum(MaterialDocumentItem[MatlStkChangeStandardValue_EUR])",
              ")"
            ],
            "lineageTag": "66a1510a-db50-4108-9b4b-fe1313089570"
          },
          {
            "name": "KPI dynamics",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(",
              "    HASONEVALUE(srv_SelectKPI[KPI]),",
              "    SWITCH(",
              "        VALUES(srv_SelectKPI[KPI]),",
              "        \"Stock Quantity\", sum(MaterialStockLevel[StockLevelQtyInBaseUnit]),",
              "        \"Stock Value\", [StockValue]",
              "    ),",
              "    [StockValue]",
              ")"
            ],
            "lineageTag": "d8b8fc02-013c-41e7-b43b-f3104a38c058"
          },
          {
            "name": "StockQuantityToDate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockQuantity_Qty",
            "expression": "calculate(sum(MaterialDocumentItem[MatlStkChangeQtyInBaseUnit]),all(MaterialDocumentItem[HDR_PostingDate]), all('Calendar'))",
            "lineageTag": "172a31c6-1040-48da-9fbe-b97bec7d71eb"
          },
          {
            "name": "StockQuantityPM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockQuantity_Qty",
            "expression": "calculate([StockQuantity2],MaterialDocumentItem[HDR_PostingDate]<=date(year(today()),month(today())-1,day(today())))",
            "lineageTag": "a164398a-7327-4d89-be6f-c044eca34be2"
          },
          {
            "name": "StockValuePM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockValue",
            "expression": [
              "",
              "--calculate([StockValue],month(MaterialStockLevel[ReportingDate])=month(MaterialStockLevel[MaxDate])-1)",
              "CALCULATE(",
              "\t[StockValue],",
              "\tPREVIOUSMONTH(MaterialStockLevel[ReportingDate]), all('Calendar')",
              ")"
            ],
            "lineageTag": "953afac8-fedf-4db8-a62f-013c3c4f9159"
          },
          {
            "name": "StockTurnInQtyPM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockTurn",
            "expression": "divide([ConsumptionQuantity12M-PM],[StockQuantityPM_],0)",
            "lineageTag": "88f9e356-d540-4929-b5d2-1d908b2d9c97"
          },
          {
            "name": "ConsumptionQuantity12M-PM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Consumption",
            "expression": "calculate([ConsumptionQuantity],datediff('Calendar'[Date],today(),month)<14,datediff('Calendar'[Date],today(),month)>=1)",
            "lineageTag": "954a37e7-e2d3-49d3-a8bc-0ce748a510b8"
          },
          {
            "name": "DeltaStockQuantity",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Delta",
            "expression": "if(isblank(divide([StockQuantityByMonths],[StockQuantityPM_],0)),0,divide([StockQuantityByMonths],[StockQuantityPM_],0)-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4ce66fee-dfaa-4b68-9501-9bb1a4c88ada"
          },
          {
            "name": "DeltaStockValue",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Delta",
            "expression": "if(isblank(divide([StockValue],[StockValuePM],0)),0,divide([StockValue],[StockValuePM],0)-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "04235552-9964-4ec5-8b5e-e14d225feb1b"
          },
          {
            "name": "DeltaStockTurnInQty",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Delta",
            "expression": "if(divide([StockTurnInQty],[StockTurnInQtyPM],0)=0,0,divide([StockTurnInQty],[StockTurnInQtyPM],0)-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b0072f84-4888-4e5c-859a-97ffeff7644d"
          },
          {
            "name": "ConsumptionValue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Consumption",
            "expression": [
              "IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Local Currency\", sum(MaterialDocumentItem[ConsumptionQtyICPOInStandardValue])+sum(MaterialDocumentItem[ConsumptionQtyOBDProStandardValue])+sum(MaterialDocumentItem[ConsumptionQtySOStandardValue]),",
              "        \"Group Currency EUR\", sum(MaterialDocumentItem[ConsumptionQtyICPOInStandardValue_EUR])+sum(MaterialDocumentItem[ConsumptionQtyOBDProStandardValue_EUR])+sum(MaterialDocumentItem[ConsumptionQtySOStandardValue_EUR])",
              "    ,",
              "    \"Group Currency USD\", sum(MaterialDocumentItem[ConsumptionQtyICPOInStandardValue_USD])+sum(MaterialDocumentItem[ConsumptionQtyOBDProStandardValue_USD])+sum(MaterialDocumentItem[ConsumptionQtySOStandardValue_USD])",
              "    ), ",
              "    sum(MaterialDocumentItem[ConsumptionQtyICPOInStandardValue_EUR])+sum(MaterialDocumentItem[ConsumptionQtyOBDProStandardValue_EUR])+sum(MaterialDocumentItem[ConsumptionQtySOStandardValue_EUR])",
              ")"
            ],
            "lineageTag": "606f4b2d-7149-4cb1-be4d-9334ab4a4cee"
          },
          {
            "name": "ConsumptionValue12M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Consumption",
            "expression": "calculate([ConsumptionValue],datediff('Calendar'[Date],today(),month)<13)",
            "lineageTag": "0df913c3-d141-441d-98d0-ad5a1f061628"
          },
          {
            "name": "StockTurnInValue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockTurn",
            "expression": "divide([ConsumptionValue12M_lastPPU],[StockValue],0)",
            "lineageTag": "408d64ab-c49a-4d5a-a74b-f39d18acb5ca"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Local Currency\", sum(MaterialDocumentItem[QuantityInBaseUnitStandardValue]),",
              "        \"Group Currency EUR\", sum(MaterialDocumentItem[QuantityInBaseUnitStandardValue_EUR])",
              "    ),",
              "   sum(MaterialDocumentItem[QuantityInBaseUnitStandardValue_EUR])",
              ")"
            ],
            "lineageTag": "3c5327dd-d98f-4e1f-86b6-ba715f042807"
          },
          {
            "name": "SelectedValue_Region",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( Plant[SalesOrg_Region] ),",
              "    CONCATENATEX ( FILTERS ( Plant[SalesOrg_Region]), Plant[SalesOrg_Region], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "14aa456a-90d8-428f-bac2-0bfb8ab1b7a2"
          },
          {
            "name": "StockQuantity2ToDate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockQuantity_Qty",
            "expression": "sum(MaterialDocumentItem[StockLevelToDate])",
            "lineageTag": "4ee5a802-ec4c-4a0c-a35f-6dbf6597fa72"
          },
          {
            "name": "StockValueCM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockValue",
            "expression": [
              "IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Local Currency\", calculate(sum(MaterialStockLevel[StockLevelStandardPPU]),MaterialStockLevel[ReportingDate] = MaterialStockLevel[MaxDate]),",
              "        \"Group Currency EUR\", calculate(sum(MaterialStockLevel[StockLevelStandardPPU_EUR]),MaterialStockLevel[ReportingDate] = MaterialStockLevel[MaxDate]),",
              "        \"Group Currency USD\", calculate(sum(MaterialStockLevel[StockLevelStandardPPU_USD]),MaterialStockLevel[ReportingDate] = MaterialStockLevel[MaxDate])",
              "    ),",
              "   calculate(sum(MaterialStockLevel[StockLevelStandardPPU_EUR]),",
              "   MaterialStockLevel[ReportingDate] = MaterialStockLevel[MaxDate])",
              ")"
            ],
            "lineageTag": "61868f36-184a-4085-afe3-d56e32f816b2"
          },
          {
            "name": "StockQuantityPM_",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockQuantity_Qty",
            "expression": [
              "--calculate(sum(MaterialStockLevel[StockLevelQtyInBaseUnit]),month(MaterialStockLevel[ReportingDate]) = month(MaterialStockLevel[MaxDate])-1)",
              "CALCULATE(",
              "\tsum(MaterialStockLevel[StockLevelQtyInBaseUnit]),",
              "\tPREVIOUSMONTH(MaterialStockLevel[ReportingDate]), all('Calendar')",
              ")"
            ],
            "lineageTag": "cae0a7ca-1ec2-451d-a80c-8accfba8b595"
          },
          {
            "name": "StockValue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockValue",
            "expression": [
              "IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Local Currency\",sum(MaterialStockLevel[StockLevelStandardPPU]),",
              "        \"Group Currency EUR\", sum(MaterialStockLevel[StockLevelStandardPPU_EUR]),",
              "        \"Group Currency USD\", sum(MaterialStockLevel[StockLevelStandardPPU_USD]",
              "    ),",
              "   sum(MaterialStockLevel[StockLevelStandardPPU_EUR])",
              "))"
            ],
            "lineageTag": "cb04ac37-48f1-453a-a947-06a1d6ee6a4d"
          },
          {
            "name": "OBD Qty (Pro)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "OBD",
            "expression": "calculate(sum(MaterialDocumentItem[ConsumptionQtyOBDProInBaseUnit]))",
            "lineageTag": "23e14e5f-9b86-4521-810f-cd904d6db125"
          },
          {
            "name": "OBD Pro %",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "OBD",
            "expression": "[OBD Qty (Pro)]/[ConsumptionQuantity]",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "56f61dde-41d6-4c2c-be80-84633a25908d"
          },
          {
            "name": "KPI",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(",
              "    HASONEVALUE(srv_SelectKPI[KPI]),",
              "    SWITCH(",
              "        VALUES(srv_SelectKPI[KPI]),",
              "        \"Stock Quantity\", round([StockQuantity],2),",
              "        \"Stock Value\", round(calculate([StockValue],MaterialStockLevel[ReportingDate] = MaterialStockLevel[MaxDate]),2)",
              "    ),",
              "   round(calculate([StockValue],MaterialStockLevel[ReportingDate] = MaterialStockLevel[MaxDate]),2)",
              ")"
            ],
            "lineageTag": "05aea8dd-82fb-469a-9a8b-d609a28539c0"
          },
          {
            "name": "ProductRankTable",
            "displayFolder": "Rank",
            "expression": "rankx(all(MaterialStockLevel),MaterialStockLevel[StockLevel],1,DESC,Dense)",
            "formatString": "0",
            "lineageTag": "b06b21ea-19af-4943-b3a0-821184db4e77"
          },
          {
            "name": "NumberOfStockItemsPM",
            "displayFolder": "NumberOfStockItems",
            "expression": [
              "--calculate([NumberOfStockItems],month(MaterialStockLevel[ReportingDate])=month(MaterialStockLevel[MaxDate])-1)",
              "",
              "CALCULATE(",
              "\t[NumberOfStockItems],",
              "\tPREVIOUSMONTH(MaterialStockLevel[ReportingDate]), all('Calendar')",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "45817bb1-2241-4177-a9fa-4ece585bea2a"
          },
          {
            "name": "DeltaNumberOfStockItems",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Delta",
            "expression": "if(divide([NumberOfStockItems],[NumberOfStockItemsPM],0)=0,0,divide([NumberOfStockItems],[NumberOfStockItemsPM],0)-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "283d930a-561d-45cb-b4e7-a03ce442f476"
          },
          {
            "name": "NumberOfStockItemsCM",
            "displayFolder": "NumberOfStockItems",
            "expression": "calculate(DISTINCTCOUNT(MaterialStockLevel[MaterialID]),ROUND(MaterialStockLevel[StockLevel], 6) >0,all(dimProductCalculated[ProductID_NameCalculated]),MaterialStockLevel[ReportingDate] = MaterialStockLevel[MaxDate])",
            "formatString": "0",
            "lineageTag": "0be0bb8e-fbf3-41ff-9661-04eb710450b0"
          },
          {
            "name": "MsgCurrentCurrency",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "var CurrencyCount = calculate(DISTINCTCOUNT(MaterialDocumentItem[CompanyCodeCurrency]))",
              "var CurrencyType_ = max('Currency'[CurrencyType])",
              "return",
              "IF(CurrencyType_ = \"Group Currency EUR\", \"Amounts currency: EUR\", if( CurrencyType_ = \"Group Currency USD\", \"Amounts currency: USD\", if(CurrencyCount=1, \"Amounts currency: \"&MAX(MaterialDocumentItem[CompanyCodeCurrency]), \"Amounts currency: Multiple currencies in data selection\")))"
            ],
            "lineageTag": "cb873728-7e4f-4a8a-84d3-506e017011ad"
          },
          {
            "name": "CurrentCurrency_Int",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "if([MsgCurrentCurrency]=\"Amounts currency: Multiple currencies in data selection\", 0, 1)"
            ],
            "formatString": "0",
            "lineageTag": "aa5cbbc8-9c54-4291-ac2c-d2e5927b795a"
          },
          {
            "name": "TurnInQty_Product12M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockTurn",
            "expression": "if([NotificationProduct]=0,CALCULATE([StockTurnInQty2], datediff('Calendar'[Date], today(), month) <13))",
            "lineageTag": "425dfdfb-1f4a-43c9-9070-d6d410adfac5"
          },
          {
            "name": "Bucket_maxx",
            "expression": "MAXX(MaterialDocumentItem, MaterialDocumentItem[BucketRemaining])",
            "lineageTag": "c4ff9f62-090a-48e1-9d9d-5fe21c84cf40"
          },
          {
            "name": "ProductRank1_2",
            "displayFolder": "Rank",
            "expression": [
              "",
              "Var _FilteredTableTop=addcolumns(SUMMARIZE(allselected(MaterialDocumentItem), dimProductCalculated[ProductID_NameCalculated], MaterialDocumentItem[MaterialBaseUnitID])",
              ",\"Sum\",[StockRemaining2_W998]--, \"Qty\", [ConsumptionQuantity]",
              ") ",
              "-- by lowest weeks remaining ",
              "Var _FilteredTableFlop=addcolumns(SUMMARIZE(allselected(MaterialStockLevel),dimProductCalculated[ProductID_NameCalculated])",
              ",\"Sum\", [StockValueLatestByLastPPU])",
              "-- from highest to lowest by stock value",
              "var Rank_Top=ADDCOLUMNS(_FilteredTableTop,\"RNK\",",
              "                            if(--AND(",
              "                              not(isblank([Sum])--, not(isblank([Qty]))",
              "                            ),",
              "                            RANKX(_FilteredTableTop,[Sum],,ASC,skip)",
              "                            --calculate(rankx(_FilteredTableTop, calculate([StockRemaining],all('MaterialDocumentItem'[Bucket])),,ASC,skip))",
              "                            )",
              ")",
              "var Rank_Flop=ADDCOLUMNS(_FilteredTableFlop,\"RNK\",",
              "                            if(not(isblank([Sum])),",
              "                            --RANKX(_FilteredTableFlop,[Sum],,DESC,skip)",
              "                            calculate(rankx(_FilteredTableFlop, calculate([StockValueLatestByLastPPU],all('UnitOfMeasure'[UnitOfMeasureID]",
              "                            )",
              "                            ),,DESC,skip))",
              "                            )",
              ")",
              "",
              "return",
              "SWITCH(",
              "    SELECTEDVALUE(srv_TopFlop[SelectValue]),",
              "    \"Top\", MAXX(FILTER(",
              "       Rank_Top",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK]),",
              "",
              " ",
              "   \"Flop\", MAXX(FILTER(",
              "       Rank_Flop",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "86c58ccc-a356-42fb-b603-0dc458b655fe"
          },
          {
            "name": "#OpenOrder",
            "displayFolder": "OpenOrder",
            "expression": [
              "",
              "CALCULATE(DISTINCTCOUNT(OrderItem[SalesOrderID]), OrderItem[ItemBillingIncompletionStatus] <> \"Complete\" && OrderItem[OverallSDProcessStatus]<>\"Completed\" && OrderItem[SDDocumentRejectionStatus] <> \"Fully Rejected\")"
            ],
            "formatString": "0",
            "lineageTag": "f36f61b4-c773-4882-ba30-e0648ce18a51"
          },
          {
            "name": "$OpenOrder",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "OpenOrder",
            "expression": [
              "",
              "CALCULATE(SUM(OrderItem[NetAmount]), (OrderItem[OverallSDProcessStatus]<>\"Completed\" && OrderItem[SDDocumentRejectionStatus] <> \"Fully Rejected\" && OrderItem[ItemBillingIncompletionStatus] <> \"Complete\" ))"
            ],
            "lineageTag": "4fb16b47-2500-40f5-9030-9a8f8e1397e1"
          },
          {
            "name": "SelectedValue_Country",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( Plant[SalesOrg_Country] ),",
              "    CONCATENATEX ( FILTERS ( Plant[SalesOrg_Country]), Plant[SalesOrg_Country], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "07ad46c1-c4e3-42b6-bab2-4e0b6b0d87a1"
          },
          {
            "name": "SelectedValue_Product_L1",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Product'[Product_L1_Pillar] ),",
              "    CONCATENATEX ( FILTERS ( 'Product'[Product_L1_Pillar]), 'Product'[Product_L1_Pillar], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "0eea23ea-5f12-450f-a62a-a5e87fbdced6"
          },
          {
            "name": "SelectedValue_Product_L2",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Product'[Product_L2_Group] ),",
              "    CONCATENATEX ( FILTERS ( 'Product'[Product_L2_Group]), 'Product'[Product_L2_Group], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "26fe992b-2e43-47ae-8a3a-6287c85a875c"
          },
          {
            "name": "SelectedValue_Product_L3",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Product'[Product_L3_Type] ),",
              "    CONCATENATEX ( FILTERS ( 'Product'[Product_L3_Type]), 'Product'[Product_L3_Type], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "cb268094-186a-4835-965f-5e61ed0a04fd"
          },
          {
            "name": "SelectedValue_Product_L4",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Product'[Product_L4_Family] ),",
              "    CONCATENATEX ( FILTERS ( 'Product'[Product_L4_Family]), 'Product'[Product_L4_Family], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "08a8848f-4a51-4f36-9c93-e816fd41af58"
          },
          {
            "name": "SelectedValue_Product_L5",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Product'[Product_L5_SubFamily] ),",
              "    CONCATENATEX ( FILTERS ( 'Product'[Product_L5_SubFamily]), 'Product'[Product_L5_SubFamily], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "8532a953-936c-4d95-b0d8-83ef4bdcad9f"
          },
          {
            "name": "SelectedValue_ConsumptionType",
            "displayFolder": "SelectedValue_",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'MaterialDocumentItem'[ConsumptionType] ),",
              "    CONCATENATEX ( FILTERS ( 'MaterialDocumentItem'[ConsumptionType] ), 'MaterialDocumentItem'[ConsumptionType] , \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "fd0fc632-b731-4d59-ad39-cfc35da96cca"
          },
          {
            "name": "StockRemainingDays2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Remainings",
            "expression": [
              "--divide([StockQuantity2],[ConsumptionQuantity12M],0) *365",
              "divide([StockQuantityToDate],[ConsumptionQuantity12M],0)*365"
            ],
            "formatString": "0",
            "lineageTag": "3ea73bfb-4ada-4666-8baa-30be430a3664"
          },
          {
            "name": "StockRemainingDays",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Remainings",
            "expression": "divide([StockQuantity2],[ConsumptionQuantity12M],0) *365",
            "lineageTag": "24e85571-1b32-48e9-8524-986f975dd485"
          },
          {
            "name": "StockRemainingD998",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Remainings",
            "expression": [
              "",
              "--LOGIC",
              "-- Any item that has more than 9998 months remaining BUT has some consumption should be capped at 9998 months remaining.",
              "--No movement is an item that has no consumption we should give the value of months remaining to 9999",
              "",
              "VAR months_remaining_var = AVERAGEX(MaterialDocumentItem, MaterialDocumentItem[StockRemainingMonths])",
              "VAR year_remaining_var = AVERAGEX(MaterialDocumentItem, MaterialDocumentItem[StockRemainingYears])",
              "",
              "RETURN ",
              "IF([ConsumptionQuantity]<>0.00, ",
              "                    IF (",
              "                        months_remaining_var >=9998, \"9998\", year_remaining_var*365), ",
              "    \"9999\"",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "822da33c-a227-401d-bdf4-33da7f0a91de"
          },
          {
            "name": "StockRemainingM_CC",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Remainings",
            "expression": [
              "",
              "--LOGIC",
              "-- Any item that has more than 9998 months remaining BUT has some consumption should be capped at 9998 months remaining.",
              "--No movement is an item that has no consumption we should give the value of months remaining to 9999",
              "VAR months_remaining_var = AVERAGEX(MaterialDocumentItem, MaterialDocumentItem[StockRemainingMnths])",
              "VAR year_remaining_var = AVERAGEX(MaterialDocumentItem, MaterialDocumentItem[StockRemainingYears])",
              "",
              "RETURN ",
              "IF([ConsumptionQuantity]<>0.00, ",
              "                    IF (",
              "                        months_remaining_var >=9998, \"9998\", months_remaining_var), ",
              "    \"9999\"",
              ")"
            ],
            "lineageTag": "3022cb17-db7e-4978-9b68-b52496bd8247"
          },
          {
            "name": "StockRemainingM9998_MSL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Remainings",
            "expression": [
              "",
              "--LOGIC",
              "-- Any item that has more than 9998 months remaining BUT has some consumption should be capped at 9998 months remaining.",
              "--No movement is an item that has no consumption we should give the value of months remaining to 9999",
              "",
              "VAR months_remaining_var = ",
              "",
              "CALCULATE(SUMX(MaterialStockLevel, MaterialStockLevel[RemainingM]), MaterialStockLevel[ReportingDate] = MaterialStockLevel[LastDate])",
              "---VAR no_consumption =  and(not(ISBLANK([ConsumptionQuantity])), [ConsumptionQuantity] > 0)  ",
              "RETURN ",
              "IF([ConsumptionQuantity]<>0.00, ",
              "                    IF (",
              "                        months_remaining_var >=9998, \"9998\", months_remaining_var), ",
              "    \"9999\"",
              ")"
            ],
            "lineageTag": "0f38baf9-36d6-4193-a4ad-c72d7c2e9ad3"
          },
          {
            "name": "StockRemainingM_SC",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Remainings",
            "expression": [
              "",
              "IF(DIVIDE([QtyLatest],CALCULATE(SUM(MaterialStockLevel[Prev12MConsumptionQty])),0)=0,BLANK(),DIVIDE([QtyLatest],CALCULATE(SUM(MaterialStockLevel[Prev12MConsumptionQty])),0)) *12",
              "--LOGIC",
              "-- Any item that has more than 9998 months remaining BUT has some consumption should be capped at 9998 months remaining.",
              "--No movement is an item that has no consumption we should give the value of months remaining to 9999",
              "",
              "// VAR months_remaining_var = AVERAGEX(MaterialDocumentItem, MaterialDocumentItem[StockRemainingYears])",
              "",
              "// RETURN ",
              "// IF([ConsumptionQuantity]<>0.00, ",
              "//                     IF (",
              "//                         months_remaining_var >=9998, \"9998\", months_remaining_var), ",
              "//     \"9999\"",
              "// )"
            ],
            "lineageTag": "0c66b7c0-aa27-4f6d-8d9f-309c7e4ac739"
          },
          {
            "name": "StockRemainingMaxxMonths",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Remainings",
            "expression": [
              "AVERAGEX(MaterialDocumentItem, MaterialDocumentItem[StockRemainingMnths])",
              "--[StockRemaining2]"
            ],
            "lineageTag": "e3bb0347-2dba-4405-8eb3-2ff2982c956f"
          },
          {
            "name": "StockRemainingMaxxYears",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Remainings",
            "expression": [
              "SUMX(MaterialDocumentItem, MaterialDocumentItem[StockRemainingWeeks])",
              "--[StockRemaining]"
            ],
            "lineageTag": "ce5119a9-9a95-40b6-875d-8944832893d5"
          },
          {
            "name": "StockValueEoM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockValue",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Local Currency\", CALCULATE(sum(MaterialDocumentItem[MatlStkChangeStandardValue]), ENDOFMONTH('Calendar'[Date (bins)])),",
              "        \"Group Currency EUR\", CALCULATE(sum(MaterialDocumentItem[MatlStkChangeStandardValue_EUR]), ENDOFMONTH('Calendar'[Date (bins)])),",
              "        \"Group Currency USD\", CALCULATE(sum(MaterialDocumentItem[MatlStkChangeStandardValue_USD]), ENDOFMONTH('Calendar'[Date (bins)]))",
              "    ),",
              "   sum(MaterialDocumentItem[MatlStkChangeStandardValue_EUR])",
              ")"
            ],
            "lineageTag": "7f2b9c2d-837a-45e5-81e6-022c163fc269"
          },
          {
            "name": "StockTurnInValueEoM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockTurn",
            "expression": "divide([ConsumptionValue_byLatestPPU_dynamic],[StockValueEoM],0)",
            "lineageTag": "8fcf4c4c-3f29-48ab-820e-27455e0fa266"
          },
          {
            "name": "ValuationArea",
            "expression": "CALCULATE( MAXX(ProductValuationPUP,ProductValuationPUP[ValuationArea]), CROSSFILTER('dimProductCalculated'[ProductIDCalculated], ProductValuationPUP[ProductID], both))",
            "lineageTag": "9cd0682d-2f69-4666-8de2-d0b987b70fea"
          },
          {
            "name": "StockPricePerUnit_Latest_EUR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Price",
            "expression": [
              "",
              "// IF(",
              "//     HASONEVALUE('Currency'[CurrencyType]),",
              "//     SWITCH(",
              "//         VALUES('Currency'[CurrencyType]),",
              "//         \"Stock Price\", CALCULATE(MAXX(ProductValuationPUP, ProductValuationPUP[StockPricePerUnit]), ALL('Calendar')),",
              "//         \"Stock Price EUR\", CALCULATE(MAXX(ProductValuationPUP, ProductValuationPUP[StockPricePerUnit_EUR]), ALL('Calendar'))",
              "//        -- , \"Stock Price USD\", sum(ProductValuationPUP[StockPricePerUnit_EUR])",
              "//     ),",
              "//    CALCULATE(MAXX(ProductValuationPUP, ProductValuationPUP[StockPricePerUnit_EUR]), ALL('Calendar'))",
              "// )",
              "// CALCULATE(ProductValuationPUP, ProductValuationPUP[StockPricePerUnit]--, --ALL('Calendar')",
              "// )",
              "VAR LastDay =",
              "    CALCULATE (",
              "        MAX ( ProductValuationPUP[Date] ),",
              "        NOT ISBLANK ( ProductValuationPUP[StockPricePerUnit_EUR] )",
              "    )",
              "VAR LastPrice =",
              "    CALCULATE (",
              "        MAX ( ProductValuationPUP[StockPricePerUnit_EUR] ),",
              "        ProductValuationPUP[Date] = LastDay,",
              "        NOT ISBLANK ( ProductValuationPUP[StockPricePerUnit_EUR] )",
              "    )",
              "RETURN",
              "    CALCULATE ( MAX ( ProductValuationPUP[StockPricePerUnit_EUR] ), ProductValuationPUP[StockPricePerUnit_EUR] = LastPrice )"
            ],
            "lineageTag": "a5a0167a-4224-4398-91b5-7fbfd2eb6005"
          },
          {
            "name": "UnitOfMeasureMAXX",
            "expression": "MAXX(UnitOfMeasure, UnitOfMeasure[UnitOfMeasureID])",
            "lineageTag": "ebb18a02-20ee-4b2a-90f9-aa7aa313843a"
          },
          {
            "name": "LatestPUP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Price",
            "expression": "CALCULATE([StockPrice],CROSSFILTER('Calendar'[Date],ProductValuationPUP[Date], Both))",
            "isHidden": true,
            "lineageTag": "b2f678cc-8d29-4779-b2a0-3ff7c7c78403"
          },
          {
            "name": "StockQuantityByMonths",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockQuantity_Qty",
            "expression": [
              "CALCULATE(",
              "    SUM(MaterialStockLevel[StockLevelQtyInBaseUnit]), ",
              "    ALLEXCEPT('Calendar'",
              "    --, DATEDIFF( TODAY(), ",
              "    ,'Calendar'[Date]",
              "    --, MONTH    ) < 6)",
              "    ))"
            ],
            "lineageTag": "f3ae107f-abb5-4433-b3be-d6b205707a8f"
          },
          {
            "name": "StockLevelStandardPPU2_byMonths",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockQuantity_Qty",
            "expression": "SUM(MaterialStockLevel[StockLevelStandardPPU])",
            "lineageTag": "6e7ee3d9-f78b-4dd7-ad64-ec84e390976a"
          },
          {
            "name": "StockLevelStandardPPU2_byMonths_EUR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockQuantity_Qty",
            "expression": "SUM(MaterialStockLevel[StockLevelStandardPPU_EUR])",
            "lineageTag": "c542b907-97e3-4151-a8ba-7c9487cf7ba3"
          },
          {
            "name": "StockLevelStandardPPU2_byMonths_USD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockQuantity_Qty",
            "expression": "SUM(MaterialStockLevel[StockLevelStandardPPU_USD])",
            "lineageTag": "7c52694b-9389-47f9-9e50-f9e8cea131cc"
          },
          {
            "name": "StockValueByMonths",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockValue",
            "expression": [
              "IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Local Currency\", CALCULATE([StockLevelStandardPPU2_byMonths]),",
              "        \"Group Currency EUR\", CALCULATE([StockLevelStandardPPU2_byMonths_EUR]),",
              "        \"Group Currency USD\", CALCULATE([StockLevelStandardPPU2_byMonths_USD])",
              "    ),",
              "   CALCULATE([StockLevelStandardPPU2_byMonths_EUR])",
              ")"
            ],
            "lineageTag": "dd3401cf-8061-4204-bbad-e38d719a3d6a"
          },
          {
            "name": "StockRemaining2_M998",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Remainings",
            "expression": [
              "--divide([StockQuantity2],[ConsumptionQuantity12M],0) *12",
              "",
              "VAR months_remaining_var = divide([QtyLatest],[ConsumptionQuantity12M],0) * 12 -- divide([StockQuantityToDate],[ConsumptionQuantity12M],0) ",
              "VAR years_remaining_var = divide([QtyLatest],[ConsumptionQuantity12M],0) -- divide([StockQuantityToDate],[ConsumptionQuantity12M],0) ",
              "  ",
              "RETURN ",
              "IF(AND(NOT(ISBLANK([ConsumptionQuantity])), [ConsumptionQuantity]<>0.00), ",
              "                    IF (",
              "                        months_remaining_var >=9998, \"9998\", months_remaining_var), ",
              "    \"9999\"",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "1f1206ae-bb13-4e5e-bbe8-82ef1d2f1a53"
          },
          {
            "name": "StockRemaining2_D998",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Remainings",
            "expression": [
              "--divide([StockQuantity2],[ConsumptionQuantity12M],0) *12",
              "",
              "VAR months_remaining_var = divide([QtyLatest],[ConsumptionQuantity12M],0) *12 -- divide([StockQuantityToDate],[ConsumptionQuantity12M],0) ",
              "VAR years_remaining_var = divide([QtyLatest],[ConsumptionQuantity12M],0) -- divide([StockQuantityToDate],[ConsumptionQuantity12M],0) ",
              "---VAR no_consumption =  and(not(ISBLANK([ConsumptionQuantity])), [ConsumptionQuantity] > 0)  ",
              "RETURN ",
              "IF(AND(NOT(ISBLANK([ConsumptionQuantity])), [ConsumptionQuantity]<>0.00), ",
              "                    IF (",
              "                        months_remaining_var >=9998, \"9998\", years_remaining_var * 365), ",
              "    \"9999\"",
              ")"
            ],
            "lineageTag": "475d9187-13dc-4bd4-af5f-f5ed8ca83b27"
          },
          {
            "name": "StockRemaining2_W998",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Remainings",
            "expression": [
              "--divide([StockQuantity2],[ConsumptionQuantity12M],0) *12",
              "",
              "VAR months_remaining_var = divide([QtyLatest],[ConsumptionQuantity12M],0) *12 -- divide([StockQuantityToDate],[ConsumptionQuantity12M],0) ",
              "VAR years_remaining_var = divide([QtyLatest],[ConsumptionQuantity12M],0) -- divide([StockQuantityToDate],[ConsumptionQuantity12M],0) ",
              " ",
              "RETURN ",
              "IF(AND(NOT(ISBLANK([ConsumptionQuantity])), [ConsumptionQuantity]<>0.00), ",
              "                    IF (",
              "                        months_remaining_var >=9998, \"9998\", years_remaining_var * 52), ",
              "    \"9999\"",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "b2e08059-6fa6-4240-a50a-5e6aae7217c7"
          },
          {
            "name": "StockRemaining2_Y998",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Remainings",
            "expression": [
              "--divide([StockQuantity2],[ConsumptionQuantity12M],0) *12",
              "",
              "VAR months_remaining_var = divide([QtyLatest],[ConsumptionQuantity12M],0) * 12 -- divide([StockQuantityToDate],[ConsumptionQuantity12M],0) * 12",
              "VAR years_remaining_var = divide([QtyLatest],[ConsumptionQuantity12M],0) --divide([StockQuantityToDate],[ConsumptionQuantity12M],0)",
              "---VAR no_consumption =  and(not(ISBLANK([ConsumptionQuantity])), [ConsumptionQuantity] > 0)  ",
              "RETURN ",
              "IF(AND(NOT(ISBLANK([ConsumptionQuantity])),[ConsumptionQuantity]<>0.00), ",
              "                    IF (",
              "                        months_remaining_var >=9998, \"9998\", years_remaining_var), ",
              "    \"9999\"",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "3cfc0a80-ebcc-4e3f-9fb5-cf8a417f016b"
          },
          {
            "name": "StockPricePerUnit_Latest",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Price",
            "expression": [
              "",
              "// IF(",
              "//     HASONEVALUE('Currency'[CurrencyType]),",
              "//     SWITCH(",
              "//         VALUES('Currency'[CurrencyType]),",
              "//         \"Stock Price\", CALCULATE(MAXX(ProductValuationPUP, ProductValuationPUP[StockPricePerUnit]), ALL('Calendar')),",
              "//         \"Stock Price EUR\", CALCULATE(MAXX(ProductValuationPUP, ProductValuationPUP[StockPricePerUnit_EUR]), ALL('Calendar'))",
              "//        -- , \"Stock Price USD\", sum(ProductValuationPUP[StockPricePerUnit_EUR])",
              "//     ),",
              "//    CALCULATE(MAXX(ProductValuationPUP, ProductValuationPUP[StockPricePerUnit_EUR]), ALL('Calendar'))",
              "// )",
              "// CALCULATE(ProductValuationPUP, ProductValuationPUP[StockPricePerUnit]--, --ALL('Calendar')",
              "// )",
              "VAR LastDay =",
              "    CALCULATE (",
              "        MAX ( ProductValuationPUP[Date] ),",
              "        NOT ISBLANK ( ProductValuationPUP[StockPricePerUnit] )",
              "    )",
              "VAR LastPrice =",
              "    CALCULATE (",
              "        MAX ( ProductValuationPUP[StockPricePerUnit] ),",
              "        ProductValuationPUP[Date] = LastDay,",
              "        NOT ISBLANK ( ProductValuationPUP[StockPricePerUnit] )",
              "    )",
              "RETURN",
              "    CALCULATE ( MAX ( ProductValuationPUP[StockPricePerUnit] ), ProductValuationPUP[StockPricePerUnit] = LastPrice )"
            ],
            "lineageTag": "e276a8c4-4cc1-4aaf-992b-547585d57a49"
          },
          {
            "name": "StockPricePerUnit_Latest_USD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Price",
            "expression": [
              "",
              "// IF(",
              "//     HASONEVALUE('Currency'[CurrencyType]),",
              "//     SWITCH(",
              "//         VALUES('Currency'[CurrencyType]),",
              "//         \"Stock Price\", CALCULATE(MAXX(ProductValuationPUP, ProductValuationPUP[StockPricePerUnit]), ALL('Calendar')),",
              "//         \"Stock Price EUR\", CALCULATE(MAXX(ProductValuationPUP, ProductValuationPUP[StockPricePerUnit_EUR]), ALL('Calendar'))",
              "//        -- , \"Stock Price USD\", sum(ProductValuationPUP[StockPricePerUnit_EUR])",
              "//     ),",
              "//    CALCULATE(MAXX(ProductValuationPUP, ProductValuationPUP[StockPricePerUnit_EUR]), ALL('Calendar'))",
              "// )",
              "// CALCULATE(ProductValuationPUP, ProductValuationPUP[StockPricePerUnit]--, --ALL('Calendar')",
              "// )",
              "VAR LastDay =",
              "    CALCULATE (",
              "        MAX ( ProductValuationPUP[Date] ),",
              "        NOT ISBLANK ( ProductValuationPUP[StockPricePerUnit_USD] )",
              "    )",
              "VAR LastPrice =",
              "    CALCULATE (",
              "        MAX ( ProductValuationPUP[StockPricePerUnit_USD] ),",
              "        ProductValuationPUP[Date] = LastDay,",
              "        NOT ISBLANK ( ProductValuationPUP[StockPricePerUnit_USD] )",
              "    )",
              "RETURN",
              "    CALCULATE ( MAX ( ProductValuationPUP[StockPricePerUnit_USD] ), ProductValuationPUP[StockPricePerUnit_USD] = LastPrice )"
            ],
            "lineageTag": "f6349c5c-1093-486f-bfac-d84da9bb4172"
          },
          {
            "name": "#Order12M",
            "expression": "CALCULATE(DISTINCTCOUNT(OrderItem[SalesOrderID]),datediff(OrderItem[CreationDate],today(),WEEK)<=52)",
            "formatString": "0",
            "lineageTag": "2a8caf87-4271-48b9-a998-4a04a4e1538a"
          },
          {
            "name": "StockValueLatest",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockValue",
            "expression": [
              "IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Local Currency\", calculate(sum(MaterialStockLevel[StockLevelStandardPPU]),MaterialStockLevel[ReportingDate] = MaterialStockLevel[LastDate], all(MaterialDocumentItem[Application])),",
              "        \"Group Currency EUR\", calculate(sum(MaterialStockLevel[StockLevelStandardPPU_EUR]),MaterialStockLevel[ReportingDate] = MaterialStockLevel[LastDate], all(MaterialDocumentItem[Application])),",
              "        \"Group Currency USD\", calculate(sum(MaterialStockLevel[StockLevelStandardPPU_USD]),MaterialStockLevel[ReportingDate] = MaterialStockLevel[LastDate], all(MaterialDocumentItem[Application]))",
              "    ),",
              "   calculate(sum(MaterialStockLevel[StockLevelStandardPPU_EUR]),",
              "   MaterialStockLevel[ReportingDate] = MaterialStockLevel[LastDate], all(MaterialDocumentItem[Application]))",
              ")"
            ],
            "lineageTag": "3cae4ae1-006a-4608-b34a-c9068ee910ed"
          },
          {
            "name": "PPU Latest",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Price",
            "expression": [
              "",
              " IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Local Currency\",",
              "        _Measures[StockPricePerUnit_Latest],",
              "        --CALCULATE(_Measures[StockPricePerUnit_Latest], CROSSFILTER(ProductValuationPUP[ValuationAreaID],MaterialDocumentItem[PlantID], Both)),",
              "        \"Group Currency EUR\", ",
              "        _Measures[StockPricePerUnit_Latest_EUR]",
              "        --calculate(_Measures[StockPricePerUnit_Latest_EUR], CROSSFILTER(ProductValuationPUP[ValuationAreaID],MaterialDocumentItem[PlantID], Both))",
              "        --,\"Group Currency USD\", sum(_Measures[StockPricePerUnit_Latest]]",
              "        ,",
              "        \"Group Currency USD\", ",
              "        _Measures[StockPricePerUnit_Latest_USD]",
              "        --calculate(_Measures[StockPricePerUnit_Latest_EUR], CROSSFILTER(ProductValuationPUP[ValuationAreaID],MaterialDocumentItem[PlantID], Both))",
              "        --,\"Group Currency USD\", sum(_Measures[StockPricePerUnit_Latest]]",
              "    ),",
              "   _Measures[StockPricePerUnit_Latest_EUR]",
              " )"
            ],
            "formatString": "0.00",
            "lineageTag": "e6274028-2800-4f2d-8ed7-0a87e8344824"
          },
          {
            "name": "ConsumptionQuantity12M_byLatestPrice",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Consumption",
            "expression": "CALCULATE([ConsumptionQuantity12M] * [PPU Latest])",
            "lineageTag": "864cec9c-36f1-43d4-a5b8-77f6e0fe0ac4"
          },
          {
            "name": "QtyLatest",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "calculate(sum(MaterialStockLevel[StockLevelQtyInBaseUnit]),",
              "MaterialStockLevel[ReportingDate] = MaterialStockLevel[LastDate])"
            ],
            "lineageTag": "8f99e18a-9425-4320-8981-3951bbb955f9"
          },
          {
            "name": "DeltaStockTurnInValue",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Delta",
            "expression": "if(divide([StockTurnInValue],[StockTurnInValuePM],0)=0,0,divide([StockTurnInValue],[StockTurnInValuePM],0)-1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "22f5a6e3-5752-4e81-8f09-321701f91dd5"
          },
          {
            "name": "ConsumptionValue12M-PM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Consumption",
            "expression": "calculate([ConsumptionValue],datediff('Calendar'[Date],today(),month)<14,datediff('Calendar'[Date],today(),month)>=1)",
            "lineageTag": "a6fee2a8-c971-4748-8746-ed92376fad67"
          },
          {
            "name": "StockTurnInValuePM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockTurn",
            "expression": "divide([ConsumptionValue12M-PM],[StockValuePM],0)",
            "lineageTag": "a9ecb1f2-20c8-4d64-a5fd-bcf059f62035"
          },
          {
            "name": "MDI_StockPPU_Latest",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Price",
            "expression": [
              "",
              "VAR LastDay =",
              "    CALCULATE (",
              "        MAX ( MaterialDocumentItem[DocumentDate] ),",
              "        NOT ISBLANK ( MaterialDocumentItem[StockPricePerUnit] )",
              "    )",
              "VAR LastPrice =",
              "    CALCULATE (",
              "        MAX ( MaterialDocumentItem[StockPricePerUnit]  ),",
              "        MaterialDocumentItem[DocumentDate] = LastDay,",
              "        NOT ISBLANK ( MaterialDocumentItem[StockPricePerUnit]  )",
              "    )",
              "RETURN",
              "    CALCULATE ( MAX ( MaterialDocumentItem[StockPricePerUnit]  ), MaterialDocumentItem[StockPricePerUnit]  = LastPrice )"
            ],
            "lineageTag": "29d964fc-eff0-45f8-92b5-8c3f27e4e2fa"
          },
          {
            "name": "MDI_StockPPU_Latest_EUR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Price",
            "expression": [
              "",
              "VAR LastDay =",
              "    CALCULATE (",
              "        MAX ( MaterialDocumentItem[DocumentDate] ),",
              "        NOT ISBLANK ( MaterialDocumentItem[StockPricePerUnit_EUR] )",
              "    )",
              "VAR LastPrice =",
              "    CALCULATE (",
              "        MAX ( MaterialDocumentItem[StockPricePerUnit_EUR]  ),",
              "        MaterialDocumentItem[DocumentDate] = LastDay,",
              "        NOT ISBLANK ( MaterialDocumentItem[StockPricePerUnit_EUR]  )",
              "    )",
              "RETURN",
              "    CALCULATE ( MAX ( MaterialDocumentItem[StockPricePerUnit_EUR]  ), MaterialDocumentItem[StockPricePerUnit_EUR]  = LastPrice )"
            ],
            "lineageTag": "09e297d6-386f-482d-944e-f3dbc9dcc869"
          },
          {
            "name": "MDI_StockPPU_Latest_USD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Price",
            "expression": [
              "",
              "VAR LastDay =",
              "    CALCULATE (",
              "        MAX ( MaterialDocumentItem[DocumentDate] ),",
              "        NOT ISBLANK ( MaterialDocumentItem[StockPricePerUnit_USD] )",
              "    )",
              "VAR LastPrice =",
              "    CALCULATE (",
              "        MAX ( MaterialDocumentItem[StockPricePerUnit_USD]  ),",
              "        MaterialDocumentItem[DocumentDate] = LastDay,",
              "        NOT ISBLANK ( MaterialDocumentItem[StockPricePerUnit_USD]  )",
              "    )",
              "RETURN",
              "    CALCULATE ( MAX ( MaterialDocumentItem[StockPricePerUnit_USD]  ), MaterialDocumentItem[StockPricePerUnit_USD]  = LastPrice )"
            ],
            "lineageTag": "7ea7f54c-a22c-4d42-95fd-1238a280ee09"
          },
          {
            "name": "ConsumptionValue_byLatestPPU",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Consumption",
            "expression": "[ConsumptionQuantity12M] * [MDI_StockPPU_Latest]",
            "lineageTag": "c9158502-655c-4efc-9fba-cb33f28c48cd"
          },
          {
            "name": "ConsumptionValue_byLatestPPU_EUR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Consumption",
            "expression": "[ConsumptionQuantity12M] * [MDI_StockPPU_Latest_EUR]",
            "lineageTag": "ad2ad1c7-dfe9-46a8-816d-537971117b28"
          },
          {
            "name": "ConsumptionValue_byLatestPPU_USD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Consumption",
            "expression": "[ConsumptionQuantity12M] * [MDI_StockPPU_Latest_USD]",
            "lineageTag": "afde4eaa-90c7-4ccd-871d-2d102e17f8ef"
          },
          {
            "name": "ConsumptionValue_byLatestPPU_dynamic",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Consumption",
            "expression": [
              "",
              " IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Local Currency\",",
              "        _Measures[ConsumptionValue_byLatestPPU],",
              "        \"Group Currency EUR\", ",
              "        _Measures[ConsumptionValue_byLatestPPU_EUR],",
              "        \"Group Currency USD\", ",
              "        _Measures[ConsumptionValue_byLatestPPU_USD]",
              "    ),",
              "   _Measures[ConsumptionValue_byLatestPPU_EUR]",
              " )"
            ],
            "lineageTag": "f78dc1a8-eac6-4122-aea0-ff117cbfd37e"
          },
          {
            "name": "TurnInValue_Product12M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockTurn",
            "expression": "if([NotificationProduct]=0,CALCULATE([StockTurnInValueEoM], datediff('Calendar'[Date], today(), month) <13))",
            "lineageTag": "ad3a5c8c-d6f8-46db-9484-fc2eee8d8b5b"
          },
          {
            "name": "StockValuebyLastPPU",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockValue",
            "expression": [
              "IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Local Currency\",sum(MaterialStockLevel[StockLevelStandardLastPPU]),",
              "        \"Group Currency EUR\", sum(MaterialStockLevel[StockLevelStandardLastPPU_EUR]),",
              "        \"Group Currency USD\", sum(MaterialStockLevel[StockLevelStandardLastPPU_USD]",
              "    ),",
              "   sum(MaterialStockLevel[StockLevelStandardLastPPU_EUR])",
              "))"
            ],
            "lineageTag": "f45f4d4c-aa4c-4591-a84d-2720ba3ef18f"
          },
          {
            "name": "ConsumptionValue_byLatestPPU_dynamic12M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Consumption",
            "expression": [
              "",
              " IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Local Currency\",",
              "        CALCULATE(_Measures[ConsumptionValue_byLatestPPU], datediff('Calendar'[Date],today(),month)<13),",
              "        \"Group Currency EUR\", ",
              "        CALCULATE(_Measures[ConsumptionValue_byLatestPPU_EUR], datediff('Calendar'[Date],today(),month)<13),",
              "        \"Group Currency USD\", ",
              "        CALCULATE(_Measures[ConsumptionValue_byLatestPPU_USD], datediff('Calendar'[Date],today(),month)<13)",
              "    ),",
              "   _Measures[ConsumptionValue_byLatestPPU_EUR]",
              " )"
            ],
            "lineageTag": "054829cb-8046-47bf-bcc3-25b64ed00667"
          },
          {
            "name": "ConsumptionQuantity12M_byLatestPriceLocation",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Consumption",
            "expression": "CALCULATE(SUM(MaterialDocumentItem[ConsumptionQty]), USERELATIONSHIP(MaterialDocumentItem[nk_StoragePlantID], StorageLocation[nk_StoragePlantID]), datediff('Calendar'[Date],today(),month)<13)",
            "lineageTag": "af878820-3681-4c1b-ae22-a08f4112114c"
          },
          {
            "name": "OBD Qty (Pro) Location",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "OBD",
            "expression": "calculate(sum(MaterialDocumentItem[ConsumptionQtyOBDProInBaseUnit]), USERELATIONSHIP(MaterialDocumentItem[nk_StoragePlantID], StorageLocation[nk_StoragePlantID]))",
            "lineageTag": "25eba07f-9fff-4eaa-a670-1b34dfe11298"
          },
          {
            "name": "OBD Qty (ICPO) Location",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "OBD",
            "expression": "calculate(sum(MaterialDocumentItem[ConsumptionQtyICPOInBaseUnit]), USERELATIONSHIP(MaterialDocumentItem[nk_StoragePlantID], StorageLocation[nk_StoragePlantID]))",
            "lineageTag": "5be74563-28e1-4177-a1f5-ad60202339d6"
          },
          {
            "name": "OBD Qty (SO) Location",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "OBD",
            "expression": "calculate(sum(MaterialDocumentItem[ConsumptionQtySOInBaseUnit]), USERELATIONSHIP(MaterialDocumentItem[nk_StoragePlantID], StorageLocation[nk_StoragePlantID]))",
            "lineageTag": "f6ae90e5-11ab-405d-a4b4-de3eed349861"
          },
          {
            "name": "PPU Latest_raw",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Price",
            "expression": [
              "",
              " IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Local Currency\",",
              "        CALCULATE(SUM(ProductValuationPUP[StockPricePerUnit])),",
              "        \"Group Currency EUR\", ",
              "        CALCULATE(SUM(ProductValuationPUP[StockPricePerUnit_EUR]))",
              "        ,",
              "        \"Group Currency USD\", ",
              "        CALCULATE(SUM(ProductValuationPUP[StockPricePerUnit_USD]))",
              "    ),",
              "   CALCULATE(SUM(ProductValuationPUP[StockPricePerUnit_EUR]))",
              " )"
            ],
            "lineageTag": "a35be939-7dcd-4701-899e-4435b8e88570"
          },
          {
            "name": "ConsumptionValue12M_lastPPU",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate([ConsumptionValue_lastPPU],datediff('Calendar'[Date],today(),month)<13)",
            "lineageTag": "face0ed3-0a05-4706-b60f-08273371ed3b"
          },
          {
            "name": "StockTurnInValue_lastPPU",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "StockTurn",
            "expression": "divide([ConsumptionValue12M_lastPPU],[StockValue],0)",
            "lineageTag": "ecc30c48-c760-45ea-abc4-856f183cedf8"
          },
          {
            "name": "OBD Qty (ICPO) 12M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sum(MaterialDocumentItem[ConsumptionQtyICPOInBaseUnit]), datediff('Calendar'[Date],today(),month)<13)",
            "lineageTag": "37636ae4-4093-4a86-bd2d-73232fcb8b40"
          },
          {
            "name": "OBD Qty (Pro) 12M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sum(MaterialDocumentItem[ConsumptionQtyOBDProInBaseUnit]), datediff('Calendar'[Date],today(),month)<13)",
            "lineageTag": "3ed60e82-3542-4393-93ce-880917840884"
          },
          {
            "name": "OBD Qty (SO) 12M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(sum(MaterialDocumentItem[ConsumptionQtySOInBaseUnit]), datediff('Calendar'[Date],today(),month)<13)",
            "lineageTag": "5a267179-aeb6-450a-853c-4404deb28fb2"
          },
          {
            "name": "ProductRank1_2_zero",
            "displayFolder": "Rank",
            "expression": [
              "",
              "Var _FilteredTableTop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialDocumentItem), dimProductCalculated[ProductID_NameCalculated], MaterialDocumentItem[MaterialBaseUnitID])",
              ",\"Sum\",[StockRemaining2_W998]--, \"Qty\", [ConsumptionQuantity]",
              "), [QtyLatest] >= 0.1 )",
              "",
              "-- by lowest weeks remaining ",
              "Var _FilteredTableFlop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialStockLevel),dimProductCalculated[ProductID_NameCalculated])",
              ",\"Sum\", [StockValueLatestByLastPPU]), ",
              "[QtyLatest] >= 0.1 )",
              "-- from highest to lowest by stock value",
              "var Rank_Top=ADDCOLUMNS(_FilteredTableTop,\"RNK\",",
              "                            if(--AND(",
              "                              not(isblank([Sum])--, not(isblank([Qty]))",
              "                            ),",
              "                            RANKX(_FilteredTableTop,[Sum],,ASC,skip)",
              "                            --calculate(rankx(_FilteredTableTop, calculate([StockRemaining],all('MaterialDocumentItem'[Bucket])),,ASC,skip))",
              "                            )",
              ")",
              "var Rank_Flop=ADDCOLUMNS(_FilteredTableFlop,\"RNK\",",
              "                            if(not(isblank([Sum])),",
              "                            --RANKX(_FilteredTableFlop,[Sum],,DESC,skip)",
              "                            calculate(rankx(_FilteredTableFlop, calculate([StockValueLatestByLastPPU],all('UnitOfMeasure'[UnitOfMeasureID]",
              "                            )",
              "                            ),,DESC,skip))",
              "                            )",
              ")",
              "",
              "return",
              "SWITCH(",
              "    SELECTEDVALUE(srv_TopFlop[SelectValue]),",
              "    \"Top\", MAXX(FILTER(",
              "       Rank_Top",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK]),",
              "",
              " ",
              "   \"Flop\", MAXX(FILTER(",
              "       Rank_Flop",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "125cf027-9c9f-4297-9d5c-3a06b182e914"
          },
          {
            "name": "ProductRank_12Mto18M",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "Var _FilteredTableTop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialDocumentItem), dimProductCalculated[ProductID_NameCalculated], MaterialDocumentItem[MaterialBaseUnitID])",
              ",\"Sum\",[StockRemaining2_W998]), ",
              "AND([StockRemaining2_M998] >= 12, [StockRemaining2_M998] < 18)",
              ")",
              "",
              "-- by lowest weeks remaining ",
              "Var _FilteredTableFlop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialStockLevel),dimProductCalculated[ProductID_NameCalculated])",
              ",\"Sum\", [StockValueLatestByLastPPU]), ",
              "AND([StockRemaining2_M998] >= 12, [StockRemaining2_M998] < 18)",
              ")",
              "",
              "-- from highest to lowest by stock value",
              "var Rank_Top=ADDCOLUMNS(_FilteredTableTop ,\"RNK\",",
              "                            if(",
              "                              not(isblank([Sum])",
              "                            ),",
              "                            RANKX(_FilteredTableTop,[Sum],,ASC,skip)",
              "                            )",
              ")",
              "var Rank_Flop=ADDCOLUMNS(_FilteredTableFlop,\"RNK\",",
              "                            if(not(isblank([Sum])),",
              "                            calculate(rankx(_FilteredTableFlop, calculate([StockValueLatestByLastPPU],all('UnitOfMeasure'[UnitOfMeasureID]",
              "                            )",
              "                            ),,DESC,skip))",
              "                            )",
              ")",
              "",
              "return",
              "SWITCH(",
              "    SELECTEDVALUE(srv_TopFlop[SelectValue]),",
              "    \"Top\", MAXX(FILTER(",
              "       Rank_Top",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK]),",
              "",
              " ",
              "   \"Flop\", MAXX(FILTER(",
              "       Rank_Flop",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "05059a30-e179-45ba-bf5f-d5462b3df060"
          },
          {
            "name": "ProductRank_12Mto18M_zero",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "Var _FilteredTableTop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialDocumentItem), dimProductCalculated[ProductID_NameCalculated], MaterialDocumentItem[MaterialBaseUnitID])",
              ",\"Sum\",[StockRemaining2_W998]), ",
              "AND(",
              "AND([StockRemaining2_M998] >= 12, [StockRemaining2_M998] < 18), ",
              "[QtyLatest] >= 0.1 )",
              ")",
              "",
              "-- by lowest weeks remaining ",
              "Var _FilteredTableFlop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialStockLevel),dimProductCalculated[ProductID_NameCalculated])",
              ",\"Sum\", [StockValueLatestByLastPPU]), ",
              "AND(",
              "AND([StockRemaining2_M998] >= 12, [StockRemaining2_M998] < 18), ",
              "[QtyLatest] >= 0.1 )",
              ")",
              "",
              "-- from highest to lowest by stock value",
              "var Rank_Top=ADDCOLUMNS(_FilteredTableTop ,\"RNK\",",
              "                            if(",
              "                              not(isblank([Sum])",
              "                            ),",
              "                            RANKX(_FilteredTableTop,[Sum],,ASC,skip)",
              "                            )",
              ")",
              "var Rank_Flop=ADDCOLUMNS(_FilteredTableFlop,\"RNK\",",
              "                            if(not(isblank([Sum])),",
              "                            calculate(rankx(_FilteredTableFlop, calculate([StockValueLatestByLastPPU],all('UnitOfMeasure'[UnitOfMeasureID]",
              "                            )",
              "                            ),,DESC,skip))",
              "                            )",
              ")",
              "",
              "return",
              "SWITCH(",
              "    SELECTEDVALUE(srv_TopFlop[SelectValue]),",
              "    \"Top\", MAXX(FILTER(",
              "       Rank_Top",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK]),",
              "",
              " ",
              "   \"Flop\", MAXX(FILTER(",
              "       Rank_Flop",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "43694878-8416-4d56-93be-f07faab4aaa4"
          },
          {
            "name": "ProductRank_18Mto24M",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "Var _FilteredTableTop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialDocumentItem), dimProductCalculated[ProductID_NameCalculated], MaterialDocumentItem[MaterialBaseUnitID])",
              ",\"Sum\",[StockRemaining2_W998]), ",
              "AND([StockRemaining2_M998] >= 18, [StockRemaining2_M998] < 24)",
              ")",
              "",
              "-- by lowest weeks remaining ",
              "Var _FilteredTableFlop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialStockLevel),dimProductCalculated[ProductID_NameCalculated])",
              ",\"Sum\", [StockValueLatestByLastPPU]), ",
              "AND([StockRemaining2_M998] >= 18, [StockRemaining2_M998] < 24)",
              ")",
              "",
              "-- from highest to lowest by stock value",
              "var Rank_Top=ADDCOLUMNS(_FilteredTableTop ,\"RNK\",",
              "                            if(",
              "                              not(isblank([Sum])",
              "                            ),",
              "                            RANKX(_FilteredTableTop,[Sum],,ASC,skip)",
              "                            )",
              ")",
              "var Rank_Flop=ADDCOLUMNS(_FilteredTableFlop,\"RNK\",",
              "                            if(not(isblank([Sum])),",
              "                            calculate(rankx(_FilteredTableFlop, calculate([StockValueLatestByLastPPU],all('UnitOfMeasure'[UnitOfMeasureID]",
              "                            )",
              "                            ),,DESC,skip))",
              "                            )",
              ")",
              "",
              "return",
              "SWITCH(",
              "    SELECTEDVALUE(srv_TopFlop[SelectValue]),",
              "    \"Top\", MAXX(FILTER(",
              "       Rank_Top",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK]),",
              "",
              " ",
              "   \"Flop\", MAXX(FILTER(",
              "       Rank_Flop",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "f3a9b654-9fa3-4fd4-b637-9b4458041295"
          },
          {
            "name": "ProductRank_18Mto24M_zero",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "Var _FilteredTableTop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialDocumentItem), dimProductCalculated[ProductID_NameCalculated], MaterialDocumentItem[MaterialBaseUnitID])",
              ",\"Sum\",[StockRemaining2_W998]), ",
              "AND(",
              "AND([StockRemaining2_M998] >= 18, [StockRemaining2_M998] < 24), ",
              "[QtyLatest] >= 0.1 )",
              ")",
              "",
              "-- by lowest weeks remaining ",
              "Var _FilteredTableFlop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialStockLevel),dimProductCalculated[ProductID_NameCalculated])",
              ",\"Sum\", [StockValueLatestByLastPPU]), ",
              "AND(",
              "AND([StockRemaining2_M998] >= 18, [StockRemaining2_M998] < 24), ",
              "[QtyLatest] >= 0.1 )",
              ")",
              "",
              "-- from highest to lowest by stock value",
              "var Rank_Top=ADDCOLUMNS(_FilteredTableTop ,\"RNK\",",
              "                            if(",
              "                              not(isblank([Sum])",
              "                            ),",
              "                            RANKX(_FilteredTableTop,[Sum],,ASC,skip)",
              "                            )",
              ")",
              "var Rank_Flop=ADDCOLUMNS(_FilteredTableFlop,\"RNK\",",
              "                            if(not(isblank([Sum])),",
              "                            calculate(rankx(_FilteredTableFlop, calculate([StockValueLatestByLastPPU],all('UnitOfMeasure'[UnitOfMeasureID]",
              "                            )",
              "                            ),,DESC,skip))",
              "                            )",
              ")",
              "",
              "return",
              "SWITCH(",
              "    SELECTEDVALUE(srv_TopFlop[SelectValue]),",
              "    \"Top\", MAXX(FILTER(",
              "       Rank_Top",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK]),",
              "",
              " ",
              "   \"Flop\", MAXX(FILTER(",
              "       Rank_Flop",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "b0fbe2b2-fff5-45a4-8c68-6ee00de92ffa"
          },
          {
            "name": "ProductRank_3Mto6M",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "Var _FilteredTableTop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialDocumentItem), dimProductCalculated[ProductID_NameCalculated], MaterialDocumentItem[MaterialBaseUnitID])",
              ",\"Sum\",[StockRemaining2_W998]), ",
              "AND([StockRemaining2_M998] >= 3, [StockRemaining2_M998] < 6)",
              ")",
              "",
              "-- by lowest weeks remaining ",
              "Var _FilteredTableFlop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialStockLevel),dimProductCalculated[ProductID_NameCalculated])",
              ",\"Sum\", [StockValueLatestByLastPPU]), ",
              "AND([StockRemaining2_M998] >= 3, [StockRemaining2_M998] < 6)",
              ")",
              "",
              "-- from highest to lowest by stock value",
              "var Rank_Top=ADDCOLUMNS(_FilteredTableTop ,\"RNK\",",
              "                            if(",
              "                              not(isblank([Sum])",
              "                            ),",
              "                            RANKX(_FilteredTableTop,[Sum],,ASC,skip)",
              "                            )",
              ")",
              "var Rank_Flop=ADDCOLUMNS(_FilteredTableFlop,\"RNK\",",
              "                            if(not(isblank([Sum])),",
              "                            calculate(rankx(_FilteredTableFlop, calculate([StockValueLatestByLastPPU],all('UnitOfMeasure'[UnitOfMeasureID]",
              "                            )",
              "                            ),,DESC,skip))",
              "                            )",
              ")",
              "",
              "return",
              "SWITCH(",
              "    SELECTEDVALUE(srv_TopFlop[SelectValue]),",
              "    \"Top\", MAXX(FILTER(",
              "       Rank_Top",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK]),",
              "",
              " ",
              "   \"Flop\", MAXX(FILTER(",
              "       Rank_Flop",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "7e9acefe-e812-410d-ae83-9f64a22c5938"
          },
          {
            "name": "ProductRank_3Mto6M_zero",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "Var _FilteredTableTop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialDocumentItem), dimProductCalculated[ProductID_NameCalculated], MaterialDocumentItem[MaterialBaseUnitID])",
              ",\"Sum\",[StockRemaining2_W998]), ",
              "AND(",
              "AND([StockRemaining2_M998] >= 3, [StockRemaining2_M998] < 6), ",
              "[QtyLatest] >= 0.1)",
              ")",
              "",
              "-- by lowest weeks remaining ",
              "Var _FilteredTableFlop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialStockLevel),dimProductCalculated[ProductID_NameCalculated])",
              ",\"Sum\", [StockValueLatestByLastPPU]), ",
              "AND(",
              "AND([StockRemaining2_M998] >= 3, [StockRemaining2_M998] < 6), ",
              "[QtyLatest] >= 0.1)",
              ")",
              "",
              "-- from highest to lowest by stock value",
              "var Rank_Top=ADDCOLUMNS(_FilteredTableTop ,\"RNK\",",
              "                            if(",
              "                              not(isblank([Sum])",
              "                            ),",
              "                            RANKX(_FilteredTableTop,[Sum],,ASC,skip)",
              "                            )",
              ")",
              "var Rank_Flop=ADDCOLUMNS(_FilteredTableFlop,\"RNK\",",
              "                            if(not(isblank([Sum])),",
              "                            calculate(rankx(_FilteredTableFlop, calculate([StockValueLatestByLastPPU],all('UnitOfMeasure'[UnitOfMeasureID]",
              "                            )",
              "                            ),,DESC,skip))",
              "                            )",
              ")",
              "",
              "return",
              "SWITCH(",
              "    SELECTEDVALUE(srv_TopFlop[SelectValue]),",
              "    \"Top\", MAXX(FILTER(",
              "       Rank_Top",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK]),",
              "",
              " ",
              "   \"Flop\", MAXX(FILTER(",
              "       Rank_Flop",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "b627e928-1223-4090-99a5-c80400290f18"
          },
          {
            "name": "ProductRank_6Mto12M",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "Var _FilteredTableTop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialDocumentItem), dimProductCalculated[ProductID_NameCalculated], MaterialDocumentItem[MaterialBaseUnitID])",
              ",\"Sum\",[StockRemaining2_W998]), ",
              "AND([StockRemaining2_M998] >= 6, [StockRemaining2_M998] < 12)",
              ")",
              "",
              "-- by lowest weeks remaining ",
              "Var _FilteredTableFlop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialStockLevel),dimProductCalculated[ProductID_NameCalculated])",
              ",\"Sum\", [StockValueLatestByLastPPU]), ",
              "AND([StockRemaining2_M998] >= 6, [StockRemaining2_M998] < 12)",
              ")",
              "",
              "-- from highest to lowest by stock value",
              "var Rank_Top=ADDCOLUMNS(_FilteredTableTop ,\"RNK\",",
              "                            if(",
              "                              not(isblank([Sum])",
              "                            ),",
              "                            RANKX(_FilteredTableTop,[Sum],,ASC,skip)",
              "                            )",
              ")",
              "var Rank_Flop=ADDCOLUMNS(_FilteredTableFlop,\"RNK\",",
              "                            if(not(isblank([Sum])),",
              "                            calculate(rankx(_FilteredTableFlop, calculate([StockValueLatestByLastPPU],all('UnitOfMeasure'[UnitOfMeasureID]",
              "                            )",
              "                            ),,DESC,skip))",
              "                            )",
              ")",
              "",
              "return",
              "SWITCH(",
              "    SELECTEDVALUE(srv_TopFlop[SelectValue]),",
              "    \"Top\", MAXX(FILTER(",
              "       Rank_Top",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK]),",
              "",
              " ",
              "   \"Flop\", MAXX(FILTER(",
              "       Rank_Flop",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "91819015-49f6-4e74-9b11-681f570efb8f"
          },
          {
            "name": "ProductRank_6Mto12M_zero",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "Var _FilteredTableTop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialDocumentItem), dimProductCalculated[ProductID_NameCalculated], MaterialDocumentItem[MaterialBaseUnitID])",
              ",\"Sum\",[StockRemaining2_W998]), ",
              "AND(",
              "AND([StockRemaining2_M998] >= 6, [StockRemaining2_M998] < 12), ",
              "[QtyLatest] >= 0.1)",
              ")",
              "",
              "-- by lowest weeks remaining ",
              "Var _FilteredTableFlop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialStockLevel),dimProductCalculated[ProductID_NameCalculated])",
              ",\"Sum\", [StockValueLatestByLastPPU]), ",
              "AND(",
              "AND([StockRemaining2_M998] >= 6, [StockRemaining2_M998] < 12), ",
              "[QtyLatest] >= 0.1)",
              ")",
              "",
              "-- from highest to lowest by stock value",
              "var Rank_Top=ADDCOLUMNS(_FilteredTableTop ,\"RNK\",",
              "                            if(",
              "                              not(isblank([Sum])",
              "                            ),",
              "                            RANKX(_FilteredTableTop,[Sum],,ASC,skip)",
              "                            )",
              ")",
              "var Rank_Flop=ADDCOLUMNS(_FilteredTableFlop,\"RNK\",",
              "                            if(not(isblank([Sum])),",
              "                            calculate(rankx(_FilteredTableFlop, calculate([StockValueLatestByLastPPU],all('UnitOfMeasure'[UnitOfMeasureID]",
              "                            )",
              "                            ),,DESC,skip))",
              "                            )",
              ")",
              "",
              "return",
              "SWITCH(",
              "    SELECTEDVALUE(srv_TopFlop[SelectValue]),",
              "    \"Top\", MAXX(FILTER(",
              "       Rank_Top",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK]),",
              "",
              " ",
              "   \"Flop\", MAXX(FILTER(",
              "       Rank_Flop",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "bccb35fb-0875-47ff-bef3-bdc068833730"
          },
          {
            "name": "ProductRank_9999_nousage",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "Var _FilteredTableTop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialDocumentItem), dimProductCalculated[ProductID_NameCalculated], MaterialDocumentItem[MaterialBaseUnitID])",
              ",\"Sum\",[StockRemaining2_W998]), ",
              "AND([ConsumptionQuantity12M] = 0.00,  [StockRemaining2_M998] > 9998 )",
              ")",
              "",
              "-- by lowest weeks remaining ",
              "Var _FilteredTableFlop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialStockLevel),dimProductCalculated[ProductID_NameCalculated])",
              ",\"Sum\", [StockValueLatestByLastPPU]), ",
              "AND([ConsumptionQuantity12M] = 0.00,  [StockRemaining2_M998] > 9998 )",
              ")",
              "-- from highest to lowest by stock value",
              "var Rank_Top=ADDCOLUMNS(_FilteredTableTop ,\"RNK\",",
              "                            if(",
              "                              not(isblank([Sum])",
              "                            ),",
              "                            RANKX(_FilteredTableTop,[Sum],,ASC,skip)",
              "                            )",
              ")",
              "var Rank_Flop=ADDCOLUMNS(_FilteredTableFlop,\"RNK\",",
              "                            if(not(isblank([Sum])),",
              "                            calculate(rankx(_FilteredTableFlop, calculate([StockValueLatestByLastPPU],all('UnitOfMeasure'[UnitOfMeasureID]",
              "                            )",
              "                            ),,DESC,skip))",
              "                            )",
              ")",
              "",
              "return",
              "SWITCH(",
              "    SELECTEDVALUE(srv_TopFlop[SelectValue]),",
              "    \"Top\", MAXX(FILTER(",
              "       Rank_Top",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK]),",
              "",
              " ",
              "   \"Flop\", MAXX(FILTER(",
              "       Rank_Flop",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "d88a84c2-21b9-4a9d-9232-1e73271d5c0c"
          },
          {
            "name": "ProductRank_9999_nousage_zero",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "Var _FilteredTableTop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialDocumentItem), dimProductCalculated[ProductID_NameCalculated], MaterialDocumentItem[MaterialBaseUnitID])",
              ",\"Sum\",[StockRemaining2_W998]), ",
              "AND(",
              "AND([ConsumptionQuantity12M] = 0.00,  [StockRemaining2_M998] > 9998 ), ",
              "[QtyLatest]  >= 0.1)",
              ")",
              "",
              "-- by lowest weeks remaining ",
              "Var _FilteredTableFlop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialStockLevel),dimProductCalculated[ProductID_NameCalculated])",
              ",\"Sum\", [StockValueLatestByLastPPU]), ",
              "AND(",
              "AND([ConsumptionQuantity12M] = 0.00,  [StockRemaining2_M998] > 9998 ), ",
              "[QtyLatest] >= 0.1 )",
              ")",
              "-- from highest to lowest by stock value",
              "var Rank_Top=ADDCOLUMNS(_FilteredTableTop ,\"RNK\",",
              "                            if(",
              "                              not(isblank([Sum])",
              "                            ),",
              "                            RANKX(_FilteredTableTop,[Sum],,ASC,skip)",
              "                            )",
              ")",
              "var Rank_Flop=ADDCOLUMNS(_FilteredTableFlop,\"RNK\",",
              "                            if(not(isblank([Sum])),",
              "                            calculate(rankx(_FilteredTableFlop, calculate([StockValueLatestByLastPPU],all('UnitOfMeasure'[UnitOfMeasureID]",
              "                            )",
              "                            ),,DESC,skip))",
              "                            )",
              ")",
              "",
              "return",
              "SWITCH(",
              "    SELECTEDVALUE(srv_TopFlop[SelectValue]),",
              "    \"Top\", MAXX(FILTER(",
              "       Rank_Top",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK]),",
              "",
              " ",
              "   \"Flop\", MAXX(FILTER(",
              "       Rank_Flop",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "97a78189-851f-41f3-b68b-d4ca27b7244f"
          },
          {
            "name": "ProductRank_less3M",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "Var _FilteredTableTop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialDocumentItem), dimProductCalculated[ProductID_NameCalculated], MaterialDocumentItem[MaterialBaseUnitID])",
              ",\"Sum\",[StockRemaining2_W998]), ",
              "[StockRemaining2_M998] < 3 )",
              "",
              "-- by lowest weeks remaining ",
              "Var _FilteredTableFlop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialStockLevel),dimProductCalculated[ProductID_NameCalculated])",
              ",\"Sum\", [StockValueLatestByLastPPU]), ",
              "[StockRemaining2_M998] < 3 )",
              "",
              "-- from highest to lowest by stock value",
              "var Rank_Top =",
              "ADDCOLUMNS(_FilteredTableTop ,\"RNK\",",
              "                            if(",
              "                              not(isblank([Sum])",
              "                            ),",
              "                            RANKX(_FilteredTableTop,[Sum],,ASC,skip)",
              "                            )",
              "        )",
              "// IF(HASONEVALUE(srv_SlicerZero[SlicerZero]), ",
              "// SWITCH(",
              "//     VALUES(srv_SlicerZero[SlicerZero]),",
              "// \"Exclude\", ",
              "// ADDCOLUMNS(_FilteredTableTop ,\"RNK\",",
              "//                             if(",
              "//                               not(isblank([Sum])",
              "//                             ),",
              "//                             RANKX(_FilteredTableTop,[Sum],,ASC,skip)",
              "//                             )",
              "//         ), ",
              "// \"Include\", ",
              "// ADDCOLUMNS(_FilteredTableTop ,\"RNK\",",
              "//                             if(",
              "//                               not(isblank([Sum])",
              "//                             ),",
              "//                             RANKX(FILTER(_FilteredTableTop,[QtyLatest]>0) ,[Sum],,ASC,skip)",
              "//                             )",
              "//         )   ",
              "//     )",
              "// )",
              "",
              "var Rank_Flop = ADDCOLUMNS(_FilteredTableFlop,\"RNK\",",
              "                            if(not(isblank([Sum])),",
              "                            calculate(rankx(_FilteredTableFlop, calculate([StockValueLatestByLastPPU],all('UnitOfMeasure'[UnitOfMeasureID]",
              "                            )",
              "                            ),,DESC,skip))",
              "                            )",
              ")",
              "",
              "return",
              "SWITCH(",
              "    SELECTEDVALUE(srv_TopFlop[SelectValue]),",
              "    \"Top\", MAXX(FILTER(",
              "       Rank_Top",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK]),",
              " ",
              "   \"Flop\", MAXX(FILTER(",
              "       Rank_Flop",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "d84aaad7-be8c-4053-bbea-efdf1cb84097"
          },
          {
            "name": "ProductRank_less3M_switcher",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "IF(HASONEVALUE(srv_SlicerZero[SlicerZero]),",
              "    SWITCH(VALUES(srv_SlicerZero[SlicerZero]), ",
              "    \"Exclude\", [ProductRank_less3M_zero],",
              "    \"Include\", [ProductRank_less3M]",
              "    ), ",
              "    [ProductRank_less3M]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "a09a2359-2399-45e9-a25e-c474ee8208bc"
          },
          {
            "name": "ProductRank_less3M_zero",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "Var _FilteredTableTop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialDocumentItem), dimProductCalculated[ProductID_NameCalculated], MaterialDocumentItem[MaterialBaseUnitID])",
              ",\"Sum\",[StockRemaining2_W998]), ",
              "AND([StockRemaining2_M998] < 3, [QtyLatest]  >= 0.1))",
              "",
              "-- by lowest weeks remaining ",
              "Var _FilteredTableFlop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialStockLevel),dimProductCalculated[ProductID_NameCalculated])",
              ",\"Sum\", [StockValueLatestByLastPPU]), ",
              "AND([StockRemaining2_M998] < 3, [QtyLatest]  >= 0.1))",
              "",
              "-- from highest to lowest by stock value",
              "var Rank_Top=ADDCOLUMNS(_FilteredTableTop ,\"RNK\",",
              "                            if(",
              "                              not(isblank([Sum])",
              "                            ),",
              "                            RANKX(_FilteredTableTop,[Sum],,ASC,skip)",
              "                            )",
              ")",
              "var Rank_Flop=ADDCOLUMNS(_FilteredTableFlop,\"RNK\",",
              "                            if(not(isblank([Sum])),",
              "                            calculate(rankx(_FilteredTableFlop, calculate([StockValueLatestByLastPPU],all('UnitOfMeasure'[UnitOfMeasureID]",
              "                            )",
              "                            ),,DESC,skip))",
              "                            )",
              ")",
              "",
              "return",
              "SWITCH(",
              "    SELECTEDVALUE(srv_TopFlop[SelectValue]),",
              "    \"Top\", MAXX(FILTER(",
              "       Rank_Top",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK]),",
              "",
              " ",
              "   \"Flop\", MAXX(FILTER(",
              "       Rank_Flop",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c81db8ce-3464-462c-9024-dae34527c380"
          },
          {
            "name": "ProductRank_more24",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "Var _FilteredTableTop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialDocumentItem), dimProductCalculated[ProductID_NameCalculated], MaterialDocumentItem[MaterialBaseUnitID])",
              ",\"Sum\",[StockRemaining2_W998]), ",
              "AND([StockRemaining2_M998] >= 24, [StockRemaining2_M998] <= 9998)",
              ")",
              "",
              "-- by lowest weeks remaining ",
              "Var _FilteredTableFlop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialStockLevel),dimProductCalculated[ProductID_NameCalculated])",
              ",\"Sum\", [StockValueLatestByLastPPU]), ",
              "AND([StockRemaining2_M998] >= 24, [StockRemaining2_M998] <= 9998)",
              ")",
              "",
              "-- from highest to lowest by stock value",
              "var Rank_Top=ADDCOLUMNS(_FilteredTableTop ,\"RNK\",",
              "                            if(",
              "                              not(isblank([Sum])",
              "                            ),",
              "                            RANKX(_FilteredTableTop,[Sum],,ASC,skip)",
              "                            )",
              ")",
              "var Rank_Flop=ADDCOLUMNS(_FilteredTableFlop,\"RNK\",",
              "                            if(not(isblank([Sum])),",
              "                            calculate(rankx(_FilteredTableFlop, calculate([StockValueLatestByLastPPU],all('UnitOfMeasure'[UnitOfMeasureID]",
              "                            )",
              "                            ),,DESC,skip))",
              "                            )",
              ")",
              "",
              "return",
              "SWITCH(",
              "    SELECTEDVALUE(srv_TopFlop[SelectValue]),",
              "    \"Top\", MAXX(FILTER(",
              "       Rank_Top",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK]),",
              "",
              " ",
              "   \"Flop\", MAXX(FILTER(",
              "       Rank_Flop",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "7cca733a-37be-42c1-a320-ba61b5844e36"
          },
          {
            "name": "ProductRank_more24_zero",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "Var _FilteredTableTop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialDocumentItem), dimProductCalculated[ProductID_NameCalculated], MaterialDocumentItem[MaterialBaseUnitID])",
              ",\"Sum\",[StockRemaining2_W998]), ",
              "AND(",
              "AND([StockRemaining2_M998] >= 24, [StockRemaining2_M998] <= 9998), ",
              "[QtyLatest] >= 0.1 )",
              ")",
              "",
              "-- by lowest weeks remaining ",
              "Var _FilteredTableFlop=FILTER(addcolumns(SUMMARIZE(allselected(MaterialStockLevel),dimProductCalculated[ProductID_NameCalculated])",
              ",\"Sum\", [StockValueLatestByLastPPU]), ",
              "AND(",
              "AND([StockRemaining2_M998] >= 24, [StockRemaining2_M998] <= 9998), ",
              "[QtyLatest] >= 0.1 ) ",
              ")",
              "",
              "-- from highest to lowest by stock value",
              "var Rank_Top=ADDCOLUMNS(_FilteredTableTop ,\"RNK\",",
              "                            if(",
              "                              not(isblank([Sum])",
              "                            ),",
              "                            RANKX(_FilteredTableTop,[Sum],,ASC,skip)",
              "                            )",
              ")",
              "var Rank_Flop=ADDCOLUMNS(_FilteredTableFlop,\"RNK\",",
              "                            if(not(isblank([Sum])),",
              "                            calculate(rankx(_FilteredTableFlop, calculate([StockValueLatestByLastPPU],all('UnitOfMeasure'[UnitOfMeasureID]",
              "                            )",
              "                            ),,DESC,skip))",
              "                            )",
              ")",
              "",
              "return",
              "SWITCH(",
              "    SELECTEDVALUE(srv_TopFlop[SelectValue]),",
              "    \"Top\", MAXX(FILTER(",
              "       Rank_Top",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK]),",
              "",
              " ",
              "   \"Flop\", MAXX(FILTER(",
              "       Rank_Flop",
              "    ,[ProductID_NameCalculated]=SELECTEDVALUE(dimProductCalculated[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "270413b5-1581-4c44-9847-ec204a058fbe"
          },
          {
            "name": "StockRemaining2Todate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([StockQuantity_Product], [ConsumptionQuantity12M])",
            "lineageTag": "350c9928-cef6-407f-8144-168e3982f5af"
          },
          {
            "name": "StockValueLastByLatestPPU_MDI",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR LastDay =",
              "    CALCULATE (",
              "        MAX ( MaterialStockLevel[ReportingDate] ),",
              "        NOT ISBLANK ( MaterialStockLevel[ReportingDate] )",
              "    )",
              "",
              "RETURN",
              "IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Local Currency\", CALCULATE(SUM(MaterialDocumentItem[StockValueByLatestPPU_local]), MaterialDocumentItem[DocumentDate] = MaterialDocumentItem[MaxDate MDI])",
              "        ,",
              "        \"Group Currency EUR\", CALCULATE(SUM(MaterialDocumentItem[StockValueByLatestPPU_EUR]), MaterialDocumentItem[DocumentDate] = MaterialDocumentItem[MaxDate MDI])",
              "        ,",
              "        \"Group Currency USD\", CALCULATE(SUM(MaterialDocumentItem[StockValueByLatestPPU_USD]), MaterialDocumentItem[DocumentDate] = MaterialDocumentItem[MaxDate MDI])",
              "    ),",
              "   CALCULATE(SUM(MaterialDocumentItem[StockValueByLatestPPU_EUR]), MaterialDocumentItem[DocumentDate] = MaterialDocumentItem[MaxDate MDI])",
              ")"
            ],
            "lineageTag": "1e14221e-8e57-4e2b-af44-1122994a4991"
          },
          {
            "name": "StockValueLatestByLastPPU",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Local Currency\", calculate(sum(MaterialStockLevel[StockLevelStandardLastPPU]),MaterialStockLevel[ReportingDate] = MaterialStockLevel[LastDate]--, all(MaterialDocumentItem[Application])",
              "        ),",
              "        \"Group Currency EUR\", calculate(sum(MaterialStockLevel[StockLevelStandardLastPPU_EUR]),MaterialStockLevel[ReportingDate] = MaterialStockLevel[LastDate]--, all(MaterialDocumentItem[Application])",
              "        ),",
              "        \"Group Currency USD\", calculate(sum(MaterialStockLevel[StockLevelStandardLastPPU_USD]),MaterialStockLevel[ReportingDate] = MaterialStockLevel[LastDate]--, all(MaterialDocumentItem[Application])",
              "        )",
              "    ),",
              "   calculate(sum(MaterialStockLevel[StockLevelStandardLastPPU_EUR]),",
              "   MaterialStockLevel[ReportingDate] = MaterialStockLevel[LastDate]--, all(MaterialDocumentItem[Application])",
              "   )",
              ")"
            ],
            "lineageTag": "8805f4f6-d9d5-499c-878f-0d6dcc5ee20d"
          },
          {
            "name": "ProductRank_more24_switcher",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "IF(HASONEVALUE(srv_SlicerZero[SlicerZero]),",
              "    SWITCH(VALUES(srv_SlicerZero[SlicerZero]), ",
              "    \"Exclude\", [ProductRank_more24_zero],",
              "    \"Include\", [ProductRank_more24]",
              "    ), ",
              "    [ProductRank_more24]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "0b3a0170-2699-44ca-8fd7-5bb9530db5d0"
          },
          {
            "name": "ProductRank1_2_switcher",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "IF(HASONEVALUE(srv_SlicerZero[SlicerZero]),",
              "    SWITCH(VALUES(srv_SlicerZero[SlicerZero]), ",
              "    \"Exclude\", [ProductRank1_2_zero],",
              "    \"Include\", [ProductRank1_2]",
              "    ), ",
              "    [ProductRank1_2]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "7d9922f6-5e7a-4edd-a075-a7f1557c8602"
          },
          {
            "name": "ProductRank_12Mto18M_switcher",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "IF(HASONEVALUE(srv_SlicerZero[SlicerZero]),",
              "    SWITCH(VALUES(srv_SlicerZero[SlicerZero]), ",
              "    \"Exclude\", [ProductRank_12Mto18M_zero],",
              "    \"Include\", [ProductRank_12Mto18M]",
              "    ), ",
              "    [ProductRank_12Mto18M]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "a74be8a3-27a2-488d-9389-7a412e13d443"
          },
          {
            "name": "ProductRank_18Mto24M_switcher",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "IF(HASONEVALUE(srv_SlicerZero[SlicerZero]),",
              "    SWITCH(VALUES(srv_SlicerZero[SlicerZero]), ",
              "    \"Exclude\", [ProductRank_18Mto24M_zero],",
              "    \"Include\", [ProductRank_18Mto24M]",
              "    ), ",
              "    [ProductRank_18Mto24M]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "03f7b288-58fd-410b-b080-a7f2197a1d52"
          },
          {
            "name": "ProductRank_3Mto6M_switcher",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "IF(HASONEVALUE(srv_SlicerZero[SlicerZero]),",
              "    SWITCH(VALUES(srv_SlicerZero[SlicerZero]), ",
              "    \"Exclude\", [ProductRank_3Mto6M_zero],",
              "    \"Include\", [ProductRank_3Mto6M]",
              "    ), ",
              "    [ProductRank_3Mto6M]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "401d7f4e-a8f0-46f9-84fb-69c11abbae96"
          },
          {
            "name": "ProductRank_6Mto12M_switcher",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "IF(HASONEVALUE(srv_SlicerZero[SlicerZero]),",
              "    SWITCH(VALUES(srv_SlicerZero[SlicerZero]), ",
              "    \"Exclude\", [ProductRank_6Mto12M_zero],",
              "    \"Include\", [ProductRank_6Mto12M]",
              "    ), ",
              "    [ProductRank_6Mto12M]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "334253ce-3022-4a8f-a039-0b4fdadd46df"
          },
          {
            "name": "ProductRank_9999_nousage_switcher",
            "displayFolder": "Rank by Months",
            "expression": [
              "",
              "IF(HASONEVALUE(srv_SlicerZero[SlicerZero]),",
              "    SWITCH(VALUES(srv_SlicerZero[SlicerZero]), ",
              "    \"Exclude\", [ProductRank_9999_nousage_zero],",
              "    \"Include\", [ProductRank_9999_nousage]",
              "    ), ",
              "    [ProductRank_9999_nousage]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "94d9139e-63da-4784-b95d-ff2642fa05f2"
          },
          {
            "name": "ConsumptionValue_lastPPU",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Local Currency\", sum(MaterialDocumentItem[ConsumptionValueByLatestPriceInBaseValue]),",
              "        \"Group Currency EUR\", sum(MaterialDocumentItem[ConsumptionValueByLatestPrice_EUR]), ",
              "        \"Group Currency USD\", sum(MaterialDocumentItem[ConsumptionValueByLatestPrice_USD])",
              "    ),",
              "    sum(MaterialDocumentItem[ConsumptionValueByLatestPrice_EUR])",
              ")"
            ],
            "lineageTag": "04c8ab11-26a3-4297-9360-3df81f490d3c"
          },
          {
            "name": "Devaluation",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[StockValueLatestByLastPPU]* [Devaluation %]",
            "lineageTag": "e8fa9edb-1d06-44e6-8715-ca12cc17ffc1"
          },
          {
            "name": "Devaluation %",
            "expression": [
              "",
              "VAR range = [StockRemaining2Years]--[StockRemaining2_Y998]",
              "RETURN",
              "IF(AND(NOT(ISBLANK(range)),AND(range >= 0, range <1)) , 0,",
              "        IF(AND(range >= 1, range <2) , 0.2,",
              "            IF( AND(range >= 2, range <3) , 0.4,",
              "                IF(AND(range >= 3, range <5) , 0.6,",
              "                    IF(AND(range >= 5, range <10) , 0.8,",
              "                        IF(AND(range >= 10, range <9998) , 0.9,",
              "                            IF(AND(range >= 9998, [ConsumptionQuantity] <0) , 0)",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "baf8e11f-cab6-4026-89b7-742045e6aab5"
          },
          {
            "name": "DocsCnt_StockMaterial",
            "expression": "COUNT(MaterialStockLevel[sk_dim_ProductValuationPUP])",
            "formatString": "0",
            "lineageTag": "1edc5dca-4088-4ee9-8198-c2d1c24240a1"
          },
          {
            "name": "Inventory Net Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[StockValueLatestByLastPPU] - [Devaluation]",
            "lineageTag": "ae7347f1-05a3-4b73-90d9-f86c2c422d37"
          },
          {
            "name": "LatestPricePerPiece_switch",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              " IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Local Currency\",",
              "        CALCULATE(MAX(MaterialStockLevel[LatestPricePerPiece_Local])),",
              "        \"Group Currency EUR\", ",
              "        CALCULATE(MAX(MaterialStockLevel[LatestPricePerPiece_EUR]))",
              "        ,",
              "        \"Group Currency USD\", ",
              "        CALCULATE(MAX(MaterialStockLevel[LatestPricePerPiece_USD]))",
              "    ),",
              "   CALCULATE(SUM(MaterialStockLevel[LatestPricePerPiece_EUR]))",
              " )"
            ],
            "lineageTag": "b1239f1b-4a30-41d9-a279-8dae75044ac3"
          },
          {
            "name": "Notification_TopFlop",
            "expression": [
              "",
              "IF(HASONEVALUE(srv_TopFlop[SelectValue]), ",
              "    SWITCH(VALUES(srv_TopFlop[SelectValue]), ",
              "        \"Top\", \"by lowest months remainning\", ",
              "        \"Flop\", \"from highest value of current stock value\")",
              "    ,",
              "    \"Please select Top/Flop\"",
              ")"
            ],
            "lineageTag": "a58471a2-9464-4928-b8ed-e3be0805cc3f"
          },
          {
            "name": "StockQuantity2_AVG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate(AVERAGE(MaterialStockLevel[StockLevelQtyInBaseUnit]),all(MaterialDocumentItem[HDR_PostingDate]), all('Calendar'))",
            "lineageTag": "dd881431-503e-4b29-aec2-f63e99c851c4"
          },
          {
            "name": "DocsCnt",
            "expression": "COUNTROWS(MaterialDocumentItem)",
            "formatString": "0",
            "lineageTag": "6139874b-33a9-4c05-919d-7c8cd31fec5c"
          },
          {
            "name": "ProductRank1",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Rank",
            "expression": [
              "",
              "",
              "Var _FilteredTable=addcolumns(SUMMARIZE(allselected(MaterialStockLevel),'dimProductCalculated'[ProductID_NameCalculated]),\"Sum\",[StockQuantityYTD])",
              "Var Rank_Top=ADDCOLUMNS(_FilteredTable,\"RNK\",calculate(rankx(_FilteredTable, calculate([QtyLatestDynamic]),,DESC,skip)))",
              "Var Rank_Flop = ADDCOLUMNS(_FilteredTable,\"RNK\",calculate(rankx(_FilteredTable,calculate([QtyLatestDynamic]),,ASC,Skip)))",
              "",
              "// Var _FilteredTable=addcolumns(SUMMARIZE(allselected(MaterialStockLevel),'dimProductCalculated'[ProductID_NameCalculated]),\"Sum\",[StockQuantity2])",
              "// var Rank_Top=ADDCOLUMNS(_FilteredTable,\"RNK\",calculate(rankx(_FilteredTable, calculate([StockQuantity2],all('Calendar')),,DESC,skip)))",
              "// var Rank_Flop = ADDCOLUMNS(_FilteredTable,\"RNK\",calculate(rankx(_FilteredTable,calculate([StockQuantity2],all('Calendar')),,ASC,Skip)))",
              "",
              "return",
              "SWITCH(",
              "    SELECTEDVALUE(srv_TopFlop[SelectValue]),",
              "   \"Top\", MAXX(FILTER(Rank_Top,[ProductID_NameCalculated]=SELECTEDVALUE('dimProductCalculated'[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK]),",
              "",
              " ",
              "   \"Flop\", MAXX(FILTER(Rank_Flop,[ProductID_NameCalculated]=SELECTEDVALUE('dimProductCalculated'[ProductID_NameCalculated])&&[RNK]<=SELECTEDVALUE(param_TopN[TopN])),[RNK])",
              ")"
            ],
            "lineageTag": "8b4d2b20-a940-4b3e-bc39-e20dd896f7e1"
          },
          {
            "name": "StockPrice",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Price",
            "expression": [
              "IF(",
              "    HASONEVALUE('Currency'[CurrencyType]),",
              "    SWITCH(",
              "        VALUES('Currency'[CurrencyType]),",
              "        \"Stock Price\", SUM(ProductValuationPUP[PriceUnit]),",
              "        \"Stock Price EUR\", SUM(ProductValuationPUP[StockPricePerUnit_EUR])",
              "        , \"Stock Price USD\", sum(ProductValuationPUP[StockPricePerUnit_USD])",
              "    ),",
              "   sum(ProductValuationPUP[StockPricePerUnit_EUR])",
              ")"
            ],
            "lineageTag": "6bc1a194-55ac-47d1-bcd8-eb7523a7ac88"
          },
          {
            "name": "StockRemaining2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Remainings",
            "expression": [
              "divide([StockQuantityToDate],[ConsumptionQuantity12M],0) *12",
              "-- BEFORE divide([StockQuantity2],[ConsumptionQuantity12M],0) *12",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "cc551210-2c43-4229-871c-1fb3591c16a3"
          },
          {
            "name": "StockRemaining2Years",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Remainings",
            "expression": [
              "",
              "--divide([StockQuantity2],[ConsumptionQuantity12M],0) ",
              "IF(AND(NOT(ISBLANK([StockQuantity2ToDate])), NOT(ISBLANK([ConsumptionQuantity12M]))),",
              "divide([StockQuantityToDate],[ConsumptionQuantity12M],0))"
            ],
            "formatString": "0.00",
            "lineageTag": "8becae61-b9fc-46d2-b80f-9379405e6a9c"
          },
          {
            "name": "StockQuantityYTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "TOTALYTD(SUM(MaterialStockLevel[StockLevelQtyInBaseUnit]), MaterialStockLevel[ReportingDate])"
            ],
            "lineageTag": "b68d1cf1-74fd-4d7d-9290-ced948e38141"
          },
          {
            "name": "Config Stock Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE([StockValue], ",
              "                                ProductSalesThirdPartyDelivery[IsConfigurable] = \"Yes\"",
              "                                )"
            ],
            "lineageTag": "55d5cd10-a474-4fb9-9594-f623e712f6a9"
          },
          {
            "name": "Config StockValuePM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "\t[Config Stock Value],",
              "\tPREVIOUSMONTH(MaterialStockLevel[ReportingDate]), all('Calendar'))"
            ],
            "lineageTag": "f723c26e-9ea1-4497-ad76-2e4f569d8f95"
          },
          {
            "name": "DeltaConfigStockValue",
            "expression": "if(isblank(divide([Config Stock Value],[Config StockValuePM],0)),0,divide([Config Stock Value],[Config StockValuePM],0)-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8063486c-7533-469e-9838-6df15ffcb068"
          },
          {
            "name": "ConsumptionQuantityProduct",
            "expression": [
              "",
              "CALCULATE( SUM(MaterialDocumentItem[ConsumptionQty]), USERELATIONSHIP(MaterialDocumentItem[MaterialID], MaterialStockLevel[MaterialID]))"
            ],
            "lineageTag": "4cea3fa2-1b62-4b73-8c9a-8388f1df7d65"
          },
          {
            "name": "ConsumptionQuantity12M_dynamic",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "calculate([ConsumptionQuantity],datediff('MaterialStockLevel'[ReportingDate],MaterialStockLevel[LastDate],month)<13)",
            "lineageTag": "ae41c3e6-72a6-4426-9f1d-806c1369e4fd"
          },
          {
            "name": "ConsumptionQuantityDynamic",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR LatestReportingDate = [LatestReportingDate12M] --DATEADD([LatestReportingDate], -12, MONTH)",
              "RETURN",
              "CALCULATE(",
              "    [ConsumptionQuantity],",
              "        FILTER(",
              "            ALLEXCEPT(MaterialDocumentItem, ",
              "                    'Calendar'[MonthName_Year], ",
              "                    dimProductCalculated[ProductID_NameCalculated], ",
              "                    dim_Application_manual,",
              "                    Plant[SalesOrganization],",
              "                    Plant[Plant],",
              "                    StorageLocation[StorageLocationID_Name],",
              "                    UnitOfMeasure[UnitOfMeasureID],",
              "                    InventoryStockType[InventoryStockTypeName],",
              "                    'Product'[MaterialType]",
              "                ),",
              "            MaterialDocumentItem[DocumentDate] >= LatestReportingDate",
              "            )",
              "    )"
            ],
            "lineageTag": "3206c484-ad39-45d0-b21d-48c1bf711970"
          },
          {
            "name": "DeltaNonConfigStockValue",
            "expression": "if(isblank(divide([NonConfig StockValue],[NonConfig StockValuePM],0)),0,divide([NonConfig StockValue],[NonConfig StockValuePM],0)-1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4b1d4ffd-d85e-4df1-a6c1-d98f6522369f"
          },
          {
            "name": "lastdatedynamic",
            "expression": [
              "",
              "CALCULATE(MAX(MaterialStockLevel[ReportingDate]),TOPN(1, MaterialStockLevel, MaterialStockLevel[ReportingDate],DESC))"
            ],
            "formatString": "General Date",
            "lineageTag": "648dc96b-e9ad-41c7-a65e-09a993bea906"
          },
          {
            "name": "LatestReportingDate",
            "expression": [
              "",
              "LASTDATE(MaterialStockLevel[ReportingDate])"
            ],
            "formatString": "General Date",
            "lineageTag": "d95dc593-0f6a-47f1-bd0f-5854cd138895"
          },
          {
            "name": "NonConfig StockValue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE([StockValue], ",
              "                                ProductSalesThirdPartyDelivery[IsConfigurable] = \"No\"",
              "                                                                 )"
            ],
            "lineageTag": "d1bd1d77-8de5-41b9-bf95-9fbfba43c6aa"
          },
          {
            "name": "NonConfig StockValuePM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "\t[NonConfig StockValue],",
              "\tPREVIOUSMONTH(MaterialStockLevel[ReportingDate]), all('Calendar'))"
            ],
            "lineageTag": "b3a3ee5d-82e7-4bf9-b28e-91844046f6bf"
          },
          {
            "name": "RANX Calculated",
            "expression": [
              "",
              "RANKX(",
              "dimProductCalculated,",
              "[StockQuantity2]",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "fd9ab8b4-c924-436b-b474-1b3a3c3855e1"
          },
          {
            "name": "QtyLatestDynamic",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR MonthCount = DISTINCTCOUNT('Calendar'[MonthName_Year])",
              "VAR LatestReportingDate = [LatestReportingDate]",
              "// VAR LastReportingDateDynamic = calculate(sum(MaterialStockLevel[StockLevelQtyInBaseUnit]),",
              "// MaterialStockLevel[ReportingDate] = [lastdatedynamic])",
              "RETURN",
              "// IF(MonthCount = 1, calculate(sum(MaterialStockLevel[StockLevelQtyInBaseUnit]),FILTER(ALLEXCEPT(MaterialStockLevel, 'Calendar'[Year], dimProductCalculated[ProductID_NameCalculated]), MaterialStockLevel[ReportingDate] = LatestReportingDate)),",
              "// calculate(sum(MaterialStockLevel[StockLevelQtyInBaseUnit]),FILTER(ALLEXCEPT(MaterialStockLevel, 'Calendar'[Year], dimProductCalculated[ProductID_NameCalculated]), MaterialStockLevel[ReportingDate] = LatestReportingDate))",
              "// //calculate(sum(MaterialStockLevel[StockLevelQtyInBaseUnit]),",
              "// // MaterialStockLevel[ReportingDate] = [lastdatedynamic])",
              "// // DATEADD(PREVIOUSMONTH('Calendar'[Date]), 1, MONTH))",
              "// )",
              "CALCULATE(",
              "    SUM(MaterialStockLevel[StockLevelQtyInBaseUnit]),",
              "        FILTER(",
              "            ALLEXCEPT(MaterialStockLevel, ",
              "                    'Calendar'[MonthName_Year], ",
              "                    dimProductCalculated[ProductID_NameCalculated], ",
              "                    dim_Application_manual,",
              "                    Plant[SalesOrganization],",
              "                    Plant[Plant],",
              "                    StorageLocation[StorageLocationID_Name],",
              "                    UnitOfMeasure[UnitOfMeasureID],",
              "                    InventoryStockType[InventoryStockTypeName],",
              "                    'Product'[MaterialType]",
              "                ),",
              "            MaterialStockLevel[ReportingDate] = LatestReportingDate)",
              "    )"
            ],
            "lineageTag": "fa4f945a-f3cf-40ba-b27b-9596896d343c"
          },
          {
            "name": "ProductRank1_fix",
            "expression": [
              "",
              "",
              "Var _FilteredTable=addcolumns(SUMMARIZE(allselected(MaterialStockLevel),'dimProductCalculated'[ProductID_NameCalculated]),\"Sum\",[StockQuantityYTD])",
              "",
              " var Rank_Top=ADDCOLUMNS(_FilteredTable,\"RNK\",calculate(rankx(_FilteredTable, calculate([QtyLatest]),,DESC,skip)))",
              "",
              " return",
              " --MAXX(Rank_Top, [StockQuantityYTD])",
              "",
              "--rankx(_FilteredTable, calculate([StockQuantityYTD]),,DESC,skip)",
              "// IF (",
              "//     HASONEVALUE ( 'Calendar'[YearMonth] ),",
              "    RANKX ( Rank_Top, [StockQuantityYTD] )",
              "--)"
            ],
            "formatString": "0",
            "lineageTag": "e6b6b1c3-b924-4b78-af58-b8abc6783e1f"
          },
          {
            "name": "BLANK",
            "expression": "BLANK()",
            "formatString": "0",
            "lineageTag": "adf8cbb3-4912-44b4-9648-2629283ff56e"
          },
          {
            "name": "LatestReportingDate12M",
            "expression": [
              "",
              "LASTDATE(DATEADD(MaterialDocumentItem[DocumentDate], -1, YEAR))"
            ],
            "formatString": "General Date",
            "lineageTag": "37915d08-64cf-4780-ab91-4aa9ab99a8e6"
          },
          {
            "name": "ConsumptionQuantity12M_0",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(ISBLANK([ConsumptionQuantity12M]), 0, [ConsumptionQuantity12M])",
            "lineageTag": "777b359e-7fa4-4d0c-8b97-86cc85d79b2a"
          },
          {
            "name": "MSL Consumption12M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "        SUM(MaterialStockLevel[Prev12MConsumptionQty]),",
              "MaterialStockLevel[ReportingDate] = MaterialStockLevel[LastDate]) "
            ],
            "lineageTag": "741344f1-48aa-49a0-8424-bc2696f53d6a"
          }
        ],
        "partitions": [
          {
            "name": "_Measures-06fc5eda-217c-46ac-949f-a9c4d76fade9",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Measures = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Measures\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MaterialDocumentItem",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "MaterialDocument",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1be1a57-4424-48ce-9f28-b233609fe47d",
            "sourceColumn": "MaterialDocument",
            "summarizeBy": "none"
          },
          {
            "name": "MaterialDocumentItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "464aed32-68a6-4fe7-b1d4-6154aaa4a203",
            "sourceColumn": "MaterialDocumentItem",
            "summarizeBy": "none"
          },
          {
            "name": "MaterialID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17396ceb-0396-44d9-84e3-645d8e596498",
            "sourceColumn": "MaterialID",
            "summarizeBy": "none"
          },
          {
            "name": "PlantID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76cb2642-727e-4a6c-a392-72285c1e8836",
            "sourceColumn": "PlantID",
            "summarizeBy": "none"
          },
          {
            "name": "SupplierID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "37c0406e-bae7-4ce6-95f4-a9d3d308231b",
            "sourceColumn": "SupplierID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5bd296dd-4361-4faa-8aef-7f40eef9aa30",
            "sourceColumn": "SalesOrder",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c32b27f-c5e4-4c9b-bb25-224a0b10decb",
            "sourceColumn": "SalesOrderItem",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a911851a-f5e8-4186-8e15-9133d090097f",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "InventorySpecialStockTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6bfcd63f-a1db-435d-89f6-948e0061d2ac",
            "sourceColumn": "InventorySpecialStockTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "InventoryStockTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b8affc4-5d8d-4118-b8e9-4f10f43fc4b5",
            "sourceColumn": "InventoryStockTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "StockOwner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a80372c0-84ad-4c26-b134-28e96cab2e6a",
            "sourceColumn": "StockOwner",
            "summarizeBy": "none"
          },
          {
            "name": "QuantityInBaseUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e1602532-a1fb-4c1e-aa37-339a42038ca2",
            "sourceColumn": "QuantityInBaseUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "MaterialBaseUnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54b10dcc-f9f9-4c07-9c59-c31e24deb801",
            "sourceColumn": "MaterialBaseUnitID",
            "summarizeBy": "none"
          },
          {
            "name": "QuantityInEntryUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f36df602-c82f-4e5a-81cd-8200896bdfc5",
            "sourceColumn": "QuantityInEntryUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "EntryUnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27c6c2c6-49fd-41c3-9b96-1e79288b4b38",
            "sourceColumn": "EntryUnitID",
            "summarizeBy": "none"
          },
          {
            "name": "HDR_PostingDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9f97fd52-59f4-4c46-b928-d984340f03b4",
            "sourceColumn": "HDR_PostingDate",
            "summarizeBy": "none"
          },
          {
            "name": "DocumentDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "eee52e01-ef28-479d-8960-14458e8e5cc0",
            "sourceColumn": "DocumentDate",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyCodeCurrency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "627120d5-2dcb-4bd8-b7a5-9f77ec198d7e",
            "sourceColumn": "CompanyCodeCurrency",
            "summarizeBy": "none"
          },
          {
            "name": "CostCenterID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60a7a70a-c5d5-491b-94de-0f951860a271",
            "sourceColumn": "CostCenterID",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyCodeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71158640-83ce-4b85-9513-ef8983900c47",
            "sourceColumn": "CompanyCodeID",
            "summarizeBy": "none"
          },
          {
            "name": "GoodsMovementRefDocTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c026a6e-bd7e-4aea-8739-e1ce50107215",
            "sourceColumn": "GoodsMovementRefDocTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "IsAutomaticallyCreated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ae52545-7253-45b0-8851-d3228d17b040",
            "sourceColumn": "IsAutomaticallyCreated",
            "summarizeBy": "none"
          },
          {
            "name": "IsCompletelyDelivered",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c232e06-7176-4ee5-8c2a-d42e671ba2e0",
            "sourceColumn": "IsCompletelyDelivered",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76654944-a173-4e3d-b32a-eecb53b1a335",
            "sourceColumn": "CurrencyTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "HDR_AccountingDocumentTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a2ce9ea-99ee-4507-a5a1-cd7f9f3c28d6",
            "sourceColumn": "HDR_AccountingDocumentTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "HDR_InventoryTransactionTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5c05c47-e26c-4a5d-a2a9-bdffb3d79694",
            "sourceColumn": "HDR_InventoryTransactionTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "HDR_CreatedByUser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae11bbc1-efed-41b6-abbb-12ccfb858293",
            "sourceColumn": "HDR_CreatedByUser",
            "summarizeBy": "none"
          },
          {
            "name": "HDR_CreationDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "dcd06353-03d5-4ff7-9684-2ec6fd8212fb",
            "sourceColumn": "HDR_CreationDate",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDocumentItemCategoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd19990f-77da-4e7e-b18d-82da749dbfc3",
            "sourceColumn": "SalesDocumentItemCategoryID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDocumentItemCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d656b6e-b70c-49cb-8d12-b44562a06506",
            "sourceColumn": "SalesDocumentItemCategory",
            "summarizeBy": "none"
          },
          {
            "name": "MatlStkChangeQtyInBaseUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cd073b99-8317-4012-b2f6-83cbad489f19",
            "sourceColumn": "MatlStkChangeQtyInBaseUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "MatlCnsmpnQtyInMatlBaseUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c55327a5-e153-4be9-8538-4e88f05ae33b",
            "sourceColumn": "MatlCnsmpnQtyInMatlBaseUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "GoodsReceiptQtyInOrderUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ae0df7f6-40a2-4e31-a7b8-12876df93f70",
            "sourceColumn": "GoodsReceiptQtyInOrderUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionQtySTOInBaseUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6d4179b1-d8f4-49fc-8cff-200ff62df525",
            "sourceColumn": "ConsumptionQtySTOInBaseUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d86433c-8b01-44d9-9d9f-25399f8fcde8",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "9f4f1645-8ea4-479d-a138-efe01641be2e",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "StockLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "var CurrentProduct = MaterialDocumentItem[MaterialID]",
              "return ",
              "sumx( filter( all(MaterialDocumentItem), MaterialDocumentItem[MaterialID] = CurrentProduct),MaterialDocumentItem[MatlStkChangeQtyInBaseUnit])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "34697751-3251-479c-97ac-1f461f0593fe",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "ConsumptionLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "var CurrentProduct = MaterialDocumentItem[MaterialID]",
              "return ",
              "sumx( filter( all(MaterialDocumentItem), and(datediff(MaterialDocumentItem[HDR_PostingDate],today(),month)<=12,MaterialDocumentItem[MaterialID] = CurrentProduct)),MaterialDocumentItem[ConsumptionQtyICPOInBaseUnit]+MaterialDocumentItem[ConsumptionQtyOBDProInBaseUnit]+MaterialDocumentItem[ConsumptionQtySOInBaseUnit])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "2c016e82-d198-4eac-aec2-7f19d1f55e44",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "StockRemainingMnths",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "DIVIDE(MaterialDocumentItem[StockLevel],MaterialDocumentItem[ConsumptionLevel],0) * 12",
            "isDataTypeInferred": true,
            "lineageTag": "6eda2345-ef44-466c-a032-4369bf20de46",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "StockLevelToDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "var CurrentProduct = MaterialDocumentItem[MaterialID]",
              "var CurrentDate = MaterialDocumentItem[HDR_PostingDate]",
              "return ",
              "sumx( filter( all(MaterialDocumentItem), and(MaterialDocumentItem[MaterialID] = CurrentProduct, MaterialDocumentItem[HDR_PostingDate]<=CurrentDate)),MaterialDocumentItem[MatlStkChangeQtyInBaseUnit])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "15ce40d1-c6d1-41eb-8635-2f32d1f24ee6",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "MatlStkChangeStandardValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dfc2c444-9f04-41e9-a348-dc091e766192",
            "sourceColumn": "MatlStkChangeStandardValue",
            "summarizeBy": "sum"
          },
          {
            "name": "MatlStkChangeStandardValue_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8aaeb372-f029-4d46-a9f3-7813a8faf6e3",
            "sourceColumn": "MatlStkChangeStandardValue_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "QuantityInBaseUnitStandardValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b37f4246-80e5-4980-92a2-bd51099465fc",
            "sourceColumn": "QuantityInBaseUnitStandardValue",
            "summarizeBy": "sum"
          },
          {
            "name": "QuantityInBaseUnitStandardValue_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6840d204-1aa6-4556-97ba-c81a9c41d7ad",
            "sourceColumn": "QuantityInBaseUnitStandardValue_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionQtyICPOInBaseUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cf02976a-b6a8-4572-abf2-9f4b7bd34a7a",
            "sourceColumn": "ConsumptionQtyICPOInBaseUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionQtyOBDProInBaseUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "05b6c78e-4daa-40a6-ac97-3eff258ea731",
            "sourceColumn": "ConsumptionQtyOBDProInBaseUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionQtySOInBaseUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c89bb8f7-f282-430a-a558-03629ab7f276",
            "sourceColumn": "ConsumptionQtySOInBaseUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionQtyICPOInStandardValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e40bd67f-4a19-46d1-97cf-f684b0078799",
            "sourceColumn": "ConsumptionQtyICPOInStandardValue",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionQtyICPOInStandardValue_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fe88801a-934d-4a02-a41f-c0a109fdebbf",
            "sourceColumn": "ConsumptionQtyICPOInStandardValue_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionQtyOBDProStandardValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "52c40756-b073-4b40-ae77-b23f67631e11",
            "sourceColumn": "ConsumptionQtyOBDProStandardValue",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionQtyOBDProStandardValue_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "34501eb7-b44c-4342-8854-494ace9e0e3b",
            "sourceColumn": "ConsumptionQtyOBDProStandardValue_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionQtySOStandardValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "82007d29-09bc-40dc-8437-ef0b2b43c1f1",
            "sourceColumn": "ConsumptionQtySOStandardValue",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionQtySOStandardValue_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cef8f23b-b5d8-43f8-b36b-63f4a7da5efb",
            "sourceColumn": "ConsumptionQtySOStandardValue_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "StockPricePerUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3635b1ef-9b34-45f2-ba16-118f33ee2c58",
            "sourceColumn": "StockPricePerUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "StockPricePerUnit_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "574c1d5d-b917-49fa-ad02-2fec32427573",
            "sourceColumn": "StockPricePerUnit_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "MaxDate MDI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "var CurrentProduct = MaterialDocumentItem[MaterialID]",
              "return ",
              "maxx( filter( all(MaterialDocumentItem), MaterialDocumentItem[MaterialID] = CurrentProduct),MaterialDocumentItem[DocumentDate])"
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "ed24e7b3-54c3-4f35-97ca-e4e36d6ee878",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "StockRemainingYears",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "DIVIDE(MaterialDocumentItem[StockLevel],MaterialDocumentItem[ConsumptionLevel],0)",
            "isDataTypeInferred": true,
            "lineageTag": "b03b70a8-8236-496d-b096-f566e179b44e",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "StandardPricePerUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1c16df88-5a50-4673-b71e-3d937392c853",
            "sourceColumn": "StandardPricePerUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "StandardPricePerUnit_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ca482b83-2006-40fc-9dfa-583bcf81c307",
            "sourceColumn": "StandardPricePerUnit_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "-- IF ICPO is not blank and is <> 0 then ICPO, ",
              "-- IF Pro is not blank and is <> 0 then Pro, ",
              "-- IF SO is not blank and is <> 0 then SO,",
              "-- Otherwise 0 and blank values would be classified as No consumption",
              "",
              "IF(AND(NOT(ISBLANK(MaterialDocumentItem[ConsumptionQtyICPOInBaseUnit])), ",
              "ABS(MaterialDocumentItem[ConsumptionQtyICPOInBaseUnit]) > 0), \"ICPO\", ",
              "--else result",
              "IF(AND(NOT(ISBLANK(MaterialDocumentItem[ConsumptionQtyOBDProInBaseUnit])), ",
              "ABS(MaterialDocumentItem[ConsumptionQtyOBDProInBaseUnit]) > 0 ), \"Pro\", ",
              "--else result",
              "IF(AND(NOT(ISBLANK(MaterialDocumentItem[ConsumptionQtySOInBaseUnit])), ",
              "ABS(MaterialDocumentItem[ConsumptionQtySOInBaseUnit]) > 0),  \"SO\", ",
              "",
              "\"No consumption\"",
              "                        )",
              "                    )",
              "                )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "52b9f956-1ea3-4071-8b96-673c0bd64c88",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Bucket2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "",
              "VAR cond = MaterialDocumentItem[StockRemainingMnths]--MaterialDocumentItem[StockRemainingMnths] --cond it is the short of condition ",
              "RETURN",
              "",
              "// 09/01/22",
              "// the buckets for stock remainig in months",
              "//< 3mnts, 3-6mnt, 6-12, 12-18, 18-24, 24-36, 36-60, 60-120, 120-9998 , No movement (9999)",
              "if(NOT(ISBLANK(cond)), ",
              "    (if (and(cond > 0, cond < 3), \" 0) <3 months\", ",
              "        if(and(cond >=3, cond<6), \"1) 3-6 month\", ",
              "            if(and(cond >=6, cond<12), \"2) 6-12 month\", ",
              "                if(and(cond >= 12, cond <18), \"3) 12-18 month\", ",
              "                    if(and(cond >= 18, cond <24), \"4) 18-24 month\",",
              "                        if(and(cond >=24, cond<36), \"5) 24-36 month\", ",
              "                            if(and(cond >= 36, cond < 60), \"6) 36-60 month\", ",
              "                                if(and(cond >= 60, cond <120), \"7) 60-120 month\",",
              "                                    if(and(cond >= 120, cond <9998), \"8) 120-9998 month\", \"9) 9999 (no consumption)\")",
              "                                        )",
              "                                    )",
              "                                )",
              "                            )",
              "                        )",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    )"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "896cb7b6-17ac-4cfb-8ae3-f7a6fa187c6c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "StockRemainingWeeks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "MaterialDocumentItem[StockLevel]/MaterialDocumentItem[ConsumptionLevel]*52",
            "isDataTypeInferred": true,
            "lineageTag": "8225dcf9-e495-4d49-a5de-ae94998c298f",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "",
              "var cond = MaterialDocumentItem[StockRemaining]",
              "",
              "RETURN",
              "",
              "    if(cond<3,\"0) <3 months\",",
              "",
              "        if(and(cond>=3,cond<6),\"1) 3 to 6 months\",",
              "",
              "            if(and(cond>=6,cond<12),\"2) 6 to 12 months\",",
              "",
              "                if(and(cond>=12,cond<18),\"3) 12 to 18 months\",",
              "",
              "                    if(and(cond>=18,cond<24),\"4) 18 to 24 months\",",
              "",
              "                        if(cond>=24,\"5) >24 months\",",
              "",
              "    \"6) No usage\"))))))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "23a90a58-e564-435f-9252-7085c8ed30fc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "StockRemaining",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "MaterialDocumentItem[StockLevel]/MaterialDocumentItem[ConsumptionLevel]*12",
            "isDataTypeInferred": true,
            "lineageTag": "55e4259c-0235-4a45-aea9-65825eb01112",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "StockPricePerUnit_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a87d6189-454c-4a4d-8633-02811c8145eb",
            "sourceColumn": "StockPricePerUnit_USD",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionQtyICPOInStandardValue_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "319f995e-59f3-4f17-b32a-586c376912aa",
            "sourceColumn": "ConsumptionQtyICPOInStandardValue_USD",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionQtyOBDProStandardValue_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f7af41b8-6f93-41db-8e6c-f1a8a344c5c0",
            "sourceColumn": "ConsumptionQtyOBDProStandardValue_USD",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionQtySOStandardValue_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bdebb367-9754-4a56-b20c-89fa524273ff",
            "sourceColumn": "ConsumptionQtySOStandardValue_USD",
            "summarizeBy": "sum"
          },
          {
            "name": "MatlStkChangeStandardValue_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f6469dc6-1a08-4403-b546-4c382f3bef13",
            "sourceColumn": "MatlStkChangeStandardValue_USD",
            "summarizeBy": "sum"
          },
          {
            "name": "QuantityInBaseUnitStandardValue_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f98fc26d-1c6d-4335-9dc3-9063d214ec6e",
            "sourceColumn": "QuantityInBaseUnitStandardValue_USD",
            "summarizeBy": "sum"
          },
          {
            "name": "LatestPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "",
              "VAR LastDay =",
              "    CALCULATE (",
              "        MAX ( ProductValuationPUP[Date] ),",
              "        NOT ISBLANK ( ProductValuationPUP[StockPricePerUnit] )",
              "    )",
              "VAR LastPrice =",
              "    CALCULATE (",
              "        MAX ( ProductValuationPUP[StockPricePerUnit] ),",
              "        ProductValuationPUP[Date] = LastDay,",
              "        NOT ISBLANK ( ProductValuationPUP[StockPricePerUnit] )",
              "    )",
              "VAR Plant_ = MaterialDocumentItem[PlantID]",
              "RETURN",
              "    CALCULATE ( MAX ( ProductValuationPUP[StockPricePerUnit] ), ProductValuationPUP[StockPricePerUnit] = LastPrice, ProductValuationPUP[ValuationAreaID] = Plant_)"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "8643386c-7208-4764-980a-fad654b55236",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "nk_dim_ProductValuationPUP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "20a8d35b-c1c0-44a2-9b44-b6ecf14ae764",
            "sourceColumn": "nk_dim_ProductValuationPUP",
            "summarizeBy": "none"
          },
          {
            "name": "StandardPricePerUnit_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6c35295d-da7e-4f64-b534-6d504b85f6fa",
            "sourceColumn": "StandardPricePerUnit_USD",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionQty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2e091873-eb12-490d-bfe7-0ddb644d0991",
            "sourceColumn": "ConsumptionQty",
            "summarizeBy": "sum"
          },
          {
            "name": "LatestPricePerPiece_Local",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a6cf0336-277d-4513-8369-8084b0301868",
            "sourceColumn": "LatestPricePerPiece_Local",
            "summarizeBy": "sum"
          },
          {
            "name": "LatestPricePerPiece_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5487d5a4-6fbd-4034-8318-a21ca381543b",
            "sourceColumn": "LatestPricePerPiece_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "LatestPricePerPiece_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d916ff46-ffd5-49a7-9ca4-b8c8adf99ce3",
            "sourceColumn": "LatestPricePerPiece_USD",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionValueByLatestPriceInBaseValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ecb867be-12ff-4bff-adf9-c134e92dbfdb",
            "sourceColumn": "ConsumptionValueByLatestPriceInBaseValue",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionValueByLatestPrice_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ce69b87d-dc0d-40a6-83af-020983b53c54",
            "sourceColumn": "ConsumptionValueByLatestPrice_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionValueByLatestPrice_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9adf7216-af58-4915-af15-a2a6a5845143",
            "sourceColumn": "ConsumptionValueByLatestPrice_USD",
            "summarizeBy": "sum"
          },
          {
            "name": "StockValueByLatestPPU_local",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "MaterialDocumentItem[MatlStkChangeQtyInBaseUnit] * MaterialDocumentItem[LatestPricePerPiece_Local]",
            "isDataTypeInferred": true,
            "lineageTag": "e3ad7337-bbdc-4528-80af-eeb2b6e18d9b",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "StockValueByLatestPPU_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "MaterialDocumentItem[MatlStkChangeQtyInBaseUnit] * MaterialDocumentItem[LatestPricePerPiece_USD]",
            "isDataTypeInferred": true,
            "lineageTag": "24cff922-824a-4d26-96e2-8c58e5216ddb",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "StockValueByLatestPPU_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "MaterialDocumentItem[MatlStkChangeQtyInBaseUnit] * MaterialDocumentItem[LatestPricePerPiece_EUR]",
            "isDataTypeInferred": true,
            "lineageTag": "87593963-d36a-4c82-a8cc-6f97a3b897fc",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "StockRemainingMonths",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "",
              "var cond = MaterialDocumentItem[StockRemainingMnths] ",
              "RETURN",
              "",
              "IF(AND(NOT(ISBLANK([ConsumptionQuantity12M])),cond >=9998), 9998, ",
              "    IF([ConsumptionQuantity12M] = 0,9999, AVERAGE(MaterialDocumentItem[StockRemainingMnths]))",
              "    )",
              "",
              "//MaterialDocumentItem[StockLevel]/MaterialDocumentItem[ConsumptionLevel]*365",
              "",
              "        // IF(MaterialDocumentItem[StockRemainingMnths] < 9998, MaterialDocumentItem[StockRemainingMnths], 9998)",
              "",
              "// VAR cond = MaterialDocumentItem[StockRemainingMnths] --cond it is the short of condition ",
              "// RETURN",
              "",
              "// // 09/01/22",
              "// // the buckets for stock remainig in months",
              "// //< 3mnts, 3-6mnt, 6-12, 12-18, 18-24, 24-36, 36-60, 60-120, 120-9998 , No movement (9999) ",
              "// if(AND",
              "//         (NOT(ISBLANK([ConsumptionQuantity12M])), and(NOT(ISBLANK(cond)), cond >= 9998)",
              "//     ), 9998, cond",
              "        ",
              "// ))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "e427e6e0-13ae-4dbf-9094-12416cbb00fc",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "nk_StoragePlantID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6de8ae5a-425a-4fb9-9df8-7e0f6ab92284",
            "sourceColumn": "nk_StoragePlantID",
            "summarizeBy": "none"
          },
          {
            "name": "PlantSalesOrgID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7f7f7c1-6f84-46d5-b812-74fb4906507c",
            "sourceColumn": "PlantSalesOrgID",
            "summarizeBy": "none"
          },
          {
            "name": "sk_ProductSalesOrg",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1221b3e5-34d5-4612-86ed-853526e2b395",
            "sourceColumn": "sk_ProductSalesOrg",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "952dc7fd-ff8b-4ff9-8015-9d6a859c6df0",
        "partitions": [
          {
            "name": "MaterialDocumentItem-422ac1ae-e56a-4640-bc09-1810532c1728",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB, [Query=\"SELECT #(lf)mdi.*#(lf)FROM dm_sales.vw_fact_MaterialDocumentItem mdi#(lf)WHERE DocumentDate >= DATEADD(year, -2, CAST(GETDATE() as date))\"]),",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each true),",
                "    #\"Filtered Rows1\" = Table.SelectRows(Source, each [HDR_PostingDate] >= RangeStart and [HDR_PostingDate] <= RangeEnd),",
                "    #\"Filtered Rows3\" = Table.SelectRows(#\"Filtered Rows1\", each not Text.Contains([t_applicationId], \"HALFEN\")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows3\",{\"MaterialDocumentYear\", \"SalesOrderScheduleLine\", \"WBSElementInternalID\", \"GoodsMovementTypeID\", \"DebitCreditCode\", \"InventoryUsabilityCode\", \"ReservationIsFinallyIssued\", \"PurchaseOrder\", \"PurchaseOrderItem\", \"ProjectNetwork\", \"Reservation\", \"ReservationItem\", \"DeliveryDocument\", \"DeliveryDocumentItem\", \"ReversedMaterialDocumentYear\", \"ReversedMaterialDocument\", \"ReversedMaterialDocumentItem\", \"RvslOfGoodsReceiptIsAllowed\", \"GoodsRecipientName\", \"UnloadingPointName\", \"ServicePerformer\", \"EmploymentInternalID\", \"AccountAssignmentCategory\", \"WorkItem\", \"ServicesRenderedDate\", \"IssgOrRcvgMaterial\", \"IssuingOrReceivingPlantID\", \"IssuingOrReceivingStorageLocID\", \"BusinessAreaID\", \"ControllingAreaID\", \"FiscalYearPeriod\", \"FiscalYearVariant\", \"IssgOrRcvgBatch\", \"IssgOrRcvgSpclStockInd\", \"MaterialDocumentItemText\", \"HDR_CreationTime\", \"HDR_MaterialDocumentHeaderText\", \"HDR_ReferenceDocument\", \"HDR_BillOfLading\", \"GoodsMovementIsCancelled\", \"GoodsMovementCancellationType\", \"ConsumptionPosting\", \"ManufacturingOrder\", \"ManufacturingOrderItem\", \"IsReversalMovementType\", \"SalesDocumentTypeID\", \"SalesDocumentType\", \"PurchaseOrderTypeID\", \"PurchaseOrderType\", \"HDR_DeliveryDocumentTypeID\", \"GoodsMovementTypeName\", \"InventorySpecialStockTypeName\", \"InventoryStockTypeName\", \"PriceControlIndicatorID\", \"PriceControlIndicator\", \"ShelfLifeExpirationDate\", \"ManufactureDate\", \"StorageBin\", \"Batch\", \"StorageTypeID\", \"StorageLocationID\", \"TotalGoodsMvtAmtInCCCrcy\", \"InventoryValuationTypeID\", \"Order\", \"OrderItem\", \"GLAccountID\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "param_TopN",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "fdf67cfddeb64f038a34e19e63f3e061"
          }
        ],
        "columns": [
          {
            "name": "TopN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "03596335-e11d-41f0-9b87-67037fd662e0",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "5663d050-58ee-4a80-90b2-2f398545e67c",
        "measures": [
          {
            "name": "TopN Value",
            "expression": "SELECTEDVALUE('param_TopN'[TopN], 5)",
            "lineageTag": "9306c42c-c1e0-4d8c-b2bd-da0812d2aa82"
          }
        ],
        "partitions": [
          {
            "name": "param_TopN-446728b4-022c-4908-a05b-b754eac9b31d",
            "mode": "import",
            "source": {
              "expression": "UNION( GENERATESERIES(5, 200, 5), {1000, 10000} )",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "srv_TopFlop",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SelectValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11e93602-bd0f-4341-a6fc-ee2aabb8c258",
            "sourceColumn": "SelectValue",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cae56e48-8450-4ebc-950e-ec3eda39ddf0",
        "partitions": [
          {
            "name": "srv_TopFlop-534a2cfd-46c8-43b8-be61-13cfdeb5baf9",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCskvUIrViVZyywExYgE=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [SelectValue = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"SelectValue\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "StorageLocation",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "StorageLocationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a74c984c-b587-4b46-907e-40c015aa11fc",
            "sourceColumn": "StorageLocationID",
            "summarizeBy": "none"
          },
          {
            "name": "StorageLocation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "53151d0f-6a61-4379-a340-c0f3a72f0385",
            "sourceColumn": "StorageLocation",
            "summarizeBy": "none"
          },
          {
            "name": "Plant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47ae9012-65f7-4d36-9406-eac73e246075",
            "sourceColumn": "Plant",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganizationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad9a46d8-f4f3-49d7-90c1-f2a1a4550921",
            "sourceColumn": "SalesOrganizationID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3be7dad2-18bb-4858-93e3-acb807eecb47",
            "sourceColumn": "SalesOrganization",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrg_CountryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "800fafca-94fe-4adb-9dce-dcbc869bcffb",
            "sourceColumn": "SalesOrg_CountryID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrg_Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8f2b049-41d3-4a77-88a0-91d5d5fab8e7",
            "sourceColumn": "SalesOrg_Country",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrg_RegionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c64e31b5-6b94-4ed2-906d-3e65d64d8990",
            "sourceColumn": "SalesOrg_RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrg_Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9732451b-8349-4141-a8e5-64c04674b8ad",
            "sourceColumn": "SalesOrg_Region",
            "summarizeBy": "none"
          },
          {
            "name": "DistributionChannel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c8996db-aa26-4c32-90cd-f7e53b955b03",
            "sourceColumn": "DistributionChannel",
            "summarizeBy": "none"
          },
          {
            "name": "Division",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "377de880-af88-4f42-a111-05f019e84323",
            "sourceColumn": "Division",
            "summarizeBy": "none"
          },
          {
            "name": "IsStorLocAuthznCheckActive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c941bdc7-aa7e-47c0-8e12-99886bd03a74",
            "sourceColumn": "IsStorLocAuthznCheckActive",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf7eb759-eb9f-4e03-a046-ebcb8e8a9cec",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "230e4364-fb64-4dc1-9051-1a948178369d",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "StorageLocationID_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "StorageLocation[StorageLocationID]&\"_\"&StorageLocation[StorageLocation]",
            "isDataTypeInferred": true,
            "lineageTag": "70572e12-2560-4a2b-8b3e-5377ead59379",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "nk_StoragePlantID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2776d481-1e40-486b-b837-ca9d14e6cba2",
            "sourceColumn": "nk_StoragePlantID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7160dcf4-97c3-4f51-ac44-4f65030b3e62",
        "partitions": [
          {
            "name": "StorageLocation-3258a517-65ab-4e0c-a5f0-cef0d1ccfd7e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_dim_StorageLocation = Source{[Schema=\"dm_sales\",Item=\"vw_dim_StorageLocation\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_StorageLocation"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Plant",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PlantID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec2da100-cb86-49eb-89f1-1b987ac819c8",
            "sourceColumn": "PlantID",
            "summarizeBy": "none"
          },
          {
            "name": "Plant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a62c282d-ab38-4c75-8edf-825878daf9b0",
            "sourceColumn": "Plant",
            "summarizeBy": "none"
          },
          {
            "name": "ValuationArea",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "135f8ece-09cf-419d-9d46-3fe51bbb5363",
            "sourceColumn": "ValuationArea",
            "summarizeBy": "none"
          },
          {
            "name": "PlantCustomer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d7b35f6-d28d-4821-aca4-d3a38d561d62",
            "sourceColumn": "PlantCustomer",
            "summarizeBy": "none"
          },
          {
            "name": "PlantSupplier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a784c32a-537a-4307-a80d-8a8d858ff9e9",
            "sourceColumn": "PlantSupplier",
            "summarizeBy": "none"
          },
          {
            "name": "FactoryCalendar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06f66b95-0c5a-41f6-8e8a-64e7b352b231",
            "sourceColumn": "FactoryCalendar",
            "summarizeBy": "none"
          },
          {
            "name": "DefaultPurchasingOrganization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a25f89b1-c956-4c51-8c51-73ca55f89b6a",
            "sourceColumn": "DefaultPurchasingOrganization",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganizationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08bd6fae-476b-40ab-b1ec-321c61169382",
            "sourceColumn": "SalesOrganizationID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f76e6451-dbdd-4031-a159-26e4b2ff79f9",
            "sourceColumn": "SalesOrganization",
            "summarizeBy": "none"
          },
          {
            "name": "AddressID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fba22810-96f6-4913-b72d-4b33adc9b6c8",
            "sourceColumn": "AddressID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrg_CountryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc28cde1-e7ff-4883-9dc0-3f8e47c50786",
            "sourceColumn": "SalesOrg_CountryID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrg_Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f9b04919-012e-411d-be05-0a8b18e41c96",
            "sourceColumn": "SalesOrg_Country",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrg_RegionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08e10fc9-134e-4c86-be59-9388924f35b6",
            "sourceColumn": "SalesOrg_RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrg_Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e1c8367-9c15-4d10-b09d-cd239ca684cd",
            "sourceColumn": "SalesOrg_Region",
            "summarizeBy": "none"
          },
          {
            "name": "PlantCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f270825d-7eb6-44f6-8884-05257750a660",
            "sourceColumn": "PlantCategory",
            "summarizeBy": "none"
          },
          {
            "name": "DistributionChannel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8e48c85-1078-4893-96f3-6ad2435472e1",
            "sourceColumn": "DistributionChannel",
            "summarizeBy": "none"
          },
          {
            "name": "Division",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0be8698-0855-4a72-89b9-39d0263e1d1f",
            "sourceColumn": "Division",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3beca201-e8f0-4be6-a347-1658b6f482df",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "2f10ad64-4a28-413f-ae6f-0dfb0a41c37f",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "db87b509-dc0b-4020-9f63-7db8f9051226",
        "partitions": [
          {
            "name": "Plant-63834e6d-011e-42f3-9f55-3ad8f6a9e8f0",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_dim_Plant = Source{[Schema=\"dm_sales\",Item=\"vw_dim_Plant\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_Plant"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "UnitOfMeasure",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UnitOfMeasureID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e01232cd-a812-49c4-97b7-7c7ee7099540",
            "sourceColumn": "UnitOfMeasureID",
            "summarizeBy": "none"
          },
          {
            "name": "UnitOfMeasure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a5b0d2e-0991-43dd-bcf5-d1fc42599978",
            "sourceColumn": "UnitOfMeasure",
            "summarizeBy": "none"
          },
          {
            "name": "UnitOfMeasureLongName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17b44c50-8a2c-464a-abcb-75a8c5771719",
            "sourceColumn": "UnitOfMeasureLongName",
            "summarizeBy": "none"
          },
          {
            "name": "UnitOfMeasureTechnicalName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfc8a42e-9c76-440f-a5e5-ea3dfc0c72b1",
            "sourceColumn": "UnitOfMeasureTechnicalName",
            "summarizeBy": "none"
          },
          {
            "name": "UnitOfMeasure_E",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14aa473c-cd46-4457-a6d4-925820daace7",
            "sourceColumn": "UnitOfMeasure_E",
            "summarizeBy": "none"
          },
          {
            "name": "UnitOfMeasureCommercialName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c5bdff2-b0cf-48a7-b1b5-6c7e1944d65f",
            "sourceColumn": "UnitOfMeasureCommercialName",
            "summarizeBy": "none"
          },
          {
            "name": "UnitOfMeasureSAPCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0a25a9c-0d00-4575-9ea9-c2f1e411eae8",
            "sourceColumn": "UnitOfMeasureSAPCode",
            "summarizeBy": "none"
          },
          {
            "name": "UnitOfMeasureISOCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7657b2aa-9a98-462d-8ed3-ac68cdcd2d73",
            "sourceColumn": "UnitOfMeasureISOCode",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19ddae3d-eb72-4551-bc1f-6f27297dbba3",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "3d002c33-cae2-441c-b5dc-07e3bd9ac42d",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6df14dcd-92fc-4665-9e4a-729791f939e6",
        "partitions": [
          {
            "name": "UnitOfMeasure-808eeaff-cd93-46fa-8f59-e5ac5395e697",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_dim_UnitOfMeasure = Source{[Schema=\"dm_sales\",Item=\"vw_dim_UnitOfMeasure\"]}[Data],",
                "    #\"Uppercased Text\" = Table.TransformColumns(dm_sales_vw_dim_UnitOfMeasure,{{\"UnitOfMeasureID\", Text.Upper, type text}}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Uppercased Text\", {\"UnitOfMeasureID\"})",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "InventoryStockType",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "InventoryStockTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b0403b0-9399-4976-a4e0-0ad2361cae41",
            "sourceColumn": "InventoryStockTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "InventoryStockTypeName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c3540c0-7390-48cd-862b-475a9d4f219f",
            "sourceColumn": "InventoryStockTypeName",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad0b605e-77d6-4e48-a1a4-678ea390eaf5",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "969319e8-1400-4e69-a92f-2b5292a02aff",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3a2f77a4-064f-4849-9a81-723f41f3c840",
        "partitions": [
          {
            "name": "InventoryStockType-86af5506-aae3-469d-bcef-21886e36d7df",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_dim_InventoryStockType = Source{[Schema=\"dm_sales\",Item=\"vw_dim_InventoryStockType\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dm_sales_vw_dim_InventoryStockType, each ([InventoryStockTypeID] <> \"\"))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "InventorySpecialStockType",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "InventorySpecialStockTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f185f3f-f214-403a-9a30-a0a977669f49",
            "sourceColumn": "InventorySpecialStockTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "InventorySpecialStockTypeName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ce8437b-61d5-4de0-a097-1b8472d1dfcc",
            "sourceColumn": "InventorySpecialStockTypeName",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3bebacd-feb2-4f4e-a744-388bd2b2928c",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "77ed4707-1b36-428d-bc39-705abde2ca99",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "216cf31c-f5c0-4eee-8569-3fd1f15bd4ef",
        "partitions": [
          {
            "name": "InventorySpecialStockType-f4140b98-2a88-4189-ad0d-a21c2e31af1c",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_dim_InventorySpecialStockType = Source{[Schema=\"dm_sales\",Item=\"vw_dim_InventorySpecialStockType\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_InventorySpecialStockType"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "BucketOrder",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aafcb035-1a29-472f-8faf-bafa1c31dce3",
            "sourceColumn": "Order",
            "summarizeBy": "none"
          },
          {
            "name": "Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cac6e6b8-07b3-49f1-9e97-9ec43dd61787",
            "sourceColumn": "Bucket",
            "summarizeBy": "none"
          },
          {
            "name": "BucketName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43ffd5b0-657f-4d6e-ae1a-61f509d61726",
            "sourceColumn": "BucketName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f6fc094d-4aad-481d-8f51-2b203111870e",
        "measures": [
          {
            "name": "Non Specified Config Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    CALCULATE([StockValue], ISBLANK(ProductSalesThirdPartyDelivery[IsConfigurable]))"
            ],
            "lineageTag": "a63308cb-ac69-4079-982c-a8d238c75e04"
          },
          {
            "name": "MSL Remaining",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR Prev12MConsumption = CALCULATE(SUM(MaterialStockLevel[Prev12MConsumptionQty]))",
              "VAR StockLevelQty = CALCULATE(SUM(MaterialStockLevel[StockLevelQtyInBaseUnit]))",
              "RETURN",
              "DIVIDE(StockLevelQty, Prev12MConsumption)*12"
            ],
            "lineageTag": "6c59c862-a88c-43b3-909c-06506304a976"
          },
          {
            "name": "MSL Remaining2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "divide([QtyLatest], [MSL Consumption12M]) * 12",
              "/*",
              "CALCULATE(",
              "    DIVIDE(",
              "        SUM(MaterialStockLevel[StockLevelQtyInBaseUnit]), ",
              "        SUM(MaterialStockLevel[Prev12MConsumptionQty])),",
              "MaterialStockLevel[ReportingDate] = MaterialStockLevel[LastDate]) * 12*/"
            ],
            "lineageTag": "b6c87e26-a11a-4846-9795-beabc74322ae"
          },
          {
            "name": "Bucket as measure",
            "expression": [
              "",
              "VAR Remain = DIVIDE([QtyLatest], [MSL Consumption12M]) * 12 ",
              "VAR consumption = [MSL Consumption12M]",
              "--[ConsumptionQuantity12M] ",
              "VAR stklvl = [QtyLatest]",
              "--[StockQuantityToDate] ",
              "RETURN",
              "if(NOT(ISBLANK(consumption)),",
              "//07/08/23",
              "    if (consumption = 0.00, \"0) No movement\",",
              "        if (and(stklvl>0, remain < 3), \"0) <3 months\",",
              "            if(and(remain >=3, remain<6), \"1) 3-6 month\", ",
              "                if(and(remain >=6, remain<12), \"2) 6-12 month\", ",
              "                    if(and(remain >= 12, remain <18), \"3) 12-18 month\", ",
              "                        if(and(remain >= 18, remain <24), \"4) 18-24 month\",",
              "                            if(remain >=24, \"5) > 24 month\", ",
              "            \"6) No movement\")",
              "                        )         ",
              "                    )",
              "                )",
              "            )",
              "        )",
              "    ),  \"6) No movement\"--\"6) No movement\"--",
              ")"
            ],
            "lineageTag": "f6093701-7363-4bc3-9e8a-63a3556623f4"
          },
          {
            "name": "MSL StockRemaining_Month",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "var remaining = DIVIDE([QtyLatest], [MSL Consumption12M], 0) * 12 ",
              "RETURN",
              "",
              "IF([QtyLatest] <> 0 && [MSL Consumption12M] = 0.00, 9999, remaining)"
            ],
            "formatString": "0",
            "lineageTag": "bb84901e-95f1-41d6-bfbf-208418de6c0c"
          }
        ],
        "partitions": [
          {
            "name": "BucketOrder-b5d39d1b-075c-4f2c-9920-92b13c9ba48b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"VY5BDgIhDEWvQrqeJrRghUt4AWRhzEQ3OouZub98klHcUPJem/9LIaGJrrv34R5+P/da3ttzpToV0oYDG163Lc5GhxNjwYpBio42NizKkvrsPo3+BJ5Y+16C1zh6ZGrkYEex+d+f0cnYfJsdIMh86/MluUd7zjmngwlsA3CXxe3r7TFTrR8=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Order = _t, Bucket = _t, BucketName = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Order\", Int64.Type}, {\"Bucket\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Pseudo Prod Table",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "806438c78d364343b10ade5f3b847865"
          }
        ],
        "columns": [
          {
            "name": "ProductID_NameCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "42861da0-68e5-405c-84e2-5e55d014a496",
            "sourceColumn": "dimProductCalculated[ProductID_NameCalculated]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6944f96e-0ab5-4f2b-901b-451cb12d40ee",
        "partitions": [
          {
            "name": "Pseudo Prod Table-5fa2aaf0-e63b-4168-b21f-47cb85b76749",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "UNION (",
                "    DISTINCT ( 'dimProductCalculated'[ProductID_NameCalculated] ),    -- to find unique names of the products ",
                "    DATATABLE (                        -- one row table having value \"Others\" ",
                "        \"ProductID_Name\", STRING,",
                "        { { \"Others\" } }",
                "    ) ",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "srv_SelectKPI",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "KPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93fa722b-0668-4f5b-b3f1-1b49aaa07f54",
            "sourceColumn": "KPI",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d5140d70-d634-4be2-9aa0-9d945ab76b79",
        "measures": [
          {
            "name": "SelectedMeasure",
            "expression": "SELECTEDVALUE(srv_SelectKPI[KPI])",
            "lineageTag": "baa51492-66f5-473a-95e9-d13bd10d7027"
          }
        ],
        "partitions": [
          {
            "name": "srv_SelectKPI-65a1e30a-e64b-4034-be93-ddf16fe97c7d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCi7JT85WCCxNzCvJLKlUitWBCYUl5pSmKsXGAgA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [KPI = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"KPI\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Currency",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CurrencyType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2482dfb-492b-45e3-8078-64e0a7f6ae64",
            "sourceColumn": "CurrencyType",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "313bda99-325f-4686-8e4a-1674bf73ab60",
        "measures": [
          {
            "name": "SelectedCurrency",
            "expression": "SELECTEDVALUE('Currency'[CurrencyType])",
            "lineageTag": "a9b79e07-0521-4f26-b971-f3e9f9859c0e"
          },
          {
            "name": "SelectedBucket",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( MaterialStockLevel[Bucket] ),",
              "    CONCATENATEX ( FILTERS ( MaterialStockLevel[Bucket] ), MaterialStockLevel[Bucket]  , \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "3b9785c2-3e7f-4955-9609-476dbff64b54"
          }
        ],
        "partitions": [
          {
            "name": "Currency-11ffde92-23ff-4f22-afce-7d3fad53fec0",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8slPTsxRcC4tKkrNS65UitWJVnIvyi8tgAspuIYGYRMODXZRio0FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [CurrencyType = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"CurrencyType\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ProductValuationPUP",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b7a3d6c-24f2-4669-b208-fcb2aa600a2a",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "ValuationAreaID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2fb6882f-07f5-4af4-947b-9f00ab206568",
            "sourceColumn": "ValuationAreaID",
            "summarizeBy": "none"
          },
          {
            "name": "ValuationArea",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48525513-2883-41a4-a2e4-12cf201425d4",
            "sourceColumn": "ValuationArea",
            "summarizeBy": "none"
          },
          {
            "name": "ValuationTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1bd26136-9d89-4176-81fa-bbf3229dcfb2",
            "sourceColumn": "ValuationTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "ValuationType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d3830e3-6dc9-4dfe-9a9d-39c4dfb017f8",
            "sourceColumn": "ValuationType",
            "summarizeBy": "none"
          },
          {
            "name": "ValuationClassID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "64cb8f1d-aa31-49c3-9baf-e067c3c16c0c",
            "sourceColumn": "ValuationClassID",
            "summarizeBy": "none"
          },
          {
            "name": "ValuationClass",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e283ef43-7b76-4931-9aac-7d6e899c25ed",
            "sourceColumn": "ValuationClass",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYearPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4db28593-70f2-468d-85d8-1b822216519a",
            "sourceColumn": "FiscalYearPeriod",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalMonthPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a63151b-a7cf-422c-bbb3-25f6cb59d366",
            "sourceColumn": "FiscalMonthPeriod",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalPeriodDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7c05665f-14aa-4471-941f-0005b2cb0dc2",
            "sourceColumn": "FiscalPeriodDate",
            "summarizeBy": "none"
          },
          {
            "name": "TotalValuatedStock",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3579c190-acc5-453b-a047-30bc04bf084d",
            "sourceColumn": "TotalValuatedStock",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalValuatedStockValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f2ec16b8-4a5d-4727-a99d-42c285a8d4b9",
            "sourceColumn": "TotalValuatedStockValue",
            "summarizeBy": "sum"
          },
          {
            "name": "PriceControlIndicatorID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3087289-b8d4-4f4f-b0df-e93f097503c7",
            "sourceColumn": "PriceControlIndicatorID",
            "summarizeBy": "none"
          },
          {
            "name": "PriceControlIndicator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f03348b-1ec7-43b3-b2bc-b059236d52a0",
            "sourceColumn": "PriceControlIndicator",
            "summarizeBy": "none"
          },
          {
            "name": "PeriodicUnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fee87292-34a1-4fd1-ac7a-3d644ae6c5c2",
            "sourceColumn": "PeriodicUnitPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "StandardPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bccc110a-34ad-41fc-af36-52af74b3288d",
            "sourceColumn": "StandardPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "PriceUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "138d9063-c50f-4e1d-998c-78c54cfd484a",
            "sourceColumn": "PriceUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "SAPTotalStockValuePUP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2ca86c54-24d4-40ff-bfbd-6e687c0b1461",
            "sourceColumn": "SAPTotalStockValuePUP",
            "summarizeBy": "sum"
          },
          {
            "name": "SAPTotalStockValueAtSalesPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "54867c48-22ae-449d-a8fc-b783079919d5",
            "sourceColumn": "SAPTotalStockValueAtSalesPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "CurrencyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9630ac41-2d6e-4717-a10f-a266f73a3f28",
            "sourceColumn": "CurrencyID",
            "summarizeBy": "none"
          },
          {
            "name": "StockPricePerUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "faf3c73d-735d-4897-b353-376d6622acf8",
            "sourceColumn": "StockPricePerUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "StockPricePerUnit_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9fd931e3-9f61-478c-9d11-26d2210cf804",
            "sourceColumn": "StockPricePerUnit_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "sk_dim_ProductValuationPUP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "95552dae-3516-48ec-a2fc-351feca49587",
            "sourceColumn": "sk_dim_ProductValuationPUP",
            "summarizeBy": "sum"
          },
          {
            "name": "CalendarYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01bff2a7-0927-49a4-8767-a12945bfbe85",
            "sourceColumn": "CalendarYear",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6cb23eb0-eea3-489d-9788-1a3f2ba424f4",
            "sourceColumn": "CalendarMonth",
            "summarizeBy": "none"
          },
          {
            "name": "isAddedMissingMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "93d19121-19e9-4004-a3c6-7a49abea7539",
            "sourceColumn": "isAddedMissingMonth",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "lineageTag": "000729a9-5359-4a1e-808a-0f543d1d5052",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "CalendarYear - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "092ab28e-a8f5-42fb-a2f6-829fbed9d846",
            "sourceColumn": "CalendarYear - Copy",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarMonth - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f571d33-93b1-4c60-9566-1e8b54d314b9",
            "sourceColumn": "CalendarMonth - Copy",
            "summarizeBy": "none"
          },
          {
            "name": "Custom",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3be7ebac-546b-4078-a1d3-6c8b71475258",
            "sourceColumn": "Custom",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6e5fbf0b-8a1c-4157-95a6-5417eaa9e434",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "StockPricePerUnit_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "74c0b790-20a1-464d-887b-062c0504179d",
            "sourceColumn": "StockPricePerUnit_USD",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "c9f59179-58e4-4ca4-a4da-f892dfabd8c8",
        "partitions": [
          {
            "name": "ProductValuationPUP-8c6f5c3a-fabc-4d88-a921-84b16b78b447",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_dim_ProductValuationPUP = Source{[Schema=\"dm_sales\",Item=\"vw_dim_ProductValuationPUP\"]}[Data],",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(dm_sales_vw_dim_ProductValuationPUP, \"CalendarYear\", \"CalendarYear - Copy\"),",
                "    #\"Duplicated Column1\" = Table.DuplicateColumn(#\"Duplicated Column\", \"CalendarMonth\", \"CalendarMonth - Copy\"),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Duplicated Column1\", \"Custom\", each 01),",
                "    #\"Inserted Merged Column\" = Table.AddColumn(#\"Added Custom\", \"Merged\", each Text.Combine({[#\"CalendarMonth - Copy\"], Text.From([Custom], \"en-US\"), [#\"CalendarYear - Copy\"]}, \"/\"), type text),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Inserted Merged Column\",{{\"Merged\", type date}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Merged\", \"Date\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns\",{\"nk_dim_ProductValuationPUP\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "OrderItem",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesOrderID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b454623-0a9e-4b8b-adf2-a354814f4895",
            "sourceColumn": "SalesOrderID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderItemID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0aad8a33-9857-4287-83a2-ebf5a1059519",
            "sourceColumn": "SalesOrderItemID",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04b693ef-93c3-4395-b7f7-efb4485f253c",
            "sourceColumn": "CurrencyTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a02e287-78cf-4219-b291-f8c38d0adbd3",
            "sourceColumn": "CurrencyType",
            "summarizeBy": "none"
          },
          {
            "name": "SDDocumentCategoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f56ab211-3dab-48d0-9a9e-3aba90d70e9d",
            "sourceColumn": "SDDocumentCategoryID",
            "summarizeBy": "none"
          },
          {
            "name": "SDDocumentCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76ae804f-580c-4177-bd1e-a2de306bf42f",
            "sourceColumn": "SDDocumentCategory",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDocumentTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f7d5188-db64-4916-9de9-792f78c8bf46",
            "sourceColumn": "SalesDocumentTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDocumentType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d4c6d13-0dce-4d53-b557-05549e46823e",
            "sourceColumn": "SalesDocumentType",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDocumentItemCategoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "630e13d7-77a5-425e-9baa-6c5c42ad08ff",
            "sourceColumn": "SalesDocumentItemCategoryID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDocumentItemCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f176b5ee-b3f7-4b30-987e-2d4599ae1688",
            "sourceColumn": "SalesDocumentItemCategory",
            "summarizeBy": "none"
          },
          {
            "name": "IsReturnsItemID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d538aea-f2cf-47de-89aa-90dc74c943a6",
            "sourceColumn": "IsReturnsItemID",
            "summarizeBy": "none"
          },
          {
            "name": "CreationDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8802a45a-7962-48a2-9a1a-ab6c1348bff3",
            "sourceColumn": "CreationDate",
            "summarizeBy": "none"
          },
          {
            "name": "CreationTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "34ebd041-dc55-462c-8f59-ac4041a98440",
            "sourceColumn": "CreationTime",
            "summarizeBy": "none"
          },
          {
            "name": "LastChangeDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "51d6b80d-5360-4fcf-8321-f3e97e4e2f9e",
            "sourceColumn": "LastChangeDate",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganizationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2181f5f-615f-4e4c-8ed5-d771e732c5c8",
            "sourceColumn": "SalesOrganizationID",
            "summarizeBy": "none"
          },
          {
            "name": "DistributionChannelID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4e73f01-b1ff-4076-a0b8-4891f9c52a95",
            "sourceColumn": "DistributionChannelID",
            "summarizeBy": "none"
          },
          {
            "name": "DistributionChannel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38ab9253-b107-4680-b1d7-38b76d4ef006",
            "sourceColumn": "DistributionChannel",
            "summarizeBy": "none"
          },
          {
            "name": "MaterialID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f662289b-0c48-4457-b72d-a27a2c41fdf8",
            "sourceColumn": "MaterialID",
            "summarizeBy": "none"
          },
          {
            "name": "OriginallyRequestedMaterialID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17c92821-dd38-4684-baf0-6c4e0b694687",
            "sourceColumn": "OriginallyRequestedMaterialID",
            "summarizeBy": "none"
          },
          {
            "name": "MaterialSubstitutionReasonID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eddd8809-31a2-46c1-9d52-f50a468d7342",
            "sourceColumn": "MaterialSubstitutionReasonID",
            "summarizeBy": "none"
          },
          {
            "name": "MaterialGroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1e76d6f-8bbe-47ea-afd2-b4cd0046a8cd",
            "sourceColumn": "MaterialGroupID",
            "summarizeBy": "none"
          },
          {
            "name": "SoldToPartyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c18e90e8-70db-4d49-943b-7fb9e6fe97f9",
            "sourceColumn": "SoldToPartyID",
            "summarizeBy": "none"
          },
          {
            "name": "ShipToPartyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e43fd82-7e1b-46a3-b9a4-67d59174fe35",
            "sourceColumn": "ShipToPartyID",
            "summarizeBy": "none"
          },
          {
            "name": "PayerPartyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42d82f91-2665-475d-bdce-ff693f56e428",
            "sourceColumn": "PayerPartyID",
            "summarizeBy": "none"
          },
          {
            "name": "BillToPartyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d4fae724-06d1-4462-bcdc-4b27318bbecf",
            "sourceColumn": "BillToPartyID",
            "summarizeBy": "none"
          },
          {
            "name": "SDDocumentReasonID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57a80f42-5925-4c71-99d3-edf11a6a6d01",
            "sourceColumn": "SDDocumentReasonID",
            "summarizeBy": "none"
          },
          {
            "name": "SDDocumentReason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9a2135b-f6d2-48ea-9ca5-fb9b9a76541b",
            "sourceColumn": "SDDocumentReason",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDocumentDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0c6cbe48-5f5c-4ace-9e3e-1c4ea3700138",
            "sourceColumn": "SalesDocumentDate",
            "summarizeBy": "none"
          },
          {
            "name": "OrderQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "821dd85c-cbc4-4003-8d31-955508e79793",
            "sourceColumn": "OrderQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "OrderQuantityUnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb9b2c8a-4d51-4122-b1e7-e27609ba2172",
            "sourceColumn": "OrderQuantityUnitID",
            "summarizeBy": "none"
          },
          {
            "name": "OrderQuantityUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "357e5e9c-175a-450c-8002-62d91e01ea04",
            "sourceColumn": "OrderQuantityUnit",
            "summarizeBy": "none"
          },
          {
            "name": "TargetQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9de0e845-3a71-4691-9b7d-88c16a7dfc2b",
            "sourceColumn": "TargetQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "TargetQuantityUnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f41bd4a1-c5d4-4c8c-86ff-e623389b4bb8",
            "sourceColumn": "TargetQuantityUnitID",
            "summarizeBy": "none"
          },
          {
            "name": "ServicesRenderedDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e9d2fecc-8189-483c-a46e-6ce6c5699aac",
            "sourceColumn": "ServicesRenderedDate",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDistrictID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "384738e7-f6cc-4bbf-8bdb-8a33d72ab085",
            "sourceColumn": "SalesDistrictID",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerGroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b86d0d8d-1697-47ae-afa4-9bbf4bd43623",
            "sourceColumn": "CustomerGroupID",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "231095dc-cf59-4e46-9ca6-537f364b7762",
            "sourceColumn": "CustomerGroup",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDocumentRjcnReasonID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e35f996-e01e-4b8d-8b97-8c82a1daad07",
            "sourceColumn": "SalesDocumentRjcnReasonID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDocumentRjcnReason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1bfb6fa-be38-4852-a1c0-81864ab88325",
            "sourceColumn": "SalesDocumentRjcnReason",
            "summarizeBy": "none"
          },
          {
            "name": "PricingDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d80f1523-f480-4588-8717-d15a67374ee8",
            "sourceColumn": "PricingDate",
            "summarizeBy": "none"
          },
          {
            "name": "ExchangeRateDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4eaafc97-6cb5-4e2a-9ba7-3ca375d6a633",
            "sourceColumn": "ExchangeRateDate",
            "summarizeBy": "none"
          },
          {
            "name": "NetAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "954ab615-60ff-4131-b0be-9db0dfe62e5b",
            "sourceColumn": "NetAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "TransactionCurrencyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72616a31-d3df-4c10-b777-f8549ced008f",
            "sourceColumn": "TransactionCurrencyID",
            "summarizeBy": "none"
          },
          {
            "name": "RequestedDeliveryDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "18367811-66e6-4655-aa90-16cc5d1debf0",
            "sourceColumn": "RequestedDeliveryDate",
            "summarizeBy": "none"
          },
          {
            "name": "PlantID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2dd9795e-9fbf-4728-9e85-3db555252359",
            "sourceColumn": "PlantID",
            "summarizeBy": "none"
          },
          {
            "name": "StorageLocationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "858e7ae7-7a4d-4356-a49a-56cd2f262d1f",
            "sourceColumn": "StorageLocationID",
            "summarizeBy": "none"
          },
          {
            "name": "BillingDocumentDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e97d4d4b-3a1a-4bb4-ad0b-e9b8accbf5d9",
            "sourceColumn": "BillingDocumentDate",
            "summarizeBy": "none"
          },
          {
            "name": "BillingCompanyCodeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a3aafa5-7d4e-4ac1-8519-a416cbcacece",
            "sourceColumn": "BillingCompanyCodeID",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenterID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a4269f8-920b-4f2c-b435-4aab03dc1235",
            "sourceColumn": "ProfitCenterID",
            "summarizeBy": "none"
          },
          {
            "name": "ReferenceSDDocumentItemSurrogateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c9e474d6-b0a4-448e-9845-4fa4987903b6",
            "sourceColumn": "ReferenceSDDocumentItemSurrogateKey",
            "summarizeBy": "count"
          },
          {
            "name": "ReferenceSDDocumentID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b318d83a-8217-4fe3-b4cd-76dcbd0adfa8",
            "sourceColumn": "ReferenceSDDocumentID",
            "summarizeBy": "none"
          },
          {
            "name": "ReferenceSDDocumentItemID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa262bce-2444-4221-8d96-d75044256997",
            "sourceColumn": "ReferenceSDDocumentItemID",
            "summarizeBy": "none"
          },
          {
            "name": "ReferenceSDDocumentCategoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9940cf42-6532-4678-9e28-7c96524f96e6",
            "sourceColumn": "ReferenceSDDocumentCategoryID",
            "summarizeBy": "none"
          },
          {
            "name": "ReferenceSDDocumentCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca7f6ba0-1ce1-40a9-9ba0-ed825458c37b",
            "sourceColumn": "ReferenceSDDocumentCategory",
            "summarizeBy": "none"
          },
          {
            "name": "OriginSDDocumentID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8fa5251-2e1b-47c3-81ac-db10d7fd1d33",
            "sourceColumn": "OriginSDDocumentID",
            "summarizeBy": "none"
          },
          {
            "name": "OriginSDDocumentItemID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1825dc2-19ed-46ff-a3ce-2d2e02cd0314",
            "sourceColumn": "OriginSDDocumentItemID",
            "summarizeBy": "none"
          },
          {
            "name": "OverallSDProcessStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bdcdb627-e206-498e-8d46-80487b7d96b3",
            "sourceColumn": "OverallSDProcessStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "OverallSDProcessStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9768448f-7483-4e23-b4bd-33ea39c2029c",
            "sourceColumn": "OverallSDProcessStatus",
            "summarizeBy": "none"
          },
          {
            "name": "OverallTotalDeliveryStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad26f50f-edc4-4550-9cbd-d0e6b54b0a11",
            "sourceColumn": "OverallTotalDeliveryStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "OverallTotalDeliveryStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7743680-a42d-414e-a9a2-3016b66ee700",
            "sourceColumn": "OverallTotalDeliveryStatus",
            "summarizeBy": "none"
          },
          {
            "name": "OverallOrdReltdBillgStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66b53915-3f8b-4cb5-b797-b984cd182c22",
            "sourceColumn": "OverallOrdReltdBillgStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "TotalCreditCheckStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "866534a7-933a-4231-8a38-f0078edcbef0",
            "sourceColumn": "TotalCreditCheckStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "TotalCreditCheckStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42df1b96-1976-4586-af3f-968b7e67130e",
            "sourceColumn": "TotalCreditCheckStatus",
            "summarizeBy": "none"
          },
          {
            "name": "DeliveryBlockStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55fd9237-96ef-48f4-a3c2-20f0288f4896",
            "sourceColumn": "DeliveryBlockStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "DeliveryBlockStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27508450-0c8c-428c-8511-8698b56669bd",
            "sourceColumn": "DeliveryBlockStatus",
            "summarizeBy": "none"
          },
          {
            "name": "BillingBlockStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6111723-0508-42ed-baa3-25d8b1c45fed",
            "sourceColumn": "BillingBlockStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "BillingBlockStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94346e7c-8c99-4186-911a-aa2f0d1e4447",
            "sourceColumn": "BillingBlockStatus",
            "summarizeBy": "none"
          },
          {
            "name": "TotalSDDocReferenceStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a513199f-2bf6-4ec5-a579-606ef24370ca",
            "sourceColumn": "TotalSDDocReferenceStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "TotalSDDocReferenceStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d489b650-26a2-41fc-adf2-c683f21d512f",
            "sourceColumn": "TotalSDDocReferenceStatus",
            "summarizeBy": "none"
          },
          {
            "name": "SDDocReferenceStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50bf0fc0-a520-4daf-ac75-fd9412620ef8",
            "sourceColumn": "SDDocReferenceStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "SDDocReferenceStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6d5ea3a-df81-4a8a-aa4f-80670e100a77",
            "sourceColumn": "SDDocReferenceStatus",
            "summarizeBy": "none"
          },
          {
            "name": "OverallSDDocumentRjcnStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05a1af8e-9ff4-4680-8895-ed662008da6e",
            "sourceColumn": "OverallSDDocumentRjcnStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "OverallSDDocumentRejectionSts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d469739-513c-4bbd-be45-56660eaeeda4",
            "sourceColumn": "OverallSDDocumentRejectionSts",
            "summarizeBy": "none"
          },
          {
            "name": "SDDocumentRejectionStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f88143a-850e-4e7d-b2ec-c8065b3a3bdc",
            "sourceColumn": "SDDocumentRejectionStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "SDDocumentRejectionStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5009008-cf8b-40a1-938e-acfefe6598f1",
            "sourceColumn": "SDDocumentRejectionStatus",
            "summarizeBy": "none"
          },
          {
            "name": "OverallTotalSDDocRefStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2a65225-a843-4274-aa30-8165e513c9e6",
            "sourceColumn": "OverallTotalSDDocRefStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "OverallTotalSDDocRefStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7dd82a0-a94f-4028-8119-763976e99997",
            "sourceColumn": "OverallTotalSDDocRefStatus",
            "summarizeBy": "none"
          },
          {
            "name": "OverallSDDocReferenceStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "669932c5-0d1c-4092-90de-4e77f9f9d0b6",
            "sourceColumn": "OverallSDDocReferenceStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "OverallSDDocReferenceStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09ccebc4-59b8-44c6-8314-6837f31132c1",
            "sourceColumn": "OverallSDDocReferenceStatus",
            "summarizeBy": "none"
          },
          {
            "name": "ItemGeneralIncompletionStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21f71650-5d5c-4c88-a48a-9339c5a98d63",
            "sourceColumn": "ItemGeneralIncompletionStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "ItemGeneralIncompletionStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f3c248e7-407c-4738-9b76-ffeb726b1248",
            "sourceColumn": "ItemGeneralIncompletionStatus",
            "summarizeBy": "none"
          },
          {
            "name": "ItemBillingIncompletionStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5616e1f-bc25-490b-a36e-871366a437d1",
            "sourceColumn": "ItemBillingIncompletionStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "ItemBillingIncompletionStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aef29133-712f-42ff-b35b-d863879bdac8",
            "sourceColumn": "ItemBillingIncompletionStatus",
            "summarizeBy": "none"
          },
          {
            "name": "PricingIncompletionStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "31fd969f-260f-427d-8c15-63e6b2641620",
            "sourceColumn": "PricingIncompletionStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "PricingIncompletionStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3cf16aee-9a26-4578-8a67-3855cfbe9b11",
            "sourceColumn": "PricingIncompletionStatus",
            "summarizeBy": "none"
          },
          {
            "name": "ItemDeliveryIncompletionStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f94eead7-e385-449c-83a6-65e52773c63f",
            "sourceColumn": "ItemDeliveryIncompletionStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "ItemDeliveryIncompletionStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4db1c681-45ea-425e-bbda-48d334f87da7",
            "sourceColumn": "ItemDeliveryIncompletionStatus",
            "summarizeBy": "none"
          },
          {
            "name": "ExternalSalesAgentID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cee97d65-c4b6-420e-9835-cac7c584b5b2",
            "sourceColumn": "ExternalSalesAgentID",
            "summarizeBy": "none"
          },
          {
            "name": "ExternalSalesAgent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b28868f-8c02-4001-b801-283df7890aa3",
            "sourceColumn": "ExternalSalesAgent",
            "summarizeBy": "none"
          },
          {
            "name": "ProjectID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "22e82e3c-e8f7-4fd8-bd25-525faf26dd69",
            "sourceColumn": "ProjectID",
            "summarizeBy": "none"
          },
          {
            "name": "Project",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c1eacf6-4378-4eed-902d-db2bf117f796",
            "sourceColumn": "Project",
            "summarizeBy": "none"
          },
          {
            "name": "SalesEmployeeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "daa5ce4f-b90f-4622-8ec2-94605478157b",
            "sourceColumn": "SalesEmployeeID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesEmployee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90382132-b55c-4df8-87b4-8349344a1a6f",
            "sourceColumn": "SalesEmployee",
            "summarizeBy": "none"
          },
          {
            "name": "GlobalParentCalculatedID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bdf8b98c-817c-4332-a90e-3735fc221e18",
            "sourceColumn": "GlobalParentCalculatedID",
            "summarizeBy": "none"
          },
          {
            "name": "GlobalParentCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c94db09e-f6e0-43ce-bde5-e02670804bc4",
            "sourceColumn": "GlobalParentCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "LocalParentCalculatedID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6e579cd-31e5-49b6-9135-1f0cfda066a1",
            "sourceColumn": "LocalParentCalculatedID",
            "summarizeBy": "none"
          },
          {
            "name": "LocalParentCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc8c8b7a-203c-4004-9813-a8fbf3ce50b6",
            "sourceColumn": "LocalParentCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "Margin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "40cd34cb-a5e6-4945-84cf-6fdd9486474e",
            "sourceColumn": "Margin",
            "summarizeBy": "sum"
          },
          {
            "name": "Subtotal1Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "47aea749-f286-499f-bbbd-4664fc20cc1f",
            "sourceColumn": "Subtotal1Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Subtotal2Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f00d2487-2d74-4d32-8e12-796263d45dfc",
            "sourceColumn": "Subtotal2Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Subtotal3Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a9099fc7-d42f-4e92-922b-d85613074998",
            "sourceColumn": "Subtotal3Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Subtotal4Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9c01df17-b50e-4221-b9e8-9ad29ad8ade6",
            "sourceColumn": "Subtotal4Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Subtotal5Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ede09cbd-42e4-44aa-b367-24db5e95eb9c",
            "sourceColumn": "Subtotal5Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Subtotal6Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "df9a8292-ec82-4bbe-ab39-3575f45da462",
            "sourceColumn": "Subtotal6Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "CurrencyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8186cd4d-2a77-4bdb-be5c-8a7120958643",
            "sourceColumn": "CurrencyID",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSurrogateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92947ae9-5bbd-4810-a1f5-89906101ca6b",
            "sourceColumn": "ProductSurrogateKey",
            "summarizeBy": "none"
          },
          {
            "name": "BrandID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a13d9a1e-2df2-4638-ab8a-db268bad16bc",
            "sourceColumn": "BrandID",
            "summarizeBy": "none"
          },
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f195e8e5-7a26-434d-b483-8881fb042362",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          },
          {
            "name": "InOutID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e055d936-1ac0-4c50-9f55-5fbd43164c13",
            "sourceColumn": "InOutID",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98493641-ba9f-4856-b398-9c3da85f35e6",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5c313924-a557-4d6f-a7f9-b91e094a7cde",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "SalesAgentID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7aa71a42-8610-4e1d-929c-3edef27622f3",
            "sourceColumn": "SalesAgentID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesAgent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6abafab-d9b4-4937-9fa5-b6ad24979167",
            "sourceColumn": "SalesAgent",
            "summarizeBy": "none"
          },
          {
            "name": "OrderType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8508af39-ac2c-450d-8981-ba3c2fe6b733",
            "sourceColumn": "OrderType",
            "summarizeBy": "none"
          },
          {
            "name": "ItemOrderStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87c0d65c-6008-4a9f-b5a4-661160515bd6",
            "sourceColumn": "ItemOrderStatus",
            "summarizeBy": "none"
          },
          {
            "name": "OrderStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "828cd504-9040-49c4-b5d4-01ae4d924130",
            "sourceColumn": "OrderStatus",
            "summarizeBy": "none"
          },
          {
            "name": "ActualDeliveredQuantityInBaseUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ac4057d6-77e3-4679-8f87-7b61fbce6ac1",
            "sourceColumn": "ActualDeliveredQuantityInBaseUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "BillingQuantityInBaseUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a8d5bc6d-c836-43da-87c3-68aa828da27d",
            "sourceColumn": "BillingQuantityInBaseUnit",
            "summarizeBy": "sum"
          },
          {
            "name": "ActualDeliveredQuantityIBUOverall",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "89a772cd-366b-4175-9095-b3ee3c5ce112",
            "sourceColumn": "ActualDeliveredQuantityIBUOverall",
            "summarizeBy": "sum"
          },
          {
            "name": "BillingQuantityIBUOverall",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2d15c2a2-0bad-4144-851c-eeda48720617",
            "sourceColumn": "BillingQuantityIBUOverall",
            "summarizeBy": "sum"
          },
          {
            "name": "ItemDeliveryStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d95174e-f74d-4ed2-bbc0-92ab74a78730",
            "sourceColumn": "ItemDeliveryStatus",
            "summarizeBy": "none"
          },
          {
            "name": "OverallDeliveryStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "657c4ad0-b723-4e50-a020-a5ee053d240c",
            "sourceColumn": "OverallDeliveryStatus",
            "summarizeBy": "none"
          },
          {
            "name": "ScheduleLineCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d59b4e7-a10b-48e0-b5d4-1a389ddd66a7",
            "sourceColumn": "ScheduleLineCategory",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOfficeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f803b03e-4593-4e62-8812-2e43194be7cd",
            "sourceColumn": "SalesOfficeID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOffice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0653c4af-93ff-40a2-a48d-001142d9d373",
            "sourceColumn": "SalesOffice",
            "summarizeBy": "none"
          },
          {
            "name": "CostAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0f66f57a-dd6d-423f-b8eb-f6c6279617b2",
            "sourceColumn": "CostAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "ShippingConditionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a30553f-4106-47f1-ac68-ca991363b12a",
            "sourceColumn": "ShippingConditionID",
            "summarizeBy": "none"
          },
          {
            "name": "nk_ProductPlant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "acbe72a7-933d-4aa3-85f7-e2e57e9d704d",
            "sourceColumn": "nk_ProductPlant",
            "summarizeBy": "none"
          },
          {
            "name": "sk_fact_SalesDocumentItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "72b4717e-8bc5-4772-83e0-5b395feb6ddd",
            "sourceColumn": "sk_fact_SalesDocumentItem",
            "summarizeBy": "sum"
          },
          {
            "name": "HeaderBillingBlockReasonID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0fe73b08-ae2b-47d1-9fd6-40cb5d52a6d7",
            "sourceColumn": "HeaderBillingBlockReasonID",
            "summarizeBy": "none"
          },
          {
            "name": "ItemBillingBlockReasonID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bca553bb-becf-40aa-bba4-c361773e41ef",
            "sourceColumn": "ItemBillingBlockReasonID",
            "summarizeBy": "none"
          },
          {
            "name": "DeliveryBlockReasonID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63a0bf43-1382-415e-b567-132fb45fae5e",
            "sourceColumn": "DeliveryBlockReasonID",
            "summarizeBy": "none"
          },
          {
            "name": "HDR_PlannedGoodsIssueDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "75f910d5-1a29-4e92-8a42-e6114d0e79f0",
            "sourceColumn": "HDR_PlannedGoodsIssueDate",
            "summarizeBy": "none"
          },
          {
            "name": "HDR_ShippingPointID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "37f73c3d-0db5-453a-8403-be0de190a2b0",
            "sourceColumn": "HDR_ShippingPointID",
            "summarizeBy": "none"
          },
          {
            "name": "HDR_HeaderBillingBlockReason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7798227-961a-4231-ba4a-41481dffb394",
            "sourceColumn": "HDR_HeaderBillingBlockReason",
            "summarizeBy": "none"
          },
          {
            "name": "HDR_TotalBlockStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "652d54e7-7ba1-4e67-81dc-26b402fa0bbd",
            "sourceColumn": "HDR_TotalBlockStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "HDR_ShipmentBlockReason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a361816-cc66-4026-863c-2005564216a0",
            "sourceColumn": "HDR_ShipmentBlockReason",
            "summarizeBy": "none"
          },
          {
            "name": "HDR_DeliveryBlockReason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d66a23b-cc7b-44e2-aa47-59251ae2c921",
            "sourceColumn": "HDR_DeliveryBlockReason",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedByUserID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4953eb01-4132-412d-87dd-757e6d7ff77e",
            "sourceColumn": "CreatedByUserID",
            "summarizeBy": "none"
          },
          {
            "name": "LatestOutboundDelivery",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd5083e2-1678-461c-a214-c423f2afc23c",
            "sourceColumn": "LatestOutboundDelivery",
            "summarizeBy": "none"
          },
          {
            "name": "LatestOutboundDeliveryItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0c5d413-f9a2-4649-9052-1be4e8480d5b",
            "sourceColumn": "LatestOutboundDeliveryItem",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5485a8bb-20b7-47ad-ba78-5641974c26c2",
        "partitions": [
          {
            "name": "OrderItem-3ce6b3b9-ac2c-465a-ba4f-b5604b1a3dda",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_SalesOrderItem = Source{[Schema=\"dm_sales\",Item=\"vw_fact_SalesOrderItem\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dm_sales_vw_SalesOrderItem, each Text.Contains([t_applicationId], \"s4h\"))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dimProductCalculated",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductIDCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "afe2da1e-8bb3-4dee-b993-47660abdeab1",
            "sourceColumn": "ProductIDCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c46afec7-b2c9-4523-a3ef-e8df45106f9f",
            "sourceColumn": "ProductCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "ProductID_NameCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d1ae589d-9bcb-49ad-b523-c7df0aaf5a59",
            "sourceColumn": "ProductID_NameCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "ProductPillarIDCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4caca412-7a03-4cf5-89b0-a319a2202d7a",
            "sourceColumn": "ProductPillarIDCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "ProductPillarCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ccb4f9ae-63e4-4b7b-bb31-8865f2d0a1ac",
            "sourceColumn": "ProductPillarCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "ProductGroupIDCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74961e1c-87b1-4ad7-92a9-f3016f8359f8",
            "sourceColumn": "ProductGroupIDCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "ProductGroupCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0694a87-252d-433a-aab0-05a22daa2ea9",
            "sourceColumn": "ProductGroupCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "MainGroupIDCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63d572b2-20fb-4f44-a705-d8638a8fb772",
            "sourceColumn": "MainGroupIDCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "MainGroupCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74035797-e87b-411e-b3ff-9b55b59dcbeb",
            "sourceColumn": "MainGroupCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "isReviewed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e88ecf2d-6dda-4202-bcde-a1aa182f59e5",
            "sourceColumn": "isReviewed",
            "summarizeBy": "sum"
          },
          {
            "name": "mappingType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9008a494-9447-4282-b739-9150fd298444",
            "sourceColumn": "mappingType",
            "summarizeBy": "none"
          },
          {
            "name": "axbiItemNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a2e58b59-07f6-44b7-8911-de94debf701b",
            "sourceColumn": "axbiItemNo",
            "summarizeBy": "none"
          },
          {
            "name": "axbiItemName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c76cdac-048a-45c7-a48b-c5793d5e08aa",
            "sourceColumn": "axbiItemName",
            "summarizeBy": "none"
          },
          {
            "name": "axbiProductPillarIDCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe4efd9e-27b2-41b2-baac-10999034ca60",
            "sourceColumn": "axbiProductPillarIDCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "axbiProductPillarCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7f55152-e325-4c59-9509-803fb683e842",
            "sourceColumn": "axbiProductPillarCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "axbiProductGroupIDCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a878faa-6866-4ce7-82d1-ddbc05474eea",
            "sourceColumn": "axbiProductGroupIDCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "axbiProductGroupCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43854a63-01ff-494d-81dc-1b5be9f1c80a",
            "sourceColumn": "axbiProductGroupCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "axbiMainGroupIDCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2acf6b4b-5cc2-459a-974c-6c9d32c57b20",
            "sourceColumn": "axbiMainGroupIDCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "axbiMainGroupCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6db3279b-910b-4371-a7fc-21824ce66774",
            "sourceColumn": "axbiMainGroupCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "469bae77-8510-474e-9006-9cc648195408",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "15af9b32-a732-4917-aa82-86453ff1c2e6",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "Bucket",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "var CurrentProduct = 'dimProductCalculated'[ProductIDCalculated]",
              "return ",
              "maxx( filter( all(MaterialDocumentItem), MaterialDocumentItem[MaterialID] = CurrentProduct),MaterialDocumentItem[Bucket])",
              "--[Bucket3])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "1c3f8e1e-33cc-4780-a9b0-e1a4a3ac8c5e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "750d11ab-de8b-43df-9759-9d14e19d57ec",
        "partitions": [
          {
            "name": "dimProductCalculated-c5397459-0154-4ee7-ba7d-0876c55bd3cb",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB, [Query=\"SELECT * #(lf)FROM dm_sales.vw_dim_ProductCalculated  AS prdcl  #(lf)WHERE EXISTS  #(lf)#(tab)#(tab)#(tab)(SELECT DISTINCT mdi.MaterialID  #(lf)#(tab)#(tab)#(tab)#(tab)FROM dm_sales.vw_fact_MaterialDocumentItem mdi  #(lf)#(tab)#(tab)#(tab)#(tab)WHERE prdcl.ProductIDCalculated = mdi.MaterialID )\"])",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_Application_manual",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "t_application_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6e32a5a-2af0-4df2-a4f9-38c1461892fc",
            "sourceColumn": "t_application_id",
            "summarizeBy": "none"
          },
          {
            "name": "Application",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf0e355e-8dca-4010-8aaf-f43340dc24ee",
            "sourceColumn": "Application",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2b6bbcb7-0774-44ac-8111-0a0a1edd4241",
        "partitions": [
          {
            "name": "dim_Application_manual-3b2e60bd-7362-4e9d-a190-6f9b87a4ef4c",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WKjbJ0E1OTNQ1MjBQ0lEKNvFQitWJVgqJiPdw9HFz9Ys3incJ94gPdQwByjpGOHkqQMTBqiB6C3QNEXpjAQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [t_application_id = _t, application = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"t_application_id\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"application\", \"Application\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "StockLevel",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "fdbaebb23ae7409699beb593eb049125"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e26c8167-aaba-4d27-910b-c2266013161b",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "5a014ceb-61b0-4a91-8e92-113ae5ea1fc5",
        "partitions": [
          {
            "name": "StockLevel-05b3ed6d-8278-4ee2-9d34-c03ea63239f2",
            "mode": "import",
            "source": {
              "expression": "{\"1\"}",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "srv_SlicerZero",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SlicerZero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95c03f9e-1d82-4d99-8636-8cacc081d639",
            "sourceColumn": "SlicerZero",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6dee9fdf-dc93-4580-b462-4f4adf0add65",
        "partitions": [
          {
            "name": "srv_SlicerZero-3230e2be-6670-4764-99c8-967989df514a",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wcq1IzilNSVWK1YlW8syDsmMB\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [SlicerZero = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"SlicerZero\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ProductPlant",
        "columns": [
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf57f7d6-0c52-4617-8e22-9dc611bd8780",
            "sourceColumn": "Product",
            "summarizeBy": "none"
          },
          {
            "name": "Plant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "300b488a-c83a-4866-a4f3-1dc72579c86b",
            "sourceColumn": "Plant",
            "summarizeBy": "none"
          },
          {
            "name": "PurchasingGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0b65cba-8d2c-4e2c-a10d-422c24a41146",
            "sourceColumn": "PurchasingGroup",
            "summarizeBy": "none"
          },
          {
            "name": "CountryOfOrigin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "425ff052-6100-49da-ae4c-5592ead606bb",
            "sourceColumn": "CountryOfOrigin",
            "summarizeBy": "none"
          },
          {
            "name": "RegionOfOrigin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46b312e6-2b99-464f-a9c6-74e235d897da",
            "sourceColumn": "RegionOfOrigin",
            "summarizeBy": "none"
          },
          {
            "name": "ProductionInvtryManagedLoc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "548e559c-caba-4596-8dae-807be2ecbe6c",
            "sourceColumn": "ProductionInvtryManagedLoc",
            "summarizeBy": "none"
          },
          {
            "name": "ProfileCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec367e9e-ba7c-457a-8d8f-2a4204704f99",
            "sourceColumn": "ProfileCode",
            "summarizeBy": "none"
          },
          {
            "name": "ProfileValidityStartDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d905fb7d-131c-415d-a861-2133181f6a21",
            "sourceColumn": "ProfileValidityStartDate",
            "summarizeBy": "none"
          },
          {
            "name": "AvailabilityCheckType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "821e1eec-1625-4d4b-ac05-a78d6e1e7213",
            "sourceColumn": "AvailabilityCheckType",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYearVariant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1f5d5cb-920a-4baf-82b6-b3fcf30608cf",
            "sourceColumn": "FiscalYearVariant",
            "summarizeBy": "none"
          },
          {
            "name": "PeriodType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d861e9b6-5b9c-4ed5-b2a3-eee406f6c0e4",
            "sourceColumn": "PeriodType",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af791d5d-9b64-45e7-b0a0-0d2b949be340",
            "sourceColumn": "ProfitCenter",
            "summarizeBy": "none"
          },
          {
            "name": "Commodity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f04a80d8-f9dc-46df-b6e0-bbf72898254d",
            "sourceColumn": "Commodity",
            "summarizeBy": "none"
          },
          {
            "name": "GoodsReceiptDuration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a1d82818-dfc0-4385-b2a4-73481b19551d",
            "sourceColumn": "GoodsReceiptDuration",
            "summarizeBy": "sum"
          },
          {
            "name": "MaintenanceStatusName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19ca0fdc-9fff-4c2a-a3b7-440f7d35f316",
            "sourceColumn": "MaintenanceStatusName",
            "summarizeBy": "none"
          },
          {
            "name": "IsMarkedForDeletion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ef2447f-d881-4b84-b29c-d8dc4d45cea9",
            "sourceColumn": "IsMarkedForDeletion",
            "summarizeBy": "none"
          },
          {
            "name": "MRPType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3dec41f1-456e-488d-9132-b73d7160ad73",
            "sourceColumn": "MRPType",
            "summarizeBy": "none"
          },
          {
            "name": "MRPResponsible",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e89d360-b310-4563-8792-12880e8af8fb",
            "sourceColumn": "MRPResponsible",
            "summarizeBy": "none"
          },
          {
            "name": "ABCIndicator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a1deb65-e9bd-4b67-b7f5-019a6eaf8924",
            "sourceColumn": "ABCIndicator",
            "summarizeBy": "none"
          },
          {
            "name": "MinimumLotSizeQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8ddb1165-965c-4440-82da-62420bd65b89",
            "sourceColumn": "MinimumLotSizeQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "MaximumLotSizeQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a3f7ba03-ced4-4ce6-8705-17045832bf8f",
            "sourceColumn": "MaximumLotSizeQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "FixedLotSizeQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3b9fdb81-f4e5-474f-b1f8-a9700e8b9ec0",
            "sourceColumn": "FixedLotSizeQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "ConsumptionTaxCtrlCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "828b1ba1-4afd-42e6-a9dd-57dab423b69f",
            "sourceColumn": "ConsumptionTaxCtrlCode",
            "summarizeBy": "none"
          },
          {
            "name": "IsCoProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebe1a92c-895f-4655-ac43-2ab62460d78d",
            "sourceColumn": "IsCoProduct",
            "summarizeBy": "none"
          },
          {
            "name": "ProductIsConfigurable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a8ef856-aa50-4eef-9151-542b0dc08af7",
            "sourceColumn": "ProductIsConfigurable",
            "summarizeBy": "none"
          },
          {
            "name": "ConfigurableProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "067d56f1-3ca7-4b37-a2aa-cdf6c104e3f3",
            "sourceColumn": "ConfigurableProduct",
            "summarizeBy": "none"
          },
          {
            "name": "StockDeterminationGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af770ec6-a6b5-4c9a-a602-476668250d86",
            "sourceColumn": "StockDeterminationGroup",
            "summarizeBy": "none"
          },
          {
            "name": "StockInTransferQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f9c51fb7-b3d4-4169-b8be-bc67b86fcecc",
            "sourceColumn": "StockInTransferQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "StockInTransitQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2983761c-0d73-49ac-89b0-ed5a708c9e1a",
            "sourceColumn": "StockInTransitQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "HasPostToInspectionStock",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d3385fa-dbfc-473f-bd53-cdd190be3777",
            "sourceColumn": "HasPostToInspectionStock",
            "summarizeBy": "none"
          },
          {
            "name": "IsBatchManagementRequired",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "33dbada5-17ac-4463-bc1a-8cdf257c428c",
            "sourceColumn": "IsBatchManagementRequired",
            "summarizeBy": "none"
          },
          {
            "name": "SerialNumberProfile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94bf39d1-72ec-431c-9143-cf1ad50094d6",
            "sourceColumn": "SerialNumberProfile",
            "summarizeBy": "none"
          },
          {
            "name": "IsNegativeStockAllowed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8bda7c9-bfec-4494-b572-37ca6af6d116",
            "sourceColumn": "IsNegativeStockAllowed",
            "summarizeBy": "none"
          },
          {
            "name": "GoodsReceiptBlockedStockQty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "29bde86a-1766-45d3-b8f6-00b191b39528",
            "sourceColumn": "GoodsReceiptBlockedStockQty",
            "summarizeBy": "sum"
          },
          {
            "name": "HasConsignmentCtrl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "662dd335-022d-49ba-9327-434d213d49b1",
            "sourceColumn": "HasConsignmentCtrl",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYearCurrentPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7c8bba1-de36-4612-af30-a440682dd534",
            "sourceColumn": "FiscalYearCurrentPeriod",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalMonthCurrentPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "858aea3e-c5f8-4b42-9fc0-a197e88329e6",
            "sourceColumn": "FiscalMonthCurrentPeriod",
            "summarizeBy": "none"
          },
          {
            "name": "IsPurgAcrossPurgGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f82b1c34-e06c-44cf-9a39-57c105562856",
            "sourceColumn": "IsPurgAcrossPurgGroup",
            "summarizeBy": "none"
          },
          {
            "name": "IsInternalBatchManaged",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecaf81b1-eda0-40b2-be3b-2f3c167f3317",
            "sourceColumn": "IsInternalBatchManaged",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCFOPCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c590c22e-def0-4e8c-a9e4-bb97f0a69f12",
            "sourceColumn": "ProductCFOPCategory",
            "summarizeBy": "none"
          },
          {
            "name": "ProductIsExciseTaxRelevant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2c6ddc9-d9c3-4799-ad97-3f6ce23f98cf",
            "sourceColumn": "ProductIsExciseTaxRelevant",
            "summarizeBy": "none"
          },
          {
            "name": "UnderDelivToleranceLimit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1d897de8-6e42-48e3-8f72-6e66d68207dd",
            "sourceColumn": "UnderDelivToleranceLimit",
            "summarizeBy": "sum"
          },
          {
            "name": "OverDelivToleranceLimit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "52d10bcb-1edb-4c75-a792-92b8758d6d97",
            "sourceColumn": "OverDelivToleranceLimit",
            "summarizeBy": "sum"
          },
          {
            "name": "ProcurementType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adb20387-4167-46f3-bc8b-02e5bd030afe",
            "sourceColumn": "ProcurementType",
            "summarizeBy": "none"
          },
          {
            "name": "SpecialProcurementType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fec0fe7f-6ae1-4790-826f-378b94c643fe",
            "sourceColumn": "SpecialProcurementType",
            "summarizeBy": "none"
          },
          {
            "name": "ProductionSchedulingProfile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d1e7b34e-2fb3-475d-9f7e-63afbc289f4d",
            "sourceColumn": "ProductionSchedulingProfile",
            "summarizeBy": "none"
          },
          {
            "name": "ProductionSupervisor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a040d030-cc53-4b56-b3a1-abc09f96e4f7",
            "sourceColumn": "ProductionSupervisor",
            "summarizeBy": "none"
          },
          {
            "name": "SafetyStockQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "479cc8dd-930e-4761-94c7-1ce43934ffa3",
            "sourceColumn": "SafetyStockQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "GoodsIssueUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41f8bf53-331b-4c18-937b-35c7a972a53d",
            "sourceColumn": "GoodsIssueUnit",
            "summarizeBy": "none"
          },
          {
            "name": "SourceOfSupplyCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fef3dd04-f52e-497f-950b-11ddd5ff0116",
            "sourceColumn": "SourceOfSupplyCategory",
            "summarizeBy": "none"
          },
          {
            "name": "ConsumptionReferenceProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95963232-f0f3-42b2-b4a9-49815c25f59e",
            "sourceColumn": "ConsumptionReferenceProduct",
            "summarizeBy": "none"
          },
          {
            "name": "ConsumptionReferencePlant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "26e70820-7cfa-46d3-acab-c8f1b6406bcc",
            "sourceColumn": "ConsumptionReferencePlant",
            "summarizeBy": "none"
          },
          {
            "name": "ConsumptionRefUsageEndDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f7f706fd-2d09-4781-b3d8-849fb1da42c1",
            "sourceColumn": "ConsumptionRefUsageEndDate",
            "summarizeBy": "none"
          },
          {
            "name": "ConsumptionQtyMultiplier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1b65bb41-734b-413e-aae2-084614ac2fed",
            "sourceColumn": "ConsumptionQtyMultiplier",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductUnitGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a97ec7b8-fd87-432a-a6d2-1ca5032d5259",
            "sourceColumn": "ProductUnitGroup",
            "summarizeBy": "none"
          },
          {
            "name": "DistrCntrDistributionProfile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3b2a61c-f9e5-44e0-9df4-a933f6fdc32f",
            "sourceColumn": "DistrCntrDistributionProfile",
            "summarizeBy": "none"
          },
          {
            "name": "ConsignmentControl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0a01351-b4a1-4cb4-8146-debe4ae33d07",
            "sourceColumn": "ConsignmentControl",
            "summarizeBy": "none"
          },
          {
            "name": "GoodIssueProcessingDays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c6f7c687-460a-477e-bf83-bcc70f453a3d",
            "sourceColumn": "GoodIssueProcessingDays",
            "summarizeBy": "sum"
          },
          {
            "name": "PlannedDeliveryDurationInDays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "da812132-cb9d-44fc-acab-dc2153d3aa6a",
            "sourceColumn": "PlannedDeliveryDurationInDays",
            "summarizeBy": "sum"
          },
          {
            "name": "IsActiveEntity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61e5692b-527a-43ad-91ca-963018f883a6",
            "sourceColumn": "IsActiveEntity",
            "summarizeBy": "none"
          },
          {
            "name": "ProductIsCriticalPrt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e721ff76-fa23-4db8-8548-62f9a4735d5a",
            "sourceColumn": "ProductIsCriticalPrt",
            "summarizeBy": "none"
          },
          {
            "name": "ProductLogisticsHandlingGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af15e59c-cad5-4677-bc65-24ccffb37e51",
            "sourceColumn": "ProductLogisticsHandlingGroup",
            "summarizeBy": "none"
          },
          {
            "name": "MaterialFreightGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c277969-4bb4-4bb1-a0fb-f57f960dc648",
            "sourceColumn": "MaterialFreightGroup",
            "summarizeBy": "none"
          },
          {
            "name": "OriginalBatchReferenceMaterial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8152b50-fe63-4e78-b1a3-a39967909db8",
            "sourceColumn": "OriginalBatchReferenceMaterial",
            "summarizeBy": "none"
          },
          {
            "name": "OriglBatchManagementIsRequired",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3898021-afe8-432f-8b57-302b8b302955",
            "sourceColumn": "OriglBatchManagementIsRequired",
            "summarizeBy": "none"
          },
          {
            "name": "ProductConfiguration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83660fa8-45b8-45be-a6e5-3edbf88f1cb3",
            "sourceColumn": "ProductConfiguration",
            "summarizeBy": "none"
          },
          {
            "name": "MRPController",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b49d5cd2-494a-4e20-80e4-035f14680b82",
            "sourceColumn": "MRPController",
            "summarizeBy": "none"
          },
          {
            "name": "Re-Order Point",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "16b19f2a-4d8e-4eba-8fd6-10da0079dd76",
            "sourceColumn": "Re-Order Point",
            "summarizeBy": "sum"
          },
          {
            "name": "Rounding Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f4600472-5362-4eb4-8e36-6683d2ae4157",
            "sourceColumn": "Rounding Value",
            "summarizeBy": "sum"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58d4054f-b42c-43f0-bdf2-fc907372c17f",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "0ad34ea9-dbbb-4127-b24f-4ac40a8f8ccd",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "ProductPlant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(ProductPlant[Product], ProductPlant[Plant])",
            "isDataTypeInferred": true,
            "lineageTag": "09424da5-1d43-4c75-9745-f310a4bc5abe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "nk_ProductPlant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc4af8b1-0d43-4c3e-9766-7075590b71bf",
            "sourceColumn": "nk_ProductPlant",
            "summarizeBy": "none"
          },
          {
            "name": "PlanningStrategyGroupID_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c8a1a30-dd61-4fa6-9ebe-1fa24b06119c",
            "sourceColumn": "PlanningStrategyGroupID_Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4ac4907a-281c-4544-afff-8fa46ea84f34",
        "partitions": [
          {
            "name": "ProductPlant-bcceb24b-088b-431a-bc6f-7fe7f1e166e9",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_dim_ProductPlant = Source{[Schema=\"dm_sales\",Item=\"vw_dim_ProductPlant\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_ProductPlant"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ProductSalesDelivery",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "sk_ProductSalesDelivery",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e36806ed-b24e-43b3-b402-ddfd7944955a",
            "sourceColumn": "sk_ProductSalesDelivery",
            "summarizeBy": "none"
          },
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f581a809-d80f-47f0-bc57-db324d85214a",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganizationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6bd480a6-0eb4-4359-94dc-4f12b70b6d71",
            "sourceColumn": "SalesOrganizationID",
            "summarizeBy": "none"
          },
          {
            "name": "DistributionChannelID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9597e296-64d1-430d-8e7d-c28d197fa1df",
            "sourceColumn": "DistributionChannelID",
            "summarizeBy": "none"
          },
          {
            "name": "DistributionChannel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "244f89bf-6e8c-46f0-b7e5-1e1702575427",
            "sourceColumn": "DistributionChannel",
            "summarizeBy": "none"
          },
          {
            "name": "AccountDetnProductGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94920e92-5690-4658-9d29-ce8899ffc600",
            "sourceColumn": "AccountDetnProductGroup",
            "summarizeBy": "none"
          },
          {
            "name": "IsMarkedForDeletion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4bb08ecb-4895-4289-910a-fcf1f7638f50",
            "sourceColumn": "IsMarkedForDeletion",
            "summarizeBy": "none"
          },
          {
            "name": "ItemCategoryGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad1e4cbe-0528-4289-a9d4-8da35e5d1c32",
            "sourceColumn": "ItemCategoryGroup",
            "summarizeBy": "none"
          },
          {
            "name": "ProductPlant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(ProductSalesDelivery[ProductID], ProductSalesDelivery[SalesOrganizationID])",
            "isDataTypeInferred": true,
            "lineageTag": "6baa95d4-f3f7-4801-a4ac-52e048fe9793",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MinimumOrderQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "134dd393-9536-443b-8ff9-c2952f6a1ca3",
            "sourceColumn": "MinimumOrderQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "SupplyingPlant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78d52d4e-20eb-499c-a079-ed2dabd791fc",
            "sourceColumn": "SupplyingPlant",
            "summarizeBy": "none"
          },
          {
            "name": "PriceSpecificationProductGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c60353e3-feb8-4d25-8649-851fe7ab6ab6",
            "sourceColumn": "PriceSpecificationProductGroup",
            "summarizeBy": "none"
          },
          {
            "name": "DeliveryNoteProcMinDelivQty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8fda649d-8106-4dfc-bb74-fe45387db057",
            "sourceColumn": "DeliveryNoteProcMinDelivQty",
            "summarizeBy": "sum"
          },
          {
            "name": "DeliveryQuantityUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2073d587-5f56-41bc-ba52-94095c02a375",
            "sourceColumn": "DeliveryQuantityUnit",
            "summarizeBy": "none"
          },
          {
            "name": "DeliveryQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "50384f9a-e129-460c-84a3-df4d9fc654af",
            "sourceColumn": "DeliveryQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductSalesStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7a38318-5ac5-4c1d-afb8-550704bb6dd5",
            "sourceColumn": "ProductSalesStatus",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSalesStatusValidityDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b02ce188-b2d1-4548-8f2b-dc578ddca61e",
            "sourceColumn": "ProductSalesStatusValidityDate",
            "summarizeBy": "none"
          },
          {
            "name": "SalesMeasureUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66ba45eb-e88a-4d3d-966a-9c1c9624e9bc",
            "sourceColumn": "SalesMeasureUnit",
            "summarizeBy": "none"
          },
          {
            "name": "IsConfigurable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90484a6d-c764-417f-b658-10572da6d40d",
            "sourceColumn": "IsConfigurable",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2065b858-3aab-4804-9977-b79f0e954a0a",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "62f9cd3f-4736-4bf8-bdb6-35e4939ee372",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "ItemCategoryGroupName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc315333-30f0-4a61-8ed3-f99a8de765a4",
            "sourceColumn": "ItemCategoryGroupName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "caa0bd0a-f842-4996-aef7-a146b6e0b4d5",
        "partitions": [
          {
            "name": "ProductSalesDelivery-c2124563-c077-440a-84b3-6e7475bbe881",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_fact_ProductSalesDelivery = Source{[Schema=\"dm_sales\",Item=\"vw_fact_ProductSalesDelivery\"]}[Data]",
                "in",
                "    dm_sales_vw_fact_ProductSalesDelivery"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ProductSalesThirdPartyDelivery",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "sk_ProductSalesOrg",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6831fc97-5a44-42e8-8866-25109fac0ec9",
            "sourceColumn": "sk_ProductSalesOrg",
            "summarizeBy": "none"
          },
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca1e124b-b975-4224-9a05-03c2e5bde051",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganizationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43db3a1c-ed60-4180-896b-c64e9baf7b8d",
            "sourceColumn": "SalesOrganizationID",
            "summarizeBy": "none"
          },
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e3d0089-9e05-441a-91c9-249b23c3199d",
            "sourceColumn": "Product",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50d74baf-0f3d-49b2-886b-3092954b701b",
            "sourceColumn": "SalesOrganization",
            "summarizeBy": "none"
          },
          {
            "name": "MinimumOrderQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "eb4e2432-473a-4c36-9036-20e9d4468d34",
            "sourceColumn": "MinimumOrderQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "SupplyingPlant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d1df190-eeb0-48fa-b222-db0ef2609bb5",
            "sourceColumn": "SupplyingPlant",
            "summarizeBy": "none"
          },
          {
            "name": "AccountDetnProductGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb6546d6-1a7f-4032-a541-053721eb0212",
            "sourceColumn": "AccountDetnProductGroup",
            "summarizeBy": "none"
          },
          {
            "name": "ItemCategoryGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41d54b72-414c-46ed-9ae8-80204ab1f9e3",
            "sourceColumn": "ItemCategoryGroup",
            "summarizeBy": "none"
          },
          {
            "name": "IsMarkedForDeletion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78a75ec6-5c23-4f3d-adfc-75d27a75ba10",
            "sourceColumn": "IsMarkedForDeletion",
            "summarizeBy": "none"
          },
          {
            "name": "CashDiscountIsDeductible",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d3eb25a8-3a88-4317-bf16-b7ed7ca344e7",
            "sourceColumn": "CashDiscountIsDeductible",
            "summarizeBy": "none"
          },
          {
            "name": "IsConfigurable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d921410-0838-4b3c-96f2-fef4d17f1ebd",
            "sourceColumn": "IsConfigurable",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50b36f6e-dea5-4cb6-a339-f554ae95399c",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "2afd349b-5f23-4ff7-8da0-b1f29d252a70",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1d7edf84-9756-4dff-8792-d59c10d27b84",
        "partitions": [
          {
            "name": "ProductSalesThirdPartyDelivery",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_scm_vw_fact_ProductSalesThirdPartyDelivery = Source{[Schema=\"dm_scm\",Item=\"vw_fact_ProductSalesThirdPartyDelivery\"]}[Data]",
                "in",
                "    dm_scm_vw_fact_ProductSalesThirdPartyDelivery"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}