CREATE PROC [edw].[sp_load_fact_SalesDocItem_SAPSnapshotMonthly]
  @t_jobId [varchar](36)
, @t_jobDtm [datetime]
, @t_lastActionCd [varchar](1)
, @t_jobBy [nvarchar](128)
AS
BEGIN
    DECLARE @isSnapshotMonthlyViewNotEmpty  BIT = 0;
    DECLARE @errmessage NVARCHAR(2048);

    BEGIN TRY
    
        SELECT TOP 1 @isSnapshotMonthlyViewNotEmpty = 1 FROM [edw].[vw_SalesDocItem_SAPSnapshotMonthly];

        IF (@isSnapshotMonthlyViewNotEmpty = 0)
            begin
                SET @errmessage = 'Temporary view [edw].[vw_SalesDocItem_SAPSnapshotMonthly] was not filled.';
                THROW 50001, @errmessage, 1;
            end;

	    IF OBJECT_ID('[edw].[fact_SalesDocItem_SAPSnapshotMonthly_tmp]') IS NOT NULL
		    DROP TABLE [edw].[fact_SalesDocItem_SAPSnapshotMonthly_tmp];

        CREATE TABLE [edw].[fact_SalesDocItem_SAPSnapshotMonthly_tmp]
        WITH
        (
            DISTRIBUTION = HASH ([nk_fact_SalesDocItem_SAPSnapshotMonthly]),
            CLUSTERED COLUMNSTORE INDEX
        )
        as select * from  [edw].[fact_SalesDocItem_SAPSnapshotMonthly]
        WHERE [SnapshotCalMonth] <> CONCAT(YEAR(@t_jobDtm), RIGHT('00'+CONVERT(VARCHAR(2), MONTH([t_jobDtm])), 2));

        INSERT INTO [edw].[fact_SalesDocItem_SAPSnapshotMonthly_tmp](
            [sk_fact_SalesDocItem_SAPSnapshotMonthly]
        ,   [nk_fact_SalesDocItem_SAPSnapshotMonthly]
        ,   [SalesDocument]
        ,   [SalesDocumentItem]
        ,   [CurrencyTypeID]
        ,   [CurrencyType]
        ,   [CurrencyID]
        ,   [ExchangeRate]
        ,   [SDDocumentCategoryID]
        ,   [SalesDocumentTypeID]
        ,   [SalesDocumentItemCategoryID]
        ,   [IsReturnsItemID]
        ,   [CreationDate]
        ,   [CreationTime]
        ,   [LastChangeDate]
        ,   [SalesOrganizationID]
        ,   [DistributionChannelID]
        ,   [DivisionID]
        ,   [SalesGroupID]
        ,   [SalesOfficeID]
        ,   [InternationalArticleNumberID]
        ,   [BatchID]
        ,   [MaterialID]
        ,   [OriginallyRequestedMaterialID]
        ,   [MaterialSubstitutionReasonID]
        ,   [MaterialGroupID]
        ,   [BrandID]
        ,   [Brand]
        ,   [AdditionalMaterialGroup2ID]
        ,   [AdditionalMaterialGroup3ID]
        ,   [AdditionalMaterialGroup4ID]
        ,   [AdditionalMaterialGroup5ID]
        ,   [SoldToPartyID]
        ,   [AdditionalCustomerGroup1ID]
        ,   [AdditionalCustomerGroup2ID]
        ,   [AdditionalCustomerGroup3ID]
        ,   [AdditionalCustomerGroup4ID]
        ,   [AdditionalCustomerGroup5ID]
        ,   [ShipToPartyID]
        ,   [PayerPartyID]
        ,   [BillToPartyID]
        ,   [SDDocumentReasonID]
        ,   [SalesDocumentDate]
        ,   [OrderQuantity]
        ,   [OrderQuantityUnitID]
        ,   [TargetQuantity]
        ,   [TargetQuantityUnitID]
        ,   [TargetToBaseQuantityDnmntr]
        ,   [TargetToBaseQuantityNmrtr]
        ,   [OrderToBaseQuantityDnmntr]
        ,   [OrderToBaseQuantityNmrtr]
        ,   [ConfdDelivQtyInOrderQtyUnit]
        ,   [TargetDelivQtyInOrderQtyUnit]
        ,   [ConfdDeliveryQtyInBaseUnit]
        ,   [BaseUnitID]
        ,   [ItemGrossWeight]
        ,   [ItemNetWeight]
        ,   [ItemWeightUnitID]
        ,   [ItemVolume]
        ,   [ItemVolumeUnitID]
        ,   [ServicesRenderedDate]
        ,   [SalesDistrictID]
        ,   [CustomerGroupID]
        ,   [HdrOrderProbabilityInPercentID]
        ,   [ItemOrderProbabilityInPercentID]
        ,   [SalesDocumentRjcnReasonID]
        ,   [PricingDate]
        ,   [ExchangeRateDate]
        ,   [PriceDetnExchangeRate]
        ,   [StatisticalValueControlID]
        ,   [NetAmount]
        ,   [TransactionCurrencyID]
        ,   [SalesOrganizationCurrencyID]
        ,   [NetPriceAmount]
        ,   [NetPriceQuantity]
        ,   [NetPriceQuantityUnitID]
        ,   [TaxAmount]
        ,   [CostAmount]
        ,   [Margin]
        ,   [Subtotal1Amount]
        ,   [Subtotal2Amount]
        ,   [Subtotal3Amount]
        ,   [Subtotal4Amount]
        ,   [Subtotal5Amount]
        ,   [Subtotal6Amount]
        ,   [ShippingPointID]
        ,   [ShippingTypeID]
        ,   [DeliveryPriorityID]
        ,   [InventorySpecialStockTypeID]
        ,   [RequestedDeliveryDate]
        ,   [ShippingConditionID]
        ,   [DeliveryBlockReasonID]
        ,   [PlantID]
        ,   [StorageLocationID]
        ,   [RouteID]
        ,   [IncotermsClassificationID]
        ,   [IncotermsVersionID]
        ,   [IncotermsTransferLocationID]
        ,   [IncotermsLocation1ID]
        ,   [IncotermsLocation2ID]
        ,   [MinDeliveryQtyInBaseUnit]
        ,   [UnlimitedOverdeliveryIsAllowedID]
        ,   [OverdelivTolrtdLmtRatioInPct]
        ,   [UnderdelivTolrtdLmtRatioInPct]
        ,   [PartialDeliveryIsAllowedID]
        ,   [BindingPeriodValidityStartDate]
        ,   [BindingPeriodValidityEndDate]
        ,   [OutlineAgreementTargetAmount]
        ,   [BillingDocumentDate]
        ,   [BillingCompanyCodeID]
        ,   [HeaderBillingBlockReasonID]
        ,   [ItemBillingBlockReasonID]
        ,   [FiscalYearID]
        ,   [FiscalPeriodID]
        ,   [CustomerAccountAssignmentGroupID]
        ,   [ExchangeRateTypeID]
        ,   [CompanyCodeCurrencyID]
        ,   [FiscalYearVariantID]
        ,   [BusinessAreaID]
        ,   [ProfitCenterID]
        ,   [OrderID]
        ,   [ProfitabilitySegmentID]
        ,   [ControllingAreaID]
        ,   [ReferenceSDDocumentID]
        ,   [ReferenceSDDocumentItemID]
        ,   [ReferenceSDDocumentCategoryID]
        ,   [OriginSDDocumentID]
        ,   [OriginSDDocumentItemID]
        ,   [OverallSDProcessStatusID]
        ,   [OverallTotalDeliveryStatusID]
        ,   [OverallOrdReltdBillgStatusID]
        ,   [TotalCreditCheckStatusID]
        ,   [DeliveryBlockStatusID]
        ,   [BillingBlockStatusID]
        ,   [TotalSDDocReferenceStatusID]
        ,   [SDDocReferenceStatusID]
        ,   [OverallSDDocumentRejectionStsID]
        ,   [SDDocumentRejectionStatusID]
        ,   [OverallTotalSDDocRefStatusID]
        ,   [OverallSDDocReferenceStatusID]
        ,   [ItemGeneralIncompletionStatusID]
        ,   [ItemBillingIncompletionStatusID]
        ,   [PricingIncompletionStatusID]
        ,   [ItemDeliveryIncompletionStatusID]
        ,   [ExternalSalesAgentID]
        ,   [ExternalSalesAgent]
        ,   [GlobalParentID]
        ,   [GlobalParent]
        ,   [LocalParentID]
        ,   [LocalParent]
        ,   [ProjectID]
        ,   [Project]
        ,   [SalesEmployeeID]
        ,   [SalesEmployee]
        ,   [GlobalParentCalculatedID]
        ,   [GlobalParentCalculated]
        ,   [LocalParentCalculatedID]
        ,   [LocalParentCalculated]
        ,   [SDoc_ControllingObjectID]
        ,   [SDItem_ControllingObjectID]
        ,   [CorrespncExternalReference] 
        ,   [InOutID]
        ,   [SnapshotCalMonth]
        ,   [SnapshotDate]
        ,   [t_applicationId]
        ,   [t_extractionDtm]
        ,   [t_jobId]
        ,   [t_jobDtm]
        ,   [t_lastActionCd]
        ,   [t_jobBy]
        )
        SELECT
            [sk_fact_SalesDocItem_SAPSnapshotMonthly]
        ,   [nk_fact_SalesDocItem_SAPSnapshotMonthly]
        ,   [SalesDocument]
        ,   [SalesDocumentItem]
        ,   [CurrencyTypeID]
        ,   [CurrencyType]
        ,   [CurrencyID]
        ,   [ExchangeRate]
        ,   [SDDocumentCategoryID]
        ,   [SalesDocumentTypeID]
        ,   [SalesDocumentItemCategoryID]
        ,   [IsReturnsItemID]
        ,   [CreationDate]
        ,   [CreationTime]
        ,   [LastChangeDate]
        ,   [SalesOrganizationID]
        ,   [DistributionChannelID]
        ,   [DivisionID]
        ,   [SalesGroupID]
        ,   [SalesOfficeID]
        ,   [InternationalArticleNumberID]
        ,   [BatchID]
        ,   [MaterialID]
        ,   [OriginallyRequestedMaterialID]
        ,   [MaterialSubstitutionReasonID]
        ,   [MaterialGroupID]
        ,   [BrandID]
        ,   [Brand]
        ,   [AdditionalMaterialGroup2ID]
        ,   [AdditionalMaterialGroup3ID]
        ,   [AdditionalMaterialGroup4ID]
        ,   [AdditionalMaterialGroup5ID]
        ,   [SoldToPartyID]
        ,   [AdditionalCustomerGroup1ID]
        ,   [AdditionalCustomerGroup2ID]
        ,   [AdditionalCustomerGroup3ID]
        ,   [AdditionalCustomerGroup4ID]
        ,   [AdditionalCustomerGroup5ID]
        ,   [ShipToPartyID]
        ,   [PayerPartyID]
        ,   [BillToPartyID]
        ,   [SDDocumentReasonID]
        ,   [SalesDocumentDate]
        ,   [OrderQuantity]
        ,   [OrderQuantityUnitID]
        ,   [TargetQuantity]
        ,   [TargetQuantityUnitID]
        ,   [TargetToBaseQuantityDnmntr]
        ,   [TargetToBaseQuantityNmrtr]
        ,   [OrderToBaseQuantityDnmntr]
        ,   [OrderToBaseQuantityNmrtr]
        ,   [ConfdDelivQtyInOrderQtyUnit]
        ,   [TargetDelivQtyInOrderQtyUnit]
        ,   [ConfdDeliveryQtyInBaseUnit]
        ,   [BaseUnitID]
        ,   [ItemGrossWeight]
        ,   [ItemNetWeight]
        ,   [ItemWeightUnitID]
        ,   [ItemVolume]
        ,   [ItemVolumeUnitID]
        ,   [ServicesRenderedDate]
        ,   [SalesDistrictID]
        ,   [CustomerGroupID]
        ,   [HdrOrderProbabilityInPercentID]
        ,   [ItemOrderProbabilityInPercentID]
        ,   [SalesDocumentRjcnReasonID]
        ,   [PricingDate]
        ,   [ExchangeRateDate]
        ,   [PriceDetnExchangeRate]
        ,   [StatisticalValueControlID]
        ,   [NetAmount]
        ,   [TransactionCurrencyID]
        ,   [SalesOrganizationCurrencyID]
        ,   [NetPriceAmount]
        ,   [NetPriceQuantity]
        ,   [NetPriceQuantityUnitID]
        ,   [TaxAmount]
        ,   [CostAmount]
        ,   [Margin]
        ,   [Subtotal1Amount]
        ,   [Subtotal2Amount]
        ,   [Subtotal3Amount]
        ,   [Subtotal4Amount]
        ,   [Subtotal5Amount]
        ,   [Subtotal6Amount]
        ,   [ShippingPointID]
        ,   [ShippingTypeID]
        ,   [DeliveryPriorityID]
        ,   [InventorySpecialStockTypeID]
        ,   [RequestedDeliveryDate]
        ,   [ShippingConditionID]
        ,   [DeliveryBlockReasonID]
        ,   [PlantID]
        ,   [StorageLocationID]
        ,   [RouteID]
        ,   [IncotermsClassificationID]
        ,   [IncotermsVersionID]
        ,   [IncotermsTransferLocationID]
        ,   [IncotermsLocation1ID]
        ,   [IncotermsLocation2ID]
        ,   [MinDeliveryQtyInBaseUnit]
        ,   [UnlimitedOverdeliveryIsAllowedID]
        ,   [OverdelivTolrtdLmtRatioInPct]
        ,   [UnderdelivTolrtdLmtRatioInPct]
        ,   [PartialDeliveryIsAllowedID]
        ,   [BindingPeriodValidityStartDate]
        ,   [BindingPeriodValidityEndDate]
        ,   [OutlineAgreementTargetAmount]
        ,   [BillingDocumentDate]
        ,   [BillingCompanyCodeID]
        ,   [HeaderBillingBlockReasonID]
        ,   [ItemBillingBlockReasonID]
        ,   [FiscalYearID]
        ,   [FiscalPeriodID]
        ,   [CustomerAccountAssignmentGroupID]
        ,   [ExchangeRateTypeID]
        ,   [CompanyCodeCurrencyID]
        ,   [FiscalYearVariantID]
        ,   [BusinessAreaID]
        ,   [ProfitCenterID]
        ,   [OrderID]
        ,   [ProfitabilitySegmentID]
        ,   [ControllingAreaID]
        ,   [ReferenceSDDocumentID]
        ,   [ReferenceSDDocumentItemID]
        ,   [ReferenceSDDocumentCategoryID]
        ,   [OriginSDDocumentID]
        ,   [OriginSDDocumentItemID]
        ,   [OverallSDProcessStatusID]
        ,   [OverallTotalDeliveryStatusID]
        ,   [OverallOrdReltdBillgStatusID]
        ,   [TotalCreditCheckStatusID]
        ,   [DeliveryBlockStatusID]
        ,   [BillingBlockStatusID]
        ,   [TotalSDDocReferenceStatusID]
        ,   [SDDocReferenceStatusID]
        ,   [OverallSDDocumentRejectionStsID]
        ,   [SDDocumentRejectionStatusID]
        ,   [OverallTotalSDDocRefStatusID]
        ,   [OverallSDDocReferenceStatusID]
        ,   [ItemGeneralIncompletionStatusID]
        ,   [ItemBillingIncompletionStatusID]
        ,   [PricingIncompletionStatusID]
        ,   [ItemDeliveryIncompletionStatusID]
        ,   [ExternalSalesAgentID]
        ,   [ExternalSalesAgent]
        ,   [GlobalParentID]
        ,   [GlobalParent]
        ,   [LocalParentID]
        ,   [LocalParent]
        ,   [ProjectID]
        ,   [Project]
        ,   [SalesEmployeeID]
        ,   [SalesEmployee]
        ,   [GlobalParentCalculatedID]
        ,   [GlobalParentCalculated]
        ,   [LocalParentCalculatedID]
        ,   [LocalParentCalculated]
        ,   [SDoc_ControllingObjectID]
        ,   [SDItem_ControllingObjectID]
        ,   [CorrespncExternalReference] 
        ,   [InOutID]
        ,   [SnapshotCalMonth]
        ,   [SnapshotDate]
        ,   [t_applicationId]
        ,   [t_extractionDtm]
        ,   @t_jobId AS t_jobId
        ,   @t_jobDtm AS t_jobDtm
        ,   @t_lastActionCd AS t_lastActionCd
        ,   @t_jobBy AS t_jobBy
        FROM
            [edw].[vw_SalesDocItem_SAPSnapshotMonthly];

        RENAME OBJECT [edw].[fact_SalesDocItem_SAPSnapshotMonthly] TO [fact_SalesDocItem_SAPSnapshotMonthly_old];
        RENAME OBJECT [edw].[fact_SalesDocItem_SAPSnapshotMonthly_tmp] TO [fact_SalesDocItem_SAPSnapshotMonthly];
        DROP TABLE [edw].[fact_SalesDocItem_SAPSnapshotMonthly_old];

    END TRY
    BEGIN CATCH
        SET @errmessage = 'Internal error in ' + ERROR_PROCEDURE() + '. ' +  ERROR_MESSAGE();
		THROW 50001, @errmessage, 1;
    END CATCH
END