CREATE PROC [edw].[sp_load_fact_BillingDocumentItem_s4h_active]
  @t_jobId [varchar](36)
, @t_jobDtm [datetime]
, @t_jobBy [nvarchar](128)
, @t_lastActionCd [varchar](1) -- workaround with option to save single solution in DF
AS
BEGIN
    DECLARE @errmessage NVARCHAR(2048);
    
    BEGIN TRY
        update [edw].[fact_BillingDocumentItem_s4h_active] 
            SET -- exclude [BillingDocument], [SalesDocumentItem], [CurrencyTypeID] is it pk_key                     
              [CurrencyType]                          = vwBD.[CurrencyType]                          
            , [CurrencyID]                            = vwBD.[CurrencyID]                            
            , [ExchangeRate]                          = vwBD.[ExchangeRate]                          
            , [SalesDocumentItemCategoryID]           = vwBD.[SalesDocumentItemCategoryID]           
            , [SalesDocumentItemTypeID]               = vwBD.[SalesDocumentItemTypeID]               
            , [ReturnItemProcessingType]              = vwBD.[ReturnItemProcessingType]              
            , [BillingDocumentTypeID]                 = vwBD.[BillingDocumentTypeID]                 
            , [BillingDocumentCategoryID]             = vwBD.[BillingDocumentCategoryID]             
            , [SDDocumentCategoryID]                  = vwBD.[SDDocumentCategoryID]                  
            , [CreationDate]                          = vwBD.[CreationDate]                          
            , [CreationTime]                          = vwBD.[CreationTime]                          
            , [LastChangeDate]                        = vwBD.[LastChangeDate]                        
            , [BillingDocumentDate]                   = vwBD.[BillingDocumentDate]                   
            , [BillingDocumentIsTemporary]            = vwBD.[BillingDocumentIsTemporary]            
            , [OrganizationDivision]                  = vwBD.[OrganizationDivision]                  
            , [Division]                              = vwBD.[Division]                              
            , [SalesOfficeID]                         = vwBD.[SalesOfficeID]                         
            , [SalesOrganizationID]                   = vwBD.[SalesOrganizationID]                   
            , [DistributionChannelID]                 = vwBD.[DistributionChannelID]                 
            , [Material]                              = vwBD.[Material]
            , [ProductSurrogateKey]                   = vwBD.[ProductSurrogateKey]
            , [OriginallyRequestedMaterial]           = vwBD.[OriginallyRequestedMaterial]           
            , [InternationalArticleNumber]            = vwBD.[InternationalArticleNumber]            
            , [PricingReferenceMaterial]              = vwBD.[PricingReferenceMaterial]              
            , [LengthInMPer1]                         = vwBD.[LengthInMPer1]                         
            , [LengthInM]                             = vwBD.[LengthInM]                             
            , [Batch]                                 = vwBD.[Batch]                                 
            , [MaterialGroupID]                       = vwBD.[MaterialGroupID]  
            , [BrandID]                               = vwBD.[BrandID]                                                             
            , [AdditionalMaterialGroup2]              = vwBD.[AdditionalMaterialGroup2]              
            , [AdditionalMaterialGroup3]              = vwBD.[AdditionalMaterialGroup3]              
            , [AdditionalMaterialGroup4]              = vwBD.[AdditionalMaterialGroup4]              
            , [AdditionalMaterialGroup5]              = vwBD.[AdditionalMaterialGroup5]              
            , [MaterialCommissionGroup]               = vwBD.[MaterialCommissionGroup]               
            , [PlantID]                               = vwBD.[PlantID]                               
            , [StorageLocationID]                     = vwBD.[StorageLocationID]                     
            , [BillingDocumentIsCancelled]            = vwBD.[BillingDocumentIsCancelled]            
            , [CancelledBillingDocument]              = vwBD.[CancelledBillingDocument]              
            , [CancelledInvoiceEffect]                = vwBD.[CancelledInvoiceEffect]
            , [BillingDocumentItemText]               = vwBD.[BillingDocumentItemText]               
            , [ServicesRenderedDate]                  = vwBD.[ServicesRenderedDate]                  
            , [BillingQuantity]                       = vwBD.[BillingQuantity]                       
            , [BillingQuantityUnitID]                 = vwBD.[BillingQuantityUnitID]                 
            , [BillingQuantityInBaseUnit]             = vwBD.[BillingQuantityInBaseUnit]             
            , [BaseUnit]                              = vwBD.[BaseUnit]                              
            , [MRPRequiredQuantityInBaseUnit]         = vwBD.[MRPRequiredQuantityInBaseUnit]         
            , [BillingToBaseQuantityDnmntr]           = vwBD.[BillingToBaseQuantityDnmntr]           
            , [BillingToBaseQuantityNmrtr]            = vwBD.[BillingToBaseQuantityNmrtr]            
            , [ItemGrossWeight]                       = vwBD.[ItemGrossWeight]                       
            , [ItemNetWeight]                         = vwBD.[ItemNetWeight]                         
            , [ItemWeightUnit]                        = vwBD.[ItemWeightUnit]                        
            , [ItemVolume]                            = vwBD.[ItemVolume]                            
            , [ItemVolumeUnit]                        = vwBD.[ItemVolumeUnit]                        
            , [BillToPartyCountry]                    = vwBD.[BillToPartyCountry]                    
            , [BillToPartyRegion]                     = vwBD.[BillToPartyRegion]                     
            , [BillingPlanRule]                       = vwBD.[BillingPlanRule]                       
            , [BillingPlan]                           = vwBD.[BillingPlan]                           
            , [BillingPlanItem]                       = vwBD.[BillingPlanItem]                       
            , [CustomerPriceGroupID]                  = vwBD.[CustomerPriceGroupID]                  
            , [PriceListTypeID]                       = vwBD.[PriceListTypeID]                       
            , [TaxDepartureCountry]                   = vwBD.[TaxDepartureCountry]                   
            , [VATRegistration]                       = vwBD.[VATRegistration]                       
            , [VATRegistrationCountry]                = vwBD.[VATRegistrationCountry]                
            , [VATRegistrationOrigin]                 = vwBD.[VATRegistrationOrigin]                 
            , [CustomerTaxClassification1]            = vwBD.[CustomerTaxClassification1]            
            , [CustomerTaxClassification2]            = vwBD.[CustomerTaxClassification2]            
            , [CustomerTaxClassification3]            = vwBD.[CustomerTaxClassification3]            
            , [CustomerTaxClassification4]            = vwBD.[CustomerTaxClassification4]            
            , [CustomerTaxClassification5]            = vwBD.[CustomerTaxClassification5]            
            , [CustomerTaxClassification6]            = vwBD.[CustomerTaxClassification6]            
            , [CustomerTaxClassification7]            = vwBD.[CustomerTaxClassification7]            
            , [CustomerTaxClassification8]            = vwBD.[CustomerTaxClassification8]            
            , [CustomerTaxClassification9]            = vwBD.[CustomerTaxClassification9]            
            , [SDPricingProcedure]                    = vwBD.[SDPricingProcedure]                    
            , [NetAmount]                             = vwBD.[NetAmount]                             
            , [TransactionCurrencyID]                 = vwBD.[TransactionCurrencyID]                 
            , [GrossAmount]                           = vwBD.[GrossAmount]                           
            , [PricingDate]                           = vwBD.[PricingDate]                           
            , [PriceDetnExchangeRate]                 = vwBD.[PriceDetnExchangeRate]                 
            , [PricingScaleQuantityInBaseUnit]        = vwBD.[PricingScaleQuantityInBaseUnit]        
            , [TaxAmount]                             = vwBD.[TaxAmount]                             
            , [CostAmount]                            = vwBD.[CostAmount]                         
            , [Subtotal1Amount]                       = vwBD.[Subtotal1Amount]                       
            , [Subtotal2Amount]                       = vwBD.[Subtotal2Amount]                       
            , [Subtotal3Amount]                       = vwBD.[Subtotal3Amount]                       
            , [Subtotal4Amount]                       = vwBD.[Subtotal4Amount]                       
            , [Subtotal5Amount]                       = vwBD.[Subtotal5Amount]                       
            , [Subtotal6Amount]                       = vwBD.[Subtotal6Amount]                       
            , [StatisticalValueControl]               = vwBD.[StatisticalValueControl]               
            , [StatisticsExchangeRate]                = vwBD.[StatisticsExchangeRate]                
            , [StatisticsCurrency]                    = vwBD.[StatisticsCurrency]                    
            , [SalesOrganizationCurrency]             = vwBD.[SalesOrganizationCurrency]             
            , [EligibleAmountForCashDiscount]         = vwBD.[EligibleAmountForCashDiscount]         
            , [ContractAccount]                       = vwBD.[ContractAccount]                       
            , [CustomerPaymentTerms]                  = vwBD.[CustomerPaymentTerms]                  
            , [PaymentMethod]                         = vwBD.[PaymentMethod]                         
            , [PaymentReference]                      = vwBD.[PaymentReference]                      
            , [FixedValueDate]                        = vwBD.[FixedValueDate]                        
            , [AdditionalValueDays]                   = vwBD.[AdditionalValueDays]                   
            , [PayerParty]                            = vwBD.[PayerParty]                            
            , [CompanyCode]                           = vwBD.[CompanyCode]                           
            , [FiscalYear]                            = vwBD.[FiscalYear]                            
            , [FiscalPeriod]                          = vwBD.[FiscalPeriod]                          
            , [CustomerAccountAssignmentGroupID]      = vwBD.[CustomerAccountAssignmentGroupID]      
            , [BusinessArea]                          = vwBD.[BusinessArea]                          
            , [ProfitCenter]                          = vwBD.[ProfitCenter]                          
            , [OrderID]                               = vwBD.[OrderID]                               
            , [ControllingArea]                       = vwBD.[ControllingArea]                       
            , [ProfitabilitySegment]                  = vwBD.[ProfitabilitySegment]                  
            , [CostCenter]                            = vwBD.[CostCenter]                            
            , [OriginSDDocument]                      = vwBD.[OriginSDDocument]                      
            , [OriginSDDocumentItem]                  = vwBD.[OriginSDDocumentItem]                  
            , [PriceDetnExchangeRateDate]             = vwBD.[PriceDetnExchangeRateDate]             
            , [ExchangeRateTypeID]                    = vwBD.[ExchangeRateTypeID]                    
            , [FiscalYearVariant]                     = vwBD.[FiscalYearVariant]                     
            , [CompanyCodeCurrencyID]                 = vwBD.[CompanyCodeCurrencyID]                 
            , [AccountingExchangeRate]                = vwBD.[AccountingExchangeRate]                
            , [AccountingExchangeRateIsSet]           = vwBD.[AccountingExchangeRateIsSet]           
            , [ReferenceSDDocument]                   = vwBD.[ReferenceSDDocument]                   
            , [ReferenceSDDocumentItem]               = vwBD.[ReferenceSDDocumentItem]               
            , [ReferenceSDDocumentCategoryID]         = vwBD.[ReferenceSDDocumentCategoryID]         
            , [SalesDocumentID]                       = vwBD.[SalesDocumentID]                       
            , [SalesDocumentItemID]                   = vwBD.[SalesDocumentItemID]                   
            , [SalesSDDocumentCategoryID]             = vwBD.[SalesSDDocumentCategoryID]             
            , [HigherLevelItem]                       = vwBD.[HigherLevelItem]                       
            , [BillingDocumentItemInPartSgmt]         = vwBD.[BillingDocumentItemInPartSgmt]         
            , [SalesGroup]                            = vwBD.[SalesGroup]                            
            , [AdditionalCustomerGroup1]              = vwBD.[AdditionalCustomerGroup1]              
            , [AdditionalCustomerGroup2]              = vwBD.[AdditionalCustomerGroup2]              
            , [AdditionalCustomerGroup3]              = vwBD.[AdditionalCustomerGroup3]              
            , [AdditionalCustomerGroup4]              = vwBD.[AdditionalCustomerGroup4]              
            , [AdditionalCustomerGroup5]              = vwBD.[AdditionalCustomerGroup5]              
            , [SDDocumentReasonID]                    = vwBD.[SDDocumentReasonID]                    
            , [ItemIsRelevantForCredit]               = vwBD.[ItemIsRelevantForCredit]               
            , [CreditRelatedPrice]                    = vwBD.[CreditRelatedPrice]                    
            , [SalesDistrictID]                       = vwBD.[SalesDistrictID]                       
            , [CustomerGroupID]                       = vwBD.[CustomerGroupID]                       
            , [SoldToParty]                           = vwBD.[SoldToParty]                           
            , [CountryID]                             = vwBD.[CountryID]                             
            , [ShipToParty]                           = vwBD.[ShipToParty]                           
            , [BillToParty]                           = vwBD.[BillToParty]                           
            , [ShippingPoint]                         = vwBD.[ShippingPoint]                         
            , [IncotermsVersion]                      = vwBD.[IncotermsVersion]                      
            , [IncotermsClassification]               = vwBD.[IncotermsClassification]               
            , [IncotermsTransferLocation]             = vwBD.[IncotermsTransferLocation]             
            , [IncotermsLocation1]                    = vwBD.[IncotermsLocation1]                    
            , [IncotermsLocation2]                    = vwBD.[IncotermsLocation2]                    
            , [ShippingCondition]                     = vwBD.[ShippingCondition]                     
            , [QuantitySold]                          = vwBD.[QuantitySold]                          
            , [GrossMargin]                           = vwBD.[GrossMargin]                           
            , [ExternalSalesAgentID]                  = vwBD.[ExternalSalesAgentID]                  
            , [ExternalSalesAgent]                    = vwBD.[ExternalSalesAgent]                    
            , [ProjectID]                             = vwBD.[ProjectID]                             
            , [Project]                               = vwBD.[Project]                               
            , [SalesEmployeeID]                       = vwBD.[SalesEmployeeID]                       
            , [SalesEmployee]                         = vwBD.[SalesEmployee]                         
            , [GlobalParentID]                        = vwBD.[GlobalParentID]                        
            , [GlobalParent]                          = vwBD.[GlobalParent]                          
            , [GlobalParentCalculatedID]              = vwBD.[GlobalParentCalculatedID]              
            , [GlobalParentCalculated]                = vwBD.[GlobalParentCalculated]                
            , [LocalParentID]                         = vwBD.[LocalParentID]                         
            , [LocalParent]                           = vwBD.[LocalParent]                           
            , [LocalParentCalculatedID]               = vwBD.[LocalParentCalculatedID]               
            , [LocalParentCalculated]                 = vwBD.[LocalParentCalculated]                 
            , [SalesOrderTypeID]                      = vwBD.[SalesOrderTypeID]                      
            , [BillToID]                              = vwBD.[BillToID]                              
            , [BillTo]                                = vwBD.[BillTo]                                
            , [FinNetAmountRealProduct]               = vwBD.[FinNetAmountRealProduct]               
            , [FinNetAmountFreight]                   = vwBD.[FinNetAmountFreight]                   
            , [FinNetAmountMinQty]                    = vwBD.[FinNetAmountMinQty]                    
            , [FinNetAmountEngServ]                   = vwBD.[FinNetAmountEngServ]                   
            , [FinNetAmountMisc]                      = vwBD.[FinNetAmountMisc]                      
            , [FinNetAmountServOther]                 = vwBD.[FinNetAmountServOther]                 
            , [FinNetAmountVerp]                      = vwBD.[FinNetAmountVerp]                      
            , [FinRebateAccrual]                      = vwBD.[FinRebateAccrual]                      
            , [PaymentTermCashDiscountPercentageRate] = vwBD.[PaymentTermCashDiscountPercentageRate] 
            , [FinNetAmountOtherSales]                = vwBD.[FinNetAmountOtherSales]                
            , [FinReserveCashDiscount]                = vwBD.[FinReserveCashDiscount]                
            , [FinNetAmountAllowances]                = vwBD.[FinNetAmountAllowances]                
            , [FinSales100]                           = vwBD.[FinSales100]                           
            , [AccountingDate]                        = vwBD.[AccountingDate]                        
--            , [axbi_DataAreaID]                       = vwBD.[axbi_DataAreaID]                       
--            , [axbi_DataAreaName]                     = vwBD.[axbi_DataAreaName]                     
--            , [axbi_DataAreaGroup]                    = vwBD.[axbi_DataAreaGroup]                    
--            , [axbi_MaterialID]                       = vwBD.[axbi_MaterialID]                       
--            , [axbi_CustomerID]                       = vwBD.[axbi_CustomerID]                       
            , [MaterialCalculated]                    = vwBD.[MaterialCalculated]                    
            , [SoldToPartyCalculated]                 = vwBD.[SoldToPartyCalculated]                 
            , [InOutID]                               = vwBD.[InOutID]                               
--            , [axbi_ItemNoCalc]                       = vwBD.[axbi_ItemNoCalc]                    
            , [t_applicationId]                       = vwBD.[t_applicationId]
            , [t_extractionDtm]                       = vwBD.[t_extractionDtm]
            , [t_jobId]                               =  @t_jobId 
            , [t_jobDtm]                              =  @t_jobDtm 
            , [t_jobBy]                               =  @t_jobBy 
            , [t_lastActionBy]                        = vwBD.[t_lastActionBy]
            , [t_lastActionCd]                        = vwBD.[t_lastActionCd]
            , [t_lastActionDtm]                       = vwBD.[t_lastActionDtm]   
        FROM [edw].[fact_BillingDocumentItem_s4h_active]  AS tBD
        JOIN [edw].[vw_BillingDocumentItem_s4h_fin_delta] AS vwBD  
            ON (
                tBD.[BillingDocument] = vwBD.[BillingDocument]
            AND
                tBD.[BillingDocumentItem] = vwBD.[BillingDocumentItem]
            AND
                tBD.[CurrencyTypeID] = vwBD.[CurrencyTypeID])

        INSERT [edw].[fact_BillingDocumentItem_s4h_active] (
              [BillingDocument]
            , [BillingDocumentItem]
            , [CurrencyTypeID]
            , [CurrencyType]
            , [CurrencyID]
            , [ExchangeRate]
            , [SalesDocumentItemCategoryID]
            , [SalesDocumentItemTypeID]
            , [ReturnItemProcessingType]
            , [BillingDocumentTypeID]
            , [BillingDocumentCategoryID]
            , [SDDocumentCategoryID]
            , [CreationDate]
            , [CreationTime]
            , [LastChangeDate]
            , [BillingDocumentDate]
            , [BillingDocumentIsTemporary]
            , [OrganizationDivision]
            , [Division]
            , [SalesOfficeID]
            , [SalesOrganizationID]
            , [DistributionChannelID]
            , [Material]
            , [ProductSurrogateKey]
            , [OriginallyRequestedMaterial]
            , [InternationalArticleNumber]
            , [PricingReferenceMaterial]
            , [LengthInMPer1]
            , [LengthInM]
            , [Batch]
            , [MaterialGroupID]
            , [BrandID]
            , [AdditionalMaterialGroup2]
            , [AdditionalMaterialGroup3]
            , [AdditionalMaterialGroup4]
            , [AdditionalMaterialGroup5]
            , [MaterialCommissionGroup]
            , [PlantID]
            , [StorageLocationID]
            , [BillingDocumentIsCancelled]
            , [CancelledBillingDocument]
            , [CancelledInvoiceEffect]
            , [BillingDocumentItemText]
            , [ServicesRenderedDate]
            , [BillingQuantity]
            , [BillingQuantityUnitID]
            , [BillingQuantityInBaseUnit]
            , [BaseUnit]
            , [MRPRequiredQuantityInBaseUnit]
            , [BillingToBaseQuantityDnmntr]
            , [BillingToBaseQuantityNmrtr]
            , [ItemGrossWeight]
            , [ItemNetWeight]
            , [ItemWeightUnit]
            , [ItemVolume]
            , [ItemVolumeUnit]
            , [BillToPartyCountry]
            , [BillToPartyRegion]
            , [BillingPlanRule]
            , [BillingPlan]
            , [BillingPlanItem]
            , [CustomerPriceGroupID]
            , [PriceListTypeID]
            , [TaxDepartureCountry]
            , [VATRegistration]
            , [VATRegistrationCountry]
            , [VATRegistrationOrigin]
            , [CustomerTaxClassification1]
            , [CustomerTaxClassification2]
            , [CustomerTaxClassification3]
            , [CustomerTaxClassification4]
            , [CustomerTaxClassification5]
            , [CustomerTaxClassification6]
            , [CustomerTaxClassification7]
            , [CustomerTaxClassification8]
            , [CustomerTaxClassification9]
            , [SDPricingProcedure]
            , [NetAmount]
            , [TransactionCurrencyID]
            , [GrossAmount]
            , [PricingDate]
            , [PriceDetnExchangeRate]
            , [PricingScaleQuantityInBaseUnit]
            , [TaxAmount]
            , [CostAmount]
            , [Subtotal1Amount]
            , [Subtotal2Amount]
            , [Subtotal3Amount]
            , [Subtotal4Amount]
            , [Subtotal5Amount]
            , [Subtotal6Amount]
            , [StatisticalValueControl]
            , [StatisticsExchangeRate]
            , [StatisticsCurrency]
            , [SalesOrganizationCurrency]
            , [EligibleAmountForCashDiscount]
            , [ContractAccount]
            , [CustomerPaymentTerms]
            , [PaymentMethod]
            , [PaymentReference]
            , [FixedValueDate]
            , [AdditionalValueDays]
            , [PayerParty]
            , [CompanyCode]
            , [FiscalYear]
            , [FiscalPeriod]
            , [CustomerAccountAssignmentGroupID]
            , [BusinessArea]
            , [ProfitCenter]
            , [OrderID]
            , [ControllingArea]
            , [ProfitabilitySegment]
            , [CostCenter]
            , [OriginSDDocument]
            , [OriginSDDocumentItem]
            , [PriceDetnExchangeRateDate]
            , [ExchangeRateTypeID]
            , [FiscalYearVariant]
            , [CompanyCodeCurrencyID]
            , [AccountingExchangeRate]
            , [AccountingExchangeRateIsSet]
            , [ReferenceSDDocument]
            , [ReferenceSDDocumentItem]
            , [ReferenceSDDocumentCategoryID]
            , [SalesDocumentID]
            , [SalesDocumentItemID]
            , [SalesSDDocumentCategoryID]
            , [HigherLevelItem]
            , [BillingDocumentItemInPartSgmt]
            , [SalesGroup]
            , [AdditionalCustomerGroup1]
            , [AdditionalCustomerGroup2]
            , [AdditionalCustomerGroup3]
            , [AdditionalCustomerGroup4]
            , [AdditionalCustomerGroup5]
            , [SDDocumentReasonID]
            , [ItemIsRelevantForCredit]
            , [CreditRelatedPrice]
            , [SalesDistrictID]
            , [CustomerGroupID]
            , [SoldToParty]
            , [CountryID]
            , [ShipToParty]
            , [BillToParty]
            , [ShippingPoint]
            , [IncotermsVersion]
            , [IncotermsClassification]
            , [IncotermsTransferLocation]
            , [IncotermsLocation1]
            , [IncotermsLocation2]
            , [ShippingCondition]
            , [QuantitySold]
            , [GrossMargin]
            , [ExternalSalesAgentID]
            , [ExternalSalesAgent]
            , [ProjectID]
            , [Project]
            , [SalesEmployeeID]
            , [SalesEmployee]
            , [GlobalParentID]
            , [GlobalParent]
            , [GlobalParentCalculatedID]
            , [GlobalParentCalculated]
            , [LocalParentID]
            , [LocalParent]
            , [LocalParentCalculatedID]
            , [LocalParentCalculated]
            , [SalesOrderTypeID]
            , [BillToID]
            , [BillTo]
            , [FinNetAmountRealProduct]
            , [FinNetAmountFreight]
            , [FinNetAmountMinQty]
            , [FinNetAmountEngServ]
            , [FinNetAmountMisc]
            , [FinNetAmountServOther]
            , [FinNetAmountVerp]
            , [FinRebateAccrual]
            , [PaymentTermCashDiscountPercentageRate]
            , [FinNetAmountOtherSales]
            , [FinReserveCashDiscount]
            , [FinNetAmountAllowances]
            , [FinSales100]
            , [AccountingDate]
--            , [axbi_DataAreaID]
--            , [axbi_DataAreaName]
--            , [axbi_DataAreaGroup]
--            , [axbi_MaterialID]
--            , [axbi_CustomerID]
            , [MaterialCalculated]
            , [SoldToPartyCalculated]
            , [InOutID]
--            , [axbi_ItemNoCalc]
            , [t_applicationId] 
            , [t_extractionDtm] 
            , [t_jobId]         
            , [t_jobDtm]        
            , [t_jobBy]         
            , [t_lastActionBy]  
            , [t_lastActionCd]  
            , [t_lastActionDtm])
        SELECT
              vwBD.[BillingDocument]
            , vwBD.[BillingDocumentItem]
            , vwBD.[CurrencyTypeID]
            , vwBD.[CurrencyType]
            , vwBD.[CurrencyID]
            , vwBD.[ExchangeRate]
            , vwBD.[SalesDocumentItemCategoryID]
            , vwBD.[SalesDocumentItemTypeID]
            , vwBD.[ReturnItemProcessingType]
            , vwBD.[BillingDocumentTypeID]
            , vwBD.[BillingDocumentCategoryID]
            , vwBD.[SDDocumentCategoryID]
            , vwBD.[CreationDate]
            , vwBD.[CreationTime]
            , vwBD.[LastChangeDate]
            , vwBD.[BillingDocumentDate]
            , vwBD.[BillingDocumentIsTemporary]
            , vwBD.[OrganizationDivision]
            , vwBD.[Division]
            , vwBD.[SalesOfficeID]
            , vwBD.[SalesOrganizationID]
            , vwBD.[DistributionChannelID]
            , vwBD.[Material]
            , vwBD.[ProductSurrogateKey]
            , vwBD.[OriginallyRequestedMaterial]
            , vwBD.[InternationalArticleNumber]
            , vwBD.[PricingReferenceMaterial]
            , vwBD.[LengthInMPer1]
            , vwBD.[LengthInM]
            , vwBD.[Batch]
            , vwBD.[MaterialGroupID]
            , vwBD.[BrandID]
            , vwBD.[AdditionalMaterialGroup2]
            , vwBD.[AdditionalMaterialGroup3]
            , vwBD.[AdditionalMaterialGroup4]
            , vwBD.[AdditionalMaterialGroup5]
            , vwBD.[MaterialCommissionGroup]
            , vwBD.[PlantID]
            , vwBD.[StorageLocationID]
            , vwBD.[BillingDocumentIsCancelled]
            , vwBD.[CancelledBillingDocument]
            , vwBD.[CancelledInvoiceEffect]
            , vwBD.[BillingDocumentItemText]
            , vwBD.[ServicesRenderedDate]
            , vwBD.[BillingQuantity]
            , vwBD.[BillingQuantityUnitID]
            , vwBD.[BillingQuantityInBaseUnit]
            , vwBD.[BaseUnit]
            , vwBD.[MRPRequiredQuantityInBaseUnit]
            , vwBD.[BillingToBaseQuantityDnmntr]
            , vwBD.[BillingToBaseQuantityNmrtr]
            , vwBD.[ItemGrossWeight]
            , vwBD.[ItemNetWeight]
            , vwBD.[ItemWeightUnit]
            , vwBD.[ItemVolume]
            , vwBD.[ItemVolumeUnit]
            , vwBD.[BillToPartyCountry]
            , vwBD.[BillToPartyRegion]
            , vwBD.[BillingPlanRule]
            , vwBD.[BillingPlan]
            , vwBD.[BillingPlanItem]
            , vwBD.[CustomerPriceGroupID]
            , vwBD.[PriceListTypeID]
            , vwBD.[TaxDepartureCountry]
            , vwBD.[VATRegistration]
            , vwBD.[VATRegistrationCountry]
            , vwBD.[VATRegistrationOrigin]
            , vwBD.[CustomerTaxClassification1]
            , vwBD.[CustomerTaxClassification2]
            , vwBD.[CustomerTaxClassification3]
            , vwBD.[CustomerTaxClassification4]
            , vwBD.[CustomerTaxClassification5]
            , vwBD.[CustomerTaxClassification6]
            , vwBD.[CustomerTaxClassification7]
            , vwBD.[CustomerTaxClassification8]
            , vwBD.[CustomerTaxClassification9]
            , vwBD.[SDPricingProcedure]
            , vwBD.[NetAmount]
            , vwBD.[TransactionCurrencyID]
            , vwBD.[GrossAmount]
            , vwBD.[PricingDate]
            , vwBD.[PriceDetnExchangeRate]
            , vwBD.[PricingScaleQuantityInBaseUnit]
            , vwBD.[TaxAmount]
            , vwBD.[CostAmount]
            , vwBD.[Subtotal1Amount]
            , vwBD.[Subtotal2Amount]
            , vwBD.[Subtotal3Amount]
            , vwBD.[Subtotal4Amount]
            , vwBD.[Subtotal5Amount]
            , vwBD.[Subtotal6Amount]
            , vwBD.[StatisticalValueControl]
            , vwBD.[StatisticsExchangeRate]
            , vwBD.[StatisticsCurrency]
            , vwBD.[SalesOrganizationCurrency]
            , vwBD.[EligibleAmountForCashDiscount]
            , vwBD.[ContractAccount]
            , vwBD.[CustomerPaymentTerms]
            , vwBD.[PaymentMethod]
            , vwBD.[PaymentReference]
            , vwBD.[FixedValueDate]
            , vwBD.[AdditionalValueDays]
            , vwBD.[PayerParty]
            , vwBD.[CompanyCode]
            , vwBD.[FiscalYear]
            , vwBD.[FiscalPeriod]
            , vwBD.[CustomerAccountAssignmentGroupID]
            , vwBD.[BusinessArea]
            , vwBD.[ProfitCenter]
            , vwBD.[OrderID]
            , vwBD.[ControllingArea]
            , vwBD.[ProfitabilitySegment]
            , vwBD.[CostCenter]
            , vwBD.[OriginSDDocument]
            , vwBD.[OriginSDDocumentItem]
            , vwBD.[PriceDetnExchangeRateDate]
            , vwBD.[ExchangeRateTypeID]
            , vwBD.[FiscalYearVariant]
            , vwBD.[CompanyCodeCurrencyID]
            , vwBD.[AccountingExchangeRate]
            , vwBD.[AccountingExchangeRateIsSet]
            , vwBD.[ReferenceSDDocument]
            , vwBD.[ReferenceSDDocumentItem]
            , vwBD.[ReferenceSDDocumentCategoryID]
            , vwBD.[SalesDocumentID]
            , vwBD.[SalesDocumentItemID]
            , vwBD.[SalesSDDocumentCategoryID]
            , vwBD.[HigherLevelItem]
            , vwBD.[BillingDocumentItemInPartSgmt]
            , vwBD.[SalesGroup]
            , vwBD.[AdditionalCustomerGroup1]
            , vwBD.[AdditionalCustomerGroup2]
            , vwBD.[AdditionalCustomerGroup3]
            , vwBD.[AdditionalCustomerGroup4]
            , vwBD.[AdditionalCustomerGroup5]
            , vwBD.[SDDocumentReasonID]
            , vwBD.[ItemIsRelevantForCredit]
            , vwBD.[CreditRelatedPrice]
            , vwBD.[SalesDistrictID]
            , vwBD.[CustomerGroupID]
            , vwBD.[SoldToParty]
            , vwBD.[CountryID]
            , vwBD.[ShipToParty]
            , vwBD.[BillToParty]
            , vwBD.[ShippingPoint]
            , vwBD.[IncotermsVersion]
            , vwBD.[IncotermsClassification]
            , vwBD.[IncotermsTransferLocation]
            , vwBD.[IncotermsLocation1]
            , vwBD.[IncotermsLocation2]
            , vwBD.[ShippingCondition]
            , vwBD.[QuantitySold]
            , vwBD.[GrossMargin]
            , vwBD.[ExternalSalesAgentID]
            , vwBD.[ExternalSalesAgent]
            , vwBD.[ProjectID]
            , vwBD.[Project]
            , vwBD.[SalesEmployeeID]
            , vwBD.[SalesEmployee]
            , vwBD.[GlobalParentID]
            , vwBD.[GlobalParent]
            , vwBD.[GlobalParentCalculatedID]
            , vwBD.[GlobalParentCalculated]
            , vwBD.[LocalParentID]
            , vwBD.[LocalParent]
            , vwBD.[LocalParentCalculatedID]
            , vwBD.[LocalParentCalculated]
            , vwBD.[SalesOrderTypeID]
            , vwBD.[BillToID]
            , vwBD.[BillTo]
            , vwBD.[FinNetAmountRealProduct]
            , vwBD.[FinNetAmountFreight]
            , vwBD.[FinNetAmountMinQty]
            , vwBD.[FinNetAmountEngServ]
            , vwBD.[FinNetAmountMisc]
            , vwBD.[FinNetAmountServOther]
            , vwBD.[FinNetAmountVerp]
            , vwBD.[FinRebateAccrual]
            , vwBD.[PaymentTermCashDiscountPercentageRate]
            , vwBD.[FinNetAmountOtherSales]
            , vwBD.[FinReserveCashDiscount]
            , vwBD.[FinNetAmountAllowances]
            , vwBD.[FinSales100]
            , vwBD.[AccountingDate]
--            , vwBD.[axbi_DataAreaID]
--            , vwBD.[axbi_DataAreaName]
--            , vwBD.[axbi_DataAreaGroup]
--            , vwBD.[axbi_MaterialID]
--            , vwBD.[axbi_CustomerID]
            , vwBD.[MaterialCalculated]
            , vwBD.[SoldToPartyCalculated]
            , vwBD.[InOutID]
--            , vwBD.[axbi_ItemNoCalc]            
            , vwBD.[t_applicationId] 
            , vwBD.[t_extractionDtm] 
            , @t_jobId
            , @t_jobDtm
            , @t_jobBy
            , vwBD.[t_lastActionBy]  
            , vwBD.[t_lastActionCd]  
            , vwBD.[t_lastActionDtm]                             
            FROM [edw].[vw_BillingDocumentItem_s4h_fin_delta] AS vwBD 
        WHERE NOT EXISTS (SELECT 1 FROM [edw].[fact_BillingDocumentItem_s4h_active]  
                WHERE           
                    [BillingDocument] = vwBD.[BillingDocument]
                AND
                    [BillingDocumentItem] = vwBD.[BillingDocumentItem]
                AND
                    [CurrencyTypeID] = vwBD.[CurrencyTypeID]);        
    END TRY
    BEGIN CATCH
        SET @errmessage = 'Internal error in ' + ERROR_PROCEDURE() + '. ' +  ERROR_MESSAGE();
		THROW 50001, @errmessage, 1;
    END CATCH
END       