CREATE PROC [edw].[sp_load_fact_SalesDocumentItem_s4h_active]
  @t_jobId [varchar](36)
, @t_jobDtm [datetime]
, @t_jobBy [nvarchar](128)
, @t_lastActionCd [varchar](1) -- workaround with option to save single solution in DF
AS
BEGIN
    DECLARE @errmessage NVARCHAR(2048);
    
    BEGIN TRY
        update [edw].[fact_SalesDocumentItem_s4h_active] 
            SET -- exclude [SalesDocument], [SalesDocumentItem], [CurrencyTypeID] is it nk_key
              [CurrencyType]                     = vwSD.[CurrencyType]
            , [CurrencyID]                       = vwSD.[CurrencyID]
            , [ExchangeRate]                     = vwSD.[ExchangeRate]
            , [SDDocumentCategoryID]             = vwSD.[SDDocumentCategoryID]
            , [SalesDocumentTypeID]              = vwSD.[SalesDocumentTypeID]
            , [SalesDocumentItemCategoryID]      = vwSD.[SalesDocumentItemCategoryID]
            , [IsReturnsItemID]                  = vwSD.[IsReturnsItemID]
            , [CreationDate]                     = vwSD.[CreationDate]
            , [CreationTime]                     = vwSD.[CreationTime]
            , [LastChangeDate]                   = vwSD.[LastChangeDate]
            , [SalesOrganizationID]              = vwSD.[SalesOrganizationID]
            , [DistributionChannelID]            = vwSD.[DistributionChannelID]
            , [DivisionID]                       = vwSD.[DivisionID]
            , [SalesGroupID]                     = vwSD.[SalesGroupID]
            , [SalesOfficeID]                    = vwSD.[SalesOfficeID]
            , [InternationalArticleNumberID]     = vwSD.[InternationalArticleNumberID]
            , [BatchID]                          = vwSD.[BatchID]
            , [MaterialID]                       = vwSD.[MaterialID]
            , [ProductSurrogateKey]              = vwSD.[ProductSurrogateKey]
            , [OriginallyRequestedMaterialID]    = vwSD.[OriginallyRequestedMaterialID]
            , [MaterialSubstitutionReasonID]     = vwSD.[MaterialSubstitutionReasonID]
            , [MaterialGroupID]                  = vwSD.[MaterialGroupID]
            , [BrandID]                          = vwSD.[BrandID]
            , [AdditionalMaterialGroup2ID]       = vwSD.[AdditionalMaterialGroup2ID]
            , [AdditionalMaterialGroup3ID]       = vwSD.[AdditionalMaterialGroup3ID]
            , [AdditionalMaterialGroup4ID]       = vwSD.[AdditionalMaterialGroup4ID]
            , [AdditionalMaterialGroup5ID]       = vwSD.[AdditionalMaterialGroup5ID]
            , [SoldToPartyID]                    = vwSD.[SoldToPartyID]
            , [AdditionalCustomerGroup1ID]       = vwSD.[AdditionalCustomerGroup1ID]
            , [AdditionalCustomerGroup2ID]       = vwSD.[AdditionalCustomerGroup2ID]
            , [AdditionalCustomerGroup3ID]       = vwSD.[AdditionalCustomerGroup3ID]
            , [AdditionalCustomerGroup4ID]       = vwSD.[AdditionalCustomerGroup4ID]
            , [AdditionalCustomerGroup5ID]       = vwSD.[AdditionalCustomerGroup5ID]
            , [ShipToPartyID]                    = vwSD.[ShipToPartyID]
            , [PayerPartyID]                     = vwSD.[PayerPartyID]
            , [BillToPartyID]                    = vwSD.[BillToPartyID]
            , [SDDocumentReasonID]               = vwSD.[SDDocumentReasonID]
            , [SalesDocumentDate]                = vwSD.[SalesDocumentDate]
            , [OrderQuantity]                    = vwSD.[OrderQuantity]
            , [OrderQuantityUnitID]              = vwSD.[OrderQuantityUnitID]
            , [TargetQuantity]                   = vwSD.[TargetQuantity]
            , [TargetQuantityUnitID]             = vwSD.[TargetQuantityUnitID]
            , [TargetToBaseQuantityDnmntr]       = vwSD.[TargetToBaseQuantityDnmntr]
            , [TargetToBaseQuantityNmrtr]        = vwSD.[TargetToBaseQuantityNmrtr]
            , [OrderToBaseQuantityDnmntr]        = vwSD.[OrderToBaseQuantityDnmntr]
            , [OrderToBaseQuantityNmrtr]         = vwSD.[OrderToBaseQuantityNmrtr]
            , [ConfdDelivQtyInOrderQtyUnit]      = vwSD.[ConfdDelivQtyInOrderQtyUnit]
            , [TargetDelivQtyInOrderQtyUnit]     = vwSD.[TargetDelivQtyInOrderQtyUnit]
            , [ConfdDeliveryQtyInBaseUnit]       = vwSD.[ConfdDeliveryQtyInBaseUnit]
            , [BaseUnitID]                       = vwSD.[BaseUnitID]
            , [ItemGrossWeight]                  = vwSD.[ItemGrossWeight]
            , [ItemNetWeight]                    = vwSD.[ItemNetWeight]
            , [ItemWeightUnitID]                 = vwSD.[ItemWeightUnitID]
            , [ItemVolume]                       = vwSD.[ItemVolume]
            , [ItemVolumeUnitID]                 = vwSD.[ItemVolumeUnitID]
            , [ServicesRenderedDate]             = vwSD.[ServicesRenderedDate]
            , [SalesDistrictID]                  = vwSD.[SalesDistrictID]
            , [CustomerGroupID]                  = vwSD.[CustomerGroupID]
            , [HdrOrderProbabilityInPercentID]   = vwSD.[HdrOrderProbabilityInPercentID]
            , [ItemOrderProbabilityInPercentID]  = vwSD.[ItemOrderProbabilityInPercentID]
            , [SalesDocumentRjcnReasonID]        = vwSD.[SalesDocumentRjcnReasonID]
            , [PricingDate]                      = vwSD.[PricingDate]
            , [ExchangeRateDate]                 = vwSD.[ExchangeRateDate]
            , [PriceDetnExchangeRate]            = vwSD.[PriceDetnExchangeRate]
            , [StatisticalValueControlID]        = vwSD.[StatisticalValueControlID]
            , [NetAmount]                        = vwSD.[NetAmount]
            , [TransactionCurrencyID]            = vwSD.[TransactionCurrencyID]
            , [SalesOrganizationCurrencyID]      = vwSD.[SalesOrganizationCurrencyID]
            , [NetPriceAmount]                   = vwSD.[NetPriceAmount]
            , [NetPriceQuantity]                 = vwSD.[NetPriceQuantity]
            , [NetPriceQuantityUnitID]           = vwSD.[NetPriceQuantityUnitID]
            , [TaxAmount]                        = vwSD.[TaxAmount]
            , [CostAmount]                       = vwSD.[CostAmount]
            , [Margin]                           = vwSD.[Margin]
            , [Subtotal1Amount]                  = vwSD.[Subtotal1Amount]
            , [Subtotal2Amount]                  = vwSD.[Subtotal2Amount]
            , [Subtotal3Amount]                  = vwSD.[Subtotal3Amount]
            , [Subtotal4Amount]                  = vwSD.[Subtotal4Amount]
            , [Subtotal5Amount]                  = vwSD.[Subtotal5Amount]
            , [Subtotal6Amount]                  = vwSD.[Subtotal6Amount]
            , [ShippingPointID]                  = vwSD.[ShippingPointID]
            , [ShippingTypeID]                   = vwSD.[ShippingTypeID]
            , [DeliveryPriorityID]               = vwSD.[DeliveryPriorityID]
            , [InventorySpecialStockTypeID]      = vwSD.[InventorySpecialStockTypeID]
            , [RequestedDeliveryDate]            = vwSD.[RequestedDeliveryDate]
            , [ShippingConditionID]              = vwSD.[ShippingConditionID]
            , [DeliveryBlockReasonID]            = vwSD.[DeliveryBlockReasonID]
            , [PlantID]                          = vwSD.[PlantID]
            , [StorageLocationID]                = vwSD.[StorageLocationID]
            , [RouteID]                          = vwSD.[RouteID]
            , [IncotermsClassificationID]        = vwSD.[IncotermsClassificationID]
            , [IncotermsVersionID]               = vwSD.[IncotermsVersionID]
            , [IncotermsTransferLocationID]      = vwSD.[IncotermsTransferLocationID]
            , [IncotermsLocation1ID]             = vwSD.[IncotermsLocation1ID]
            , [IncotermsLocation2ID]             = vwSD.[IncotermsLocation2ID]
            , [MinDeliveryQtyInBaseUnit]         = vwSD.[MinDeliveryQtyInBaseUnit]
            , [UnlimitedOverdeliveryIsAllowedID] = vwSD.[UnlimitedOverdeliveryIsAllowedID]
            , [OverdelivTolrtdLmtRatioInPct]     = vwSD.[OverdelivTolrtdLmtRatioInPct]
            , [UnderdelivTolrtdLmtRatioInPct]    = vwSD.[UnderdelivTolrtdLmtRatioInPct]
            , [PartialDeliveryIsAllowedID]       = vwSD.[PartialDeliveryIsAllowedID]
            , [BindingPeriodValidityStartDate]   = vwSD.[BindingPeriodValidityStartDate]
            , [BindingPeriodValidityEndDate]     = vwSD.[BindingPeriodValidityEndDate]
            , [OutlineAgreementTargetAmount]     = vwSD.[OutlineAgreementTargetAmount]
            , [BillingDocumentDate]              = vwSD.[BillingDocumentDate]
            , [BillingCompanyCodeID]             = vwSD.[BillingCompanyCodeID]
            , [HeaderBillingBlockReasonID]       = vwSD.[HeaderBillingBlockReasonID]
            , [ItemBillingBlockReasonID]         = vwSD.[ItemBillingBlockReasonID]
            , [FiscalYearID]                     = vwSD.[FiscalYearID]
            , [FiscalPeriodID]                   = vwSD.[FiscalPeriodID]
            , [CustomerAccountAssignmentGroupID] = vwSD.[CustomerAccountAssignmentGroupID]
            , [ExchangeRateTypeID]               = vwSD.[ExchangeRateTypeID]
            , [CompanyCodeCurrencyID]            = vwSD.[CompanyCodeCurrencyID]
            , [FiscalYearVariantID]              = vwSD.[FiscalYearVariantID]
            , [BusinessAreaID]                   = vwSD.[BusinessAreaID]
            , [ProfitCenterID]                   = vwSD.[ProfitCenterID]
            , [OrderID]                          = vwSD.[OrderID]
            , [ProfitabilitySegmentID]           = vwSD.[ProfitabilitySegmentID]
            , [ControllingAreaID]                = vwSD.[ControllingAreaID]
            , [ReferenceSDDocumentID]            = vwSD.[ReferenceSDDocumentID]
            , [ReferenceSDDocumentItemID]        = vwSD.[ReferenceSDDocumentItemID]
            , [ReferenceSDDocumentCategoryID]    = vwSD.[ReferenceSDDocumentCategoryID]
            , [OriginSDDocumentID]               = vwSD.[OriginSDDocumentID]
            , [OriginSDDocumentItemID]           = vwSD.[OriginSDDocumentItemID]
            , [OverallSDProcessStatusID]         = vwSD.[OverallSDProcessStatusID]
            , [OverallTotalDeliveryStatusID]     = vwSD.[OverallTotalDeliveryStatusID]
            , [OverallOrdReltdBillgStatusID]     = vwSD.[OverallOrdReltdBillgStatusID]
            , [TotalCreditCheckStatusID]         = vwSD.[TotalCreditCheckStatusID]
            , [DeliveryBlockStatusID]            = vwSD.[DeliveryBlockStatusID]
            , [BillingBlockStatusID]             = vwSD.[BillingBlockStatusID]
            , [TotalSDDocReferenceStatusID]      = vwSD.[TotalSDDocReferenceStatusID]
            , [SDDocReferenceStatusID]           = vwSD.[SDDocReferenceStatusID]
            , [OverallSDDocumentRejectionStsID]  = vwSD.[OverallSDDocumentRejectionStsID]
            , [SDDocumentRejectionStatusID]      = vwSD.[SDDocumentRejectionStatusID]
            , [OverallTotalSDDocRefStatusID]     = vwSD.[OverallTotalSDDocRefStatusID]
            , [OverallSDDocReferenceStatusID]    = vwSD.[OverallSDDocReferenceStatusID]
            , [ItemGeneralIncompletionStatusID]  = vwSD.[ItemGeneralIncompletionStatusID]
            , [ItemBillingIncompletionStatusID]  = vwSD.[ItemBillingIncompletionStatusID]
            , [PricingIncompletionStatusID]      = vwSD.[PricingIncompletionStatusID]
            , [ItemDeliveryIncompletionStatusID] = vwSD.[ItemDeliveryIncompletionStatusID]
            , [ExternalSalesAgentID]             = vwSD.[ExternalSalesAgentID]
            , [ExternalSalesAgent]               = vwSD.[ExternalSalesAgent]
            , [GlobalParentID]                   = vwSD.[GlobalParentID]
            , [GlobalParent]                     = vwSD.[GlobalParent]
            , [LocalParentID]                    = vwSD.[LocalParentID]
            , [LocalParent]                      = vwSD.[LocalParent]
            , [ProjectID]                        = vwSD.[ProjectID]
            , [Project]                          = vwSD.[Project]
            , [SalesEmployeeID]                  = vwSD.[SalesEmployeeID]
            , [SalesEmployee]                    = vwSD.[SalesEmployee]
            , [GlobalParentCalculatedID]         = vwSD.[GlobalParentCalculatedID]
            , [GlobalParentCalculated]           = vwSD.[GlobalParentCalculated]
            , [LocalParentCalculatedID]          = vwSD.[LocalParentCalculatedID]
            , [LocalParentCalculated]            = vwSD.[LocalParentCalculated]
            , [SDoc_ControllingObjectID]         = vwSD.[SDoc_ControllingObjectID]
            , [SDItem_ControllingObjectID]       = vwSD.[SDItem_ControllingObjectID]
            , [CorrespncExternalReference]       = vwSD.[CorrespncExternalReference] 
            , [InOutID]                          = vwSD.[InOutID]
            , [t_applicationId]                  = vwSD.[t_applicationId]
            , [t_extractionDtm]                  = vwSD.[t_extractionDtm]
            , [t_jobId]                          =  @t_jobId 
            , [t_jobDtm]                         =  @t_jobDtm 
            , [t_jobBy]                          =  @t_jobBy 
            , [t_lastActionBy]                   = vwSD.[t_lastActionBy]
            , [t_lastActionCd]                   = vwSD.[t_lastActionCd]
            , [t_lastActionDtm]                  = vwSD.[t_lastActionDtm]                               
        FROM [edw].[fact_SalesDocumentItem_s4h_active]  AS tSD
        JOIN [edw].[vw_SalesDocumentItem_s4h_delta] AS vwSD  ON tSD.[nk_fact_SalesDocumentItem] = vwSD.[nk_fact_SalesDocumentItem];

        INSERT [edw].[fact_SalesDocumentItem_s4h_active] (
              [nk_fact_SalesDocumentItem]
            , [SalesDocument]
            , [SalesDocumentItem]
            , [CurrencyTypeID]
            , [CurrencyType]
            , [CurrencyID]
            , [ExchangeRate]
            , [SDDocumentCategoryID]
            , [SalesDocumentTypeID]
            , [SalesDocumentItemCategoryID]
            , [IsReturnsItemID]
            , [CreationDate]
            , [CreationTime]
            , [LastChangeDate]
            , [SalesOrganizationID]
            , [DistributionChannelID]
            , [DivisionID]
            , [SalesGroupID]
            , [SalesOfficeID]
            , [InternationalArticleNumberID]
            , [BatchID]
            , [MaterialID]
            , [ProductSurrogateKey]
            , [OriginallyRequestedMaterialID]
            , [MaterialSubstitutionReasonID]
            , [MaterialGroupID]
            , [BrandID]
            , [AdditionalMaterialGroup2ID]
            , [AdditionalMaterialGroup3ID]
            , [AdditionalMaterialGroup4ID]
            , [AdditionalMaterialGroup5ID]
            , [SoldToPartyID]
            , [AdditionalCustomerGroup1ID]
            , [AdditionalCustomerGroup2ID]
            , [AdditionalCustomerGroup3ID]
            , [AdditionalCustomerGroup4ID]
            , [AdditionalCustomerGroup5ID]
            , [ShipToPartyID]
            , [PayerPartyID]
            , [BillToPartyID]
            , [SDDocumentReasonID]
            , [SalesDocumentDate]
            , [OrderQuantity]
            , [OrderQuantityUnitID]
            , [TargetQuantity]
            , [TargetQuantityUnitID]
            , [TargetToBaseQuantityDnmntr]
            , [TargetToBaseQuantityNmrtr]
            , [OrderToBaseQuantityDnmntr]
            , [OrderToBaseQuantityNmrtr]
            , [ConfdDelivQtyInOrderQtyUnit]
            , [TargetDelivQtyInOrderQtyUnit]
            , [ConfdDeliveryQtyInBaseUnit]
            , [BaseUnitID]
            , [ItemGrossWeight]
            , [ItemNetWeight]
            , [ItemWeightUnitID]
            , [ItemVolume]
            , [ItemVolumeUnitID]
            , [ServicesRenderedDate]
            , [SalesDistrictID]
            , [CustomerGroupID]
            , [HdrOrderProbabilityInPercentID]
            , [ItemOrderProbabilityInPercentID]
            , [SalesDocumentRjcnReasonID]
            , [PricingDate]
            , [ExchangeRateDate]
            , [PriceDetnExchangeRate]
            , [StatisticalValueControlID]
            , [NetAmount]
            , [TransactionCurrencyID]
            , [SalesOrganizationCurrencyID]
            , [NetPriceAmount]
            , [NetPriceQuantity]
            , [NetPriceQuantityUnitID]
            , [TaxAmount]
            , [CostAmount]
            , [Margin]
            , [Subtotal1Amount]
            , [Subtotal2Amount]
            , [Subtotal3Amount]
            , [Subtotal4Amount]
            , [Subtotal5Amount]
            , [Subtotal6Amount]
            , [ShippingPointID]
            , [ShippingTypeID]
            , [DeliveryPriorityID]
            , [InventorySpecialStockTypeID]
            , [RequestedDeliveryDate]
            , [ShippingConditionID]
            , [DeliveryBlockReasonID]
            , [PlantID]
            , [StorageLocationID]
            , [RouteID]
            , [IncotermsClassificationID]
            , [IncotermsVersionID]
            , [IncotermsTransferLocationID]
            , [IncotermsLocation1ID]
            , [IncotermsLocation2ID]
            , [MinDeliveryQtyInBaseUnit]
            , [UnlimitedOverdeliveryIsAllowedID]
            , [OverdelivTolrtdLmtRatioInPct]
            , [UnderdelivTolrtdLmtRatioInPct]
            , [PartialDeliveryIsAllowedID]
            , [BindingPeriodValidityStartDate]
            , [BindingPeriodValidityEndDate]
            , [OutlineAgreementTargetAmount]
            , [BillingDocumentDate]
            , [BillingCompanyCodeID]
            , [HeaderBillingBlockReasonID]
            , [ItemBillingBlockReasonID]
            , [FiscalYearID]
            , [FiscalPeriodID]
            , [CustomerAccountAssignmentGroupID]
            , [ExchangeRateTypeID]
            , [CompanyCodeCurrencyID]
            , [FiscalYearVariantID]
            , [BusinessAreaID]
            , [ProfitCenterID]
            , [OrderID]
            , [ProfitabilitySegmentID]
            , [ControllingAreaID]
            , [ReferenceSDDocumentID]
            , [ReferenceSDDocumentItemID]
            , [ReferenceSDDocumentCategoryID]
            , [OriginSDDocumentID]
            , [OriginSDDocumentItemID]
            , [OverallSDProcessStatusID]
            , [OverallTotalDeliveryStatusID]
            , [OverallOrdReltdBillgStatusID]
            , [TotalCreditCheckStatusID]
            , [DeliveryBlockStatusID]
            , [BillingBlockStatusID]
            , [TotalSDDocReferenceStatusID]
            , [SDDocReferenceStatusID]
            , [OverallSDDocumentRejectionStsID]
            , [SDDocumentRejectionStatusID]
            , [OverallTotalSDDocRefStatusID]
            , [OverallSDDocReferenceStatusID]
            , [ItemGeneralIncompletionStatusID]
            , [ItemBillingIncompletionStatusID]
            , [PricingIncompletionStatusID]
            , [ItemDeliveryIncompletionStatusID]
            , [ExternalSalesAgentID]
            , [ExternalSalesAgent]
            , [GlobalParentID]
            , [GlobalParent]
            , [LocalParentID]
            , [LocalParent]
            , [ProjectID]
            , [Project]
            , [SalesEmployeeID]
            , [SalesEmployee]
            , [GlobalParentCalculatedID]
            , [GlobalParentCalculated]
            , [LocalParentCalculatedID]
            , [LocalParentCalculated]
            , [SDoc_ControllingObjectID]
            , [SDItem_ControllingObjectID]
            , [CorrespncExternalReference] 
            , [InOutID]
            , [t_applicationId] 
            , [t_extractionDtm] 
            , [t_jobId]         
            , [t_jobDtm]        
            , [t_jobBy]         
            , [t_lastActionBy]  
            , [t_lastActionCd]  
            , [t_lastActionDtm])
        SELECT
              vwSD.[nk_fact_SalesDocumentItem]
            , vwSD.[SalesDocument]
            , vwSD.[SalesDocumentItem]
            , vwSD.[CurrencyTypeID]
            , vwSD.[CurrencyType]
            , vwSD.[CurrencyID]
            , vwSD.[ExchangeRate]
            , vwSD.[SDDocumentCategoryID]
            , vwSD.[SalesDocumentTypeID]
            , vwSD.[SalesDocumentItemCategoryID]
            , vwSD.[IsReturnsItemID]
            , vwSD.[CreationDate]
            , vwSD.[CreationTime]
            , vwSD.[LastChangeDate]
            , vwSD.[SalesOrganizationID]
            , vwSD.[DistributionChannelID]
            , vwSD.[DivisionID]
            , vwSD.[SalesGroupID]
            , vwSD.[SalesOfficeID]
            , vwSD.[InternationalArticleNumberID]
            , vwSD.[BatchID]
            , vwSD.[MaterialID]
            , vwSD.[ProductSurrogateKey]
            , vwSD.[OriginallyRequestedMaterialID]
            , vwSD.[MaterialSubstitutionReasonID]
            , vwSD.[MaterialGroupID]
            , vwSD.[BrandID]            
            , vwSD.[AdditionalMaterialGroup2ID]
            , vwSD.[AdditionalMaterialGroup3ID]
            , vwSD.[AdditionalMaterialGroup4ID]
            , vwSD.[AdditionalMaterialGroup5ID]
            , vwSD.[SoldToPartyID]
            , vwSD.[AdditionalCustomerGroup1ID]
            , vwSD.[AdditionalCustomerGroup2ID]
            , vwSD.[AdditionalCustomerGroup3ID]
            , vwSD.[AdditionalCustomerGroup4ID]
            , vwSD.[AdditionalCustomerGroup5ID]
            , vwSD.[ShipToPartyID]
            , vwSD.[PayerPartyID]
            , vwSD.[BillToPartyID]
            , vwSD.[SDDocumentReasonID]
            , vwSD.[SalesDocumentDate]
            , vwSD.[OrderQuantity]
            , vwSD.[OrderQuantityUnitID]
            , vwSD.[TargetQuantity]
            , vwSD.[TargetQuantityUnitID]
            , vwSD.[TargetToBaseQuantityDnmntr]
            , vwSD.[TargetToBaseQuantityNmrtr]
            , vwSD.[OrderToBaseQuantityDnmntr]
            , vwSD.[OrderToBaseQuantityNmrtr]
            , vwSD.[ConfdDelivQtyInOrderQtyUnit]
            , vwSD.[TargetDelivQtyInOrderQtyUnit]
            , vwSD.[ConfdDeliveryQtyInBaseUnit]
            , vwSD.[BaseUnitID]
            , vwSD.[ItemGrossWeight]
            , vwSD.[ItemNetWeight]
            , vwSD.[ItemWeightUnitID]
            , vwSD.[ItemVolume]
            , vwSD.[ItemVolumeUnitID]
            , vwSD.[ServicesRenderedDate]
            , vwSD.[SalesDistrictID]
            , vwSD.[CustomerGroupID]
            , vwSD.[HdrOrderProbabilityInPercentID]
            , vwSD.[ItemOrderProbabilityInPercentID]
            , vwSD.[SalesDocumentRjcnReasonID]
            , vwSD.[PricingDate]
            , vwSD.[ExchangeRateDate]
            , vwSD.[PriceDetnExchangeRate]
            , vwSD.[StatisticalValueControlID]
            , vwSD.[NetAmount]
            , vwSD.[TransactionCurrencyID]
            , vwSD.[SalesOrganizationCurrencyID]
            , vwSD.[NetPriceAmount]
            , vwSD.[NetPriceQuantity]
            , vwSD.[NetPriceQuantityUnitID]
            , vwSD.[TaxAmount]
            , vwSD.[CostAmount]
            , vwSD.[Margin]
            , vwSD.[Subtotal1Amount]
            , vwSD.[Subtotal2Amount]
            , vwSD.[Subtotal3Amount]
            , vwSD.[Subtotal4Amount]
            , vwSD.[Subtotal5Amount]
            , vwSD.[Subtotal6Amount]
            , vwSD.[ShippingPointID]
            , vwSD.[ShippingTypeID]
            , vwSD.[DeliveryPriorityID]
            , vwSD.[InventorySpecialStockTypeID]
            , vwSD.[RequestedDeliveryDate]
            , vwSD.[ShippingConditionID]
            , vwSD.[DeliveryBlockReasonID]
            , vwSD.[PlantID]
            , vwSD.[StorageLocationID]
            , vwSD.[RouteID]
            , vwSD.[IncotermsClassificationID]
            , vwSD.[IncotermsVersionID]
            , vwSD.[IncotermsTransferLocationID]
            , vwSD.[IncotermsLocation1ID]
            , vwSD.[IncotermsLocation2ID]
            , vwSD.[MinDeliveryQtyInBaseUnit]
            , vwSD.[UnlimitedOverdeliveryIsAllowedID]
            , vwSD.[OverdelivTolrtdLmtRatioInPct]
            , vwSD.[UnderdelivTolrtdLmtRatioInPct]
            , vwSD.[PartialDeliveryIsAllowedID]
            , vwSD.[BindingPeriodValidityStartDate]
            , vwSD.[BindingPeriodValidityEndDate]
            , vwSD.[OutlineAgreementTargetAmount]
            , vwSD.[BillingDocumentDate]
            , vwSD.[BillingCompanyCodeID]
            , vwSD.[HeaderBillingBlockReasonID]
            , vwSD.[ItemBillingBlockReasonID]
            , vwSD.[FiscalYearID]
            , vwSD.[FiscalPeriodID]
            , vwSD.[CustomerAccountAssignmentGroupID]
            , vwSD.[ExchangeRateTypeID]
            , vwSD.[CompanyCodeCurrencyID]
            , vwSD.[FiscalYearVariantID]
            , vwSD.[BusinessAreaID]
            , vwSD.[ProfitCenterID]
            , vwSD.[OrderID]
            , vwSD.[ProfitabilitySegmentID]
            , vwSD.[ControllingAreaID]
            , vwSD.[ReferenceSDDocumentID]
            , vwSD.[ReferenceSDDocumentItemID]
            , vwSD.[ReferenceSDDocumentCategoryID]
            , vwSD.[OriginSDDocumentID]
            , vwSD.[OriginSDDocumentItemID]
            , vwSD.[OverallSDProcessStatusID]
            , vwSD.[OverallTotalDeliveryStatusID]
            , vwSD.[OverallOrdReltdBillgStatusID]
            , vwSD.[TotalCreditCheckStatusID]
            , vwSD.[DeliveryBlockStatusID]
            , vwSD.[BillingBlockStatusID]
            , vwSD.[TotalSDDocReferenceStatusID]
            , vwSD.[SDDocReferenceStatusID]
            , vwSD.[OverallSDDocumentRejectionStsID]
            , vwSD.[SDDocumentRejectionStatusID]
            , vwSD.[OverallTotalSDDocRefStatusID]
            , vwSD.[OverallSDDocReferenceStatusID]
            , vwSD.[ItemGeneralIncompletionStatusID]
            , vwSD.[ItemBillingIncompletionStatusID]
            , vwSD.[PricingIncompletionStatusID]
            , vwSD.[ItemDeliveryIncompletionStatusID]
            , vwSD.[ExternalSalesAgentID]
            , vwSD.[ExternalSalesAgent]
            , vwSD.[GlobalParentID]
            , vwSD.[GlobalParent]
            , vwSD.[LocalParentID]
            , vwSD.[LocalParent]
            , vwSD.[ProjectID]
            , vwSD.[Project]
            , vwSD.[SalesEmployeeID]
            , vwSD.[SalesEmployee]
            , vwSD.[GlobalParentCalculatedID]
            , vwSD.[GlobalParentCalculated]
            , vwSD.[LocalParentCalculatedID]
            , vwSD.[LocalParentCalculated]
            , vwSD.[SDoc_ControllingObjectID]
            , vwSD.[SDItem_ControllingObjectID]
            , vwSD.[CorrespncExternalReference] 
            , vwSD.[InOutID]
            , vwSD.[t_applicationId] 
            , vwSD.[t_extractionDtm] 
            , @t_jobId
            , @t_jobDtm
            , @t_jobBy
            , vwSD.[t_lastActionBy]  
            , vwSD.[t_lastActionCd]  
            , vwSD.[t_lastActionDtm]                             
            FROM [edw].[vw_SalesDocumentItem_s4h_delta] AS vwSD 
        WHERE NOT EXISTS (SELECT 1 FROM [edw].[fact_SalesDocumentItem_s4h_active]  WHERE [nk_fact_SalesDocumentItem] = vwSD.[nk_fact_SalesDocumentItem]);                        
    END TRY
    BEGIN CATCH
        SET @errmessage = 'Internal error in ' + ERROR_PROCEDURE() + '. ' +  ERROR_MESSAGE();
		THROW 50001, @errmessage, 1;
    END CATCH
END       