CREATE PROC [edw].[sp_load_fact_OutboundDeliveryItem]
  @t_jobId [varchar](36)
, @t_jobDtm [datetime]
, @t_lastActionCd [varchar](1)
, @t_jobBy [nvarchar](128)
AS
BEGIN

    DECLARE @isS4HViewNotEmpty   BIT = 0;
    DECLARE @isAXBIViewNotEmpty  BIT = 0;
    DECLARE @errmessage NVARCHAR(2048);

    BEGIN TRY
	    IF OBJECT_ID('[edw].[fact_OutboundDeliveryItem_tmp]') IS NOT NULL
		    DROP TABLE [edw].[fact_OutboundDeliveryItem_tmp];

        CREATE TABLE [edw].[fact_OutboundDeliveryItem_tmp]
        WITH
        (
            DISTRIBUTION = HASH ([nk_fact_OutboundDeliveryItem]),
            CLUSTERED COLUMNSTORE INDEX
        )
        AS SELECT * FROM  [edw].[fact_OutboundDeliveryItem] WHERE 1=0;

	    SELECT TOP 1 @isS4HViewNotEmpty = 1 FROM [edw].[vw_OutboundDeliveryItem_s4h];

        IF (@isS4HViewNotEmpty = 0)
            BEGIN
                SET @errmessage = 'Temporary view [edw].[vw_OutboundDeliveryItem_s4h] was not filled with data from S4H.';
                THROW 50001, @errmessage, 1;
            END;

        INSERT INTO [edw].[fact_OutboundDeliveryItem_tmp](
             [nk_fact_OutboundDeliveryItem]
            ,[OutboundDelivery]
            ,[OutboundDeliveryItem]
            ,[DeliveryDocumentItemCategoryID]
            ,[SalesDocumentItemTypeID]
            ,[CreatedByUserID]
            ,[CreationDate]
            ,[CreationTime]
            ,[LastChangeDate]
            ,[DistributionChannelID]
            ,[ProductID]
            ,[OriginallyRequestedMaterialID]
            ,[ProductGroupID]
            ,[PlantID]
            ,[WarehouseID]
            ,[StorageLocationID]
            ,[HigherLevelItem]
            ,[ActualDeliveryQuantity]
            ,[ActDelQtyTotalForSDI]
            ,[DeliveryQuantityUnit]
            ,[ActualDeliveredQtyInBaseUnit]
            ,[BaseUnit]
            ,[Batch]
            ,[BatchClassification]
            ,[BusinessArea]
            ,[ChmlCmplncStatusID]
            ,[ControllingArea]
            ,[CostCenter]
            ,[CostInDocumentCurrency]
            ,[CreditRelatedPrice]
            ,[DangerousGoodsStatusID]
            ,[DeliveryGroup]
            ,[Division]
            ,[FixedShipgProcgDurationInDays]
            ,[FunctionalArea]
            ,[GoodsMovementType]
            ,[InventorySpecialStockType]
            ,[IsNotGoodsMovementsRelevant]
            ,[ItemGrossWeight]
            ,[ItemNetWeight]
            ,[WGT001_DataQualityCode]
            ,[ItemVolume]
            ,[ItemVolumeUnit]
            ,[ItemWeightUnit]
            ,[LoadingGroup]
            ,[NetPriceAmount_LC]
            ,[OrderDocument]
            ,[OrderID]
            ,[OrderItem]
            ,[OriginalDeliveryQuantity]
            ,[OriginSDDocument]
            ,[OverdelivTolrtdLmtRatioInPct]
            ,[PartialDeliveryIsAllowed]
            ,[PlanningPlant]
            ,[ProductAvailabilityDate]
            ,[ProfitCenterID]
            ,[SalesGroup]
            ,[SalesOffice]
            ,[SDDocumentItem]
            ,[SubsequentMovementType]
            ,[HDR_TotalNetAmount_LC]
            ,[VarblShipgProcgDurationInDays]
            ,[UnlimitedOverdeliveryIsAllowed]
            ,[GLAccountID]
            ,[IsCompletelyDelivered]
            ,[ReceivingPoint]
            ,[ItemIsBillingRelevant]
            ,[ReferenceSDDocument]
            ,[ReferenceSDDocumentItem]
            ,[ReferenceSDDocumentCategoryID]
            ,[SDProcessStatusID]
            ,[PickingConfirmationStatusID]
            ,[PickingStatusID]
            ,[WarehouseActivityStatusID]
            ,[PackingStatusID]
            ,[GoodsMovementStatusID]
            ,[DeliveryRelatedBillingStatusID]
            ,[ProofOfDeliveryStatusID]
            ,[ItemGeneralIncompletionStatusID]
            ,[ItemDeliveryIncompletionStatusID]
            ,[ItemPickingIncompletionStatusID]
            ,[ItemGdsMvtIncompletionStsID]
            ,[ItemPackingIncompletionStatusID]
            ,[ItemBillingIncompletionStatusID]
            ,[IntercompanyBillingStatusID]
            ,[IsReturnsItem]
            ,[SL_ConfirmedDeliveryDate]
            ,[SL_OriginalConfirmedDeliveryDate]
            ,[SL_FirstCustomerRequestedDeliveryDate]
            ,[SL_ConfdOrderQtyByMatlAvailCheck]
            ,[SL_GoodsIssueDate]
            ,[SL_ScheduleLine]
            ,[HDR_SalesDistrictID]
            ,[HDR_SalesOrganizationID]
            ,[HDR_SoldToPartyID]
            ,[HDR_ShipToPartyID]
            ,[HDR_DeliveryDocumentTypeID]
            ,[HDR_CompleteDeliveryIsDefined]
            ,[HDR_SupplierID]
            ,[HDR_ReceivingPlantID]
            ,[HDR_DeletionIndicator]
            ,[HDR_DeliveryDate]
            ,[HDR_CarrierID]
            ,[HDR_Carrier]
            ,[SDI_CreationDate]
            ,[SDI_RequestedDeliveryDate]
            ,[SDI_PricePerPiece_LC]
            ,[SDI_PricePerPiece_EUR]
            ,[SDI_LocalCurrency]
            ,[SDI_SalesDocumentTypeID]
            ,[SDI_IsReturnsItemID]
            ,[SDI_BillToParty]
            ,[SDI_ConfdDeliveryQtyInBaseUnit]
            ,[SDI_ConfdDelivQtyInOrderQtyUnit]
            ,[SDI_CostAmount_LC]
            ,[SDI_CostAmount_EUR]
            ,[SDI_DeliveryBlockStatusID]
            ,[SDI_ExchangeRateDate]
            ,[SDI_ExchangeRateType]
            ,[SDI_NetAmount_LC]
            ,[SDI_NetAmount_EUR]
            ,[SDI_NetPriceQuantityUnit]
            ,[SDI_OrderID]
            ,[SDI_OrderQuantity]
            ,[SDI_OrderQuantityUnit]
            ,[SDI_OverallTotalDeliveryStatusID]
            ,[SDI_PayerParty]
            ,[SDI_Route]
            ,[SDI_SalesDocumentItemCategory]
            ,[SDI_SalesOrganizationCurrency]
            ,[SDI_SDDocumentCategory]
            ,[SDI_SDDocumentRejectionStatusID]
            ,[SDI_StorageLocationID]
            ,[OTS_IsOnTime] 
            ,[OTS_EarlyDays] 
            ,[OTS_LateDays] 
            ,[OTS_IsEarly] 
            ,[OTS_IsLate] 
            ,[RouteIsChangedFlag]
            ,[NrODIPerSDIAndQtyNot0]
            ,[NrSLInScope]
            ,[OTSIF_OnTimeShipInFull]
            ,[HDR_PlannedGoodsIssueDate] 
            ,[HDR_ActualGoodsMovementDate] 
            ,[HDR_ShippingPointID] 
            ,[HDR_OrderCombinationIsAllowed] 
            ,[HDR_DeliveryPriority] 
            ,[HDR_DeliveryBlockReason] 
            ,[HDR_DeliveryDocumentBySupplier] 
            ,[HDR_DeliveryIsInPlant] 
            ,[HDR_OrderID] 
            ,[HDR_PickingDate] 
            ,[HDR_LoadingDate] 
            ,[HDR_ShippingType] 
            ,[HDR_ShippingCondition] 
            ,[HDR_ShipmentBlockReason] 
            ,[HDR_TransportationPlanningDate] 
            ,[HDR_ProposedDeliveryRoute] 
            ,[HDR_ActualDeliveryRoute] 
            ,[HDR_RouteSchedule] 
            ,[HDR_IncotermsClassification] 
            ,[HDR_IncotermsTransferLocation] 
            ,[HDR_TransportationGroup] 
            ,[HDR_MeansOfTransport] 
            ,[HDR_MeansOfTransportType] 
            ,[HDR_ProofOfDeliveryDate] 
            ,[HDR_CustomerGroup] 
            ,[HDR_TotalBlockStatusID] 
            ,[HDR_TransportationPlanningStatusID] 
            ,[HDR_OverallPickingConfStatusID] 
            ,[HDR_OverallPickingStatusID] 
            ,[HDR_OverallPackingStatusID] 
            ,[HDR_OverallGoodsMovementStatusID] 
            ,[HDR_OverallProofOfDeliveryStatusID] 
            ,[HDR_IntercompanyBillingType] 
            ,[HDR_IntercompanyBillingCustomer] 
            ,[HDR_TotalNetAmount] 
            ,[HDR_ReferenceDocumentNumber] 
            ,[HDR_CreatedByUser]
            ,[HDR_DocumentDate]
            ,[HDR_ExternalTransportSystem]
            ,[HDR_HdrGeneralIncompletionStatusID]
            ,[HDR_HdrGoodsMvtIncompletionStatusID]
            ,[HDR_HeaderBillgIncompletionStatusID]
            ,[HDR_HeaderBillingBlockReason]
            ,[HDR_HeaderDelivIncompletionStatusID]
            ,[HDR_HeaderPackingIncompletionSts]
            ,[HDR_HeaderPickgIncompletionStatusID]
            ,[HDR_IsExportDelivery]
            ,[HDR_LastChangeDate]
            ,[HDR_LastChangedByUser]
            ,[HDR_LoadingPoint]
            ,[HDR_OverallChmlCmplncStatusID]
            ,[HDR_OverallDangerousGoodsStatusID]
            ,[HDR_OverallDelivConfStatusID]
            ,[HDR_OverallDelivReltdBillgStatusID]
            ,[HDR_OverallIntcoBillingStatusID]
            ,[HDR_OverallSafetyDataSheetStatusID]
            ,[HDR_OverallSDProcessStatusID]
            ,[HDR_OverallWarehouseActivityStatusID]
            ,[HDR_OvrlItmDelivIncompletionSts]
            ,[HDR_OvrlItmGdsMvtIncompletionSts]
            ,[HDR_OvrlItmGeneralIncompletionSts]
            ,[HDR_OvrlItmPackingIncompletionSts]
            ,[HDR_OvrlItmPickingIncompletionSts]
            ,[HDR_ShippingGroupNumber]
            ,[HDR_TotalNumberOfPackage]
            ,[HDR_TransactionCurrency]
            ,[Currency_EUR]
            ,[ActualDeliveryRouteName]
            ,[ActualDeliveryRouteDurationInHrs]
            ,[ProposedDeliveryRouteName]
            ,[ProposedDeliveryRouteDurationInHrs]
            ,[ActualDeliveryRouteDurationInDays]
            ,[ProposedDeliveryRouteDurationInDays]
            ,[InOutID]
            ,[SDICreationDateIsODICreationDateFlag]
            ,[IF_Total_Group]
            ,[IF_Group]
            ,[IF_IsInFullFlag]
            ,[IF_IsInFull]
            ,[NoActualDeliveredQtyFlag]
            ,[OTS_GoodsIssueDateDiffInDays]
            ,[OTS_DaysDiff]
            ,[OTS_GIDateCheckGroup]
            ,[OTS_Group]
            ,[SDAvailableFlag]
            ,[SDI_ConfQtyEqOrderQtyFlag]
            ,[SLAvailableFlag]
            ,[IF_DataQualityCode]
            ,[OTD_DataQualityCode]
            ,[OTS_DataQualityCode]
            ,[CalculatedDelDate]
            ,[ActualLeadTime]
            ,[ALT001_DataQualityCode]
            ,[RequestedLeadTime]
            ,[RLT001_DataQualityCode]
            ,[OTD_DaysDiff]
            ,[OTD_Group]
            ,[OTD_EarlyDays]
            ,[OTD_IsEarly]
            ,[OTD_IsLate]
            ,[OTD_IsOnTime]
            ,[OTD_LateDays]
            ,[OTDIF_OnTimeDelInFull]
            ,[OTR_DaysDiff]
            ,[OTR_Group]
            ,[OTR_EarlyDays]
            ,[OTR_IsEarly]
            ,[OTR_IsLate]
            ,[OTR_IsOnTime]
            ,[OTR_LateDays]
            ,[OTRIF_OnTimeCusReqInFull]
            ,[t_applicationId]
            ,[t_extractionDtm]
            ,[t_jobId]
            ,[t_jobDtm]
            ,[t_lastActionCd]
            ,[t_jobBy]
        )
        SELECT 
            [nk_fact_OutboundDeliveryItem]
            ,[OutboundDelivery]
            ,[OutboundDeliveryItem]
            ,[DeliveryDocumentItemCategoryID]
            ,[SalesDocumentItemTypeID]
            ,[CreatedByUserID]
            ,[CreationDate]
            ,[CreationTime]
            ,[LastChangeDate]
            ,[DistributionChannelID]
            ,[ProductID]
            ,[OriginallyRequestedMaterialID]
            ,[ProductGroupID]
            ,[PlantID]
            ,[WarehouseID]
            ,[StorageLocationID]
            ,[HigherLevelItem]
            ,[ActualDeliveryQuantity]
            ,[ActDelQtyTotalForSDI]
            ,[DeliveryQuantityUnit]
            ,[ActualDeliveredQtyInBaseUnit]
            ,[BaseUnit]
            ,[Batch]
            ,[BatchClassification]
            ,[BusinessArea]
            ,[ChmlCmplncStatusID]
            ,[ControllingArea]
            ,[CostCenter]
            ,[CostInDocumentCurrency]
            ,[CreditRelatedPrice]
            ,[DangerousGoodsStatusID]
            ,[DeliveryGroup]
            ,[Division]
            ,[FixedShipgProcgDurationInDays]
            ,[FunctionalArea]
            ,[GoodsMovementType]
            ,[InventorySpecialStockType]
            ,[IsNotGoodsMovementsRelevant]
            ,[ItemGrossWeight]
            ,[ItemNetWeight]
            ,[WGT001_DataQualityCode]            
            ,[ItemVolume]
            ,[ItemVolumeUnit]
            ,[ItemWeightUnit]
            ,[LoadingGroup]
            ,[NetPriceAmount_LC]
            ,[OrderDocument]
            ,[OrderID]
            ,[OrderItem]
            ,[OriginalDeliveryQuantity]
            ,[OriginSDDocument]
            ,[OverdelivTolrtdLmtRatioInPct]
            ,[PartialDeliveryIsAllowed]
            ,[PlanningPlant]
            ,[ProductAvailabilityDate]
            ,[ProfitCenterID]
            ,[SalesGroup]
            ,[SalesOffice]
            ,[SDDocumentItem]
            ,[SubsequentMovementType]
            ,[HDR_TotalNetAmount_LC]
            ,[VarblShipgProcgDurationInDays]
            ,[UnlimitedOverdeliveryIsAllowed]
            ,[GLAccountID]
            ,[IsCompletelyDelivered]
            ,[ReceivingPoint]
            ,[ItemIsBillingRelevant]
            ,[ReferenceSDDocument]
            ,[ReferenceSDDocumentItem]
            ,[ReferenceSDDocumentCategoryID]
            ,[SDProcessStatusID]
            ,[PickingConfirmationStatusID]
            ,[PickingStatusID]
            ,[WarehouseActivityStatusID]
            ,[PackingStatusID]
            ,[GoodsMovementStatusID]
            ,[DeliveryRelatedBillingStatusID]
            ,[ProofOfDeliveryStatusID]
            ,[ItemGeneralIncompletionStatusID]
            ,[ItemDeliveryIncompletionStatusID]
            ,[ItemPickingIncompletionStatusID]
            ,[ItemGdsMvtIncompletionStsID]
            ,[ItemPackingIncompletionStatusID]
            ,[ItemBillingIncompletionStatusID]
            ,[IntercompanyBillingStatusID]
            ,[IsReturnsItem]
            ,[SL_ConfirmedDeliveryDate]
            ,[SL_OriginalConfirmedDeliveryDate]
            ,[SL_FirstCustomerRequestedDeliveryDate]
            ,null as [SL_ConfdOrderQtyByMatlAvailCheck]
            ,[SL_GoodsIssueDate]
            ,[SL_ScheduleLine]
            ,[HDR_SalesDistrictID]
            ,[HDR_SalesOrganizationID]
            ,[HDR_SoldToPartyID]
            ,[HDR_ShipToPartyID]
            ,[HDR_DeliveryDocumentTypeID]
            ,[HDR_CompleteDeliveryIsDefined]
            ,[HDR_SupplierID]
            ,[HDR_ReceivingPlantID]
            ,[HDR_DeletionIndicator]
            ,[HDR_DeliveryDate]
            ,[HDR_CarrierID]
            ,[HDR_Carrier]
            ,[SDI_CreationDate]
            ,[SDI_RequestedDeliveryDate]
            ,[SDI_PricePerPiece_LC]
            ,[SDI_PricePerPiece_EUR]
            ,[SDI_LocalCurrency]
            ,[SDI_SalesDocumentTypeID]
            ,[SDI_IsReturnsItemID]
            ,[SDI_BillToParty]
            ,[SDI_ConfdDeliveryQtyInBaseUnit]
            ,[SDI_ConfdDelivQtyInOrderQtyUnit]
            ,[SDI_CostAmount_LC]
            ,[SDI_CostAmount_EUR]
            ,[SDI_DeliveryBlockStatusID]
            ,[SDI_ExchangeRateDate]
            ,[SDI_ExchangeRateType]
            ,[SDI_NetAmount_LC]
            ,[SDI_NetAmount_EUR]
            ,[SDI_NetPriceQuantityUnit]
            ,[SDI_OrderID]
            ,[SDI_OrderQuantity]
            ,[SDI_OrderQuantityUnit]
            ,[SDI_OverallTotalDeliveryStatusID]
            ,[SDI_PayerParty]
            ,[SDI_Route]
            ,[SDI_SalesDocumentItemCategory]
            ,[SDI_SalesOrganizationCurrency]
            ,[SDI_SDDocumentCategory]
            ,[SDI_SDDocumentRejectionStatusID]
            ,[SDI_StorageLocationID]
            ,[OTS_IsOnTime] 
            ,[OTS_EarlyDays] 
            ,[OTS_LateDays] 
            ,[OTS_IsEarly] 
            ,[OTS_IsLate] 
            ,[RouteIsChangedFlag]
            ,[NrODIPerSDIAndQtyNot0]
            ,[NrSLInScope]
            ,[OTSIF_OnTimeShipInFull]
            ,[HDR_PlannedGoodsIssueDate] 
            ,[HDR_ActualGoodsMovementDate] 
            ,[HDR_ShippingPointID] 
            ,[HDR_OrderCombinationIsAllowed] 
            ,[HDR_DeliveryPriority] 
            ,[HDR_DeliveryBlockReason] 
            ,[HDR_DeliveryDocumentBySupplier] 
            ,[HDR_DeliveryIsInPlant] 
            ,[HDR_OrderID] 
            ,[HDR_PickingDate] 
            ,[HDR_LoadingDate] 
            ,[HDR_ShippingType] 
            ,[HDR_ShippingCondition] 
            ,[HDR_ShipmentBlockReason] 
            ,[HDR_TransportationPlanningDate] 
            ,[HDR_ProposedDeliveryRoute] 
            ,[HDR_ActualDeliveryRoute] 
            ,[HDR_RouteSchedule] 
            ,[HDR_IncotermsClassification] 
            ,[HDR_IncotermsTransferLocation] 
            ,[HDR_TransportationGroup] 
            ,[HDR_MeansOfTransport] 
            ,[HDR_MeansOfTransportType] 
            ,[HDR_ProofOfDeliveryDate] 
            ,[HDR_CustomerGroup] 
            ,[HDR_TotalBlockStatusID] 
            ,[HDR_TransportationPlanningStatusID] 
            ,[HDR_OverallPickingConfStatusID] 
            ,[HDR_OverallPickingStatusID] 
            ,[HDR_OverallPackingStatusID] 
            ,[HDR_OverallGoodsMovementStatusID] 
            ,[HDR_OverallProofOfDeliveryStatusID] 
            ,[HDR_IntercompanyBillingType] 
            ,[HDR_IntercompanyBillingCustomer] 
            ,[HDR_TotalNetAmount] 
            ,[HDR_ReferenceDocumentNumber]
            ,[HDR_CreatedByUser]
            ,[HDR_DocumentDate]
            ,[HDR_ExternalTransportSystem]
            ,[HDR_HdrGeneralIncompletionStatusID]
            ,[HDR_HdrGoodsMvtIncompletionStatusID]
            ,[HDR_HeaderBillgIncompletionStatusID]
            ,[HDR_HeaderBillingBlockReason]
            ,[HDR_HeaderDelivIncompletionStatusID]
            ,[HDR_HeaderPackingIncompletionSts]
            ,[HDR_HeaderPickgIncompletionStatusID]
            ,[HDR_IsExportDelivery]
            ,[HDR_LastChangeDate]
            ,[HDR_LastChangedByUser]
            ,[HDR_LoadingPoint]
            ,[HDR_OverallChmlCmplncStatusID]
            ,[HDR_OverallDangerousGoodsStatusID]
            ,[HDR_OverallDelivConfStatusID]
            ,[HDR_OverallDelivReltdBillgStatusID]
            ,[HDR_OverallIntcoBillingStatusID]
            ,[HDR_OverallSafetyDataSheetStatusID]
            ,[HDR_OverallSDProcessStatusID]
            ,[HDR_OverallWarehouseActivityStatusID]
            ,[HDR_OvrlItmDelivIncompletionSts]
            ,[HDR_OvrlItmGdsMvtIncompletionSts]
            ,[HDR_OvrlItmGeneralIncompletionSts]
            ,[HDR_OvrlItmPackingIncompletionSts]
            ,[HDR_OvrlItmPickingIncompletionSts]
            ,[HDR_ShippingGroupNumber]
            ,[HDR_TotalNumberOfPackage]
            ,[HDR_TransactionCurrency]
            ,[Currency_EUR]
            ,[ActualDeliveryRouteName]
            ,[ActualDeliveryRouteDurationInHrs]
            ,[ProposedDeliveryRouteName]
            ,[ProposedDeliveryRouteDurationInHrs]
            ,[ActualDeliveryRouteDurationInDays]
            ,[ProposedDeliveryRouteDurationInDays]
            ,[InOutID]
            ,[SDICreationDateIsODICreationDateFlag]
            ,[IF_Total_Group]
            ,[IF_Group]
            ,[IF_IsInFullFlag]
            ,[IF_IsInFull]
            ,[NoActualDeliveredQtyFlag]
            ,[OTS_GoodsIssueDateDiffInDays]
            ,[OTS_DaysDiff]
            ,[OTS_GIDateCheckGroup]
            ,[OTS_Group]
            ,[SDAvailableFlag]
            ,[SDI_ConfQtyEqOrderQtyFlag]
            ,[SLAvailableFlag]
            ,[IF_DataQualityCode]
            ,[OTD_DataQualityCode]
            ,[OTS_DataQualityCode]
            ,[CalculatedDelDate]
            ,[ActualLeadTime]
            ,[ALT001_DataQualityCode]
            ,[RequestedLeadTime]
            ,[RLT001_DataQualityCode]
            ,[OTD_DaysDiff]
            ,[OTD_Group]
            ,[OTD_EarlyDays]
            ,[OTD_IsEarly]
            ,[OTD_IsLate]
            ,[OTD_IsOnTime]
            ,[OTD_LateDays]
            ,[OTDIF_OnTimeDelInFull]
            ,[OTR_DaysDiff]
            ,[OTR_Group]
            ,[OTR_EarlyDays]
            ,[OTR_IsEarly]
            ,[OTR_IsLate]
            ,[OTR_IsOnTime]
            ,[OTR_LateDays]
            ,[OTRIF_OnTimeCusReqInFull]
            ,[t_applicationId]
            ,[t_extractionDtm]
            ,@t_jobId AS t_jobId
            ,@t_jobDtm AS t_jobDtm
            ,@t_lastActionCd AS t_lastActionCd
            ,@t_jobBy AS t_jobBy
        FROM [edw].[vw_OutboundDeliveryItem_s4h];    


        /*
            MPS 2022-01-19 Including AXBI data in OutboundDeliveryItem is currently on hold.
        */
	--     SELECT TOP 1 @isAXBIViewNotEmpty = 1 FROM [edw].[vw_OutboundDeliveryItem_axbi];

    --     IF (@isAXBIViewNotEmpty = 0)
    --         begin
    --             SET @errmessage = 'Temporary view [edw].[vw_OutboundDeliveryItem_axbi] was not filled with data from AXBI.';
    --             THROW 50001, @errmessage, 1;
    --         end;

    --     INSERT INTO [edw].[fact_OutboundDeliveryItem_tmp](
    --    [nk_fact_OutboundDeliveryItem]
    --   ,[OutboundDelivery]
    --   ,[OutboundDeliveryItem]
    --   ,[DeliveryDocumentItemCategoryID]
    --   ,[SalesDocumentItemTypeID]
    --   ,[CreatedByUserID]
    --   ,[CreationDate]
    --   ,[CreationTime]
    --   ,[LastChangeDate]
    --   ,[DistributionChannelID]
    --   ,[ProductID]
    --   ,[OriginallyRequestedMaterialID]
    --   ,[ProductGroupID]
    --   ,[PlantID]
    --   ,[WarehouseID]
    --   ,[StorageLocationID]
    --   ,[HigherLevelItem]
    --   ,[ActualDeliveryQuantity]
    --   ,[ActDelQtyTotalForSDI]
    --   ,[DeliveryQuantityUnit]
	--   ,[ActualDeliveredQtyInBaseUnit]
    --   ,[BaseUnit]
    --   ,[Batch]
    --   ,[BatchClassification]
    --   ,[BusinessArea]
    --   ,[ChmlCmplncStatusID]
    --   ,[ControllingArea]
    --   ,[CostCenter]
    --   ,[CostInDocumentCurrency]
    --   ,[CreditRelatedPrice]
    --   ,[DangerousGoodsStatusID]
    --   ,[DeliveryGroup]
    --   ,[Division]
    --   ,[FixedShipgProcgDurationInDays]
    --   ,[FunctionalArea]
    --   ,[GoodsMovementType]
    --   ,[InventorySpecialStockType]
    --   ,[IsNotGoodsMovementsRelevant]
    --   ,[ItemGrossWeight]
    --   ,[ItemNetWeight]
    --   ,[ItemVolume]
    --   ,[ItemVolumeUnit]
    --   ,[ItemWeightUnit]
    --   ,[LoadingGroup]
    --   ,[NetPriceAmount_LC]
    --   ,[OrderDocument]
    --   ,[OrderID]
    --   ,[OrderItem]
    --   ,[OriginalDeliveryQuantity]
    --   ,[OriginSDDocument]
    --   ,[OverdelivTolrtdLmtRatioInPct]
    --   ,[PartialDeliveryIsAllowed]
    --   ,[PlanningPlant]
    --   ,[ProductAvailabilityDate]
    --   ,[ProfitCenterID]
    --   ,[SalesGroup]
    --   ,[SalesOffice]
    --   ,[SDDocumentItem]
    --   ,[SubsequentMovementType]
    --   ,[HDR_TotalNetAmount_LC]
    --   ,[VarblShipgProcgDurationInDays]
    --   ,[UnlimitedOverdeliveryIsAllowed]
    --   ,[GLAccountID]
    --   ,[IsCompletelyDelivered]
    --   ,[ReceivingPoint]
    --   ,[ItemIsBillingRelevant]
    --   ,[ReferenceSDDocument]
    --   ,[ReferenceSDDocumentItem]
    --   ,[sk_fact_SalesDocumentItem]
    --   ,[ReferenceSDDocumentCategoryID]
    --   ,[SDProcessStatusID]
    --   ,[PickingConfirmationStatusID]
    --   ,[PickingStatusID]
    --   ,[WarehouseActivityStatusID]
    --   ,[PackingStatusID]
    --   ,[GoodsMovementStatusID]
    --   ,[DeliveryRelatedBillingStatusID]
    --   ,[ProofOfDeliveryStatusID]
    --   ,[ItemGeneralIncompletionStatusID]
    --   ,[ItemDeliveryIncompletionStatusID]
    --   ,[ItemPickingIncompletionStatusID]
    --   ,[ItemGdsMvtIncompletionStsID]
    --   ,[ItemPackingIncompletionStatusID]
    --   ,[ItemBillingIncompletionStatusID]
    --   ,[IntercompanyBillingStatusID]
    --   ,[IsReturnsItem]
    --   ,[SL_ConfirmedDeliveryDate]
    --   ,[SL_ConfdOrderQtyByMatlAvailCheck]
    --   ,[SL_GoodsIssueDate]
    --   ,[SL_ScheduleLine]
    --   ,[HDR_SalesDistrictID]
    --   ,[HDR_SalesOrganizationID]
    --   ,[HDR_SoldToPartyID]
    --   ,[HDR_ShipToPartyID]
    --   ,[HDR_DeliveryDocumentTypeID]
    --   ,[HDR_CompleteDeliveryIsDefined]
    --   ,[HDR_SupplierID]
    --   ,[HDR_ReceivingPlantID]
    --   ,[HDR_DeletionIndicator]
    --   ,[HDR_DeliveryDate]
    --   ,[SDI_CreationDate]
    --   ,[SDI_RequestedDeliveryDate]
    --   ,[SDI_PricePerPiece_LC]
    --   ,[SDI_PricePerPiece_EUR]
    --   ,[SDI_LocalCurrency]
    --   ,[SDI_SalesDocumentTypeID]
    --   ,[SDI_IsReturnsItemID]
    --   ,[SDI_BillToParty]
    --   ,[SDI_ConfdDeliveryQtyInBaseUnit]
    --   ,[SDI_ConfdDelivQtyInOrderQtyUnit]
    --   ,[SDI_CostAmount_LC]
    --   ,[SDI_CostAmount_EUR]
    --   ,[SDI_DeliveryBlockStatusID]
    --   ,[SDI_ExchangeRateDate]
    --   ,[SDI_ExchangeRateType]
    --   ,[SDI_NetAmount_LC]
    --   ,[SDI_NetAmount_EUR]
    --   ,[SDI_NetPriceQuantityUnit]
    --   ,[SDI_OrderID]
    --   ,[SDI_OrderQuantity]
    --   ,[SDI_OrderQuantityUnit]
    --   ,[SDI_OverallTotalDeliveryStatusID]
    --   ,[SDI_PayerParty]
    --   ,[SDI_Route]
    --   ,[SDI_SalesDocumentItemCategory]
    --   ,[SDI_SalesOrganizationCurrency]
    --   ,[SDI_SDDocumentCategory]
    --   ,[SDI_SDDocumentRejectionStatusID]
    --   ,[SDI_StorageLocationID]
    --   ,[OTS_IsOnTime] 
    --   ,[OTS_EarlyDays] 
    --   ,[OTS_LateDays] 
    --   ,[OTS_IsEarly] 
    --   ,[OTS_IsLate] 
    --   ,[RouteIsChangedFlag]
    --   ,[NrODIPerSDIAndQtyNot0]
    --   ,[NrSLInScope]
    --   ,[OTSIF_OnTimeShipInFull]
    --   ,[HDR_PlannedGoodsIssueDate] 
    --   ,[HDR_ActualGoodsMovementDate] 
    --   ,[HDR_ShippingPointID] 
    --   ,[HDR_OrderCombinationIsAllowed] 
    --   ,[HDR_DeliveryPriority] 
    --   ,[HDR_DeliveryBlockReason] 
    --   ,[HDR_DeliveryDocumentBySupplier] 
    --   ,[HDR_DeliveryIsInPlant] 
    --   ,[HDR_OrderID] 
    --   ,[HDR_PickingDate] 
    --   ,[HDR_LoadingDate] 
    --   ,[HDR_ShippingType] 
    --   ,[HDR_ShippingCondition] 
    --   ,[HDR_ShipmentBlockReason] 
    --   ,[HDR_TransportationPlanningDate] 
    --   ,[HDR_ProposedDeliveryRoute] 
    --   ,[HDR_ActualDeliveryRoute] 
    --   ,[HDR_RouteSchedule] 
    --   ,[HDR_IncotermsClassification] 
    --   ,[HDR_IncotermsTransferLocation] 
    --   ,[HDR_TransportationGroup] 
    --   ,[HDR_MeansOfTransport] 
    --   ,[HDR_MeansOfTransportType] 
    --   ,[HDR_ProofOfDeliveryDate] 
    --   ,[HDR_CustomerGroup] 
    --   ,[HDR_TotalBlockStatusID] 
    --   ,[HDR_TransportationPlanningStatusID] 
    --   ,[HDR_OverallPickingConfStatusID] 
    --   ,[HDR_OverallPickingStatusID] 
    --   ,[HDR_OverallPackingStatusID] 
    --   ,[HDR_OverallGoodsMovementStatusID] 
    --   ,[HDR_OverallProofOfDeliveryStatusID] 
    --   ,[HDR_IntercompanyBillingType] 
    --   ,[HDR_IntercompanyBillingCustomer] 
    --   ,[HDR_TotalNetAmount] 
    --   ,[HDR_ReferenceDocumentNumber] 
    --   ,[HDR_CreatedByUser]
    --   ,[HDR_DocumentDate]
    --   ,[HDR_ExternalTransportSystem]
    --   ,[HDR_HdrGeneralIncompletionStatusID]
    --   ,[HDR_HdrGoodsMvtIncompletionStatusID]
    --   ,[HDR_HeaderBillgIncompletionStatusID]
    --   ,[HDR_HeaderBillingBlockReason]
    --   ,[HDR_HeaderDelivIncompletionStatusID]
    --   ,[HDR_HeaderPackingIncompletionSts]
    --   ,[HDR_HeaderPickgIncompletionStatusID]
    --   ,[HDR_IsExportDelivery]
    --   ,[HDR_LastChangeDate]
    --   ,[HDR_LastChangedByUser]
    --   ,[HDR_LoadingPoint]
    --   ,[HDR_OverallChmlCmplncStatusID]
    --   ,[HDR_OverallDangerousGoodsStatusID]
    --   ,[HDR_OverallDelivConfStatusID]
    --   ,[HDR_OverallDelivReltdBillgStatusID]
    --   ,[HDR_OverallIntcoBillingStatusID]
    --   ,[HDR_OverallSafetyDataSheetStatusID]
    --   ,[HDR_OverallSDProcessStatusID]
    --   ,[HDR_OverallWarehouseActivityStatusID]
    --   ,[HDR_OvrlItmDelivIncompletionSts]
    --   ,[HDR_OvrlItmGdsMvtIncompletionSts]
    --   ,[HDR_OvrlItmGeneralIncompletionSts]
    --   ,[HDR_OvrlItmPackingIncompletionSts]
    --   ,[HDR_OvrlItmPickingIncompletionSts]
    --   ,[HDR_ShippingGroupNumber]
    --   ,[HDR_TotalNumberOfPackage]
    --   ,[HDR_TransactionCurrency]
    --   ,[Currency_EUR]
    --   ,[ActualDeliveryRouteName]
    --   ,[ActualDeliveryRouteDurationInHrs]
    --   ,[ProposedDeliveryRouteName]
    --   ,[ProposedDeliveryRouteDurationInHrs]
    --   ,[ActualDeliveryRouteDurationInDays]
    --   ,[ProposedDeliveryRouteDurationInDays]
    --   ,[InOutID]
    --   ,[SDICreationDateIsODICreationDateFlag]
    --   ,[IF_Total_Group]
    --   ,[IF_Group]
    --   ,[IF_IsInFullFlag]
    --   ,[IF_IsInFull]
    --   ,[NoActualDeliveredQtyFlag]
    --   ,[OTS_GoodsIssueDateDiffInDays]
    --   ,[OTS_DaysDiff]
    --   ,[OTS_GIDateCheckGroup]
    --   ,[OTS_Group]
    --   ,[SDAvailableFlag]
    --   ,[SDI_ConfQtyEqOrderQtyFlag]
    --   ,[SLAvailableFlag]
    --   ,[IF_DataQualityCode]
    --   ,[OTD_DataQualityCode]
    --   ,[OTS_DataQualityCode]
    --   ,[CalculatedDelDate]
    --   ,[OTD_DaysDiff]
    --   ,[OTD_Group]
    --   ,[OTD_EarlyDays]
    --   ,[OTD_IsEarly]
    --   ,[OTD_IsLate]
    --   ,[OTD_IsOnTime]
    --   ,[OTD_LateDays]
    --   ,[OTDIF_OnTimeDelInFull]
    --   ,[t_applicationId]
    --   ,[t_extractionDtm]
    --   ,[t_jobId]
    --   ,[t_jobDtm]
    --   ,[t_lastActionCd]
    --   ,[t_jobBy])
    -- SELECT [nk_fact_OutboundDeliveryItem]
    --       ,[OutboundDelivery]
    --       ,[OutboundDeliveryItem]
    --       ,null as [DeliveryDocumentItemCategoryID]
    --       ,null as [SalesDocumentItemTypeID]
    --       ,null as [CreatedByUserID]
    --       ,null as [CreationDate]
    --       ,null as [CreationTime]
    --       ,null as [LastChangeDate]
    --       ,null as [DistributionChannelID]
    --       ,[ProductID]
    --       ,null as [OriginallyRequestedMaterialID]
    --       ,null as [ProductGroupID]
    --       ,null as [PlantID]
    --       ,null as [WarehouseID]
    --       ,null as [StorageLocationID]
    --       ,null as [HigherLevelItem]
    --       ,[ActualDeliveryQuantity]
    --       ,null as [ActDelQtyTotalForSDI]
    --       ,null as [DeliveryQuantityUnit]
	--       ,null as [ActualDeliveredQtyInBaseUnit]
    --       ,null as [BaseUnit]
    --       ,null as [Batch]
    --       ,null as [BatchClassification]
    --       ,null as [BusinessArea]
    --       ,null as [ChmlCmplncStatusID]
    --       ,null as [ControllingArea]
    --       ,null as [CostCenter]
    --       ,null as [CostInDocumentCurrency]
    --       ,null as [CreditRelatedPrice]
    --       ,null as [DangerousGoodsStatus]
    --       ,null as [DeliveryGroup]
    --       ,null as [Division]
    --       ,null as [FixedShipgProcgDurationInDays]
    --       ,null as [FunctionalArea]
    --       ,null as [GoodsMovementType]
    --       ,null as [InventorySpecialStockType]
    --       ,null as [IsNotGoodsMovementsRelevant]
    --       ,null as [ItemGrossWeight]
    --       ,null as [ItemNetWeight]
    --       ,null as [ItemVolume]
    --       ,null as [ItemVolumeUnit]
    --       ,null as [ItemWeightUnit]
    --       ,null as [LoadingGroup]
    --       ,null as [NetPriceAmount]
    --       ,null as [OrderDocument]
    --       ,null as [OrderID]
    --       ,null as [OrderItem]
    --       ,null as [OriginalDeliveryQuantity]
    --       ,null as [OriginSDDocument]
    --       ,null as [OverdelivTolrtdLmtRatioInPct]
    --       ,null as [PartialDeliveryIsAllowed]
    --       ,null as [PlanningPlant]
    --       ,null as [ProductAvailabilityDate]
    --       ,null as [ProfitCenterID]
    --       ,null as [SalesGroup]
    --       ,null as [SalesOffice]
    --       ,null as [SDDocumentItem]
    --       ,null as [SubsequentMovementType]
    --       ,null as [TotalNetAmount]
    --       ,null as [VarblShipgProcgDurationInDays]
    --       ,null as [UnlimitedOverdeliveryIsAllowed]
    --       ,null as [GLAccountID]
    --       ,null as [IsCompletelyDelivered]
    --       ,null as [ReceivingPoint]
    --       ,null as [ItemIsBillingRelevant]
    --       ,[ReferenceSDDocument]
    --       ,[ReferenceSDDocumentItem]
    --       ,null as [sk_fact_SalesDocumentItem]
    --       ,null as [ReferenceSDDocumentCategoryID]
    --       ,null as [SDProcessStatusID]
    --       ,null as [PickingConfirmationStatusID]
    --       ,null as [PickingStatusID]
    --       ,null as [WarehouseActivityStatusID]
    --       ,null as [PackingStatusID]
    --       ,null as [GoodsMovementStatusID]
    --       ,null as [DeliveryRelatedBillingStatusID]
    --       ,null as [ProofOfDeliveryStatusID]
    --       ,null as [ItemGeneralIncompletionStatusID]
    --       ,null as [ItemDeliveryIncompletionStatusID]
    --       ,null as [ItemPickingIncompletionStatusID]
    --       ,null as [ItemGdsMvtIncompletionStsID]
    --       ,null as [ItemPackingIncompletionStatusID]
    --       ,null as [ItemBillingIncompletionStatusID]
    --       ,null as [IntercompanyBillingStatusID]
    --       ,null as [IsReturnsItem]
    --       ,[SL_ConfirmedDeliveryDate]
    --       ,[SL_ConfdOrderQtyByMatlAvailCheck]
    --       ,null as [SL_GoodsIssueDate]
    --       ,null as [SL_ScheduleLine]
    --       ,null as [HDR_SalesDistrictID]
    --       ,[HDR_SalesOrganizationID]
    --       ,[HDR_SoldToPartyID]
    --       ,null as [HDR_ShipToPartyID]
    --       ,null as [HDR_DeliveryDocumentTypeID]
    --       ,null as [HDR_CompleteDeliveryIsDefinedID]
    --       ,null as [HDR_SupplierID]
    --       ,null as [HDR_ReceivingPlantID]
    --       ,null as [HDR_DeletionIndicator]
    --       ,[HDR_DeliveryDate]
    --       ,null as [SDI_CreationDate]
    --       ,[SDI_RequestedDeliveryDate]
    --       ,[SDI_PricePerPiece_LC]
    --       ,null as [SDI_PricePerPiece_EUR]
    --       ,[SDI_LocalCurrency]
    --       ,null as [SDI_SalesDocumentTypeID]
    --       ,null as [SDI_IsReturnsItemID]
    --       ,null as [SDI_BillToParty]
    --       ,null as [SDI_ConfdDeliveryQtyInBaseUnit]
    --       ,null as [SDI_ConfdDelivQtyInOrderQtyUnit]
    --       ,null as [SDI_CostAmount_LC]
    --       ,null as [SDI_CostAmount_EUR]
    --       ,null as [SDI_DeliveryBlockStatusID]
    --       ,null as [SDI_ExchangeRateDate]
    --       ,null as [SDI_ExchangeRateType]
    --       ,null as [SDI_NetAmount_LC]
    --       ,null as [SDI_NetAmount_EUR]
    --       ,null as [SDI_NetPriceQuantityUnit]
    --       ,null as [SDI_OrderID]
    --       ,null as [SDI_OrderQuantity]
    --       ,null as [SDI_OrderQuantityUnit]
    --       ,null as [SDI_OverallTotalDeliveryStatusID]
    --       ,null as [SDI_PayerParty]
    --       ,null as [SDI_Route]
    --       ,null as [SDI_SalesDocumentItemCategory]
    --       ,null as [SDI_SalesOrganizationCurrency]
    --       ,null as [SDI_SDDocumentCategory]
    --       ,null as [SDI_SDDocumentRejectionStatusID]
    --       ,null as [SDI_StorageLocationID]
    --       ,null as [OTS_IsOnTime] 
    --       ,null as [OTS_EarlyDays] 
    --       ,null as [OTS_LateDays] 
    --       ,null as [OTS_IsEarly] 
    --       ,null as [OTS_IsLate] 
    --       ,null as [RouteIsChangedFlag] 
    --       ,null as [NrODIPerSDIAndQtyNot0] 
    --       ,null as [NrSLInScope]
    --       ,null as [OTSIF_OnTimeShipInFull] 
    --       ,null as [HDR_PlannedGoodsIssueDate] 
    --       ,null as [HDR_ActualGoodsMovementDate] 
    --       ,null as [HDR_ShippingPointID] 
    --       ,null as [HDR_OrderCombinationIsAllowed] 
    --       ,null as [HDR_DeliveryPriority] 
    --       ,null as [HDR_DeliveryBlockReason] 
    --       ,null as [HDR_DeliveryDocumentBySupplier] 
    --       ,null as [HDR_DeliveryIsInPlant] 
    --       ,null as [HDR_OrderID] 
    --       ,null as [HDR_PickingDate] 
    --       ,null as [HDR_LoadingDate] 
    --       ,null as [HDR_ShippingType] 
    --       ,null as [HDR_ShippingCondition] 
    --       ,null as [HDR_ShipmentBlockReason] 
    --       ,null as [HDR_TransportationPlanningDate] 
    --       ,null as [HDR_ProposedDeliveryRoute] 
    --       ,null as [HDR_ActualDeliveryRoute] 
    --       ,null as [HDR_RouteSchedule] 
    --       ,null as [HDR_IncotermsClassification] 
    --       ,null as [HDR_IncotermsTransferLocation] 
    --       ,null as [HDR_TransportationGroup] 
    --       ,null as [HDR_MeansOfTransport] 
    --       ,null as [HDR_MeansOfTransportType] 
    --       ,null as [HDR_ProofOfDeliveryDate] 
    --       ,null as [HDR_CustomerGroup] 
    --       ,null as [HDR_TotalBlockStatusID] 
    --       ,null as [HDR_TransportationPlanningStatusID] 
    --       ,null as [HDR_OverallPickingConfStatusID] 
    --       ,null as [HDR_OverallPickingStatusID] 
    --       ,null as [HDR_OverallPackingStatusID] 
    --       ,null as [HDR_OverallGoodsMovementStatusID] 
    --       ,null as [HDR_OverallProofOfDeliveryStatusID] 
    --       ,null as [HDR_IntercompanyBillingType] 
    --       ,null as [HDR_IntercompanyBillingCustomer] 
    --       ,null as [HDR_TotalNetAmount] 
    --       ,null as [HDR_ReferenceDocumentNumber] 
	--       ,null as [HDR_CreatedByUser]
    --       ,null as [HDR_DocumentDate]
    --       ,null as [HDR_ExternalTransportSystem]
    --       ,null as [HDR_HdrGeneralIncompletionStatusID]
    --       ,null as [HDR_HdrGoodsMvtIncompletionStatusID]
    --       ,null as [HDR_HeaderBillgIncompletionStatusID]
    --       ,null as [HDR_HeaderBillingBlockReason]
    --       ,null as [HDR_HeaderDelivIncompletionStatusID]
    --       ,null as [HDR_HeaderPackingIncompletionSts]
    --       ,null as [HDR_HeaderPickgIncompletionStatusID]
    --       ,null as [HDR_IsExportDelivery]
    --       ,null as [HDR_LastChangeDate]
    --       ,null as [HDR_LastChangedByUser]
    --       ,null as [HDR_LoadingPoint]
    --       ,null as [HDR_OverallChmlCmplncStatusID]
    --       ,null as [HDR_OverallDangerousGoodsStatusID]
    --       ,null as [HDR_OverallDelivConfStatusID]
    --       ,null as [HDR_OverallDelivReltdBillgStatusID]
    --       ,null as [HDR_OverallIntcoBillingStatusID]
    --       ,null as [HDR_OverallSafetyDataSheetStatusID]
    --       ,null as [HDR_OverallSDProcessStatusID]
    --       ,null as [HDR_OverallWarehouseActivityStatusID]
    --       ,null as [HDR_OvrlItmDelivIncompletionSts]
    --       ,null as [HDR_OvrlItmGdsMvtIncompletionSts]
    --       ,null as [HDR_OvrlItmGeneralIncompletionSts]
    --       ,null as [HDR_OvrlItmPackingIncompletionSts]
    --       ,null as [HDR_OvrlItmPickingIncompletionSts]
    --       ,null as [HDR_ShippingGroupNumber]
    --       ,null as [HDR_TotalNumberOfPackage]
    --       ,null as [HDR_TransactionCurrency]
    --       ,null as [Currency_EUR]
    --       ,null as [ActualDeliveryRouteName]
    --       ,null as [ActualDeliveryRouteDurationInHrs]
    --       ,null as [ProposedDeliveryRouteName]
    --       ,null as [ProposedDeliveryRouteDurationInHrs]
    --       ,null as [ActualDeliveryRouteDurationInDays]
    --       ,null as [ProposedDeliveryRouteDurationInDays]
    --       ,null as [InOutID]
    --       ,null as [SDICreationDateIsODICreationDateFlag]
    --       ,null as [IF_Total_Group]
    --       ,null as [IF_Group]
    --       ,null as [IF_IsInFullFlag]
    --       ,[IsInFull] as [IF_IsInFull]
    --       ,null as [NoActualDeliveredQtyFlag]
    --       ,null as [OTS_GoodsIssueDateDiffInDays]
    --       ,null as [OTS_DaysDiff]
    --       ,null as [OTS_GIDateCheckGroup]
    --       ,null as [OTS_Group]
    --       ,null as [SDAvailableFlag]
    --       ,null as [SDI_ConfQtyEqOrderQtyFlag]
    --       ,null as [SLAvailableFlag]
    --       ,null as [IF_DataQualityCode]
    --       ,null as [OTD_DataQualityCode]
    --       ,null as [OTS_DataQualityCode]
    --       ,null as [CalculatedDelDate]
    --       ,null as [OTD_DaysDiff]
    --       ,null as [OTD_Group]
    --       ,[DeliveredEarlyDays] as [OTD_EarlyDays]
    --       ,[IsEarlyDelivered] as [OTD_IsEarly]
    --       ,[IsLateDelivered] as [OTD_IsLate]
    --       ,[IsOnTimeDelivery] as [OTD_IsOnTime]
    --       ,[DeliveredLateDays] as [OTD_LateDays]
    --       ,null as [OTDIF_OnTimeDelInFull]
    --       ,[t_applicationId]
    --       ,[t_extractionDtm]
    --       ,@t_jobId AS t_jobId
    --       ,@t_jobDtm AS t_jobDtm
    --       ,@t_lastActionCd AS t_lastActionCd
    --       ,@t_jobBy AS t_jobBy
    --     FROM [edw].[vw_OutboundDeliveryItem_axbi];

        RENAME OBJECT [edw].[fact_OutboundDeliveryItem] TO [fact_OutboundDeliveryItem_old];
        RENAME OBJECT [edw].[fact_OutboundDeliveryItem_tmp] TO [fact_OutboundDeliveryItem];
        DROP TABLE [edw].[fact_OutboundDeliveryItem_old];

    END TRY
    BEGIN CATCH
        SET @errmessage = 'Internal error in ' + ERROR_PROCEDURE() + '. ' +  ERROR_MESSAGE();
		THROW 50001, @errmessage, 1;
    END CATCH
END
GO