CREATE PROC [edw].[sp_load_fact_ACDOCA_active]
  @t_jobId [varchar](36)
, @t_jobDtm [datetime]
, @t_jobBy [nvarchar](128)
, @t_lastActionCd [varchar](1) -- workaround with option to save single solution in DF
AS
BEGIN 
    DECLARE @errmessage NVARCHAR(2048);   
    BEGIN TRY
        update [edw].[fact_ACDOCA_active] 
            SET -- exclude[SourceLedgerID], [CompanyCodeID], [FiscalYear], [AccountingDocument], [LedgerGLLineItem] is it pk_key
              fACDOCA.[LedgerFiscalYear]                  = vw.[LedgerFiscalYear]
            , fACDOCA.[GLRecordTypeID]                    = vw.[GLRecordTypeID]
            , fACDOCA.[ChartOfAccountsID]                 = vw.[ChartOfAccountsID]
            , fACDOCA.[ControllingAreaID]                 = vw.[ControllingAreaID]
            , fACDOCA.[FinancialTransactionTypeID]        = vw.[FinancialTransactionTypeID]
            , fACDOCA.[BusinessTransactionTypeID]         = vw.[BusinessTransactionTypeID]
            , fACDOCA.[ControllingBusTransacTypeID]       = vw.[ControllingBusTransacTypeID]
            , fACDOCA.[ReferenceDocumentTypeID]           = vw.[ReferenceDocumentTypeID]
            , fACDOCA.[ReferenceDocumentContextID]        = vw.[ReferenceDocumentContextID]
            , fACDOCA.[ReferenceDocument]                 = vw.[ReferenceDocument]
            , fACDOCA.[ReferenceDocumentItem]             = vw.[ReferenceDocumentItem]
            , fACDOCA.[ReferenceDocumentItemGroupID]      = vw.[ReferenceDocumentItemGroupID]
            , fACDOCA.[IsReversal]                        = vw.[IsReversal]
            , fACDOCA.[IsReversed]                        = vw.[IsReversed]
            , fACDOCA.[PredecessorReferenceDocTypeID]     = vw.[PredecessorReferenceDocTypeID]
            , fACDOCA.[ReversalReferenceDocumentCntxtID]  = vw.[ReversalReferenceDocumentCntxtID]
            , fACDOCA.[ReversalReferenceDocument]         = vw.[ReversalReferenceDocument]
            , fACDOCA.[IsSettlement]                      = vw.[IsSettlement]
            , fACDOCA.[IsSettled]                         = vw.[IsSettled]
            , fACDOCA.[PredecessorReferenceDocument]      = vw.[PredecessorReferenceDocument]
            , fACDOCA.[PredecessorReferenceDocItem]       = vw.[PredecessorReferenceDocItem]
            , fACDOCA.[SourceReferenceDocumentTypeID]     = vw.[SourceReferenceDocumentTypeID]
            , fACDOCA.[SourceReferenceDocument]           = vw.[SourceReferenceDocument]
            , fACDOCA.[SourceReferenceDocumentItem]       = vw.[SourceReferenceDocumentItem]
            , fACDOCA.[IsCommitment]                      = vw.[IsCommitment]
            , fACDOCA.[JrnlEntryItemObsoleteReasonID]     = vw.[JrnlEntryItemObsoleteReasonID]
            , fACDOCA.[GLAccountID]                       = vw.[GLAccountID]
            , fACDOCA.[CostCenterID]                      = vw.[CostCenterID]
            , fACDOCA.[ProfitCenterID]                    = vw.[ProfitCenterID]
            , fACDOCA.[FunctionalAreaID]                  = vw.[FunctionalAreaID]
            , fACDOCA.[BusinessAreaID]                    = vw.[BusinessAreaID]
            , fACDOCA.[SegmentID]                         = vw.[SegmentID]
            , fACDOCA.[PartnerCostCenterID]               = vw.[PartnerCostCenterID]
            , fACDOCA.[PartnerProfitCenterID]             = vw.[PartnerProfitCenterID]
            , fACDOCA.[PartnerFunctionalAreaID]           = vw.[PartnerFunctionalAreaID]
            , fACDOCA.[PartnerBusinessAreaID]             = vw.[PartnerBusinessAreaID]
            , fACDOCA.[PartnerCompanyID]                  = vw.[PartnerCompanyID]
            , fACDOCA.[PartnerSegmentID]                  = vw.[PartnerSegmentID]
            , fACDOCA.[BalanceTransactionCurrency]        = vw.[BalanceTransactionCurrency]
            , fACDOCA.[AmountInBalanceTransacCrcy]        = vw.[AmountInBalanceTransacCrcy]
            , fACDOCA.[TransactionCurrency]               = vw.[TransactionCurrency]
            , fACDOCA.[AmountInTransactionCurrency]       = vw.[AmountInTransactionCurrency]
            , fACDOCA.[CompanyCodeCurrency]               = vw.[CompanyCodeCurrency]
            , fACDOCA.[AmountInCompanyCodeCurrency]       = vw.[AmountInCompanyCodeCurrency]
            , fACDOCA.[GlobalCurrency]                    = vw.[GlobalCurrency]
            , fACDOCA.[AmountInGlobalCurrency]            = vw.[AmountInGlobalCurrency]
            , fACDOCA.[FreeDefinedCurrency1]              = vw.[FreeDefinedCurrency1]
            , fACDOCA.[AmountInFreeDefinedCurrency1]      = vw.[AmountInFreeDefinedCurrency1]
            , fACDOCA.[FreeDefinedCurrency2]              = vw.[FreeDefinedCurrency2]
            , fACDOCA.[AmountInFreeDefinedCurrency2]      = vw.[AmountInFreeDefinedCurrency2]
            , fACDOCA.[BaseUnit]                          = vw.[BaseUnit]
            , fACDOCA.[Quantity]                          = vw.[Quantity]
            , fACDOCA.[DebitCreditID]                     = vw.[DebitCreditID]
            , fACDOCA.[FiscalPeriod]                      = vw.[FiscalPeriod]
            , fACDOCA.[FiscalYearVariant]                 = vw.[FiscalYearVariant]
            , fACDOCA.[FiscalYearPeriod]                  = vw.[FiscalYearPeriod]
            , fACDOCA.[PostingDate]                       = vw.[PostingDate]
            , fACDOCA.[DocumentDate]                      = vw.[DocumentDate]
            , fACDOCA.[AccountingDocumentTypeID]          = vw.[AccountingDocumentTypeID]
            , fACDOCA.[AccountingDocumentItem]            = vw.[AccountingDocumentItem]
            , fACDOCA.[AssignmentReference]               = vw.[AssignmentReference]
            , fACDOCA.[AccountingDocumentCategoryID]      = vw.[AccountingDocumentCategoryID]
            , fACDOCA.[PostingKeyID]                      = vw.[PostingKeyID]
            , fACDOCA.[TransactionTypeDeterminationID]    = vw.[TransactionTypeDeterminationID]
            , fACDOCA.[SubLedgerAcctLineItemTypeID]       = vw.[SubLedgerAcctLineItemTypeID]
            , fACDOCA.[AccountingDocCreatedByUserID]      = vw.[AccountingDocCreatedByUserID]
            , fACDOCA.[LastChangeDateTime]                = vw.[LastChangeDateTime]
            , fACDOCA.[CreationDateTime]                  = vw.[CreationDateTime]
            , fACDOCA.[CreationDate]                      = vw.[CreationDate]
            , fACDOCA.[OriginObjectTypeID]                = vw.[OriginObjectTypeID]
            , fACDOCA.[GLAccountTypeID]                   = vw.[GLAccountTypeID]
            , fACDOCA.[InvoiceReference]                  = vw.[InvoiceReference]
            , fACDOCA.[InvoiceReferenceFiscalYear]        = vw.[InvoiceReferenceFiscalYear]
            , fACDOCA.[InvoiceItemReference]              = vw.[InvoiceItemReference]
            , fACDOCA.[ReferencePurchaseOrderCategoryID]  = vw.[ReferencePurchaseOrderCategoryID]
            , fACDOCA.[PurchasingDocument]                = vw.[PurchasingDocument]
            , fACDOCA.[PurchasingDocumentItem]            = vw.[PurchasingDocumentItem]
            , fACDOCA.[AccountAssignmentNumber]           = vw.[AccountAssignmentNumber]
            , fACDOCA.[DocumentItemText]                  = vw.[DocumentItemText]
            , fACDOCA.[SalesDocumentID]                   = vw.[SalesDocumentID]
            , fACDOCA.[SalesDocumentItemID]               = vw.[SalesDocumentItemID]
            , fACDOCA.[ProductID]                         = vw.[ProductID]
            , fACDOCA.[PlantID]                           = vw.[PlantID]
            , fACDOCA.[SupplierID]                        = vw.[SupplierID]
            , fACDOCA.[CustomerID]                        = vw.[CustomerID]
            , fACDOCA.[ExchangeRateDate]                  = vw.[ExchangeRateDate]
            , fACDOCA.[FinancialAccountTypeID]            = vw.[FinancialAccountTypeID]
            , fACDOCA.[SpecialGLCodeID]                   = vw.[SpecialGLCodeID]
            , fACDOCA.[TaxCodeID]                         = vw.[TaxCodeID]
            , fACDOCA.[ClearingDate]                      = vw.[ClearingDate]
            , fACDOCA.[ClearingAccountingDocument]        = vw.[ClearingAccountingDocument]
            , fACDOCA.[ClearingDocFiscalYear]             = vw.[ClearingDocFiscalYear]
            , fACDOCA.[LineItemIsCompleted]               = vw.[LineItemIsCompleted]
            , fACDOCA.[PersonnelNumber]                   = vw.[PersonnelNumber]
            , fACDOCA.[PartnerCompanyCodeID]              = vw.[PartnerCompanyCodeID]
            , fACDOCA.[OriginProfitCenterID]              = vw.[OriginProfitCenterID]
            , fACDOCA.[OriginCostCenterID]                = vw.[OriginCostCenterID]
            , fACDOCA.[AccountAssignmentID]               = vw.[AccountAssignmentID]
            , fACDOCA.[AccountAssignmentTypeID]           = vw.[AccountAssignmentTypeID]
            , fACDOCA.[CostCtrActivityTypeID]             = vw.[CostCtrActivityTypeID]
            , fACDOCA.[OrderID]                           = vw.[OrderID]
            , fACDOCA.[OrderCategoryID]                   = vw.[OrderCategoryID]
            , fACDOCA.[WBSElementID]                      = vw.[WBSElementID]
            , fACDOCA.[ProjectInternalID]                 = vw.[ProjectInternalID]
            , fACDOCA.[ProjectID]                         = vw.[ProjectID]
            , fACDOCA.[OperatingConcernID]                = vw.[OperatingConcernID]
            , fACDOCA.[BusinessProcessID]                 = vw.[BusinessProcessID]
            , fACDOCA.[CostObjectID]                      = vw.[CostObjectID]
            , fACDOCA.[BillableControlID]                 = vw.[BillableControlID]
            , fACDOCA.[ServiceDocumentTypeID]             = vw.[ServiceDocumentTypeID]
            , fACDOCA.[ServiceDocument]                   = vw.[ServiceDocument]
            , fACDOCA.[ServiceDocumentItem]               = vw.[ServiceDocumentItem]
            , fACDOCA.[BillingDocumentTypeID]             = vw.[BillingDocumentTypeID]
            , fACDOCA.[SalesOrganizationID]               = vw.[SalesOrganizationID]
            , fACDOCA.[DistributionChannelID]             = vw.[DistributionChannelID]
            , fACDOCA.[SalesDistrictID]                   = vw.[SalesDistrictID]
            , fACDOCA.[BillToPartyID]                     = vw.[BillToPartyID]
            , fACDOCA.[t_applicationId]                   = vw.[t_applicationId]
            , fACDOCA.[t_extractionDtm]                   = vw.[t_extractionDtm]
            , fACDOCA.[t_jobId]                           =  @t_jobId 
            , fACDOCA.[t_jobDtm]                          =  @t_jobDtm 
            , fACDOCA.[t_jobBy]                           =  @t_jobBy 
            , fACDOCA.[t_lastActionBy]                    = vw.[t_lastActionBy]
            , fACDOCA.[t_lastActionCd]                    = vw.[t_lastActionCd]
            , fACDOCA.[t_lastActionDtm]                   = vw.[t_lastActionDtm]   
        FROM [edw].[fact_ACDOCA_active] AS fACDOCA
        JOIN [edw].[vw_ACDOCA_delta] AS vw  
            ON (
                fACDOCA.[SourceLedgerID] = vw.[SourceLedgerID]
            AND
                fACDOCA.[CompanyCodeID] = vw.[CompanyCodeID]
            AND
                fACDOCA.[FiscalYear] = vw.[FiscalYear]
            AND
                fACDOCA.[AccountingDocument] = vw.[AccountingDocument]
            AND
                fACDOCA.[LedgerGLLineItem] = vw.[LedgerGLLineItem]
            )

        INSERT [edw].[fact_ACDOCA_active] (
              vw.[SourceLedgerID]                   
            , vw.[CompanyCodeID]                    
            , vw.[FiscalYear]                       
            , vw.[AccountingDocument]               
            , vw.[LedgerGLLineItem]                 
            , vw.[LedgerFiscalYear]                 
            , vw.[GLRecordTypeID]                   
            , vw.[ChartOfAccountsID]                
            , vw.[ControllingAreaID]                
            , vw.[FinancialTransactionTypeID]       
            , vw.[BusinessTransactionTypeID]        
            , vw.[ControllingBusTransacTypeID]      
            , vw.[ReferenceDocumentTypeID]          
            , vw.[ReferenceDocumentContextID]       
            , vw.[ReferenceDocument]                
            , vw.[ReferenceDocumentItem]            
            , vw.[ReferenceDocumentItemGroupID]     
            , vw.[IsReversal]                       
            , vw.[IsReversed]                       
            , vw.[PredecessorReferenceDocTypeID]    
            , vw.[ReversalReferenceDocumentCntxtID] 
            , vw.[ReversalReferenceDocument]        
            , vw.[IsSettlement]                     
            , vw.[IsSettled]                        
            , vw.[PredecessorReferenceDocument]     
            , vw.[PredecessorReferenceDocItem]      
            , vw.[SourceReferenceDocumentTypeID]    
            , vw.[SourceReferenceDocument]          
            , vw.[SourceReferenceDocumentItem]      
            , vw.[IsCommitment]                     
            , vw.[JrnlEntryItemObsoleteReasonID]    
            , vw.[GLAccountID]                      
            , vw.[CostCenterID]                     
            , vw.[ProfitCenterID]                   
            , vw.[FunctionalAreaID]                 
            , vw.[BusinessAreaID]                   
            , vw.[SegmentID]                        
            , vw.[PartnerCostCenterID]              
            , vw.[PartnerProfitCenterID]            
            , vw.[PartnerFunctionalAreaID]          
            , vw.[PartnerBusinessAreaID]            
            , vw.[PartnerCompanyID]                 
            , vw.[PartnerSegmentID]                 
            , vw.[BalanceTransactionCurrency]       
            , vw.[AmountInBalanceTransacCrcy]       
            , vw.[TransactionCurrency]              
            , vw.[AmountInTransactionCurrency]      
            , vw.[CompanyCodeCurrency]              
            , vw.[AmountInCompanyCodeCurrency]      
            , vw.[GlobalCurrency]                   
            , vw.[AmountInGlobalCurrency]           
            , vw.[FreeDefinedCurrency1]             
            , vw.[AmountInFreeDefinedCurrency1]     
            , vw.[FreeDefinedCurrency2]             
            , vw.[AmountInFreeDefinedCurrency2]     
            , vw.[BaseUnit]                         
            , vw.[Quantity]                         
            , vw.[DebitCreditID]                    
            , vw.[FiscalPeriod]                     
            , vw.[FiscalYearVariant]                
            , vw.[FiscalYearPeriod]                 
            , vw.[PostingDate]                      
            , vw.[DocumentDate]                     
            , vw.[AccountingDocumentTypeID]         
            , vw.[AccountingDocumentItem]           
            , vw.[AssignmentReference]              
            , vw.[AccountingDocumentCategoryID]     
            , vw.[PostingKeyID]                     
            , vw.[TransactionTypeDeterminationID]   
            , vw.[SubLedgerAcctLineItemTypeID]      
            , vw.[AccountingDocCreatedByUserID]     
            , vw.[LastChangeDateTime]               
            , vw.[CreationDateTime]                 
            , vw.[CreationDate]                     
            , vw.[OriginObjectTypeID]               
            , vw.[GLAccountTypeID]                  
            , vw.[InvoiceReference]                 
            , vw.[InvoiceReferenceFiscalYear]       
            , vw.[InvoiceItemReference]             
            , vw.[ReferencePurchaseOrderCategoryID] 
            , vw.[PurchasingDocument]               
            , vw.[PurchasingDocumentItem]           
            , vw.[AccountAssignmentNumber]          
            , vw.[DocumentItemText]                 
            , vw.[SalesDocumentID]                  
            , vw.[SalesDocumentItemID]              
            , vw.[ProductID]                        
            , vw.[PlantID]                          
            , vw.[SupplierID]                       
            , vw.[CustomerID]                       
            , vw.[ExchangeRateDate]                 
            , vw.[FinancialAccountTypeID]           
            , vw.[SpecialGLCodeID]                  
            , vw.[TaxCodeID]                        
            , vw.[ClearingDate]                     
            , vw.[ClearingAccountingDocument]       
            , vw.[ClearingDocFiscalYear]            
            , vw.[LineItemIsCompleted]              
            , vw.[PersonnelNumber]                  
            , vw.[PartnerCompanyCodeID]             
            , vw.[OriginProfitCenterID]             
            , vw.[OriginCostCenterID]               
            , vw.[AccountAssignmentID]              
            , vw.[AccountAssignmentTypeID]          
            , vw.[CostCtrActivityTypeID]            
            , vw.[OrderID]                          
            , vw.[OrderCategoryID]                  
            , vw.[WBSElementID]                     
            , vw.[ProjectInternalID]                
            , vw.[ProjectID]                        
            , vw.[OperatingConcernID]               
            , vw.[BusinessProcessID]                
            , vw.[CostObjectID]                     
            , vw.[BillableControlID]                
            , vw.[ServiceDocumentTypeID]            
            , vw.[ServiceDocument]                  
            , vw.[ServiceDocumentItem]              
            , vw.[BillingDocumentTypeID]            
            , vw.[SalesOrganizationID]              
            , vw.[DistributionChannelID]            
            , vw.[SalesDistrictID]                  
            , vw.[BillToPartyID]                    
            , vw.[t_applicationId] 
            , vw.[t_extractionDtm] 
            , vw.[t_jobId]         
            , vw.[t_jobDtm]        
            , vw.[t_jobBy]         
            , vw.[t_lastActionBy]  
            , vw.[t_lastActionCd]  
            , vw.[t_lastActionDtm])
        SELECT
              vw.[SourceLedgerID]                   
            , vw.[CompanyCodeID]                    
            , vw.[FiscalYear]                       
            , vw.[AccountingDocument]               
            , vw.[LedgerGLLineItem]                 
            , vw.[LedgerFiscalYear]                 
            , vw.[GLRecordTypeID]                   
            , vw.[ChartOfAccountsID]                
            , vw.[ControllingAreaID]                
            , vw.[FinancialTransactionTypeID]       
            , vw.[BusinessTransactionTypeID]        
            , vw.[ControllingBusTransacTypeID]      
            , vw.[ReferenceDocumentTypeID]          
            , vw.[ReferenceDocumentContextID]       
            , vw.[ReferenceDocument]                
            , vw.[ReferenceDocumentItem]            
            , vw.[ReferenceDocumentItemGroupID]     
            , vw.[IsReversal]                       
            , vw.[IsReversed]                       
            , vw.[PredecessorReferenceDocTypeID]    
            , vw.[ReversalReferenceDocumentCntxtID] 
            , vw.[ReversalReferenceDocument]        
            , vw.[IsSettlement]                     
            , vw.[IsSettled]                        
            , vw.[PredecessorReferenceDocument]     
            , vw.[PredecessorReferenceDocItem]      
            , vw.[SourceReferenceDocumentTypeID]    
            , vw.[SourceReferenceDocument]          
            , vw.[SourceReferenceDocumentItem]      
            , vw.[IsCommitment]                     
            , vw.[JrnlEntryItemObsoleteReasonID]    
            , vw.[GLAccountID]                      
            , vw.[CostCenterID]                     
            , vw.[ProfitCenterID]                   
            , vw.[FunctionalAreaID]                 
            , vw.[BusinessAreaID]                
            , vw.[SegmentID]                        
            , vw.[PartnerCostCenterID]              
            , vw.[PartnerProfitCenterID]            
            , vw.[PartnerFunctionalAreaID]          
            , vw.[PartnerBusinessAreaID]            
            , vw.[PartnerCompanyID]                 
            , vw.[PartnerSegmentID]                 
            , vw.[BalanceTransactionCurrency]       
            , vw.[AmountInBalanceTransacCrcy]       
            , vw.[TransactionCurrency]              
            , vw.[AmountInTransactionCurrency]      
            , vw.[CompanyCodeCurrency]              
            , vw.[AmountInCompanyCodeCurrency]      
            , vw.[GlobalCurrency]                   
            , vw.[AmountInGlobalCurrency]           
            , vw.[FreeDefinedCurrency1]             
            , vw.[AmountInFreeDefinedCurrency1]     
            , vw.[FreeDefinedCurrency2]             
            , vw.[AmountInFreeDefinedCurrency2]     
            , vw.[BaseUnit]                         
            , vw.[Quantity]                         
            , vw.[DebitCreditID]                    
            , vw.[FiscalPeriod]                     
            , vw.[FiscalYearVariant]                
            , vw.[FiscalYearPeriod]                 
            , vw.[PostingDate]                      
            , vw.[DocumentDate]                     
            , vw.[AccountingDocumentTypeID]         
            , vw.[AccountingDocumentItem]           
            , vw.[AssignmentReference]              
            , vw.[AccountingDocumentCategoryID]     
            , vw.[PostingKeyID]                     
            , vw.[TransactionTypeDeterminationID]   
            , vw.[SubLedgerAcctLineItemTypeID]      
            , vw.[AccountingDocCreatedByUserID]     
            , vw.[LastChangeDateTime]               
            , vw.[CreationDateTime]                 
            , vw.[CreationDate]                     
            , vw.[OriginObjectTypeID]               
            , vw.[GLAccountTypeID]                  
            , vw.[InvoiceReference]                 
            , vw.[InvoiceReferenceFiscalYear]       
            , vw.[InvoiceItemReference]             
            , vw.[ReferencePurchaseOrderCategoryID] 
            , vw.[PurchasingDocument]               
            , vw.[PurchasingDocumentItem]           
            , vw.[AccountAssignmentNumber]          
            , vw.[DocumentItemText]                 
            , vw.[SalesDocumentID]                  
            , vw.[SalesDocumentItemID]              
            , vw.[ProductID]                        
            , vw.[PlantID]                          
            , vw.[SupplierID]                       
            , vw.[CustomerID]                       
            , vw.[ExchangeRateDate]                 
            , vw.[FinancialAccountTypeID]           
            , vw.[SpecialGLCodeID]                  
            , vw.[TaxCodeID]                        
            , vw.[ClearingDate]                     
            , vw.[ClearingAccountingDocument]       
            , vw.[ClearingDocFiscalYear]            
            , vw.[LineItemIsCompleted]              
            , vw.[PersonnelNumber]                  
            , vw.[PartnerCompanyCodeID]             
            , vw.[OriginProfitCenterID]             
            , vw.[OriginCostCenterID]               
            , vw.[AccountAssignmentID]              
            , vw.[AccountAssignmentTypeID]          
            , vw.[CostCtrActivityTypeID]            
            , vw.[OrderID]                          
            , vw.[OrderCategoryID]                  
            , vw.[WBSElementID]                     
            , vw.[ProjectInternalID]                
            , vw.[ProjectID]                        
            , vw.[OperatingConcernID]               
            , vw.[BusinessProcessID]                
            , vw.[CostObjectID]                     
            , vw.[BillableControlID]                
            , vw.[ServiceDocumentTypeID]            
            , vw.[ServiceDocument]                  
            , vw.[ServiceDocumentItem]              
            , vw.[BillingDocumentTypeID]            
            , vw.[SalesOrganizationID]              
            , vw.[DistributionChannelID]            
            , vw.[SalesDistrictID]                  
            , vw.[BillToPartyID]    
            , @t_jobId
            , @t_jobDtm
            , @t_jobBy
            , vw.[t_lastActionBy]  
            , vw.[t_lastActionCd]  
            , vw.[t_lastActionDtm]                             
            FROM [edw].[vw_ACDOCA_delta] AS vw
        WHERE NOT EXISTS (
            SELECT 1 FROM [edw].[fact_ACDOCA_active]  
            WHERE
                [SourceLedgerID] = vw.[SourceLedgerID]
            AND
                [CompanyCodeID] = vw.[CompanyCodeID]
            AND
                [FiscalYear] = vw.[FiscalYear]
            AND
                [AccountingDocument] = vw.[AccountingDocument]
            AND
                [LedgerGLLineItem] = vw.[LedgerGLLineItem]
        );        
    END TRY
    BEGIN CATCH
        SET @errmessage = 'Internal error in ' + ERROR_PROCEDURE() + '. ' +  ERROR_MESSAGE();
		THROW 50001, @errmessage, 1;
    END CATCH
END       