CREATE PROC [edw].[sp_load_fact_ACDOCA_active]
  @t_jobId [varchar](36)
, @t_jobDtm [datetime]
, @t_jobBy [nvarchar](128)
, @t_lastActionCd [varchar](1) -- workaround with option to save single solution in DF
AS
BEGIN 
    DECLARE @errmessage NVARCHAR(2048);   
    BEGIN TRY
        update [edw].[fact_ACDOCA_active] 
            SET -- exclude[SourceLedgerID], [CompanyCodeID], [FiscalYear], [AccountingDocument], [LedgerGLLineItem] is it pk_key
              [LedgerFiscalYear]                  = vw.[LedgerFiscalYear]
            , [GLRecordTypeID]                    = vw.[GLRecordTypeID]
            , [ChartOfAccountsID]                 = vw.[ChartOfAccountsID]
            , [ControllingAreaID]                 = vw.[ControllingAreaID]
            , [FinancialTransactionTypeID]        = vw.[FinancialTransactionTypeID]
            , [BusinessTransactionTypeID]         = vw.[BusinessTransactionTypeID]
            , [ControllingBusTransacTypeID]       = vw.[ControllingBusTransacTypeID]
            , [ReferenceDocumentTypeID]           = vw.[ReferenceDocumentTypeID]
            , [ReferenceDocumentContextID]        = vw.[ReferenceDocumentContextID]
            , [ReferenceDocument]                 = vw.[ReferenceDocument]
            , [ReferenceDocumentItem]             = vw.[ReferenceDocumentItem]
            , [ReferenceDocumentItemGroupID]      = vw.[ReferenceDocumentItemGroupID]
            , [IsReversal]                        = vw.[IsReversal]
            , [IsReversed]                        = vw.[IsReversed]
            , [PredecessorReferenceDocTypeID]     = vw.[PredecessorReferenceDocTypeID]
            , [ReversalReferenceDocumentCntxtID]  = vw.[ReversalReferenceDocumentCntxtID]
            , [ReversalReferenceDocument]         = vw.[ReversalReferenceDocument]
            , [IsSettlement]                      = vw.[IsSettlement]
            , [IsSettled]                         = vw.[IsSettled]
            , [PredecessorReferenceDocument]      = vw.[PredecessorReferenceDocument]
            , [PredecessorReferenceDocItem]       = vw.[PredecessorReferenceDocItem]
            , [SourceReferenceDocumentTypeID]     = vw.[SourceReferenceDocumentTypeID]
            , [SourceReferenceDocument]           = vw.[SourceReferenceDocument]
            , [SourceReferenceDocumentItem]       = vw.[SourceReferenceDocumentItem]
            , [IsCommitment]                      = vw.[IsCommitment]
            , [JrnlEntryItemObsoleteReasonID]     = vw.[JrnlEntryItemObsoleteReasonID]
            , [GLAccountID]                       = vw.[GLAccountID]
            , [CostCenterID]                      = vw.[CostCenterID]
            , [ProfitCenterID]                    = vw.[ProfitCenterID]
            , [FunctionalAreaID]                  = vw.[FunctionalAreaID]
            , [BusinessAreaID]                    = vw.[BusinessAreaID]
            , [SegmentID]                         = vw.[SegmentID]
            , [PartnerCostCenterID]               = vw.[PartnerCostCenterID]
            , [PartnerProfitCenterID]             = vw.[PartnerProfitCenterID]
            , [PartnerFunctionalAreaID]           = vw.[PartnerFunctionalAreaID]
            , [PartnerBusinessAreaID]             = vw.[PartnerBusinessAreaID]
            , [PartnerCompanyID]                  = vw.[PartnerCompanyID]
            , [PartnerSegmentID]                  = vw.[PartnerSegmentID]
            , [BalanceTransactionCurrency]        = vw.[BalanceTransactionCurrency]
            , [AmountInBalanceTransacCrcy]        = vw.[AmountInBalanceTransacCrcy]
            , [TransactionCurrency]               = vw.[TransactionCurrency]
            , [AmountInTransactionCurrency]       = vw.[AmountInTransactionCurrency]
            , [CompanyCodeCurrency]               = vw.[CompanyCodeCurrency]
            , [AmountInCompanyCodeCurrency]       = vw.[AmountInCompanyCodeCurrency]
            , [GlobalCurrency]                    = vw.[GlobalCurrency]
            , [AmountInGlobalCurrency]            = vw.[AmountInGlobalCurrency]
            , [FreeDefinedCurrency1]              = vw.[FreeDefinedCurrency1]
            , [AmountInFreeDefinedCurrency1]      = vw.[AmountInFreeDefinedCurrency1]
            , [FreeDefinedCurrency2]              = vw.[FreeDefinedCurrency2]
            , [AmountInFreeDefinedCurrency2]      = vw.[AmountInFreeDefinedCurrency2]
            , [BaseUnit]                          = vw.[BaseUnit]
            , [Quantity]                          = vw.[Quantity]
            , [DebitCreditID]                     = vw.[DebitCreditID]
            , [FiscalPeriod]                      = vw.[FiscalPeriod]
            , [FiscalYearVariant]                 = vw.[FiscalYearVariant]
            , [FiscalYearPeriod]                  = vw.[FiscalYearPeriod]
            , [PostingDate]                       = vw.[PostingDate]
            , [DocumentDate]                      = vw.[DocumentDate]
            , [AccountingDocumentTypeID]          = vw.[AccountingDocumentTypeID]
            , [AccountingDocumentItem]            = vw.[AccountingDocumentItem]
            , [AssignmentReference]               = vw.[AssignmentReference]
            , [AccountingDocumentCategoryID]      = vw.[AccountingDocumentCategoryID]
            , [PostingKeyID]                      = vw.[PostingKeyID]
            , [TransactionTypeDeterminationID]    = vw.[TransactionTypeDeterminationID]
            , [SubLedgerAcctLineItemTypeID]       = vw.[SubLedgerAcctLineItemTypeID]
            , [AccountingDocCreatedByUserID]      = vw.[AccountingDocCreatedByUserID]
            , [LastChangeDateTime]                = vw.[LastChangeDateTime]
            , [CreationDateTime]                  = vw.[CreationDateTime]
            , [CreationDate]                      = vw.[CreationDate]
            , [OriginObjectTypeID]                = vw.[OriginObjectTypeID]
            , [GLAccountTypeID]                   = vw.[GLAccountTypeID]
            , [InvoiceReference]                  = vw.[InvoiceReference]
            , [InvoiceReferenceFiscalYear]        = vw.[InvoiceReferenceFiscalYear]
            , [InvoiceItemReference]              = vw.[InvoiceItemReference]
            , [ReferencePurchaseOrderCategoryID]  = vw.[ReferencePurchaseOrderCategoryID]
            , [PurchasingDocument]                = vw.[PurchasingDocument]
            , [PurchasingDocumentItem]            = vw.[PurchasingDocumentItem]
            , [AccountAssignmentNumber]           = vw.[AccountAssignmentNumber]
            , [DocumentItemText]                  = vw.[DocumentItemText]
            , [SalesDocumentID]                   = vw.[SalesDocumentID]
            , [SalesDocumentItemID]               = vw.[SalesDocumentItemID]
            , [ProductID]                         = vw.[ProductID]
            , [PlantID]                           = vw.[PlantID]
            , [SupplierID]                        = vw.[SupplierID]
            , [CustomerID]                        = vw.[CustomerID]
            , [ExchangeRateDate]                  = vw.[ExchangeRateDate]
            , [FinancialAccountTypeID]            = vw.[FinancialAccountTypeID]
            , [SpecialGLCodeID]                   = vw.[SpecialGLCodeID]
            , [TaxCodeID]                         = vw.[TaxCodeID]
            , [ClearingDate]                      = vw.[ClearingDate]
            , [ClearingAccountingDocument]        = vw.[ClearingAccountingDocument]
            , [ClearingDocFiscalYear]             = vw.[ClearingDocFiscalYear]
            , [LineItemIsCompleted]               = vw.[LineItemIsCompleted]
            , [PersonnelNumber]                   = vw.[PersonnelNumber]
            , [PartnerCompanyCodeID]              = vw.[PartnerCompanyCodeID]
            , [OriginProfitCenterID]              = vw.[OriginProfitCenterID]
            , [OriginCostCenterID]                = vw.[OriginCostCenterID]
            , [AccountAssignmentID]               = vw.[AccountAssignmentID]
            , [AccountAssignmentTypeID]           = vw.[AccountAssignmentTypeID]
            , [CostCtrActivityTypeID]             = vw.[CostCtrActivityTypeID]
            , [OrderID]                           = vw.[OrderID]
            , [OrderCategoryID]                   = vw.[OrderCategoryID]
            , [WBSElementID]                      = vw.[WBSElementID]
            , [ProjectInternalID]                 = vw.[ProjectInternalID]
            , [ProjectID]                         = vw.[ProjectID]
            , [OperatingConcernID]                = vw.[OperatingConcernID]
            , [BusinessProcessID]                 = vw.[BusinessProcessID]
            , [CostObjectID]                      = vw.[CostObjectID]
            , [BillableControlID]                 = vw.[BillableControlID]
            , [ServiceDocumentTypeID]             = vw.[ServiceDocumentTypeID]
            , [ServiceDocument]                   = vw.[ServiceDocument]
            , [ServiceDocumentItem]               = vw.[ServiceDocumentItem]
            , [BillingDocumentTypeID]             = vw.[BillingDocumentTypeID]
            , [SalesOrganizationID]               = vw.[SalesOrganizationID]
            , [DistributionChannelID]             = vw.[DistributionChannelID]
            , [SalesDistrictID]                   = vw.[SalesDistrictID]
            , [BillToPartyID]                     = vw.[BillToPartyID]
            , [t_applicationId]                   = vw.[t_applicationId]
            , [t_extractionDtm]                   = vw.[t_extractionDtm]
            , [t_jobId]                           =  @t_jobId 
            , [t_jobDtm]                          =  @t_jobDtm 
            , [t_jobBy]                           =  @t_jobBy 
            , [t_lastActionBy]                    = vw.[t_lastActionBy]
            , [t_lastActionCd]                    = vw.[t_lastActionCd]
            , [t_lastActionDtm]                   = vw.[t_lastActionDtm]   
        FROM [edw].[fact_ACDOCA_active] AS fACDOCA
        JOIN [edw].[vw_ACDOCA_delta] AS vw  
            ON (
                fACDOCA.[SourceLedgerID] = vw.[SourceLedgerID]
            AND
                fACDOCA.[CompanyCodeID] = vw.[CompanyCodeID]
            AND
                fACDOCA.[FiscalYear] = vw.[FiscalYear]
            AND
                fACDOCA.[AccountingDocument] = vw.[AccountingDocument]
            AND
                fACDOCA.[LedgerGLLineItem] = vw.[LedgerGLLineItem]
            )

        INSERT [edw].[fact_ACDOCA_active] (
              vw.[SourceLedgerID]                   
            , vw.[CompanyCodeID]                    
            , vw.[FiscalYear]                       
            , vw.[AccountingDocument]               
            , vw.[LedgerGLLineItem]                 
            , vw.[LedgerFiscalYear]                 
            , vw.[GLRecordTypeID]                   
            , vw.[ChartOfAccountsID]                
            , vw.[ControllingAreaID]                
            , vw.[FinancialTransactionTypeID]       
            , vw.[BusinessTransactionTypeID]        
            , vw.[ControllingBusTransacTypeID]      
            , vw.[ReferenceDocumentTypeID]          
            , vw.[ReferenceDocumentContextID]       
            , vw.[ReferenceDocument]                
            , vw.[ReferenceDocumentItem]            
            , vw.[ReferenceDocumentItemGroupID]     
            , vw.[IsReversal]                       
            , vw.[IsReversed]                       
            , vw.[PredecessorReferenceDocTypeID]    
            , vw.[ReversalReferenceDocumentCntxtID] 
            , vw.[ReversalReferenceDocument]        
            , vw.[IsSettlement]                     
            , vw.[IsSettled]                        
            , vw.[PredecessorReferenceDocument]     
            , vw.[PredecessorReferenceDocItem]      
            , vw.[SourceReferenceDocumentTypeID]    
            , vw.[SourceReferenceDocument]          
            , vw.[SourceReferenceDocumentItem]      
            , vw.[IsCommitment]                     
            , vw.[JrnlEntryItemObsoleteReasonID]    
            , vw.[GLAccountID]                      
            , vw.[CostCenterID]                     
            , vw.[ProfitCenterID]                   
            , vw.[FunctionalAreaID]                 
            , vw.[BusinessAreaID]                   
            , vw.[SegmentID]                        
            , vw.[PartnerCostCenterID]              
            , vw.[PartnerProfitCenterID]            
            , vw.[PartnerFunctionalAreaID]          
            , vw.[PartnerBusinessAreaID]            
            , vw.[PartnerCompanyID]                 
            , vw.[PartnerSegmentID]                 
            , vw.[BalanceTransactionCurrency]       
            , vw.[AmountInBalanceTransacCrcy]       
            , vw.[TransactionCurrency]              
            , vw.[AmountInTransactionCurrency]      
            , vw.[CompanyCodeCurrency]              
            , vw.[AmountInCompanyCodeCurrency]      
            , vw.[GlobalCurrency]                   
            , vw.[AmountInGlobalCurrency]           
            , vw.[FreeDefinedCurrency1]             
            , vw.[AmountInFreeDefinedCurrency1]     
            , vw.[FreeDefinedCurrency2]             
            , vw.[AmountInFreeDefinedCurrency2]     
            , vw.[BaseUnit]                         
            , vw.[Quantity]                         
            , vw.[DebitCreditID]                    
            , vw.[FiscalPeriod]                     
            , vw.[FiscalYearVariant]                
            , vw.[FiscalYearPeriod]                 
            , vw.[PostingDate]                      
            , vw.[DocumentDate]                     
            , vw.[AccountingDocumentTypeID]         
            , vw.[AccountingDocumentItem]           
            , vw.[AssignmentReference]              
            , vw.[AccountingDocumentCategoryID]     
            , vw.[PostingKeyID]                     
            , vw.[TransactionTypeDeterminationID]   
            , vw.[SubLedgerAcctLineItemTypeID]      
            , vw.[AccountingDocCreatedByUserID]     
            , vw.[LastChangeDateTime]               
            , vw.[CreationDateTime]                 
            , vw.[CreationDate]                     
            , vw.[OriginObjectTypeID]               
            , vw.[GLAccountTypeID]                  
            , vw.[InvoiceReference]                 
            , vw.[InvoiceReferenceFiscalYear]       
            , vw.[InvoiceItemReference]             
            , vw.[ReferencePurchaseOrderCategoryID] 
            , vw.[PurchasingDocument]               
            , vw.[PurchasingDocumentItem]           
            , vw.[AccountAssignmentNumber]          
            , vw.[DocumentItemText]                 
            , vw.[SalesDocumentID]                  
            , vw.[SalesDocumentItemID]              
            , vw.[ProductID]                        
            , vw.[PlantID]                          
            , vw.[SupplierID]                       
            , vw.[CustomerID]                       
            , vw.[ExchangeRateDate]                 
            , vw.[FinancialAccountTypeID]           
            , vw.[SpecialGLCodeID]                  
            , vw.[TaxCodeID]                        
            , vw.[ClearingDate]                     
            , vw.[ClearingAccountingDocument]       
            , vw.[ClearingDocFiscalYear]            
            , vw.[LineItemIsCompleted]              
            , vw.[PersonnelNumber]                  
            , vw.[PartnerCompanyCodeID]             
            , vw.[OriginProfitCenterID]             
            , vw.[OriginCostCenterID]               
            , vw.[AccountAssignmentID]              
            , vw.[AccountAssignmentTypeID]          
            , vw.[CostCtrActivityTypeID]            
            , vw.[OrderID]                          
            , vw.[OrderCategoryID]                  
            , vw.[WBSElementID]                     
            , vw.[ProjectInternalID]                
            , vw.[ProjectID]                        
            , vw.[OperatingConcernID]               
            , vw.[BusinessProcessID]                
            , vw.[CostObjectID]                     
            , vw.[BillableControlID]                
            , vw.[ServiceDocumentTypeID]            
            , vw.[ServiceDocument]                  
            , vw.[ServiceDocumentItem]              
            , vw.[BillingDocumentTypeID]            
            , vw.[SalesOrganizationID]              
            , vw.[DistributionChannelID]            
            , vw.[SalesDistrictID]                  
            , vw.[BillToPartyID]                    
            , vw.[t_applicationId] 
            , vw.[t_extractionDtm] 
            , vw.[t_jobId]         
            , vw.[t_jobDtm]        
            , vw.[t_jobBy]         
            , vw.[t_lastActionBy]  
            , vw.[t_lastActionCd]  
            , vw.[t_lastActionDtm])
            
        SELECT
              vw.[SourceLedgerID]                   
            , vw.[CompanyCodeID]                    
            , vw.[FiscalYear]                       
            , vw.[AccountingDocument]               
            , vw.[LedgerGLLineItem]                 
            , vw.[LedgerFiscalYear]                 
            , vw.[GLRecordTypeID]                   
            , vw.[ChartOfAccountsID]                
            , vw.[ControllingAreaID]                
            , vw.[FinancialTransactionTypeID]       
            , vw.[BusinessTransactionTypeID]        
            , vw.[ControllingBusTransacTypeID]      
            , vw.[ReferenceDocumentTypeID]          
            , vw.[ReferenceDocumentContextID]       
            , vw.[ReferenceDocument]                
            , vw.[ReferenceDocumentItem]            
            , vw.[ReferenceDocumentItemGroupID]     
            , vw.[IsReversal]                       
            , vw.[IsReversed]                       
            , vw.[PredecessorReferenceDocTypeID]    
            , vw.[ReversalReferenceDocumentCntxtID] 
            , vw.[ReversalReferenceDocument]        
            , vw.[IsSettlement]                     
            , vw.[IsSettled]                        
            , vw.[PredecessorReferenceDocument]     
            , vw.[PredecessorReferenceDocItem]      
            , vw.[SourceReferenceDocumentTypeID]    
            , vw.[SourceReferenceDocument]          
            , vw.[SourceReferenceDocumentItem]      
            , vw.[IsCommitment]                     
            , vw.[JrnlEntryItemObsoleteReasonID]    
            , vw.[GLAccountID]                      
            , vw.[CostCenterID]                     
            , vw.[ProfitCenterID]                   
            , vw.[FunctionalAreaID]                 
            , vw.[BusinessAreaID]                
            , vw.[SegmentID]                        
            , vw.[PartnerCostCenterID]              
            , vw.[PartnerProfitCenterID]            
            , vw.[PartnerFunctionalAreaID]          
            , vw.[PartnerBusinessAreaID]            
            , vw.[PartnerCompanyID]                 
            , vw.[PartnerSegmentID]                 
            , vw.[BalanceTransactionCurrency]       
            , vw.[AmountInBalanceTransacCrcy]       
            , vw.[TransactionCurrency]              
            , vw.[AmountInTransactionCurrency]      
            , vw.[CompanyCodeCurrency]              
            , vw.[AmountInCompanyCodeCurrency]      
            , vw.[GlobalCurrency]                   
            , vw.[AmountInGlobalCurrency]           
            , vw.[FreeDefinedCurrency1]             
            , vw.[AmountInFreeDefinedCurrency1]     
            , vw.[FreeDefinedCurrency2]             
            , vw.[AmountInFreeDefinedCurrency2]     
            , vw.[BaseUnit]                         
            , vw.[Quantity]                         
            , vw.[DebitCreditID]                    
            , vw.[FiscalPeriod]                     
            , vw.[FiscalYearVariant]                
            , vw.[FiscalYearPeriod]                 
            , vw.[PostingDate]                      
            , vw.[DocumentDate]                     
            , vw.[AccountingDocumentTypeID]         
            , vw.[AccountingDocumentItem]           
            , vw.[AssignmentReference]              
            , vw.[AccountingDocumentCategoryID]     
            , vw.[PostingKeyID]                     
            , vw.[TransactionTypeDeterminationID]   
            , vw.[SubLedgerAcctLineItemTypeID]      
            , vw.[AccountingDocCreatedByUserID]     
            , vw.[LastChangeDateTime]               
            , vw.[CreationDateTime]                 
            , vw.[CreationDate]                     
            , vw.[OriginObjectTypeID]               
            , vw.[GLAccountTypeID]                  
            , vw.[InvoiceReference]                 
            , vw.[InvoiceReferenceFiscalYear]       
            , vw.[InvoiceItemReference]             
            , vw.[ReferencePurchaseOrderCategoryID] 
            , vw.[PurchasingDocument]               
            , vw.[PurchasingDocumentItem]           
            , vw.[AccountAssignmentNumber]          
            , vw.[DocumentItemText]                 
            , vw.[SalesDocumentID]                  
            , vw.[SalesDocumentItemID]              
            , vw.[ProductID]                        
            , vw.[PlantID]                          
            , vw.[SupplierID]                       
            , vw.[CustomerID]                       
            , vw.[ExchangeRateDate]                 
            , vw.[FinancialAccountTypeID]           
            , vw.[SpecialGLCodeID]                  
            , vw.[TaxCodeID]                        
            , vw.[ClearingDate]                     
            , vw.[ClearingAccountingDocument]       
            , vw.[ClearingDocFiscalYear]            
            , vw.[LineItemIsCompleted]              
            , vw.[PersonnelNumber]                  
            , vw.[PartnerCompanyCodeID]             
            , vw.[OriginProfitCenterID]             
            , vw.[OriginCostCenterID]               
            , vw.[AccountAssignmentID]              
            , vw.[AccountAssignmentTypeID]          
            , vw.[CostCtrActivityTypeID]            
            , vw.[OrderID]                          
            , vw.[OrderCategoryID]                  
            , vw.[WBSElementID]                     
            , vw.[ProjectInternalID]                
            , vw.[ProjectID]                        
            , vw.[OperatingConcernID]               
            , vw.[BusinessProcessID]                
            , vw.[CostObjectID]                     
            , vw.[BillableControlID]                
            , vw.[ServiceDocumentTypeID]            
            , vw.[ServiceDocument]                  
            , vw.[ServiceDocumentItem]              
            , vw.[BillingDocumentTypeID]            
            , vw.[SalesOrganizationID]              
            , vw.[DistributionChannelID]            
            , vw.[SalesDistrictID]                  
            , vw.[BillToPartyID] 
            , vw.[t_applicationId] 
            , vw.[t_extractionDtm] 
            , @t_jobId
            , @t_jobDtm
            , @t_jobBy       
            , vw.[t_lastActionBy]  
            , vw.[t_lastActionCd]  
            , vw.[t_lastActionDtm]                                       
            FROM [edw].[vw_ACDOCA_delta] AS vw
        WHERE NOT EXISTS (
            SELECT 1 FROM [edw].[fact_ACDOCA_active]  
            WHERE
                [SourceLedgerID] = vw.[SourceLedgerID]
            AND
                [CompanyCodeID] = vw.[CompanyCodeID]
            AND
                [FiscalYear] = vw.[FiscalYear]
            AND
                [AccountingDocument] = vw.[AccountingDocument]
            AND
                [LedgerGLLineItem] = vw.[LedgerGLLineItem]
        );        
    END TRY
    BEGIN CATCH
        SET @errmessage = 'Internal error in ' + ERROR_PROCEDURE() + '. ' +  ERROR_MESSAGE();
		THROW 50001, @errmessage, 1;
    END CATCH
END       