CREATE TABLE [base_dw_halfen_2_dwh].[FACT_HGDAWA_Archive]
(
	[DW_Id] [bigint] NOT NULL,
	[Company] [nvarchar](8) NULL,
	[Distributioncompany] [nvarchar](8) NULL,
	[Salesarea] [nvarchar](3) NULL,
	[Inside_Outside] [nvarchar](1) NULL,
	[Inside_Outside-Text] [varchar](50) NULL,
	[Site] [nvarchar](8) NULL,
	[Invoiceno] [char](20) NULL,
	[Invoicedate] [datetime] NULL,
	[Accountingdate] [datetime] NULL,
	[Year] [bigint] NULL,
	[Month] [bigint] NULL,
	[Day] [bigint] NULL,
	[Orderno] [char](20) NULL,
	[Deliveryno] [char](20) NULL,
	[Posno] [decimal](38, 12) NULL,
	[Orderdate] [datetime] NULL,
	[Deldateplan] [datetime] NULL,
	[Deldateconfirmed] [datetime] NULL,
	[Deldateact] [datetime] NULL,
	[SalesType] [bigint] NULL,
	[Customerno] [nvarchar](10) NULL,
	[Country] [char](3) NULL,
	[Postalcode] [char](10) NULL,
	[DlvCountry] [nvarchar](10) NULL,
	[DlvState] [nvarchar](20) NULL,
	[DlvCounty] [nvarchar](20) NULL,
	[Mainsalesperson] [nvarchar](2) NULL,
	[Salesperson] [nvarchar](10) NULL,
	[Maindistrict] [nchar](2) NULL,
	[Salesdistrict] [nvarchar](10) NULL,
	[Lineofbusiness] [char](10) NULL,
	[Concern] [char](10) NULL,
	[I_E_V] [nvarchar](1) NULL,
	[I_E_V-Text] [varchar](20) NULL,
	[Responsible] [char](10) NULL,
	[Warehouse] [nvarchar](6) NULL,
	[Aquisitioncode] [char](1) NULL,
	[Aquisitioncode-Text] [varchar](40) NULL,
	[Originwarehouse] [nvarchar](6) NULL,
	[OriginAquisitioncode] [char](1) NULL,
	[OriginAquisitioncode-Text] [varchar](50) NULL,
	[Itemno] [nvarchar](20) NULL,
	[Productsub_group] [nvarchar](20) NULL,
	[Itemtype] [char](3) NULL,
	[Productgroup] [nvarchar](20) NULL,
	[Productline] [nvarchar](20) NULL,
	[Productrange] [nvarchar](20) NULL,
	[CRHProductGroupID] [nvarchar](10) NULL,
	[Production_Purchase] [char](1) NULL,
	[Stainlesssteelflag] [nvarchar](1) NULL,
	[Stainlesssteel-Text] [varchar](25) NULL,
	[MainProductclass] [varchar](5) NULL,
	[Productclass] [nvarchar](20) NULL,
	[Configno] [decimal](38, 0) NULL,
	[Pricelistno] [char](10) NULL,
	[Projectno] [nvarchar](20) NULL,
	[ProjectPos] [nvarchar](10) NULL,
	[Kitheaderno] [char](20) NULL,
	[Bruttosaleslocal] [decimal](38, 2) NULL,
	[BruttosalesCRHEUR] [decimal](38, 2) NULL,
	[Brutto2saleslocal] [decimal](38, 2) NULL,
	[Brutto2salesCRHEUR] [decimal](38, 2) NULL,
	[Nettosalesposlocal] [decimal](38, 2) NULL,
	[NettosalesposCRHEUR] [decimal](38, 2) NULL,
	[Linepercentweighted] [decimal](38, 2) NULL,
	[Invoicedsaleslocal] [decimal](38, 2) NULL,
	[InvoicedsalesCRHEUR] [decimal](38, 2) NULL,
	[Othersaleslocal] [decimal](38, 6) NULL,
	[OthersalesCRHEUR] [decimal](38, 6) NULL,
	[Allowanceslocal] [decimal](38, 6) NULL,
	[AllowancesCRHEUR] [decimal](38, 6) NULL,
	[Sales100%local] [decimal](38, 6) NULL,
	[Sales100%CRHEUR] [decimal](38, 6) NULL,
	[TZlocal] [decimal](38, 2) NULL,
	[TZCRHEUR] [decimal](38, 2) NULL,
	[TZpercent] [decimal](38, 2) NULL,
	[LZlocal] [decimal](38, 2) NULL,
	[LZCRHEUR] [decimal](38, 2) NULL,
	[LZpercent] [decimal](38, 2) NULL,
	[Linediscount1local] [decimal](38, 2) NULL,
	[Linediscount1CRHEUR] [decimal](38, 2) NULL,
	[Linediscount1percent] [decimal](38, 2) NULL,
	[Linediscount2local] [decimal](38, 2) NULL,
	[Linediscount2CRHEUR] [decimal](38, 2) NULL,
	[Linediscount2percent] [decimal](38, 2) NULL,
	[Orderdiscountlocal] [decimal](38, 2) NULL,
	[OrderdiscountCRHEUR] [decimal](38, 2) NULL,
	[Orderdiscountpercent] [decimal](38, 2) NULL,
	[Productsaleslocal] [decimal](38, 6) NULL,
	[ProductsalesCRHEUR] [decimal](38, 6) NULL,
	[Plantsellingpricelocal] [decimal](38, 6) NULL,
	[PlantsellingpriceCRHEUR] [decimal](38, 6) NULL,
	[ICPlocal] [decimal](38, 6) NULL,
	[ICPCRHEUR] [decimal](38, 6) NULL,
	[SMClocal] [decimal](38, 6) NULL,
	[SMCCRHEUR] [decimal](38, 6) NULL,
	[SMCsumlocal] [decimal](38, 6) NULL,
	[SMCsumCRHEUR] [decimal](38, 6) NULL,
	[Variablesellingcostslocal] [decimal](38, 6) NULL,
	[VariablesellingcostsCRHEUR] [decimal](38, 6) NULL,
	[Netsaleslocal] [decimal](38, 6) NULL,
	[NetsalesCRHEUR] [decimal](38, 6) NULL,
	[Grossmarginlocal] [decimal](38, 6) NULL,
	[GrossmarginCRHEUR] [decimal](38, 6) NULL,
	[contribmarginIIdclocal] [decimal](38, 6) NULL,
	[contribmarginIIdcCRHEUR] [decimal](38, 6) NULL,
	[contribmarginIIholocal] [decimal](38, 6) NULL,
	[contribmarginIIhoCRHEUR] [decimal](38, 6) NULL,
	[Plantoverheadcostslocal] [decimal](38, 6) NULL,
	[PlantoverheadcostsCRHEUR] [decimal](38, 6) NULL,
	[contribmarginIIIlocal] [decimal](38, 6) NULL,
	[contribmarginIIICRHEUR] [decimal](38, 6) NULL,
	[Invoicequantity] [decimal](38, 6) NULL,
	[Orderquantity] [decimal](38, 6) NULL,
	[Netweight] [decimal](38, 3) NULL,
	[Freightinvoicedlocal] [decimal](38, 6) NULL,
	[FreightinvoicedCRHEUR] [decimal](38, 6) NULL,
	[Tollinvoicedlocal] [decimal](38, 6) NULL,
	[TollinvoicedCRHEUR] [decimal](38, 6) NULL,
	[Packingsinvoicedlocal] [decimal](38, 6) NULL,
	[PackingsinvoicedCRHEUR] [decimal](38, 6) NULL,
	[Surchargeonshortquantitylocal] [decimal](38, 6) NULL,
	[SurchargeonshortquantityCRHEUR] [decimal](38, 6) NULL,
	[Planningcostsinvoicedlocal] [decimal](38, 6) NULL,
	[PlanningcostsinvoicedCRHEUR] [decimal](38, 6) NULL,
	[Packingdepositlocal] [decimal](38, 6) NULL,
	[PackingdepositCRHEUR] [decimal](38, 6) NULL,
	[Miscellaneousproceedsinvoicedlocal] [decimal](38, 6) NULL,
	[MiscellaneousproceedsinvoicedCRHEUR] [decimal](38, 6) NULL,
	[Reservecustomerbonuslocal] [decimal](38, 6) NULL,
	[ReservecustomerbonusCRHEUR] [decimal](38, 6) NULL,
	[Warrentieslocal] [decimal](38, 6) NULL,
	[WarrentiesCRHEUR] [decimal](38, 6) NULL,
	[Marketingcostsallowanceslocal] [decimal](38, 6) NULL,
	[MarketingcostsallowancesCRHEUR] [decimal](38, 6) NULL,
	[Reservecustomerdiscountlocal] [decimal](38, 6) NULL,
	[ReservecustomerdiscountCRHEUR] [decimal](38, 6) NULL,
	[Freightcostslocal] [decimal](38, 6) NULL,
	[FreightcostsCRHEUR] [decimal](38, 6) NULL,
	[Packingcostslocal] [decimal](38, 6) NULL,
	[PackingcostsCRHEUR] [decimal](38, 6) NULL,
	[Dutieslocal] [decimal](38, 6) NULL,
	[DutiesCRHEUR] [decimal](38, 6) NULL,
	[Insurancelocal] [decimal](38, 6) NULL,
	[InsuranceCRHEUR] [decimal](38, 6) NULL,
	[Commissionslocal] [decimal](38, 6) NULL,
	[CommissionsCRHEUR] [decimal](38, 6) NULL,
	[Licenceslocal] [decimal](38, 6) NULL,
	[LicencesCRHEUR] [decimal](38, 6) NULL,
	[SMCordinarysteellocal] [decimal](38, 6) NULL,
	[SMCordinarysteelCRHEUR] [decimal](38, 6) NULL,
	[SMCstainlesssteellocal] [decimal](38, 6) NULL,
	[SMCstainlesssteelCRHEUR] [decimal](38, 6) NULL,
	[SMCotherrawmateriallocal] [decimal](38, 6) NULL,
	[SMCotherrawmaterialCRHEUR] [decimal](38, 6) NULL,
	[SMCmaterialoverheadcostslocal] [decimal](38, 6) NULL,
	[SMCmaterialoverheadcostsCRHEUR] [decimal](38, 6) NULL,
	[SMCalloysurchargelocal] [decimal](38, 6) NULL,
	[SMCalloysurchargeCRHEUR] [decimal](38, 6) NULL,
	[SMCexternalproductioncostslocal] [decimal](38, 6) NULL,
	[SMCexternalproductioncostsCRHEUR] [decimal](38, 6) NULL,
	[SMCvariableproductioncostslocal] [decimal](38, 6) NULL,
	[SMCvariableproductioncostsCRHEUR] [decimal](38, 6) NULL,
	[SMCfixedproductioncostslocal] [decimal](38, 6) NULL,
	[SMCfixedproductioncostsCRHEUR] [decimal](38, 6) NULL,
	[CostsofcapitalE01local] [decimal](38, 6) NULL,
	[CostsofcapitalE01CRHEUR] [decimal](38, 6) NULL,
	[WarehousechargesE02local] [decimal](38, 6) NULL,
	[WarhousechargesE02CRHEUR] [decimal](38, 6) NULL,
	[HandlingchargesE03local] [decimal](38, 6) NULL,
	[HandlingchargesE03CRHEUR] [decimal](38, 6) NULL,
	[PackagingchargesE04local] [decimal](38, 6) NULL,
	[PackagingchargesE04CRHEUR] [decimal](38, 6) NULL,
	[PlantoverheadE05local] [decimal](38, 6) NULL,
	[PlantoverheadE05CRHEUR] [decimal](38, 6) NULL,
	[E06local] [decimal](38, 6) NULL,
	[E06CRHEUR] [decimal](38, 6) NULL,
	[E07local] [decimal](38, 6) NULL,
	[E07CRHEUR] [decimal](38, 6) NULL,
	[PlantprofitE08local] [decimal](38, 6) NULL,
	[PlantprofitE08CRHEUR] [decimal](38, 6) NULL,
	[ICsurchargeE09local] [decimal](38, 6) NULL,
	[ICsurchargeE09CRHEUR] [decimal](38, 6) NULL,
	[FreightsurchargeE10local] [decimal](38, 6) NULL,
	[FreightsurchargeE10CRHEUR] [decimal](38, 6) NULL,
	[Freightdctocustomerlocal] [decimal](38, 6) NULL,
	[FreightdctocustomerCRHEUR] [decimal](38, 6) NULL,
	[FreightAR_LAtodclocal] [decimal](38, 6) NULL,
	[FreightAR_LAtodcCRHEUR] [decimal](38, 6) NULL,
	[FreightPNtoAR_LAlocal] [decimal](38, 6) NULL,
	[FreightPNtoAR_LACRHEUR] [decimal](38, 6) NULL,
	[DAN502] [decimal](38, 2) NULL,
	[DAN503] [decimal](38, 2) NULL,
	[DAA705] [nvarchar](20) NULL,
	[LengthinMper1] [decimal](38, 2) NULL,
	[LengthinM] [decimal](38, 2) NULL,
	[Freight_Tollinvoicedlocal] [decimal](38, 6) NULL,
	[Freight_TollinvoicedCRHEUR] [decimal](38, 6) NULL,
	[Packaginginvoicedlocal] [decimal](38, 6) NULL,
	[PackaginginvoicedCRHEUR] [decimal](38, 6) NULL,
	[Grosssaleslocal] [decimal](38, 6) NULL,
	[GrosssalesCRHEUR] [decimal](38, 6) NULL,
	[CostCenter] [nvarchar](3) NULL,
	[DAGRWE] [decimal](38, 3) NULL,
	[CurrencyRatelocaltoCRH1EUR] [decimal](38, 9) NULL,
	[CurrencyEUR] [char](3) NULL,
	[Currencylocal] [char](3) NULL,
	[Salespersonname] [nvarchar](140) NULL,
	[Salesdistrictname] [nvarchar](60) NULL,
	[Projectname] [nvarchar](140) NULL,
	[Projectdeliverycountry] [nvarchar](10) NULL,
	[Projectdeliverycity] [nvarchar](140) NULL,
	[Companycountrycode] [char](10) NULL,
	[Companycountryname] [char](50) NULL,
	[DW_Batch] [bigint] NULL,
	[DW_SourceCode] [varchar](15) NOT NULL,
	[DW_TimeStamp] [datetime] NOT NULL,
	[t_applicationId] [varchar](32) NULL,
	[t_jobId] [varchar](36) NULL,
	[t_jobDtm] [datetime] NULL,
	[t_jobBy] [nvarchar](128) NULL,
	[t_extractionDtm] [datetime] NULL,
	[t_filePath] [nvarchar](1024) NULL,
    CONSTRAINT [PK_FACT_HGDAWA_Archive] PRIMARY KEY NONCLUSTERED ([DW_Id]) NOT ENFORCED
)
WITH
(
	HEAP,  
    DISTRIBUTION = REPLICATE 
);