CREATE TABLE [base_tx_ca_0_hlp].[MAPPING_ITEMGROUP_ANUK](
	[ITEMGROUPID] [nvarchar](60) NOT NULL,
	[ITEMGROUPNAME] [nvarchar](100) NOT NULL,
	[PRODUCTGROUPID] [nvarchar](10) NOT NULL
)  NOT ENFORCED
) WITH (HEAP, DISTRIBUTION = ROUND_ROBIN)