CREATE TABLE [base_us_leviat_db].[CUSTOMERS]
(
    [COMP]                  NVARCHAR(8)     NOT NULL,
    [CUSTOMER]              NVARCHAR(40)    NOT NULL,
    [CustName]              NVARCHAR(60)    NULL,
    [SearchName]            NVARCHAR(120)   NULL,
    [SalesGroup]            NVARCHAR(20)    NULL,
    [CustGroup]             NVARCHAR(20)    NULL,
    [CompName]              NVARCHAR(120)   NULL,
    [REGION]                NVARCHAR(40)    NULL,
    [SubRegion]             NVARCHAR(40)    NULL,
    [ADDRESS]               NVARCHAR(500)   NULL,
    [CITY]                  NVARCHAR(120)   NULL,
    [STATE]                 NVARCHAR(20)    NULL,
    [ZipCode]               NVARCHAR(20)    NULL,
    [COUNTY]                NVARCHAR(60)    NULL,
    [COUNTRY]               NVARCHAR(20)    NULL,
    [PHONE]                 NVARCHAR(40)    NULL,
    [FAX]                   NVARCHAR(40)    NULL,
    [InvoiceTo]             NVARCHAR(40)    NULL,
    [LineDisc]              NVARCHAR(20)    NULL,
    [TERMS]                 NVARCHAR(40)    NULL,
    [DISCOUNT]              NVARCHAR(40)    NULL,
    [CUR]                   NVARCHAR(6)     NULL,
    [STOPPED]               CHAR(3)         NULL,
    [STATEMENT]             NVARCHAR(6)     NULL,
    [CreditLimit]           DECIMAL(28, 12) NULL,
    [PriceGroup]            NVARCHAR(20)    NULL,
    [ResaleNo]              NVARCHAR(40)    NULL,
    [CELL]                  NVARCHAR(40)    NULL,
    [CreditRating]          NVARCHAR(20)    NULL,
    [TaxGroup]              NVARCHAR(22)    NULL,
    [DateOpened]            DATETIME        NULL,
    [PrecastCode]           NVARCHAR(30)    NULL,
    [PrecastCategory]       NVARCHAR(30)    NULL,
    [TaxExpiration]         DATETIME        NULL,
    [CreatedDate]           DATETIME        NULL,
    [CreatedBy]             NVARCHAR(10)    NULL,
    [ModifiedDate]          DATETIME        NULL,
    [ModifiedBy]            NVARCHAR(10)    NULL,
    [RebateCode]            NVARCHAR(20)    NULL,
    [ExcInterest]           CHAR(3)         NULL,
    [LastInvoice]           DATETIME        NULL,
    [LastPayment]           DATETIME        NULL,
    [LastTransaction]       DATETIME        NULL,
    [BALANCE]               DECIMAL(38, 12) NULL,
    [LTMInvoices]           DECIMAL(38, 12) NULL,
    [LTMPayments]           DECIMAL(38, 12) NULL,
    [CollectorCode]         NVARCHAR(20)    NULL,
    [PURPOSE]               NVARCHAR(30)    NULL,
    [CompClosed]            NVARCHAR(3)     NULL,
    [FLAG]                  CHAR(6)         NULL,
    [SEGMENT]               NVARCHAR(40)    NULL,
    [StoreNo]               NVARCHAR(60)    NULL,
    [MethodofPayment]       NVARCHAR(20)    NULL,
    [CONTACT]               NVARCHAR(120)   NULL,
    [ContactPhone]          NVARCHAR(20)    NULL,
    [ContactEmail]          NVARCHAR(160)   NULL,
    [MainContact]           NVARCHAR(40)    NULL,
    [STREET]                NVARCHAR(500)   NULL,
    [RSM]                   NVARCHAR(20)    NULL,
    [REBATE]                DECIMAL(28, 12) NULL,
    [DoNotPrintInvoice]     CHAR(3)         NULL,
    [BusinessLine]          NVARCHAR(30)    NULL,
    [AccountType]           CHAR(10)        NULL,
    [RiskType]              CHAR(20)        NULL,
    [CreditMgr]             NVARCHAR(20)    NULL,
    [BIN]                   NVARCHAR(30)    NULL,
    [ParentBIN]             NVARCHAR(30)    NULL,
    [CommGroup]             NVARCHAR(20)    NULL,
    [LANGUAGE]              NVARCHAR(14)    NULL,
    [PAY_DISC_TERMS]        NVARCHAR(81)    NULL,
    [ARCHIVED]              DECIMAL(38, 0)  NULL,
    [Key]                   NVARCHAR(48)    NULL,
    [SalesDistrict]         NVARCHAR(40)    NULL,
    [CustItemDescr]         NVARCHAR(20)    NULL,
    [PRECAST_CODE_NATIONAL] CHAR(3)         NULL,
    [PARENT_NAME]           NVARCHAR(120)   NULL,
    [SHIPPING_INSTRUCTIONS] NVARCHAR(1000)  NULL,
    [t_applicationId]       VARCHAR(32)     NULL,
    [t_jobId]               VARCHAR(36)     NULL,
    [t_jobDtm]              DATETIME,
    [t_jobBy]               NVARCHAR(128)   NULL,
    [t_extractionDtm]       DATETIME,
    [t_filePath]            NVARCHAR(1024)  NULL,
    CONSTRAINT [PK_CUSTOMERS] PRIMARY KEY NONCLUSTERED ([COMP], [CUSTOMER]) NOT ENFORCED
)
WITH
    (HEAP, DISTRIBUTION = ROUND_ROBIN);
