CREATE TABLE [base_us_leviat_db].[CUSTOMER_SALES]
(
    [COMP]                          NVARCHAR(24)            NULL
    ,[INVOICE]                      NVARCHAR(40)            NULL
    ,[CUSTOMER]                     NVARCHAR(40)            NULL
    ,[CustName]                     NVARCHAR(120)           NULL
    ,[ITEM]                         NVARCHAR(80)            NULL
    ,[WH]                           NVARCHAR(40)            NULL
    ,[ItemName]                     NVARCHAR(2000)          NULL
    ,[CUR]                          NVARCHAR(6)             NULL
    ,[EndCustomer]                  NVARCHAR(40)            NULL
    ,[SO_END_CUSTOMER]              NVARCHAR(40)            NULL
    ,[CustGroup]                    NVARCHAR(20)            NULL
    ,[JobName]                      NVARCHAR(120)           NULL
    ,[ZipCode]                      NVARCHAR(20)            NULL
    ,[COUNTY]                       NVARCHAR(60)            NULL
    ,[COUNTRY]                      NVARCHAR(20)            NULL
    ,[STATE]                        NVARCHAR(20)            NULL
    ,[CITY]                         NVARCHAR(120)           NULL
    ,[ExchRate]                     DECIMAL(28,12)          NULL
    ,[InvoiceCust]                  NVARCHAR(20)            NULL
    ,[InvAmount]                    DECIMAL(28,12)          NULL
    ,[InvDate]                      DATETIME                NULL
    ,[InvYear]                      DECIMAL(4,0)            NULL
    ,[RECIPIENT]                    NVARCHAR(40)            NULL
    ,[SalesGroup]                   NVARCHAR(20)            NULL
    ,[SalesOrder]                   NVARCHAR(40)            NULL
    ,[SALESTYPE]                    CHAR(10)                NULL
    ,[SalesTax]                     DECIMAL(28,12)          NULL
    ,[LineNo]                       DECIMAL(28,12)          NULL
    ,[CostCenter]                   NVARCHAR(30)            NULL
    ,[DEPARTMENT]                   NVARCHAR(30)            NULL
    ,[TYPE]                         NVARCHAR(30)            NULL
    ,[PURPOSE]                      NVARCHAR(30)            NULL
    ,[BusinessLine]                 NVARCHAR(30)            NULL
    ,[UnitPrice]                    DECIMAL(28,12)          NULL
    ,[SalesQty]                     DECIMAL(28,12)          NULL
    ,[InventQty]                    DECIMAL(28,12)          NULL
    ,[UnitCost]                     DECIMAL(28,12)          NULL
    ,[ItemPrice]                    DECIMAL(28,12)          NULL
    ,[ItemCost]                     DECIMAL(28,12)          NULL
    ,[ImbFrtCost]                   DECIMAL(28,12)          NULL
    ,[ImbFrt]                       DECIMAL(28,12)          NULL
    ,[WEIGHT]                       DECIMAL(28,12)          NULL
    ,[SPECIAL]                      CHAR(3)                 NULL
    ,[SpecialNo]                    NVARCHAR(24)            NULL
    ,[GLUnits]                      DECIMAL(28,12)          NULL
    ,[SearchName]                   NVARCHAR(60)            NULL
    ,[CustSalesGroup]               NVARCHAR(20)            NULL
    ,[ItemGroup]                    NVARCHAR(40)            NULL
    ,[ItemType]                     CHAR(10)                NULL
    ,[CompName]                     NVARCHAR(80)            NULL
    ,[REGION]                       NVARCHAR(40)            NULL
    ,[SubRegion]                    NVARCHAR(40)            NULL
    ,[SALES]                        DECIMAL(38,12)          NULL
    ,[COGS]                         DECIMAL(38,12)          NULL
    ,[COGS_NO_COMMISION]            DECIMAL(38,12)          NULL
    ,[TONS]                         DECIMAL(38,12)          NULL
    ,[CollectorCode]                NVARCHAR(20)            NULL
    ,[PrecastCategory]              NVARCHAR(30)            NULL
    ,[PrecastCode]                  NVARCHAR(30)            NULL
    ,[InvoiceTo]                    NVARCHAR(40)            NULL
    ,[CompClosed]                   NVARCHAR(3)             NULL
    ,[CommGroup]                    NVARCHAR(20)            NULL
    ,[FLAG]                         CHAR(10)                NULL
    ,[SEGMENT]                      NVARCHAR(20)            NULL
    ,[DefaultPrice]                 DECIMAL(28,12)          NULL
    ,[ListPrice]                    DECIMAL(28,12)          NULL
    ,[DeliveryTerms]                NVARCHAR(20)            NULL
    ,[ModeofDelivery]               NVARCHAR(20)            NULL
    ,[StoreNo]                      NVARCHAR(60)            NULL
    ,[PICKING_LIST]                 NVARCHAR(1000)          NULL
    ,[OH%]                          DECIMAL(28,12)          NULL
    ,[ItemPurpose]                  NVARCHAR(60)            NULL
    ,[PurposeGroup]                 NVARCHAR(60)            NULL
    ,[ProductClassName]             NVARCHAR(240)           NULL
    ,[SalesClassName]               NVARCHAR(240)           NULL
    ,[SalesClass]                   NVARCHAR(40)            NULL
    ,[ProductClass]                 NVARCHAR(40)            NULL
    ,[RSM]                          NVARCHAR(20)            NULL
    ,[ItemPCCode]                   NVARCHAR(60)            NULL
    ,[ItemPCCategory]               NVARCHAR(60)            NULL
    ,[EXT_ITEM_SALES]               DECIMAL(38,12)          NULL
    ,[EXT_IMB_FRT_SALES]            DECIMAL(38,12)          NULL
    ,[ItemNameField]                NVARCHAR(240)           NULL
    ,[PCAT]                         NVARCHAR(80)            NULL
    ,[SubPCAT]                      NVARCHAR(80)            NULL
    ,[SKUFamily]                    NVARCHAR(80)            NULL
    ,[CustSegment]                  NVARCHAR(60)            NULL
    ,[CLASSIFICATION]               NVARCHAR(20)            NULL
    ,[CustItemDescr]                NVARCHAR(20)            NULL
    ,[CreditReason]                 NVARCHAR(30)            NULL
    ,[t_applicationId]              VARCHAR(32)             NULL
    ,[t_jobId]                      VARCHAR(36)             NULL
    ,[t_jobDtm]                     DATETIME
    ,[t_jobBy]                      NVARCHAR(128)           NULL
    ,[t_extractionDtm]              DATETIME
    ,[t_filePath]                   NVARCHAR(1024)          NULL
)
WITH
    (HEAP, DISTRIBUTION = ROUND_ROBIN);
