CREATE TABLE [base_us_leviat_db].[ITEMS]
(
     [COMP]                     NVARCHAR(24)            NULL
    ,[ITEM]                     NVARCHAR(80)            NULL
    ,[ItemName]                 NVARCHAR(240)           NULL
    ,[ItemText]                 VARCHAR(4241)          NULL
    ,[ITEM_TEXT_NO_NAME]        VARCHAR(4000)          NULL
    ,[ItemType]                 CHAR(10)                NULL
    ,[ItemGroup]                NVARCHAR(40)            NULL
    ,[KIT]                      CHAR(3)                 NULL
    ,[LatestPurchasePrice]      CHAR(3)                 NULL
    ,[LatestCostPrice]          CHAR(3)                 NULL
    ,[BOMUnit]                  NVARCHAR(40)            NULL
    ,[DimensionGroup]           NVARCHAR(40)            NULL
    ,[ModelGroup]               NVARCHAR(40)            NULL
    ,[WEIGHT]                   DECIMAL(28,12)          NULL
    ,[PHANTOM]                  CHAR(3)                 NULL
    ,[PrecastCategory]          NVARCHAR(60)            NULL
    ,[CategoryDescription]      NVARCHAR(120)           NULL
    ,[PrecastCode]              NVARCHAR(60)            NULL
    ,[CodeDescription]          NVARCHAR(120)           NULL
    ,[ProductClass]             NVARCHAR(40)            NULL
    ,[ExpFrt]                   CHAR(3)                 NULL
    ,[GLProdQty]                DECIMAL(28,12)          NULL
    ,[GLSalesQty]               DECIMAL(28,12)          NULL
    ,[LaborHours]               DECIMAL(28,12)          NULL
    ,[ChangeCost]               CHAR(3)                 NULL
    ,[ProdFlushing]             CHAR(10)                NULL
    ,[CreatedDate]              DATETIME                NULL
    ,[CreatedBy]                NVARCHAR(20)            NULL
    ,[ModifiedDate]             DATETIME                NULL
    ,[ModifiedBy]               NVARCHAR(20)            NULL
    ,[InvUnit]                  NVARCHAR(40)            NULL
    ,[InvCost]                  DECIMAL(28,12)          NULL
    ,[InvStop]                  CHAR(3)                 NULL
    ,[POUnit]                   NVARCHAR(40)            NULL
    ,[POCost]                   DECIMAL(28,12)          NULL
    ,[SOUnit]                   NVARCHAR(40)            NULL
    ,[PRICE]                    DECIMAL(28,12)          NULL
    ,[ImbFrt]                   DECIMAL(28,12)          NULL
    ,[DelPrice]                 DECIMAL(29,12)          NULL
    ,[FrtPerLb]                 DECIMAL(28,12)          NULL
    ,[ImbFrtCost]               DECIMAL(28,12)          NULL
    ,[MC]                       DECIMAL(28,12)          NULL
    ,[BuyerGroup]               NVARCHAR(40)            NULL
    ,[UPCCarton]                NVARCHAR(60)            NULL
    ,[UPCItem]                  NVARCHAR(60)            NULL
    ,[MOLD]                     NVARCHAR(60)            NULL
    ,[LineDiscount]             NVARCHAR(40)            NULL
    ,[CoverageGroup]            NVARCHAR(40)            NULL
    ,[SearchName]               NVARCHAR(120)           NULL
    ,[CompName]                 NVARCHAR(80)            NULL
    ,[REGION]                   NVARCHAR(40)            NULL
    ,[SubRegion]                NVARCHAR(40)            NULL
    ,[CompClosed]               NVARCHAR(3)             NULL
    ,[MasterItem]               NVARCHAR(80)            NULL
    ,[PriceChanged]             DATETIME                NULL
    ,[CostChanged]              DATETIME                NULL
    ,[TIER]                     CHAR(4)                 NULL
    ,[ItemPurpose]              NVARCHAR(60)            NULL
    ,[BinLoc]                   NVARCHAR(40)            NULL
    ,[BUILDING]                 NVARCHAR(40)            NULL
    ,[ProdABCD]                 CHAR(1)                 NULL
    ,[WH]                       NVARCHAR(40)            NULL
    ,[SITE]                     NVARCHAR(40)            NULL
    ,[CountGroup]               NVARCHAR(40)            NULL
    ,[PriceMultiplier]          DECIMAL(28,12)          NULL
    ,[ProductClassName]         NVARCHAR(240)           NULL
    ,[SalesClassName]           NVARCHAR(240)           NULL
    ,[SalesClass]               NVARCHAR(40)            NULL
    ,[MaxQtyOnHand]             DECIMAL(28,12)          NULL
    ,[BusinessLine]             NVARCHAR(60)            NULL
    ,[ItemCommGroup]            NVARCHAR(40)            NULL
    ,[PrimaryVendor]            NVARCHAR(80)            NULL
    ,[FormGroup]                NVARCHAR(80)            NULL
    ,[FORM]                     NVARCHAR(80)            NULL
    ,[InvCost_Var]              DECIMAL(28,12)          NULL
    ,[InvCost_Fixed]            DECIMAL(28,12)          NULL
    ,[PRICE_VAR]                DECIMAL(28,12)          NULL
    ,[PRICE_FIXED]              DECIMAL(28,12)          NULL
    ,[CYDS_VAR]                 DECIMAL(28,12)          NULL
    ,[CYDS_FIXED]               DECIMAL(28,12)          NULL
    ,[CYDS]                     DECIMAL(28,12)          NULL
    ,[WEIGHT_VAR]               DECIMAL(28,12)          NULL
    ,[WEIGHT_FIXED]             DECIMAL(28,12)          NULL
    ,[CostGroup]                NVARCHAR(40)            NULL
    ,[SCRAP]                    NVARCHAR(40)            NULL
    ,[INV_COST_PLUS_SCRAP]      DECIMAL(38,12)          NULL
    ,[VITALITY_DATE]            DATETIME                NULL
    ,[PCAT]                     NVARCHAR(80)            NULL
    ,[SUB_PCAT]                 NVARCHAR(80)            NULL
    ,[SKU_FAMILY]               NVARCHAR(80)            NULL
    ,[SHIPPING_CLASS]           NVARCHAR(120)           NULL
    ,[t_applicationId]          VARCHAR(32)             NULL
    ,[t_jobId]                  VARCHAR(36)             NULL
    ,[t_jobDtm]                 DATETIME
    ,[t_jobBy]                  NVARCHAR(128)           NULL
    ,[t_extractionDtm]          DATETIME
    ,[t_filePath]               NVARCHAR(1024)          NULL
)
WITH
    (
    HEAP, 
    DISTRIBUTION = ROUND_ROBIN
    );
