CREATE TABLE [base_s4h_cax].[I_Address](
  [MANDT] char(3) NOT NULL -- collate Latin1_General_100_BIN2 NOT NULL
, [AddressID] nvarchar(10) NOT NULL
, [CareOfName] nvarchar(40)
, [AdditionalStreetSuffixName] nvarchar(40)
, [CorrespondenceLanguage] char(1) -- collate Latin1_General_100_BIN2
, [PrfrdCommMediumType] nvarchar(3)
, [POBox] nvarchar(10)
, [POBoxIsWithoutNumber] nvarchar(1)
, [POBoxPostalCode] nvarchar(10)
, [POBoxLobbyName] nvarchar(40)
, [POBoxDeviatingCityName] nvarchar(40)
, [POBoxDeviatingRegion] nvarchar(3)
, [POBoxDeviatingCountry] nvarchar(3)
, [DeliveryServiceTypeCode] nvarchar(4)
, [DeliveryServiceNumber] nvarchar(10)
, [AddressTimeZone] nvarchar(6)
, [FullName] nvarchar(80)
, [CityName] nvarchar(40)
, [District] nvarchar(40)
, [CityCode] nvarchar(12)
, [HomeCityName] nvarchar(40)
, [PostalCode] nvarchar(10)
, [CompanyPostalCode] nvarchar(10)
, [StreetName] nvarchar(60)
, [StreetPrefixName] nvarchar(40)
, [AdditionalStreetPrefixName] nvarchar(40)
, [StreetSuffixName] nvarchar(40)
, [HouseNumber] nvarchar(10)
, [HouseNumberSupplementText] nvarchar(10)
, [Building] nvarchar(20)
, [Floor] nvarchar(10)
, [RoomNumber] nvarchar(10)
, [Country] nvarchar(3)
, [Region] nvarchar(3)
, [County] nvarchar(40)
, [CountyCode] nvarchar(8)
, [FormOfAddress] nvarchar(4)
, [BusinessPartnerName1] nvarchar(40)
, [BusinessPartnerName2] nvarchar(40)
, [Nation] nvarchar(1)
, [PhoneNumber] nvarchar(30)
, [FaxNumber] nvarchar(30)
, [SearchTerm1] nvarchar(20)
, [SearchTerm2] nvarchar(20)
, [StreetSearch] nvarchar(25)
, [CitySearch] nvarchar(25)
, [BusinessPartnerName3] nvarchar(40)
, [BusinessPartnerName4] nvarchar(40)
, [TaxJurisdiction] nvarchar(15)
, [TransportZone] nvarchar(10)
, [Person] nvarchar(10)
, [t_applicationId]       VARCHAR (32)
, [t_jobId]               VARCHAR (36)
, [t_jobDtm]              DATETIME
, [t_jobBy]        		  NVARCHAR (128)
, [t_extractionDtm]		  DATETIME
, [t_filePath]            NVARCHAR (1024)
, CONSTRAINT [PK_I_Address] PRIMARY KEY NONCLUSTERED (
    [MANDT], [AddressID]
  ) NOT ENFORCED
)
WITH (
  HEAP
)
