CREATE TABLE [base_s4h_cax].[I_CostCenter](
  [MANDT] char(3) NOT NULL -- collate Latin1_General_100_BIN2 NOT NULL
, [ControllingArea] nvarchar(4) NOT NULL
, [CostCenter] nvarchar(10) NOT NULL
, [ValidityEndDate] date NOT NULL
, [ValidityStartDate] date
, [IsBlkdForPrimaryCostsPosting] nvarchar(1)
, [IsBlockedForPlanPrimaryCosts] nvarchar(1)
, [CompanyCode] nvarchar(4)
, [BusinessArea] nvarchar(4)
, [CostCenterCategory] nvarchar(1)
, [CostCtrResponsiblePersonName] nvarchar(20)
, [CostCtrResponsibleUser] nvarchar(12)
, [CostCenterCurrency] char(5) -- collate Latin1_General_100_BIN2
, [CostingSheet] nvarchar(6)
, [TaxJurisdiction] nvarchar(15)
, [ProfitCenter] nvarchar(10)
, [Plant] nvarchar(4)
, [LogicalSystem] nvarchar(10)
, [CostCenterCreationDate] date
, [CostCenterCreatedByUser] nvarchar(12)
, [IsBlkdForSecondaryCostsPosting] nvarchar(1)
, [IsBlockedForRevenuePosting] nvarchar(1)
, [IsBlockedForCommitmentPosting] nvarchar(1)
, [IsBlockedForPlanSecondaryCosts] nvarchar(1)
, [IsBlockedForPlanRevenues] nvarchar(1)
, [CostCenterAllocationMethod] nvarchar(2)
, [ConsumptionQtyIsRecorded] nvarchar(1)
, [Department] nvarchar(12)
, [SubsequentCostCenter] nvarchar(10)
, [ConditionUsage] nvarchar(1)
, [ConditionApplication] nvarchar(2)
, [CostCenterAccountingOverhead] nvarchar(6)
, [Country] nvarchar(3)
, [FormOfAddress] nvarchar(15)
, [AddressName] nvarchar(35)
, [AddressAdditionalName] nvarchar(35)
, [CostCenterAddrName3] nvarchar(35)
, [CostCenterAddrName4] nvarchar(35)
, [CityName] nvarchar(35)
, [District] nvarchar(35)
, [StreetAddressName] nvarchar(35)
, [POBox] nvarchar(10)
, [PostalCode] nvarchar(10)
, [POBoxPostalCode] nvarchar(10)
, [Region] nvarchar(3)
, [Language] char(1) -- collate Latin1_General_100_BIN2
, [TeleboxNumber] nvarchar(15)
, [PhoneNumber1] nvarchar(16)
, [PhoneNumber2] nvarchar(16)
, [FaxNumber] nvarchar(31)
, [TeletexNumber] nvarchar(30)
, [TelexNumber] nvarchar(30)
, [DataCommunicationPhoneNumber] nvarchar(14)
, [CostCenterPrinterDestination] nvarchar(4)
, [CostCenterStandardHierArea] nvarchar(12)
, [CostCollector] nvarchar(23)
, [CostCenterIsComplete] nvarchar(1)
, [IsStatisticalCostCenter] nvarchar(1)
, [ObjectInternalID] nvarchar(22)
, [CostCenterFunction] nvarchar(3)
, [CostCenterAlternativeFunction] nvarchar(3)
, [FunctionalArea] nvarchar(16)
, [ActyIndepFormulaPlanningTmpl] nvarchar(10)
, [ActyDepdntFormulaPlanningTmpl] nvarchar(10)
, [ActyIndependentAllocationTmpl] nvarchar(10)
, [ActyDependentAllocationTmpl] nvarchar(10)
, [ActlIndepStatisticalKeyFigures] nvarchar(10)
, [ActlDepStatisticalKeyFigures] nvarchar(10)
, [JointVenture] nvarchar(6)
, [JointVentureRecoveryCode] nvarchar(2)
, [JointVentureEquityType] nvarchar(3)
, [JointVentureObjectType] nvarchar(4)
, [JointVentureClass] nvarchar(3)
, [JointVentureSubClass] nvarchar(5)
, [BudgetCarryingCostCenter] nvarchar(10)
, [AvailabilityControlProfile] nvarchar(6)
, [AvailabilityControlIsActive] nvarchar(1)
, [Fund] nvarchar(10)
, [GrantID] nvarchar(20)
, [FundIsFixAssigned] nvarchar(1)
, [GrantIDIsFixAssigned] nvarchar(1)
, [FunctionalAreaIsFixAssigned] nvarchar(1)
, [t_applicationId]       VARCHAR (32)
, [t_jobId]               VARCHAR (36)
, [t_jobDtm]              DATETIME
, [t_jobBy]        		  NVARCHAR (128)
, [t_extractionDtm]		  DATETIME
, [t_filePath]            NVARCHAR (1024)
, CONSTRAINT [PK_I_CostCenter] PRIMARY KEY NONCLUSTERED (
    [MANDT], [ControllingArea], [CostCenter], [ValidityEndDate]
  ) NOT ENFORCED
)
WITH (
  HEAP
)
