CREATE TABLE [base_s4h_cax].[I_GLAccountLineItemRawData_delta](
    [TS_SEQUENCE_NUMBER]             INTEGER                                 NOT NULL,
    [ODQ_CHANGEMODE]                 CHAR(1),
    [ODQ_ENTITYCNTR]                 NUMERIC(19, 0),
    [MANDT]                          char(3) collate Latin1_General_100_BIN2 NOT NULL,
    [SOURCELEDGER]                   nvarchar(2)                             NOT NULL,
    [COMPANYCODE]                    nvarchar(4)                             NOT NULL,
    [FISCALYEAR]                     char(4) collate Latin1_General_100_BIN2 NOT NULL,
    [ACCOUNTINGDOCUMENT]             nvarchar(10)                            NOT NULL,
    [LEDGERGLLINEITEM]               nvarchar(6)                             NOT NULL,
    [LEDGERFISCALYEAR]               char(4) collate Latin1_General_100_BIN2,
    [GLRECORDTYPE]                   nvarchar(1),
    [CHARTOFACCOUNTS]                nvarchar(4),
    [CONTROLLINGAREA]                nvarchar(4),
    [FINANCIALTRANSACTIONTYPE]       nvarchar(3),
    [BUSINESSTRANSACTIONTYPE]        nvarchar(4),
    [CONTROLLINGBUSTRANSACTYPE]      nvarchar(4),
    [REFERENCEDOCUMENTTYPE]          nvarchar(5),
    [LOGICALSYSTEM]                  nvarchar(10),
    [REFERENCEDOCUMENTCONTEXT]       nvarchar(10),
    [REFERENCEDOCUMENT]              nvarchar(10),
    [REFERENCEDOCUMENTITEM]          char(6) collate Latin1_General_100_BIN2,
    [REFERENCEDOCUMENTITEMGROUP]     char(6) collate Latin1_General_100_BIN2,
    [ISREVERSAL]                     nvarchar(1),
    [ISREVERSED]                     nvarchar(1),
    [REVERSALREFERENCEDOCUMENTCNTXT] nvarchar(10),
    [REVERSALREFERENCEDOCUMENT]      nvarchar(10),
    [ISSETTLEMENT]                   nvarchar(1),
    [ISSETTLED]                      nvarchar(1),
    [PREDECESSORREFERENCEDOCTYPE]    nvarchar(5),
    [PREDECESSORREFERENCEDOCCNTXT]   nvarchar(10),
    [PREDECESSORREFERENCEDOCUMENT]   nvarchar(10),
    [PREDECESSORREFERENCEDOCITEM]    char(6) collate Latin1_General_100_BIN2,
    [SOURCEREFERENCEDOCUMENTTYPE]    nvarchar(5),
    [SOURCELOGICALSYSTEM]            nvarchar(10),
    [SOURCEREFERENCEDOCUMENTCNTXT]   nvarchar(10),
    [SOURCEREFERENCEDOCUMENT]        nvarchar(10),
    [SOURCEREFERENCEDOCUMENTITEM]    char(6) collate Latin1_General_100_BIN2,
    [SOURCEREFERENCEDOCSUBITEM]      char(6) collate Latin1_General_100_BIN2,
    [ISCOMMITMENT]                   nvarchar(1),
    [JRNLENTRYITEMOBSOLETEREASON]    nvarchar(1),
    [GLACCOUNT]                      nvarchar(10),
    [COSTCENTER]                     nvarchar(10),
    [PROFITCENTER]                   nvarchar(10),
    [FUNCTIONALAREA]                 nvarchar(16),
    [BUSINESSAREA]                   nvarchar(4),
    [SEGMENT]                        nvarchar(10),
    [PARTNERCOSTCENTER]              nvarchar(10),
    [PARTNERPROFITCENTER]            nvarchar(10),
    [PARTNERFUNCTIONALAREA]          nvarchar(16),
    [PARTNERBUSINESSAREA]            nvarchar(4),
    [PARTNERCOMPANY]                 nvarchar(6),
    [PARTNERSEGMENT]                 nvarchar(10),
    [BALANCETRANSACTIONCURRENCY]     char(5) collate Latin1_General_100_BIN2,
    [AMOUNTINBALANCETRANSACCRCY]     decimal(23, 2),
    [TRANSACTIONCURRENCY]            char(5) collate Latin1_General_100_BIN2,
    [AMOUNTINTRANSACTIONCURRENCY]    decimal(23, 2),
    [COMPANYCODECURRENCY]            char(5) collate Latin1_General_100_BIN2,
    [AMOUNTINCOMPANYCODECURRENCY]    decimal(23, 2),
    [GLOBALCURRENCY]                 char(5) collate Latin1_General_100_BIN2,
    [AMOUNTINGLOBALCURRENCY]         decimal(23, 2),
    [FREEDEFINEDCURRENCY1]           char(5) collate Latin1_General_100_BIN2,
    [AMOUNTINFREEDEFINEDCURRENCY1]   decimal(23, 2),
    [FREEDEFINEDCURRENCY2]           char(5) collate Latin1_General_100_BIN2,
    [AMOUNTINFREEDEFINEDCURRENCY2]   decimal(23, 2),
    [FREEDEFINEDCURRENCY3]           char(5) collate Latin1_General_100_BIN2,
    [AMOUNTINFREEDEFINEDCURRENCY3]   decimal(23, 2),
    [FREEDEFINEDCURRENCY4]           char(5) collate Latin1_General_100_BIN2,
    [AMOUNTINFREEDEFINEDCURRENCY4]   decimal(23, 2),
    [FREEDEFINEDCURRENCY5]           char(5) collate Latin1_General_100_BIN2,
    [AMOUNTINFREEDEFINEDCURRENCY5]   decimal(23, 2),
    [FREEDEFINEDCURRENCY6]           char(5) collate Latin1_General_100_BIN2,
    [AMOUNTINFREEDEFINEDCURRENCY6]   decimal(23, 2),
    [FREEDEFINEDCURRENCY7]           char(5) collate Latin1_General_100_BIN2,
    [AMOUNTINFREEDEFINEDCURRENCY7]   decimal(23, 2),
    [FREEDEFINEDCURRENCY8]           char(5) collate Latin1_General_100_BIN2,
    [AMOUNTINFREEDEFINEDCURRENCY8]   decimal(23, 2),
    [FIXEDAMOUNTINGLOBALCRCY]        decimal(23, 2),
    [FIXEDAMOUNTINCOCODECRCY]      decimal(23, 2),
    [GRPVALNFIXEDAMTINGLOBCRCY]    decimal(23, 2),
    [PRFTCTRVALNFXDAMTINGLOBCRCY]        decimal(23, 2),
    [TOTALPRICEVARCINGLOBALCRCY]     decimal(23, 2),
    [GRPVALNTOTPRCVARCINGLOBCRCY]    decimal(23, 2),
    [PRFTCTRVALNTOTPRCVARCINGLBCRCY] decimal(23, 2),
    [FIXEDPRICEVARCINGLOBALCRCY]     decimal(23, 2),
    [GRPVALNFIXEDPRCVARCINGLOBCRCY]  decimal(23, 2),
    [PRFTCTRVALNFXDPRCVARCINGLBCRCY] decimal(23, 2),
    [CONTROLLINGOBJECTCURRENCY]      char(5) collate Latin1_General_100_BIN2,
    [AMOUNTINOBJECTCURRENCY]         decimal(23, 2),
    [BASEUNIT]                       nvarchar(3) collate Latin1_General_100_BIN2,
    [QUANTITY]                       decimal(23, 3),
    [FIXEDQUANTITY]                  decimal(23, 3),
    [COSTSOURCEUNIT]                 nvarchar(3) collate Latin1_General_100_BIN2,
    [VALUATIONQUANTITY]              decimal(23, 3),
    [VALUATIONFIXEDQUANTITY]         decimal(23, 3),
    [ADDITIONALQUANTITY1UNIT]        nvarchar(3) collate Latin1_General_100_BIN2,
    [ADDITIONALQUANTITY1]            decimal(23, 3),
    [ADDITIONALQUANTITY2UNIT]        nvarchar(3) collate Latin1_General_100_BIN2,
    [ADDITIONALQUANTITY2]            decimal(23, 3),
    [ADDITIONALQUANTITY3UNIT]        nvarchar(3) collate Latin1_General_100_BIN2,
    [ADDITIONALQUANTITY3]            decimal(23, 3),
    [DEBITCREDITCODE]                nvarchar(1),
    [FISCALPERIOD]                   char(3) collate Latin1_General_100_BIN2,
    [FISCALYEARVARIANT]              nvarchar(2),
    [FISCALYEARPERIOD]               char(7) collate Latin1_General_100_BIN2,
    [POSTINGDATE]                    date,
    [DOCUMENTDATE]                   date,
    [ACCOUNTINGDOCUMENTTYPE]         nvarchar(2),
    [ACCOUNTINGDOCUMENTITEM]         char(3) collate Latin1_General_100_BIN2,
    [ASSIGNMENTREFERENCE]            nvarchar(18),
    [ACCOUNTINGDOCUMENTCATEGORY]     nvarchar(1),
    [POSTINGKEY]                     nvarchar(2),
    [TRANSACTIONTYPEDETERMINATION]   nvarchar(3),
    [SUBLEDGERACCTLINEITEMTYPE]      char(5) collate Latin1_General_100_BIN2,
    [ACCOUNTINGDOCCREATEDBYUSER]     nvarchar(12),
    [LASTCHANGEDATETIME]             decimal(15),
    [CREATIONDATETIME]               decimal(15),
    [CREATIONDATE]                   date,
    [ELIMINATIONPROFITCENTER]        nvarchar(10),
    [ORIGINOBJECTTYPE]               char(2) collate Latin1_General_100_BIN2,
    [GLACCOUNTTYPE]                  nvarchar(1),
    [ALTERNATIVEGLACCOUNT]           nvarchar(10),
    [COUNTRYCHARTOFACCOUNTS]         nvarchar(4),
    [INVOICEREFERENCE]               nvarchar(10),
    [INVOICEREFERENCEFISCALYEAR]     char(4) collate Latin1_General_100_BIN2,
    [FOLLOWONDOCUMENTTYPE]           nvarchar(1),
    [INVOICEITEMREFERENCE]           char(3) collate Latin1_General_100_BIN2,
    [REFERENCEPURCHASEORDERCATEGORY] char(3) collate Latin1_General_100_BIN2,
    [PURCHASINGDOCUMENT]             nvarchar(10),
    [PURCHASINGDOCUMENTITEM]         char(5) collate Latin1_General_100_BIN2,
    [ACCOUNTASSIGNMENTNUMBER]        char(2) collate Latin1_General_100_BIN2,
    [DOCUMENTITEMTEXT]               nvarchar(50),
    [SALESDOCUMENT]                  nvarchar(10),
    [SALESDOCUMENTITEM]              char(6) collate Latin1_General_100_BIN2,
    [PRODUCT]                        nvarchar(40),
    [PLANT]                          nvarchar(4),
    [SUPPLIER]                       nvarchar(10),
    [CUSTOMER]                       nvarchar(10),
    [SERVICESRENDEREDDATE]           date,
    [CONDITIONCONTRACT]              nvarchar(10),
    [EXCHANGERATEDATE]               date,
    [FINANCIALACCOUNTTYPE]           nvarchar(1),
    [SPECIALGLCODE]                  nvarchar(1),
    [TAXCODE]                        nvarchar(2),
    [HOUSEBANK]                      nvarchar(5),
    [HOUSEBANKACCOUNT]               nvarchar(5),
    [ISOPENITEMMANAGED]              nvarchar(1),
    [CLEARINGDATE]                   date,
    [CLEARINGACCOUNTINGDOCUMENT]     nvarchar(10),
    [CLEARINGDOCFISCALYEAR]          char(4) collate Latin1_General_100_BIN2,
    [ASSETDEPRECIATIONAREA]          char(2) collate Latin1_General_100_BIN2,
    [MASTERFIXEDASSET]               nvarchar(12),
    [FIXEDASSET]                     nvarchar(4),
    [ASSETVALUEDATE]                 date,
    [ASSETTRANSACTIONTYPE]           nvarchar(3),
    [ASSETACCTTRANSCLASSFCTN]        nvarchar(2),
    [DEPRECIATIONFISCALPERIOD]       char(3) collate Latin1_General_100_BIN2,
    [GROUPMASTERFIXEDASSET]          nvarchar(12),
    [GROUPFIXEDASSET]                nvarchar(4),
    [ASSETCLASS]                     nvarchar(8),
    [COSTESTIMATE]                   char(12) collate Latin1_General_100_BIN2,
    [INVENTORYSPECIALSTOCKVALNTYPE]  nvarchar(1),
    [INVENTORYSPECIALSTOCKTYPE]      nvarchar(1),
    [INVENTORYSPCLSTKSALESDOCUMENT]  nvarchar(10),
    [INVENTORYSPCLSTKSALESDOCITM]    char(6) collate Latin1_General_100_BIN2,
    [INVTRYSPCLSTOCKWBSELMNTINTID]   char(8) collate Latin1_General_100_BIN2,
    [INVENTORYSPCLSTOCKWBSELEMENT]   nvarchar(24),
    [INVENTORYSPECIALSTOCKSUPPLIER]  nvarchar(10),
    [INVENTORYVALUATIONTYPE]         nvarchar(10),
    [VALUATIONAREA]                  nvarchar(4),
    [SENDERCOMPANYCODE]              nvarchar(4),
    [SENDERGLACCOUNT]                nvarchar(10),
    [SENDERACCOUNTASSIGNMENT]        nvarchar(30),
    [SENDERACCOUNTASSIGNMENTTYPE]    nvarchar(2),
    [CONTROLLINGOBJECT]              nvarchar(22),
    [COSTORIGINGROUP]                nvarchar(4),
    [ORIGINSENDEROBJECT]             nvarchar(22),
    [CONTROLLINGDEBITCREDITCODE]     nvarchar(1),
    [CONTROLLINGOBJECTDEBITTYPE]     char(1) collate Latin1_General_100_BIN2,
    [QUANTITYISINCOMPLETE]           char(1) collate Latin1_General_100_BIN2,
    [OFFSETTINGACCOUNT]              nvarchar(10),
    [OFFSETTINGACCOUNTTYPE]          nvarchar(1),
    [OFFSETTINGCHARTOFACCOUNTS]      nvarchar(4),
    [LINEITEMISCOMPLETED]            nvarchar(1),
    [PERSONNELNUMBER]                char(8) collate Latin1_General_100_BIN2,
    [CONTROLLINGOBJECTCLASS]         nvarchar(2),
    [PARTNERCOMPANYCODE]             nvarchar(4),
    [PARTNERCONTROLLINGOBJECTCLASS]  nvarchar(2),
    [ORIGINCOSTCENTER]               nvarchar(10),
    [ORIGINPROFITCENTER]             nvarchar(10),
    [ORIGINCOSTCTRACTIVITYTYPE]      nvarchar(6),
    [ACCOUNTASSIGNMENT]              nvarchar(30),
    [ACCOUNTASSIGNMENTTYPE]          nvarchar(2),
    [COSTCTRACTIVITYTYPE]            nvarchar(6),
    [ORDERID]                        nvarchar(12),
    [ORDERCATEGORY]                  char(2) collate Latin1_General_100_BIN2,
    [WBSELEMENTINTERNALID]           char(8) collate Latin1_General_100_BIN2,
    [WBSELEMENT]                     nvarchar(24),
    [PARTNERWBSELEMENTINTERNALID]    char(8) collate Latin1_General_100_BIN2,
    [PARTNERWBSELEMENT]              nvarchar(24),
    [PROJECTINTERNALID]              char(8) collate Latin1_General_100_BIN2,
    [PROJECT]                        nvarchar(24),
    [PARTNERPROJECTINTERNALID]       char(8) collate Latin1_General_100_BIN2,
    [PARTNERPROJECT]                 nvarchar(24),
    [OPERATINGCONCERN]               nvarchar(4),
    [PROJECTNETWORK]                 nvarchar(12),
    [RELATEDNETWORKACTIVITY]         nvarchar(4),
    [BUSINESSPROCESS]                nvarchar(12),
    [COSTOBJECT]                     nvarchar(12),
    [BILLABLECONTROL]                nvarchar(2),
    [COSTANALYSISRESOURCE]           nvarchar(10),
    [CUSTOMERSERVICENOTIFICATION]    nvarchar(12),
    [SERVICEDOCUMENTTYPE]            nvarchar(4),
    [SERVICEDOCUMENT]                nvarchar(10),
    [SERVICEDOCUMENTITEM]            char(6) collate Latin1_General_100_BIN2,
    [PARTNERSERVICEDOCUMENTTYPE]     nvarchar(4),
    [PARTNERSERVICEDOCUMENT]         nvarchar(10),
    [PARTNERSERVICEDOCUMENTITEM]     char(6) collate Latin1_General_100_BIN2,
    [SERVICECONTRACTTYPE]            nvarchar(4),
    [SERVICECONTRACT]                nvarchar(10),
    [SERVICECONTRACTITEM]            char(6) collate Latin1_General_100_BIN2,
    [TIMESHEETOVERTIMECATEGORY]      nvarchar(4),
    [PARTNERACCOUNTASSIGNMENT]       nvarchar(30),
    [PARTNERACCOUNTASSIGNMENTTYPE]   nvarchar(2),
    [WORKPACKAGE]                    nvarchar(50),
    [WORKITEM]                       nvarchar(10),
    [PARTNERCOSTCTRACTIVITYTYPE]     nvarchar(6),
    [PARTNERORDER]                   nvarchar(12),
    [PARTNERORDERCATEGORY]           char(2) collate Latin1_General_100_BIN2,
    [PARTNERSALESDOCUMENT]           nvarchar(10),
    [PARTNERSALESDOCUMENTITEM]       char(6) collate Latin1_General_100_BIN2,
    [PARTNERPROJECTNETWORK]          nvarchar(12),
    [PARTNERPROJECTNETWORKACTIVITY]  nvarchar(4),
    [PARTNERBUSINESSPROCESS]         nvarchar(12),
    [PARTNERCOSTOBJECT]              nvarchar(12),
    [BILLINGDOCUMENTTYPE]            nvarchar(4),
    [SALESORGANIZATION]              nvarchar(4),
    [DISTRIBUTIONCHANNEL]            nvarchar(2),
    [ORGANIZATIONDIVISION]           nvarchar(2),
    [SOLDPRODUCT]                    nvarchar(40),
    [SOLDPRODUCTGROUP]               nvarchar(9),
    [CUSTOMERGROUP]                  nvarchar(2),
    [CUSTOMERSUPPLIERCOUNTRY]        nvarchar(3),
    [CUSTOMERSUPPLIERINDUSTRY]       nvarchar(4),
    [SALESDISTRICT]                  nvarchar(6),
    [BILLTOPARTY]                    nvarchar(10),
    [SHIPTOPARTY]                    nvarchar(10),
    [CUSTOMERSUPPLIERCORPORATEGROUP] nvarchar(10),
    [CASHLEDGERCOMPANYCODE]          nvarchar(4),
    [CASHLEDGERACCOUNT]              nvarchar(10),
    [FINANCIALMANAGEMENTAREA]        nvarchar(4),
    [FUNDSCENTER]                    nvarchar(16),
    [FUNDEDPROGRAM]                  nvarchar(24),
    [FUND]                           nvarchar(10),
    [GRANTID]                        nvarchar(20),
    [BUDGETPERIOD]                   nvarchar(10),
    [PARTNERFUND]                    nvarchar(10),
    [PARTNERGRANT]                   nvarchar(20),
    [PARTNERBUDGETPERIOD]            nvarchar(10),
    [PUBSECBUDGETACCOUNT]            nvarchar(10),
    [PUBSECBUDGETACCOUNTCOCODE]      nvarchar(4),
    [PUBSECBUDGETCNSMPNDATE]         date,
    [PUBSECBUDGETCNSMPNFSCLPERIOD]   char(3) collate Latin1_General_100_BIN2,
    [PUBSECBUDGETCNSMPNFSCLYEAR]     char(4) collate Latin1_General_100_BIN2,
    [PUBSECBUDGETISRELEVANT]         nvarchar(1),
    [PUBSECBUDGETCNSMPNTYPE]         nvarchar(2),
    [PUBSECBUDGETCNSMPNAMTTYPE]      nvarchar(4),
    [JOINTVENTURE]                   nvarchar(6),
    [JOINTVENTUREEQUITYGROUP]        nvarchar(3),
    [JOINTVENTURECOSTRECOVERYCODE]   nvarchar(2),
    [JOINTVENTUREPARTNER]            nvarchar(10),
    [JOINTVENTUREBILLINGTYPE]        nvarchar(2),
    [JOINTVENTUREEQUITYTYPE]         nvarchar(3),
    [JOINTVENTUREPRODUCTIONDATE]     date,
    [JOINTVENTUREBILLINGDATE]        date,
    [JOINTVENTUREOPERATIONALDATE]    date,
    [CUTBACKRUN]                     decimal(21, 7),
    [JOINTVENTUREACCOUNTINGACTIVITY] nvarchar(2),
    [PARTNERVENTURE]                 nvarchar(6),
    [PARTNEREQUITYGROUP]             nvarchar(3),
    [SENDERCOSTRECOVERYCODE]         nvarchar(2),
    [CUTBACKACCOUNT]                 nvarchar(10),
    [CUTBACKCOSTOBJECT]              nvarchar(22),
    [SETTLEMENTREFERENCEDATE]        date,
    [ACCRUALOBJECTTYPE]              nvarchar(4),
    [ACCRUALOBJECT]                  nvarchar(32),
    [ACCRUALSUBOBJECT]               nvarchar(32),
    [ACCRUALITEMTYPE]                nvarchar(11),
    [ACCRUALVALUEDATE]               date,
    [FINANCIALVALUATIONOBJECTTYPE]   nvarchar(4),
    [FINANCIALVALUATIONOBJECT]       nvarchar(32),
    [FINANCIALVALUATIONSUBOBJECT]    nvarchar(32),
    [NETDUEDATE]                     date,
    [CREDITRISKCLASS]                nvarchar(3),
    [WORKCENTERINTERNALID]           char(8) collate Latin1_General_100_BIN2,
    [ORDEROPERATION]                 nvarchar(4),
    [ORDERITEM]                      char(4) collate Latin1_General_100_BIN2,
    [ORDERSUBOPERATION]              nvarchar(4),
    [EQUIPMENT]                      nvarchar(18),
    [FUNCTIONALLOCATION]             nvarchar(30),
    [ASSEMBLY]                       nvarchar(40),
    [MAINTENANCEACTIVITYTYPE]        nvarchar(3),
    [MAINTENANCEORDERPLANNINGCODE]   nvarchar(1),
    [MAINTPRIORITYTYPE]              nvarchar(2),
    [MAINTPRIORITY]                  nvarchar(1),
    [SUPERIORORDER]                  nvarchar(12),
    [PRODUCTGROUP]                   nvarchar(9),
    [MAINTENANCEORDERISPLANNED]      nvarchar(1),
    [KMVKBUPA]                       nvarchar(4),
    [t_applicationId]                VARCHAR(32),
    [t_jobId]                        VARCHAR(36),
    [t_jobDtm]                       DATETIME,
    [t_jobBy]                        NVARCHAR(128),
    [t_extractionDtm]                DATETIME,
    [t_filePath]                     NVARCHAR(1024),
     CONSTRAINT [PK_I_GLAccountLineItemRawData_delta] PRIMARY KEY NONCLUSTERED (
    [TS_SEQUENCE_NUMBER], [MANDT], [SOURCELEDGER], [COMPANYCODE], [FISCALYEAR], [ACCOUNTINGDOCUMENT], [LedgerGLLineItem]
  ) NOT ENFORCED
)
WITH (
  HEAP
)
