CREATE TABLE [base_s4h_cax].[I_MaterialDocumentItem]
(
    [MANDT]                         nchar(3) COLLATE DATABASE_DEFAULT     NOT NULL,
    [MaterialDocumentYear]          char(4) COLLATE DATABASE_DEFAULT      NOT NULL,
    [MaterialDocument]              nvarchar(10) COLLATE DATABASE_DEFAULT NOT NULL,
    [MaterialDocumentItem]          char(4) COLLATE DATABASE_DEFAULT      NOT NULL,
    [Material]                      nvarchar(40) COLLATE DATABASE_DEFAULT,
    [Plant]                         nvarchar(4) COLLATE DATABASE_DEFAULT,
    [StorageLocation]               nvarchar(4) COLLATE DATABASE_DEFAULT,
    [StorageType]                   nvarchar(3) COLLATE DATABASE_DEFAULT,
    [StorageBin]                    nvarchar(10) COLLATE DATABASE_DEFAULT,
    [Batch]                         nvarchar(10) COLLATE DATABASE_DEFAULT,
    [ShelfLifeExpirationDate]       date,
    [ManufactureDate]               date,
    [Supplier]                      nvarchar(10) COLLATE DATABASE_DEFAULT,
    [SalesOrder]                    nvarchar(10) COLLATE DATABASE_DEFAULT,
    [SalesOrderItem]                char(6) COLLATE DATABASE_DEFAULT,
    [SalesOrderScheduleLine]        char(4) COLLATE DATABASE_DEFAULT,
    [WBSElementInternalID]          char(8) COLLATE DATABASE_DEFAULT,
    [Customer]                      nvarchar(10) COLLATE DATABASE_DEFAULT,
    [InventorySpecialStockType]     nvarchar(1) COLLATE DATABASE_DEFAULT,
    [InventoryStockType]            nvarchar(2) COLLATE DATABASE_DEFAULT,
    [StockOwner]                    nvarchar(10) COLLATE DATABASE_DEFAULT,
    [GoodsMovementType]             nvarchar(3) COLLATE DATABASE_DEFAULT,
    [DebitCreditCode]               nvarchar(1) COLLATE DATABASE_DEFAULT,
    [InventoryUsabilityCode]        nvarchar(1) COLLATE DATABASE_DEFAULT,
    [QuantityInBaseUnit]            decimal(13, 3),
    [MaterialBaseUnit]              nvarchar(3) COLLATE DATABASE_DEFAULT,
    [QuantityInEntryUnit]           decimal(13, 3),
    [EntryUnit]                     nvarchar(3) COLLATE DATABASE_DEFAULT,
    [PostingDate]                   date,
    [DocumentDate]                  date,
    [TotalGoodsMvtAmtInCCCrcy]      decimal(13, 2),
    [CompanyCodeCurrency]           nchar(5) COLLATE DATABASE_DEFAULT,
    [InventoryValuationType]        nvarchar(10) COLLATE DATABASE_DEFAULT,
    [ReservationIsFinallyIssued]    nvarchar(1) COLLATE DATABASE_DEFAULT,
    [PurchaseOrder]                 nvarchar(10) COLLATE DATABASE_DEFAULT,
    [PurchaseOrderItem]             char(5) COLLATE DATABASE_DEFAULT,
    [ProjectNetwork]                nvarchar(12) COLLATE DATABASE_DEFAULT,
    [OrderID]                       nvarchar(12) COLLATE DATABASE_DEFAULT,
    [OrderItem]                     char(4) COLLATE DATABASE_DEFAULT,
    [Reservation]                   char(10) COLLATE DATABASE_DEFAULT,
    [ReservationItem]               char(4) COLLATE DATABASE_DEFAULT,
    [DeliveryDocument]              nvarchar(10) COLLATE DATABASE_DEFAULT,
    [DeliveryDocumentItem]          char(6) COLLATE DATABASE_DEFAULT,
    [ReversedMaterialDocumentYear]  char(4) COLLATE DATABASE_DEFAULT,
    [ReversedMaterialDocument]      nvarchar(10) COLLATE DATABASE_DEFAULT,
    [ReversedMaterialDocumentItem]  char(4) COLLATE DATABASE_DEFAULT,
    [RvslOfGoodsReceiptIsAllowed]   nvarchar(1) COLLATE DATABASE_DEFAULT,
    [GoodsRecipientName]            nvarchar(12) COLLATE DATABASE_DEFAULT,
    [UnloadingPointName]            nvarchar(25) COLLATE DATABASE_DEFAULT,
    [CostCenter]                    nvarchar(10) COLLATE DATABASE_DEFAULT,
    [GLAccount]                     nvarchar(10) COLLATE DATABASE_DEFAULT,
    [ServicePerformer]              nvarchar(10) COLLATE DATABASE_DEFAULT,
    [EmploymentInternalID]          char(8) COLLATE DATABASE_DEFAULT,
    [AccountAssignmentCategory]     nvarchar(1) COLLATE DATABASE_DEFAULT,
    [WorkItem]                      nvarchar(10) COLLATE DATABASE_DEFAULT,
    [ServicesRenderedDate]          date,
    [IssgOrRcvgMaterial]            nvarchar(40) COLLATE DATABASE_DEFAULT,
    [IssuingOrReceivingPlant]       nvarchar(4) COLLATE DATABASE_DEFAULT,
    [IssuingOrReceivingStorageLoc]  nvarchar(4) COLLATE DATABASE_DEFAULT,
    [IssgOrRcvgBatch]               nvarchar(10) COLLATE DATABASE_DEFAULT,
    [IssgOrRcvgSpclStockInd]        nvarchar(1) COLLATE DATABASE_DEFAULT,
    [CompanyCode]                   nvarchar(4) COLLATE DATABASE_DEFAULT,
    [BusinessArea]                  nvarchar(4) COLLATE DATABASE_DEFAULT,
    [ControllingArea]               nvarchar(4) COLLATE DATABASE_DEFAULT,
    [FiscalYearPeriod]              char(7) COLLATE DATABASE_DEFAULT,
    [FiscalYearVariant]             nvarchar(2) COLLATE DATABASE_DEFAULT,
    [GoodsMovementRefDocType]       nvarchar(1) COLLATE DATABASE_DEFAULT,
    [IsCompletelyDelivered]         nvarchar(1) COLLATE DATABASE_DEFAULT,
    [MaterialDocumentItemText]      nvarchar(50) COLLATE DATABASE_DEFAULT,
    [IsAutomaticallyCreated]        nvarchar(1) COLLATE DATABASE_DEFAULT,
    [MatlStkChangeQtyInBaseUnit]    decimal(31, 14),
    [MatlCnsmpnQtyInMatlBaseUnit]   decimal(31, 14),
    [GoodsReceiptQtyInOrderUnit]    decimal(13, 3),
    [GoodsMovementIsCancelled]      nvarchar(1) COLLATE DATABASE_DEFAULT,
    [GoodsMovementCancellationType] nvarchar(1) COLLATE DATABASE_DEFAULT,
    [ConsumptionPosting]            nvarchar(1) COLLATE DATABASE_DEFAULT,
    [ManufacturingOrder]            char(12) COLLATE DATABASE_DEFAULT,
    [ManufacturingOrderItem]        nvarchar(4) COLLATE DATABASE_DEFAULT,
    [IsReversalMovementType]        nvarchar(1) COLLATE DATABASE_DEFAULT,
    [t_applicationId]               VARCHAR(32),
    [t_jobId]                       VARCHAR(36),
    [t_jobDtm]                      DATETIME,
    [t_jobBy]                       VARCHAR(128),
    [t_extractionDtm]               DATETIME,
    [t_filePath]                    NVARCHAR(1024)
, CONSTRAINT [PK_I_MaterialDocumentItem] PRIMARY KEY NONCLUSTERED (
    [MANDT], [MaterialDocumentYear], [MaterialDocument], [MaterialDocumentItem]
  ) NOT ENFORCED
)
WITH (
  HEAP
)
