CREATE TABLE [base_s4h_cax].[I_PurchaseOrderHistory]
-- Purchase Order History
(
    [MANDT]                          nchar(3) collate Latin1_General_100_BIN2     NOT NULL,
    [PurchaseOrder]                  nvarchar(10) collate Latin1_General_100_BIN2 NOT NULL,
    [PurchaseOrderItem]              char(5) collate Latin1_General_100_BIN2      NOT NULL,
    [AccountAssignmentNumber]        char(2) collate Latin1_General_100_BIN2      NOT NULL,
    [PurchaseOrderTransactionType]   nvarchar(1) collate Latin1_General_100_BIN2  NOT NULL,
    [MaterialDocumentYear]           char(4) collate Latin1_General_100_BIN2      NOT NULL,
    [MaterialDocument]               nvarchar(10) collate Latin1_General_100_BIN2 NOT NULL,
    [MaterialDocumentItem]           char(4) collate Latin1_General_100_BIN2      NOT NULL,
    [PurchaseOrderHistCategory]      nvarchar(1) collate Latin1_General_100_BIN2,
    [SubsequentDebitCreditIsAllowed] nvarchar(1) collate Latin1_General_100_BIN2,
    [GoodsMovementType]              nvarchar(3) collate Latin1_General_100_BIN2,
    [PostingDate]                    date,
    [Currency]                       nchar(5) collate Latin1_General_100_BIN2,
    [DebitCreditCode]                nvarchar(1) collate Latin1_General_100_BIN2,
    [IsCompletelyDelivered]          nvarchar(1) collate Latin1_General_100_BIN2,
    [ReferenceDocumentFiscalYear]    char(4) collate Latin1_General_100_BIN2,
    [ReferenceDocument]              nvarchar(10) collate Latin1_General_100_BIN2,
    [ReferenceDocumentItem]          char(4) collate Latin1_General_100_BIN2,
    [Material]                       nvarchar(40) collate Latin1_General_100_BIN2,
    [Plant]                          nvarchar(4) collate Latin1_General_100_BIN2,
    [RvslOfGoodsReceiptIsAllowed]    nvarchar(1) collate Latin1_General_100_BIN2,
    [PricingDocument]                nvarchar(10) collate Latin1_General_100_BIN2,
    [TaxCode]                        nvarchar(2) collate Latin1_General_100_BIN2,
    [DocumentDate]                   date,
    [InventoryValuationType]         nvarchar(10) collate Latin1_General_100_BIN2,
    [DocumentReferenceID]            nvarchar(16) collate Latin1_General_100_BIN2,
    [DeliveryQuantityUnit]           nvarchar(3) collate Latin1_General_100_BIN2,
    [ManufacturerMaterial]           nvarchar(40) collate Latin1_General_100_BIN2,
    [AccountingDocumentCreationDate] date,
    [Quantity]                       decimal(13, 3),
    [PurOrdAmountInCompanyCodeCrcy]  decimal(13, 2),
    [PurchaseOrderAmount]            decimal(13, 2),
    [QtyInPurchaseOrderPriceUnit]    decimal(13, 3),
    [GRIRAcctClrgAmtInCoCodeCrcy]    decimal(13, 2),
    [GdsRcptBlkdStkQtyInOrdQtyUnit]  decimal(13, 3),
    [GdsRcptBlkdStkQtyInOrdPrcUnit]  decimal(13, 3),
    [InvoiceAmtInCoCodeCrcy]         decimal(13, 2),
    [ShipgInstrnSupplierCompliance]  nvarchar(2) collate Latin1_General_100_BIN2,
    [InvoiceAmountInFrgnCurrency]    decimal(13, 2),
    [QuantityInDeliveryQtyUnit]      decimal(13, 3),
    [GRIRAcctClrgAmtInTransacCrcy]   decimal(13, 2),
    [QuantityInBaseUnit]             decimal(13, 3),
    [GRIRAcctClrgAmtInOrdTrnsacCrcy] decimal(13, 2),
    [InvoiceAmtInPurOrdTransacCrcy]  decimal(13, 2),
    [VltdGdsRcptBlkdStkQtyInOrdUnit] decimal(13, 3),
    [VltdGdsRcptBlkdQtyInOrdPrcUnit] decimal(13, 3),
    [IsToBeAcceptedAtOrigin]         nvarchar(1) collate Latin1_General_100_BIN2,
    [ExchangeRateDifferenceAmount]   decimal(13, 2),
    [ExchangeRate]                   decimal(9, 5),
    [t_applicationId]                VARCHAR(32),    
    [t_jobId]                        VARCHAR(36),
    [t_jobDtm]                       DATETIME,
    [t_jobBy]                        NVARCHAR(128),
    [t_extractionDtm]                DATETIME,
    [t_filePath]                     NVARCHAR(1024),
    CONSTRAINT [PK_I_PurchaseOrderHistory] PRIMARY KEY NONCLUSTERED (
      [MANDT], [PurchaseOrder], [PurchaseOrderItem],
      [AccountAssignmentNumber],
      [PurchaseOrderTransactionType],
      [MaterialDocumentYear], [MaterialDocument],
      [MaterialDocumentItem]) NOT ENFORCED
)
WITH (HEAP)
