CREATE TABLE [base_s4h_cax].[I_PurgDocScheduleLineEnhanced]
-- Schedule Line of Purchasing Document – Enhanced
(
    [MANDT]                          nchar(3) collate Latin1_General_100_BIN2     NOT NULL,
    [PurchasingDocument]             nvarchar(10) NOT NULL -- collate Latin1_General_100_BIN2 NOT NULL,
    [PurchasingDocumentItem]         char(5) collate Latin1_General_100_BIN2      NOT NULL,
    [ScheduleLine]                   char(4) collate Latin1_General_100_BIN2      NOT NULL,
    [ProcurementHubSourceSystem]     nvarchar(10) NOT NULL -- collate Latin1_General_100_BIN2 NOT NULL,
    [ScheduleLineUniqueID]           nvarchar(19) -- collate Latin1_General_100_BIN2,
    [PurchasingOrganization]         nvarchar(4) -- collate Latin1_General_100_BIN2,
    [PurchasingGroup]                nvarchar(3) -- collate Latin1_General_100_BIN2,
    [CompanyCode]                    nvarchar(4) -- collate Latin1_General_100_BIN2,
    [Supplier]                       nvarchar(10) -- collate Latin1_General_100_BIN2,
    [Plant]                          nvarchar(4) -- collate Latin1_General_100_BIN2,
    [Material]                       nvarchar(40) -- collate Latin1_General_100_BIN2,
    [MaterialGroup]                  nvarchar(9) -- collate Latin1_General_100_BIN2,
    [ServicePerformer]               nvarchar(10) -- collate Latin1_General_100_BIN2,
    [AnlytlCrcyExchangeRateStatus]   nvarchar(2) -- collate Latin1_General_100_BIN2,
    [AnalyticalReportingCurrency]    nchar(5) -- collate Latin1_General_100_BIN2,
    [AnalyticalReportingCurrency2]   nchar(5) -- collate Latin1_General_100_BIN2,
    [DocumentCurrency]               nchar(5) -- collate Latin1_General_100_BIN2,
    [CompanyCodeCurrency]            nchar(5) -- collate Latin1_General_100_BIN2,
    [NetPriceInReportingCurrency]    decimal(21, 5),
    [NetPriceInReportingCurrency2]   decimal(21, 5),
    [NetPriceAmount]                 decimal(11, 2),
    [NetPriceInCompanyCodeCrcy]      decimal(21, 5),
    [NetAmountInReportingCurrency]   decimal(21, 5),
    [NetAmountInReportingCurrency2]  decimal(21, 5),
    [NetAmount]                      decimal(13, 2),
    [NetAmountInCoCodeCurrency]      decimal(21, 5),
    [OpenAmountInReportingCurrency]  decimal(21, 5),
    [OpenAmountInReportingCurrency2] decimal(21, 5),
    [OpenAmountInDocumentCurrency]   decimal(21, 5),
    [OpenAmountInCompanyCodeCrcy]    decimal(21, 5),
    [ScheduleLineOpenQuantity]       decimal(13, 3),
    [OrderQuantityUnit]              nvarchar(3) -- collate Latin1_General_100_BIN2,
    [IsCompletelyDelivered]          nvarchar(1) -- collate Latin1_General_100_BIN2,
    [GoodsReceiptIsExpected]         nvarchar(1) -- collate Latin1_General_100_BIN2,
    [PurchasingDocumentDeletionCode] nvarchar(1) -- collate Latin1_General_100_BIN2,
    [PurchasingCompletenessStatus]   nvarchar(1) -- collate Latin1_General_100_BIN2,
    [PurchasingDocumentCategory]     nvarchar(1) -- collate Latin1_General_100_BIN2,
    [PurchasingDocumentType]         nvarchar(4) -- collate Latin1_General_100_BIN2,
    [PurchasingDocumentItemCategory] nvarchar(1) -- collate Latin1_General_100_BIN2,
    [AccountAssignmentCategory]      nvarchar(1) -- collate Latin1_General_100_BIN2,
    [CreationDate]                   date,
    [PurchasingDocumentStatus]       nvarchar(1) -- collate Latin1_General_100_BIN2,
    [CreatedByUser]                  nvarchar(12) -- collate Latin1_General_100_BIN2,
    --commented out due to issue while copying parquet file from In to Out. Potential cause is DateTime defined as Decima
    --[LastChangeDateTime]             decimal(21, 7),
    [PurchasingProcessingStatus]     nvarchar(2) -- collate Latin1_General_100_BIN2,
    [PurchasingDocumentOrderDate]    date,
    [PurchasingDocumentIsAged]       nvarchar(1) -- collate Latin1_General_100_BIN2,
    [OrderQuantity]                  decimal(13, 3),
    [PurchaseOrderQuantityUnit]      nvarchar(3) -- collate Latin1_General_100_BIN2,
    [ProductTypeCode]                nvarchar(4) -- collate Latin1_General_100_BIN2,
    [ReleaseIsNotCompleted]          nvarchar(1) -- collate Latin1_General_100_BIN2,
    [IsReturnsItem]                  nvarchar(1) -- collate Latin1_General_100_BIN2,
    [PurgDocSchdLnHasNextDelivery]   nvarchar(1) -- collate Latin1_General_100_BIN2,
    [PurOrdItmFirstGRPostingDate]    date,
    [PurOrdItmFinalGRPostingDate]    date,
    [POItmFinalScheduleLineIsActive] nvarchar(1) -- collate Latin1_General_100_BIN2,
    [POScheduleLineTotalExpectedQty] decimal(13, 3),
    [POPrevSchdLnTotalExpectedQty]   decimal(13, 3),
    [TimeVarianceInDays]             int,
    [TimeVarianceInPct]              decimal(13, 2),
    [TimeVarianceInPctByDelivDate]   decimal(15, 3),
    [TimeVarianceScore]              decimal(3),
    [TimeVarianceScoreByDelivDate]   decimal(3),
    [ScheduleLineDeliveryDate]       date,
    [SchedLineStscDeliveryDate]      date,
    [DelivDateCategory]              nvarchar(1) -- collate Latin1_General_100_BIN2,
    [ScheduleLineOrderQuantity]      decimal(13, 3),
    [PrevDelivQtyOfScheduleLine]     decimal(13, 3),
    [GoodsReceiptQuantity]           decimal(13, 3),
    [ScheduleLineIssuedQuantity]     decimal(13, 3),
    [ScheduleLineDeliveryTime]       time(0),
    [PurchaseRequisition]            nvarchar(10) -- collate Latin1_General_100_BIN2,
    [PurchaseRequisitionItem]        char(5) -- collate Latin1_General_100_BIN2,
    [SourceOfCreation]               nvarchar(1) -- collate Latin1_General_100_BIN2,
    [NoOfRemindersOfScheduleLine]    decimal(3),
    [SchedulingAgreementReleaseType] nvarchar(1) -- collate Latin1_General_100_BIN2,
    [ScheduleLineCommittedQuantity]  decimal(13, 3),
    [ProductAvailabilityDate]        date,
    [MaterialStagingTime]            time(0),
    [LoadingDate]                    date,
    [LoadingTime]                    time(0),
    [TransportationPlanningDate]     date,
    [TransportationPlanningTime]     time(0),
    [GoodsIssueDate]                 date,
    [GoodsIssueTime]                 time(0),
    [STOLatestPossibleGRDate]        date,
    [STOLatestPossibleGRTime]        time(0),
    [RoughGoodsReceiptQty]           decimal(13, 3),
    [PurchaseContractItem]           char(5) -- collate Latin1_General_100_BIN2,
    [PurchaseContract]               nvarchar(10) -- collate Latin1_General_100_BIN2,
    [MultipleAcctAssgmtDistribution] nvarchar(1) -- collate Latin1_General_100_BIN2,
    [PurchaseOrderDate]              date,
    [OrderPriceUnitToOrderUnitNmrtr] decimal(5),
    [OrdPriceUnitToOrderUnitDnmntr]  decimal(5),
    [NetPriceQuantity]               decimal(5),
    [PerformancePeriodStartDate]     date,
    [PerformancePeriodEndDate]       date,
    [t_applicationId]                VARCHAR(32),    
    [t_jobId]                        VARCHAR(36),
    [t_jobDtm]                       DATETIME,
    [t_jobBy]                        NVARCHAR(128),
    [t_extractionDtm]                DATETIME,
    [t_filePath]                     NVARCHAR(1024),
    CONSTRAINT [PK_I_PurgDocScheduleLineEnhanced] PRIMARY KEY NONCLUSTERED (
      [MANDT], [PurchasingDocument],
      [PurchasingDocumentItem], [ScheduleLine],
      [ProcurementHubSourceSystem]) NOT ENFORCED
)
WITH (HEAP)

