CREATE TABLE [base_s4h_cax].[Opt_Vim_1Head]
(
    MANDT                   NVARCHAR(3)                
    ,DOCID                  NVARCHAR(12)                
    ,DOCTYPE                NVARCHAR(10)
--    ,ARCHIV_ID              NVARCHAR(2)
--    ,ARC_DOC_ID             NVARCHAR(40)
--    ,AR_OBJECT              NVARCHAR(10)
--    ,EDI_DOCNUM             NVARCHAR(16)
--    ,ARCHIVE_DATE           DATE                
--    ,ARCHIVE_TIME           TIME(0)                
--    ,ARCHIVE_USER           NVARCHAR(12)
    ,INDEX_DATE             DATE
--    ,INDEX_TIME             TIME(0)                
--    ,INDEX_USER             NVARCHAR(12)
--    ,CHANGE_DATE            DATE
--    ,CHANGE_TIME            TIME(0)                
--    ,CHANGE_USER            NVARCHAR(12)
    ,BUS_OBJTYPE            NVARCHAR(10)
--    ,BUS_OBJKEY             NVARCHAR(70)
    ,STATUS                 NVARCHAR(2)
--    ,CURR_ROLE              NVARCHAR(15)
--    ,CURR_PROC_TYPE         NVARCHAR(3)
--    ,RESCANID               NVARCHAR(2)
--    ,DELREASON              NVARCHAR(2)
--    ,SCAN_LOCATION          NVARCHAR(25)
--    ,PRIORITY               NVARCHAR(1)
    ,NOFIRSTPASS            NVARCHAR(1)
--    ,CHECKRULE              NVARCHAR(1)
--    ,CHECKDUPS              NVARCHAR(1)
--    ,CONFIRMED_NO_DUP       NVARCHAR(1)
--    ,DUP_CHK_RUN            NVARCHAR(1)
--    ,TARGET_SYSTEM          NVARCHAR(10)                
--    ,BUKRS                  NVARCHAR(4)
    ,BELNR                  NVARCHAR(10)                
    ,GJAHR                  NVARCHAR(4)                
    ,BLART                  NVARCHAR(2)
    ,BLDAT                  DATE
    ,BUDAT                  DATE
    ,XBLNR                  NVARCHAR(16)
--    ,RMWWR                  DECIMAL(13,2)                                    
    ,WAERS                  NVARCHAR(5)
    ,LIFNR                  NVARCHAR(10)                
--    ,VEND_NAME              NVARCHAR(35)
--    ,VEND_NAME2             NVARCHAR(35)
    ,EBELN                  NVARCHAR(10)                
--    ,RECIPIENT_NAME         NVARCHAR(35)
--    ,LXBLNR                 NVARCHAR(60)
--    ,REQUISITIONER          NVARCHAR(35)
--    ,EMAIL_ID               NVARCHAR(80)
--    ,WINDOWS_ID             NVARCHAR(30)
--    ,WINDOWS_DOMAIN         NVARCHAR(63)
--    ,SKIP_STACK             NVARCHAR(1)
--    ,BLOCK_PA               NVARCHAR(1)
--    ,PAS_ACTIVE             NVARCHAR(1)
--    ,ALTERNATIVE            NVARCHAR(2)
--    ,DISTR_TYPE             NVARCHAR(1)
--    ,EASYMATCH              NVARCHAR(1)
--    ,AUTO_POST              NVARCHAR(1)
--    ,SCAN_DATE              DATE
--    ,SCAN_TIME              TIME(0)                
--    ,SCAN_LOC               NVARCHAR(25)
--    ,BATCHNUMBER            NVARCHAR(40)
--    ,CREDIT_MEMO            NVARCHAR(1)
--    ,VORGANG                NVARCHAR(1)
--    ,CLASSIFIER             NVARCHAR(2)
--    ,WERKS                  NVARCHAR(4)
--    ,WMWST                  DECIMAL(23,2)                                    
--    ,BEZNK                  DECIMAL(13,2)                                    
--    ,REMIT_STREET           NVARCHAR(60)
--    ,REMIT_HSNM1            NVARCHAR(10)
--    ,REMIT_PSTLZ            NVARCHAR(10)
--    ,REMIT_LAND1            NVARCHAR(3)
--    ,REMIT_AD_CITY1         NVARCHAR(40)
--    ,REMIT_REGIO            NVARCHAR(3)
--    ,REMIT_PO_BOX           NVARCHAR(10)
--    ,REMIT_PSTL2            NVARCHAR(10)
--    ,SHIPTO_STREET          NVARCHAR(60)
--    ,SHIPTO_HSNM1           NVARCHAR(10)
--    ,SHIPTO_PSTLZ           NVARCHAR(10)
--    ,SHIPTO_LAND1           NVARCHAR(3)
--    ,SHIPTO_AD_CITY1        NVARCHAR(40)
--    ,SHIPTO_REGIO           NVARCHAR(3)
--    ,SHIPTO_PO_BOX          NVARCHAR(10)
    ,BKTXT                  NVARCHAR(25)
--    ,SGTXT                  NVARCHAR(50)
--    ,PRORITY_FLAG           NVARCHAR(1)
--    ,NET_AMOUNT             DECIMAL(13,2)                                    
--    ,GROSS_AMOUNT           DECIMAL(13,2)                                    
--    ,F_TAX_AMOUNT           DECIMAL(13,2)                                    
--    ,S_TAX_AMOUNT           DECIMAL(13,2)                                    
--    ,VAT_AMOUNT             DECIMAL(13,2)                                    
--    ,TOT_TAX_AMOUNT         DECIMAL(13,2)                                    
--    ,FREIGHT_AMOUNT         DECIMAL(13,2)                                    
--    ,HANDLING_CHARGES       DECIMAL(13,2)                                    
--    ,UN_ALLOCATED_EXP       DECIMAL(13,2)                                    
--    ,EXPENSE_TYPE           NVARCHAR(2)
--    ,ATTRIBUTE1             NVARCHAR(10)
--    ,ATTRIBUTE2             NVARCHAR(10)
--    ,ATTRIBUTE3             NVARCHAR(20)
--    ,ATTRIBUTE4             NVARCHAR(20)
--    ,TAX_CODE               NVARCHAR(2)
--    ,AUTO_CALC              NVARCHAR(1)
--    ,TAX_CODE_WH            NVARCHAR(2)
--    ,SUPPLY_DATE            DATE
--    ,VENDOR_VAT_NO          NVARCHAR(20)
--    ,VENDOR_TAX_NO          NVARCHAR(18)
--    ,RECEPIENT_VAT_NO       NVARCHAR(20)
--    ,FISCAL_REP_VAT_N       NVARCHAR(18)
--    ,PYMNT_TERMS            NVARCHAR(4)
--    ,PYMNT_TERMS_TEXT       NVARCHAR(40)
--    ,ISR                    NVARCHAR(90)
--    ,CM_REF_NO              NVARCHAR(16)
--    ,CM_REF_DAT             DATE
--    ,TAX_RATE               DECIMAL(13,3)
--    ,SIRET_NO               NVARCHAR(14)
--    ,ZERO_TAX_RATE          NVARCHAR(10)
--    ,DOC_ARC_DOC_ID         NVARCHAR(40)
--    ,TRNG_LEARN             NVARCHAR(1)
--    ,FEEDB_LEARN            NVARCHAR(1)
--    ,CHANNEL_ID             NVARCHAR(10)
--    ,CUSTOM_FIELD4          NVARCHAR(1)
--    ,CUSTOM_FIELD5          NVARCHAR(60)
--    ,CUSTOM_FIELD6          NVARCHAR(10)
--    ,CUSTOM_FIELD7          NVARCHAR(1)
--    ,CUSTOM_FIELD8          NVARCHAR(10)
--    ,CUSTOM_FIELD9          NVARCHAR(20)
--    ,CUSTOM_FIELD0          NVARCHAR(20)
--    ,PAYMENT_METHOD         NVARCHAR(1)
--    ,PAY_METHOD_TEXT        NVARCHAR(30)
--    ,KIDNO                  NVARCHAR(30)
--    ,INV_CAT                NVARCHAR(2)
--    ,TAX_EXEMPT_TEXT        NVARCHAR(50)
--    ,IMPORT_TEXT            NVARCHAR(50)
--    ,TRI_TEXT               NVARCHAR(50)
--    ,ORG_NUMBER             NVARCHAR(20)
--    ,DISCOUNT               DECIMAL(11,2)                                    
--    ,TAXRATE_1              DECIMAL(13,3)
--    ,TAXRATE_2              DECIMAL(13,3)
--    ,TAXRATE_3              DECIMAL(13,3)
--    ,TAXRATE_4              DECIMAL(13,3)
--    ,TAXAMT_1               DECIMAL(13,2)                                    
--    ,TAXAMT_2               DECIMAL(13,2)                                    
--    ,TAXAMT_3               DECIMAL(13,2)                                    
--    ,TAXAMT_4               DECIMAL(13,2)                                    
--    ,SCB_IND                NVARCHAR(3)
--    ,TAX_INVOICE            NVARCHAR(1)
--    ,POST_DATE_DET          NVARCHAR(1)
--    ,ZFBDT_DET              NVARCHAR(1)
--    ,NF_TYPE                NVARCHAR(2)
--    ,BUPLA                  NVARCHAR(4)
--    ,TAX_LAWS               NVARCHAR(20)
--    ,SUPCOUNTRY             NVARCHAR(3)
--    ,BVTYP                  NVARCHAR(4)
--    ,IBAN                   NVARCHAR(34)
--    ,BANKL                  NVARCHAR(15)
--    ,BANKA                  NVARCHAR(60)
--    ,BANKN                  NVARCHAR(18)
--    ,BKREF                  NVARCHAR(20)
--    ,BANKS                  NVARCHAR(3)
--    ,BKONT                  NVARCHAR(2)
--    ,GSBER                  NVARCHAR(4)
--    ,RESTART                NVARCHAR(1)
    ,LAND1                  NVARCHAR(3)
--    ,BARCODE                NVARCHAR(64)
--    ,ZFBDT                  DATE
--    ,ZBD1T                  DECIMAL(3)
--    ,ZBD1P                  DECIMAL(5,3)
--    ,ZBD2T                  DECIMAL(3)
--    ,ZBD2P                  DECIMAL(5,3)
--    ,ZBD3T                  DECIMAL(3)
--    ,SWIFT                  NVARCHAR(11)
--    ,HBKID                  NVARCHAR(5)
--    ,HKTID                  NVARCHAR(5)
--    ,ZUONR                  NVARCHAR(18)
--    ,DTAWS                  NVARCHAR(2)
--    ,DTAMS                  NVARCHAR(1)
--    ,FITYP                  NVARCHAR(2)
--    ,STCDT                  NVARCHAR(2)
--    ,STKZN                  NVARCHAR(1)
--    ,STKZU                  NVARCHAR(1)
--    ,STKZA                  NVARCHAR(1)
--    ,EMPFB                  NVARCHAR(10)                
--    ,WHT_TYPE               NVARCHAR(1)
--    ,ENRICH_FLAG            NVARCHAR(1)
--    ,DUE_DATE               DATE
--    ,DUE_DATE1              DATE
--    ,DUE_DATE2              DATE
--    ,SECCO                  NVARCHAR(4)
--    ,VEND_GRP               NVARCHAR(10)
--    ,TH_BCODE               NVARCHAR(5)
--    ,ESRRE                  NVARCHAR(27)                
--    ,QR_REF_TYP             NVARCHAR(4)
--    ,VAT_INV_IDENT          NVARCHAR(10)
--    ,SECRET_CODE1           NVARCHAR(27)
--    ,SECRET_CODE2           NVARCHAR(27)
--    ,SECRET_CODE3           NVARCHAR(27)
--    ,SECRET_CODE4           NVARCHAR(27)
--    ,INVOICE_CODE           NVARCHAR(12)
--    ,VALIDATION_CODE        NVARCHAR(30)
--    ,NOT_HAND_WRITTEN       NVARCHAR(1)
--    ,AFTCS_VALIDATION       NVARCHAR(1)
--    ,USER_ID                NVARCHAR(12)
--    ,TIME_STAMP             DECIMAL(15)
--    ,TAX_DESC               NVARCHAR(1)
--    ,PAN_NO                 NVARCHAR(40)
--    ,STC_NO                 NVARCHAR(30)
--    ,TIN_TOT                NVARCHAR(11)
--    ,LST_NO                 NVARCHAR(40)
--    ,CST_NO                 NVARCHAR(40)
--    ,ECC_NO                 NVARCHAR(40)
--    ,EDC_CESS               DECIMAL(13,2)                                    
--    ,EXC_DUTY               DECIMAL(13,2)                                    
--    ,SAHE_CESS              DECIMAL(13,2)                                    
--    ,MODEL                  NVARCHAR(2)
--    ,SERIES                 NVARCHAR(3)
--    ,NFNUM                  NVARCHAR(6)
--    ,CGC                    NVARCHAR(14)                
--    ,XMLVERS                DECIMAL(5,2)
--    ,AUTHCOD                NVARCHAR(15)
--    ,DOCNUM9                NVARCHAR(9)
--    ,ACCESSKEY              NVARCHAR(44)
--    ,NFNUM9                 NVARCHAR(9)
--    ,CDV                    NVARCHAR(1)
--    ,TRANSPAYMENT           NVARCHAR(1)
--    ,NFTOT                  DECIMAL(15,2)                                    
--    ,REFNFENUM              NVARCHAR(9)
--    ,ACTION_DATE            DATE
--    ,ACTION_TIME            TIME(0)                
--    ,DOCDAT                 DATE
--    ,PARID                  NVARCHAR(10)                
--    ,STCD1                  NVARCHAR(14)                
--    ,FLAG_ENFE              NVARCHAR(1)
--    ,FLAG_SNFE              NVARCHAR(1)
--    ,FLAG_SIG_VALID         NVARCHAR(1)
--    ,ORG_NUM                NVARCHAR(16)
--    ,ORG_DATE               DATE
--    ,REV_NUM                NVARCHAR(16)
--    ,REV_DATE               DATE
--    ,REV_NUM_COR            NVARCHAR(16)
--    ,REV_DATE_COR           DATE
--    ,BSTYP                  NVARCHAR(1)
--    ,CONTRACT               NVARCHAR(10)                
--    ,RECNTYPE               NVARCHAR(4)
--    ,RECNNR                 NVARCHAR(13)                
--    ,RECNTXT                NVARCHAR(80)
--    ,RECNTXTOLD             NVARCHAR(20)                
--    ,REC_MANUAL_CHK         NVARCHAR(1)
--    ,EVRTN                  NVARCHAR(10)                
--    ,REP_COUNTRY            NVARCHAR(3)
--    ,ROUTE_ID               NVARCHAR(46)
--    ,ROUTE_ID1              NVARCHAR(16)
--    ,ROUTE_ID2              NVARCHAR(16)
--    ,RETRY_NO1              INT               
--    ,RETRY_NO2              INT               
--    ,RFC_DUP                NVARCHAR(1)
--    ,RETRY_COUNT_EXT        NVARCHAR(4)
--    ,ORIG_AR_OBJECT         NVARCHAR(10)
--    ,SCAN_TIMESTAMP         DECIMAL(15)
--    ,DOC_ARCHIV_ID          NVARCHAR(2)
--    ,SKIP_DETERMINE         NVARCHAR(1)
--    ,REG_ID                 NVARCHAR(12)
--    ,OTYPE                  NVARCHAR(2)
--    ,ACTORID                NVARCHAR(12)
--    ,RTV_REASON             NVARCHAR(2)
--    ,VATDATE                DATE
--    ,MWSKZ_BNK              NVARCHAR(2)
--    ,TXJCD_BNK              NVARCHAR(15)
--    ,CM_REF_BEL             NVARCHAR(10)                
--    ,CM_REF_GJA             NVARCHAR(4)                
--    ,CM_REF_ZEI             NVARCHAR(3)
--    ,WHT_CHECK              NVARCHAR(1)
--    ,KURSF                  DECIMAL(9,5)                
--    ,IGNORE_IP              NVARCHAR(1)
--    ,TXKRS                  DECIMAL(9,5)                
--    ,EGMLD                  NVARCHAR(3)
--    ,GST_PART               NVARCHAR(10)                
--    ,PLC_SUP                NVARCHAR(3)
--    ,GST_REG_NUM            NVARCHAR(18)
--    ,REC_GST_REG_NUM        NVARCHAR(18)
--    ,AIC_STATUS             NVARCHAR(2)
    , [t_applicationId]       VARCHAR (32)
    , [t_jobId]               VARCHAR (36)
    , [t_jobDtm]             DATETIME
    , [t_jobBy]        NVARCHAR (128)
    , [t_filePath]            NVARCHAR (1024)
    , [t_extractionDtm]             DATETIME
    , CONSTRAINT [PK_OPT_VIM_1HEAD] PRIMARY KEY NONCLUSTERED (
    [MANDT], [DOCID]
  ) NOT ENFORCED
)
WITH ( 
  HEAP
)
