CREATE VIEW [base_s4h_cax].[vw_C_SalesDocumentItemDEX]
AS
with last_rows as (
    select max([TS_SEQUENCE_NUMBER]) as TS_SEQUENCE_NUMBER,
           max([t_extractionDtm])    as [t_extractionDtm],
           [MANDT],
           [SalesDocument],
           [SalesDocumentItem]
    from [base_s4h_cax].[C_SalesDocumentItemDEX_delta]
    group by [MANDT], [SalesDocument], [SalesDocumentItem]
)
select current_rows.[TS_SEQUENCE_NUMBER]
     , current_rows.[ODQ_CHANGEMODE]
     , current_rows.[ODQ_ENTITYCNTR]
     , current_rows.[MANDT]
     , current_rows.[SalesDocument]
     , current_rows.[SalesDocumentItem]
     , current_rows.[SDDocumentCategory]
     , current_rows.[SalesDocumentType]
     , current_rows.[SalesDocumentItemCategory]
     , current_rows.[IsReturnsItem]
     , current_rows.[CreationDate]
     , current_rows.[CreationTime]
     , current_rows.[LastChangeDate]
     , current_rows.[SalesOrganization]
     , current_rows.[DistributionChannel]
     , current_rows.[Division]
     , current_rows.[SalesGroup]
     , current_rows.[SalesOffice]
     , current_rows.[InternationalArticleNumber]
     , current_rows.[Batch]
     , current_rows.[Material]
     , current_rows.[OriginallyRequestedMaterial]
     , current_rows.[MaterialSubstitutionReason]
     , current_rows.[MaterialGroup]
     , current_rows.[AdditionalMaterialGroup1]
     , current_rows.[AdditionalMaterialGroup2]
     , current_rows.[AdditionalMaterialGroup3]
     , current_rows.[AdditionalMaterialGroup4]
     , current_rows.[AdditionalMaterialGroup5]
     , current_rows.[SoldToParty]
     , current_rows.[AdditionalCustomerGroup1]
     , current_rows.[AdditionalCustomerGroup2]
     , current_rows.[AdditionalCustomerGroup3]
     , current_rows.[AdditionalCustomerGroup4]
     , current_rows.[AdditionalCustomerGroup5]
     , current_rows.[ShipToParty]
     , current_rows.[PayerParty]
     , current_rows.[BillToParty]
     , current_rows.[SDDocumentReason]
     , current_rows.[SalesDocumentDate]
     , current_rows.[OrderQuantity]
     , current_rows.[OrderQuantityUnit]
     , current_rows.[TargetQuantity]
     , current_rows.[TargetQuantityUnit]
     , current_rows.[TargetToBaseQuantityDnmntr]
     , current_rows.[TargetToBaseQuantityNmrtr]
     , current_rows.[OrderToBaseQuantityDnmntr]
     , current_rows.[OrderToBaseQuantityNmrtr]
     , current_rows.[ConfdDelivQtyInOrderQtyUnit]
     , current_rows.[TargetDelivQtyInOrderQtyUnit]
     , current_rows.[ConfdDeliveryQtyInBaseUnit]
     , current_rows.[BaseUnit]
     , current_rows.[ItemGrossWeight]
     , current_rows.[ItemNetWeight]
     , current_rows.[ItemWeightUnit]
     , current_rows.[ItemVolume]
     , current_rows.[ItemVolumeUnit]
     , current_rows.[ServicesRenderedDate]
     , current_rows.[SalesDistrict]
     , current_rows.[CustomerGroup]
     , current_rows.[HdrOrderProbabilityInPercent]
     , current_rows.[ItemOrderProbabilityInPercent]
     , current_rows.[SalesDocumentRjcnReason]
     , current_rows.[PricingDate]
     , current_rows.[ExchangeRateDate]
     , current_rows.[PriceDetnExchangeRate]
     , current_rows.[StatisticalValueControl]
     , current_rows.[NetAmount]
     , current_rows.[TransactionCurrency]
     , current_rows.[SalesOrganizationCurrency]
     , current_rows.[NetPriceAmount]
     , current_rows.[NetPriceQuantity]
     , current_rows.[NetPriceQuantityUnit]
     , current_rows.[TaxAmount]
     , current_rows.[CostAmount]
     , current_rows.[Subtotal1Amount]
     , current_rows.[Subtotal2Amount]
     , current_rows.[Subtotal3Amount]
     , current_rows.[Subtotal4Amount]
     , current_rows.[Subtotal5Amount]
     , current_rows.[Subtotal6Amount]
     , current_rows.[ShippingPoint]
     , current_rows.[ShippingType]
     , current_rows.[DeliveryPriority]
     , current_rows.[InventorySpecialStockType]
     , current_rows.[RequestedDeliveryDate]
     , current_rows.[ShippingCondition]
     , current_rows.[DeliveryBlockReason]
     , current_rows.[Plant]
     , current_rows.[StorageLocation]
     , current_rows.[Route]
     , current_rows.[IncotermsClassification]
     , current_rows.[IncotermsVersion]
     , current_rows.[IncotermsTransferLocation]
     , current_rows.[IncotermsLocation1]
     , current_rows.[IncotermsLocation2]
     , current_rows.[MinDeliveryQtyInBaseUnit]
     , current_rows.[UnlimitedOverdeliveryIsAllowed]
     , current_rows.[OverdelivTolrtdLmtRatioInPct]
     , current_rows.[UnderdelivTolrtdLmtRatioInPct]
     , current_rows.[PartialDeliveryIsAllowed]
     , current_rows.[BindingPeriodValidityStartDate]
     , current_rows.[BindingPeriodValidityEndDate]
     , current_rows.[OutlineAgreementTargetAmount]
     , current_rows.[BillingDocumentDate]
     , current_rows.[BillingCompanyCode]
     , current_rows.[HeaderBillingBlockReason]
     , current_rows.[ItemBillingBlockReason]
     , current_rows.[FiscalYear]
     , current_rows.[FiscalPeriod]
     , current_rows.[CustomerAccountAssignmentGroup]
     , current_rows.[ExchangeRateType]
     , current_rows.[Currency]
     , current_rows.[FiscalYearVariant]
     , current_rows.[BusinessArea]
     , current_rows.[ProfitCenter]
     , current_rows.[OrderID]
     , current_rows.[ProfitabilitySegment]
     , current_rows.[ControllingArea]
     , current_rows.[ReferenceSDDocument]
     , current_rows.[ReferenceSDDocumentItem]
     , current_rows.[ReferenceSDDocumentCategory]
     , current_rows.[OriginSDDocument]
     , current_rows.[OriginSDDocumentItem]
     , current_rows.[OverallSDProcessStatus]
     , current_rows.[OverallTotalDeliveryStatus]
     , current_rows.[OverallOrdReltdBillgStatus]
     , current_rows.[TotalCreditCheckStatus]
     , current_rows.[DeliveryBlockStatus]
     , current_rows.[BillingBlockStatus]
     , current_rows.[TotalSDDocReferenceStatus]
     , current_rows.[SDDocReferenceStatus]
     , current_rows.[OverallSDDocumentRejectionSts]
     , current_rows.[SDDocumentRejectionStatus]
     , current_rows.[OverallTotalSDDocRefStatus]
     , current_rows.[OverallSDDocReferenceStatus]
     , current_rows.[ItemGeneralIncompletionStatus]
     , current_rows.[ItemBillingIncompletionStatus]
     , current_rows.[PricingIncompletionStatus]
     , current_rows.[ItemDeliveryIncompletionStatus]
     , current_rows.[SDoc_ControllingObject]
     , current_rows.[SDItem_ControllingObject]
     , current_rows.[CorrespncExternalReference]
     , current_rows.[t_applicationId]
     , current_rows.[t_jobId]
     , current_rows.[t_jobDtm]
     , current_rows.[t_jobBy]
     , current_rows.[t_extractionDtm]
     , current_rows.[t_filePath]
from last_rows
join [base_s4h_cax].[C_SalesDocumentItemDEX_delta] current_rows on
        current_rows.[TS_SEQUENCE_NUMBER] = last_rows.[TS_SEQUENCE_NUMBER]
        and current_rows.[t_extractionDtm] = last_rows.[t_extractionDtm]
        and current_rows.[MANDT] = last_rows.[MANDT]
        and current_rows.[SalesDocument] = last_rows.[SalesDocument]
        and current_rows.[SalesDocumentItem] = last_rows.[SalesDocumentItem]
