{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.128.1380.0 (24.04)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"srv_MeasureTypes\",\"srv_Cogs_cost\",\"Calendar\",\"Product\",\"ProfitCenter\",\"CustomerSoldTo\",\"fact_ACDOCA_EPMSalesView\",\"_Measures\",\"SalesOrganization\",\"Source\",\"DB\",\"SalesDistrict\",\"GLAccount\",\"RLS_GROUPS\",\"RLS_USERS\",\"ExQLReportingEntity\",\"exQL_Map\",\"CompanyCode\",\"DateStart\",\"fact_ACDOCA_FinStatemntSalesMargin\",\"Calendar_cut\",\"CompanyCodeProfitCenter\",\"Currency\",\"CurrencyType\",\"fact_Budget_EPM\",\"ValueType\",\"InOut\",\"GM Element Sort\",\"Reconciliation_File\",\"GM Element 2 Sorting\",\"srv_Actual_Finance\",\"ProductPlant\",\"Plant\",\"ProductSalesDelivery\",\"RangeStart\",\"RangeEnd\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Source",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"ws-xxxx-sls-a-euw-001.sql.azuresynapse.net\" meta [IsParameterQuery=true, List={\"ws-xxxx-sls-p-euw-001.sql.azuresynapse.net\", \"ws-xxxx-sls-d-euw-001.sql.azuresynapse.net\", \"ws-xxxx-sls-a-euw-001.sql.azuresynapse.net\", \"ws-sleshchuk-d-euw-001.sql.azuresynapse.net\", \"ws-nkukhtenko-d-euw-001.sql.azuresynapse.net\"}, DefaultValue=\"ws-xxxx-sls-p-euw-001.sql.azuresynapse.net\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "51c1eca3-85e3-40a5-9886-bc7b2858932e"
      },
      {
        "name": "DB",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"syndw_xxxx_sls_a_euw_001\" meta [IsParameterQuery=true, List={\"syndw_xxxx_sls_p_euw_001\", \"syndw_xxxx_sls_d_euw_001\", \"syndw_xxxx_sls_a_euw_001\", \"syndw_sleshchuk_d_euw_001\", \"syndw_nkukhtenko_d_euw_001\"}, DefaultValue=\"syndw_xxxx_sls_p_euw_001\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "59565eac-ed26-41a4-b712-5d399b142541"
      },
      {
        "name": "DateStart",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": "#date(2023, 1, 1) meta [IsParameterQuery=true, List={#date(2022, 1, 1), #date(2023, 7, 1)}, DefaultValue=#date(2022, 1, 1), Type=\"Date\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "c9feb069-310a-4c6c-837c-4c88984121b8"
      },
      {
        "name": "RangeStart",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "DateTime"
          }
        ],
        "expression": "#datetime(2024, 3, 1, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=false]",
        "kind": "m",
        "lineageTag": "9e7502f8-46af-4416-984c-6f0f8dc5d65e"
      },
      {
        "name": "RangeEnd",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "DateTime"
          }
        ],
        "expression": "#datetime(2024, 3, 31, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=false]",
        "kind": "m",
        "lineageTag": "9aeac4dd-6100-4e33-b8a9-88c22166d42b"
      }
    ],
    "perspectives": [
      {
        "name": "Sales View",
        "tables": [
          {
            "name": "SalesOrganization",
            "columns": [
              {
                "name": "RegionName"
              },
              {
                "name": "SalesOrganizationID"
              },
              {
                "name": "SalesOrganization"
              }
            ]
          },
          {
            "name": "Product",
            "columns": [
              {
                "name": "Product_L1_PillarID"
              },
              {
                "name": "Product_L2_Group"
              },
              {
                "name": "Product_L2_GroupID"
              },
              {
                "name": "Product_L3_Type"
              },
              {
                "name": "Product_L3_TypeID"
              },
              {
                "name": "Product_L4_Family"
              },
              {
                "name": "Product_L4_FamilyID"
              },
              {
                "name": "Product_L5_SubFamily"
              },
              {
                "name": "Product_L5_SubFamilyID"
              },
              {
                "name": "ProductID"
              },
              {
                "name": "ProductID_Name"
              },
              {
                "name": "Product_L1_Pillar"
              },
              {
                "name": "Product"
              },
              {
                "name": "MaterialType"
              },
              {
                "name": "MaterialTypeID"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Month"
              },
              {
                "name": "MonthName"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "Week calc"
              },
              {
                "name": "Year"
              }
            ]
          },
          {
            "name": "fact_ACDOCA_EPMSalesView",
            "columns": [
              {
                "name": "Application"
              },
              {
                "name": "BillingDocumentTypeID"
              },
              {
                "name": "Brand"
              },
              {
                "name": "InOutID"
              },
              {
                "name": "SalesDocumentID"
              },
              {
                "name": "t_extractionDtm"
              },
              {
                "name": "ReferenceDocumentTypeID"
              },
              {
                "name": "AccountingDocument"
              },
              {
                "name": "AccountingDocumentTypeID"
              },
              {
                "name": "Amount"
              },
              {
                "name": "AmountCategory"
              },
              {
                "name": "AmountInGlobalCurrency"
              },
              {
                "name": "BalanceTransactionCurrency"
              },
              {
                "name": "BaseUnit"
              },
              {
                "name": "BillingDocumentType"
              },
              {
                "name": "BillToPartyID"
              },
              {
                "name": "BrandID"
              },
              {
                "name": "BusinessTransactionTypeID"
              },
              {
                "name": "Source"
              },
              {
                "name": "ClearingDate"
              },
              {
                "name": "COGSActCostAmount"
              },
              {
                "name": "COGSStdCostAmount"
              },
              {
                "name": "CompanyCodeID"
              },
              {
                "name": "CostCenterID"
              },
              {
                "name": "CreationDate"
              },
              {
                "name": "CurrencyID"
              },
              {
                "name": "CurrencyType"
              },
              {
                "name": "CurrencyTypeID"
              },
              {
                "name": "CustomerFlag"
              },
              {
                "name": "CustomerGroup"
              },
              {
                "name": "CustomerGroupID"
              },
              {
                "name": "CustomerID"
              },
              {
                "name": "DebitCreditID"
              },
              {
                "name": "DistributionChannelID"
              },
              {
                "name": "DocumentDate"
              },
              {
                "name": "DocumentItemText"
              },
              {
                "name": "ExchangeRateDate"
              },
              {
                "name": "FiscalPeriod"
              },
              {
                "name": "FiscalYear"
              },
              {
                "name": "FiscalYearPeriod"
              },
              {
                "name": "FunctionalAreaID"
              },
              {
                "name": "GLAccountID"
              },
              {
                "name": "GLAccountTypeID"
              },
              {
                "name": "IsReversal"
              },
              {
                "name": "IsReversed"
              },
              {
                "name": "LedgerFiscalYear"
              },
              {
                "name": "LedgerGLLineItem"
              },
              {
                "name": "ManualAdjustment"
              },
              {
                "name": "OtherCoSAmount"
              },
              {
                "name": "PartnerCompanyCodeID"
              },
              {
                "name": "PartnerCompanyID"
              },
              {
                "name": "PlantID"
              },
              {
                "name": "PostingDate"
              },
              {
                "name": "ProductFlag"
              },
              {
                "name": "ProductID"
              },
              {
                "name": "ProfitCenterID"
              },
              {
                "name": "PurchasingDocument"
              },
              {
                "name": "PurchasingDocumentItem"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "ReferenceDocument"
              },
              {
                "name": "ReferenceDocumentItem"
              },
              {
                "name": "ReversalReferenceDocument"
              },
              {
                "name": "SalesAmount"
              },
              {
                "name": "SalesDistrictID"
              },
              {
                "name": "SalesDocumentItemID"
              },
              {
                "name": "SalesOrganizationID"
              },
              {
                "name": "ShipToParty"
              },
              {
                "name": "SourceLedgerID"
              },
              {
                "name": "SupplierID"
              },
              {
                "name": "t_applicationId"
              },
              {
                "name": "TPAdjustment"
              },
              {
                "name": "CustomerCategory"
              },
              {
                "name": "SoldProduct"
              },
              {
                "name": "HigherLevelItem"
              },
              {
                "name": "SalesReferenceDocumentCalculated"
              },
              {
                "name": "SalesReferenceDocumentItemCalculated"
              },
              {
                "name": "GMElementL1"
              },
              {
                "name": "GMElementL2"
              }
            ]
          },
          {
            "name": "_Measures",
            "measures": [
              {
                "name": "BillingDocsNumber"
              },
              {
                "name": "Billing Docs per Order"
              },
              {
                "name": "CitySelected"
              },
              {
                "name": "CustomerAmount"
              },
              {
                "name": "Sales"
              },
              {
                "name": "OrderAmount"
              },
              {
                "name": "SelectedPeriod"
              },
              {
                "name": "Amount cy"
              },
              {
                "name": "Amount PY"
              },
              {
                "name": "Cogs"
              },
              {
                "name": "Cogs a/c"
              },
              {
                "name": "COGS a/c PY"
              },
              {
                "name": "COGS PY"
              },
              {
                "name": "cogs_switch"
              },
              {
                "name": "cogs_switch_py"
              },
              {
                "name": "DeltaCogs"
              },
              {
                "name": "DeltaCogs a/c"
              },
              {
                "name": "DeltaGrossProfit"
              },
              {
                "name": "DeltaOtherCOS"
              },
              {
                "name": "GrossProfit"
              },
              {
                "name": "GrossProfit PY"
              },
              {
                "name": "Sales PY"
              },
              {
                "name": "NetAmount PY YTD"
              },
              {
                "name": "NetAmount YTD"
              },
              {
                "name": "OtherCOS"
              },
              {
                "name": "OtherCOS PY"
              },
              {
                "name": "SalesMargin"
              },
              {
                "name": "SalesMargin PY"
              },
              {
                "name": "DeltaSalesMargin"
              },
              {
                "name": "DeltaSalesMargint%"
              },
              {
                "name": "DeltaNetAmount%"
              },
              {
                "name": "Sales Margin %"
              },
              {
                "name": "KPI PY"
              }
            ]
          },
          {
            "name": "exQL_Map",
            "columns": [
              {
                "name": "ExQLAccount"
              },
              {
                "name": "ExQLNode"
              },
              {
                "name": "GM element L1"
              },
              {
                "name": "GM element L2"
              }
            ]
          },
          {
            "name": "CustomerSoldTo",
            "columns": [
              {
                "name": "CustomerID"
              },
              {
                "name": "Customer"
              },
              {
                "name": "CustomerAccountGroupID"
              },
              {
                "name": "AccountGroup"
              },
              {
                "name": "AuthorizationGroupID"
              },
              {
                "name": "AuthorizationGroup"
              },
              {
                "name": "DeliveryIsBlocked"
              },
              {
                "name": "PostingIsBlocked"
              },
              {
                "name": "BillingIsBlockedForCustomer"
              },
              {
                "name": "OrderIsBlockedForCustomer"
              },
              {
                "name": "IsOneTimeAccount"
              },
              {
                "name": "CountryID"
              },
              {
                "name": "Country"
              },
              {
                "name": "CityName"
              },
              {
                "name": "PostalCode"
              },
              {
                "name": "StreetName"
              },
              {
                "name": "RegionID"
              },
              {
                "name": "Region"
              },
              {
                "name": "DeletionIndicator"
              },
              {
                "name": "TradingPartnerID"
              },
              {
                "name": "TradingPartner"
              },
              {
                "name": "BusinessType"
              },
              {
                "name": "IndustryType"
              },
              {
                "name": "t_jobDtm"
              },
              {
                "name": "CustomerID_Name"
              },
              {
                "name": "t_applicationId"
              },
              {
                "name": "t_extractionDtm"
              },
              {
                "name": "Column"
              }
            ]
          },
          {
            "name": "fact_ACDOCA_FinStatemntSalesMargin",
            "columns": [
              {
                "name": "CompanyCodeID"
              },
              {
                "name": "ProfitCenterID"
              },
              {
                "name": "ProfitCenter"
              },
              {
                "name": "GLAccountID"
              },
              {
                "name": "FunctionalAreaID"
              },
              {
                "name": "CurrencyID"
              },
              {
                "name": "SAP_Sales"
              },
              {
                "name": "SAP_COGS"
              },
              {
                "name": "SAP_SalesMargin"
              },
              {
                "name": "FiscalYear"
              },
              {
                "name": "FiscalYearPeriod"
              },
              {
                "name": "t_applicationId"
              },
              {
                "name": "t_extractionDtm"
              },
              {
                "name": "CompanyCodeProfitCenterID"
              }
            ]
          },
          {
            "name": "CompanyCodeProfitCenter",
            "columns": [
              {
                "name": "CompanyCodeID"
              },
              {
                "name": "ProfitCenterID"
              },
              {
                "name": "SKReportingEntityKey"
              },
              {
                "name": "ExQLReportingEntity"
              }
            ]
          },
          {
            "name": "ProductPlant",
            "columns": [
              {
                "name": "Plant"
              },
              {
                "name": "Product"
              },
              {
                "name": "ProcurementType"
              },
              {
                "name": "PurchasingGroup"
              },
              {
                "name": "SpecialProcurementType"
              }
            ]
          },
          {
            "name": "Plant",
            "columns": [
              {
                "name": "Plant"
              },
              {
                "name": "PlantID"
              }
            ]
          },
          {
            "name": "ProductSalesDelivery",
            "columns": [
              {
                "name": "ItemCategoryGroupName"
              },
              {
                "name": "ItemCategoryGroup"
              }
            ]
          }
        ]
      },
      {
        "name": "Sales View Advanced",
        "tables": [
          {
            "name": "SalesOrganization",
            "columns": [
              {
                "name": "RegionName"
              },
              {
                "name": "SalesOrganizationID"
              },
              {
                "name": "SalesOrganization"
              }
            ]
          },
          {
            "name": "Product",
            "columns": [
              {
                "name": "Product_L1_PillarID"
              },
              {
                "name": "Product_L2_Group"
              },
              {
                "name": "Product_L2_GroupID"
              },
              {
                "name": "Product_L3_Type"
              },
              {
                "name": "Product_L3_TypeID"
              },
              {
                "name": "Product_L4_Family"
              },
              {
                "name": "Product_L4_FamilyID"
              },
              {
                "name": "Product_L5_SubFamily"
              },
              {
                "name": "Product_L5_SubFamilyID"
              },
              {
                "name": "ProductID"
              },
              {
                "name": "ProductID_Name"
              },
              {
                "name": "Product_L1_Pillar"
              },
              {
                "name": "Product"
              },
              {
                "name": "MaterialType"
              },
              {
                "name": "MaterialTypeID"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Month"
              },
              {
                "name": "MonthName"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "Week calc"
              },
              {
                "name": "Year"
              }
            ]
          },
          {
            "name": "fact_ACDOCA_EPMSalesView",
            "columns": [
              {
                "name": "Application"
              },
              {
                "name": "BillingDocumentTypeID"
              },
              {
                "name": "Brand"
              },
              {
                "name": "InOutID"
              },
              {
                "name": "SalesDocumentID"
              },
              {
                "name": "t_extractionDtm"
              },
              {
                "name": "ReferenceDocumentTypeID"
              },
              {
                "name": "AccountingDocument"
              },
              {
                "name": "AccountingDocumentTypeID"
              },
              {
                "name": "Amount"
              },
              {
                "name": "AmountCategory"
              },
              {
                "name": "AmountInGlobalCurrency"
              },
              {
                "name": "BalanceTransactionCurrency"
              },
              {
                "name": "BaseUnit"
              },
              {
                "name": "BillingDocumentType"
              },
              {
                "name": "BillToPartyID"
              },
              {
                "name": "BrandID"
              },
              {
                "name": "BusinessTransactionTypeID"
              },
              {
                "name": "Source"
              },
              {
                "name": "ClearingDate"
              },
              {
                "name": "COGSActCostAmount"
              },
              {
                "name": "COGSStdCostAmount"
              },
              {
                "name": "CompanyCodeID"
              },
              {
                "name": "CostCenterID"
              },
              {
                "name": "CreationDate"
              },
              {
                "name": "CurrencyID"
              },
              {
                "name": "CurrencyType"
              },
              {
                "name": "CurrencyTypeID"
              },
              {
                "name": "CustomerFlag"
              },
              {
                "name": "CustomerGroup"
              },
              {
                "name": "CustomerGroupID"
              },
              {
                "name": "CustomerID"
              },
              {
                "name": "DebitCreditID"
              },
              {
                "name": "DistributionChannelID"
              },
              {
                "name": "DocumentDate"
              },
              {
                "name": "DocumentItemText"
              },
              {
                "name": "ExchangeRateDate"
              },
              {
                "name": "FiscalPeriod"
              },
              {
                "name": "FiscalYear"
              },
              {
                "name": "FiscalYearPeriod"
              },
              {
                "name": "FunctionalAreaID"
              },
              {
                "name": "GLAccountID"
              },
              {
                "name": "GLAccountTypeID"
              },
              {
                "name": "IsReversal"
              },
              {
                "name": "IsReversed"
              },
              {
                "name": "LedgerFiscalYear"
              },
              {
                "name": "LedgerGLLineItem"
              },
              {
                "name": "ManualAdjustment"
              },
              {
                "name": "OtherCoSAmount"
              },
              {
                "name": "PartnerCompanyCodeID"
              },
              {
                "name": "PartnerCompanyID"
              },
              {
                "name": "PlantID"
              },
              {
                "name": "PostingDate"
              },
              {
                "name": "ProductFlag"
              },
              {
                "name": "ProductID"
              },
              {
                "name": "ProfitCenterID"
              },
              {
                "name": "PurchasingDocument"
              },
              {
                "name": "PurchasingDocumentItem"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "ReferenceDocument"
              },
              {
                "name": "ReferenceDocumentItem"
              },
              {
                "name": "ReversalReferenceDocument"
              },
              {
                "name": "SalesAmount"
              },
              {
                "name": "SalesDistrictID"
              },
              {
                "name": "SalesDocumentItemID"
              },
              {
                "name": "SalesOrganizationID"
              },
              {
                "name": "ShipToParty"
              },
              {
                "name": "SourceLedgerID"
              },
              {
                "name": "SupplierID"
              },
              {
                "name": "t_applicationId"
              },
              {
                "name": "TPAdjustment"
              },
              {
                "name": "CustomerCategory"
              },
              {
                "name": "SoldProduct"
              },
              {
                "name": "HigherLevelItem"
              },
              {
                "name": "SalesReferenceDocumentCalculated"
              },
              {
                "name": "SalesReferenceDocumentItemCalculated"
              },
              {
                "name": "GMElementL1"
              },
              {
                "name": "GMElementL2"
              }
            ]
          },
          {
            "name": "_Measures",
            "measures": [
              {
                "name": "Sales Margin %"
              },
              {
                "name": "KPI PY"
              }
            ]
          },
          {
            "name": "exQL_Map",
            "columns": [
              {
                "name": "ExQLAccount"
              },
              {
                "name": "ExQLNode"
              },
              {
                "name": "GM element L1"
              },
              {
                "name": "GM element L2"
              }
            ]
          },
          {
            "name": "CustomerSoldTo",
            "columns": [
              {
                "name": "CustomerID"
              },
              {
                "name": "Customer"
              },
              {
                "name": "CustomerAccountGroupID"
              },
              {
                "name": "AccountGroup"
              },
              {
                "name": "AuthorizationGroupID"
              },
              {
                "name": "AuthorizationGroup"
              },
              {
                "name": "DeliveryIsBlocked"
              },
              {
                "name": "PostingIsBlocked"
              },
              {
                "name": "BillingIsBlockedForCustomer"
              },
              {
                "name": "OrderIsBlockedForCustomer"
              },
              {
                "name": "IsOneTimeAccount"
              },
              {
                "name": "CountryID"
              },
              {
                "name": "Country"
              },
              {
                "name": "CityName"
              },
              {
                "name": "PostalCode"
              },
              {
                "name": "StreetName"
              },
              {
                "name": "RegionID"
              },
              {
                "name": "Region"
              },
              {
                "name": "DeletionIndicator"
              },
              {
                "name": "TradingPartnerID"
              },
              {
                "name": "TradingPartner"
              },
              {
                "name": "BusinessType"
              },
              {
                "name": "IndustryType"
              },
              {
                "name": "t_jobDtm"
              },
              {
                "name": "CustomerID_Name"
              },
              {
                "name": "t_applicationId"
              },
              {
                "name": "t_extractionDtm"
              },
              {
                "name": "Column"
              }
            ]
          },
          {
            "name": "fact_ACDOCA_FinStatemntSalesMargin",
            "columns": [
              {
                "name": "CompanyCodeID"
              },
              {
                "name": "ProfitCenterID"
              },
              {
                "name": "ProfitCenter"
              },
              {
                "name": "GLAccountID"
              },
              {
                "name": "FunctionalAreaID"
              },
              {
                "name": "CurrencyID"
              },
              {
                "name": "SAP_Sales"
              },
              {
                "name": "SAP_COGS"
              },
              {
                "name": "SAP_SalesMargin"
              },
              {
                "name": "FiscalYear"
              },
              {
                "name": "FiscalYearPeriod"
              },
              {
                "name": "t_applicationId"
              },
              {
                "name": "t_extractionDtm"
              },
              {
                "name": "CompanyCodeProfitCenterID"
              }
            ]
          },
          {
            "name": "CompanyCodeProfitCenter",
            "columns": [
              {
                "name": "CompanyCodeID"
              },
              {
                "name": "ProfitCenterID"
              },
              {
                "name": "SKReportingEntityKey"
              },
              {
                "name": "ExQLReportingEntity"
              }
            ]
          },
          {
            "name": "ProductPlant",
            "columns": [
              {
                "name": "Plant"
              },
              {
                "name": "Product"
              },
              {
                "name": "ProcurementType"
              },
              {
                "name": "PurchasingGroup"
              },
              {
                "name": "SpecialProcurementType"
              }
            ]
          },
          {
            "name": "Plant",
            "columns": [
              {
                "name": "Plant"
              },
              {
                "name": "PlantID"
              }
            ]
          },
          {
            "name": "ProductSalesDelivery",
            "columns": [
              {
                "name": "ItemCategoryGroupName"
              },
              {
                "name": "ItemCategoryGroup"
              }
            ]
          }
        ]
      },
      {
        "name": "EPM Sales View",
        "tables": [
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Date"
              },
              {
                "name": "Year"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "MonthNumber"
              },
              {
                "name": "Month"
              },
              {
                "name": "Week"
              },
              {
                "name": "Day"
              },
              {
                "name": "YearMonth"
              },
              {
                "name": "YearQuarter"
              },
              {
                "name": "YearWeek"
              },
              {
                "name": "WeekDay"
              },
              {
                "name": "FirstDayOfWeekDate"
              },
              {
                "name": "FirstDayOfMonthDate"
              },
              {
                "name": "CalendarDayOfYear"
              },
              {
                "name": "YearDay"
              },
              {
                "name": "WeekNumber"
              },
              {
                "name": "12 months before date"
              },
              {
                "name": "Today"
              },
              {
                "name": "MonthYear"
              },
              {
                "name": "YTD"
              },
              {
                "name": "CurrentDay_Filter"
              },
              {
                "name": "Month_Short"
              },
              {
                "name": "MonthNumber_oder"
              },
              {
                "name": "MonthName"
              },
              {
                "name": "Trend Filter"
              },
              {
                "name": "Week calc"
              },
              {
                "name": "Previous year"
              }
            ],
            "hierarchies": [
              {
                "name": "Date Hierarchy"
              }
            ]
          },
          {
            "name": "Product",
            "columns": [
              {
                "name": "ProductID"
              },
              {
                "name": "ProductExternalID"
              },
              {
                "name": "Product"
              },
              {
                "name": "MaterialTypeID"
              },
              {
                "name": "MaterialType"
              },
              {
                "name": "IsMarkedForDeletion"
              },
              {
                "name": "CrossPlantStatus"
              },
              {
                "name": "GrossWeight"
              },
              {
                "name": "SourceOfSupply"
              },
              {
                "name": "CountryOfOrigin"
              },
              {
                "name": "CompetitorID"
              },
              {
                "name": "MaterialGroup"
              },
              {
                "name": "BaseUnit"
              },
              {
                "name": "ItemCategoryGroup"
              },
              {
                "name": "ProductHierarchy"
              },
              {
                "name": "Product_L1_PillarID"
              },
              {
                "name": "Product_L2_GroupID"
              },
              {
                "name": "Product_L3_TypeID"
              },
              {
                "name": "Product_L4_FamilyID"
              },
              {
                "name": "Product_L5_SubFamilyID"
              },
              {
                "name": "Product_L1_Pillar"
              },
              {
                "name": "Product_L2_Group"
              },
              {
                "name": "Product_L3_Type"
              },
              {
                "name": "Product_L4_Family"
              },
              {
                "name": "Product_L5_SubFamily"
              },
              {
                "name": "ProductCategory"
              },
              {
                "name": "Brand"
              },
              {
                "name": "IndustryStandardName"
              },
              {
                "name": "ProductStandardID"
              },
              {
                "name": "InternationalArticleNumberCat"
              },
              {
                "name": "ProductIsConfigurable"
              },
              {
                "name": "IsBatchManagementRequired"
              },
              {
                "name": "ExternalProductGroup"
              },
              {
                "name": "CrossPlantConfigurableProduct"
              },
              {
                "name": "ProductManufacturerNumber"
              },
              {
                "name": "ManufacturerNumber"
              },
              {
                "name": "MaximumPackagingLength"
              },
              {
                "name": "MaximumPackagingWidth"
              },
              {
                "name": "MaximumPackagingHeight"
              },
              {
                "name": "MaximumCapacity"
              },
              {
                "name": "OvercapacityTolerance"
              },
              {
                "name": "UnitForMaxPackagingDimensions"
              },
              {
                "name": "BaseUnitSpecificProductLength"
              },
              {
                "name": "BaseUnitSpecificProductWidth"
              },
              {
                "name": "BaseUnitSpecificProductHeight"
              },
              {
                "name": "ArticleCategory"
              },
              {
                "name": "ProductIsLocked"
              },
              {
                "name": "BasicMaterial"
              },
              {
                "name": "SalesProduct"
              },
              {
                "name": "ZZ1_CustomFieldRiskMit_PRD"
              },
              {
                "name": "ZZ1_CustomFieldHighRis_PRD"
              },
              {
                "name": "ZZ1_CustomFieldRiskRea_PRD"
              },
              {
                "name": "t_jobDtm"
              },
              {
                "name": "ID_Product"
              },
              {
                "name": "ProductID_Name"
              },
              {
                "name": "t_applicationId"
              },
              {
                "name": "t_extractionDtm"
              },
              {
                "name": "sk_dim_Product"
              },
              {
                "name": "CreationDate"
              },
              {
                "name": "NetWeight"
              },
              {
                "name": "IndustrySector"
              },
              {
                "name": "WeightUnit"
              },
              {
                "name": "Division"
              },
              {
                "name": "TransportationGroup"
              },
              {
                "name": "CreatedByUser"
              },
              {
                "name": "CrossPlantStatusID"
              },
              {
                "name": "ItemCategoryGroupName"
              }
            ],
            "hierarchies": [
              {
                "name": "Product Hierarchy"
              }
            ]
          },
          {
            "name": "CustomerSoldTo",
            "columns": [
              {
                "name": "CustomerID"
              },
              {
                "name": "Customer"
              },
              {
                "name": "CustomerAccountGroupID"
              },
              {
                "name": "AccountGroup"
              },
              {
                "name": "AuthorizationGroupID"
              },
              {
                "name": "AuthorizationGroup"
              },
              {
                "name": "DeliveryIsBlocked"
              },
              {
                "name": "PostingIsBlocked"
              },
              {
                "name": "BillingIsBlockedForCustomer"
              },
              {
                "name": "OrderIsBlockedForCustomer"
              },
              {
                "name": "IsOneTimeAccount"
              },
              {
                "name": "CountryID"
              },
              {
                "name": "Country"
              },
              {
                "name": "CityName"
              },
              {
                "name": "PostalCode"
              },
              {
                "name": "StreetName"
              },
              {
                "name": "RegionID"
              },
              {
                "name": "Region"
              },
              {
                "name": "DeletionIndicator"
              },
              {
                "name": "TradingPartnerID"
              },
              {
                "name": "TradingPartner"
              },
              {
                "name": "BusinessType"
              },
              {
                "name": "IndustryType"
              },
              {
                "name": "t_jobDtm"
              },
              {
                "name": "CustomerID_Name"
              },
              {
                "name": "t_applicationId"
              },
              {
                "name": "t_extractionDtm"
              },
              {
                "name": "Column"
              }
            ]
          },
          {
            "name": "fact_ACDOCA_EPMSalesView",
            "columns": [
              {
                "name": "BillingDocumentTypeID"
              },
              {
                "name": "CreationDate"
              },
              {
                "name": "SalesOrganizationID"
              },
              {
                "name": "DistributionChannelID"
              },
              {
                "name": "PlantID"
              },
              {
                "name": "FiscalYear"
              },
              {
                "name": "FiscalPeriod"
              },
              {
                "name": "CurrencyID"
              },
              {
                "name": "SalesDocumentID"
              },
              {
                "name": "SalesDocumentItemID"
              },
              {
                "name": "SalesDistrictID"
              },
              {
                "name": "CustomerGroup"
              },
              {
                "name": "t_applicationId"
              },
              {
                "name": "Application"
              },
              {
                "name": "t_extractionDtm"
              },
              {
                "name": "InOutID"
              },
              {
                "name": "Brand"
              },
              {
                "name": "SourceLedgerID"
              },
              {
                "name": "CompanyCodeID"
              },
              {
                "name": "AccountingDocument"
              },
              {
                "name": "LedgerGLLineItem"
              },
              {
                "name": "LedgerFiscalYear"
              },
              {
                "name": "BusinessTransactionTypeID"
              },
              {
                "name": "ReferenceDocumentTypeID"
              },
              {
                "name": "ReferenceDocument"
              },
              {
                "name": "ReferenceDocumentItem"
              },
              {
                "name": "IsReversal"
              },
              {
                "name": "IsReversed"
              },
              {
                "name": "ReversalReferenceDocument"
              },
              {
                "name": "GLAccountID"
              },
              {
                "name": "CostCenterID"
              },
              {
                "name": "ProfitCenterID"
              },
              {
                "name": "FunctionalAreaID"
              },
              {
                "name": "PartnerCompanyID"
              },
              {
                "name": "BalanceTransactionCurrency"
              },
              {
                "name": "AmountInGlobalCurrency"
              },
              {
                "name": "BaseUnit"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "DebitCreditID"
              },
              {
                "name": "FiscalYearPeriod"
              },
              {
                "name": "PostingDate"
              },
              {
                "name": "DocumentDate"
              },
              {
                "name": "AccountingDocumentTypeID"
              },
              {
                "name": "GLAccountTypeID"
              },
              {
                "name": "PurchasingDocument"
              },
              {
                "name": "PurchasingDocumentItem"
              },
              {
                "name": "DocumentItemText"
              },
              {
                "name": "ProductID"
              },
              {
                "name": "SupplierID"
              },
              {
                "name": "CustomerID"
              },
              {
                "name": "ExchangeRateDate"
              },
              {
                "name": "ClearingDate"
              },
              {
                "name": "PartnerCompanyCodeID"
              },
              {
                "name": "BillToPartyID"
              },
              {
                "name": "ShipToParty"
              },
              {
                "name": "ManualAdjustment"
              },
              {
                "name": "TPAdjustment"
              },
              {
                "name": "CurrencyTypeID"
              },
              {
                "name": "SalesAmount"
              },
              {
                "name": "CurrencyType"
              },
              {
                "name": "BillingDocumentType"
              },
              {
                "name": "BrandID"
              },
              {
                "name": "CustomerGroupID"
              },
              {
                "name": "COGSActCostAmount"
              },
              {
                "name": "COGSStdCostAmount"
              },
              {
                "name": "OtherCoSAmount"
              },
              {
                "name": "AmountCategory"
              },
              {
                "name": "Amount"
              },
              {
                "name": "ProductFlag"
              },
              {
                "name": "CustomerFlag"
              },
              {
                "name": "Source"
              },
              {
                "name": "OpexAmount"
              },
              {
                "name": "GrossMarginAmount"
              },
              {
                "name": "Subsource"
              },
              {
                "name": "SKReportingEntityKey"
              },
              {
                "name": "ProductSurrogateKey"
              },
              {
                "name": "SalesOfficeID"
              },
              {
                "name": "SubSourceShort"
              },
              {
                "name": "nk_ExQLmap"
              },
              {
                "name": "SoldProduct"
              },
              {
                "name": "CustomerCategory"
              },
              {
                "name": "ProjectNumber"
              },
              {
                "name": "ProjectNumberCalculated"
              },
              {
                "name": "HigherLevelItem"
              },
              {
                "name": "SalesDocumentItemCategoryID"
              },
              {
                "name": "SalesReferenceDocumentCalculated"
              },
              {
                "name": "SalesReferenceDocumentItemCalculated"
              },
              {
                "name": "GMElementL1"
              },
              {
                "name": "GMElementL2"
              }
            ]
          },
          {
            "name": "_Measures",
            "columns": [
              {
                "name": "Measures"
              }
            ],
            "measures": [
              {
                "name": "Sales"
              },
              {
                "name": "Sales PY"
              },
              {
                "name": "DeltaNetAmount"
              },
              {
                "name": "DeltaNetAmount%"
              },
              {
                "name": "DeltaMargin"
              },
              {
                "name": "KPI"
              },
              {
                "name": "KPI PY"
              },
              {
                "name": "LastUpdated"
              },
              {
                "name": "DeltaMargin%"
              },
              {
                "name": "BillingDocsNumber"
              },
              {
                "name": "BillingDocsNumber PY"
              },
              {
                "name": "DeltaBillingDocsNumber%"
              },
              {
                "name": "OrderAmount"
              },
              {
                "name": "OrderAmount PY"
              },
              {
                "name": "DeltaOrdersAmount%"
              },
              {
                "name": "Sales&MarginsK"
              },
              {
                "name": "DeltaSales&Margins%"
              },
              {
                "name": "DeltaSales&MarginsNegative"
              },
              {
                "name": "DeltaSales&MarginsPositive"
              },
              {
                "name": "Sales&MarginsRank"
              },
              {
                "name": "Sales&MarginsRank PY"
              },
              {
                "name": "DeltaKPIRank"
              },
              {
                "name": "DeltaSales&MarginsRankSign"
              },
              {
                "name": "CustomerAmount"
              },
              {
                "name": "CustomerAmount PY"
              },
              {
                "name": "DeltaCustomerAmount%"
              },
              {
                "name": "MsgCurrentCurrency"
              },
              {
                "name": "CurrentCurrency_Int"
              },
              {
                "name": "Slicer_filter"
              },
              {
                "name": "KPI Delta"
              },
              {
                "name": "Title_SalesDistrict"
              },
              {
                "name": "Title_Country"
              },
              {
                "name": "Sales&MarginsK PY"
              },
              {
                "name": "MsgCurrentCountry"
              },
              {
                "name": "Billing Docs per Order"
              },
              {
                "name": "Billing Docs per Order PY"
              },
              {
                "name": "Billing Docs per Order Delta"
              },
              {
                "name": "Title_Project"
              },
              {
                "name": "Title_Product"
              },
              {
                "name": "Title_Customer"
              },
              {
                "name": "Title_tooltip_chart"
              },
              {
                "name": "Title_tooltip_chart_week"
              },
              {
                "name": "Title_YTD"
              },
              {
                "name": "Title_YTD_week"
              },
              {
                "name": "Title_YTD_Delta"
              },
              {
                "name": "SelectedPeriod"
              },
              {
                "name": "SelectedValue_Application"
              },
              {
                "name": "SelectedValue_SalesOrganization"
              },
              {
                "name": "SelectedValue_Product"
              },
              {
                "name": "SelectedValue_Period"
              },
              {
                "name": "SelectedValue_SalesDistrict"
              },
              {
                "name": "SelectedYear"
              },
              {
                "name": "SelectedValue_Region"
              },
              {
                "name": "SelectedValue_KPI"
              },
              {
                "name": "SelectedValue_Customer"
              },
              {
                "name": "SelectevValue_CurrencyType"
              },
              {
                "name": "SelectedValue_MaterialType"
              },
              {
                "name": "SelectedValue_BillingDocType"
              },
              {
                "name": "Sales&MarginsCustomerRank"
              },
              {
                "name": "Sales&MarginsCustomerRank PY"
              },
              {
                "name": "DeltaSales&MarginsCustomerRankSign"
              },
              {
                "name": "DeltaKPICustomerRank"
              },
              {
                "name": "CustomerSelected"
              },
              {
                "name": "CitySelected"
              },
              {
                "name": "CustomerRankFilter"
              },
              {
                "name": "KPI Delta color"
              },
              {
                "name": "AmountInCompanyCodeCurrency"
              },
              {
                "name": "SelectedValue_inoutid"
              },
              {
                "name": "SelectedValue_glaccountid"
              },
              {
                "name": "SelectedValue_acdoca_ledger"
              },
              {
                "name": "SelectedValue_acdoca_tpadjustment"
              },
              {
                "name": "SelectedValue_acdoca_ma_adjustment"
              },
              {
                "name": "SelectedValue_profit_center"
              },
              {
                "name": "SelectedValue_product_group"
              },
              {
                "name": "SelectedValue_product_pillar"
              },
              {
                "name": "SelectedValue_brand"
              },
              {
                "name": "NetAmount YTD"
              },
              {
                "name": "NetAmount PY YTD"
              },
              {
                "name": "DeltaNetAmount YTD"
              },
              {
                "name": "SelectedValue_Companycode_ID"
              },
              {
                "name": "Cogs"
              },
              {
                "name": "Cogs a/c"
              },
              {
                "name": "SalesMargin"
              },
              {
                "name": "OtherCOS"
              },
              {
                "name": "GrossProfit"
              },
              {
                "name": "COGS PY"
              },
              {
                "name": "COGS a/c PY"
              },
              {
                "name": "SalesMargin PY"
              },
              {
                "name": "OtherCOS PY"
              },
              {
                "name": "GrossProfit PY"
              },
              {
                "name": "MsgCogsCost"
              },
              {
                "name": "DeltaSalesMargint%"
              },
              {
                "name": "DeltaCogs"
              },
              {
                "name": "DeltaCogs a/c"
              },
              {
                "name": "DeltaSalesMargin"
              },
              {
                "name": "DeltaOtherCOS"
              },
              {
                "name": "DeltaProfitMargin"
              },
              {
                "name": "DeltaGrossProfit"
              },
              {
                "name": "cogs_switch"
              },
              {
                "name": "cogs_switch_py"
              },
              {
                "name": "Amount cy"
              },
              {
                "name": "Amount PY"
              },
              {
                "name": "DeltaNetAmount_col"
              },
              {
                "name": "DeltaSalesMargin_col"
              },
              {
                "name": "DeltaCustAmount_col"
              },
              {
                "name": "GrossMargin"
              },
              {
                "name": "DeltaKPI%"
              },
              {
                "name": "Opex"
              },
              {
                "name": "Opex PY"
              },
              {
                "name": "GrossMargin PY"
              },
              {
                "name": "MC %"
              },
              {
                "name": "MC % PY"
              },
              {
                "name": "Sales Margin %"
              },
              {
                "name": "Profit Margin %"
              },
              {
                "name": "KPI_Tooltip_Title"
              },
              {
                "name": "Sales Margin % PY"
              },
              {
                "name": "Profit Margin % PY"
              },
              {
                "name": "Profit Margin % Delta"
              },
              {
                "name": "Delta Gross Margin"
              },
              {
                "name": "Delta MC %"
              },
              {
                "name": "SelectedValue_Source"
              },
              {
                "name": "SelectedValue_Subsource"
              },
              {
                "name": "SelectedValue_Predefined_KPI"
              },
              {
                "name": "SelectedValue_PredefinedKPI_filters"
              },
              {
                "name": "SelectedValue_KPI_type"
              },
              {
                "name": "1_Net Invoice Sales"
              },
              {
                "name": "1_Net Invoice Sales PY"
              },
              {
                "name": "1_Net Invoice Sales PY_1"
              },
              {
                "name": "1a_Rebate Accruals"
              },
              {
                "name": "1a_Rebate Accruals PY"
              },
              {
                "name": "2_Net Revenue"
              },
              {
                "name": "2_Net Revenue PY"
              },
              {
                "name": "2a_Fin Accr & Rebates"
              },
              {
                "name": "2a_Fin Accr & Rebates PY"
              },
              {
                "name": "3_Reported Revenue"
              },
              {
                "name": "3_Reported Revenue PY"
              },
              {
                "name": "3a_COGS Standard"
              },
              {
                "name": "3a_COGS Standard PY"
              },
              {
                "name": "3b_COGS Actual"
              },
              {
                "name": "3b_COGS Actual PY"
              },
              {
                "name": "5_Standard Finance Margin"
              },
              {
                "name": "5_Standard Finance Margin PY"
              },
              {
                "name": "6_Actual Finance Margin"
              },
              {
                "name": "6_Actual Finance Margin PY"
              },
              {
                "name": "7_Gross Margin"
              },
              {
                "name": "7_Gross Margin PY"
              },
              {
                "name": "Notification_KPI_name"
              },
              {
                "name": "Selected_Period"
              },
              {
                "name": "Delta 1_Net Invoice Sales"
              },
              {
                "name": "Delta 2_Net Revenue"
              },
              {
                "name": "Delta 1a_Rebate Accruals"
              },
              {
                "name": "Delta 2a_Fin Accr & Rebates"
              },
              {
                "name": "Delta 3_Reported Revenue"
              },
              {
                "name": "Delta 3a_COGS Standard"
              },
              {
                "name": "Delta 3b_Cogs Actual"
              },
              {
                "name": "Delta 5_Standard Finance Margin"
              },
              {
                "name": "Delta 6_Actual Finance Margin"
              },
              {
                "name": "Delta 7_Gross Margin"
              },
              {
                "name": "MsgCurrentRegion"
              },
              {
                "name": "Quantity"
              }
            ]
          },
          {
            "name": "SalesOrganization",
            "columns": [
              {
                "name": "SalesOrganizationID"
              },
              {
                "name": "SalesOrganization"
              },
              {
                "name": "SalesOrganizationCurrency"
              },
              {
                "name": "CompanyCode"
              },
              {
                "name": "CountryID"
              },
              {
                "name": "CountryName"
              },
              {
                "name": "RegionID"
              },
              {
                "name": "RegionName"
              },
              {
                "name": "Access_Control_Unit"
              },
              {
                "name": "t_applicationId"
              },
              {
                "name": "t_extractionDtm"
              }
            ]
          },
          {
            "name": "exQL_Map",
            "columns": [
              {
                "name": "nk_ExQLmap"
              },
              {
                "name": "GLAccountID"
              },
              {
                "name": "FunctionalAreaID"
              },
              {
                "name": "ExQLNode"
              },
              {
                "name": "ExQLAccount"
              },
              {
                "name": "t_applicationId"
              },
              {
                "name": "t_jobDtm"
              },
              {
                "name": "t_extractionDtm"
              },
              {
                "name": "GM element L1"
              },
              {
                "name": "GM element L2"
              }
            ]
          },
          {
            "name": "fact_ACDOCA_FinStatemntSalesMargin",
            "columns": [
              {
                "name": "CompanyCodeID"
              },
              {
                "name": "ProfitCenterID"
              },
              {
                "name": "ProfitCenter"
              },
              {
                "name": "GLAccountID"
              },
              {
                "name": "FunctionalAreaID"
              },
              {
                "name": "CurrencyID"
              },
              {
                "name": "SAP_Sales"
              },
              {
                "name": "SAP_COGS"
              },
              {
                "name": "SAP_SalesMargin"
              },
              {
                "name": "FiscalYear"
              },
              {
                "name": "FiscalYearPeriod"
              },
              {
                "name": "t_applicationId"
              },
              {
                "name": "t_extractionDtm"
              }
            ]
          },
          {
            "name": "CompanyCodeProfitCenter",
            "columns": [
              {
                "name": "CompanyCodeID"
              },
              {
                "name": "ProfitCenterID"
              },
              {
                "name": "SKReportingEntityKey"
              },
              {
                "name": "ExQLReportingEntity"
              }
            ]
          },
          {
            "name": "GLAccount",
            "columns": [
              {
                "name": "GLAccount"
              }
            ]
          },
          {
            "name": "ProductPlant",
            "columns": [
              {
                "name": "Plant"
              },
              {
                "name": "Product"
              },
              {
                "name": "ProcurementType"
              },
              {
                "name": "PurchasingGroup"
              },
              {
                "name": "SpecialProcurementType"
              }
            ]
          },
          {
            "name": "Plant",
            "columns": [
              {
                "name": "Plant"
              },
              {
                "name": "PlantID"
              }
            ]
          },
          {
            "name": "ProductSalesDelivery",
            "columns": [
              {
                "name": "ItemCategoryGroupName"
              },
              {
                "name": "ItemCategoryGroup"
              }
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "250c1e4d-afcf-49ab-ab17-a960cf5af5b6",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "SalesOrganizationID",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "SalesOrganizationID",
        "toTable": "SalesOrganization"
      },
      {
        "name": "dcfafa3a-cb4b-4cd1-aaef-c7611eaf4071",
        "fromColumn": "ProfitCenterID",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "ProfitCenterID",
        "toTable": "ProfitCenter"
      },
      {
        "name": "004a4342-3665-49ad-bbff-801b057b8b69",
        "fromColumn": "SalesDistrictID",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "SalesDistrictID",
        "toTable": "SalesDistrict"
      },
      {
        "name": "e59534fe-2b69-41f1-8743-19f6a26a6a83",
        "fromColumn": "PostingDate",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "447e5c85-f794-4e5b-9ac8-fbf058a3fae8",
        "fromColumn": "GLAccountID",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "GLAccountID",
        "toTable": "GLAccount"
      },
      {
        "name": "7032ce89-7bd4-4bc6-bbbe-3c1ce0a0a94b",
        "fromColumn": "CustomerID",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "CustomerID",
        "toTable": "CustomerSoldTo"
      },
      {
        "name": "a20c3188-5021-4ebf-8e01-2f313746a777",
        "fromColumn": "ShipToParty",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "CustomerID",
        "toTable": "CustomerShippedTo"
      },
      {
        "name": "4108ec3a-b243-46f3-ad9f-eb854fc08894",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "GROUP",
        "fromTable": "RLS_USERS",
        "securityFilteringBehavior": "bothDirections",
        "toCardinality": "many",
        "toColumn": "GROUP",
        "toTable": "RLS_GROUPS"
      },
      {
        "name": "f7a0cc0a-615f-4c02-ac75-9a2f6274b886",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "CompanyCodeID",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toCardinality": "many",
        "toColumn": "ompanyCodeID",
        "toTable": "RLS_GROUPS"
      },
      {
        "name": "0e6905d6-0254-4524-9bf8-0a04d1d189ad",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ProductSurrogateKey",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "securityFilteringBehavior": "bothDirections",
        "toColumn": "sk_dim_Product",
        "toTable": "Product"
      },
      {
        "name": "1c96de1e-c704-4029-9b18-1722edcefd70",
        "fromColumn": "GLAccountID",
        "fromTable": "fact_ACDOCA_FinStatemntSalesMargin",
        "toColumn": "GLAccountID",
        "toTable": "GLAccount"
      },
      {
        "name": "d9486ecb-882f-42f2-90a6-f7b73e59e2af",
        "fromColumn": "FiscalYearPeriod",
        "fromTable": "fact_ACDOCA_FinStatemntSalesMargin",
        "toColumn": "YearMonth",
        "toTable": "Calendar_cut"
      },
      {
        "name": "c064fb31-ab1c-40b7-bbf9-7df08b00a6cc",
        "fromColumn": "FiscalYearPeriod",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "YearMonth",
        "toTable": "Calendar_cut"
      },
      {
        "name": "feb78152-e18d-41c9-81a2-ca1530e60880",
        "fromColumn": "YearMonthPeriod",
        "fromTable": "Calendar",
        "isActive": false,
        "toColumn": "YearMonth",
        "toTable": "Calendar_cut"
      },
      {
        "name": "bbd5d39f-99a4-42c9-9356-da5e9cdccb15",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "YearMonthPeriod",
        "fromTable": "Calendar",
        "isActive": false,
        "toCardinality": "many",
        "toColumn": "FiscalYearPeriod",
        "toTable": "fact_ACDOCA_FinStatemntSalesMargin"
      },
      {
        "name": "6f43a9df-96f7-4acb-aa42-d85adb594cf6",
        "fromColumn": "SKReportingEntityKey",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "SKReportingEntityKey",
        "toTable": "CompanyCodeProfitCenter"
      },
      {
        "name": "dbae20df-9bb7-450f-b7bc-eb2fba9634f6",
        "fromColumn": "CurrencyID",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "CurrencyID",
        "toTable": "Currency"
      },
      {
        "name": "df130aef-ea9e-4551-a95d-3131f73ff973",
        "fromColumn": "CurrencyID",
        "fromTable": "fact_ACDOCA_FinStatemntSalesMargin",
        "toColumn": "CurrencyID",
        "toTable": "Currency"
      },
      {
        "name": "9e09974f-9dc2-4262-b593-d919e9c824e1",
        "fromColumn": "CurrencyTypeID",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "CurrencyTypeID",
        "toTable": "CurrencyType"
      },
      {
        "name": "ef20abe2-5e57-4316-b5d9-5bab76b74cb0",
        "fromColumn": "CompanyCodeProfitCenterID",
        "fromTable": "fact_ACDOCA_FinStatemntSalesMargin",
        "toColumn": "SKReportingEntityKey",
        "toTable": "CompanyCodeProfitCenter"
      },
      {
        "name": "d4cfd861-c7e0-42be-a0b5-2897b7bce14b",
        "fromColumn": "ProfitCenterID",
        "fromTable": "fact_ACDOCA_FinStatemntSalesMargin",
        "toColumn": "ProfitCenterID",
        "toTable": "ProfitCenter"
      },
      {
        "name": "0a63f2a6-1f2c-4ff4-b123-d1cdc3d4cfdf",
        "fromColumn": "CompanyCodeID",
        "fromTable": "CompanyCodeProfitCenter",
        "toColumn": "CompanyCodeID",
        "toTable": "CompanyCode"
      },
      {
        "name": "5b7e8b8f-4e6d-4428-b7a9-0ce20979643b",
        "fromColumn": "CurrencyID",
        "fromTable": "fact_Budget_EPM",
        "toColumn": "CurrencyID",
        "toTable": "Currency"
      },
      {
        "name": "a7e8f036-53e5-4df4-96e8-204fcc453964",
        "fromColumn": "InOutID",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "InOutID",
        "toTable": "InOut"
      },
      {
        "name": "937f9227-7cb7-4a3d-acd6-64c7f85c51a9",
        "fromColumn": "InOutID",
        "fromTable": "fact_Budget_EPM",
        "toColumn": "InOutID",
        "toTable": "InOut"
      },
      {
        "name": "228cb476-d78e-48b6-b28c-5ee5da062c66",
        "fromColumn": "CurrencyTypeID",
        "fromTable": "fact_Budget_EPM",
        "toColumn": "CurrencyTypeID",
        "toTable": "CurrencyType"
      },
      {
        "name": "5d390a7a-5ed5-412e-9069-c7e7bb270878",
        "fromColumn": "ValueTypeID",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "ValueTypeID",
        "toTable": "ValueType"
      },
      {
        "name": "02b7442a-6727-417d-a1ca-09c4da5ebb7e",
        "fromColumn": "ValueTypeID",
        "fromTable": "fact_Budget_EPM",
        "toColumn": "ValueTypeID",
        "toTable": "ValueType"
      },
      {
        "name": "5203d252-cd36-448d-ac84-92879756e56c",
        "fromColumn": "Date",
        "fromTable": "fact_Budget_EPM",
        "toColumn": "LastDayOfTheMonth",
        "toTable": "Calendar_cut"
      },
      {
        "name": "e4dc4dc0-f899-4e6b-97ce-7982659c86dc",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "nk_CompCodeRepEntity",
        "fromTable": "CompanyCodeProfitCenter",
        "toColumn": "nk_CompCodeRepEntity",
        "toTable": "CompCodeRepEntity"
      },
      {
        "name": "746e0324-21ce-4dd9-acb7-d68bfa221d9d",
        "fromColumn": "nk_CompCodeRepEntity",
        "fromTable": "fact_Budget_EPM",
        "toColumn": "nk_CompCodeRepEntity",
        "toTable": "CompCodeRepEntity"
      },
      {
        "name": "c6c0a75d-2a5c-49f3-905b-9fdb8c70b1cc",
        "fromColumn": "Date",
        "fromTable": "fact_Budget_EPM",
        "toColumn": "Date",
        "toTable": "Calendar"
      },
      {
        "name": "6e3a64c9-4fb4-4460-bdbd-9ea8f6d2a187",
        "fromColumn": "ExQL reporting entity ",
        "fromTable": "Reconciliation_File",
        "toColumn": "ExQLReportingEntity",
        "toTable": "ExQLReportingEntity"
      },
      {
        "name": "83660e90-e6cd-4fbb-a9ca-9383e66719df",
        "fromColumn": "nk_CompCodeRepEntity",
        "fromTable": "CompanyCodeProfitCenter",
        "toColumn": "Key ",
        "toTable": "Reconciliation_File"
      },
      {
        "name": "a4c258f3-47b0-45dc-be39-5fdcf6056d0d",
        "fromColumn": "nk_ExQLmap",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "nk_ExQLmap",
        "toTable": "exQL_Map"
      },
      {
        "name": "e72292a7-4167-47b9-bd24-40a995838083",
        "fromColumn": "GMElementL1",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "KPI name",
        "toTable": "GM Element Sort"
      },
      {
        "name": "b2302b5d-932d-4e45-ad70-4d8163b1cdd7",
        "fromColumn": "GMElementL2",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "GM element L2",
        "toTable": "GM Element 2 Sorting"
      },
      {
        "name": "1f2bdb64-6c15-435f-94de-84d4c1a96c20",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "PlantID",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "PlantID",
        "toTable": "Plant"
      },
      {
        "name": "9cb4019c-9834-4110-b6ff-c56b1c842e27",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "nk_ProductPlant_derived",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toColumn": "nk_ProductPlant",
        "toTable": "ProductPlant"
      },
      {
        "name": "59cce710-e23f-4636-a471-b99e14c9a17d",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "ProductID",
        "fromTable": "fact_ACDOCA_EPMSalesView",
        "toCardinality": "many",
        "toColumn": "ProductID",
        "toTable": "ProductSalesDelivery"
      }
    ],
    "roles": [
      {
        "name": "RLS",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "59197cd22b8b496594338ae5264c4541"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "RLS_USERS",
            "filterExpression": "[USER]=userprincipalname()"
          }
        ]
      }
    ],
    "sourceQueryCulture": "ru-UA",
    "tables": [
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mmmm d\\, yyyy",
            "isKey": true,
            "lineageTag": "1d6951e1-d7db-487c-8c4c-a24d8aa7a0ca",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5fd7d45-5c4c-456b-b85c-10d6e36e8a40",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6dab0902-763b-4e00-a184-d643553a0094",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "MonthNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2487d343-e68b-486b-9219-cabcdbfd6979",
            "sourceColumn": "MonthNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69b64fa6-0674-49e6-95c9-6a6d642e0cad",
            "sortByColumn": "MonthNumber",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d15755fe-cf8a-4a30-bec0-7df73fb82723",
            "sourceColumn": "Week",
            "summarizeBy": "none"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ea9ae91-7991-4c01-b8df-2252aaee4257",
            "sourceColumn": "Day",
            "summarizeBy": "none"
          },
          {
            "name": "YearMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b8fea4a3-dbff-4a01-8654-eaabb7f5c1e3",
            "sourceColumn": "YearMonth",
            "summarizeBy": "none"
          },
          {
            "name": "YearQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e0faca08-398c-4132-b27d-46a8a379b5e2",
            "sourceColumn": "YearQuarter",
            "summarizeBy": "none"
          },
          {
            "name": "YearWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "43182401-34dc-4a32-9c3b-5474c04941d1",
            "sourceColumn": "YearWeek",
            "summarizeBy": "none"
          },
          {
            "name": "WeekDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "91e97c46-bbf2-4f49-93ab-5b8c24c49f9f",
            "sourceColumn": "WeekDay",
            "summarizeBy": "none"
          },
          {
            "name": "FirstDayOfWeekDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "c45add9d-1aca-421d-9046-9652e3288564",
            "sourceColumn": "FirstDayOfWeekDate",
            "summarizeBy": "none"
          },
          {
            "name": "FirstDayOfMonthDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "633af68f-d4ba-41de-a63d-b754ceeb5823",
            "sourceColumn": "FirstDayOfMonthDate",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarDayOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "948aca54-502d-4200-8563-43152ddfcf79",
            "sourceColumn": "CalendarDayOfYear",
            "summarizeBy": "none"
          },
          {
            "name": "YearDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a709a60f-b6aa-488f-adc1-569639e7dfe5",
            "sourceColumn": "YearDay",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKNUM([Date],2)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3c96f291-8bff-44ed-95b8-cea82f5a99da",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "12 months before date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "if(and(datediff('Calendar'[Date],'Calendar'[Today],DAY)>=0,datediff('Calendar'[Date],'Calendar'[Today],MONTH)<=12),1,0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9f620441-1390-4e72-9804-ad4fb973b4ff",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Today",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "expression": "date(year(today()),month(TODAY()),day(TODAY()))",
            "formatString": "Long Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2e039e2f-b086-484d-adc3-567812417ba5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Calendar'[Month]&\" \"&'Calendar'[Year]",
            "isDataTypeInferred": true,
            "lineageTag": "0235550e-b372-40e1-b443-360b58f0e94a",
            "sortByColumn": "YearMonth",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "YTD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "if(and(datediff('Calendar'[Date],'Calendar'[Today],DAY)>=0,year('Calendar'[Date])=year('Calendar'[Today])),1,0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "817185dc-1afc-4f05-8e1f-73f396f315f5",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "CurrentDay_Filter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF ( 'Calendar'[Date] <= TODAY (), 1,0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f72baa5a-9cc5-4378-9e3b-3711e7e9be90",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Month_Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Calendar'[Date],\"MMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "77686f9c-9172-4624-8921-b5df4353d5ab",
            "sortByColumn": "MonthNumber_oder",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNumber_oder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH('Calendar'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "369fa8e2-28b0-4cb5-96c3-ab400a8c8e13",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Calendar'[Date],\"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cbe3e855-4d39-4785-8647-bf6fe2fee2c0",
            "sortByColumn": "MonthNumber_oder",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trend Filter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "var maxBillingDate = max(fact_ACDOCA_EPMSalesView[PostingDate])",
              "return",
              "if('Calendar'[Date]<=maxBillingDate,1,0)"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "819a290f-032a-4d2c-8bfe-c93bb58afff7",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Week calc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "expression": "if(and(month('Calendar'[Date])=1,'Calendar'[Week]=\"52\"),\"01\",'Calendar'[Week])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "de369351-a54c-4cf4-ac08-cde8e55e381f",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Previous year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "[Year]-1",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ba093d8c-9038-4408-828a-9692c2c1db38",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "YearMonthPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE('Calendar'[Year], CONCATENATE(\"0\", 'Calendar'[Month]))",
            "isDataTypeInferred": true,
            "lineageTag": "e50d8760-d647-40e0-96bd-c519696fc65b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "LastDayOfTheMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "expression": "EOMONTH('Calendar'[Date],0 )",
            "formatString": "mmmm d\\, yyyy",
            "isDataTypeInferred": true,
            "lineageTag": "f71cc9d0-ee95-4339-a738-1d083f68582f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "isHidden": true,
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "28c3e042-dae6-4061-862f-f1c7d24d2e25",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "829e45c7-d79e-47d3-a73d-815e7200c79e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "472a0a37-14fb-4214-9e75-e641398549c6",
                "ordinal": 2
              },
              {
                "name": "Week",
                "column": "Week",
                "lineageTag": "558b6a16-a91e-47de-96f8-18862f3815a4",
                "ordinal": 3
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "739f3be3-1d4d-4bfd-8cd2-ef4f2cf8e0f7",
                "ordinal": 4
              }
            ],
            "lineageTag": "19c6a929-ba19-4785-9380-7541acc0265e"
          }
        ],
        "lineageTag": "23b61ee0-dd79-4c21-8026-6836ae54321c",
        "measures": [
          {
            "name": "KPI Budget",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "IF( HASONEVALUE(srv_MeasureTypes[Choose KPI]), ",
              "    SWITCH(",
              "        SELECTEDVALUE(srv_MeasureTypes[Choose KPI]), ",
              "        \"3_Reported Revenue\", [Budget]),",
              "        BLANK()",
              ")"
            ],
            "lineageTag": "50d2274d-17a1-4baf-9159-ce8841890210"
          },
          {
            "name": "KPI right",
            "expression": [
              "",
              "IF([SelectedValue_KPI] = \"Predefined KPI is chosen\", [Budget], [KPI])"
            ],
            "formatString": "0",
            "lineageTag": "05d52075-e3c4-4416-a274-30efc472fae9"
          },
          {
            "name": "Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "\t[Sales],",
              "    ALLSELECTED(fact_ACDOCA_EPMSalesView),FILTERS('Calendar'[Month_Short]))"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "TotalForSelectedCategory",
                  "version": 0
                }
              }
            ],
            "lineageTag": "95a98c6b-b299-43ad-99ce-509f075dabea"
          }
        ],
        "partitions": [
          {
            "name": "Calendar-fe7c89e6-d300-4e27-8a22-dced5b696b42",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&Source&\"\", \"\"&DB&\"\"),",
                "    dm_sales_vw_dim_Calendar = Source{[Schema=\"dm_sales\",Item=\"vw_dim_Calendar\"]}[Data],",
                "    #\"Filtered Rows1\" = Table.SelectRows(dm_sales_vw_dim_Calendar, each [Date] >= #date(2019, 01, 01)),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Filtered Rows1\", each [Date] < #date(2026, 01, 01))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Product",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "298219e9-33ac-4db2-a93e-2379eed4a9da",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "ProductExternalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8c524d6b-2731-4d1b-bdec-35cc6c845358",
            "sourceColumn": "ProductExternalID",
            "summarizeBy": "none"
          },
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2885daab-58b0-461a-bbaa-353eb288269e",
            "sourceColumn": "Product",
            "summarizeBy": "none"
          },
          {
            "name": "MaterialTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad32a4e9-7f1e-43e6-96d8-0642d05bf523",
            "sourceColumn": "MaterialTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "MaterialType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e827f20f-db18-485a-a9bb-2cfa6a880c93",
            "sourceColumn": "MaterialType",
            "summarizeBy": "none"
          },
          {
            "name": "IsMarkedForDeletion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "14560036-4bf3-41a0-966f-9be269943c48",
            "sourceColumn": "IsMarkedForDeletion",
            "summarizeBy": "none"
          },
          {
            "name": "CrossPlantStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "bdee69ec-827a-41f9-8bc1-b368ffab5ceb",
            "sourceColumn": "CrossPlantStatus",
            "summarizeBy": "none"
          },
          {
            "name": "GrossWeight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "d07871c3-e841-4751-afe5-5611822a1fe8",
            "sourceColumn": "GrossWeight",
            "summarizeBy": "none"
          },
          {
            "name": "SourceOfSupply",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "68b7cbf9-2a71-4c2c-9c8a-7e37847fdf44",
            "sourceColumn": "SourceOfSupply",
            "summarizeBy": "none"
          },
          {
            "name": "CountryOfOrigin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2c091d40-8450-466e-b08c-b343892ad593",
            "sourceColumn": "CountryOfOrigin",
            "summarizeBy": "none"
          },
          {
            "name": "CompetitorID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b882e7ed-8a0c-4696-a69c-79bc4b6fafa9",
            "sourceColumn": "CompetitorID",
            "summarizeBy": "none"
          },
          {
            "name": "MaterialGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fcd1c949-9de8-4fab-92a8-5aa0865e94d5",
            "sourceColumn": "MaterialGroup",
            "summarizeBy": "none"
          },
          {
            "name": "BaseUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65e92f43-69cd-4f3a-bb28-52b08fadfa8b",
            "sourceColumn": "BaseUnit",
            "summarizeBy": "none"
          },
          {
            "name": "ItemCategoryGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "14de9bd4-66dc-46fc-a62b-b8492ae0508a",
            "sourceColumn": "ItemCategoryGroup",
            "summarizeBy": "none"
          },
          {
            "name": "ProductHierarchy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e90b40cc-116d-43bf-82d0-a22575572386",
            "sourceColumn": "ProductHierarchy",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L1_PillarID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f6e73e2-8902-4bd5-9273-85dd7468ded0",
            "sourceColumn": "Product_L1_PillarID",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L2_GroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79fab102-e2dd-4379-abf1-28822b15aacd",
            "sourceColumn": "Product_L2_GroupID",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L3_TypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "113634a5-a6d9-4a48-9943-35d3651027aa",
            "sourceColumn": "Product_L3_TypeID",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L4_FamilyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a19d6d99-d44b-431c-898c-587b70bb3dca",
            "sourceColumn": "Product_L4_FamilyID",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L5_SubFamilyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21811f31-ff30-49a7-b601-d668a464d0a7",
            "sourceColumn": "Product_L5_SubFamilyID",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L1_Pillar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9943029-91b0-43a3-8d0a-0f1ded269c18",
            "sourceColumn": "Product_L1_Pillar",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L2_Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66d4f894-01c5-43e6-8d18-4094a0a58903",
            "sourceColumn": "Product_L2_Group",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L3_Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc29d6b2-57e0-425a-91c5-729b4555bb9d",
            "sourceColumn": "Product_L3_Type",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L4_Family",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93f554a2-484b-4860-b029-fda085328910",
            "sourceColumn": "Product_L4_Family",
            "summarizeBy": "none"
          },
          {
            "name": "Product_L5_SubFamily",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6ce246f-5fd0-47c9-aea5-b8f58a564c32",
            "sourceColumn": "Product_L5_SubFamily",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "692cd762-f418-436e-9b56-c742d1cfcd1a",
            "sourceColumn": "ProductCategory",
            "summarizeBy": "none"
          },
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "afd5f1f3-312f-4860-a919-1266c3c47f74",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          },
          {
            "name": "IndustryStandardName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0d61e29a-1343-450f-b506-edeb29a34dbc",
            "sourceColumn": "IndustryStandardName",
            "summarizeBy": "none"
          },
          {
            "name": "ProductStandardID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2928b792-47db-4a38-b420-f408c7ec40ce",
            "sourceColumn": "ProductStandardID",
            "summarizeBy": "none"
          },
          {
            "name": "InternationalArticleNumberCat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9d2de0ac-bdc0-4e52-b698-46ff7fc3d5f7",
            "sourceColumn": "InternationalArticleNumberCat",
            "summarizeBy": "none"
          },
          {
            "name": "ProductIsConfigurable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7051de17-b9d3-4c4a-acf4-b3dd6dd20a02",
            "sourceColumn": "ProductIsConfigurable",
            "summarizeBy": "none"
          },
          {
            "name": "IsBatchManagementRequired",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a75dd014-4e52-4f18-86e4-52a1592e0797",
            "sourceColumn": "IsBatchManagementRequired",
            "summarizeBy": "none"
          },
          {
            "name": "ExternalProductGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5dbaa89c-1bd9-4057-8da6-e8ec10bd6f7d",
            "sourceColumn": "ExternalProductGroup",
            "summarizeBy": "none"
          },
          {
            "name": "CrossPlantConfigurableProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "71f018ff-1c87-4fea-87ae-1af8b0f33a94",
            "sourceColumn": "CrossPlantConfigurableProduct",
            "summarizeBy": "none"
          },
          {
            "name": "ProductManufacturerNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "06c61837-dda3-45eb-beed-c498e30484d9",
            "sourceColumn": "ProductManufacturerNumber",
            "summarizeBy": "none"
          },
          {
            "name": "ManufacturerNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f30c2da1-cac8-45e5-b5ac-71c8a19711ee",
            "sourceColumn": "ManufacturerNumber",
            "summarizeBy": "none"
          },
          {
            "name": "MaximumPackagingLength",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "9ba6266f-a1a3-40e4-970f-a84af75a2d19",
            "sourceColumn": "MaximumPackagingLength",
            "summarizeBy": "none"
          },
          {
            "name": "MaximumPackagingWidth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "5611c7e8-0a7b-4785-b05c-c48eaf8d887b",
            "sourceColumn": "MaximumPackagingWidth",
            "summarizeBy": "none"
          },
          {
            "name": "MaximumPackagingHeight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "690cb278-5f08-43e4-bd77-48f110e4e251",
            "sourceColumn": "MaximumPackagingHeight",
            "summarizeBy": "none"
          },
          {
            "name": "MaximumCapacity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "bac66443-f30f-447d-b4cb-3a16c1d46c5a",
            "sourceColumn": "MaximumCapacity",
            "summarizeBy": "none"
          },
          {
            "name": "OvercapacityTolerance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "7b216ef4-238f-4259-bce9-a0b7992d808f",
            "sourceColumn": "OvercapacityTolerance",
            "summarizeBy": "none"
          },
          {
            "name": "UnitForMaxPackagingDimensions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "596e6628-63e1-40dc-bd64-69fbdf3f601f",
            "sourceColumn": "UnitForMaxPackagingDimensions",
            "summarizeBy": "none"
          },
          {
            "name": "BaseUnitSpecificProductLength",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "bdee2a63-2a16-4e80-b62b-c54d20285e76",
            "sourceColumn": "BaseUnitSpecificProductLength",
            "summarizeBy": "none"
          },
          {
            "name": "BaseUnitSpecificProductWidth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "ae327246-5bc7-452d-ad79-4c7a32506472",
            "sourceColumn": "BaseUnitSpecificProductWidth",
            "summarizeBy": "none"
          },
          {
            "name": "BaseUnitSpecificProductHeight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "c65a8006-fa1e-4f22-912c-d3ff01ed2b50",
            "sourceColumn": "BaseUnitSpecificProductHeight",
            "summarizeBy": "none"
          },
          {
            "name": "ArticleCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5c0b5dde-b57d-4abb-ac55-26baf622b0a3",
            "sourceColumn": "ArticleCategory",
            "summarizeBy": "none"
          },
          {
            "name": "ProductIsLocked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d3d827d-30ba-43d0-96de-d6907a40776c",
            "sourceColumn": "ProductIsLocked",
            "summarizeBy": "none"
          },
          {
            "name": "BasicMaterial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a6701520-f72e-49f8-a7cf-378383b651d8",
            "sourceColumn": "BasicMaterial",
            "summarizeBy": "none"
          },
          {
            "name": "SalesProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a4f45ff9-28c4-4ea3-ab8f-2ebcef8de3c0",
            "sourceColumn": "SalesProduct",
            "summarizeBy": "none"
          },
          {
            "name": "ZZ1_CustomFieldRiskMit_PRD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7b2db7c9-8853-402b-b8be-99785ac4abb7",
            "sourceColumn": "ZZ1_CustomFieldRiskMit_PRD",
            "summarizeBy": "none"
          },
          {
            "name": "ZZ1_CustomFieldHighRis_PRD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "93d165ba-b28d-4a16-ab3e-9b6f54f6d43b",
            "sourceColumn": "ZZ1_CustomFieldHighRis_PRD",
            "summarizeBy": "none"
          },
          {
            "name": "ZZ1_CustomFieldRiskRea_PRD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5b55d529-f115-4771-8e03-043973bf5fdb",
            "sourceColumn": "ZZ1_CustomFieldRiskRea_PRD",
            "summarizeBy": "none"
          },
          {
            "name": "t_jobDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "d8409230-5722-42c6-8632-84aaf9f02e9a",
            "sourceColumn": "t_jobDtm",
            "summarizeBy": "none"
          },
          {
            "name": "ID_Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'Product'[ProductID]&\"_\"&'Product'[Product]",
            "isDataTypeInferred": true,
            "lineageTag": "97c317eb-b1d7-4766-82a5-304efeb35308",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ProductID_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b21cc5a-e8d3-4972-8775-6d7d5582104c",
            "sourceColumn": "ProductID_Name",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2841c934-cdba-4d33-9bea-9457f3c9266d",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "fc15a0e0-0feb-4273-a9c3-201ca43fbbcb",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "sk_dim_Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "14511f79-4387-497f-8b05-937d41b046e8",
            "sourceColumn": "sk_dim_Product",
            "summarizeBy": "none"
          },
          {
            "name": "CreationDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "afffbf53-b167-41ef-82ae-283db60fe55c",
            "sourceColumn": "CreationDate",
            "summarizeBy": "none"
          },
          {
            "name": "NetWeight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "d18288f1-8bc0-40f9-92c8-5ebcf9af99ef",
            "sourceColumn": "NetWeight",
            "summarizeBy": "none"
          },
          {
            "name": "IndustrySector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "12fc1260-10ef-466d-8fd9-58384c619daa",
            "sourceColumn": "IndustrySector",
            "summarizeBy": "none"
          },
          {
            "name": "WeightUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "593d99b8-ae79-4c93-abfb-d83b1fede80b",
            "sourceColumn": "WeightUnit",
            "summarizeBy": "none"
          },
          {
            "name": "Division",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "19f2c133-cf64-4b8f-be20-e2827eff3bf9",
            "sourceColumn": "Division",
            "summarizeBy": "none"
          },
          {
            "name": "TransportationGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d24bf421-23a3-43a5-8254-90deef7d944d",
            "sourceColumn": "TransportationGroup",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedByUser",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4de5f3fe-371f-4e98-84a7-a0d8147d7073",
            "sourceColumn": "CreatedByUser",
            "summarizeBy": "none"
          },
          {
            "name": "CrossPlantStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0347e958-3d1d-475d-a8c7-bb521f0e3ba7",
            "sourceColumn": "CrossPlantStatusID",
            "summarizeBy": "none"
          },
          {
            "name": "ItemCategoryGroupName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3e0fb9a-3ffe-4f81-a18c-8c17235534ae",
            "sourceColumn": "ItemCategoryGroupName",
            "summarizeBy": "none"
          }
        ],
        "hierarchies": [
          {
            "name": "Product Hierarchy",
            "isHidden": true,
            "levels": [
              {
                "name": "Product_L1_Pillar",
                "column": "Product_L1_Pillar",
                "lineageTag": "30d14195-62fa-4861-b0d7-78d08db1d56d",
                "ordinal": 0
              },
              {
                "name": "Product_L2_Group",
                "column": "Product_L2_Group",
                "lineageTag": "dabaae36-0236-431f-a52e-392ba64cb2f2",
                "ordinal": 1
              },
              {
                "name": "Product_L3_Type",
                "column": "Product_L3_Type",
                "lineageTag": "e51514ef-205b-47db-bd7a-458efc06904c",
                "ordinal": 2
              },
              {
                "name": "Product_L4_Family",
                "column": "Product_L4_Family",
                "lineageTag": "652db67f-9016-43ae-9e4b-7b093e4a063d",
                "ordinal": 3
              },
              {
                "name": "Product_L5_SubFamily",
                "column": "Product_L5_SubFamily",
                "lineageTag": "2c368a67-fc45-4c45-89e6-8d14070768bb",
                "ordinal": 4
              }
            ],
            "lineageTag": "57c96a21-b91a-447a-8dd5-be3a1b1ef5d6"
          }
        ],
        "lineageTag": "ab9cc8b5-914a-4ebf-b5b6-43dcd9261cb5",
        "partitions": [
          {
            "name": "Product-99de6899-b1ad-4fd2-a1a6-8e6211673f07",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&Source&\"\", \"\"&DB&\"\"),",
                "    dm_sales_vw_dim_Product = Source{[Schema=\"dm_finance\",Item=\"vw_dim_Product\"]}[Data],",
                "    #\"Removed Duplicates\" = Table.Distinct(dm_sales_vw_dim_Product)",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ProfitCenter",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ControllingArea",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d614847e-1b02-4785-ab26-d2d9920ce9cb",
            "sourceColumn": "ControllingArea",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenterID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2c26839-44cd-4c91-ba3e-38d9f9fc56df",
            "sourceColumn": "ProfitCenterID",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58ffa6d8-d4ec-4354-b2ed-b5090c2cc9f0",
            "sourceColumn": "ProfitCenter",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCtrResponsiblePersonName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "849265bd-1bea-46dd-9644-3a352f6128c6",
            "sourceColumn": "ProfitCtrResponsiblePersonName",
            "summarizeBy": "none"
          },
          {
            "name": "Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9e3ab212-3956-4182-b1d9-5d01baa63189",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenterIsBlocked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1d6e8e54-5b32-416b-b57c-bae569845c92",
            "sourceColumn": "ProfitCenterIsBlocked",
            "summarizeBy": "none"
          },
          {
            "name": "CityName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a65f39c1-80e0-4c83-9312-29408ddf05b6",
            "sourceColumn": "CityName",
            "summarizeBy": "none"
          },
          {
            "name": "PostalCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1b00332b-e02d-457a-aba2-5d580184755b",
            "sourceColumn": "PostalCode",
            "summarizeBy": "none"
          },
          {
            "name": "District",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "446879de-f1d5-4435-bd0c-d15f6ad538f1",
            "sourceColumn": "District",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "663d8fdd-f3d6-431a-b21f-598844dbc99d",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "93944469-b3d4-4179-a214-7d394bd4c803",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenterTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51bff716-7986-476c-af87-1a29a515f135",
            "sourceColumn": "ProfitCenterTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenterType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d992d0d-7669-4309-b463-b7b9afa88efe",
            "sourceColumn": "ProfitCenterType",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter_ID_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(ProfitCenter[ProfitCenterID], \" \"), ProfitCenter[ProfitCenter])",
            "isDataTypeInferred": true,
            "lineageTag": "cdd3d5c8-5df1-465a-97a5-1c89e3cf0b9b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "57d986f3-00f9-45c2-802b-caadf024a2c9",
        "partitions": [
          {
            "name": "ProfitCenter-4ef61fee-14b7-481b-a877-933519aecd7e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&Source&\"\", \"\"&DB&\"\"),",
                "    dm_sales_vw_dim_ProfitCenter = Source{[Schema=\"dm_sales\",Item=\"vw_dim_ProfitCenter\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_ProfitCenter"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CustomerSoldTo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "045f7f43-aebb-417d-aa6e-b44fc63b0340",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8a6da98-b2ab-4550-a9c4-3cf0dcbc2076",
            "sourceColumn": "Customer",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerAccountGroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec196e17-4c49-4ed3-932d-25dc4f2be6da",
            "sourceColumn": "CustomerAccountGroupID",
            "summarizeBy": "none"
          },
          {
            "name": "AccountGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1897c8d-e215-4882-a57d-969c098a14f1",
            "sourceColumn": "AccountGroup",
            "summarizeBy": "none"
          },
          {
            "name": "AuthorizationGroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4e808b5c-45c4-440a-bfc9-a530b1ed1a38",
            "sourceColumn": "AuthorizationGroupID",
            "summarizeBy": "none"
          },
          {
            "name": "AuthorizationGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9a006162-b8c6-4cf8-ba93-e8a2b9d49fc4",
            "sourceColumn": "AuthorizationGroup",
            "summarizeBy": "none"
          },
          {
            "name": "DeliveryIsBlocked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8010be3e-d0f3-47ce-94b1-7b7802a7ae6e",
            "sourceColumn": "DeliveryIsBlocked",
            "summarizeBy": "none"
          },
          {
            "name": "PostingIsBlocked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "bfcc456b-d119-4a61-8065-c7c0a1c00756",
            "sourceColumn": "PostingIsBlocked",
            "summarizeBy": "none"
          },
          {
            "name": "BillingIsBlockedForCustomer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "247a546e-3c73-4d6f-8c86-c05bbda05283",
            "sourceColumn": "BillingIsBlockedForCustomer",
            "summarizeBy": "none"
          },
          {
            "name": "OrderIsBlockedForCustomer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ed630abc-3fdb-4af9-bf04-13651c0b9068",
            "sourceColumn": "OrderIsBlockedForCustomer",
            "summarizeBy": "none"
          },
          {
            "name": "IsOneTimeAccount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a627846f-d20b-4a69-b798-3c840db6b2f5",
            "sourceColumn": "IsOneTimeAccount",
            "summarizeBy": "none"
          },
          {
            "name": "CountryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97622d64-4d45-433e-b91f-bb71c4a382de",
            "sourceColumn": "CountryID",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d82ec788-b232-4b77-a152-c2830bfb24d5",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "CityName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85d3dffd-faf2-4b13-9b5d-9eb0e1162794",
            "sourceColumn": "CityName",
            "summarizeBy": "none"
          },
          {
            "name": "PostalCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af247699-37f9-4f1c-a126-2c2d62f83d00",
            "sourceColumn": "PostalCode",
            "summarizeBy": "none"
          },
          {
            "name": "StreetName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a75d128d-a1ed-40bd-8c2c-ee6c7ed02cc8",
            "sourceColumn": "StreetName",
            "summarizeBy": "none"
          },
          {
            "name": "RegionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4442be0-4707-4c06-a1b6-6259eb1aafbf",
            "sourceColumn": "RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed4b2175-ee98-421e-bb9d-3737d980d921",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "DeletionIndicator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9f70aee4-b5db-4d21-8b45-debc1c5735f8",
            "sourceColumn": "DeletionIndicator",
            "summarizeBy": "none"
          },
          {
            "name": "TradingPartnerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "927dbe57-0f0a-43ba-b828-695b2dff600b",
            "sourceColumn": "TradingPartnerID",
            "summarizeBy": "none"
          },
          {
            "name": "TradingPartner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "280f2c57-4070-43a6-aae2-a0830c21eaa4",
            "sourceColumn": "TradingPartner",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6e36e5b7-af10-4270-90cd-c05f9d8e623b",
            "sourceColumn": "BusinessType",
            "summarizeBy": "none"
          },
          {
            "name": "IndustryType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8efaf7e3-350d-47bd-8e1d-d361dbd5fba6",
            "sourceColumn": "IndustryType",
            "summarizeBy": "none"
          },
          {
            "name": "t_jobDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "4cd81ddc-d29a-427f-bcbd-4fb5e4d4eeeb",
            "sourceColumn": "t_jobDtm",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerID_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48c44231-6116-4f67-95b8-726368307445",
            "sourceColumn": "CustomerID_Name",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "17c057d9-f32a-4627-bcfb-2404f9329560",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "90630ae9-3d8b-45e2-81c7-2bc16d1f7328",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "49eb6ddc-ac38-4451-b0b8-124f07671950",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "bcc1f273-d056-4fd3-978e-f13504899fed",
        "partitions": [
          {
            "name": "CustomerSoldTo-dbb215be-a845-4777-9472-de6fe32412d4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&Source&\"\", \"\"&DB&\"\"),",
                "    dm_finance_vw_dim_Customer = Source{[Schema=\"dm_finance\",Item=\"vw_dim_Customer\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dm_finance_vw_dim_Customer,{{\"AuthorizationGroup\", type text}, {\"TradingPartner\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_ACDOCA_EPMSalesView",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_IsMQueryFoldable",
            "value": "True"
          }
        ],
        "columns": [
          {
            "name": "BillingDocumentTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b754ad95-fb1d-4eaa-8a03-dcf18d2be183",
            "sourceColumn": "BillingDocumentTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "CreationDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "72b5603d-ff43-4819-a574-c5b02da297fa",
            "sourceColumn": "CreationDate",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganizationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9f6414cc-ace1-45ce-831b-a80fecc3db42",
            "sourceColumn": "SalesOrganizationID",
            "summarizeBy": "none"
          },
          {
            "name": "DistributionChannelID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b994b0c9-e56b-4d21-80b9-a5ed6ab4c6c2",
            "sourceColumn": "DistributionChannelID",
            "summarizeBy": "none"
          },
          {
            "name": "PlantID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "331a5758-7314-4008-970b-8a2229d2eb6d",
            "sourceColumn": "PlantID",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "71f74eff-d2b1-459f-b674-91eb757b4e44",
            "sourceColumn": "FiscalYear",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f2244e24-c25f-419f-af6b-51fc794a54e5",
            "sourceColumn": "FiscalPeriod",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "006a6e13-433d-4056-8087-1510636f5dec",
            "sourceColumn": "CurrencyID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDocumentID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd7e3a5b-b50a-4c75-ba04-a4d5e847e907",
            "sourceColumn": "SalesDocumentID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDocumentItemID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed9aa33b-5501-43bb-8a47-5810be1f8ac3",
            "sourceColumn": "SalesDocumentItemID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDistrictID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "456d9a34-fae0-4c2e-9c54-b6dca4346208",
            "sourceColumn": "SalesDistrictID",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "88d9fb6d-dcd8-4c9f-9d82-96309e7fe62d",
            "sourceColumn": "CustomerGroup",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c682f9a5-c79b-4c7f-9fbe-e19584a8b7c2",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "Application",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "if(CONTAINSSTRING(fact_ACDOCA_EPMSalesView[t_applicationId],\"s4h\"),\"S4H\", if(CONTAINSSTRING(fact_ACDOCA_EPMSalesView[t_applicationId], \"HALFEN\"),\"AXBI HALFEN\", \"AXBI NON-HALFEN\"))",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0ae2a171-514b-49d3-b8f5-bbc0b9558e9a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "029d322d-08a3-4745-926c-a029f396a9bf",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "InOutID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7581a0a-5578-4f81-93b9-d798b08db201",
            "sourceColumn": "InOutID",
            "summarizeBy": "none"
          },
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ceacdfcd-c78e-4d67-99fd-d8ed858c0aa8",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          },
          {
            "name": "SourceLedgerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "283be4d9-8f2f-4ddd-8c6d-a1df27be5bfc",
            "sourceColumn": "SourceLedgerID",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyCodeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "0da4021d-c3bd-4178-8d70-bba199e64e90",
            "sourceColumn": "CompanyCodeID",
            "summarizeBy": "none"
          },
          {
            "name": "AccountingDocument",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "836abf10-06e6-4880-b602-0d48592a5581",
            "sourceColumn": "AccountingDocument",
            "summarizeBy": "none"
          },
          {
            "name": "LedgerGLLineItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0c8231c7-9178-4f5a-8931-bf627428da5e",
            "sourceColumn": "LedgerGLLineItem",
            "summarizeBy": "none"
          },
          {
            "name": "LedgerFiscalYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d4462145-3061-42a2-88df-550b298215da",
            "sourceColumn": "LedgerFiscalYear",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessTransactionTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02af5bd3-e15e-4f46-9b7d-99fc1d9a9d48",
            "sourceColumn": "BusinessTransactionTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "ReferenceDocumentTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28df8f95-df64-469b-bf00-fb648d4ad9cc",
            "sourceColumn": "ReferenceDocumentTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "ReferenceDocument",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb2e5cdd-0b56-400a-986d-4e30dcf3af51",
            "sourceColumn": "ReferenceDocument",
            "summarizeBy": "none"
          },
          {
            "name": "ReferenceDocumentItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ae52b21-a831-4228-831e-750b130869d6",
            "sourceColumn": "ReferenceDocumentItem",
            "summarizeBy": "none"
          },
          {
            "name": "IsReversal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b49ed0b2-fd29-4a8b-9961-31d8fd3531aa",
            "sourceColumn": "IsReversal",
            "summarizeBy": "none"
          },
          {
            "name": "IsReversed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a502817a-194d-4cd0-8d7f-895a9c32d255",
            "sourceColumn": "IsReversed",
            "summarizeBy": "none"
          },
          {
            "name": "ReversalReferenceDocument",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b197d7e-92d0-42c9-ac09-a29da77ad86b",
            "sourceColumn": "ReversalReferenceDocument",
            "summarizeBy": "none"
          },
          {
            "name": "GLAccountID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a008517-8819-4ccf-86b9-f5b370248e01",
            "sourceColumn": "GLAccountID",
            "summarizeBy": "none"
          },
          {
            "name": "CostCenterID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ff0934c-8607-4955-9096-065344900402",
            "sourceColumn": "CostCenterID",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenterID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9959db0d-1a15-43b9-8c0c-1112c814200b",
            "sourceColumn": "ProfitCenterID",
            "summarizeBy": "none"
          },
          {
            "name": "FunctionalAreaID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c011af4a-767b-4728-b7f2-ee42c0bebeb6",
            "sourceColumn": "FunctionalAreaID",
            "summarizeBy": "none"
          },
          {
            "name": "PartnerCompanyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "2be0fe24-5d66-4e5f-ae1c-1dbc4463de7e",
            "sourceColumn": "PartnerCompanyID",
            "summarizeBy": "none"
          },
          {
            "name": "BalanceTransactionCurrency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2919cc70-d243-4559-910e-83303b1f1aca",
            "sourceColumn": "BalanceTransactionCurrency",
            "summarizeBy": "none"
          },
          {
            "name": "AmountInGlobalCurrency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "3d425aae-8d8b-46a8-8016-1c9ddb33da98",
            "sourceColumn": "AmountInGlobalCurrency",
            "summarizeBy": "sum"
          },
          {
            "name": "BaseUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c4a7743-3401-46f0-a65e-61e31343c344",
            "sourceColumn": "BaseUnit",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "e08b8d2d-8647-49ea-b25c-350dac3918b6",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "DebitCreditID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "bc0d69ab-7dcf-4f5e-a5a6-5472e3d7fdc6",
            "sourceColumn": "DebitCreditID",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYearPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9b5debdb-9f46-4352-a3bc-9c0081d263dd",
            "sourceColumn": "FiscalYearPeriod",
            "summarizeBy": "none"
          },
          {
            "name": "PostingDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d0f51709-1651-4534-a09c-575313e44077",
            "sourceColumn": "PostingDate",
            "summarizeBy": "none"
          },
          {
            "name": "DocumentDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "accce0cb-3e0e-43d6-b809-5ab75520504d",
            "sourceColumn": "DocumentDate",
            "summarizeBy": "none"
          },
          {
            "name": "AccountingDocumentTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c13517df-0ca0-4dde-b33a-2b415e5330e3",
            "sourceColumn": "AccountingDocumentTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "GLAccountTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "277cb6d3-d282-4504-9320-4a6a853da01a",
            "sourceColumn": "GLAccountTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "PurchasingDocument",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "401f06d8-a085-40b4-94aa-4735be8701ae",
            "sourceColumn": "PurchasingDocument",
            "summarizeBy": "none"
          },
          {
            "name": "PurchasingDocumentItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "753c0697-b6ee-4b3b-becf-c21ad0e43eba",
            "sourceColumn": "PurchasingDocumentItem",
            "summarizeBy": "none"
          },
          {
            "name": "DocumentItemText",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0cf5fe16-694a-48a1-ab97-0167472c1919",
            "sourceColumn": "DocumentItemText",
            "summarizeBy": "none"
          },
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc53c6b8-b821-4984-8306-297ea86b5cfc",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "SupplierID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "23ad20f5-8506-407a-a350-0dbed42fd843",
            "sourceColumn": "SupplierID",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a9fb9bc0-e19c-48d2-aa35-a7938e915e47",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "ExchangeRateDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "d8b67efb-77ab-4e25-b282-d04b802e9a31",
            "sourceColumn": "ExchangeRateDate",
            "summarizeBy": "none"
          },
          {
            "name": "ClearingDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "8940526e-762a-4275-aa96-7d4199330616",
            "sourceColumn": "ClearingDate",
            "summarizeBy": "none"
          },
          {
            "name": "PartnerCompanyCodeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "3203ce3b-c68c-450f-96d4-b13298a235e8",
            "sourceColumn": "PartnerCompanyCodeID",
            "summarizeBy": "none"
          },
          {
            "name": "BillToPartyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b74f12b2-eed4-483d-a1ee-44798ad81877",
            "sourceColumn": "BillToPartyID",
            "summarizeBy": "none"
          },
          {
            "name": "ShipToParty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "309bd8dd-694c-4a52-b496-eb87acbd5592",
            "sourceColumn": "ShipToParty",
            "summarizeBy": "none"
          },
          {
            "name": "ManualAdjustment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e67059d6-d2dc-4f65-add7-ea5b8ec0e69b",
            "sourceColumn": "ManualAdjustment",
            "summarizeBy": "sum"
          },
          {
            "name": "TPAdjustment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5714f298-7844-4a5d-8ce8-e17209858ea3",
            "sourceColumn": "TPAdjustment",
            "summarizeBy": "sum"
          },
          {
            "name": "CurrencyTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "bcc9504e-02c9-4411-8bd1-8762f407d7a3",
            "sourceColumn": "CurrencyTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "120b8689-f58e-45d4-97ff-974175b3bce6",
            "sourceColumn": "SalesAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "CurrencyType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3c3db12-ec72-4fa6-be2d-b2f2212a1063",
            "sourceColumn": "CurrencyType",
            "summarizeBy": "none"
          },
          {
            "name": "BillingDocumentType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c22a767-b74b-4bbc-8bec-ece2c6960ac6",
            "sourceColumn": "BillingDocumentType",
            "summarizeBy": "none"
          },
          {
            "name": "BrandID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e6cc44c-b48e-48ac-9709-8394e45a0884",
            "sourceColumn": "BrandID",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerGroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1fef3b35-9bd5-4e92-b672-476253cd2047",
            "sourceColumn": "CustomerGroupID",
            "summarizeBy": "none"
          },
          {
            "name": "COGSActCostAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "bb6e88ff-219c-4e62-991f-e36ef5db908f",
            "sourceColumn": "COGSActCostAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "COGSStdCostAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "b81d7067-cd06-470a-bcf7-b3021b3c2950",
            "sourceColumn": "COGSStdCostAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "OtherCoSAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "a68cc3c1-2d88-4554-a989-bcb3f5869707",
            "sourceColumn": "OtherCoSAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "AmountCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "020911d4-4478-4e19-9344-9e055bede1db",
            "sourceColumn": "AmountCategory",
            "summarizeBy": "none"
          },
          {
            "name": "Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "ec60906a-65fc-4411-8419-98e519a42bbe",
            "sourceColumn": "Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(OR(fact_ACDOCA_EPMSalesView[ProductID]=\"\",CONTAINSSTRING(fact_ACDOCA_EPMSalesView[ProductID],\"MA\")=TRUE()), \"Empty\", \"Not Empty\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "52da9ffd-43c9-4442-8d53-c48d7a793c11",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CustomerFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(or(fact_ACDOCA_EPMSalesView[CustomerID]=\"\",CONTAINSSTRING(fact_ACDOCA_EPMSalesView[CustomerID],\"MA\")=TRUE()), \"Empty\", \"Not Empty\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "553bf6d6-b92e-4de8-8e85-49a5cef15782",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Source",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "/*IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"BKPF\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\")",
              ",\"Finance\",",
              "IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"BKPFF\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\"),",
              "\"Finance\", ",
              "IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"CTE\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\"),",
              "\"Finance\",",
              "IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"IBKPF\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\"),",
              "\"Billing\",",
              " IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"IBKPF\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Not Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Not Empty\"),",
              "\"Billing\",",
              " IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"MKPF\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\"),",
              "\"Billing\",",
              " IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"MKPF\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Not Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\"),",
              "\"Billing\",",
              " IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"MKPF\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Not Empty\"),ACDOCA_SalesView[CustomerFlag]=\"NotEmpty\"),",
              "\"Billing\",",
              "IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"MKPF\",ACDOCA_SalesView[BillingDocumentType]<>\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Not Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Not Empty\"),",
              "\"Billing\",",
              " IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"PRCHG\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Not Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\"),",
              "\"Billing\",",
              "IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"RMRP\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\"),",
              "\"Billing\",",
              " IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"RMRP\",ACDOCA_SalesView[BillingDocumentType]=\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Not Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Empty\"),",
              "\"Billing\",",
              "IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"RMRP\",ACDOCA_SalesView[BillingDocumentType]<>\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Not Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Not Empty\"),",
              "\"Billing\",",
              "IF(AND(AND(AND(ACDOCA_SalesView[ReferenceDocumentTypeID]=\"VBRK\",ACDOCA_SalesView[BillingDocumentType]<>\"MA\"),ACDOCA_SalesView[ProductFlag]=\"Not Empty\"),ACDOCA_SalesView[CustomerFlag]=\"Not Empty\"),",
              "\"Billing\",BLANK())))))))))))))) */",
              "",
              "IF(fact_ACDOCA_EPMSalesView[ReferenceDocumentTypeID] =\"VBRK\", \"Billing\", \"Finance\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "3393c9db-c5e4-48c1-98ad-2064c7ea988b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "OpexAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "7a23a030-51c3-4c9a-bb6d-e151eed8b814",
            "sourceColumn": "OpexAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "GrossMarginAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "ac3483a4-3dcb-400c-8e6b-3f89a8b20350",
            "sourceColumn": "GrossMarginAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "Subsource",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(AND(fact_ACDOCA_EPMSalesView[ReferenceDocumentTypeID]=\"VBRK\",LEFT(fact_ACDOCA_EPMSalesView[GLAccountID],5)=\"00418\"),\"Rebates\",",
              "IF(fact_ACDOCA_EPMSalesView[ReferenceDocumentTypeID]=\"VBRK\",\"Net invoiced sales\",\"Finance\"))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "28a1d62e-d05e-42ef-b33b-094492442997",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "SKReportingEntityKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b7f1fc33-3c38-4063-a305-4dc73964daf3",
            "sourceColumn": "SKReportingEntityKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSurrogateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e1c213a6-f784-4912-ad4a-1b6c4ea4ebd3",
            "sourceColumn": "ProductSurrogateKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOfficeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ce60d8e-6e23-4824-829a-7f3237429e39",
            "sourceColumn": "SalesOfficeID",
            "summarizeBy": "none"
          },
          {
            "name": "SubSourceShort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "LEFT(fact_ACDOCA_EPMSalesView[Subsource], 3)",
            "isDataTypeInferred": true,
            "lineageTag": "1bcce34a-17aa-4c09-9381-c15cf3506e8f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "nk_ExQLmap",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bbc4752-3d8c-49a6-9b14-3e80793dc6b3",
            "sourceColumn": "nk_ExQLmap",
            "summarizeBy": "none"
          },
          {
            "name": "SoldProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7159139b-e6b1-4df3-8755-b50b0eb28fa5",
            "sourceColumn": "SoldProduct",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5ac3a0d-8036-473f-b8c6-47f974a9f262",
            "sourceColumn": "CustomerCategory",
            "summarizeBy": "none"
          },
          {
            "name": "AccountingDocumentItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd5a243b-762b-4e6a-a2ee-857cc0690452",
            "sourceColumn": "AccountingDocumentItem",
            "summarizeBy": "none"
          },
          {
            "name": "AccountingDocCreatedByUserID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10e26e18-2fac-4345-8507-39cfa57b4745",
            "sourceColumn": "AccountingDocCreatedByUserID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesReferenceDocumentCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eba806fd-5e6d-4e4d-8c8a-e14d8494090f",
            "sourceColumn": "SalesReferenceDocumentCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "SalesReferenceDocumentItemCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ef8f85e-767b-465c-a7b3-c8489a0cc65c",
            "sourceColumn": "SalesReferenceDocumentItemCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDocumentItemCategoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e60ebbf4-bcfe-4cee-a627-78d990029b1f",
            "sourceColumn": "SalesDocumentItemCategoryID",
            "summarizeBy": "none"
          },
          {
            "name": "HigherLevelItem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "035bfb11-5aa9-4663-b7d0-460cdfd9a393",
            "sourceColumn": "HigherLevelItem",
            "summarizeBy": "none"
          },
          {
            "name": "ValueTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab38310d-546d-474d-aec9-225b0bb40aae",
            "sourceColumn": "ValueTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "ProjectNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a5df8c4-5172-47bd-9c0e-fbc479032c70",
            "sourceColumn": "ProjectNumber",
            "summarizeBy": "none"
          },
          {
            "name": "ProjectNumberCalculated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "899279d7-3a5f-4c98-a9a7-0e5c65d6b42c",
            "sourceColumn": "ProjectNumberCalculated",
            "summarizeBy": "none"
          },
          {
            "name": "Personalize Visual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "BLANK() ",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "1ef8b08f-bbb4-4a48-a09b-d6f681168edf",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "GMElementL1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81af75dd-7a67-45b7-b50d-4c9ccb889280",
            "sourceColumn": "GMElementL1",
            "summarizeBy": "none"
          },
          {
            "name": "GMElementL2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47509985-70cc-43bb-8059-f24a2cfc00cf",
            "sourceColumn": "GMElementL2",
            "summarizeBy": "none"
          },
          {
            "name": "AmountInCompanyCodeCurrency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "19631501-9efd-4899-84fa-937eab8baa1c",
            "sourceColumn": "AmountInCompanyCodeCurrency",
            "summarizeBy": "sum"
          },
          {
            "name": "nk_ProductPlant_derived",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(fact_ACDOCA_EPMSalesView[ProductID],\"\"),fact_ACDOCA_EPMSalesView[PlantID])",
            "isDataTypeInferred": true,
            "lineageTag": "e1422870-9675-442a-8dab-900c63024898",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "ac84624d-69b6-416c-8ecd-f006e24cdd3f",
        "measures": [
          {
            "name": "FSSM Filter",
            "expression": "COUNTROWS(fact_ACDOCA_FinStatemntSalesMargin)",
            "formatString": "0",
            "lineageTag": "8de567fd-56c0-436d-b6d2-08ce8b8fa999"
          }
        ],
        "partitions": [
          {
            "name": "fact_ACDOCA_EPMSalesView",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&Source&\"\", \"\"&DB&\"\"),",
                "    dm_finance_vw_fact_ACDOCA_EPMSalesView = Source{[Schema=\"dm_finance\",Item=\"vw_fact_ACDOCA_EPMSalesView\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dm_finance_vw_fact_ACDOCA_EPMSalesView,{",
                "\"AccountAssignmentID\",",
                "\"AccountAssignmentNumber\",",
                "\"AccountAssignmentTypeID\",",
                "\"AccountingDocumentCategoryID\",",
                "\"AmountInFreeDefinedCurrency1\",",
                "\"AmountInFreeDefinedCurrency2\",",
                "\"AssignmentReference\",",
                "\"BillableControlID\",",
                "\"BusinessAreaID\",",
                "\"BusinessProcessID\",",
                "\"ChartOfAccountsID\",",
                "\"ClearingAccountingDocument\",",
                "\"ClearingDocFiscalYear\",",
                "\"ControllingAreaID\",",
                "\"ControllingBusTransacTypeID\",",
                "\"CostCtrActivityTypeID\",",
                "\"CostObjectID\",",
                "\"CreationDateTime\",",
                "\"FinancialAccountTypeID\",",
                "\"FinancialTransactionTypeID\",",
                "\"FiscalYearVariant\",",
                "\"FreeDefinedCurrency1\",",
                "\"FreeDefinedCurrency2\",",
                "\"GLRecordTypeID\",",
                "\"InvoiceItemReference\",",
                "\"InvoiceReference\",",
                "\"InvoiceReferenceFiscalYear\",",
                "\"IsCommitment\",",
                "\"IsSettled\",",
                "\"IsSettlement\",",
                "\"JrnlEntryItemObsoleteReasonID\",",
                "\"LastChangeDateTime\",",
                "\"LineItemIsCompleted\",",
                "\"OperatingConcernID\",",
                "\"OrderCategoryID\",",
                "\"OrderID\",",
                "\"OriginCostCenterID\",",
                "\"OriginObjectTypeID\",",
                "\"OriginProfitCenterID\",",
                "\"PartnerBusinessAreaID\",",
                "\"PartnerCostCenterID\",",
                "\"PartnerFunctionalAreaID\",",
                "\"PartnerProfitCenterID\",",
                "\"PartnerSegmentID\",",
                "\"PersonnelNumber\",",
                "\"PostingKeyID\",",
                "\"PredecessorReferenceDocItem\",",
                "\"PredecessorReferenceDocTypeID\",",
                "\"PredecessorReferenceDocument\",",
                "\"ProjectID\",",
                "\"ProjectInternalID\",",
                "\"ReferenceDocumentContextID\",",
                "\"ReferenceDocumentItemGroupID\",",
                "\"ReferencePurchaseOrderCategoryID\",",
                "\"ReversalReferenceDocumentCntxtID\",",
                "\"SegmentID\",",
                "\"ServiceDocument\",",
                "\"ServiceDocumentItem\",",
                "\"ServiceDocumentTypeID\",",
                "\"SourceReferenceDocument\",",
                "\"SourceReferenceDocumentItem\",",
                "\"SourceReferenceDocumentTypeID\",",
                "\"SpecialGLCodeID\",",
                "\"SubLedgerAcctLineItemTypeID\",",
                "\"TaxCodeID\",",
                "\"TransactionTypeDeterminationID\",",
                "\"WBSElementID\"",
                "}",
                "),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"PostingDate\", type datetime}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each [PostingDate] > RangeStart and [PostingDate] <= RangeEnd)",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ],
        "refreshPolicy": {
          "incrementalGranularity": "month",
          "incrementalPeriods": 3,
          "policyType": "basic",
          "rollingWindowGranularity": "year",
          "rollingWindowPeriods": 5,
          "sourceExpression": [
            "let",
            "    Source = Sql.Database(\"\"&Source&\"\", \"\"&DB&\"\"),",
            "    dm_finance_vw_fact_ACDOCA_EPMSalesView = Source{[Schema=\"dm_finance\",Item=\"vw_fact_ACDOCA_EPMSalesView\"]}[Data],",
            "    #\"Removed Columns\" = Table.RemoveColumns(dm_finance_vw_fact_ACDOCA_EPMSalesView,{",
            "\"AccountAssignmentID\",",
            "\"AccountAssignmentNumber\",",
            "\"AccountAssignmentTypeID\",",
            "\"AccountingDocumentCategoryID\",",
            "\"AmountInFreeDefinedCurrency1\",",
            "\"AmountInFreeDefinedCurrency2\",",
            "\"AssignmentReference\",",
            "\"BillableControlID\",",
            "\"BusinessAreaID\",",
            "\"BusinessProcessID\",",
            "\"ChartOfAccountsID\",",
            "\"ClearingAccountingDocument\",",
            "\"ClearingDocFiscalYear\",",
            "\"ControllingAreaID\",",
            "\"ControllingBusTransacTypeID\",",
            "\"CostCtrActivityTypeID\",",
            "\"CostObjectID\",",
            "\"CreationDateTime\",",
            "\"FinancialAccountTypeID\",",
            "\"FinancialTransactionTypeID\",",
            "\"FiscalYearVariant\",",
            "\"FreeDefinedCurrency1\",",
            "\"FreeDefinedCurrency2\",",
            "\"GLRecordTypeID\",",
            "\"InvoiceItemReference\",",
            "\"InvoiceReference\",",
            "\"InvoiceReferenceFiscalYear\",",
            "\"IsCommitment\",",
            "\"IsSettled\",",
            "\"IsSettlement\",",
            "\"JrnlEntryItemObsoleteReasonID\",",
            "\"LastChangeDateTime\",",
            "\"LineItemIsCompleted\",",
            "\"OperatingConcernID\",",
            "\"OrderCategoryID\",",
            "\"OrderID\",",
            "\"OriginCostCenterID\",",
            "\"OriginObjectTypeID\",",
            "\"OriginProfitCenterID\",",
            "\"PartnerBusinessAreaID\",",
            "\"PartnerCostCenterID\",",
            "\"PartnerFunctionalAreaID\",",
            "\"PartnerProfitCenterID\",",
            "\"PartnerSegmentID\",",
            "\"PersonnelNumber\",",
            "\"PostingKeyID\",",
            "\"PredecessorReferenceDocItem\",",
            "\"PredecessorReferenceDocTypeID\",",
            "\"PredecessorReferenceDocument\",",
            "\"ProjectID\",",
            "\"ProjectInternalID\",",
            "\"ReferenceDocumentContextID\",",
            "\"ReferenceDocumentItemGroupID\",",
            "\"ReferencePurchaseOrderCategoryID\",",
            "\"ReversalReferenceDocumentCntxtID\",",
            "\"SegmentID\",",
            "\"ServiceDocument\",",
            "\"ServiceDocumentItem\",",
            "\"ServiceDocumentTypeID\",",
            "\"SourceReferenceDocument\",",
            "\"SourceReferenceDocumentItem\",",
            "\"SourceReferenceDocumentTypeID\",",
            "\"SpecialGLCodeID\",",
            "\"SubLedgerAcctLineItemTypeID\",",
            "\"TaxCodeID\",",
            "\"TransactionTypeDeterminationID\",",
            "\"WBSElementID\"",
            "}",
            "),",
            "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"PostingDate\", type datetime}}),",
            "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each [PostingDate] > RangeStart and [PostingDate] <= RangeEnd)",
            "in",
            "    #\"Filtered Rows\""
          ]
        }
      },
      {
        "name": "CustomerShippedTo",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1025cfec47534c579821f0558d5e91c4"
          }
        ],
        "columns": [
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ad587b5c-c9d3-4a0f-bbfe-4c42fdfece41",
            "sourceColumn": "CustomerSoldTo[CustomerID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "36d84fe7-b29b-4697-bb9a-912d85f391c8",
            "sourceColumn": "CustomerSoldTo[Customer]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CustomerAccountGroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a6084c95-efcf-4959-baf0-c82861f5f360",
            "sourceColumn": "CustomerSoldTo[CustomerAccountGroupID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "AccountGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5a074d90-4404-4764-b4ad-3deca6782334",
            "sourceColumn": "CustomerSoldTo[AccountGroup]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "AuthorizationGroupID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "764ac8f8-df2b-4311-a2e3-0e19abe3393f",
            "sourceColumn": "CustomerSoldTo[AuthorizationGroupID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "AuthorizationGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "def74cda-c133-45cb-8402-8dfa76c22783",
            "sourceColumn": "CustomerSoldTo[AuthorizationGroup]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DeliveryIsBlocked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5f60b79a-fb1c-4d58-a6e3-215a01d00307",
            "sourceColumn": "CustomerSoldTo[DeliveryIsBlocked]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "PostingIsBlocked",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d87b16f9-3005-4d2f-a0a4-e6742c342030",
            "sourceColumn": "CustomerSoldTo[PostingIsBlocked]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "BillingIsBlockedForCustomer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "83610b17-4b0f-4a66-a10d-1bcc4625051b",
            "sourceColumn": "CustomerSoldTo[BillingIsBlockedForCustomer]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "OrderIsBlockedForCustomer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3bf2eacb-26f4-437b-9cf7-9b06ce032d9c",
            "sourceColumn": "CustomerSoldTo[OrderIsBlockedForCustomer]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IsOneTimeAccount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "26a06dbf-8b97-4070-ab6e-8a3ff2152a05",
            "sourceColumn": "CustomerSoldTo[IsOneTimeAccount]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CountryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c0ddb0a9-b58f-4dff-92e5-e5fefd8b968a",
            "sourceColumn": "CustomerSoldTo[CountryID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3f97eb9c-376c-4edc-be1f-68e0d2194b0e",
            "sourceColumn": "CustomerSoldTo[Country]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "CityName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "41e852cf-8a4b-474b-890c-cc088a863f8d",
            "sourceColumn": "CustomerSoldTo[CityName]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "PostalCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "82209653-2cbe-4ca3-a31f-9f13f916675c",
            "sourceColumn": "CustomerSoldTo[PostalCode]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "StreetName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1bd48420-4ca4-4f3b-b1d6-9a5f96afe4fd",
            "sourceColumn": "CustomerSoldTo[StreetName]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "RegionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f78b7845-144a-4225-b24d-0b3248be5e90",
            "sourceColumn": "CustomerSoldTo[RegionID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "84a41be8-51be-48be-a165-184739bf9401",
            "sourceColumn": "CustomerSoldTo[Region]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DeletionIndicator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1d9e41eb-542c-4882-afe5-3391a24635bb",
            "sourceColumn": "CustomerSoldTo[DeletionIndicator]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "TradingPartnerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "262684d9-0435-4bd7-96b9-c31251e83ab6",
            "sourceColumn": "CustomerSoldTo[TradingPartnerID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "TradingPartner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "dcfc0303-7a97-4385-a712-4063d01b8310",
            "sourceColumn": "CustomerSoldTo[TradingPartner]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "BusinessType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8b5aa8ce-5147-4086-be9d-d5196cf1133b",
            "sourceColumn": "CustomerSoldTo[BusinessType]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "IndustryType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e851f61f-7a91-4eda-9911-cb4ba36d3f71",
            "sourceColumn": "CustomerSoldTo[IndustryType]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "t_jobDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9b518cd6-a10f-40ba-9b7e-56370dad2b8b",
            "sourceColumn": "CustomerSoldTo[t_jobDtm]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ID_Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CustomerShippedTo[CustomerID]&\"_\"&CustomerShippedTo[Customer]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c7f78420-2a69-4ca5-b14c-107856d374df",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CustomerID_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b24a73cd-4f8e-4d06-96a3-267f8068f25f",
            "sourceColumn": "CustomerSoldTo[CustomerID_Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e8f96ae7-2425-4f61-a232-1fed50a3a53b",
            "sourceColumn": "CustomerSoldTo[t_applicationId]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "92474125-4103-471e-af20-9dd132c3c85d",
            "sourceColumn": "CustomerSoldTo[t_extractionDtm]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6fde8414-f524-4c98-aa62-9595744ad601",
            "sourceColumn": "CustomerSoldTo[Column]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "c8a0a16f-3a5f-43bd-ba5b-768c9096368d",
        "partitions": [
          {
            "name": "CustomerShippedTo-4263f765-3968-477e-a5f2-9405d599f149",
            "mode": "import",
            "source": {
              "expression": "CALCULATETABLE(CustomerSoldTo)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "_Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Measures",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Other measures",
            "isHidden": true,
            "lineageTag": "61223085-13c0-4932-a217-dc0ae519aa58",
            "sourceColumn": "Measures",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d0c28a7a-3fae-4b09-bc56-55fb48bbc05e",
        "measures": [
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Sales and Margins",
            "expression": "round(SUM(fact_ACDOCA_EPMSalesView[SalesAmount]),2)",
            "lineageTag": "4f1c9c8d-b459-48d1-9b88-2171e6aaa716"
          },
          {
            "name": "Sales PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Sales and Margins",
            "expression": "round(CALCULATE([AmountInCompanyCodeCurrency], DATEADD('Calendar'[Date],-1,YEAR)),1)",
            "lineageTag": "5a00f47c-de7b-4334-9268-97eb89839ff1"
          },
          {
            "name": "DeltaNetAmount",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "EPM Deltas",
            "expression": "IF([Sales PY]<>BLANK(), [Sales]-[Sales PY], BLANK())",
            "formatString": "#,0",
            "lineageTag": "626f5c0a-8301-4ceb-b4ce-fb46f5f8e209"
          },
          {
            "name": "DeltaNetAmount%",
            "displayFolder": "EPM Deltas",
            "expression": "DIVIDE([DeltaNetAmount], [Sales PY], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a68f2def-9803-4968-b320-d2834d271326"
          },
          {
            "name": "DeltaMargin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "EPM Deltas",
            "expression": "IF([GrossMargin PY]<>0, [GrossMargin] - [GrossMargin PY], BLANK())",
            "formatString": "#,0",
            "lineageTag": "430ac9d6-5014-41db-b421-b634bc941d4c"
          },
          {
            "name": "KPI",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "KPI dynamic",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE(srv_MeasureTypes[Choose KPI]),",
              "    SWITCH(",
              "        VALUES(srv_MeasureTypes[Choose KPI]),",
              "        ---- Analysis",
              "        \"1_Net Invoice Sales\", [1_Net Invoice Sales],",
              "        \"1a_Rebate Accruals\", [1a_Rebate Accruals], ",
              "        \"2_Net Revenue\", [2_Net Revenue],",
              "        \"2a_Fin Accr & Rebates\", [2a_Fin Accr & Rebates],",
              "        \"3_Reported Revenue\", [3_Reported Revenue],",
              "        \"3a_COGS Standard\", [3a_COGS Standard],",
              "        \"3b_COGS Actual\", [3b_COGS Actual],",
              "        \"5_Standard Finance Margin\", [5_Standard Finance Margin],",
              "        \"6_Actual Finance Margin\", [6_Actual Finance Margin],",
              "        \"7_Gross Margin\", [7_Gross Margin],",
              "        \"7%_Gross Margin %\",  DIVIDE([7_Gross Margin], [3_Reported Revenue], 0) *100, ",
              "        --- Predefined ",
              "        \"Sales\", [Sales],",
              "        \"COGS\", IF(SELECTEDVALUE(srv_Cogs_cost[Choose KPI])=\"At actual cost\",[Cogs a/c],[Cogs]),",
              "        \"Sales Margin\", [SalesMargin],",
              "        \"Other CoS\", [OtherCOS],",
              "        \"Gross Profit\", [GrossProfit],",
              "        \"Opex\", [Opex],",
              "        \"Gross Margin\", [GrossMargin],",
              "        \"MC %\", [MC %] *100,",
              "        \"Sales Margin %\", DIVIDE([SalesMargin],[Sales],0)  *100,",
              "        \"Profit Margin %\", DIVIDE([GrossProfit],[Sales],0)  *100",
              "            ),",
              "    [Sales]",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "c341e0e2-a7a9-4035-bb18-59c09b040c04"
          },
          {
            "name": "KPI PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "KPI dynamic",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE(srv_MeasureTypes[Choose KPI]),",
              "    SWITCH(",
              "        VALUES(srv_MeasureTypes[Choose KPI]),",
              "                ---- Analysis",
              "        \"1_Net Invoice Sales\", [1_Net Invoice Sales PY],",
              "        \"1a_Rebate Accruals\", [1a_Rebate Accruals PY], ",
              "        \"2_Net Revenue\", [2_Net Revenue PY],",
              "        \"2a_Fin Accr & Rebates\", [2a_Fin Accr & Rebates PY],",
              "        \"3_Reported Revenue\", [3_Reported Revenue PY],",
              "        \"3a_COGS Standard\", [3a_COGS Standard PY],",
              "        \"3b_COGS Actual\", [3b_COGS Actual PY],",
              "        \"5_Standard Finance Margin\", [5_Standard Finance Margin PY],",
              "        \"6_Actual Finance Margin\", [6_Actual Finance Margin PY],",
              "        \"7_Gross Margin\", [7_Gross Margin PY],",
              "        \"7%_Gross Margin %\", [7_Grosss Margin % PY] *100 ,",
              "        --- Predefined ",
              "        \"Sales\", [Sales PY],",
              "        \"COGS\", IF(SELECTEDVALUE(srv_Cogs_cost[Choose KPI])=\"At actual cost\",[COGS a/c PY],[COGS PY]),",
              "        \"Sales Margin\", [SalesMargin PY],",
              "        \"Other CoS\", [OtherCOS PY],",
              "        \"Gross Profit\", [GrossProfit PY],",
              "        \"Opex\", [Opex PY],",
              "        \"Gross Margin\", [GrossMargin PY],",
              "        \"MC %\", [MC % PY] *100,",
              "        \"Sales Margin %\", DIVIDE([SalesMargin Py],[Sales PY],0) *100,",
              "        \"Profit Margin %\", DIVIDE([GrossProfit PY],[Sales PY],0) *100",
              "            ),",
              "    [Sales PY]",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "21262827-f781-4e4e-aa40-0448da832329"
          },
          {
            "name": "LastUpdated",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "displayFolder": "Notifications",
            "expression": "CALCULATE(MAX(fact_ACDOCA_EPMSalesView[t_extractionDtm]), ALL(fact_ACDOCA_EPMSalesView))",
            "formatString": "d mmmm\\, yyyy",
            "isHidden": true,
            "lineageTag": "b6e98520-281d-4c38-bc93-8aed7a9bc1a8"
          },
          {
            "name": "DeltaMargin%",
            "displayFolder": "EPM Deltas",
            "expression": "DIVIDE([DeltaMargin], [GrossMargin PY], BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "93937cc7-75ed-4211-9b2a-dfabf451df31"
          },
          {
            "name": "BillingDocsNumber",
            "displayFolder": "BillingDocs",
            "expression": "CALCULATE(DISTINCTCOUNT(fact_ACDOCA_EPMSalesView[ReferenceDocument]), fact_ACDOCA_EPMSalesView[ReferenceDocument] <> BLANK())",
            "formatString": "#,0",
            "lineageTag": "6f49d0a1-8c77-4dbb-9224-1a29d91b774f"
          },
          {
            "name": "BillingDocsNumber PY",
            "displayFolder": "BillingDocs",
            "expression": "CALCULATE([BillingDocsNumber], DATEADD('Calendar'[Date], -1, year))",
            "formatString": "#,0",
            "lineageTag": "919cae90-694a-4389-b6ca-d874b99e6bd8"
          },
          {
            "name": "DeltaBillingDocsNumber%",
            "displayFolder": "EPM Deltas",
            "expression": "DIVIDE([BillingDocsNumber]-[BillingDocsNumber PY], [BillingDocsNumber PY])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "68fdffec-168c-4004-8296-6dbce6bace55"
          },
          {
            "name": "OrderAmount",
            "displayFolder": "Other measures",
            "expression": "DISTINCTCOUNT(fact_ACDOCA_EPMSalesView[SalesDocumentID])",
            "formatString": "0",
            "lineageTag": "283b567d-d716-4d59-8770-b4efbf3de86a"
          },
          {
            "name": "OrderAmount PY",
            "displayFolder": "Other measures",
            "expression": "CALCULATE([OrderAmount], DATEADD('Calendar'[Date], -1, year))",
            "formatString": "0",
            "lineageTag": "2f43185c-1204-4316-9fe5-9b68fd5d67a8"
          },
          {
            "name": "DeltaOrdersAmount%",
            "displayFolder": "EPM Deltas",
            "expression": "DIVIDE([OrderAmount]-[OrderAmount PY], [OrderAmount PY])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f0d8cf1a-a048-4147-8e7e-dbf786ba62f3"
          },
          {
            "name": "Sales&MarginsK",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Sales and Margins",
            "expression": "DIVIDE([KPI],1000)",
            "isHidden": true,
            "lineageTag": "baf7d5ac-44e8-4046-8714-f3dc7b17ba09"
          },
          {
            "name": "DeltaSales&Margins%",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Deltas",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE(srv_MeasureTypes[Choose KPI]),",
              "    SWITCH(",
              "        VALUES(srv_MeasureTypes[Choose KPI]),",
              "        \"Sales\", [DeltaNetAmount%]",
              "    ),",
              "    [DeltaNetAmount%]",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "ac52aa54-5ad6-4ee1-bf41-6c94c52c5084"
          },
          {
            "name": "DeltaSales&MarginsNegative",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Deltas",
            "expression": "IF([DeltaSales&Margins%]<0, [DeltaSales&Margins%]*100)",
            "isHidden": true,
            "lineageTag": "c3912969-99dc-43ae-8f0b-4cbd6ccaeec0"
          },
          {
            "name": "DeltaSales&MarginsPositive",
            "displayFolder": "EPM Deltas",
            "expression": "IF([DeltaSales&Margins%]>0, format([DeltaSales&Margins%]*100,\"+##.#\"))",
            "isHidden": true,
            "lineageTag": "e8af633f-23ba-42a0-a76b-a0f5398388c7"
          },
          {
            "name": "Sales&MarginsRank",
            "displayFolder": "EPM Sales and Margins",
            "expression": "IF(ISBLANK([KPI]), BLANK(), RANKX(ALLSELECTED('Product'[Product_L3_Type]), CALCULATE([KPI])))",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cb5b0419-77d8-4f47-8b5e-944d2d5c1102"
          },
          {
            "name": "Sales&MarginsRank PY",
            "displayFolder": "EPM Sales and Margins",
            "expression": "IF( ISBLANK([KPI]), BLANK(), RANKX(ALLSELECTED('Product'[Product_L3_Type]), CALCULATE([KPI PY])) )",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2bb608d9-5bd5-4a11-a7bd-b7f3ef892923"
          },
          {
            "name": "DeltaKPIRank",
            "displayFolder": "EPM Deltas",
            "expression": "[Sales&MarginsRank PY]-[Sales&MarginsRank]",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5e386b4c-2d14-489e-b200-d0068254d9c0"
          },
          {
            "name": "DeltaSales&MarginsRankSign",
            "displayFolder": "EPM Deltas",
            "expression": "IF( [DeltaKPIRank]<>0, IF([DeltaKPIRank]>0, \"+\"&[DeltaKPIRank], [DeltaKPIRank]) )",
            "isHidden": true,
            "lineageTag": "b9533f8b-c71f-4fad-852e-644c3baba3d7"
          },
          {
            "name": "CustomerAmount",
            "displayFolder": "Other measures",
            "expression": "DISTINCTCOUNT(fact_ACDOCA_EPMSalesView[CustomerID])",
            "formatString": "0",
            "lineageTag": "d15449f3-25ba-4877-a487-6f037aa014a9"
          },
          {
            "name": "CustomerAmount PY",
            "displayFolder": "Other measures",
            "expression": "CALCULATE([CustomerAmount], DATEADD('Calendar'[Date], -1, year))",
            "formatString": "0",
            "lineageTag": "c65565f2-2149-4c2e-939d-b92f1fca4c69"
          },
          {
            "name": "DeltaCustomerAmount%",
            "displayFolder": "EPM Deltas",
            "expression": "DIVIDE([CustomerAmount]-[CustomerAmount PY], [CustomerAmount PY])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "79d49806-7661-4861-8e65-ce0a744c47c0"
          },
          {
            "name": "MsgCurrentCurrency",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "var CurrencyCount = CALCULATE(DISTINCTCOUNT(fact_ACDOCA_EPMSalesView[CurrencyID]))",
              "return",
              "IF(CurrencyCount<1,\"\",if(CurrencyCount=1, \"Values currency: \"&MAX(fact_ACDOCA_EPMSalesView[CurrencyID]), \"Error: There are different currencies in the dataset\"))"
            ],
            "isHidden": true,
            "lineageTag": "59f0802e-f7f5-4401-b112-609150536274"
          },
          {
            "name": "CurrentCurrency_Int",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "if([MsgCurrentCurrency]=\"Error: There are different currencies in the dataset\", 0, 1)"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5ce025bf-aa93-4a24-9534-cf35a5a76a64"
          },
          {
            "name": "Slicer_filter",
            "displayFolder": "Other measures",
            "expression": "COUNTROWS(fact_ACDOCA_EPMSalesView)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c33bc8a4-750e-4ffa-bac5-c43667731cf7"
          },
          {
            "name": "KPI Delta",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "KPI dynamic",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE(srv_MeasureTypes[Choose KPI]),",
              "    SWITCH(",
              "        VALUES(srv_MeasureTypes[Choose KPI]),",
              "                ---- Analysis",
              "        \"1_Net Invoice Sales\", [Delta 1_Net Invoice Sales],",
              "        \"1a_Rebate Accruals\", [Delta 1a_Rebate Accruals], ",
              "        \"2_Net Revenue\", [Delta 2_Net Revenue],",
              "        \"2a_Fin Accr & Rebates\", [Delta 2a_Fin Accr & Rebates],",
              "        \"3_Reported Revenue\", [Delta 3_Reported Revenue],",
              "        \"3a_COGS Standard\", [Delta 3a_COGS Standard],",
              "        \"3b_COGS Actual\", [Delta 3b_Cogs Actual],",
              "        \"5_Standard Finance Margin\", [Delta 5_Standard Finance Margin],",
              "        \"6_Actual Finance Margin\", [Delta 6_Actual Finance Margin],",
              "        \"7_Gross Margin\", [Delta 7_Gross Margin],",
              "        \"7%_Gross Margin %\", FORMAT([Delta 7_Gross Margin %], \"Percent\"), ",
              "        ----------- Predefined",
              "        \"Sales\", [DeltaNetAmount],",
              "        \"COGS\", IF(SELECTEDVALUE(srv_Cogs_cost[Choose KPI])=\"At actual cost\",[DeltaCogs],[DeltaCogs a/c]),",
              "        \"Sales Margin\", [DeltaSalesMargin],",
              "        \"Other CoS\", [DeltaOtherCOS],",
              "        \"Gross Profit\", [DeltaGrossProfit]",
              "            ),",
              "    [DeltaNetAmount]",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "87bbd84b-d45e-48a9-b292-1c5c9fe9ecb0"
          },
          {
            "name": "Title_SalesDistrict",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\" by Sales District\"",
            "isHidden": true,
            "lineageTag": "75d9d2b0-b8ea-4918-a695-ac2c262aa96e"
          },
          {
            "name": "Title_Country",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\" by Delivery Country\"",
            "isHidden": true,
            "lineageTag": "e627857b-b072-452c-9b13-06b20fb22e42"
          },
          {
            "name": "Sales&MarginsK PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Sales and Margins",
            "expression": "DIVIDE([KPI PY],1000)",
            "isHidden": true,
            "lineageTag": "c26b17a0-5a87-4f83-96aa-2208ce9c1782"
          },
          {
            "name": "MsgCurrentCountry",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "var CountryCount = CALCULATE(DISTINCTCOUNT(fact_ACDOCA_EPMSalesView[SalesOrganizationID]),SalesOrganization[SalesOrganizationID]<>\"MA-Dummy\")",
              "return",
              "IF(CountryCount<1,\"\",if(CountryCount=1, \"Country: \"&CALCULATE(MAX(SalesOrganization[SalesOrganization]),SalesOrganization[SalesOrganizationID]<>\"MA-Dummy\"), \"Multiple countries\"))"
            ],
            "isHidden": true,
            "lineageTag": "8e1c80fa-ba08-4e48-a199-b5184a0930ba"
          },
          {
            "name": "Billing Docs per Order",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "BillingDocs",
            "expression": "DIVIDE([BillingDocsNumber],[OrderAmount])",
            "lineageTag": "2cb47249-5485-4d4e-825e-ca55ee73a751"
          },
          {
            "name": "Billing Docs per Order PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "BillingDocs",
            "expression": "CALCULATE([Billing Docs per Order], DATEADD('Calendar'[Date], -1, year))",
            "lineageTag": "3037583c-4e60-41bd-8973-c91f75d80bd1"
          },
          {
            "name": "Billing Docs per Order Delta",
            "displayFolder": "BillingDocs",
            "expression": "DIVIDE([Billing Docs per Order]-[Billing Docs per Order PY], [Billing Docs per Order PY])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7391fc2b-1ab8-474e-bf88-7f72261a93cc"
          },
          {
            "name": "Title_Project",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\" by Project\"",
            "isHidden": true,
            "lineageTag": "769a0239-5ce2-49c6-9e49-dd2fc2dc710d"
          },
          {
            "name": "Title_Product",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\" by Product\"",
            "isHidden": true,
            "lineageTag": "84159268-5b20-4256-999d-a61d072e4d0d"
          },
          {
            "name": "Title_Customer",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\" by Customer\"",
            "isHidden": true,
            "lineageTag": "4b030f43-95c5-48c3-aef6-6f0f1c78e38d"
          },
          {
            "name": "Title_tooltip_chart",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\" by Month\"",
            "isHidden": true,
            "lineageTag": "1e7f3fdf-89b4-4eed-aa75-34b406f8e46d"
          },
          {
            "name": "Title_tooltip_chart_week",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\" by Week\"",
            "isHidden": true,
            "lineageTag": "fa6f1fa7-8de6-448f-96d4-885dbb0f1e52"
          },
          {
            "name": "Title_YTD",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\": YTD vs PY by Month\"",
            "isHidden": true,
            "lineageTag": "d90466ff-5ad9-4b12-b8ba-7ea5d4a1471b"
          },
          {
            "name": "Title_YTD_week",
            "displayFolder": "Titles",
            "expression": "SELECTEDVALUE(srv_MeasureTypes[Choose KPI])&\": YTD vs PY by Week\"",
            "isHidden": true,
            "lineageTag": "725bf5f4-7069-44af-8ac4-48a46db73e6a"
          },
          {
            "name": "Title_YTD_Delta",
            "displayFolder": "Titles",
            "expression": "\"Delta \"&SELECTEDVALUE(srv_MeasureTypes[Choose KPI])",
            "isHidden": true,
            "lineageTag": "9da6b72a-fa86-4628-a65f-0368b43373e3"
          },
          {
            "name": "SelectedPeriod",
            "displayFolder": "Notifications",
            "expression": "SELECTEDVALUE('Calendar'[MonthName])",
            "isHidden": true,
            "lineageTag": "69352e4d-5afd-476d-8d26-270db67cdc74"
          },
          {
            "name": "SelectedValue_Application",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "",
              "IF (",
              "    ISFILTERED ( fact_ACDOCA_EPMSalesView[Application] ),",
              "    CONCATENATEX ( FILTERS ( fact_ACDOCA_EPMSalesView[Application]), fact_ACDOCA_EPMSalesView[Application], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "ff50b1c4-9fb1-4116-a8c1-3dfc2589b871"
          },
          {
            "name": "SelectedValue_SalesOrganization",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( SalesOrganization[SalesOrganization] ),",
              "    CONCATENATEX ( FILTERS ( SalesOrganization[SalesOrganization]), SalesOrganization[SalesOrganization], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "e0298159-df4c-4cec-b4f3-0389bc0f028f"
          },
          {
            "name": "SelectedValue_Product",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Product'[Product]),",
              "    CONCATENATEX ( FILTERS ( 'Product'[Product]), 'Product'[Product], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "ca251011-0cef-45c4-8f79-29100bc2ccb7"
          },
          {
            "name": "SelectedValue_Period",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "var Year1 = ",
              "IF (",
              "    ISFILTERED ( 'Calendar'[Year] ),",
              "    CONCATENATEX ( FILTERS ( 'Calendar'[Year]), 'Calendar'[Year], \", \" ),",
              "    \"ALL Year\"",
              ")",
              "var Month1 = ",
              "IF (",
              "    ISFILTERED ( 'Calendar'[MonthName] ),",
              "    CONCATENATEX ( FILTERS ( 'Calendar'[MonthName]), 'Calendar'[MonthName], \", \" ),",
              "    \"All Month\"",
              ")",
              "var DateRange = ",
              "IF (",
              "    ISFILTERED ( 'Calendar'[Date] ),",
              "    CONCATENATEX ( FILTERS ( 'Calendar'[Date]), max('Calendar'[Date]), \", \" ),",
              "    \"ALL\"",
              ")",
              "return",
              "Year1&\" \"&Month1"
            ],
            "isHidden": true,
            "lineageTag": "b1c4cfd0-2e4b-478b-bc22-27376d3181e6"
          },
          {
            "name": "SelectedValue_SalesDistrict",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( fact_ACDOCA_EPMSalesView[SalesDistrictID] ),",
              "    CONCATENATEX ( FILTERS ( fact_ACDOCA_EPMSalesView[SalesDistrictID]), fact_ACDOCA_EPMSalesView[SalesDistrictID], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "92f387fc-4450-4758-9090-4667f0b75dcb"
          },
          {
            "name": "SelectedYear",
            "displayFolder": "Notifications",
            "expression": "INT(SELECTEDVALUE('Calendar'[Year]))",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "11906298-af83-474a-86e5-700e14039687"
          },
          {
            "name": "SelectedValue_Region",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( SalesOrganization[RegionName] ),",
              "    CONCATENATEX ( FILTERS (SalesOrganization[RegionName]), SalesOrganization[RegionName], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "e220ad06-2e4f-4f83-a775-4a02ceb2a444"
          },
          {
            "name": "SelectedValue_KPI",
            "displayFolder": "Notifications",
            "expression": [
              "IF (",
              "    AND(ISFILTERED ( srv_MeasureTypes[Choose KPI] ), MAX(srv_MeasureTypes[Type]) = \"Analysis\"), ",
              "    CONCATENATEX ( FILTERS (srv_MeasureTypes[Choose KPI]), srv_MeasureTypes[Choose KPI], \", \" ),",
              "    \"Predefined KPI is chosen\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "1a4d18b1-dee5-4c82-b3ab-66510012e9d4"
          },
          {
            "name": "SelectedValue_Customer",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( CustomerSoldTo[Customer]),",
              "    CONCATENATEX ( FILTERS ( CustomerSoldTo[Customer]), CustomerSoldTo[Customer], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "7fe30e6a-cfc2-4c1b-8dff-9cdd7da137c4"
          },
          {
            "name": "SelectevValue_CurrencyType",
            "displayFolder": "Notifications",
            "expression": "SELECTEDVALUE(fact_ACDOCA_EPMSalesView[CurrencyType])",
            "isHidden": true,
            "lineageTag": "2593a28b-6e14-4a0e-ba93-0878599d8e27"
          },
          {
            "name": "SelectedValue_MaterialType",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Product'[MaterialType]),",
              "    CONCATENATEX ( FILTERS ('Product'[MaterialType]),'Product'[MaterialType], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "5d22be37-cea2-4ca3-85c4-d7cfd55ac6e3"
          },
          {
            "name": "SelectedValue_BillingDocType",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( fact_ACDOCA_EPMSalesView[BillingDocumentTypeID]),",
              "    CONCATENATEX ( FILTERS ( fact_ACDOCA_EPMSalesView[BillingDocumentTypeID]), fact_ACDOCA_EPMSalesView[BillingDocumentTypeID], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "d903ce52-8747-43fa-923c-68eddb3675e9"
          },
          {
            "name": "Sales&MarginsCustomerRank",
            "displayFolder": "EPM Sales and Margins",
            "expression": [
              "",
              "IF([KPI]+[KPI PY]=0, BLANK(), --RANKX(ALLSELECTED(CustomerSoldTo[ID_Customer]), CALCULATE([KPI])))",
              "",
              "CALCULATE(RANKX(ALLselected(CustomerSoldTo),[KPI],,DESC,Dense),",
              "    ALLSELECTED(CustomerSoldTo[CityName])))"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "31fbeb8b-0240-4448-9583-8e8ac5393767"
          },
          {
            "name": "Sales&MarginsCustomerRank PY",
            "displayFolder": "EPM Sales and Margins",
            "expression": [
              "",
              "--IF( ISBLANK([KPI]), BLANK(), RANKX(ALLSELECTED(CustomerSoldTo[ID_Customer]), CALCULATE([KPI PY])) )",
              "",
              "CALCULATE(RANKX(all(CustomerSoldTo[CustomerID]),CALCULATE([KPI PY]),,DESC),",
              "    ALLSELECTED(CustomerSoldTo[CityName]))"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "abf37b1f-1d43-448f-b25f-aefb3b0c9d97"
          },
          {
            "name": "DeltaSales&MarginsCustomerRankSign",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "EPM Deltas",
            "expression": "IF( [DeltaKPICustomerRank]<>0, IF([DeltaKPICustomerRank]>0, \"+\"&[DeltaKPICustomerRank], [DeltaKPICustomerRank]) )",
            "isHidden": true,
            "lineageTag": "bf45ebfe-ed0b-44f7-81aa-662297dac6a9"
          },
          {
            "name": "DeltaKPICustomerRank",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "EPM Deltas",
            "expression": "if([CustomerRankFilter]=1,[Sales&MarginsCustomerRank PY]-[Sales&MarginsCustomerRank])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1169a3c7-dd44-42c1-a570-d6540d067f88"
          },
          {
            "name": "CustomerSelected",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "var _filter = SELECTEDVALUE(CustomerSoldTo[CustomerID_Name])",
              "return",
              "if(count(CustomerSoldTo[CustomerID_Name])>1,\"\",\"Customer: \" & _filter)"
            ],
            "isHidden": true,
            "lineageTag": "68ce787d-6892-4a95-a7cc-6cc4ab5999f9"
          },
          {
            "name": "CitySelected",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "var _filter = SELECTEDVALUE(CustomerSoldTo[CityName])",
              "return",
              "if(count(CustomerSoldTo[CustomerID_Name])>1,\"\",\"City: \" & _filter)"
            ],
            "isHidden": true,
            "lineageTag": "393b1da6-736f-4f2c-95c5-121c079cf770"
          },
          {
            "name": "CustomerRankFilter",
            "displayFolder": "Other measures",
            "expression": "IF([KPI]+[KPI PY]=0, 0, 1)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "90f84fc7-e72c-4302-94f1-690fcbace409"
          },
          {
            "name": "KPI Delta color",
            "displayFolder": "KPI dynamic",
            "expression": "IF([KPI Delta]>=0,1,0)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c8cef6dc-e8ec-4206-8d25-4c75a8f74cb7"
          },
          {
            "name": "AmountInCompanyCodeCurrency",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Other measures",
            "expression": "CALCULATE(sum(fact_ACDOCA_EPMSalesView[SalesAmount]))",
            "isHidden": true,
            "lineageTag": "ee0f4511-01ba-475d-8ea7-48ba36573da1"
          },
          {
            "name": "SelectedValue_inoutid",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( fact_ACDOCA_EPMSalesView[InOutID]),",
              "    CONCATENATEX ( FILTERS ( fact_ACDOCA_EPMSalesView[InOutID]), fact_ACDOCA_EPMSalesView[InOutID], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "a329e7a3-6be2-49f4-a3e7-0c276c64c39f"
          },
          {
            "name": "SelectedValue_glaccountid",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( GLAccount[glaccountID_Name]),",
              "    CONCATENATEX ( FILTERS ( GLAccount[glaccountID_Name]), GLAccount[glaccountID_Name], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "d204d9c3-8a9a-4e52-853a-43ac11b85083"
          },
          {
            "name": "SelectedValue_acdoca_ledger",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( fact_ACDOCA_EPMSalesView[SourceLedgerID]),",
              "    CONCATENATEX ( FILTERS ( fact_ACDOCA_EPMSalesView[SourceLedgerID]), fact_ACDOCA_EPMSalesView[SourceLedgerID], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "b02c560a-d8b4-47ef-8995-e1fd95694983"
          },
          {
            "name": "SelectedValue_acdoca_tpadjustment",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( fact_ACDOCA_EPMSalesView[TPAdjustment]),",
              "    CONCATENATEX ( FILTERS ( fact_ACDOCA_EPMSalesView[TPAdjustment]), fact_ACDOCA_EPMSalesView[TPAdjustment], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "ffb1503e-12a2-451b-968c-3cf4ccd77131"
          },
          {
            "name": "SelectedValue_acdoca_ma_adjustment",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( fact_ACDOCA_EPMSalesView[ManualAdjustment]),",
              "    CONCATENATEX ( FILTERS ( fact_ACDOCA_EPMSalesView[ManualAdjustment]), fact_ACDOCA_EPMSalesView[ManualAdjustment], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "6981f406-ff33-42e7-a758-701e98c7e35d"
          },
          {
            "name": "SelectedValue_profit_center",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( ProfitCenter[ProfitCenter]),",
              "    CONCATENATEX ( FILTERS ( ProfitCenter[ProfitCenter]), ProfitCenter[ProfitCenter], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "8d7170c7-3046-44ea-af9b-580077f3f616"
          },
          {
            "name": "SelectedValue_product_group",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Product'[Product_L2_Group]),",
              "    CONCATENATEX ( FILTERS (  'Product'[Product_L2_Group]),  'Product'[Product_L2_Group], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "57920142-aa13-408f-95a9-2ff76d4a8099"
          },
          {
            "name": "SelectedValue_product_pillar",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Product'[Product_L1_Pillar]),",
              "    CONCATENATEX ( FILTERS ( 'Product'[Product_L1_Pillar]), 'Product'[Product_L1_Pillar], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "86086cb1-c8cd-4d89-851f-03956e559482"
          },
          {
            "name": "SelectedValue_brand",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Product'[Brand]),",
              "    CONCATENATEX ( FILTERS ( 'Product'[Brand]), 'Product'[Brand], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "4277d929-8d47-49f4-9f94-9c26714f2366"
          },
          {
            "name": "NetAmount YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Sales and Margins",
            "expression": "round(TOTALYTD(sum(fact_ACDOCA_EPMSalesView[SalesAmount]),'Calendar'[Date]),1)",
            "lineageTag": "03f0dfa6-c0dd-41f1-b288-f8819aa4bb2b"
          },
          {
            "name": "NetAmount PY YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Sales and Margins",
            "expression": "round(CALCULATE([NetAmount YTD], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "b5ae0be2-234b-4798-8b27-06b1505f420b"
          },
          {
            "name": "DeltaNetAmount YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Deltas",
            "expression": "IF([NetAmount PY YTD]<>BLANK(), [NetAmount YTD]-[NetAmount PY YTD], BLANK())",
            "lineageTag": "d956ccb3-5da7-444a-9bb0-65128f02a22a"
          },
          {
            "name": "SelectedValue_Companycode_ID",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( fact_ACDOCA_EPMSalesView[CompanyCodeID] ),",
              "    CONCATENATEX ( FILTERS ( fact_ACDOCA_EPMSalesView[CompanyCodeID]), fact_ACDOCA_EPMSalesView[CompanyCodeID], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "e4b08cbd-0dde-43b0-8977-004a37cf50c8"
          },
          {
            "name": "Cogs",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Cogs",
            "expression": "CALCULATE(SUM(fact_ACDOCA_EPMSalesView[COGSStdCostAmount])) ",
            "lineageTag": "0c39b5da-42b1-4e0d-b0d1-485b1889a7a5"
          },
          {
            "name": "Cogs a/c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Cogs",
            "expression": "CALCULATE(SUM(fact_ACDOCA_EPMSalesView[COGSActCostAmount]))",
            "lineageTag": "49407efb-9ea1-493e-a9e6-aa75cc7955a6"
          },
          {
            "name": "SalesMargin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Sales and Margins",
            "expression": "[Sales]+[cogs_switch]  ",
            "lineageTag": "7126526f-7e41-4001-a881-05e324fe4586"
          },
          {
            "name": "OtherCOS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Sales and Margins",
            "expression": "CALCULATE(SUM(fact_ACDOCA_EPMSalesView[OtherCoSAmount])) ",
            "lineageTag": "a79b5c50-269f-49bb-b6f3-dbebc48942bb"
          },
          {
            "name": "GrossProfit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Sales and Margins",
            "expression": "CALCULATE([SalesMargin]+[OtherCOS])",
            "lineageTag": "20a48e25-81bd-4c87-9ecd-0e721b8f7d3e"
          },
          {
            "name": "COGS PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Cogs",
            "expression": "round(CALCULATE([Cogs], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "76a18151-9fc1-4583-9575-2b0662496b4d"
          },
          {
            "name": "COGS a/c PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Cogs",
            "expression": "round(CALCULATE([Cogs a/c], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "76d6016d-69ab-4639-aa56-d5680c096aa0"
          },
          {
            "name": "SalesMargin PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Sales and Margins",
            "expression": "round(CALCULATE([SalesMargin], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "ad2b19eb-823f-4ce9-b33d-463ae31acba4"
          },
          {
            "name": "OtherCOS PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Sales and Margins",
            "expression": "round(CALCULATE([OtherCOS], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "5cbe6f5e-b52b-44f9-8921-d15770717a2c"
          },
          {
            "name": "GrossProfit PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Sales and Margins",
            "expression": "round(CALCULATE([GrossProfit], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "a9bd23cb-cbb2-4521-88e0-061b5469f966"
          },
          {
            "name": "MsgCogsCost",
            "displayFolder": "Notifications",
            "expression": "IF(SELECTEDVALUE(srv_Cogs_cost[Choose KPI]) =\"At Standard Cost\", \"Standard Cost\", \"Actual cost\")",
            "isHidden": true,
            "lineageTag": "664f180d-0ca7-4d9a-9180-23e80e31ed19"
          },
          {
            "name": "DeltaSalesMargint%",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "EPM Deltas",
            "expression": "DIVIDE(IF([SalesMargin PY]<>BLANK(), [SalesMargin]-[SalesMargin PY], BLANK()), [SalesMargin PY], BLANK())",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "8eb4dedc-84fd-4f6a-98e3-c19ccf2f40a3"
          },
          {
            "name": "DeltaCogs",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Deltas",
            "expression": "IF([Cogs]<>BLANK(), [Cogs]-[Cogs PY], BLANK())",
            "lineageTag": "d68135ee-90e4-47e3-a135-4f7ecf6c4635"
          },
          {
            "name": "DeltaCogs a/c",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Deltas",
            "expression": "IF([Cogs a/c]<>BLANK(), [Cogs a/c]-[Cogs a/c], BLANK())",
            "lineageTag": "493ffe37-56f9-462b-9775-5d033b22d5ff"
          },
          {
            "name": "DeltaSalesMargin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Deltas",
            "expression": "IF([SalesMargin]<>BLANK(), [SalesMargin]-[SalesMargin PY], BLANK())",
            "lineageTag": "f7dd0402-7e31-44c2-be7c-926674be51a1"
          },
          {
            "name": "DeltaOtherCOS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Deltas",
            "expression": "IF([OtherCOS]<>BLANK(), [OtherCOS]-[OtherCOS PY], BLANK())",
            "lineageTag": "270b3026-f4d2-4efb-9861-d1497beac55b"
          },
          {
            "name": "DeltaProfitMargin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Deltas",
            "expression": "IF([GrossProfit]<>BLANK(), [GrossProfit]-[GrossProfit PY], BLANK())",
            "lineageTag": "1abc6c27-59aa-4d68-a581-34920263ee25"
          },
          {
            "name": "DeltaGrossProfit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Deltas",
            "expression": "IF([GrossProfit]<>BLANK(), [GrossProfit]-[GrossProfit PY], BLANK())",
            "lineageTag": "784ead95-aa28-4028-b012-6ccb7af2c2d4"
          },
          {
            "name": "cogs_switch",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Cogs",
            "expression": "IF(SELECTEDVALUE(srv_Cogs_cost[Choose KPI])=\"At standard cost\",[Cogs],[Cogs a/c])",
            "isHidden": true,
            "lineageTag": "fbe0d9c5-362d-4057-aba5-2d0ca1ba8d20"
          },
          {
            "name": "cogs_switch_py",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Cogs",
            "expression": "IF(SELECTEDVALUE(srv_Cogs_cost[Choose KPI])=\"At standard cost\", [Cogs a/c py],[COGS PY])",
            "isHidden": true,
            "lineageTag": "226d59c9-e1f4-4ee9-812b-c933c2a2c030"
          },
          {
            "name": "Amount cy",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Other measures",
            "expression": "CALCULATE(SUM(fact_ACDOCA_EPMSalesView[Amount]))",
            "lineageTag": "a755adc1-51a0-4553-a616-0f51e48e0515"
          },
          {
            "name": "Amount PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Other measures",
            "expression": "round(CALCULATE([Amount cy], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "fe59f185-9016-487c-b66f-6804077d8c13"
          },
          {
            "name": "DeltaNetAmount_col",
            "displayFolder": "EPM Deltas",
            "expression": "IF([DeltaNetAmount%]<0,0,1) ",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fb034030-ae83-4b4b-aff0-06c654a04635"
          },
          {
            "name": "DeltaSalesMargin_col",
            "displayFolder": "EPM Deltas",
            "expression": "IF([DeltaSalesMargint%]<0,0,1) ",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b56683e1-2bfd-4b4f-b26e-ba95ee85f194"
          },
          {
            "name": "DeltaCustAmount_col",
            "displayFolder": "EPM Deltas",
            "expression": "IF([DeltaCustomerAmount%]<0,0,1) ",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "273cd2d7-e3de-4f6f-ade4-28651b198061"
          },
          {
            "name": "GrossMargin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Sales and Margins",
            "expression": "CALCULATE(SUM(fact_ACDOCA_EPMSalesView[GrossMarginAmount])) ",
            "lineageTag": "0b6511c5-5f5d-44b3-b3af-b308a3d9d734"
          },
          {
            "name": "DeltaKPI%",
            "displayFolder": "EPM Deltas",
            "expression": "DIVIDE(IF([KPI PY]<>BLANK(), [KPI]-[KPI PY], BLANK()), [KPI PY], BLANK())",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "0cb73459-c7bc-45aa-8c91-ed427d7749d6"
          },
          {
            "name": "Opex",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Sales and Margins",
            "expression": "CALCULATE(SUM(fact_ACDOCA_EPMSalesView[OpexAmount])) ",
            "lineageTag": "1d4872f2-531e-4cc1-8634-1786f777cf9c"
          },
          {
            "name": "Opex PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Sales and Margins",
            "expression": "round(CALCULATE([Opex], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "d37c49d2-877c-4644-9550-6353a4fdcb47"
          },
          {
            "name": "GrossMargin PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Sales and Margins",
            "expression": "round(CALCULATE([GrossMargin], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "a76d03b7-7414-4ae7-8870-ec52bfe364bb"
          },
          {
            "name": "MC %",
            "displayFolder": "EPM Sales and Margins",
            "expression": "DIVIDE([GrossMargin],[Sales],0)",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "4d149eac-d423-4c38-9d1f-947aafd7ed43"
          },
          {
            "name": "MC % PY",
            "displayFolder": "EPM Sales and Margins",
            "expression": "CALCULATE([MC %], DATEADD('Calendar'[Date], -1, year))",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "62283583-bfad-4ff4-95fc-932507f5969f"
          },
          {
            "name": "Sales Margin %",
            "displayFolder": "EPM Sales and Margins",
            "expression": "DIVIDE([SalesMargin],[Sales],0) ",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "e58a745e-7a49-4fd4-b522-c7301c9a598f"
          },
          {
            "name": "Profit Margin %",
            "displayFolder": "EPM Profit",
            "expression": "DIVIDE([GrossProfit],[Sales],0) ",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "bbe2fea2-cb07-47a5-b2b6-981f318a26a4"
          },
          {
            "name": "KPI_Tooltip_Title",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "KPI dynamic",
            "expression": "CONCATENATE(SELECTEDVALUE(srv_MeasureTypes[Choose KPI]),\" by Week\")",
            "isHidden": true,
            "lineageTag": "23d8adf0-e7b5-4d71-b875-33a45eb37fe2"
          },
          {
            "name": "Sales Margin % PY",
            "displayFolder": "EPM Sales and Margins",
            "expression": "DIVIDE([SalesMargin PY],[Sales PY],0) ",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "f6814f94-25d9-4bf2-b94f-84aaf9ae7f38"
          },
          {
            "name": "Profit Margin % PY",
            "displayFolder": "EPM Profit",
            "expression": "DIVIDE([GrossProfit PY],[Sales PY],0) ",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "2e100bc7-132b-4a03-ae7b-3544f4c06ff0"
          },
          {
            "name": "Profit Margin % Delta",
            "displayFolder": "EPM Profit",
            "expression": "[Profit Margin %]-[Profit Margin % PY]",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "abecb395-2405-43da-9663-90b080c836df"
          },
          {
            "name": "Delta Gross Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Deltas",
            "expression": "[GrossMargin]-[GrossMargin PY]",
            "lineageTag": "c54dd845-d6db-4b9b-8379-8df390baaea6"
          },
          {
            "name": "Delta MC %",
            "displayFolder": "EPM Deltas",
            "expression": "[MC %]-[MC % PY] ",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "d7ab77cf-5a0a-429d-8181-f68e71dcccc6"
          },
          {
            "name": "SelectedValue_Source",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( fact_ACDOCA_EPMSalesView[Source]),",
              "    CONCATENATEX ( FILTERS ( fact_ACDOCA_EPMSalesView[Source]), fact_ACDOCA_EPMSalesView[Source], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "a56122bd-8b46-4608-af41-e49c1aca9127"
          },
          {
            "name": "SelectedValue_Subsource",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( fact_ACDOCA_EPMSalesView[Subsource]),",
              "    CONCATENATEX ( FILTERS ( fact_ACDOCA_EPMSalesView[Subsource]), fact_ACDOCA_EPMSalesView[Subsource], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "793c10dc-45b9-45a8-a4c4-62be4f1b5297"
          },
          {
            "name": "SelectedValue_Predefined_KPI",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF (",
              "    AND(ISFILTERED (srv_MeasureTypes[Choose KPI] ), MAX(srv_MeasureTypes[Type]) = \"Predefined\"), ",
              "    CONCATENATEX ( FILTERS (srv_MeasureTypes[Choose KPI]), srv_MeasureTypes[Choose KPI], \", \" ),",
              "    \"Analysis KPI is chosen\"",
              ")"
            ],
            "lineageTag": "f1d2dc17-ffc2-4373-9de8-4e0fc39513e3"
          },
          {
            "name": "SelectedValue_PredefinedKPI_filters",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "SWITCH([SelectedValue_Predefined_KPI],",
              "        -- 1",
              "        \"1_Net Invoice Sales\", ",
              "        \"Source: Billing, Net invoice Sales;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Standard;\",",
              "        -- 2",
              "        \"1a_Rebate Accruals\", ",
              "        \"Source: Billing, Rebates;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Standard;\",",
              "        -- 3",
              "        \"2_Net Revenue\", ",
              "        \"Source: Billing, Net invoice Sales, Rebates;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Standard;\",",
              "        -- 4",
              "        \"2a_Fin Accr & Rebates\", ",
              "        \"Source: Finance, Finance;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Standard;\",",
              "        -- 5",
              "        \"3_Reported Revenue\", ",
              "        \"Source: All;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Standard;\",",
              "        -- 6",
              "        \"3a_COGS Standard\", ",
              "        \"Source: All;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Standard;\",",
              "        -- 7       ",
              "        \"3b_COGS Actual\", ",
              "        \"Source: All;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Actual;\",",
              "        -- 8",
              "        \"5_Standard Finance Margin\", ",
              "        \"Source: All;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Standard;\",",
              "        -- 9",
              "        \"6_Actual Finance Margin\", ",
              "        \"Source: All;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Actual;\",",
              "        -- 10",
              "        \"7_Gross Margin\", ",
              "        \"Source: All;",
              "        TP Adjustment: 0;",
              "        ACDOCA Ledger: 0L, OC;",
              "        GL Account: ALL;",
              "        COGS Cost: Actual;\")",
              ""
            ],
            "lineageTag": "9a29e809-3d7e-45fa-90a5-cbdd9bb28945"
          },
          {
            "name": "SelectedValue_KPI_type",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF(",
              "    AND([SelectedValue_KPI] = \"Predefined KPI is chosen\", [SelectedValue_Predefined_KPI] = \"Analysis KPI is chosen\"),",
              "    \"KPI has to be selected in main slicer pane respectively to type selected in hidden filter panel\", SELECTEDVALUE(srv_MeasureTypes[Type])",
              ")"
            ],
            "lineageTag": "111e3ae6-a288-4d88-b55c-1b652ee88219"
          },
          {
            "name": "1_Net Invoice Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE(",
              "    [Sales], ",
              "    fact_ACDOCA_EPMSalesView[Source] = \"Billing\",",
              "    fact_ACDOCA_EPMSalesView[SubSourceShort] = \"Net\",",
              "    fact_ACDOCA_EPMSalesView[TPAdjustment] = 0,",
              "    fact_ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\"},",
              "    ALL(GLAccount[glaccountID_Name]),",
              "    FILTER(fact_ACDOCA_EPMSalesView, CONCATENATE(fact_ACDOCA_EPMSalesView[CompanyCodeID],fact_ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              "    )"
            ],
            "lineageTag": "90a3524b-cd8e-4fbe-b218-863114d2d211"
          },
          {
            "name": "1_Net Invoice Sales PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([1_Net Invoice Sales], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "d4093ff4-2451-4b79-ad48-c06c758d66a2"
          },
          {
            "name": "1_Net Invoice Sales PY_1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([1_Net Invoice Sales], SAMEPERIODLASTYEAR('Calendar'[Date])),1)"
            ],
            "lineageTag": "b9467b5e-0232-4ad2-80b0-3d1315c586d7"
          },
          {
            "name": "1a_Rebate Accruals",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([Sales], ",
              "    fact_ACDOCA_EPMSalesView[Source] = \"Billing\",",
              "    fact_ACDOCA_EPMSalesView[SubSourceShort] = \"Reb\",",
              "    fact_ACDOCA_EPMSalesView[TPAdjustment] = 0,",
              "    fact_ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "    ALL(GLAccount[glaccountID_Name]),",
              "    FILTER(fact_ACDOCA_EPMSalesView, CONCATENATE(fact_ACDOCA_EPMSalesView[CompanyCodeID],fact_ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              ")"
            ],
            "lineageTag": "5911c532-0fe9-4767-90f2-242823720be7"
          },
          {
            "name": "1a_Rebate Accruals PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([1a_Rebate Accruals], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "c5d6ce75-d03c-4341-ae12-1f59b106df9b"
          },
          {
            "name": "2_Net Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([Sales], ",
              "    fact_ACDOCA_EPMSalesView[Source] = \"Billing\",",
              "    fact_ACDOCA_EPMSalesView[SubSourceShort] in {\"Reb\", \"Net\"},",
              "    fact_ACDOCA_EPMSalesView[TPAdjustment] = 0,",
              "    fact_ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "    ALL(GLAccount[glaccountID_Name]),",
              "    FILTER(fact_ACDOCA_EPMSalesView, CONCATENATE(fact_ACDOCA_EPMSalesView[CompanyCodeID],fact_ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              ")"
            ],
            "lineageTag": "a93c7cae-4646-4b15-bd9a-0d5077eced16"
          },
          {
            "name": "2_Net Revenue PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([2_Net Revenue], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "f5829ec5-6961-46f3-89d4-246dd7da1319"
          },
          {
            "name": "2a_Fin Accr & Rebates",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([Sales], ",
              "    fact_ACDOCA_EPMSalesView[Source] = \"Finance\",",
              "    fact_ACDOCA_EPMSalesView[SubSourceShort] = \"Fin\",",
              "    fact_ACDOCA_EPMSalesView[TPAdjustment] = 0,",
              "    fact_ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "    ALL(GLAccount[glaccountID_Name]),",
              "    FILTER(fact_ACDOCA_EPMSalesView, CONCATENATE(fact_ACDOCA_EPMSalesView[CompanyCodeID],fact_ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              ")"
            ],
            "lineageTag": "13b42e2e-7b9d-41de-9fb7-51406da6ce16"
          },
          {
            "name": "2a_Fin Accr & Rebates PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([2a_Fin Accr & Rebates], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "9ee5fd78-a241-42a3-811f-cb76766fa163"
          },
          {
            "name": "3_Reported Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([Sales], ",
              "    ALL(fact_ACDOCA_EPMSalesView[Source]), ",
              "    ALL(fact_ACDOCA_EPMSalesView[Subsource]),",
              "    fact_ACDOCA_EPMSalesView[TPAdjustment] = 0,",
              "    fact_ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "    ALL(GLAccount[glaccountID_Name]),",
              "    FILTER(fact_ACDOCA_EPMSalesView, CONCATENATE(fact_ACDOCA_EPMSalesView[CompanyCodeID],fact_ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              ")"
            ],
            "lineageTag": "74e71ed8-ca58-4d59-826f-ccbbdfa72b8b"
          },
          {
            "name": "3_Reported Revenue PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([3_Reported Revenue], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "f38c3308-e01f-4144-9b1c-02246df462bc"
          },
          {
            "name": "3a_COGS Standard",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([Cogs], ",
              "            fact_ACDOCA_EPMSalesView[TPAdjustment] = 0, ",
              "            fact_ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "            ALL(GLAccount), ",
              "            ALL(fact_ACDOCA_EPMSalesView[Source]), ",
              "            ALL(fact_ACDOCA_EPMSalesView[Subsource]),",
              "            FILTER(fact_ACDOCA_EPMSalesView, CONCATENATE(fact_ACDOCA_EPMSalesView[CompanyCodeID],fact_ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              "        )"
            ],
            "lineageTag": "ab8bba5c-f7c5-4516-8cb5-22d5eb7d024c"
          },
          {
            "name": "3a_COGS Standard PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([3a_COGS Standard], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "0f4d1e0d-d7bd-42bc-891c-8072127c3c9f"
          },
          {
            "name": "3b_COGS Actual",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([Cogs a/c], ",
              "            fact_ACDOCA_EPMSalesView[TPAdjustment] = 0, ",
              "            fact_ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "            ALL(GLAccount[GLAccountID]), ",
              "            ALL(fact_ACDOCA_EPMSalesView[Source]), ",
              "            ALL(fact_ACDOCA_EPMSalesView[Subsource]),",
              "            FILTER(fact_ACDOCA_EPMSalesView, CONCATENATE(fact_ACDOCA_EPMSalesView[CompanyCodeID],fact_ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              "        )"
            ],
            "lineageTag": "ea60141e-37c2-492f-8d2c-bfdb424dd8b8"
          },
          {
            "name": "3b_COGS Actual PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([3b_COGS Actual], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "b3e90866-9782-438c-9c82-57dcdf9b7b8e"
          },
          {
            "name": "5_Standard Finance Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([Sales] + [Cogs], ",
              "            fact_ACDOCA_EPMSalesView[TPAdjustment] = 0, ",
              "            fact_ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "            ALL(GLAccount[GLAccountID]), ",
              "            ALL(fact_ACDOCA_EPMSalesView[Source]), ",
              "            ALL(fact_ACDOCA_EPMSalesView[Subsource]),",
              "            FILTER(fact_ACDOCA_EPMSalesView, CONCATENATE(fact_ACDOCA_EPMSalesView[CompanyCodeID],fact_ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              "        )"
            ],
            "lineageTag": "2238eb59-f867-4adf-9320-90c9eb3abd11"
          },
          {
            "name": "5_Standard Finance Margin PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([5_Standard Finance Margin], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "00b6a25d-d39e-48c9-ab5b-d38c8386d44e"
          },
          {
            "name": "6_Actual Finance Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "IF(SELECTEDVALUE(srv_Actual_Finance[Value])=\"Exclude\",",
              "CALCULATE([Sales]+ [Cogs a/c], ",
              "            fact_ACDOCA_EPMSalesView[TPAdjustment] = 0, ",
              "            fact_ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "            ALL(GLAccount[GLAccountID]), ",
              "            ALL(fact_ACDOCA_EPMSalesView[Source]), ",
              "            ALL(fact_ACDOCA_EPMSalesView[Subsource]),",
              "            FILTER(fact_ACDOCA_EPMSalesView, CONCATENATE(fact_ACDOCA_EPMSalesView[CompanyCodeID],fact_ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              "        ),",
              "        CALCULATE([Sales]+ [Cogs a/c] + CALCULATE(SUM(fact_ACDOCA_EPMSalesView[AmountInCompanyCodeCurrency]),fact_ACDOCA_EPMSalesView[GMElementL1]=\"Freight Outbound\"), ",
              "            fact_ACDOCA_EPMSalesView[TPAdjustment] = 0, ",
              "            fact_ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "            ALL(GLAccount[GLAccountID]), ",
              "            ALL(fact_ACDOCA_EPMSalesView[Source]), ",
              "            ALL(fact_ACDOCA_EPMSalesView[Subsource]),",
              "            FILTER(fact_ACDOCA_EPMSalesView, CONCATENATE(fact_ACDOCA_EPMSalesView[CompanyCodeID],fact_ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              "))"
            ],
            "lineageTag": "deb58a71-556b-4d69-b920-721e617b0628"
          },
          {
            "name": "6_Actual Finance Margin PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([6_Actual Finance Margin], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "ccb99efa-4354-4ace-99ad-380bb5735bb4"
          },
          {
            "name": "7_Gross Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([GrossMargin], ",
              "            fact_ACDOCA_EPMSalesView[TPAdjustment] = 0, ",
              "            fact_ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "            ALL(GLAccount[GLAccountID]), ",
              "            ALL(fact_ACDOCA_EPMSalesView[Source]), ",
              "            ALL(fact_ACDOCA_EPMSalesView[Subsource]),",
              "            FILTER(fact_ACDOCA_EPMSalesView, CONCATENATE(fact_ACDOCA_EPMSalesView[CompanyCodeID],fact_ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              "        )"
            ],
            "lineageTag": "90608482-35d9-426a-a3fc-33985223c8cc"
          },
          {
            "name": "7_Gross Margin PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "round(CALCULATE([7_Gross Margin], DATEADD('Calendar'[Date], -1, year)),1)"
            ],
            "lineageTag": "640fed40-005f-4338-9820-f3132348f940"
          },
          {
            "name": "Notification_KPI_name",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF(",
              "    AND([SelectedValue_KPI] = \"Predefined KPI is chosen\", [SelectedValue_Predefined_KPI] = \"Analysis KPI is chosen\"),",
              "    \"select KPI respectively to KPI type\", SELECTEDVALUE(srv_MeasureTypes[Choose KPI])",
              ")"
            ],
            "lineageTag": "0c79e81c-6076-46a2-babf-f5150c374a59"
          },
          {
            "name": "Selected_Period",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "var Year1 = ",
              "IF (",
              "    ISFILTERED ( 'Calendar'[Year] ),",
              "    CONCATENATEX ( FILTERS ( 'Calendar'[Year]), 'Calendar'[Year], \", \" ),",
              "    \"ALL Year\"",
              ")",
              "var Month1 = ",
              "IF (",
              "    ISFILTERED ( 'Calendar'[MonthName] ),",
              "    CONCATENATEX ( FILTERS ( 'Calendar'[MonthName]), 'Calendar'[MonthName], \", \" ),",
              "    \"All Month\"",
              ")",
              "var DateCnt = DISTINCTCOUNT('Calendar'[Day])",
              "var DateRange = ",
              "IF (",
              "    ISFILTERED ( 'Calendar'[Day] ),",
              "    IF(DateCnt =1, ",
              "    CONCATENATEX ( FILTERS ( 'Calendar'[Day]), 'Calendar'[Day], \", \"), \"Multiple days\"),",
              "    \"All Days\"",
              ")",
              "return",
              "\"Selected period: \"&Year1&\", \"&Month1&\", \"&DateRange "
            ],
            "lineageTag": "e91ba393-caaa-4eff-84e3-ce743d3c8be5"
          },
          {
            "name": "Delta 1_Net Invoice Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[1_Net Invoice Sales] - [1_Net Invoice Sales PY]",
            "lineageTag": "50eb5a4a-dcd2-41a2-af0b-b9d9206cf27a"
          },
          {
            "name": "Delta 2_Net Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[2_Net Revenue] - [2_Net Revenue PY]",
            "lineageTag": "ce67dda2-d21a-4c6b-a126-ee2193e5c00d"
          },
          {
            "name": "Delta 1a_Rebate Accruals",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[1a_Rebate Accruals] - [1a_Rebate Accruals PY]",
            "lineageTag": "e31ecdb2-3c1f-4530-bb6f-e2f4eb4fee20"
          },
          {
            "name": "Delta 2a_Fin Accr & Rebates",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[2a_Fin Accr & Rebates] - [2a_Fin Accr & Rebates PY]",
            "lineageTag": "efcb1049-aad3-42db-a3fb-c7093943b50b"
          },
          {
            "name": "Delta 3_Reported Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[3_Reported Revenue] - [3_Reported Revenue PY]",
            "lineageTag": "820005fd-2df2-4140-ae0b-3739ef8df7e8"
          },
          {
            "name": "Delta 3a_COGS Standard",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[3a_COGS Standard] - [3a_COGS Standard PY]",
            "lineageTag": "00385fa3-e1d5-450f-8d33-82e8c2dc5e7b"
          },
          {
            "name": "Delta 3b_Cogs Actual",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[3b_COGS Actual] -[3b_COGS Actual PY]",
            "lineageTag": "468211c6-1717-4c92-9da4-416a6f142701"
          },
          {
            "name": "Delta 5_Standard Finance Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[5_Standard Finance Margin] -[5_Standard Finance Margin PY]",
            "lineageTag": "c52d6ac9-8226-4058-a9db-927847aaa44f"
          },
          {
            "name": "Delta 6_Actual Finance Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[6_Actual Finance Margin] -[6_Actual Finance Margin PY]",
            "lineageTag": "a9d45f07-a5df-4fec-a756-3ff38f4cc4d6"
          },
          {
            "name": "Delta 7_Gross Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[7_Gross Margin] -[7_Gross Margin PY]",
            "lineageTag": "224623a7-99be-447d-b637-c2e1e650e953"
          },
          {
            "name": "MsgCurrentRegion",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "var RegionCount = CALCULATE(DISTINCTCOUNT(CompanyCode[RegionID]))",
              "return",
              "IF(RegionCount<1,\"\",if(RegionCount=1, \"Region: \"&SELECTEDVALUE(CompanyCode[Region]), \"Multiple regions\"))"
            ],
            "lineageTag": "3bcd2d41-b518-45f3-8348-b937b57c907d"
          },
          {
            "name": "Notification_KPI_name_dynamic_left",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF(",
              "   [SelectedValue_KPI] = \"Predefined KPI is chosen\", \"3_Reported_Revenue\", \"Sales\"",
              ")"
            ],
            "lineageTag": "d57b8ad4-1013-4c31-8e55-518133f32fc0"
          },
          {
            "name": "KPI left",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "KPI dynamic",
            "expression": [
              "",
              "IF([SelectedValue_KPI] = \"Predefined KPI is chosen\", [3_Reported Revenue], [Sales])"
            ],
            "isHidden": true,
            "lineageTag": "189ce3c9-49cc-473e-a5dd-9d040abab634"
          },
          {
            "name": "Delta 3_Reported Revenue%",
            "displayFolder": "!Predefined KPIs",
            "expression": "IF([3_Reported Revenue PY] <> BLANK(), DIVIDE([3_Reported Revenue] - [3_Reported Revenue PY], [3_Reported Revenue PY]), BLANK())",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ec9f21ce-be55-44e6-8e62-b4fda789e880"
          },
          {
            "name": "7_Gross Margin %",
            "displayFolder": "!Predefined KPIs",
            "expression": "DIVIDE([7_Gross Margin], [3_Reported Revenue], 0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "139a4387-44c0-496d-ac4c-f607529f3534"
          },
          {
            "name": "7_Grosss Margin % PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "round(CALCULATE([7_Gross Margin %], DATEADD('Calendar'[Date], -1, year)),1)",
            "lineageTag": "466f93a2-8509-4abd-8f2b-1a0afa78280a"
          },
          {
            "name": "Delta 7_Gross Margin %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[7_Gross Margin %] - [7_Grosss Margin % PY]",
            "lineageTag": "87b7ac9a-3492-4070-8021-50b830132071"
          },
          {
            "name": "DeltaGrossMargin_col",
            "displayFolder": "EPM Deltas",
            "expression": "IF([Delta 7_Gross Margin %]<0,0,1) ",
            "formatString": "0",
            "lineageTag": "df8ab6ac-b406-459a-8181-428ade52eed7"
          },
          {
            "name": "Delta 7_Gross Margin %%",
            "displayFolder": "!Predefined KPIs",
            "expression": "DIVIDE(IF([7_Grosss Margin % PY]<>BLANK(), [7_Gross Margin %] - [7_Grosss Margin % PY], BLANK()), [7_Grosss Margin % PY], BLANK())",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "edfd8421-9eb9-4201-b41d-c62459b0a9b6"
          },
          {
            "name": "7_Grosss Margin %% PY",
            "displayFolder": "!Predefined KPIs",
            "expression": "CALCULATE([7_Gross Margin %], DATEADD('Calendar'[Date], -1, year))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3e83a07c-b11e-4348-a56b-bb1cd4369c5a"
          },
          {
            "name": "6_Actual Finance Margin % PY",
            "displayFolder": "!Predefined KPIs",
            "expression": "CALCULATE([6_Actual Finance Margin %], DATEADD('Calendar'[Date], -1, year))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7c6ed9de-04cd-4c3e-bcbc-9e4c46c3d7b7"
          },
          {
            "name": "6_Actual Finance Margin %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "[6_Actual Finance Margin] / [3_Reported Revenue]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "18fe9af3-152c-4d46-9399-1953550c3db0"
          },
          {
            "name": "KPI left delta %",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "KPI dynamic",
            "expression": [
              "",
              "  IF([SelectedValue_KPI] = \"Predefined KPI is chosen\", [Delta 3_Reported Revenue%], [DeltaNetAmount%])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "lineageTag": "961369b9-53a3-4098-b0ab-fb68f85886b0"
          },
          {
            "name": "KPI left PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "KPI dynamic",
            "expression": [
              "",
              "IF( [SelectedValue_KPI] = \"Predefined KPI is chosen\", [3_Reported Revenue PY], [Sales PY])"
            ],
            "isHidden": true,
            "lineageTag": "6637a45b-0a73-4c1f-829b-8bb8402fed45"
          },
          {
            "name": "Notification_TP Adj",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF(",
              "   SELECTEDVALUE(srv_MeasureTypes[Type])=BLANK(),\"TP adjustments are excluded\",",
              "   IF(SELECTEDVALUE(srv_MeasureTypes[Type])=\"Predefined\",\"TP adjustments are excluded\",",
              "   IF(SELECTEDVALUE(fact_ACDOCA_EPMSalesView[TPAdjustment]) =1, \"TP adjustments are included\", ",
              "   IF(DISTINCTCOUNT(fact_ACDOCA_EPMSalesView[TPAdjustment]) <>1,\"TP adjustments are included\", IF(SELECTEDVALUE(fact_ACDOCA_EPMSalesView[TPAdjustment]) =0,\"TP adjustments are excluded\",\"\"",
              ")))))"
            ],
            "lineageTag": "88a7a70c-dabe-4b38-931a-06f2ed7a6d61"
          },
          {
            "name": "Sales Variance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "SAP & Variance",
            "expression": "[Sales] -  [SAP Sales]",
            "lineageTag": "a593132f-2a97-4179-93dc-7c26ce9cc964"
          },
          {
            "name": "SAP COGS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "SAP & Variance",
            "expression": [
              "",
              "CALCULATE(SUM(fact_ACDOCA_FinStatemntSalesMargin[SAP_COGS]), USERELATIONSHIP(fact_ACDOCA_FinStatemntSalesMargin[FiscalYearPeriod], 'Calendar'[YearMonthPeriod]))*-1"
            ],
            "lineageTag": "0dbc02ab-90f7-4c9f-bccd-911130ff6ea0"
          },
          {
            "name": "SAP Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "SAP & Variance",
            "expression": [
              "",
              "CALCULATE(SUM(fact_ACDOCA_FinStatemntSalesMargin[SAP_Sales]), USERELATIONSHIP(fact_ACDOCA_FinStatemntSalesMargin[FiscalYearPeriod], 'Calendar'[YearMonthPeriod])) *-1"
            ],
            "lineageTag": "e939bafe-c09c-4219-9b96-b3d7c7ffe56a"
          },
          {
            "name": "SAP Sales Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "SAP & Variance",
            "expression": [
              "",
              "CALCULATE(SUM(fact_ACDOCA_FinStatemntSalesMargin[SAP_SalesMargin]), USERELATIONSHIP(fact_ACDOCA_FinStatemntSalesMargin[FiscalYearPeriod], 'Calendar'[YearMonthPeriod])) *-1"
            ],
            "lineageTag": "23ae3acd-8cea-4511-9716-4c06072de1ff"
          },
          {
            "name": "COGS Variance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "SAP & Variance",
            "expression": "[Cogs a/c] - [SAP COGS]",
            "lineageTag": "108b11b9-9a54-40a9-9865-39a068be9a92"
          },
          {
            "name": "Sales Margin Variance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "SAP & Variance",
            "expression": "[SalesMargin] - [SAP Sales Margin]",
            "lineageTag": "6a7e041f-91d0-40f2-a309-1d416d45d8df"
          },
          {
            "name": "BLANK measure",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "BLANK()",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ed615970-26bb-4e35-9a0b-eaef2bc16e6a"
          },
          {
            "name": "Budget",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Budget",
            "expression": "CALCULATE(SUM(fact_Budget_EPM[3_ReportedRevenue]), USERELATIONSHIP('Calendar'[YearMonthPeriod], Calendar_cut[YearMonth]))*1000",
            "lineageTag": "d755bea0-64da-4597-ad55-9249627ea619"
          },
          {
            "name": "% Reported Revenue",
            "displayFolder": "Budget",
            "expression": "DIVIDE([3_Reported Revenue], [Budget],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "13ce01ae-0c95-424f-978b-936edd178647"
          },
          {
            "name": "% of Sales",
            "displayFolder": "EPM Sales and Margins",
            "expression": [
              "",
              "VAR Sales_ = CALCULATE([Sales], ALL(fact_ACDOCA_EPMSalesView))",
              "RETURN",
              "DIVIDE([GrossMargin], Sales_,BLANK())",
              ""
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "25312f31-101a-4613-8e99-39043b308c6f"
          },
          {
            "name": "SelectedValue_GMElement1",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( exQL_Map[GM element L1]),",
              "    CONCATENATEX ( FILTERS ( exQL_Map[GM element L1]), exQL_Map[GM element L1], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "289282cb-062d-484e-9bac-47d58397fcab"
          },
          {
            "name": "SelectedValue_GMElement2",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( exQL_Map[GM element L2]),",
              "    CONCATENATEX ( FILTERS ( exQL_Map[GM element L2]), exQL_Map[GM element L2], \", \" ),",
              "    \"ALL\"",
              ")"
            ],
            "lineageTag": "e6a3670f-9231-49cf-bc41-da00ccd999cd"
          },
          {
            "name": "% of Total Sales KPI",
            "expression": [
              "",
              "(DIVIDE([GrossMargin],[Total Sales], BLANK()))"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2493c3bd-11f4-416f-9614-86290358ca65"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "EPM Sales and Margins",
            "expression": "CALCULATE(SUM(fact_ACDOCA_EPMSalesView[Quantity]))",
            "lineageTag": "fc3ddac0-7e28-4985-b029-345db5547bf1"
          },
          {
            "name": "Reconciliation File Title",
            "displayFolder": "Titles",
            "expression": "CONCATENATE(CONCATENATE(\"Gross Margin (\",CONCATENATE(FORMAT(CALCULATE(MAX(Reconciliation_File[YTD])),\"YYYY\"),CONCATENATE(\" \",FORMAT(CALCULATE(MAX(Reconciliation_File[YTD])),\"MMMM\")))),\" YTD) Reconciliation to ExQL\")",
            "lineageTag": "27f1e183-9eea-4b4d-a777-92140476416a"
          },
          {
            "name": "7_GrossMargin YTD in mm",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "CALCULATE([7_Gross Margin Currency USD],DATESYTD(fact_ACDOCA_EPMSalesView[PostingDate]),FILTER(fact_ACDOCA_EPMSalesView,fact_ACDOCA_EPMSalesView[PostingDate]<=MAX(Reconciliation_File[YTD])))/1000000",
            "lineageTag": "18687bae-a825-449e-a216-727f6be2a386"
          },
          {
            "name": "Delta 7_GrossMargin Reconciliation",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "CALCULATE(SUM(Reconciliation_File[ExQL values IN $mm]))-CALCULATE([7_GrossMargin YTD in mm])",
            "lineageTag": "17ce45e4-3edd-4f22-8afe-0142df04ea69"
          },
          {
            "name": "Notification_Freight_Outbound",
            "displayFolder": "Notifications",
            "expression": [
              "",
              "IF(",
              "   AND(SELECTEDVALUE(srv_MeasureTypes[Choose KPI])=\"6_Actual Finance Margin\",SELECTEDVALUE(srv_Actual_Finance[Value]) =\"Include\"), \" | Freight Outbound included\",",
              "   IF(AND(SELECTEDVALUE(srv_MeasureTypes[Choose KPI])=\"6_Actual Finance Margin\",SELECTEDVALUE(srv_Actual_Finance[Value]) =\"Exclude\"),  \" | Freight Outbound excluded\",\"\"))"
            ],
            "lineageTag": "8304ee18-623f-4cb8-a81c-e8400694fc28"
          },
          {
            "name": "Budget PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Budget",
            "expression": "CALCULATE([Budget], DATEADD('Calendar'[Date], -1, year))",
            "lineageTag": "46501e93-06c3-4242-85e2-d78289067024"
          },
          {
            "name": "7_Gross Margin Local Currency",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([GrossMargin], ",
              "            fact_ACDOCA_EPMSalesView[TPAdjustment] = 0, ",
              "            fact_ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "            ALL(GLAccount[GLAccountID]), ",
              "            ALL(fact_ACDOCA_EPMSalesView[Source]), ",
              "            ALL(fact_ACDOCA_EPMSalesView[Subsource]),",
              "            FILTER(fact_ACDOCA_EPMSalesView, CONCATENATE(fact_ACDOCA_EPMSalesView[CompanyCodeID],fact_ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              "            ,FILTER(fact_ACDOCA_EPMSalesView,fact_ACDOCA_EPMSalesView[CurrencyType]=\"Local Currency\")",
              "        )"
            ],
            "lineageTag": "d858fb56-8141-4855-ad53-e977acaf0620"
          },
          {
            "name": "7_GrossMargin YTD in mm Local Currency",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "CALCULATE([7_Gross Margin Local Currency],DATESYTD(fact_ACDOCA_EPMSalesView[PostingDate]),FILTER(fact_ACDOCA_EPMSalesView,fact_ACDOCA_EPMSalesView[PostingDate]<=MAX(Reconciliation_File[YTD])))/1000000",
            "lineageTag": "e956cf14-f00f-42c2-8bc9-ddb40c32c938"
          },
          {
            "name": "Delta 7_GrossMargin Reconciliation Local Currency",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": "CALCULATE(SUM(Reconciliation_File[ExQL values in Loc cur mm]))-CALCULATE([7_GrossMargin YTD in mm Local Currency],DATESYTD('Calendar'[Date]))",
            "lineageTag": "ec4be038-b2db-4eb1-a529-8a69ae99b7cb"
          },
          {
            "name": "Delta7_Reconciliation Color",
            "displayFolder": "!Predefined KPIs",
            "expression": "IF(and([Delta 7_GrossMargin Reconciliation]<0.01,[Delta 7_GrossMargin Reconciliation]>-0.01),0,IF(and([Delta 7_GrossMargin Reconciliation]<0.05,[Delta 7_GrossMargin Reconciliation]>-0.05),1,2))",
            "formatString": "0",
            "lineageTag": "793ada2d-8bcb-4de8-b84a-941f803a2a00"
          },
          {
            "name": "Delta7_Reconciliation Color Local Currency",
            "displayFolder": "!Predefined KPIs",
            "expression": "IF(and([Delta 7_GrossMargin Reconciliation Local Currency]<0.01,[Delta 7_GrossMargin Reconciliation Local Currency]>-0.01),0,IF(and([Delta 7_GrossMargin Reconciliation Local Currency]<0.05,[Delta 7_GrossMargin Reconciliation Local Currency]>-0.05),1,2))",
            "formatString": "0",
            "lineageTag": "e7582587-8a78-4537-9979-6f9ff56731dd"
          },
          {
            "name": "Budget label",
            "displayFolder": "Notifications",
            "expression": "\"Budget\"",
            "lineageTag": "7851313d-cda1-4223-8583-98f2bc3a06ef"
          },
          {
            "name": "GM label",
            "displayFolder": "Notifications",
            "expression": "\"% GM\"",
            "lineageTag": "bd6f5bff-9f2b-4844-8a68-6c4d9960ae1a"
          },
          {
            "name": "7_Gross Margin Currency USD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "!Predefined KPIs",
            "expression": [
              "",
              "CALCULATE([GrossMargin], ",
              "            fact_ACDOCA_EPMSalesView[TPAdjustment] = 0, ",
              "            fact_ACDOCA_EPMSalesView[SourceLedgerID] IN { \"0L\", \"OC\" },",
              "            ALL(GLAccount[GLAccountID]), ",
              "            ALL(fact_ACDOCA_EPMSalesView[Source]), ",
              "            ALL(fact_ACDOCA_EPMSalesView[Subsource]),",
              "            FILTER(fact_ACDOCA_EPMSalesView, CONCATENATE(fact_ACDOCA_EPMSalesView[CompanyCodeID],fact_ACDOCA_EPMSalesView[SourceLedgerID]) <> \"CH35OC\")",
              "            ,FILTER(fact_ACDOCA_EPMSalesView,fact_ACDOCA_EPMSalesView[CurrencyType]=\"Group Currency USD\")",
              "        )"
            ],
            "lineageTag": "9cae0a5b-7595-45df-8972-e78148e678e5"
          },
          {
            "name": "Quantity_Sales",
            "displayFolder": "EPM Sales and Margins",
            "expression": "CALCULATE(ABS(SUM(fact_ACDOCA_EPMSalesView[Quantity])),RIGHT(LEFT(GLAccount[GLAccountID],3),1)=4)",
            "formatString": "0",
            "lineageTag": "8b99734c-5958-4b5e-a89b-d7278b74357a"
          },
          {
            "name": "Quantity_COGS",
            "displayFolder": "EPM Cogs",
            "expression": "CALCULATE(ABS(SUM(fact_ACDOCA_EPMSalesView[Quantity])),RIGHT(LEFT(GLAccount[GLAccountID],3),1)=5)",
            "formatString": "0",
            "lineageTag": "d041cf5d-cd3d-456a-b256-75e185088e3d"
          }
        ],
        "partitions": [
          {
            "name": "_Measures-a5b9e016-864d-4b35-a6ae-b7bb615c2ef1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Measures = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Measures\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "srv_MeasureTypes",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Choose KPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2f0174e0-8f35-4d5e-8fdc-b9a75f7762e2",
            "sortByColumn": "Sort",
            "sourceColumn": "Choose KPI",
            "summarizeBy": "none"
          },
          {
            "name": "MeasureDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "bff0290b-5a3d-4822-850f-73c5da5d8bff",
            "sourceColumn": "MeasureDescription",
            "summarizeBy": "none"
          },
          {
            "name": "KPI Name PY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8a60f691-dff1-4147-b22d-e4304a02891c",
            "sourceColumn": "KPI Name PY",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ab07d1e6-7753-4437-a8a7-e95cdf04e794",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b730b00f-eb26-45d5-a215-0a20a4056dba",
            "sourceColumn": "Sort",
            "summarizeBy": "sum"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1744b8c-d1eb-436f-8580-a8fa8c1192c1",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "07abc236-5ff9-4eac-8734-3194df3cb2ff",
        "partitions": [
          {
            "name": "srv_MeasureTypes-0e808762-32ef-4eea-85a7-87e9f1d60fd7",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"jZRBb4IwFMe/SkPizQOgoh4NycwOzkVOi5qmQt1ITDGlmu22+77lPslaXkFoK+4A5b3+3++9V9put15CTrT0ht0Rvb7Jz0A+C0ZOX2Veevvh1ovXywRJZ2cEbWhqgbMi/D1nDdZpAmBkAtbig3IUF4mccH5D3NiMW/KilA3w4pgLOddjAmBiJT7TT5XnNoAwcmdqeuoxATDtWyM0MJfFdgBmZmJ0N62whx4gzU3SKq7Eq7h61bLAN3UBfqECPbNrkacU1Vun5cvA+fv9o+Jttd40QVUZzegxZzQDNMEbeiCCokWa8gs5KbLtsWUaGdrIsMq/oVfKLlTXycGCAjsCzRk5OAQ/ycVTCdHu4vthhKAGVZCcISxtlWMp7ofrlGM75Uh2eS64kAt6q990ySZ2asfZYg2eOMAEV6c3EYRlhGf1aW7ZpkTDIgfsAMpFKmTrNaqxutMaM7UxE9ykqlfzdmG4Z+D/9QWGMztRhHUpltrphyR3gnQ7czvLFPfcCMDsSvRF6DtQg65QHdJ/+TTSPGf7Pw==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Choose KPI\" = _t, MeasureDescription = _t, #\"KPI Name PY\" = _t, Sort = _t, Type = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Choose KPI\", type text}, {\"MeasureDescription\", type text}, {\"KPI Name PY\", type text}}),",
                "    #\"Inserted Merged Column\" = Table.AddColumn(#\"Changed Type\", \"Title\", each Text.Combine({[Choose KPI], \" Analysis\"}), type text)",
                "in",
                "    #\"Inserted Merged Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SalesOrganization",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesOrganizationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5162b249-813f-4fdc-bd79-b2abc5af0df0",
            "sourceColumn": "SalesOrganizationID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "744e8009-1179-4fdf-ba8f-8fe06b2c6419",
            "sourceColumn": "SalesOrganization",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganizationCurrency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "27e5c768-0785-44f3-b51a-601a3bdf1408",
            "sourceColumn": "SalesOrganizationCurrency",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14861842-0fe8-4a98-b5d0-c71cd5ffd488",
            "sourceColumn": "CompanyCode",
            "summarizeBy": "none"
          },
          {
            "name": "CountryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f68ba1c-211d-43ef-99d5-90c215f93ad2",
            "sourceColumn": "CountryID",
            "summarizeBy": "none"
          },
          {
            "name": "CountryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa37d5d7-4915-43fc-97e2-6df49bf530a6",
            "sourceColumn": "CountryName",
            "summarizeBy": "none"
          },
          {
            "name": "RegionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e41da18-6629-4381-95d2-5a06bff12ffd",
            "sourceColumn": "RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "RegionName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5cf6b90-ad9c-4632-94fc-43e117a6fb52",
            "sourceColumn": "RegionName",
            "summarizeBy": "none"
          },
          {
            "name": "Access_Control_Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0efc68c0-bdb5-42a9-8b1d-af5e2eb24403",
            "sourceColumn": "Access_Control_Unit",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7b471447-fac8-43c4-9fab-2fe38939ab28",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "f3af1450-fb40-4fee-ae9e-99cde39a7d50",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3d06306b-7d70-4f5d-b569-2215846a10d4",
        "partitions": [
          {
            "name": "SalesOrganization-d124955c-435d-4d5c-93b9-6ca29ec16469",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&Source&\"\", \"\"&DB&\"\"),",
                "    dm_sales_vw_dim_SalesOrganization = Source{[Schema=\"dm_finance\",Item=\"vw_dim_SalesOrganization\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_SalesOrganization"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SalesDistrict",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesDistrictID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf0d9839-32d7-485c-af0e-295cc2f34f84",
            "sourceColumn": "SalesDistrictID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesDistrict",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1db4ba99-f7d6-4d7e-9aaf-6049f5e209a6",
            "sourceColumn": "SalesDistrict",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "72f73e55-b438-44fa-8f4e-45eba3dad9c5",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4489824b-f974-4f44-9470-b656ba969aa3",
        "partitions": [
          {
            "name": "SalesDistrict-accbddad-f4df-4806-aadf-629cabaadeea",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&#\"Source\"&\"\", \"\"&#\"DB\"&\"\"),",
                "    dm_sales_vw_dim_SalesOrganization = Source{[Schema=\"dm_finance\",Item=\"vw_dim_SalesDistrict\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_SalesOrganization"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "GLAccount",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ChartOfAccounts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d28f36c4-56b6-413d-b9c3-7bce99b9ac56",
            "sourceColumn": "ChartOfAccounts",
            "summarizeBy": "none"
          },
          {
            "name": "GLAccountID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98e8e10a-01b7-45c6-b43c-b2285865e9f8",
            "sourceColumn": "GLAccountID",
            "summarizeBy": "none"
          },
          {
            "name": "GLAccount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "edcca78d-3bc6-4327-9180-f0b4b06f133e",
            "sourceColumn": "GLAccount",
            "summarizeBy": "none"
          },
          {
            "name": "GLAccountLongName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "546827fd-e90f-42ae-a9ed-02d79cf3d26b",
            "sourceColumn": "GLAccountLongName",
            "summarizeBy": "none"
          },
          {
            "name": "LastChangeDateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fccbe0b3-0cdc-4270-ae0f-9562303debd5",
            "sourceColumn": "LastChangeDateTime",
            "summarizeBy": "sum"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5eb60fba-138d-437c-ab75-731ff21f252c",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "420a9b21-fdcb-4980-ac37-e1a32999bec0",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "glaccountID_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(GLAccount[GLAccountID],\" \"), GLAccount[GLAccount])",
            "isDataTypeInferred": true,
            "lineageTag": "6b492aff-e6a7-4c2e-82af-516bf5a59185",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "75e48071-f068-4c8e-bf56-80cb381a6292",
        "partitions": [
          {
            "name": "GLAccount-96da0f41-2748-4540-b91e-901a95e1382a",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&#\"Source\"&\"\", \"\"&#\"DB\"&\"\"),",
                "    dm_sales_vw_fact_BillingDocumentItem = Source{[Schema=\"dm_sales\",Item=\"vw_dim_GLAccountText\"]}[Data]",
                "in",
                "    dm_sales_vw_fact_BillingDocumentItem"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "srv_Cogs_cost",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Choose KPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "44d13032-8b4a-4d56-b50c-0eefd79ec123",
            "sourceColumn": "Choose KPI",
            "summarizeBy": "none"
          },
          {
            "name": "MeasureDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4a415914-fcd8-4024-8c13-6a44887339f9",
            "sourceColumn": "MeasureDescription",
            "summarizeBy": "none"
          },
          {
            "name": "KPI Name PY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "950f790d-0755-4d2d-8165-545ab52d880d",
            "sourceColumn": "KPI Name PY",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c864552b-6bb1-4faa-8822-4f15984fe576",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d53be231-4048-45d8-ac45-f6105d75996c",
            "sourceColumn": "Short",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b24b47e3-3bf5-4ed2-9441-be44ace69e7d",
        "partitions": [
          {
            "name": "srv_Cogs_cost-a65e4cf1-3658-4876-917e-845dac7bd2ee",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcixRSEwuKU3MUUjOLy5R0lFy9ncPVoDRCgGRQKajc4hSrA5YbXFJYl5KYlEKiupEIsUhpgWHuCjFxgIA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Choose KPI\" = _t, MeasureDescription = _t, #\"KPI Name PY\" = _t, Short = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Choose KPI\", type text}, {\"MeasureDescription\", type text}, {\"KPI Name PY\", type text}}),",
                "    #\"Inserted Merged Column\" = Table.AddColumn(#\"Changed Type\", \"Title\", each Text.Combine({[Choose KPI], \" Analysis\"}), type text)",
                "in",
                "    #\"Inserted Merged Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "RLS_GROUPS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "GROUP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c3b67332-8798-4210-893c-454e55adabb2",
            "sourceColumn": "GROUP",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganizationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ffffb9de-4e32-4054-8813-6ff01c159303",
            "sourceColumn": "SalesOrganizationID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrg",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4d32d87a-f9fe-4aa4-9dce-d0e83ec591b9",
            "sourceColumn": "SalesOrg",
            "summarizeBy": "none"
          },
          {
            "name": "ompanyCodeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c32651eb-5493-4abd-9953-7f29eb86bb01",
            "sourceColumn": "ompanyCodeID",
            "summarizeBy": "none"
          },
          {
            "name": "PlantID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ae18a0b4-09c8-4211-8371-36d0addd52bc",
            "sourceColumn": "PlantID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8a8f2bb8-80f6-478b-b9d2-6ad6504aef1f",
        "partitions": [
          {
            "name": "RLS_GROUPS-4ff76762-72b3-46ca-b344-e72487125e2e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://crhemea.sharepoint.com/sites/crh-group-cs-dataandanalyti-0010_DevOps/Shared%20Documents/0010_DevOps/RLS/RLS_assignmnts.xlsx\"), null, true),",
                "    RLS_GROUPS_Sheet = Source{[Item=\"RLS_GROUPS\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(RLS_GROUPS_Sheet, [PromoteAllScalars=true])",
                "in",
                "    #\"Promoted Headers\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "RLS_USERS",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "USER",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5462ac1d-542f-4ecb-b61e-3a9e3f5a3f01",
            "sourceColumn": "USER",
            "summarizeBy": "none"
          },
          {
            "name": "GROUP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f97edc9f-3aaf-4061-b3e6-be8027e8b49a",
            "sourceColumn": "GROUP",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ca4af54c-bd2a-4c46-9223-e3cb0b74043f",
        "partitions": [
          {
            "name": "RLS_USERS-473c886b-f8ad-4c1b-9074-04db5254a830",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://crhemea.sharepoint.com/sites/crh-group-cs-dataandanalyti-0010_DevOps/Shared%20Documents/0010_DevOps/RLS/RLS_assignmnts.xlsx\"), null, true),",
                "    RLS_USERS_Sheet = Source{[Item=\"RLS_USERS\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(RLS_USERS_Sheet, [PromoteAllScalars=true])",
                "in",
                "    #\"Promoted Headers\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ExQLReportingEntity",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ExQLReportingEntity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b48df20d-6e89-4e0a-86c5-829ac148ed60",
            "sourceColumn": "ExQLReportingEntity",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a070344f-2eb0-4c2b-b33b-8fece1073b1c",
        "partitions": [
          {
            "name": "ExQLReportingEntity-d1f422c2-c34c-4fcc-9f28-454155805f23",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_finance_vw_dim_ExQLReportingEntity = Source{[Schema=\"dm_finance\",Item=\"vw_dim_ExQLReportingEntity\"]}[Data]",
                "in",
                "    dm_finance_vw_dim_ExQLReportingEntity"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "exQL_Map",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "nk_ExQLmap",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0949bb73-0e0a-46b8-a8cb-6ff308516fe3",
            "sourceColumn": "nk_ExQLmap",
            "summarizeBy": "none"
          },
          {
            "name": "GLAccountID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "21cbef86-42fe-452f-8226-451bc8ea789d",
            "sourceColumn": "GLAccountID",
            "summarizeBy": "none"
          },
          {
            "name": "FunctionalAreaID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e02e7df3-1b06-41b6-83ad-c95be9eb4f77",
            "sourceColumn": "FunctionalAreaID",
            "summarizeBy": "none"
          },
          {
            "name": "ExQLNode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf97664a-8c7f-4aad-b1d3-6c3e69e68501",
            "sourceColumn": "ExQLNode",
            "summarizeBy": "none"
          },
          {
            "name": "ExQLAccount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9a38ebc-65b9-4efa-9ebd-51cfb4595ed7",
            "sourceColumn": "ExQLAccount",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2f91346d-b803-4547-a33d-0f6e3e161ede",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_jobDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "f8e8887b-7029-422e-ba3d-c58f18a31c93",
            "sourceColumn": "t_jobDtm",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "lineageTag": "e2d34500-b387-47ad-b431-d9e4cc97a828",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "GM element L1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "960ad733-9539-42e7-96fd-7964e062b694",
            "sortByColumn": "GM Element Sort.Sort",
            "sourceColumn": "GM element L1",
            "summarizeBy": "none"
          },
          {
            "name": "GM element L2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6fbba11-aca5-4394-9e61-f3b80167684f",
            "sourceColumn": "GM element L2",
            "summarizeBy": "none"
          },
          {
            "name": "GM Element Sort.Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f904b1cc-60cf-45b5-be39-9f3dedb9482e",
            "sourceColumn": "GM Element Sort.Sort",
            "summarizeBy": "none"
          },
          {
            "name": "GM Element Sort.KPI name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "931411d2-ec20-482f-a9f6-fc60f0978d50",
            "sourceColumn": "GM Element Sort.KPI name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4c50a867-1bae-493c-a484-b80a1880b9e8",
        "partitions": [
          {
            "name": "exQL_Map-4e04c11e-045f-48d8-8b84-079c9df54404",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"\"&#\"Source\"&\"\", \"\"&#\"DB\"&\"\"),",
                "    dm_sales_vw_fact_BillingDocumentItem = Source{[Schema=\"dm_finance\",Item=\"vw_dim_ZE_EXQLMAP_DT\"]}[Data],",
                "    #\"Renamed Columns\" = Table.RenameColumns(dm_sales_vw_fact_BillingDocumentItem,{{\"Contingency6\", \"GM element L1\"}, {\"Contingency7\", \"GM element L2\"}}),",
                "    #\"Merged Queries\" = Table.FuzzyNestedJoin(#\"Renamed Columns\", {\"GM element L1\"}, #\"GM Element Sort\", {\"KPI name\"}, \"GM Element Sort\", JoinKind.LeftOuter, [IgnoreCase=true, IgnoreSpace=true]),",
                "    #\"Expanded GM Element Sort\" = Table.ExpandTableColumn(#\"Merged Queries\", \"GM Element Sort\", {\"Sort\", \"KPI name\"}, {\"GM Element Sort.Sort\", \"GM Element Sort.KPI name\"})",
                "in",
                "    #\"Expanded GM Element Sort\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CompanyCode",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CompanyCodeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77083303-be8d-4fde-b680-03e8e23dfbfb",
            "sourceColumn": "CompanyCodeID",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1f65fd7-f147-4b34-b813-a008589fce4d",
            "sourceColumn": "CompanyCode",
            "summarizeBy": "none"
          },
          {
            "name": "CityName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf7331b4-4bc9-465c-bf7d-07b3c2a88f85",
            "sourceColumn": "CityName",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a081be6b-f985-42fa-a23f-40556723a99d",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "CountryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70b94138-71a9-4ccb-9271-98fed4b62738",
            "sourceColumn": "CountryName",
            "summarizeBy": "none"
          },
          {
            "name": "Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "226dab70-e98b-4036-98a3-993097a8ecfd",
            "sourceColumn": "Currency",
            "summarizeBy": "none"
          },
          {
            "name": "ChartOfAccounts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee773557-3042-47ea-a3cb-a2007eee1431",
            "sourceColumn": "ChartOfAccounts",
            "summarizeBy": "none"
          },
          {
            "name": "Company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfbfd9fe-51e7-42c0-8cbf-493a34709aa9",
            "sourceColumn": "Company",
            "summarizeBy": "none"
          },
          {
            "name": "CashDiscountBaseAmtIsNetAmt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5258920a-88f4-4482-a2b3-9da5533c05c9",
            "sourceColumn": "CashDiscountBaseAmtIsNetAmt",
            "summarizeBy": "none"
          },
          {
            "name": "RegionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b428450c-810d-4559-b9e3-b2e28351bcde",
            "sourceColumn": "RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92a55a1e-1426-4175-a580-a9af08471764",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "t_jobDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d75d80c1-e25f-42a4-af0e-f5d135f9c5f8",
            "sourceColumn": "t_jobDtm",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyCodeDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91b20331-323d-496f-a72e-fa31483e2333",
            "sourceColumn": "CompanyCodeDescription",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a74996f9-43ea-4cff-bdb3-e0620eb83507",
        "partitions": [
          {
            "name": "CompanyCode-b6039867-5db3-4b82-942b-d04d0c6d6d22",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_dim_CompanyCode = Source{[Schema=\"dm_sales\",Item=\"vw_dim_CompanyCode\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_CompanyCode"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_ACDOCA_FinStatemntSalesMargin",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CompanyCodeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0a512d5-0636-4e7e-9061-2ae7793eee69",
            "sourceColumn": "CompanyCodeID",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenterID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e51ca4ec-cae9-4b00-95ef-4cd32bb96f00",
            "sourceColumn": "ProfitCenterID",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f89a9237-84d0-4442-bf12-4aa30b74d11d",
            "sourceColumn": "ProfitCenter",
            "summarizeBy": "none"
          },
          {
            "name": "GLAccountID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35124849-19d5-4421-863d-4c2c27433437",
            "sourceColumn": "GLAccountID",
            "summarizeBy": "none"
          },
          {
            "name": "FunctionalAreaID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "786a3d54-fd68-4c4a-b6b7-f3b4aefac487",
            "sourceColumn": "FunctionalAreaID",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73742ad3-6dc7-4377-b506-3525fa47906a",
            "sourceColumn": "CurrencyID",
            "summarizeBy": "none"
          },
          {
            "name": "SAP_Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fb39f4ca-d030-45d2-b12b-fb7b4d58c51f",
            "sourceColumn": "SAP_Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "SAP_COGS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "082792fa-9917-4ee6-b001-44cc7565cf9f",
            "sourceColumn": "SAP_COGS",
            "summarizeBy": "sum"
          },
          {
            "name": "SAP_SalesMargin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "17da4a50-2d6f-4181-8be2-87fa10eeb891",
            "sourceColumn": "SAP_SalesMargin",
            "summarizeBy": "sum"
          },
          {
            "name": "FiscalYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8aca2795-d224-4742-8f80-99e5f550fce0",
            "sourceColumn": "FiscalYear",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYearPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5f18640-92d7-4a10-b030-ef0b1097fec0",
            "sourceColumn": "FiscalYearPeriod",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4dcdbaca-6646-40c6-8643-dfbdfe7ea3c4",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "59f383c8-3dc7-4f54-9573-3b8ddd563930",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyCodeProfitCenterID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9aa9572e-01eb-4663-aba0-5d0d451cca77",
            "sourceColumn": "CompanyCodeProfitCenterID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "65f9552c-8e52-4643-a8e4-7aa6ae685136",
        "partitions": [
          {
            "name": "fact_ACDOCA_FinStatemntSalesMargin",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_finance_vw_fact_ACDOCA_FinStatemntSalesMargin = Source{[Schema=\"dm_finance\",Item=\"vw_fact_ACDOCA_FinStatemntSalesMargin\"]}[Data]",
                "in",
                "    dm_finance_vw_fact_ACDOCA_FinStatemntSalesMargin"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendar_cut",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed758ab1-32d1-4516-aad6-f5f6388e584b",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "493f48ef-e28e-45eb-ae10-8468d034986a",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "YearMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74d42d78-8d46-486c-9346-9c1bba6a4f35",
            "sourceColumn": "YearMonth",
            "summarizeBy": "none"
          },
          {
            "name": "FirstDayOfMonthDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "47282f34-1a89-4477-bde2-146a2d31e437",
            "sourceColumn": "FirstDayOfMonthDate",
            "summarizeBy": "none"
          },
          {
            "name": "LastDayOfTheMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "expression": "EOMONTH('Calendar_cut'[FirstDayOfMonthDate],0)",
            "formatString": "d mmmm\\, yyyy",
            "isDataTypeInferred": true,
            "lineageTag": "2582af74-eb5f-4945-9d5c-de7be960d844",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38612d3f-a511-414b-bb32-1ef5484b9179",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "YearQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf6b2cb7-e795-4088-99a3-9917c04ee421",
            "sourceColumn": "YearQuarter",
            "summarizeBy": "none"
          },
          {
            "name": "Month_Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Calendar_cut'[FirstDayOfMonthDate],\"MMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "6ef9b2cc-9746-4ec2-9239-988fe04f9974",
            "sortByColumn": "Month",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "7ca49719-8fef-486b-b088-ab4d621be6ae",
        "partitions": [
          {
            "name": "Calendar_cut",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_dim_Calendar = Source{[Schema=\"dm_sales\",Item=\"vw_dim_Calendar\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dm_sales_vw_dim_Calendar,{\"Date\", \"MonthNumber\", \"Week\", \"Day\", \"YearMonth\", \"YearWeek\", \"WeekDay\", \"FirstDayOfWeekDate\", \"CalendarDayOfYear\", \"YearDay\"}),",
                "    #\"Inserted Merged Column\" = Table.AddColumn(#\"Removed Columns\", \"YearMonth\", each Text.Combine({[Year], [Month]}, \"0\"), type text),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Inserted Merged Column\"),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Removed Duplicates\",{{\"Year\", Order.Ascending}})",
                "in",
                "    #\"Sorted Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CompanyCodeProfitCenter",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CompanyCodeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fda8b4d0-7c93-4c5e-94a1-f700bb140e40",
            "sourceColumn": "CompanyCodeID",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenterID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24f18ceb-c181-42c6-ba5a-3069a99ba796",
            "sourceColumn": "ProfitCenterID",
            "summarizeBy": "none"
          },
          {
            "name": "SKReportingEntityKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86f1986b-a3b4-4c4b-a386-1b919385a5e9",
            "sourceColumn": "SKReportingEntityKey",
            "summarizeBy": "none"
          },
          {
            "name": "ExQLReportingEntity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2b1995b-75bc-4463-8735-8cf39393622b",
            "sourceColumn": "ExQLReportingEntity",
            "summarizeBy": "none"
          },
          {
            "name": "nk_CompCodeRepEntity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CompanyCodeProfitCenter[CompanyCodeID], CompanyCodeProfitCenter[ExQLReportingEntity])",
            "isDataTypeInferred": true,
            "lineageTag": "a9cf7c3f-b6be-44ca-a324-6cf8c551a37a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "1d1b3e65-8de4-481f-960c-0a95ec39042f",
        "partitions": [
          {
            "name": "CompanyCodeProfitCenter",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_finance_vw_dim_CompanyCodeProfitCenter = Source{[Schema=\"dm_finance\",Item=\"vw_dim_CompanyCodeProfitCenter\"]}[Data]",
                "in",
                "    dm_finance_vw_dim_CompanyCodeProfitCenter"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Currency",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CurrencyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "534e708f-f1af-4342-9ee4-ed9648a1fe86",
            "sourceColumn": "CurrencyID",
            "summarizeBy": "none"
          },
          {
            "name": "Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a15ea12a-1c3c-4b09-97eb-526411d2f2d8",
            "sourceColumn": "Currency",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2cf611a7-562a-4217-a7dd-67a49abf99ea",
        "partitions": [
          {
            "name": "Currency",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_dim_Currency = Source{[Schema=\"dm_sales\",Item=\"vw_dim_Currency\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_Currency"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CurrencyType",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CurrencyTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae1277b2-fd31-407f-8f93-1ceadd96b578",
            "sourceColumn": "CurrencyTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b8f6f4c-29b9-48c0-9661-63e9c6078926",
            "sourceColumn": "CurrencyType",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ea2cbb9a-a151-4450-8526-bc5b57bf9891",
        "partitions": [
          {
            "name": "CurrencyType",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_dim_CurrencyType = Source{[Schema=\"dm_sales\",Item=\"vw_dim_CurrencyType\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_CurrencyType"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_Budget_EPM",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CompanyCodeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "043c9fd0-4ecf-4c48-9f71-219e2e32c27c",
            "sourceColumn": "CompanyCodeID",
            "summarizeBy": "none"
          },
          {
            "name": "ExQLReportingEntity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21732a11-3ad9-4ab8-8857-fcf6630e5703",
            "sourceColumn": "ExQLReportingEntity",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d4fdabf-4e57-40ca-bbf4-e96a88d46fe3",
            "sourceColumn": "CurrencyTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da219362-b63f-4488-9a2a-94b4d0c862c7",
            "sourceColumn": "CurrencyType",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5796f03d-1ed2-4d46-8968-c8aadfda90bd",
            "sourceColumn": "CurrencyID",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "2a27a0b2-54f0-440f-a5cf-4c142a5cd7e4",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "InOutID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65690c64-c993-4892-a5ef-aa9b24f7bce0",
            "sourceColumn": "InOutID",
            "summarizeBy": "none"
          },
          {
            "name": "3_ReportedRevenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "49cdc6c4-a22d-4f13-8141-6d8fedc7a3ab",
            "sourceColumn": "3_ReportedRevenue",
            "summarizeBy": "sum"
          },
          {
            "name": "ValueTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "22c071ef-b153-4824-8aa2-979a76b5b6ae",
            "sourceColumn": "ValueTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "nk_CompCodeRepEntity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(fact_Budget_EPM[CompanyCodeID], fact_Budget_EPM[ExQLReportingEntity])",
            "isDataTypeInferred": true,
            "lineageTag": "4667e2fd-1b8e-4866-8319-d76255937e88",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "24945562-6c8f-4377-b569-6cf22ba7c633",
        "partitions": [
          {
            "name": "fact_Budget_EPM",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_finance_vw_fact_Budget_EPM = Source{[Schema=\"dm_finance\",Item=\"vw_fact_Budget_EPM\"]}[Data]",
                "in",
                "    dm_finance_vw_fact_Budget_EPM"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ValueType",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ValueTypeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f72f5b3a-8801-487f-a02e-256742360105",
            "sourceColumn": "ValueTypeID",
            "summarizeBy": "none"
          },
          {
            "name": "ValueType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83fb5441-d565-4983-9a7b-055479c65ff0",
            "sourceColumn": "ValueType",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24d053f5-c008-4437-b2cc-2c0e10466d9c",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1cc468ef-e940-4b38-8448-1ef171256187",
        "partitions": [
          {
            "name": "ValueType",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_finance_vw_dim_ValueType = Source{[Schema=\"dm_finance\",Item=\"vw_dim_ValueType\"]}[Data]",
                "in",
                "    dm_finance_vw_dim_ValueType"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "InOut",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "InOutID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1baa8437-fded-4266-9434-ef38eeaa5523",
            "sourceColumn": "InOutID",
            "summarizeBy": "none"
          },
          {
            "name": "InOut",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "134fabe9-3703-40a5-b72e-475e3fd5a96b",
            "sourceColumn": "InOut",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ac46df97-a42d-459b-bbea-0906d588d17d",
        "partitions": [
          {
            "name": "InOut",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(Source, DB),",
                "    dm_sales_vw_dim_InOut = Source{[Schema=\"dm_sales\",Item=\"vw_dim_InOut\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_InOut"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CompCodeRepEntity",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "7ee7af0bf964448f9c26d67b489c0089"
          }
        ],
        "columns": [
          {
            "name": "CompanyCodeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "06d1ecef-6516-48ad-9ca0-bbfa575602f6",
            "sourceColumn": "CompanyCodeProfitCenter[CompanyCodeID]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ExQLReportingEntity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "99545398-5bd0-4ad3-aac7-6b8e7da39498",
            "sourceColumn": "CompanyCodeProfitCenter[ExQLReportingEntity]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "nk_CompCodeRepEntity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CompCodeRepEntity[CompanyCodeID], CompCodeRepEntity[ExQLReportingEntity])",
            "isDataTypeInferred": true,
            "lineageTag": "d31a3efa-a94b-4e17-ac95-41ec64353ff9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "a3e48b80-cb22-46a8-aa0a-a1e7fae2c74a",
        "partitions": [
          {
            "name": "CompCodeRepEntity",
            "mode": "import",
            "source": {
              "expression": [
                "SUMMARIZE(",
                "    CompanyCodeProfitCenter,",
                "    CompanyCodeProfitCenter[CompanyCodeID],",
                "    CompanyCodeProfitCenter[ExQLReportingEntity]",
                ")"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "GM Element Sort",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4577eb99-5838-42c0-a000-7aa0acedb605",
            "sourceColumn": "Sort",
            "summarizeBy": "none"
          },
          {
            "name": "KPI name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "23e750d3-93bf-4391-8053-429dc41ff2d0",
            "sortByColumn": "Sort",
            "sourceColumn": "KPI name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2a87210d-9606-4786-bd1c-f1fd075399b7",
        "partitions": [
          {
            "name": "GM Element Sort",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = SharePoint.Files(\"https://crhemea.sharepoint.com/sites/crh-group-cs-dataandanalyti-0010_DevOps/\", [ApiVersion = 15]),",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Name] = \"Sales KPI Sorting.xlsx\")),",
                "    #\"Sales KPI Sorting xlsx_https://crhemea sharepoint com/sites/crh-group-cs-dataandanalyti-0010_DevOps/Shared Documents/0010_DevOps/\" = #\"Filtered Rows\"{[Name=\"Sales KPI Sorting.xlsx\",#\"Folder Path\"=\"https://crhemea.sharepoint.com/sites/crh-group-cs-dataandanalyti-0010_DevOps/Shared Documents/0010_DevOps/\"]}[Content],",
                "    #\"Imported Excel Workbook\" = Excel.Workbook(#\"Sales KPI Sorting xlsx_https://crhemea sharepoint com/sites/crh-group-cs-dataandanalyti-0010_DevOps/Shared Documents/0010_DevOps/\"),",
                "    Sheet1_Sheet = #\"Imported Excel Workbook\"{[Item=\"Sheet1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Sort\", Int64.Type}, {\"KPI name\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Reconciliation_File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Reporting Entity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "326414ca-530b-413c-ae84-81ea04af4c93",
            "sourceColumn": "Reporting Entity",
            "summarizeBy": "none"
          },
          {
            "name": "Company Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce647507-5fa7-46c0-8b29-5679bb78f958",
            "sourceColumn": "Company Code",
            "summarizeBy": "none"
          },
          {
            "name": "ExQL reporting entity ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b208799-6069-4811-b43e-388742c026ca",
            "sourceColumn": "ExQL reporting entity ",
            "summarizeBy": "none"
          },
          {
            "name": "Key ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "356e9537-75b9-4e4c-99f4-1fca1c8ab339",
            "sourceColumn": "Key ",
            "summarizeBy": "none"
          },
          {
            "name": "YTD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6b4dd0cb-83b8-45b3-a436-72f034c0b1b6",
            "sourceColumn": "YTD",
            "summarizeBy": "none"
          },
          {
            "name": "ExQL values in $mm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "691984c0-00af-44d8-a419-125df0273532",
            "sourceColumn": "ExQL values in $mm",
            "summarizeBy": "sum"
          },
          {
            "name": "BI values in $mm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c47fb0f9-6063-432e-97b1-f2fbab4404e7",
            "sourceColumn": "BI values in $mm",
            "summarizeBy": "sum"
          },
          {
            "name": "Diff in $mm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "04d09108-fc32-4e5d-9df6-ed623e7e2fe7",
            "sourceColumn": "Diff in $mm",
            "summarizeBy": "sum"
          },
          {
            "name": "ExQL values in Loc cur mm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c277232d-e6b9-4a5b-81b6-f278d2f5b885",
            "sourceColumn": "ExQL values in Loc cur mm",
            "summarizeBy": "sum"
          },
          {
            "name": "BI values in Loc cur mm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cb02bc35-1fea-48fe-9b99-aa480f9928cf",
            "sourceColumn": "BI values in Loc cur mm",
            "summarizeBy": "sum"
          },
          {
            "name": "Diff in Loc cur mm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e03f42d9-5ca3-4009-93a3-e1f9925454e8",
            "sourceColumn": "Diff in Loc cur mm",
            "summarizeBy": "sum"
          },
          {
            "name": "Comments",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "794003c0-a9f8-46ec-ad03-5aabc16c0a69",
            "sourceColumn": "Comments",
            "summarizeBy": "none"
          },
          {
            "name": "Column13",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c83a41cd-1a6d-444d-b133-bc2f2eab7909",
            "sourceColumn": "Column13",
            "summarizeBy": "none"
          },
          {
            "name": "Column14",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c879c19-2d18-40c4-8274-d1cba637c4ff",
            "sourceColumn": "Column14",
            "summarizeBy": "none"
          },
          {
            "name": "Column15",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86d3b386-5bcf-4d7c-a7ab-b192b5fddc04",
            "sourceColumn": "Column15",
            "summarizeBy": "none"
          },
          {
            "name": "Column16",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1515381-8e65-4870-bf75-1bb980bdf4f4",
            "sourceColumn": "Column16",
            "summarizeBy": "none"
          },
          {
            "name": "Column17",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74debc7f-7b94-469f-beac-024ba777dabf",
            "sourceColumn": "Column17",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6c62be00-8113-4fc8-b0ba-d0719f1c79a3",
        "partitions": [
          {
            "name": "Reconciliation_File",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(Web.Contents(\"https://crhemea.sharepoint.com/sites/crh-group-cs-leviatfinancep/MEC%20Files/00.MEC%20TEMPLATES/ExQL%20to%20SAP%20Reconciliation/GM_reconciliation_data.xlsx\"), null, true),",
                "    Sheet2_Sheet = Source{[Item=\"Sheet2\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers1\" = Table.PromoteHeaders(Sheet2_Sheet, [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers1\",{{\"Reporting Entity\", type text}, {\"Company Code\", type text}, {\"ExQL reporting entity \", type text}, {\"Key \", type text}, {\"YTD\", type date}, {\"ExQL values in $mm\", type number}, {\"BI values in $mm\", type number}, {\"Diff in $mm\", type number}, {\"ExQL values in Loc cur mm\", type number}, {\"BI values in Loc cur mm\", type number}, {\"Diff in Loc cur mm\", type number}, {\"Comments\", type any}, {\"Column13\", type any}, {\"Column14\", type any}, {\"Column15\", type any}, {\"Column16\", type any}, {\"Column17\", type any}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type1\", each ([#\"Key \"] <> null))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "GM Element 2 Sorting",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "GM element L2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "182c7cd1-af55-4188-a14d-696a7cd4493e",
            "sortByColumn": "Sort",
            "sourceColumn": "GM element L2",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ddf478b0-4a2a-4e10-8677-a969167d4210",
            "sourceColumn": "Sort",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "83ccf753-d5ef-48c9-8cd1-977cb1ed2aa1",
        "partitions": [
          {
            "name": "GM Element 2 Sorting",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"jZLRT8IwEMb/lcueNIHIpqA8YzAmEAxETSQ8dN1tNIx2ubb8/V67BVQg8fF2v/vu29dbr5Oklzwkm946mRjrwJSwF9qXQjpPSldQqLJEQi2RwWELLl5WXIxisfK5NNoRDwS8D29kCs+F0cw8RmaJB1F7Eb4xMF9mGUhDhJGyjD1F7JOUw74pSwt3YCWJphFVWDuO7Q9BSuQ1Qm0qZZ2SllWsC/PpIBLvuuAGqdw7LKAhJfGH/wimETx5hENQbf8uzWJz4bZILK2t38d9dLIfqPtIzWdnC0DUtZFHrk31GblL1+wMT1oXHY2u7YrTbbpzQbu+b6A0BOawhZuvSTq45X5r9FVLs8fYLQlVtXWBmKaByP4SnY2o/jt0K2q0IHTB90E7jI99jL99v2knb7zLjddF6Iw7iw5Zp4Yai4rDDdfFVZgPOuRDYFn7iCvHSwQV0J1Zlp7d0N2lG8qy/9wA5Mj/iXB0NIuOwjzHtfkG\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"GM element L2\" = _t, Sort = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Sort\", Int64.Type}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Changed Type\",{{\"Sort\", Order.Ascending}})",
                "in",
                "    #\"Sorted Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "srv_Actual_Finance",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb128ba6-a27e-483d-b5df-299adda16a5b",
            "sourceColumn": "Value",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fe232730-9e67-445e-9774-6bff5dbc0eb9",
        "partitions": [
          {
            "name": "srv_Actual_Finance",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45W8sxLzilNSVWK1YlWcq2AsmMB\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Value = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Value\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ProductPlant",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "nk_ProductPlant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b036a973-94b7-4ca2-abbc-7c5bb9ba7be4",
            "sourceColumn": "nk_ProductPlant",
            "summarizeBy": "none"
          },
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c082779d-1469-4979-adc8-ed43206cb50a",
            "sourceColumn": "Product",
            "summarizeBy": "none"
          },
          {
            "name": "Plant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65af392e-6f65-4c3f-bd9f-13683c870563",
            "sourceColumn": "Plant",
            "summarizeBy": "none"
          },
          {
            "name": "PurchasingGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "620060d4-e378-4cb3-8c15-52b270e73732",
            "sourceColumn": "PurchasingGroup",
            "summarizeBy": "none"
          },
          {
            "name": "CountryOfOrigin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7d9d1bd-f9e3-46f2-b90c-4a41e8d9cf7e",
            "sourceColumn": "CountryOfOrigin",
            "summarizeBy": "none"
          },
          {
            "name": "RegionOfOrigin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79a4ef6c-18b5-40a3-a439-feb74987cf11",
            "sourceColumn": "RegionOfOrigin",
            "summarizeBy": "none"
          },
          {
            "name": "ProductionInvtryManagedLoc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae00a230-db97-4e30-ab1c-9fa88b0bb7f7",
            "sourceColumn": "ProductionInvtryManagedLoc",
            "summarizeBy": "none"
          },
          {
            "name": "ProfileCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b472dff-86d3-4882-b49a-2c2ac71eb19e",
            "sourceColumn": "ProfileCode",
            "summarizeBy": "none"
          },
          {
            "name": "ProfileValidityStartDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3e158d9a-bd7f-4715-8af0-9e0ca215eef4",
            "sourceColumn": "ProfileValidityStartDate",
            "summarizeBy": "none"
          },
          {
            "name": "AvailabilityCheckType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf0b254a-ccaa-4c9a-a725-0f3ceadbd24d",
            "sourceColumn": "AvailabilityCheckType",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYearVariant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0cd319e6-e628-4ec5-be7a-934f68e94262",
            "sourceColumn": "FiscalYearVariant",
            "summarizeBy": "none"
          },
          {
            "name": "PeriodType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "31d24ce1-4936-4b44-8670-94bf50e04a50",
            "sourceColumn": "PeriodType",
            "summarizeBy": "none"
          },
          {
            "name": "ProfitCenter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6dedfff8-0f2f-4466-86ae-54db82d11e98",
            "sourceColumn": "ProfitCenter",
            "summarizeBy": "none"
          },
          {
            "name": "Commodity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3689273c-2a2f-4ae0-ab2e-810f6ab59b95",
            "sourceColumn": "Commodity",
            "summarizeBy": "none"
          },
          {
            "name": "GoodsReceiptDuration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ab26f2a3-0406-42f8-a6cf-ba06e1053f35",
            "sourceColumn": "GoodsReceiptDuration",
            "summarizeBy": "none"
          },
          {
            "name": "MaintenanceStatusName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebd04e2f-016e-4486-b3a0-7e79aeddafb2",
            "sourceColumn": "MaintenanceStatusName",
            "summarizeBy": "none"
          },
          {
            "name": "IsMarkedForDeletion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "325ffa5b-87e3-44cc-babe-2e283685748a",
            "sourceColumn": "IsMarkedForDeletion",
            "summarizeBy": "none"
          },
          {
            "name": "MRPType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d0289a8-f1c0-4c75-892e-41d5471fe617",
            "sourceColumn": "MRPType",
            "summarizeBy": "none"
          },
          {
            "name": "MRPResponsible",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eaa34f81-fc1d-485b-888d-6b8651ab353c",
            "sourceColumn": "MRPResponsible",
            "summarizeBy": "none"
          },
          {
            "name": "ABCIndicator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88d3b63c-4eba-47e7-b891-02ee9c4d53d2",
            "sourceColumn": "ABCIndicator",
            "summarizeBy": "none"
          },
          {
            "name": "MinimumLotSizeQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "951cd842-4ee5-4c81-8545-3424b681a813",
            "sourceColumn": "MinimumLotSizeQuantity",
            "summarizeBy": "none"
          },
          {
            "name": "MaximumLotSizeQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f1c3ec9f-1176-4f81-8ebc-798d397d939c",
            "sourceColumn": "MaximumLotSizeQuantity",
            "summarizeBy": "none"
          },
          {
            "name": "FixedLotSizeQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "20b4cf6d-4647-48a9-acb8-1375e41a6b7a",
            "sourceColumn": "FixedLotSizeQuantity",
            "summarizeBy": "none"
          },
          {
            "name": "ConsumptionTaxCtrlCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "462b21bb-c6c9-4d77-a258-4594ef59cd56",
            "sourceColumn": "ConsumptionTaxCtrlCode",
            "summarizeBy": "none"
          },
          {
            "name": "IsCoProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d6aa0efc-2db0-4904-8768-51f2f0e1891a",
            "sourceColumn": "IsCoProduct",
            "summarizeBy": "none"
          },
          {
            "name": "ProductIsConfigurable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "993ecaf6-9873-4024-9d97-74c221c5561d",
            "sourceColumn": "ProductIsConfigurable",
            "summarizeBy": "none"
          },
          {
            "name": "ConfigurableProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dcf03145-f29a-4104-92c2-6b0344c6390f",
            "sourceColumn": "ConfigurableProduct",
            "summarizeBy": "none"
          },
          {
            "name": "StockDeterminationGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28314f62-f9c3-48cc-b192-6cf4da3e378a",
            "sourceColumn": "StockDeterminationGroup",
            "summarizeBy": "none"
          },
          {
            "name": "StockInTransferQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "11082ff1-09b4-4d3a-86d1-c88036466f1f",
            "sourceColumn": "StockInTransferQuantity",
            "summarizeBy": "none"
          },
          {
            "name": "StockInTransitQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c6851638-6bc6-4ad5-9b39-26abc359b111",
            "sourceColumn": "StockInTransitQuantity",
            "summarizeBy": "none"
          },
          {
            "name": "HasPostToInspectionStock",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a927dbab-4b09-4593-9d80-cbabd81dfcaf",
            "sourceColumn": "HasPostToInspectionStock",
            "summarizeBy": "none"
          },
          {
            "name": "IsBatchManagementRequired",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "facceb54-871e-48ab-a0f1-be5581970926",
            "sourceColumn": "IsBatchManagementRequired",
            "summarizeBy": "none"
          },
          {
            "name": "SerialNumberProfile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "37dc60b6-754d-41e3-8af8-cc2a4ee645f5",
            "sourceColumn": "SerialNumberProfile",
            "summarizeBy": "none"
          },
          {
            "name": "IsNegativeStockAllowed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71ba9785-e143-4f91-89ae-6de0f7bc4dcf",
            "sourceColumn": "IsNegativeStockAllowed",
            "summarizeBy": "none"
          },
          {
            "name": "GoodsReceiptBlockedStockQty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "49fd18b5-1789-4f5a-980a-43e0a45fb654",
            "sourceColumn": "GoodsReceiptBlockedStockQty",
            "summarizeBy": "none"
          },
          {
            "name": "HasConsignmentCtrl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8f1cdaa-9c13-4faf-b4c2-27e09b38767c",
            "sourceColumn": "HasConsignmentCtrl",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYearCurrentPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3701b47f-fb2c-4142-a307-3926b210a2a9",
            "sourceColumn": "FiscalYearCurrentPeriod",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalMonthCurrentPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3674ca89-84ff-4ff5-b648-bd9f5872c753",
            "sourceColumn": "FiscalMonthCurrentPeriod",
            "summarizeBy": "none"
          },
          {
            "name": "IsPurgAcrossPurgGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79507a2c-74de-4487-af93-e081d4da101c",
            "sourceColumn": "IsPurgAcrossPurgGroup",
            "summarizeBy": "none"
          },
          {
            "name": "IsInternalBatchManaged",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0f2f6a2-e323-4679-a897-3c0dbf136791",
            "sourceColumn": "IsInternalBatchManaged",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCFOPCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a8e47c4-5877-4154-b5ad-2d7a1f22aa43",
            "sourceColumn": "ProductCFOPCategory",
            "summarizeBy": "none"
          },
          {
            "name": "ProductIsExciseTaxRelevant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92785d5c-b218-4d45-8759-45ae9686e506",
            "sourceColumn": "ProductIsExciseTaxRelevant",
            "summarizeBy": "none"
          },
          {
            "name": "UnderDelivToleranceLimit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b5fc802e-a532-4542-bdf8-b79f2f3fd0d1",
            "sourceColumn": "UnderDelivToleranceLimit",
            "summarizeBy": "none"
          },
          {
            "name": "OverDelivToleranceLimit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1b184057-c7af-4040-8d0d-17857eb5a434",
            "sourceColumn": "OverDelivToleranceLimit",
            "summarizeBy": "none"
          },
          {
            "name": "ProcurementType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7808bfc-e4a2-46a5-8eb5-9a8186443c12",
            "sourceColumn": "ProcurementType",
            "summarizeBy": "none"
          },
          {
            "name": "SpecialProcurementType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51dc2f19-30ea-45c4-8c77-1e3ed2a55083",
            "sourceColumn": "SpecialProcurementType",
            "summarizeBy": "none"
          },
          {
            "name": "ProductionSchedulingProfile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aeb4d11c-cf75-4cd2-9564-8f2aae5449ac",
            "sourceColumn": "ProductionSchedulingProfile",
            "summarizeBy": "none"
          },
          {
            "name": "ProductionSupervisor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0eb2a6f0-5060-4b87-ab2a-75fe370241a0",
            "sourceColumn": "ProductionSupervisor",
            "summarizeBy": "none"
          },
          {
            "name": "SafetyStockQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "71d25183-15c9-4a61-b81c-4eb2f5a01116",
            "sourceColumn": "SafetyStockQuantity",
            "summarizeBy": "none"
          },
          {
            "name": "GoodsIssueUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1be9af7-0976-4f4d-8fcc-9df409134a9f",
            "sourceColumn": "GoodsIssueUnit",
            "summarizeBy": "none"
          },
          {
            "name": "SourceOfSupplyCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "556d651b-242a-4dc0-807d-44526e4dbb94",
            "sourceColumn": "SourceOfSupplyCategory",
            "summarizeBy": "none"
          },
          {
            "name": "ConsumptionReferenceProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f10a912-7a41-463d-94d4-71b2465ecd93",
            "sourceColumn": "ConsumptionReferenceProduct",
            "summarizeBy": "none"
          },
          {
            "name": "ConsumptionReferencePlant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "976aab5a-7f85-45ed-a3c9-3531e002f8a7",
            "sourceColumn": "ConsumptionReferencePlant",
            "summarizeBy": "none"
          },
          {
            "name": "ConsumptionRefUsageEndDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "98627688-0e11-420d-bc96-39e30c20db04",
            "sourceColumn": "ConsumptionRefUsageEndDate",
            "summarizeBy": "none"
          },
          {
            "name": "ConsumptionQtyMultiplier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "314a0735-4323-497c-ac35-f5f0a93984b7",
            "sourceColumn": "ConsumptionQtyMultiplier",
            "summarizeBy": "none"
          },
          {
            "name": "ProductUnitGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11be9ef2-26f7-44e6-b195-028e03a5fbe5",
            "sourceColumn": "ProductUnitGroup",
            "summarizeBy": "none"
          },
          {
            "name": "DistrCntrDistributionProfile",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "08d2211a-59a5-41e2-a38f-0ac9e776854a",
            "sourceColumn": "DistrCntrDistributionProfile",
            "summarizeBy": "none"
          },
          {
            "name": "ConsignmentControl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41fe2827-f8a6-4dac-bbc6-d20841f5bd1f",
            "sourceColumn": "ConsignmentControl",
            "summarizeBy": "none"
          },
          {
            "name": "GoodIssueProcessingDays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d752f6a5-b321-42b0-b372-bd9d7fae50c3",
            "sourceColumn": "GoodIssueProcessingDays",
            "summarizeBy": "none"
          },
          {
            "name": "PlannedDeliveryDurationInDays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5fb1ffd3-9f1d-4ca4-970c-bac6d2347bec",
            "sourceColumn": "PlannedDeliveryDurationInDays",
            "summarizeBy": "none"
          },
          {
            "name": "IsActiveEntity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7701cb6d-2298-4fac-8cd3-825270f92c84",
            "sourceColumn": "IsActiveEntity",
            "summarizeBy": "none"
          },
          {
            "name": "ProductIsCriticalPrt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93d38459-b602-454e-aab6-58028554ae0d",
            "sourceColumn": "ProductIsCriticalPrt",
            "summarizeBy": "none"
          },
          {
            "name": "ProductLogisticsHandlingGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2fabf1e7-0336-41dd-a631-9da68bf4dd3a",
            "sourceColumn": "ProductLogisticsHandlingGroup",
            "summarizeBy": "none"
          },
          {
            "name": "MaterialFreightGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "850a1e3e-5ad6-45a2-841c-be7a3b15cf23",
            "sourceColumn": "MaterialFreightGroup",
            "summarizeBy": "none"
          },
          {
            "name": "OriginalBatchReferenceMaterial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c5d3814-0dd6-42ff-8b71-869e062e80a6",
            "sourceColumn": "OriginalBatchReferenceMaterial",
            "summarizeBy": "none"
          },
          {
            "name": "OriglBatchManagementIsRequired",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0649e837-73d8-444a-8ed6-042501cb3180",
            "sourceColumn": "OriglBatchManagementIsRequired",
            "summarizeBy": "none"
          },
          {
            "name": "ProductConfiguration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "815141af-a109-411e-ba88-21a00a3a2d8f",
            "sourceColumn": "ProductConfiguration",
            "summarizeBy": "none"
          },
          {
            "name": "MRPController",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5dcb69ad-dbfd-4c4f-92b9-6bd15265fd73",
            "sourceColumn": "MRPController",
            "summarizeBy": "none"
          },
          {
            "name": "Re-Order Point",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d454323b-83d7-4086-8e6f-e74bf3bfa0b4",
            "sourceColumn": "Re-Order Point",
            "summarizeBy": "none"
          },
          {
            "name": "Rounding Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c5d58ea3-52de-434c-9c46-8e20a1f26ccc",
            "sourceColumn": "Rounding Value",
            "summarizeBy": "none"
          },
          {
            "name": "PlanningStrategyGroupID_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d872f11f-b6d3-4257-8c52-874de3ac6d89",
            "sourceColumn": "PlanningStrategyGroupID_Name",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88260468-a003-4147-9d32-5257d6ab01ba",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "851b37cc-9076-4b0e-a9f1-7b651614f64f",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f2d8c5a9-bf6a-4524-ae1e-303ac2d49680",
        "partitions": [
          {
            "name": "ProductPlant",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(#\"Source\", #\"DB\"),",
                "    dm_sales_vw_dim_InOut = Source{[Schema=\"dm_sales\",Item=\"vw_dim_ProductPlant\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_InOut"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Plant",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PlantID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6ff1eb8-403b-4bed-8995-8efbbdcbfb58",
            "sourceColumn": "PlantID",
            "summarizeBy": "none"
          },
          {
            "name": "Plant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd6b491b-37a3-4b12-b2c5-9f2a0a3b5f3c",
            "sourceColumn": "Plant",
            "summarizeBy": "none"
          },
          {
            "name": "ValuationArea",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ba307e0-eac4-45a8-be25-ca60cf6fbba4",
            "sourceColumn": "ValuationArea",
            "summarizeBy": "none"
          },
          {
            "name": "PlantCustomer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3602a012-7b38-49d5-93f7-991207000410",
            "sourceColumn": "PlantCustomer",
            "summarizeBy": "none"
          },
          {
            "name": "PlantSupplier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d3efcc3-35c3-4039-9a5f-e409d1ec9a28",
            "sourceColumn": "PlantSupplier",
            "summarizeBy": "none"
          },
          {
            "name": "FactoryCalendar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87964c07-f36a-4ae0-8041-1f3811122b76",
            "sourceColumn": "FactoryCalendar",
            "summarizeBy": "none"
          },
          {
            "name": "DefaultPurchasingOrganization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "32749901-10e1-465d-b8a9-6ddbeba981df",
            "sourceColumn": "DefaultPurchasingOrganization",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganizationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2af9911d-5585-4fa4-b9cf-28bd929fe90f",
            "sourceColumn": "SalesOrganizationID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganization",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a97c0c9-9cdb-40bf-9d1c-39c592ff04db",
            "sourceColumn": "SalesOrganization",
            "summarizeBy": "none"
          },
          {
            "name": "AddressID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "853f9f78-3b33-43e8-a9ed-62eccf00e0c7",
            "sourceColumn": "AddressID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrg_CountryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92bbe2b2-86c4-4f91-930a-c0f8ca65abcf",
            "sourceColumn": "SalesOrg_CountryID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrg_Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e8c2008-fbea-48b8-9a13-614dd4d80340",
            "sourceColumn": "SalesOrg_Country",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrg_RegionID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "126692e2-f9e2-489e-8a72-d61d937fb9fe",
            "sourceColumn": "SalesOrg_RegionID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrg_Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ec2d8c6-bd26-49e2-bc85-62dac4e76a89",
            "sourceColumn": "SalesOrg_Region",
            "summarizeBy": "none"
          },
          {
            "name": "PlantCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8a268fd-6012-4818-adfe-f1ce8648602d",
            "sourceColumn": "PlantCategory",
            "summarizeBy": "none"
          },
          {
            "name": "DistributionChannel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73963bf0-f27f-471a-bba5-66023f40f230",
            "sourceColumn": "DistributionChannel",
            "summarizeBy": "none"
          },
          {
            "name": "Division",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e938be5-3e4f-44df-b376-952ab6eef9cf",
            "sourceColumn": "Division",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "673f9463-4ac3-43f2-b73f-7d1e49b57582",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "04fae440-5b55-4008-9c16-c2820bcdf192",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9cdd6b5b-78e7-4360-9103-1cb611ace465",
        "partitions": [
          {
            "name": "Plant",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(#\"Source\", #\"DB\"),",
                "    dm_sales_vw_dim_InOut = Source{[Schema=\"dm_sales\",Item=\"vw_dim_Plant\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_InOut"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ProductSalesDelivery",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "sk_ProductSalesDelivery",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3fbdf7e9-27dd-4694-9bf4-c1d4d716f7b3",
            "sourceColumn": "sk_ProductSalesDelivery",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cf423369-5ec5-4f3a-bbd5-b20d98c363a8",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrganizationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c530f39-0b44-4acd-a15e-e92eebf88367",
            "sourceColumn": "SalesOrganizationID",
            "summarizeBy": "none"
          },
          {
            "name": "DistributionChannelID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "869d26bc-730f-4fdc-933c-37c9a2b78a55",
            "sourceColumn": "DistributionChannelID",
            "summarizeBy": "none"
          },
          {
            "name": "DistributionChannel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd2d55c9-3a88-4a80-82b8-2a2c6e6b2205",
            "sourceColumn": "DistributionChannel",
            "summarizeBy": "none"
          },
          {
            "name": "MinimumOrderQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "125b40f9-9996-4d30-8229-7fa1855a837f",
            "sourceColumn": "MinimumOrderQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "SupplyingPlant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76afd8a9-31cb-4ce4-9b18-a3b7e48aa8fb",
            "sourceColumn": "SupplyingPlant",
            "summarizeBy": "none"
          },
          {
            "name": "PriceSpecificationProductGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d986591-f213-4644-8f4f-e0759750f3ae",
            "sourceColumn": "PriceSpecificationProductGroup",
            "summarizeBy": "none"
          },
          {
            "name": "AccountDetnProductGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e2f31c5-ec76-4157-beca-91f06b756496",
            "sourceColumn": "AccountDetnProductGroup",
            "summarizeBy": "none"
          },
          {
            "name": "DeliveryNoteProcMinDelivQty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "074f21d3-a4a2-4dbb-ace9-c9d23c556066",
            "sourceColumn": "DeliveryNoteProcMinDelivQty",
            "summarizeBy": "sum"
          },
          {
            "name": "ItemCategoryGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87d55516-38ec-4c59-8470-6d51750be4e9",
            "sourceColumn": "ItemCategoryGroup",
            "summarizeBy": "none"
          },
          {
            "name": "ItemCategoryGroupName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "671b16ab-1882-4252-9cff-9779970c7196",
            "sourceColumn": "ItemCategoryGroupName",
            "summarizeBy": "none"
          },
          {
            "name": "DeliveryQuantityUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d727af06-51e4-4d66-a8a2-778245928072",
            "sourceColumn": "DeliveryQuantityUnit",
            "summarizeBy": "none"
          },
          {
            "name": "DeliveryQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "81af488f-ee46-4a5f-a980-d782a58c3cc4",
            "sourceColumn": "DeliveryQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductSalesStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8684bc8-894f-4460-8a83-c548e315ff67",
            "sourceColumn": "ProductSalesStatus",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSalesStatusValidityDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8c761fd6-ec60-4e59-9993-b4592b057135",
            "sourceColumn": "ProductSalesStatusValidityDate",
            "summarizeBy": "none"
          },
          {
            "name": "SalesMeasureUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4256955c-4d71-4c50-ac6b-a3e0f90c4629",
            "sourceColumn": "SalesMeasureUnit",
            "summarizeBy": "none"
          },
          {
            "name": "IsMarkedForDeletion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "976fb0d1-6fef-4597-8131-c523d50e0b87",
            "sourceColumn": "IsMarkedForDeletion",
            "summarizeBy": "none"
          },
          {
            "name": "IsConfigurable",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5262a43-ff7d-4ca3-a568-8152afe03a08",
            "sourceColumn": "IsConfigurable",
            "summarizeBy": "none"
          },
          {
            "name": "t_applicationId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81122a3d-e086-46bb-96cc-3416d84b2703",
            "sourceColumn": "t_applicationId",
            "summarizeBy": "none"
          },
          {
            "name": "t_extractionDtm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "523ed8d1-11f9-4e82-8003-0c059a58dff6",
            "sourceColumn": "t_extractionDtm",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ee80df4a-d16f-411b-a6e9-c8bfb9f2b1db",
        "partitions": [
          {
            "name": "ProductSalesDelivery",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(#\"Source\", #\"DB\"),",
                "    dm_sales_vw_dim_InOut = Source{[Schema=\"dm_sales\",Item=\"vw_fact_ProductSalesDelivery\"]}[Data]",
                "in",
                "    dm_sales_vw_dim_InOut"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}