CREATE VIEW [dm_sales].[vw_dim_Product] AS

WITH CTE_Products AS(
SELECT
    P.[sk_dim_Product],
    P.[ProductID],
    P.[ProductExternalID],
    P.[Product],
    P.[ProductID_Name],
    P.[ProductOldID],
    P.[CreationDate],
    P.[MaterialTypeID],
    P.[MaterialType],
    P.[IsMarkedForDeletion],
    P.[CrossPlantStatusID],
    P.[CrossPlantStatus],
    P.[GrossWeight],
    P.[SourceOfSupply],
    P.[CountryOfOrigin],
    P.[CompetitorID],
    P.[ProductGroup] AS [MaterialGroup], -- So all PBI datasets keep working
    P.[BaseUnit],
    P.[ItemCategoryGroup],
    P.[ItemCategoryGroupName],
    P.[ProductHierarchy],
    P.[Product_L1_PillarID],
    P.[Product_L2_GroupID],
    P.[Product_L3_TypeID],
    P.[Product_L4_FamilyID],
    P.[Product_L5_SubFamilyID],
    P.[Product_L1_Pillar],
    P.[Product_L2_Group],
    P.[Product_L3_Type],
    P.[Product_L4_Family],
    P.[Product_L5_SubFamily],
    P.[ProductCategory],
    P.[Brand],
    P.[IndustryStandardName],
    P.[ProductStandardID],
    P.[InternationalArticleNumberCat],
    P.[ProductIsConfigurable],
    P.[IsBatchManagementRequired],
    P.[ExternalProductGroup],
    P.[CrossPlantConfigurableProduct],
    P.[ProductManufacturerNumber],
    P.[ManufacturerNumber],
    P.[MaximumPackagingLength],
    P.[MaximumPackagingWidth],
    P.[MaximumPackagingHeight],
    P.[MaximumCapacity],
    P.[OvercapacityTolerance],
    P.[UnitForMaxPackagingDimensions],
    P.[BaseUnitSpecificProductLength],
    P.[BaseUnitSpecificProductWidth],
    P.[BaseUnitSpecificProductHeight],
    P.[ArticleCategory],
    P.[ProductIsLocked],
    P.[BasicMaterial],
    P.[SalesProduct],
    P.[NetWeight],
    P.[IndustrySector],
    P.[WeightUnit],
    P.[Division],
    P.[TransportationGroup],
    P.[EClassCode],
    P.[EClassCategory],
    P.[EClassCategoryDescription],
    P.[Category_L1],
    P.[Category_L2],
    P.[Category_L3],
    P.[Category_L4],
    P.[Classification], 
    P.[ZZ1_CustomFieldRiskMit_PRD],
    P.[ZZ1_CustomFieldHighRis_PRD],
    P.[ZZ1_CustomFieldRiskRea_PRD],
    P.[CreatedByUser],
    P.[t_jobDtm],
    P.[t_applicationId],
    P.[t_extractionDtm]
FROM
    [edw].[dim_Product] P

UNION ALL

SELECT
      [ProductID] AS [sk_dim_Product],
      [ProductID],
      [ProductExternalID],
      [Product],
      [ProductID_Name],
      NULL AS [ProductOldID],
      NULL AS [CreationDate],
      [MaterialTypeID],
      [MaterialType],
      NULL AS [IsMarkedForDeletion],
      NULL AS [CrossPlantStatusID],
      NULL AS [CrossPlantStatus],
      NULL AS [GrossWeight],
      NULL AS [SourceOfSupply],
      NULL AS [CountryOfOrigin],
      NULL AS [CompetitorID],
      NULL AS [MaterialGroup],
      NULL AS [BaseUnit],
      NULL AS [ItemCategoryGroup],
      NULL AS [ItemCategoryGroupName],
      [ProductHierarchy],
      [Product_L1_PillarID],
      [Product_L2_GroupID],
      [Product_L3_TypeID],
      [Product_L4_FamilyID],
      [Product_L5_SubFamilyID],
      [Product_L1_Pillar],
      [Product_L2_Group],
      [Product_L3_Type],
      [Product_L4_Family],
      [Product_L5_SubFamily],
      NULL AS [ProductCategory],
      NULL AS [Brand],
      NULL AS [IndustryStandardName],
      NULL AS [ProductStandardID],
      NULL AS [InternationalArticleNumberCat],
      NULL AS [ProductIsConfigurable],
      NULL AS [IsBatchManagementRequired],
      NULL AS [ExternalProductGroup],
      NULL AS [CrossPlantConfigurableProduct],
      NULL AS [ProductManufacturerNumber],
      NULL AS [ManufacturerNumber],
      NULL AS [MaximumPackagingLength],
      NULL AS [MaximumPackagingWidth],
      NULL AS [MaximumPackagingHeight],
      NULL AS [MaximumCapacity],
      NULL AS [OvercapacityTolerance],
      NULL AS [UnitForMaxPackagingDimensions],
      NULL AS [BaseUnitSpecificProductLength],
      NULL AS [BaseUnitSpecificProductWidth],
      NULL AS [BaseUnitSpecificProductHeight],
      NULL AS [ArticleCategory],
      NULL AS [ProductIsLocked],
      NULL AS [BasicMaterial],
      NULL AS [SalesProduct],
      NULL AS [NetWeight],
      NULL AS [IndustrySector],
      NULL AS [WeightUnit],
      NULL AS [Division],
      NULL AS [TransportationGroup],
      NULL AS [EClassCode],                 
      NULL AS [EClassCategory],             
      NULL AS [EClassCategoryDescription], 
      NULL AS [Category_L1],
      NULL AS [Category_L2],
      NULL AS [Category_L3],
      NULL AS [Category_L4],
      NULL AS [Classification], 
      NULL AS [ZZ1_CustomFieldRiskMit_PRD],
      NULL AS [ZZ1_CustomFieldHighRis_PRD],
      NULL AS [ZZ1_CustomFieldRiskRea_PRD],
      NULL AS [CreatedByUser],
      [t_jobDtm],
      [t_applicationId],
      [t_extractionDtm]
FROM
    [edw].[dim_AXProductSAPHierarchy]
)
SELECT
    [sk_dim_Product],
    [ProductID],
    [ProductExternalID],
    [Product],
    [ProductID_Name],
    [ProductOldID],
    [CreationDate],
    [MaterialTypeID],
    [MaterialType],
    [IsMarkedForDeletion],
    [CrossPlantStatusID],
    [CrossPlantStatus],
    [GrossWeight],
    [SourceOfSupply],
    [CountryOfOrigin],
    [CompetitorID],
    [MaterialGroup], -- So all PBI datasets keep working
    [BaseUnit],
    [ItemCategoryGroup],
    [ItemCategoryGroupName],
    [ProductHierarchy],
    [edw].[svf_getSAPHierarchyNode]([Product_L1_PillarID]) AS [Product_L1_PillarID],
    [edw].[svf_getSAPHierarchyNode]([Product_L2_GroupID]) AS [Product_L2_GroupID],
    [edw].[svf_getSAPHierarchyNode]([Product_L3_TypeID]) AS [Product_L3_TypeID],
    [edw].[svf_getSAPHierarchyNode]([Product_L4_FamilyID]) AS [Product_L4_FamilyID],
    [edw].[svf_getSAPHierarchyNode]([Product_L5_SubFamilyID]) AS [Product_L5_SubFamilyID],
    [edw].[svf_getSAPHierarchyNode]([Product_L1_Pillar]) AS [Product_L1_Pillar],
    [edw].[svf_getSAPHierarchyNode]([Product_L2_Group]) AS [Product_L2_Group],
    [edw].[svf_getSAPHierarchyNode]([Product_L3_Type]) AS [Product_L3_Type],
    [edw].[svf_getSAPHierarchyNode]([Product_L4_Family]) AS [Product_L4_Family],
    [edw].[svf_getSAPHierarchyNode]([Product_L5_SubFamily]) AS [Product_L5_SubFamily],
    [ProductCategory],
    [Brand],
    [IndustryStandardName],
    [ProductStandardID],
    [InternationalArticleNumberCat],
    [ProductIsConfigurable],
    [IsBatchManagementRequired],
    [ExternalProductGroup],
    [CrossPlantConfigurableProduct],
    [ProductManufacturerNumber],
    [ManufacturerNumber],
    [MaximumPackagingLength],
    [MaximumPackagingWidth],
    [MaximumPackagingHeight],
    [MaximumCapacity],
    [OvercapacityTolerance],
    [UnitForMaxPackagingDimensions],
    [BaseUnitSpecificProductLength],
    [BaseUnitSpecificProductWidth],
    [BaseUnitSpecificProductHeight],
    [ArticleCategory],
    [ProductIsLocked],
    [BasicMaterial],
    [SalesProduct],
    [NetWeight],
    [IndustrySector],
    [WeightUnit],
    [Division],
    [TransportationGroup],
    [EClassCode],
    [EClassCategory],
    [EClassCategoryDescription],
    [Category_L1],
    [Category_L2],
    [Category_L3],
    [Category_L4],
    [Classification], 
    [ZZ1_CustomFieldRiskMit_PRD],
    [ZZ1_CustomFieldHighRis_PRD],
    [ZZ1_CustomFieldRiskRea_PRD],
    [CreatedByUser],
    [t_jobDtm],
    [t_applicationId],
    [t_extractionDtm]
FROM
    CTE_Products