CREATE VIEW [dm_sales].[vw_dim_SalesEmployee]
AS 
SELECT
          [PartnerFunction]
        , [PartnerFunctionName]
        , [AddressID]
        , [Customer]
        , [Personnel]
        , [FullName]
        , [CityName]
        , [StreetName]
        , [PostalCode]
        , [EmailAddress]
        , [PhoneNumber]
        , [MobilePhoneNumber] 
    FROM [edw].[dim_BillingDocumentPartnerFs]
    WHERE PartnerFunction = 'VE'
    GROUP BY
          [PartnerFunction]
        , [PartnerFunctionName]
        , [AddressID]
        , [Customer]
        , [Personnel]
        , [FullName]
        , [CityName]
        , [StreetName]
        , [PostalCode]
        , [EmailAddress]
        , [PhoneNumber]
        , [MobilePhoneNumber]
