CREATE VIEW [dm_sales].[vw_dim_ProductCalculated]
	AS 
SELECT 
        [ProductIDCalculated]
    ,   [ProductCalculated]
    ,   [ProductID_NameCalculated]
    ,   [ProductPillarIDCalculated] 
    ,   [ProductPillarCalculated] 
    ,   [ProductGroupIDCalculated]
    ,   [ProductGroupCalculated] 
    ,   [MainGroupIDCalculated] 
    ,   [MainGroupCalculated] 
    ,   [isReviewed] 
    ,   [mappingType] 
    ,   [axbiItemNo] 
    ,   [axbiItemName] 
    ,   [axbiProductPillarIDCalculated] 
    ,   [axbiProductPillarCalculated]
    ,   [axbiProductGroupIDCalculated] 
    ,   [axbiProductGroupCalculated] 
    ,   [axbiMainGroupIDCalculated] 
    ,   [axbiMainGroupCalculated]
    ,   [t_applicationId]   
    ,   [t_extractionDtm] 
FROM [edw].[dim_ProductCalculated]

UNION ALL

SELECT 
        [ProductIDCalculated]
    ,   [ProductCalculated]
    ,   [ProductID_NameCalculated]
    ,   [ProductPillarIDCalculated] 
    ,   [ProductPillarCalculated] 
    ,   [ProductGroupIDCalculated]
    ,   [ProductGroupCalculated] 
    ,   [MainGroupIDCalculated] 
    ,   [MainGroupCalculated] 
    ,   [isReviewed] 
    ,   [mappingType] 
    ,   [axbiItemNo] 
    ,   [axbiItemName] 
    ,   [axbiProductPillarIDCalculated] 
    ,   [axbiProductPillarCalculated]
    ,   [axbiProductGroupIDCalculated] 
    ,   [axbiProductGroupCalculated] 
    ,   [axbiMainGroupIDCalculated] 
    ,   [axbiMainGroupCalculated]
    ,   [t_applicationId]   
    ,   [t_extractionDtm] 
FROM [edw].[dim_ProductCalculated_US]
