CREATE VIEW [dm_sales].[vw_dim_Product] AS

SELECT
  P.[sk_dim_Product],
  P.[ProductID],
  P.[ProductExternalID],
  P.[Product],
  P.[ProductID_Name],
  P.[CreationDate],
  P.[MaterialTypeID],
  P.[MaterialType],
  P.[IsMarkedForDeletion],
  P.[CrossPlantStatusID],
  P.[CrossPlantStatus],
  P.[GrossWeight],
  P.[SourceOfSupply],
  P.[CountryOfOrigin],
  P.[CompetitorID],
  P.[ProductGroup] AS [MaterialGroup], -- So all PBI datasets keep working
  P.[BaseUnit],
  P.[ItemCategoryGroup],
  P.[ItemCategoryGroupName],
  P.[ProductHierarchy],
  P.[Product_L1_PillarID],
  P.[Product_L2_GroupID],
  P.[Product_L3_TypeID],
  P.[Product_L4_FamilyID],
  P.[Product_L5_SubFamilyID],
  P.[Product_L1_Pillar],
  P.[Product_L2_Group],
  P.[Product_L3_Type],
  P.[Product_L4_Family],
  P.[Product_L5_SubFamily],
  P.[ProductCategory],
  P.[Brand],
  P.[IndustryStandardName],
  P.[ProductStandardID],
  P.[InternationalArticleNumberCat],
  P.[ProductIsConfigurable],
  P.[IsBatchManagementRequired],
  P.[ExternalProductGroup],
  P.[CrossPlantConfigurableProduct],
  P.[ProductManufacturerNumber],
  P.[ManufacturerNumber],
  P.[MaximumPackagingLength],
  P.[MaximumPackagingWidth],
  P.[MaximumPackagingHeight],
  P.[MaximumCapacity],
  P.[OvercapacityTolerance],
  P.[UnitForMaxPackagingDimensions],
  P.[BaseUnitSpecificProductLength],
  P.[BaseUnitSpecificProductWidth],
  P.[BaseUnitSpecificProductHeight],
  P.[ArticleCategory],
  P.[ProductIsLocked],
  P.[BasicMaterial],
  P.[SalesProduct],
  P.[NetWeight],
  P.[IndustrySector],
  P.[WeightUnit],
  P.[Division],
  P.[TransportationGroup],
  P.[EClassCode],                 
  P.[EClassCategory],             
  P.[EClassCategoryDescription],  
  P.[Category_L1],
  P.[Category_L2],
  P.[Category_L3],
  P.[Category_L4],
  P.[Classification], 
  P.[ZZ1_CustomFieldRiskMit_PRD],
  P.[ZZ1_CustomFieldHighRis_PRD],
  P.[ZZ1_CustomFieldRiskRea_PRD],
  P.[CreatedByUser],
  P.[t_jobDtm],
  P.[t_applicationId],
  P.[t_extractionDtm]
FROM
  [edw].[dim_Product] P

UNION ALL

SELECT
  [ProductID] AS [sk_dim_Product],
  [ProductID],
  [ProductExternalID],
  [Product],
  [ProductID_Name],
  NULL AS [CreationDate],
  [MaterialTypeID],
  [MaterialType],
  NULL AS [IsMarkedForDeletion],
  NULL AS [CrossPlantStatusID],
  NULL AS [CrossPlantStatus],
  NULL AS [GrossWeight],
  NULL AS [SourceOfSupply],
  NULL AS [CountryOfOrigin],
  NULL AS [CompetitorID],
  NULL AS [MaterialGroup],
  NULL AS [BaseUnit],
  NULL AS [ItemCategoryGroup],
  NULL AS [ItemCategoryGroupName],
  [ProductHierarchy],
  [Product_L1_PillarID],
  [Product_L2_GroupID],
  [Product_L3_TypeID],
  [Product_L4_FamilyID],
  [Product_L5_SubFamilyID],
  [Product_L1_Pillar],
  [Product_L2_Group],
  [Product_L3_Type],
  [Product_L4_Family],
  [Product_L5_SubFamily],
  NULL AS [ProductCategory],
  NULL AS [Brand],
  NULL AS [IndustryStandardName],
  NULL AS [ProductStandardID],
  NULL AS [InternationalArticleNumberCat],
  NULL AS [ProductIsConfigurable],
  NULL AS [IsBatchManagementRequired],
  NULL AS [ExternalProductGroup],
  NULL AS [CrossPlantConfigurableProduct],
  NULL AS [ProductManufacturerNumber],
  NULL AS [ManufacturerNumber],
  NULL AS [MaximumPackagingLength],
  NULL AS [MaximumPackagingWidth],
  NULL AS [MaximumPackagingHeight],
  NULL AS [MaximumCapacity],
  NULL AS [OvercapacityTolerance],
  NULL AS [UnitForMaxPackagingDimensions],
  NULL AS [BaseUnitSpecificProductLength],
  NULL AS [BaseUnitSpecificProductWidth],
  NULL AS [BaseUnitSpecificProductHeight],
  NULL AS [ArticleCategory],
  NULL AS [ProductIsLocked],
  NULL AS [BasicMaterial],
  NULL AS [SalesProduct],
  NULL AS [NetWeight],
  NULL AS [IndustrySector],
  NULL AS [WeightUnit],
  NULL AS [Division],
  NULL AS [TransportationGroup],
  NULL AS [EClassCode],                 
  NULL AS [EClassCategory],             
  NULL AS [EClassCategoryDescription], 
  NULL AS [Category_L1],
  NULL AS [Category_L2],
  NULL AS [Category_L3],
  NULL AS [Category_L4],
  NULL AS [Classification], 
  NULL AS [ZZ1_CustomFieldRiskMit_PRD],
  NULL AS [ZZ1_CustomFieldHighRis_PRD],
  NULL AS [ZZ1_CustomFieldRiskRea_PRD],
  NULL AS [CreatedByUser],
  [t_jobDtm],
  [t_applicationId],
  [t_extractionDtm]
FROM
  [edw].[dim_AXProductSAPHierarchy]
