CREATE VIEW [dm_sales].[vw_dim_SAPItemNumberBasicMappingTable]
    AS    
SELECT
        [AXItemnumber]
    ,   [axbi_ItemNoCalc]
    ,   [AXDataAreaId]
    ,   [AXDataAreaId_Original]
    ,   [SAPProductID]
    ,   [SAPItemnumber]
    ,   [SAPMaterialtype]
    ,   [Migrate]
    ,   [SAPshortdescription]
    ,   [VALUATIONCLASS]
    ,   [VALUATIONCLASSCH01]
    ,   [VALUATIONCLASSDE01]
    ,   [VALUATIONCLASSDE02]
    ,   [VALUATIONCLASSPL01]
    ,   [Wave]
    ,   [t_applicationId]
    ,   [t_extractionDtm]
FROM [edw].[dim_SAPItemNumberBasicMappingTable]