CREATE VIEW [dm_sales].[vw_dim_SalesDocumentScheduleLine]
	AS SELECT
		[SalesDocumentID]
		,[SalesDocumentItem]
		,[ScheduleLine]
		,[ScheduleLineCategory]
		,[OrderQuantityUnit]
		,[IsRequestedDelivSchedLine]
		,[RequestedDeliveryDate]
		,[ScheduleLineOrderQuantity]
		,[CorrectedQtyInOrderQtyUnit]
		,[IsConfirmedDelivSchedLine]
		,[ConfirmedDeliveryDate]
		,[ConfdOrderQtyByMatlAvailCheck]
		,[ConfdSchedLineReqdDelivDate]
		,[ProductAvailabilityDate]
		,[ScheduleLineConfirmationStatus]
		,[PlannedOrder]
		,[OrderID]
		,[DeliveryCreationDate]
		,[GoodsIssueDate]
		,[LoadingDate]
		,[ItemIsDeliveryRelevant]
		,[DelivBlockReasonForSchedLine]
		,[DeliveredQtyInOrderQtyUnit]
		,[DeliveredQuantityInBaseUnit]
		,[SalesOrganizationID]
		,[MaterialID]
		,[SoldToPartyID]
		,[SalesDocumentDate]
FROM [edw].[dim_SalesDocumentScheduleLine]