CREATE VIEW [dm_sales].[vw_dim_SalesEmployee]
AS 
SELECT
          [SDDocument]
        , [PartnerFunction]
        , [PartnerFunctionName]
        , [AddressID]
        , [Customer]
        , [Personnel]
        , [FullName]
        , [CityName]
        , [StreetName]
        , [PostalCode]
        , [EmailAddress]
        , [PhoneNumber]
        , [MobilePhoneNumber]
        , [t_applicationId]
        , [t_extractionDtm]
    FROM [base_s4h_cax].[C_BillingDocumentPartnerFs]
    WHERE PartnerFunction = 'VE'
    GROUP BY
          [SDDocument]
        , [PartnerFunction]
        , [PartnerFunctionName]
        , [AddressID]
        , [Customer]
        , [Personnel]
        , [FullName]
        , [CityName]
        , [StreetName]
        , [PostalCode]
        , [EmailAddress]
        , [PhoneNumber]
        , [MobilePhoneNumber]
        , [t_applicationId]
        , [t_extractionDtm]