CREATE VIEW [dm_sales].[vw_fact_PurchasingDocument]
AS
SELECT
  [PurchasingDocument],
  [SupplierID],
  [PurchasingDocumentCategoryID],
  [PurchasingDocumentCategory],
  [PurchasingDocumentTypeID],
  [PurchasingDocumentType],
  [CreationDate],
  [CreatedByUser],
  [PurchasingDocumentOrderDate],
  [PurchasingOrganizationID],
  [PurchasingOrganization],
  [PurchasingGroupID],
  [PurchasingGroup],
  [SupplyingPlantID],
  [CompanyCodeID],
  [PurchasingProcessingStatusID],
  [PurchasingDocumentStatus],
  [t_applicationId],
  [t_extractionDtm]
FROM
  [edw].[vw_fact_PurchasingDocument]
