CREATE VIEW [dm_sales].[vw_fact_ProductSalesDelivery] 
    AS 
    SELECT 
        [sk_ProductSalesDelivery]
        --   ,[nk_ProductSalesDelivery]
        ,[ProductID]
        ,[SalesOrganizationID]
        ,[DistributionChannelID]
        --   ,[Product]
        --   ,[SalesOrganization]
        ,[DistributionChannel]
        ,[MinimumOrderQuantity]
        ,[SupplyingPlant]
        ,[PriceSpecificationProductGroup]
        ,[AccountDetnProductGroup]
        ,[DeliveryNoteProcMinDelivQty]
        ,[ItemCategoryGroup]
        ,[DeliveryQuantityUnit]
        ,[DeliveryQuantity]
        ,[ProductSalesStatus]
        ,[ProductSalesStatusValidityDate]
        ,[SalesMeasureUnit]
        ,[IsMarkedForDeletion]
        --   ,[ProductHierarchy]
        --   ,[FirstSalesSpecProductGroup]
        --   ,[SecondSalesSpecProductGroup]
        --   ,[ThirdSalesSpecProductGroup]
        --   ,[FourthSalesSpecProductGroup]
        --   ,[FifthSalesSpecProductGroup]
        --   ,[MinimumMakeToOrderOrderQty]
        --   ,[LogisticsStatisticsGroup]
        --   ,[VolumeRebateGroup]
        --   ,[ProductCommissionGroup]
        --   ,[CashDiscountIsDeductible]
        --   ,[PricingReferenceProduct]
        --   ,[AssortmentGrade]
        --   ,[StoreListingProcedure]
        --   ,[DistrCntrListingProcedure]
        --   ,[StoreListingStartDate]
        --   ,[StoreListingEndDate]
        --   ,[DistrCntrListingStartDate]
        --   ,[DistrCntrListingEndDate]
        --   ,[StoreSaleStartDate]
        --   ,[StoreSaleEndDate]
        --   ,[DistrCntrSaleStartDate]
        --   ,[DistrCntrSaleEndDate]
        --   ,[RoundingProfile]
        --   ,[ProductUnitGroup]
        --   ,[MaxDeliveryQtyStoreOrder]
        --   ,[PriceFixingCategory]
        --   ,[VariableSalesUnitIsNotAllowed]
        --   ,[CompetitionPressureCategory]
        --   ,[ProductHasAttributeID01]
        --   ,[ProductHasAttributeID02]
        --   ,[ProductHasAttributeID03]
        --   ,[ProductHasAttributeID04]
        --   ,[ProductHasAttributeID05]
        --   ,[ProductHasAttributeID06]
        --   ,[ProductHasAttributeID07]
        --   ,[ProductHasAttributeID08]
        --   ,[ProductHasAttributeID09]
        --   ,[ProductHasAttributeID10]
        --   ,[IsActiveEntity]
        --   ,[ProdExtAssortmentPriority]
        --   ,[SubscrpnContrDfltDuration]
        --   ,[SubscrpnContrAltvDuration1]
        --   ,[SubscrpnContrAltvDuration2]
        --   ,[SubscrpnContrDurationUnit]
        --   ,[SubscrpnContrDfltExtnDurn]
        --   ,[SubscrpnContrAltvExtnDurn1]
        --   ,[SubscrpnContrAltvExtnDurn2]
        --   ,[SubscrpnContrExtnDurnUnit]
        ,[IsConfigurable]
        ,[t_applicationId]
        --   ,[t_jobId]
        ,[t_jobDtm]         AS [t_extractionDtm]
        --   ,[t_lastActionCd]
        --   ,[t_jobBy]
    FROM [edw].[dim_ProductSalesDelivery]
