CREATE VIEW [dm_sales].[vw_fact_SalesOrderItem_narrow]
AS
SELECT
    SOI.[SalesOrderID]
    ,SOI.[SalesOrderItemID]
    ,SOI.[CreationDate]             AS [SalesOrderCreationDate]
    ,SOI.[BillingDocumentDate]
    ,SOI.[CurrencyType]
    ,SOI.[SalesDocumentType]
    ,SOI.[MaterialID]
    ,SOI.[OrderQuantity]
    ,SOI.[OrderQuantityUnitID]
    ,SOI.[CurrencyID]
    ,SOI.[InOutID]
    ,SOI.[SalesOrganizationID]
    ,SOI.[RequestedDeliveryDate]
    ,SOI.[ActualDeliveredQuantityInBaseUnit]
    ,SOI.[BillingQuantityInBaseUnit]
    ,SOI.[ActualDeliveredQuantityIBUOverall]
    ,SOI.[BillingQuantityIBUOverall]
    ,SOI.[OrderStatus]
    ,SOI.[ItemOrderStatus]
    ,SOI.[OrderType]
    ,SOI.[ItemDeliveryStatus]    
    ,SOI.[OverallDeliveryStatus]
    ,SOI.[ShippingConditionID]
    ,SOI.[ScheduleLineCategory]
    ,BDI.[BillingDocument]                      
    ,BDI.[BillingDocumentItem]                  
    ,BDI.[CurrencyTypeID]      
    ,BDI.[BillingDocumentTypeID]                
    ,BDI.[BillingDocumentCategoryID]            
    ,BDI.[SDDocumentCategoryID]                 
    ,BDI.[CreationDate]             AS [BillingDocumentCreationDate]                    
    ,BDI.[CreationTime]             AS [BillingDocumentCreationTime]                                           
    ,BDI.[BillingDocumentIsTemporary]           
    ,BDI.[ProductSurrogateKey]                      
    ,BDI.[BillingDocumentIsCancelled]           
    ,BDI.[CancelledBillingDocument]             
    ,BDI.[CancelledInvoiceEffect]                     
    ,BDI.[BillingQuantity]                      
    ,BDI.[BillingQuantityUnitID]                
    ,BDI.[BillingQuantityInBaseUnit]    AS [BillingDocumentQuantityIBU]                           
    ,BDI.[MRPRequiredQuantityInBaseUnit]                 
    ,BDI.[ItemGrossWeight]                      
    ,BDI.[ItemNetWeight]                      
    ,BDI.[ItemVolume]                           
    ,BDI.[NetAmount]                       
    ,BDI.[GrossAmount]                            
    ,BDI.[TaxAmount]                            
    ,BDI.[CostAmount]              
    ,BDI.[OriginSDDocument]                     
    ,BDI.[OriginSDDocumentItem]         
    ,BDI.[ReferenceSDDocument]      AS [BillingDocumentReferenceDocument]                
    ,BDI.[ReferenceSDDocumentItem]  AS [BillingDocumentReferenceDocumentItem]            
    ,BDI.[ReferenceSDDocumentCategoryID]    AS [BillingDocumentReferenceDocumentCategoryID]       
    ,BDI.[SalesDocumentID]                      
    ,BDI.[SalesDocumentItemID]                  
    ,BDI.[SalesSDDocumentCategoryID]                            
    ,BDI.[BillingDocumentType]    
    ,BDI.[SDDocumentCategory]     
    ,BDI.[BillingDocumentCategory]
    ,ODI.[OutboundDelivery]
    ,ODI.[OutboundDeliveryItem]
    ,ODI.[DeliveryDocumentItemCategoryID]
    ,ODI.[SalesDocumentItemTypeID]
    ,ODI.[CreatedByUserID]
    ,ODI.[CreationDate]             AS [OutboundDeliveryCreationDate]
    ,ODI.[CreationTime]             AS [OutboundDeliveryCreationTime]
    ,ODI.[DistributionChannelID]
    ,ODI.[ProductID]
    ,ODI.[OriginallyRequestedMaterialID]
    ,ODI.[ProductGroupID]
    ,ODI.[ActualDeliveredQtyInBaseUnit]
    ,ODI.[ReferenceSDDocument]      AS [OutboundDeliveryReferenceDocument]
    ,ODI.[ReferenceSDDocumentItem]  AS [OutboundDeliveryReferenceDocumentItem]
    ,ODI.[ReferenceSDDocumentCategoryID]    AS [OutboundDeliveryReferenceDocumentCategoryID]
FROM [dm_sales].[vw_fact_SalesOrderItem] SOI
LEFT JOIN [edw].[vw_BillingDocumentItem_for_SalesDocumentItem] BDI
    ON SOI.SalesOrderID = BDI.SalesDocumentID
    AND SOI.SalesOrderItemID = BDI.SalesDocumentItemID
    AND SOI.CurrencyTypeID = BDI.CurrencyTypeID
LEFT JOIN [edw].[vw_OutboundDeliveryItem_for_SalesDocumentItem] ODI
    ON SOI.SalesOrderID = ODI.ReferenceSDDocument
    AND SOI.SalesOrderItemID = ODI.ReferenceSDDocumentItem
WHERE [SDDocumentRejectionStatus] <> 'Fully Rejected'