CREATE VIEW [dm_sales].[vw_fact_OpportunityCollection]
AS
SELECT
        [ObjectID]
    ,   [ProcessingTypeID]
    ,   [ProcessingType]
    ,   [ProspectPartyCustomerID]
    ,   [C4C_ProjectName]
    ,   [OriginTypeID]
    ,   [OriginType]
    ,   [ExternalUserStatusID]
    ,   [ExternalUserStatus]
    ,   [ResultReasonID]
    ,   [ResultReason]
    ,   [ExpectedRevenueAmount]
    ,   [ExpectedRevenueAmountCurrencyID]
    ,   [WeightedExpectedNetAmount]
    ,   [WeightedExpectedNetAmountCurrencyID]
    ,   [SalesOrganisationID]
    ,   [DistributionChannelID]
    ,   [ProspectPartyCustomer]
    ,   [Zopptype_KUTID]
    ,   [Zopptype_KUT]
    ,   [ZprojectParentID]
    ,   [t_applicationId]
    ,   [t_extractionDtm]
FROM
    [edw].[fact_OpportunityCollection]