CREATE VIEW [dm_sales].[vw_fact_ManufacturingOrder]
AS
SELECT
        [ManufacturingOrder]
    ,   [ManufacturingOrderCategoryID]
    ,   [ManufacturingOrderCategory]
    ,   [ManufacturingOrderOperation]
    ,   [OpActualExecutionStartDate]
    ,   [OpActualExecutionStartTime]
    ,   [OpActualExecutionEndDate]
    ,   [OpActualExecutionEndTime]
    ,   [OrderIsDelivered]
    ,   [OrderIsPartiallyDelivered]
    ,   [SalesOrder]
    ,   [SalesOrderItem]
    ,   [HDR_ActualGoodsMovementDate]
    ,   [Material]
    ,   [MfgOrderPlannedTotalQty]
    ,   [MfgOrderPlannedScrapQty]
    ,   [MfgOrderConfirmedYieldQty]
    ,   [MfgOrderConfirmedScrapQty]
    ,   [ActualDeliveredQuantity]
    ,   [ProductConfiguration]
    ,   [WorkCenterID]
    ,   [WorkCenter]
    ,   [OrderIsClosed]
    ,   [OrderIsMarkedForDeletion]
    ,   [OrderIsCreated]
    ,   [OrderIsReleased]
    ,   [OrderIsPrinted]
    ,   [OrderIsConfirmed]
    ,   [OrderIsPartiallyConfirmed]
    ,   [OrderIsLocked]
    ,   [MfgOrderCreationDate]
    ,   [MfgOrderCreationTime]
    ,   [OpErlstSchedldExecStrtTme]
    ,   [OpErlstSchedldExecStrtDte]
    ,   [OpErlstSchedldExecEndDte]
    ,   [OpErlstSchedldExecEndTme]
    ,   [ProductionPlant]
    ,   [OperationUnit]
    ,   [t_applicationId]
    ,   [t_extractionDtm]
FROM
    [edw].[fact_ManufacturingOrder] MFGO