alter VIEW [dm_sales].[vw_fact_SalesOrderItem_narrow]
AS
SELECT
     SOI.[SalesOrderID]
    ,SOI.[SalesOrderItemID]
    ,SOI.[CreationDate]             AS [SalesOrderCreationDate]
    ,SOI.[BillingDocumentDate]
    ,SOI.[CurrencyType]
    ,SOI.[SalesDocumentType]
    ,SOI.[MaterialID]
    ,SOI.[OrderQuantity]
    ,SOI.[OrderQuantityUnitID]
    ,SOI.[CurrencyID]
    ,SOI.[InOutID]
    ,SOI.[SalesOrganizationID]
    ,SOI.[RequestedDeliveryDate]
    ,SOI.[ActualDeliveredQuantityInBaseUnit]
    ,SOI.[BillingQuantityInBaseUnit]
    ,SOI.[ActualDeliveredQuantityIBUOverall]
    ,SOI.[BillingQuantityIBUOverall]
    ,SOIC.[OrderStatus]
    ,SOIC.[ItemOrderStatus]
    ,SOI.[OrderType]
    ,SOI.[ItemDeliveryStatus]    
    ,SOI.[OverallDeliveryStatus]
    ,SOI.[ShippingConditionID]
    ,SOI.[NetAmount] as SOI_NetAmount
    ,SOIC.[BillingDocument]                      
    ,SOIC.[BillingDocumentItem]                  
    ,SOIC.[CurrencyTypeID]      
    ,SOIC.[BillingDocumentTypeID]                
    ,SOIC.[BillingDocumentCategoryID]            
    ,SOIC.[SDDocumentCategoryID]                 
    ,SOIC.[BillingDocumentCreationDate]                    
    ,SOIC.[BillingDocumentCreationTime]                                           
    ,SOIC.[BillingDocumentIsTemporary]           
    ,SOIC.[ProductSurrogateKey]                      
    ,SOIC.[BillingDocumentIsCancelled]           
    ,SOIC.[CancelledBillingDocument]             
    ,SOIC.[CancelledInvoiceEffect]                     
    ,SOIC.[BillingQuantity]                      
    ,SOIC.[BillingQuantityUnitID]                
    ,SOIC.[BillingDocumentQuantityIBU]                           
    ,SOIC.[MRPRequiredQuantityInBaseUnit]                 
    ,SOIC.[ItemGrossWeight]                      
    ,SOIC.[ItemNetWeight]                      
    ,SOIC.[ItemVolume]                           
    ,SOIC.[NetAmount]                       
    ,SOIC.[GrossAmount]                            
    ,SOIC.[TaxAmount]                            
    ,SOIC.[CostAmount]              
    ,SOIC.[OriginSDDocument]                     
    ,SOIC.[OriginSDDocumentItem]         
    ,SOIC.[BillingDocumentReferenceDocument]                
    ,SOIC.[BillingDocumentReferenceDocumentItem]            
    ,SOIC.[BillingDocumentReferenceDocumentCategoryID]       
    ,SOIC.[SalesDocumentID]                      
    ,SOIC.[SalesDocumentItemID]                  
    ,SOIC.[SalesSDDocumentCategoryID]                            
    ,SOIC.[BillingDocumentType]    
    ,SOIC.[SDDocumentCategory]     
    ,SOIC.[BillingDocumentCategory]
    ,ODI.[OutboundDelivery]
    ,ODI.[OutboundDeliveryItem]
    ,ODI.[DeliveryDocumentItemCategoryID]
    ,ODI.[SalesDocumentItemTypeID]
    ,ODI.[CreatedByUserID]
    ,ODI.[CreationDate]             AS [OutboundDeliveryCreationDate]
    ,ODI.[CreationTime]             AS [OutboundDeliveryCreationTime]
    ,ODI.[DistributionChannelID]
    ,ODI.[ProductID]
    ,ODI.[OriginallyRequestedMaterialID]
    ,ODI.[ProductGroupID]
    ,ODI.[ActualDeliveredQtyInBaseUnit]
    ,ODI.[ReferenceSDDocument]      AS [OutboundDeliveryReferenceDocument]
    ,ODI.[ReferenceSDDocumentItem]  AS [OutboundDeliveryReferenceDocumentItem]
    ,ODI.[ReferenceSDDocumentCategoryID]    AS [OutboundDeliveryReferenceDocumentCategoryID]
    ,SOIC.[ScheduleLine]
    ,SOIC.[ScheduleLineCategory]
    ,SOIC.[OrderQuantityUnit]
    ,SOIC.[IsRequestedDelivSchedLine]
    ,SOIC.[ScheduleLineOrderQuantity]
    ,SOIC.[CorrectedQtyInOrderQtyUnit]
    ,SOIC.[IsConfirmedDelivSchedLine]
    ,SOIC.[ConfirmedDeliveryDate]
    ,SOIC.[ScheduleLineConfirmationStatus]
    ,SOIC.[DeliveredQtyInOrderQtyUnit]
    ,SOIC.[DeliveredQuantityInBaseUnit]
    ,SOIC.[ConfdOrderQtyByMatlAvailCheck]
    ,SOIC.[ExpectedDeliveryDate]
FROM [dm_sales].[vw_fact_SalesOrderItem] SOI
INNER JOIN [edw].[vw_SalesOrderItem_combined] SOIC
    ON  SOI.SalesOrderID = SOIC.SalesDocument
    AND SOI.SalesOrderItemID = SOIC.SalesDocumentItem
LEFT JOIN [edw].[vw_OutboundDeliveryItem_for_SalesDocumentItem] ODI
    ON SOI.SalesOrderID = ODI.ReferenceSDDocument
    AND SOI.SalesOrderItemID = ODI.ReferenceSDDocumentItem
