CREATE VIEW [dm_sales].[vw_fact_MaterialDocumentItem]
	AS 
SELECT 
  MDI.[MaterialDocumentYear]
, MDI.[MaterialDocument]
, MDI.[MaterialDocumentItem]
, MDI.[MaterialID]
, MDI.[PlantID]
, MDI.[StorageLocationID]
, MDI.[StorageTypeID]
, MDI.[StorageBin]
, MDI.[Batch]
, MDI.[ShelfLifeExpirationDate]
, MDI.[ManufactureDate]
, MDI.[SupplierID]
, MDI.[SalesOrder]
, MDI.[SalesOrderItem]
, MDI.[SalesOrderScheduleLine]
, MDI.[WBSElementInternal]
, MDI.[CustomerID]
, MDI.[InventorySpecialStockTypeID]
, MDI.[InventoryStockTypeID]
, MDI.[StockOwner]
, MDI.[GoodsMovementTypeID]
, MDI.[DebitCreditCode]
, MDI.[InventoryUsabilityCode]
, MDI.[QuantityInBaseUnit]
, MDI.[MaterialBaseUnitID]
, MDI.[QuantityInEntryUnit]
, MDI.[EntryUnitID]
, MDI.[HDR_PostingDate]
, MDI.[DocumentDate]
, MDI.[TotalGoodsMvtAmtInCCCrcy]
, MDI.[CompanyCodeCurrency]
, MDI.[InventoryValuationTypeID]
, MDI.[ReservationIsFinallyIssued]
, MDI.[PurchaseOrder]
, MDI.[PurchaseOrderItem]
, MDI.[ProjectNetwork]
, MDI.[Order]
, MDI.[OrderItem]
, MDI.[Reservation]
, MDI.[ReservationItem]
, MDI.[DeliveryDocument]
, MDI.[DeliveryDocumentItem]
, MDI.[ReversedMaterialDocumentYear]
, MDI.[ReversedMaterialDocument]
, MDI.[ReversedMaterialDocumentItem]
, MDI.[RvslOfGoodsReceiptIsAllowed]
, MDI.[GoodsRecipientName]
, MDI.[UnloadingPointName]
, MDI.[CostCenterID]
, MDI.[GLAccountID]
, MDI.[ServicePerformer]
, MDI.[EmploymentInternal]
, MDI.[AccountAssignmentCategory]
, MDI.[WorkItem]
, MDI.[ServicesRenderedDate]
, MDI.[IssgOrRcvgMaterial]
, MDI.[CompanyCodeID]
, MDI.[GoodsMovementRefDocTypeID]
, MDI.[IsAutomaticallyCreated]
, MDI.[IsCompletelyDelivered]
, MDI.[IssuingOrReceivingPlantID]
, MDI.[IssuingOrReceivingStorageLocID]
, MDI.[BusinessAreaID]
, MDI.[ControllingAreaID]
, MDI.[FiscalYearPeriod]
, MDI.[FiscalYearVariant]
, MDI.[IssgOrRcvgBatch]
, MDI.[IssgOrRcvgSpclStockInd]
, MDI.[MaterialDocumentItemText]
, MDI.[CurrencyTypeID]
, MDI.[HDR_AccountingDocumentTypeID]
, MDI.[HDR_InventoryTransactionType]
, MDI.[HDR_CreatedByUser]
, MDI.[HDR_CreationDate]
, MDI.[HDR_CreationTime]
, MDI.[HDR_MaterialDocumentHeaderText]
, MDI.[HDR_ReferenceDocument]
, MDI.[HDR_BillOfLading]
, SDT.[SalesDocumentTypeID]
, SDT.[SalesDocumentType]  
, MDI.[t_applicationId]
, MDI.[t_extractionDtm]
FROM [edw].[fact_MaterialDocumentItem] MDI
LEFT JOIN [edw].[fact_SalesDocumentItem] SDI
  ON MDI.[SalesOrder] = SDI.[SalesDocument] collate Latin1_General_100_BIN2
     AND
     MDI.[SalesOrderItem] = SDI.[SalesDocumentItem]
     AND
     SDI.[CurrencyTypeID] = 10
LEFT JOIN [edw].[dim_SalesDocumentType] SDT
  ON SDI.[SalesDocumentTypeID] = SDT.[SalesDocumentTypeID]
