CREATE VIEW [dm_sales].[vw_fact_SalesOrderItem_ODI]
AS
SELECT
    [OutboundDelivery]
    ,[OutboundDeliveryItem]
    ,[DeliveryDocumentItemCategoryID]
    ,[SalesDocumentItemTypeID]
    ,[CreatedByUserID]
    ,[CreationDate]
    ,[CreationTime]
    ,[LastChangeDate]
    ,[DistributionChannelID]
    ,[ProductID]
    ,[OriginallyRequestedMaterialID]
    ,[ProductGroupID]
    ,[ActualDeliveredQtyInBaseUnit]
    ,[ReferenceSDDocument]
    ,[ReferenceSDDocumentItem]
    ,[ReferenceSDDocumentCategoryID]
FROM [edw].[vw_OutboundDeliveryItem_for_SalesDocumentItem]