CREATE VIEW [dm_sales].[vw_fact_PurchasingDocumentItem]
AS
SELECT
  [sk_fact_PurchasingDocumentItem],
  [PurchasingDocument],
  [PurchasingDocumentItem],
  [MaterialID],
  [DocumentCurrencyID],
  [PlantID],
  [CompanyCodeID],
  [MaterialGroupID],
  [PurchaseContract],
  [PurchaseContractItem],
  [NetAmount],
  [PurchaseOrderQuantity],
  [StorageLocationID],
  [OrderPriceUnit],
  [NetPriceAmount],
  [NetPriceQuantity],
  [PurchasingDocumentItemCategoryID],
  [NextDeliveryOpenQuantity],
  [NextDeliveryDate],
  [IsCompletelyDelivered],
  [OrderQuantityUnit],
  [CostCenterID],
  [GLAccount],
  [GoodsReceiptQuantity],
  [OrderQuantityUnit],
  fact_PDI.[t_applicationId],
  fact_PDI.[t_extractionDtm]
FROM
  [edw].[fact_PurchasingDocumentItem] fact_PDI
