CREATE VIEW [dm_sales].[vw_fact_SalesOrderItem_narrow]
AS
SELECT
     SOI.[SalesOrderID]
    ,SOI.[SalesOrderItemID]
    ,SOI.[CreationDate] AS SalesOrderCreationDate
    ,SOI.[BillingDocumentDate]
    ,SOI.[CurrencyType]
    ,SOI.[SalesDocumentType]
    ,SOI.[MaterialID]
    ,SOI.[OrderQuantity]
    ,SOI.[OrderQuantityUnitID]
    ,SOI.[CurrencyID]
    ,SOI.[InOutID]
    ,SOI.[SalesOrganizationID]
    ,SOI.[RequestedDeliveryDate]
    ,SOI.[ActualDeliveredQuantityInBaseUnit]
    ,SOI.[BillingQuantityInBaseUnit]
    ,SOI.[ActualDeliveredQuantityIBUOverall]
    ,SOI.[BillingQuantityIBUOverall]
    ,SOI.[OrderStatus]
    ,SOI.[ItemOrderStatus]
    ,SOI.[OrderType]
    ,SOI.[ItemDeliveryStatus]    
    ,SOI.[OverallDeliveryStatus]
    ,SOI.[ShippingConditionID]
    ,SOI.[NetAmount] as SOI_NetAmount
    ,SOI.[BillingDocument]                      
    ,SOI.[BillingDocumentItem]                  
    ,SOI.[CurrencyTypeID]
    ,SOI.[BillingDocumentTypeID]                
    ,SOI.[BillingDocumentCategoryID]            
    ,SOI.[SDDocumentCategoryID]
    ,SOI.[BillingDocumentCreationDate]                   
    ,SOI.[BillingDocumentCreationTime]                                           
    ,SOI.[BillingDocumentIsTemporary]           
    ,SOI.[ProductSurrogateKey]                 
    ,SOI.[BillingDocumentIsCancelled]           
    ,SOI.[CancelledBillingDocument]             
    ,SOI.[CancelledInvoiceEffect]                     
    ,SOI.[BillingQuantity]                      
    ,SOI.[BillingQuantityUnitID]                
    ,SOI.[BillingDocumentQuantityIBU]                           
    ,SOI.[MRPRequiredQuantityInBaseUnit]                 
    ,SOI.[ItemGrossWeight]                      
    ,SOI.[ItemNetWeight]                      
    ,SOI.[ItemVolume]                           
    ,SOI.[NetAmount]                       
    ,SOI.[GrossAmount]                            
    ,SOI.[TaxAmount] 
    ,SOI.[SOI_CostAmount]   AS CostAmount                                    
    ,SOI.[OriginSDDocument]                     
    ,SOI.[OriginSDDocumentItem]         
    ,SOI.[BillingDocumentReferenceDocument]                
    ,SOI.[BillingDocumentReferenceDocumentItem]            
    ,SOI.[BillingDocumentReferenceDocumentCategoryID]       
    ,SOI.[SalesDocumentID]                      
    ,SOI.[SalesDocumentItemID]                  
    ,SOI.[SalesSDDocumentCategoryID]                            
    ,SOI.[BillingDocumentType]    
    ,SOI.[BillingDocumentSDDocumentCategory]  AS SDDocumentCategory
    ,SOI.[BillingDocumentCategory]
    ,ODI.[OutboundDelivery]
    ,ODI.[OutboundDeliveryItem]
    ,ODI.[DeliveryDocumentItemCategoryID]
    ,ODI.[SalesDocumentItemTypeID]
    ,ODI.[CreatedByUserID]
    ,ODI.[CreationDate]             AS [OutboundDeliveryCreationDate]
    ,ODI.[CreationTime]             AS [OutboundDeliveryCreationTime]
    ,ODI.[DistributionChannelID]    AS [OutboundDeliveryDistributionChannelID]
    ,ODI.[ProductID]
    ,ODI.[OriginallyRequestedMaterialID]
    ,ODI.[ProductGroupID]
    ,ODI.[ActualDeliveredQtyInBaseUnit]
    ,ODI.[ReferenceSDDocument]      AS [OutboundDeliveryReferenceDocument]
    ,ODI.[ReferenceSDDocumentItem]  AS [OutboundDeliveryReferenceDocumentItem]
    ,ODI.[ReferenceSDDocumentCategoryID]    AS [OutboundDeliveryReferenceDocumentCategoryID]
    ,SOI.[ScheduleLine]
    ,SOI.[ScheduleLineCategory]
    ,SOI.[OrderQuantityUnit]
    ,SOI.[IsRequestedDelivSchedLine]
    ,SOI.[ScheduleLineOrderQuantity]
    ,SOI.[CorrectedQtyInOrderQtyUnit]
    ,SOI.[IsConfirmedDelivSchedLine]
    ,SOI.[ConfirmedDeliveryDate]
    ,SOI.[ScheduleLineConfirmationStatus]
    ,SOI.[DeliveredQtyInOrderQtyUnit]
    ,SOI.[DeliveredQuantityInBaseUnit]
    ,SOI.[ConfdOrderQtyByMatlAvailCheck]
    ,SOI.[ExpectedDeliveryDate]
FROM [dm_sales].[vw_fact_SalesOrderItem_combined] SOI
LEFT JOIN [edw].[vw_OutboundDeliveryItem_for_SalesDocumentItem] ODI
    ON SOI.SalesOrderID = ODI.ReferenceSDDocument
    AND SOI.SalesOrderItemID = ODI.ReferenceSDDocumentItem

