CREATE TABLE [base_c4c].[Opportunity]
(
    [ObjectID]                                      NVARCHAR(70)    NOT NULL,
    [ProcessingTypeCode]                            NVARCHAR(4)     NULL,
    /*[ProcessingTypeCodeText]
    [ID
    [ExternalID
    [UUID
    [ProspectPartyID
    [Name
    [PrimaryContactPartyID
    [PriorityCode
    [PriorityCodeText
    [OriginTypeCode
    [OriginTypeCodeText
    [LifeCycleStatusCode
    [LifeCycleStatusCodeText
    [ExternalUserStatusCode
    [ExternalUserStatusCodeText
    [ResultReasonCode
    [ResultReasonCodeText
    [SalesCycleCode
    [SalesCycleCodeText
    [SalesCyclePhaseCode
    [SalesCyclePhaseCodeText
    [ProcessStatusValidSinceDate
    [SalesCyclePhaseStartDate
    [ProbabilityPercent
    [HeaderRevenueSchedule
    [SalesRevenueForecastRelevanceIndicator
    [ExpectedRevenueAmount
    [ExpectedRevenueAmountCurrencyCode
    [ExpectedRevenueAmountCurrencyCodeText
    [TotalExpectedNetAmount
    [TotalExpectedNetAmountAmountCurrencyCode
    [TotalExpectedNetAmountAmountCurrencyCodeText
    [WeightedExpectedNetAmount
    [WeightedExpectedNetAmountCurrencyCode
    [WeightedExpectedNetAmountCurrencyCodeText
    [ExpectedProcessingStartDate
    [ExpectedProcessingEndDate
    [ExpectedRevenueStartDate
    [ExpectedRevenueEndDate
    [SalesForecastCategoryCode
    [SalesForecastCategoryCodeText
    [GroupCode
    [GroupCodeText
    [SalesUnitPartyID
    [SalesOrganisationID
    [DistributionChannelCode
    [DistributionChannelCodeText
    [DivisionCode
    [DivisionCodeText
    [SalesOfficeID
    [SalesGroupID
    [SalesTerritoryID
    [MainEmployeeResponsiblePartyID
    [EndBuyerPartyID
    [ProductRecepientPartyID
    [ApproverPartyID
    [PayerPartyID
    [BillToPartyID
    [SellerPartyID
    [PhaseProgressEvaluationStatusCode
    [PhaseProgressEvaluationStatusCodeText
    [ProspectBudgetAmount
    [ProspectBudgetAmountCurrencyCode
    [ProspectBudgetAmountCurrencyCodeText
    [Score
    [MainEmployeeResponsiblePartyName
    [SalesUnityPartyName
    [BillToPartyName
    [ProductRecipientPartyName
    [SellerPartyName
    [PayerPartyName
    [EndBuyerPartyName
    [PrimaryContactPartyName
    [ProspectPartyName
    [ApproverPartyName
    [SalesOrganisationName
    [SalesOfficeName
    [SalesGroupName
    [SalesTerritoryName
    [ConsistencyStatusCode
    [ConsistencyStatusCodeText
    [ApprovalStatusCode
    [ApprovalStatusCodeText
    [CreationDate
    [LastChangeDate
    [CreationDateTime
    [LastChangeDateTime
    [CreatedBy
    [LastChangedBy
    [CreatedByUUID
    [LastChangedByUUID
    [EntityLastChangedOn
    [ETag
    [BestConnectedColleague
    [DealScore
    [DealScoreReason
    [FirstEmailReceivedOn
    [FirstEmailSentOn
    [LastDataHugSyncDateTime
    [LastEmailReceivedFrom
    [LastEmailReceivedOn
    [LastEmailSentBy
    [LastEmailSentOn
    [LastMeetingOn
    [NextMeetingOn
    [NumberOfColleagues
    [NumberOfMeetings
    [NumberOfOtherPeopleAtCompany
    [NumberOfReceivedEmails
    [NumberOfSentEmails
    [AutoCreateContacts
    [HugRank
    [ExternalProbabilityPercent
    [Zclassification_KUT
    [Zclassification_KUTText
    [Zexpectedorderdate_KUT
    [Zframe_KUT
    [Zframe_KUTText
    [Zinterproject_KUT
    [ZlegacyIDopp_KUT
    [Zleviatspecified_KUT
    [Zoppclosedate_KUT
    [Zoppstartdate_KUT
    [Zopptype_KUT
    [Zopptype_KUTText
    [Zparentopportunity_KUT
    [Zproductpillar_KUT
    [ZprojectID_KUT
    [Zprojectcountry_KUT
    [Zprojectcountry_KUTText
    [Zprojectdescription_KUT
    [Zprojectpostalcode_KUT
    [Zprojectstreet_KUT
    [Zprojecttype1_KUT
    [Zprojecttype1_KUTText
    [Zprojecttype2_KUT
    [Zprojecttype2_KUTText
    [Zprojetcity_KUT
    [Zsubmissiondate_KUT
    [Zuserquoterequestor_KUT
    [zbim_KUT
    [zbim_KUTText]*/
    [t_applicationId]   VARCHAR(32)    NULL,
    [t_jobId]           VARCHAR(36)    NULL,
    [t_jobDtm]          DATETIME,
    [t_jobBy]           NVARCHAR(128)  NULL,
    [t_extractionDtm]   DATETIME,
    [t_filePath]        NVARCHAR(1024) NULL
    ,CONSTRAINT [PK_Opprotunity] PRIMARY KEY NONCLUSTERED ([ObjectID]) NOT ENFORCED
)
    WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);
