CREATE TABLE [base_dw_halfen_0_hlp].[DIM_ARTICLE] (
    [DW_Id]                                   BIGINT          NOT NULL,
    [Item no]                                 NVARCHAR (40)   NULL,
    [Item description]                        NVARCHAR (280)  NULL,
    [Product line]                            NVARCHAR (20)   NULL,
    [Product range]                           NVARCHAR (20)   NULL,
    [Product group]                           NVARCHAR (20)   NULL,
    [Product sub_group]                       NVARCHAR (20)   NULL,
    [Main product class]                      NVARCHAR (20)   NULL,
    [Product class]                           NVARCHAR (20)   NULL,
    [Item no_description]                     VARCHAR (500)   NULL,
    [DW_Id_Product_Range]                     BIGINT          NULL,
    [Product range range_description]         VARCHAR (500)   NULL,
    [DW_Id_Product_Line]                      BIGINT          NULL,
    [Product line_line_description]           VARCHAR (500)   NULL,
    [DW_Id_Product_Group]                     BIGINT          NULL,
    [Product group product_group_description] VARCHAR (50)    NULL,
    [DW_Id_Product_Sub_Group]                 BIGINT          NULL,
    [Product sub_group sub_group_description] VARCHAR (500)   NULL,
    [DW_Id_Product_Class]                     BIGINT          NULL,
    [Product class productclass_description]  VARCHAR (500)   NULL,
    [Calculation Type]                        BIGINT          NULL,
    [Calculation type description]            NVARCHAR (1999) NULL,
    [Itemtype]                                INT             NULL,
    [Itemtype description]                    NVARCHAR (1999) NULL,
    [Itemgroup]                               NVARCHAR (20)   NULL,
    [Itemgroup description]                   NVARCHAR (140)  NULL,
    [Stop Explode]                            INT             NULL,
    [Stop Explode description]                VARCHAR (10)    NULL,
    [Status]                                  NVARCHAR (30)   NULL,
    [Primary Vendor]                          NVARCHAR (20)   NULL,
    [Intracode]                               NVARCHAR (10)   NULL,
    [Intracodename]                           NVARCHAR (250)  NULL,
    [Intracode_Name]                          NVARCHAR (200)  NULL,
    [CRHProductgroupid]                       NVARCHAR (10)   NULL,
    [CRHMAINGROUPID]                          NVARCHAR (10)   NULL,
    [CRHPRODUCTPILLARID]                      NVARCHAR (10)   NULL,
    [DW_Batch]                                BIGINT          NULL,
    [DW_SourceCode]                           VARCHAR (15)    NOT NULL,
    [DW_TimeStamp]                            DATETIME        NOT NULL,
    [t_applicationId] VARCHAR    (32)  NULL,
    [t_jobId]         VARCHAR    (36)  NULL,
    [t_jobDtm]        DATETIME,
    [t_jobBy]         NVARCHAR  (128)  NULL,
    [t_extractionDtm] DATETIME,
    [t_filePath]      NVARCHAR (1024)  NULL
    CONSTRAINT [PK_DIM_ARTICLE] PRIMARY KEY NONCLUSTERED ([DW_Id] ASC) NOT ENFORCED
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

