CREATE TABLE [base_dw_halfen_0_hlp].[DIM_ARTICLE] (
    [DW_Id]                                   BIGINT          NOT NULL,
    [Itemno]                                 NVARCHAR (40)   NULL,
    [Itemdescription]                        NVARCHAR (280)  NULL,
    [Productline]                            NVARCHAR (20)   NULL,
    [Productrange]                           NVARCHAR (20)   NULL,
    [Productgroup]                           NVARCHAR (20)   NULL,
    [Productsub_group]                       NVARCHAR (20)   NULL,
    [Mainproductclass]                      NVARCHAR (20)   NULL,
    [Productclass]                           NVARCHAR (20)   NULL,
    [Itemno_description]                     VARCHAR (500)   NULL,
    [DW_Id_Product_Range]                     BIGINT          NULL,
    [Productrangerange_description]         VARCHAR (500)   NULL,
    [DW_Id_Product_Line]                      BIGINT          NULL,
    [Productline_line_description]           VARCHAR (500)   NULL,
    [DW_Id_Product_Group]                     BIGINT          NULL,
    [Productgroupproduct_group_description] VARCHAR (50)    NULL,
    [DW_Id_Product_Sub_Group]                 BIGINT          NULL,
    [Productsub_groupsub_group_description] VARCHAR (500)   NULL,
    [DW_Id_Product_Class]                     BIGINT          NULL,
    [Productclassproductclass_description]  VARCHAR (500)   NULL,
    [CalculationType]                        BIGINT          NULL,
    [Calculationtypedescription]            NVARCHAR (1999) NULL,
    [Itemtype]                                INT             NULL,
    [Itemtypedescription]                    NVARCHAR (1999) NULL,
    [Itemgroup]                               NVARCHAR (20)   NULL,
    [Itemgroupdescription]                   NVARCHAR (140)  NULL,
    [StopExplode]                            INT             NULL,
    [StopExplodedescription]                VARCHAR (10)    NULL,
    [Status]                                  NVARCHAR (30)   NULL,
    [PrimaryVendor]                          NVARCHAR (20)   NULL,
    [Intracode]                               NVARCHAR (10)   NULL,
    [Intracodename]                           NVARCHAR (250)  NULL,
    [Intracode_Name]                          NVARCHAR (200)  NULL,
    [CRHProductgroupid]                       NVARCHAR (10)   NULL,
    [CRHMAINGROUPID]                          NVARCHAR (10)   NULL,
    [CRHPRODUCTPILLARID]                      NVARCHAR (10)   NULL,
    [DW_Batch]                                BIGINT          NULL,
    [DW_SourceCode]                           VARCHAR (15)    NOT NULL,
    [DW_TimeStamp]                            DATETIME        NOT NULL,
    [t_applicationId] VARCHAR    (32)  NULL,
    [t_jobId]         VARCHAR    (36)  NULL,
    [t_jobDtm]        DATETIME,
    [t_jobBy]         NVARCHAR  (128)  NULL,
    [t_extractionDtm] DATETIME,
    [t_filePath]      NVARCHAR (1024)  NULL
    CONSTRAINT [PK_DIM_ARTICLE] PRIMARY KEY NONCLUSTERED ([DW_Id] ASC) NOT ENFORCED
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);

