CREATE TABLE [base_dw_halfen_0_hlp].[PRODUCTLINE](
	[PRODUCTLINEKEY] [tinyint] NOT NULL,
	[PRODUCTLINEID] [nvarchar](10) NOT NULL,
	[PRODUCTLINEDESC] [nvarchar](60) NOT NULL,
	[PRODUCTRANGEID] [nvarchar](10) NOT NULL,
	[CRHPRODUCTGROUPID] [nvarchar](10) NOT NULL
) WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);