CREATE VIEW [edw].[vw_ExchangeRates]
	AS SELECT 
	   [ExchangeRateType]
      ,[SourceCurrency]
      ,[TargetCurrency]
      ,[ExchangeRateEffectiveDate]
      ,[ExchangeRate]
      ,[NumberOfSourceCurrencyUnits]
      ,[NumberOfTargetCurrencyUnits]
      ,[AlternativeExchangeRateType]
      ,[AltvExchangeRateTypeValdtyDate]
      ,[InvertedExchangeRateIsAllowed]
      ,[ReferenceCurrency]
      ,[BuyingRateAvgExchangeRateType]
      ,[SellingRateAvgExchangeRateType]
      ,[FixedExchangeRateIsUsed]
      ,[SpecialConversionIsUsed]
      ,[SourceCurrencyDecimals]
      ,[TargetCurrencyDecimals]
      ,[ExchRateIsIndirectQuotation]
      ,[AbsoluteExchangeRate]
      ,[EffectiveExchangeRate]
      ,[DirectQuotedEffectiveExchRate]
      ,[IndirectQuotedEffctvExchRate]
      ,[t_applicationId]
    FROM 
        [base_s4h_cax].[I_ExchangeRate]
    -- WHERE [MANDT] = 200 MPS 2021/11/01: commented out due to different client values between dev,qas, and prod

  UNION ALL
  SELECT
      'ZAXBIBUD' AS [ExchangeRateType]
      ,[CURRENCY] /*collate SQL_Latin1_General_CP1_CS_AS*/ AS [SourceCurrency]
	  ,'EUR' AS [TargetCurrency]
      ,CONVERT(date, (CAST([YEAR] as VARCHAR)), 112) AS [ExchangeRateEffectiveDate]
      ,1/[CRHRATE] AS [ExchangeRate]
      ,null as [NumberOfSourceCurrencyUnits]
      ,null as [NumberOfTargetCurrencyUnits]
      ,null as [AlternativeExchangeRateType]
      ,null as [AltvExchangeRateTypeValdtyDate]
      ,null as [InvertedExchangeRateIsAllowed]
      ,null as [ReferenceCurrency]
      ,null as [BuyingRateAvgExchangeRateType]
      ,null as [SellingRateAvgExchangeRateType]
      ,null as [FixedExchangeRateIsUsed]
      ,null as [SpecialConversionIsUsed]
      ,null as [SourceCurrencyDecimals]
      ,null as [TargetCurrencyDecimals]
      ,null as [ExchRateIsIndirectQuotation]
      ,null as [AbsoluteExchangeRate]
      ,null as [EffectiveExchangeRate]
      ,null as [DirectQuotedEffectiveExchRate]
      ,null as [IndirectQuotedEffctvExchRate]
      ,[t_applicationId]
  FROM [base_tx_ca_0_hlp].[CRHCURRENCY]
