CREATE VIEW [edw].[vw_fact_MaterialInventoryFirstPostingDate]
AS
SELECT
  [MaterialID]
, [PlantID]
, [StorageLocationID]
, [InventorySpecialStockTypeID]
, [InventoryStockTypeID]
, [StockOwner]
, [CostCenterID]
, [CompanyCodeID]
, [SalesDocumentTypeID]
, [SalesDocumentItemCategoryID]
, [MaterialBaseUnitID]
, [PurchaseOrderTypeID]
, [InventoryValuationTypeID]
, [nk_StoragePlantID]
, [sk_ProductSalesOrg]
, [PlantSalesOrgID]
, MIN(HDR_PostingDate) AS FirstPostingDate
, [t_applicationId]
, [t_extractionDtm]
FROM
  [edw].[vw_fact_MaterialDocumentItem_s4h]
GROUP BY
  [MaterialID]
, [PlantID]
, [StorageLocationID]
, [InventorySpecialStockTypeID]
, [InventoryStockTypeID]
, [StockOwner]
, [CostCenterID]
, [CompanyCodeID]
, [SalesDocumentTypeID]
, [SalesDocumentItemCategoryID]
, [MaterialBaseUnitID]
, [PurchaseOrderTypeID]
, [InventoryValuationTypeID]
, [nk_StoragePlantID]
, [sk_ProductSalesOrg]
, [PlantSalesOrgID]
, [t_applicationId]
, [t_extractionDtm]
