CREATE VIEW [edw].[vw_fact_SalesDocumentItem] 
AS
SELECT  
       doc.[sk_fact_SalesDocumentItem]
     , doc.[SalesDocument]
     , doc.[SalesDocumentItem]
     , doc.[CurrencyTypeID]
     , doc.[CurrencyType]
     , doc.[CurrencyID]
     , doc.[IsReturnsItemID]
     , doc.[CreationDate]
     , doc.[CreationTime]
     , doc.[LastChangeDate]
     , doc.[SalesOrganizationID]
     , doc.[MaterialID]
     , doc.[nk_ProductPlant]
     , doc.[ProductSurrogateKey]
     , doc.[OriginallyRequestedMaterialID]
     , doc.[MaterialSubstitutionReasonID]
     , doc.[MaterialGroupID]
     , doc.[BrandID]
     , doc.[Brand]
     , doc.[SoldToPartyID]
     , doc.[ShipToPartyID]
     , doc.[PayerPartyID]
     , doc.[BillToPartyID]
     , doc.[SalesDocumentDate]
     , doc.[OrderQuantity]
     , doc.[TargetQuantity]
     , doc.[TargetQuantityUnitID]
     , doc.[ServicesRenderedDate]
     , doc.[SalesDistrictID]
     , doc.[PricingDate]
     , doc.[ExchangeRateDate]
     , doc.[NetAmount]
     , doc.[TransactionCurrencyID]
     , doc.[RequestedDeliveryDate]
     , doc.[PlantID]
     , doc.[StorageLocationID]
     , doc.[BillingDocumentDate]
     , doc.[BillingCompanyCodeID]
     , doc.[ProfitCenterID]
     , doc.[ReferenceSDDocumentID]
     , doc.[ReferenceSDDocumentItemID]
     , doc.[OriginSDDocumentID]
     , doc.[OriginSDDocumentItemID]
     , doc.[OverallOrdReltdBillgStatusID]
     , dimDBS.[DeliveryBlockStatusID]
     , dimDBS.[DeliveryBlockStatus]
     , dimBBS.[BillingBlockStatusID]
     , dimBBS.[BillingBlockStatus]
     , doc.[SalesAgentID]
     , doc.[SalesAgent]
     , doc.[ExternalSalesAgentID]
     , doc.[ExternalSalesAgent]
     , doc.[ProjectID]
     , doc.[Project]
     , doc.[SalesEmployeeID]
     , doc.[SalesEmployee]
     , doc.[GlobalParentCalculatedID]
     , doc.[GlobalParentCalculated]
     , doc.[LocalParentCalculatedID]
     , doc.[LocalParentCalculated]
     , doc.[Margin]
     , doc.[Subtotal1Amount]
     , doc.[Subtotal2Amount]
     , doc.[Subtotal3Amount]
     , doc.[Subtotal4Amount]
     , doc.[Subtotal5Amount]
     , doc.[Subtotal6Amount]
     , doc.[InOutID]
     , doc.[OrderType]
     , doc.[ItemOrderStatus]
     , doc.[OrderStatus]
     , doc.[ActualDeliveredQuantityInBaseUnit]
     , doc.[BillingQuantityInBaseUnit]
     , doc.[ActualDeliveredQuantityIBUOverall]
     , doc.[BillingQuantityIBUOverall]
     , doc.[ItemDeliveryStatus]    
     , doc.[OverallDeliveryStatus] 
     , doc.[ScheduleLineCategory]
     , doc.[SalesOfficeID]
     , doc.[CostAmount] 
     , doc.[ShippingConditionID]
     , doc.[HeaderBillingBlockReasonID]
     , doc.[ItemBillingBlockReasonID]
     , doc.[DeliveryBlockReasonID]
     , DeliveryItem.[HDR_PlannedGoodsIssueDate]
     , DeliveryItem.[HDR_ShippingPointID]
     , DeliveryItem.[HDR_HeaderBillingBlockReason]
     , DeliveryItem.[HDR_TotalBlockStatusID]
     , DeliveryItem.[HDR_ShipmentBlockReason]
     , DeliveryItem.[HDR_DeliveryBlockReason]
     , DeliveryItem.[CreatedByUserID]
     , DeliveryItem.[OutboundDelivery]
     , DeliveryItem.[OutboundDeliveryItem]
     , edw.[svf_getIsOrderItemBlockedFlag] (
          doc.[DeliveryBlockReasonID]
        , dimBBS.[BillingBlockStatusID]
        , doc.[HeaderBillingBlockReasonID]
        , doc.[ItemBillingBlockReasonID]
        , DeliveryItem.[HDR_DeliveryBlockReason] 
       )                                          AS [IsOrderItemBlockedFlag]
     , doc.[t_applicationId]
     , doc.[t_extractionDtm]
FROM [edw].[fact_SalesDocumentItem] doc
LEFT JOIN 
    [edw].[dim_BillingBlockStatus] dimBBS
        ON 
        dimBBS.[BillingBlockStatusID] = doc.[BillingBlockStatusID]
LEFT JOIN 
    [edw].[vw_LatestOutboundDeliveryItem] DeliveryItem
        ON 
        doc.[SalesDocument] = DeliveryItem.[ReferenceSDDocument]
        AND 
        doc.[SalesDocumentItem] = DeliveryItem.[ReferenceSDDocumentItem]
