-- CREATE VIEW [edw].[vw_fact_MaterialInventoryFirstYearWeek]
-- AS

-- /*
-- 1. Aggregate stock changes on a weekly level
-- 2. Get the first posting date of each hash
-- 3. Get the corresponding year week of the first posting date
-- 4. Add the missing yearWeeks for each hash based on calendar table
-- 5. Include the stock changes for the reported weeks
-- 6. Calculate the stock levels for each combo of yearWeek and hash
-- 7. Calculate the stock level price per unit
-- */

-- -- 3. Get the YearWeek of the first posting date
-- SELECT
--   fp.[MaterialID]
-- , fp.[PlantID]
-- , fp.[StorageLocationID]
-- , fp.[InventorySpecialStockTypeID]
-- , fp.[InventoryStockTypeID]
-- , fp.[StockOwner]
-- , fp.[CostCenterID]
-- , fp.[CompanyCodeID]
-- , fp.[SalesDocumentTypeID]
-- , fp.[SalesDocumentItemCategoryID]
-- , fp.[MaterialBaseUnitID]
-- , fp.[PurchaseOrderTypeID]
-- , fp.[InventoryValuationTypeID]
-- , cal.[YearWeek] AS FirstYearWeek
-- , cal.[YearMonth] AS FirstYearMonth
-- , fp.[t_applicationId]
-- FROM
--   edw.vw_fact_MaterialInventoryFirstPostingDate fp
-- LEFT JOIN
--   [edw].[dim_Calendar] AS cal
--   ON
--     cal.CalendarDate = fp.FirstPostingDate