CREATE VIEW [edw].[vw_ProductValuation]
AS
WITH ProductValuation AS (
    SELECT
       basePV.[Product]                                AS [ProductID],
       basePV.[ValuationArea]                          AS [ValuationAreaID],
       basePV.[ValuationType]                          AS [ValuationTypeID],
       basePV.[ValuationClass]                         AS [ValuationClassID],
       basePV.[PriceDeterminationControl]              AS [PriceDeterminationControlID],
       basePV.[FiscalMonthCurrentPeriod],
       basePV.[FiscalYearCurrentPeriod],
       basePV.[StandardPrice],
       basePV.[PriceUnitQty]                           AS [PriceUnitQuantity],
       basePV.[StandardPrice] / basePV.[PriceUnitQty]  AS [StandardPricePerUnit],
       basePV.[InventoryValuationProcedure],
       basePV.[FutureEvaluatedAmountValue],
       basePV.[FuturePriceValidityStartDate],
       basePV.[PrevInvtryPriceInCoCodeCrcy],       
       basePV.[MovingAveragePrice],
       basePV.[MovingAveragePrice] / basePV.[PriceUnitQty]  AS [MovingAvgPricePerUnit],
       basePV.[ValuationCategory]                           AS [ValuationCategoryID],
       basePV.[ProductUsageType], 
       basePV.[ProductOriginType],
       basePV.[IsProducedInhouse],
       basePV.[ProdCostEstNumber],
       basePV.[IsMarkedForDeletion],
       basePV.[ValuationMargin],
       basePV.[IsActiveEntity],
       basePV.[CompanyCode]                            AS [CompanyCodeID],
       basePV.[ValuationClassSalesOrderStock], 
       basePV.[ProjectStockValuationClass],
       basePV.[PlannedPrice1InCoCodeCrcy], 
       basePV.[PlannedPrice2InCoCodeCrcy], 
       basePV.[PlannedPrice3InCoCodeCrcy], 
       basePV.[FuturePlndPrice1ValdtyDate], 
       basePV.[FuturePlndPrice2ValdtyDate], 
       basePV.[FuturePlndPrice3ValdtyDate], 
       basePV.[TaxBasedPricesPriceUnitQty],     
       basePV.[PriceLastChangeDate],
       basePV.[PlannedPrice],       
       basePV.[Currency]                               AS [CurrencyID],
       basePV.[t_applicationId],
       basePV.[t_extractionDtm]
    FROM [base_s4h_cax].[I_ProductValuation] AS basePV
)
                     
SELECT
       PV.[ProductID],
       PV.[ValuationAreaID],
       PV.[ValuationTypeID],
       PV.[ValuationClassID], 
       PV.[PriceDeterminationControlID],
       PV.[FiscalMonthCurrentPeriod],
       PV.[FiscalYearCurrentPeriod],
       PV.[StandardPrice],
       PV.[PriceUnitQuantity],
       PV.[StandardPricePerUnit],
       CONVERT(decimal(19,6), PV.[StandardPricePerUnit] * CCR.[ExchangeRate]) AS StandardPricePerUnit_EUR,
       PV.[InventoryValuationProcedure],
       PV.[FutureEvaluatedAmountValue],
       PV.[FuturePriceValidityStartDate],
       PV.[PrevInvtryPriceInCoCodeCrcy],
       PV.[MovingAveragePrice],
       PV.[MovingAvgPricePerUnit],
       CONVERT(decimal(19,6), PV.[MovingAvgPricePerUnit] * CCR.[ExchangeRate]) AS MovingAvgPricePerUnit_EUR,
       PV.[ValuationCategoryID],
       PV.[ProductUsageType], 
       PV.[ProductOriginType],
       PV.[IsProducedInhouse],
       PV.[ProdCostEstNumber],
       PV.[IsMarkedForDeletion],
       PV.[ValuationMargin],
       PV.[IsActiveEntity],
       PV.[CompanyCodeID],
       PV.[ValuationClassSalesOrderStock], 
       PV.[ProjectStockValuationClass],
       PV.[PlannedPrice1InCoCodeCrcy], 
       PV.[PlannedPrice2InCoCodeCrcy], 
       PV.[PlannedPrice3InCoCodeCrcy], 
       PV.[FuturePlndPrice1ValdtyDate], 
       PV.[FuturePlndPrice2ValdtyDate], 
       PV.[FuturePlndPrice3ValdtyDate], 
       PV.[TaxBasedPricesPriceUnitQty],           
       PV.[PriceLastChangeDate],
       PV.[PlannedPrice],
       PV.[CurrencyID],
       PV.[t_applicationId],
       PV.[t_extractionDtm]
FROM 
    ProductValuation AS PV
LEFT JOIN [edw].[vw_CurrencyConversionRate] CCR
    ON PV.CurrencyID = CCR.SourceCurrency AND CCR.CurrencyTypeID ='30'