CREATE VIEW [edw].[vw_SalesQuotationPrcgElmnt]
As
/*
    Transaction currency data from S4H
*/
SELECT
    [SalesQuotation] 
  , [PricingProcedureStep] 
  , [PricingProcedureCounter] 
  , [ConditionApplication] 
  , [ConditionType] 
  , [PricingDateTime] 
  , [ConditionCalculationType] 
  , [ConditionBaseValue] 
  , [ConditionRateValue] 
  , [ConditionCurrency] 
  , [ConditionQuantity] 
  , [ConditionQuantityUnit] 
  , [ConditionCategory] 
  , [ConditionIsForStatistics] 
  , [PricingScaleType]
  , [IsRelevantForAccrual] 
  , [CndnIsRelevantForInvoiceList] 
  , [ConditionOrigin] 
  , [IsGroupCondition]
  , [ConditionRecord] 
  , [ConditionSequentialNumber] 
  , [TaxCode] 
  , [WithholdingTaxCode] 
  , [CndnRoundingOffDiffAmount] 
  , [ConditionAmount] 
  , [TransactionCurrency] 
  , [ConditionControl] 
  , [ConditionInactiveReason] 
  , [ConditionClass] 
  , [PrcgProcedureCounterForHeader]
  , [FactorForConditionBasisValue]
  , [StructureCondition] 
  , [PeriodFactorForCndnBasisValue] 
  , [PricingScaleBasis] 
  , [ConditionScaleBasisValue] 
  , [ConditionScaleBasisUnit] 
  , [ConditionScaleBasisCurrency] 
  , [CndnIsRelevantForIntcoBilling] 
  , [ConditionIsManuallyChanged] 
  , [ConditionIsForConfiguration] 
  , [VariantCondition] 
  , [t_applicationId] 
  , [t_jobDtm]
FROM [base_s4h_cax].[I_SalesQuotationPrcgElmnt]