CREATE VIEW [edw].[vw_SupplierInvoice]
AS
SELECT
    [SupplierInvoice]     AS [SupplierInvoiceID],
    [FiscalYear],                     
    [SupplierInvoiceUUID],
    [CompanyCode]         AS [CompanyCodeID],
    [DocumentDate],
    [PostingDate],
    [InvoiceReceiptDate],
    [SupplierInvoiceIDByInvcgParty],
    [InvoicingParty]      AS [InvoicingPartyID],
    [DocumentCurrency]    AS [DocumentCurrencyID],
    [InvoiceGrossAmount],
    [IsInvoice],
    [UnplannedDeliveryCost],
    [DocumentHeaderText],
    [CreatedByUser],
    [LastChangedByUser],
    [SuplrInvcExtCreatedByUser],
    [CreationDate],
    [ManualCashDiscount],
    [PaymentTerms],
    [DueCalculationBaseDate],
    [CashDiscount1Percent],
    [CashDiscount1Days],
    [CashDiscount2Percent],
    [CashDiscount2Days],
    [NetPaymentDays],
    [PaymentBlockingReason],
    [AccountingDocumentType],
    [SupplierInvoiceStatus],
    [SupplierInvoiceOrigin],
    [BusinessNetworkOrigin],
    [SuplrInvcTransactionCategory],
    [SuplrInvcManuallyReducedAmount],
    [SuplrInvcManualReductionTaxAmt],
    [SuplrInvcAutomReducedAmount],
    [SuplrInvcAutomReductionTaxAmt],
    [BPBankAccountInternalID],
    [ExchangeRate],
    [StateCentralBankPaymentReason],
    [SupplyingCountry]                  AS [SupplyingCountryID],
    Country.[CountryName]               AS [SupplyingCountry],
    [PaymentMethod],
    [PaymentMethodSupplement],
    [PaymentReference],
    [InvoiceReference],
    [InvoiceReferenceFiscalYear],
    [FixedCashDiscount],
    [UnplannedDeliveryCostTaxCode],
    [UnplndDelivCostTaxJurisdiction],
    [AssignmentReference],
    [SupplierPostingLineItemText],
    [TaxIsCalculatedAutomatically],
    [BusinessPlace],
    [PaytSlipWthRefSubscriber],
    [PaytSlipWthRefCheckDigit],
    [PaytSlipWthRefReference],
    [IsEndOfPurposeBlocked],
    [BusinessSectionCode],
    [BusinessArea],
    [ElectronicInvoiceUUID],
    [TaxDeterminationDate],
    [DeliveryOfGoodsReportingCntry],
    [SupplierVATRegistration],
    [IsEUTriangularDeal],
    SuppInv.[t_applicationId],
    SuppInv.[t_extractionDtm]
FROM
    [base_s4h_cax].[I_SupplierInvoice] SuppInv
LEFT JOIN
    [base_s4h_cax].[I_CountryText] Country
    ON
        SuppInv.[SupplyingCountry] = Country.[Country]
        AND
        [Language] = 'E'
WHERE
    ISNULL(SuppInv.ReverseDocument, '') = ''
