CREATE VIEW [edw].[vw_SalesDocumentItem_s4h]
	AS
with C_SalesDocumentItemDEXBase as (
    SELECT
         -- doc.[TS_SEQUENCE_NUMBER]
         --,doc.[ODQ_CHANGEMODE]
         --,doc.[ODQ_ENTITYCNTR]
           doc.[SalesDocument]
         , doc.[SalesDocumentItem]
         , doc.[SDDocumentCategory]             as [SDDocumentCategoryID]
         , doc.[SalesDocumentType]              as [SalesDocumentTypeID]
         , doc.[SalesDocumentItemCategory]      as [SalesDocumentItemCategoryID]
         , doc.[IsReturnsItem]                  as [IsReturnsItemID]
         , doc.[CreationDate]
         , doc.[CreationTime]
         , doc.[LastChangeDate]
         , doc.[SalesOrganization]              as [SalesOrganizationID]
         , doc.[DistributionChannel]            as [DistributionChannelID]
         , doc.[Division]                       as [DivisionID]
         , doc.[SalesGroup]                     as [SalesGroupID]
         , doc.[SalesOffice]                    as [SalesOfficeID]
         , doc.[InternationalArticleNumber]     as [InternationalArticleNumberID]
         , doc.[Batch]                          as [BatchID]
         , doc.[Material]                       as [MaterialID]
         , doc.[OriginallyRequestedMaterial]    as [OriginallyRequestedMaterialID]
         , doc.[MaterialSubstitutionReason]     as [MaterialSubstitutionReasonID]
         , doc.[MaterialGroup]                  as [MaterialGroupID]
         , DimBrand.[BrandID]                   as [BrandID]
         , DimBrand.[Brand]                     as [Brand]
         , doc.[AdditionalMaterialGroup2]       as [AdditionalMaterialGroup2ID]
         , doc.[AdditionalMaterialGroup3]       as [AdditionalMaterialGroup3ID]
         , doc.[AdditionalMaterialGroup4]       as [AdditionalMaterialGroup4ID]
         , doc.[AdditionalMaterialGroup5]       as [AdditionalMaterialGroup5ID]
         , doc.[SoldToParty]                    as [SoldToPartyID]
         , doc.[AdditionalCustomerGroup1]       as [AdditionalCustomerGroup1ID]
         , doc.[AdditionalCustomerGroup2]       as [AdditionalCustomerGroup2ID]
         , doc.[AdditionalCustomerGroup3]       as [AdditionalCustomerGroup3ID]
         , doc.[AdditionalCustomerGroup4]       as [AdditionalCustomerGroup4ID]
         , doc.[AdditionalCustomerGroup5]       as [AdditionalCustomerGroup5ID]
         , doc.[ShipToParty]                    as [ShipToPartyID]
         , doc.[PayerParty]                     as [PayerPartyID]
         , doc.[BillToParty]                    as [BillToPartyID]
         , doc.[SDDocumentReason]               as [SDDocumentReasonID]
         , doc.[SalesDocumentDate]
         , doc.[OrderQuantity]
         , doc.[OrderQuantityUnit]              as [OrderQuantityUnitID]
         , doc.[TargetQuantity]
         , doc.[TargetQuantityUnit]             as [TargetQuantityUnitID]
         , doc.[TargetToBaseQuantityDnmntr]
         , doc.[TargetToBaseQuantityNmrtr]
         , doc.[OrderToBaseQuantityDnmntr]
         , doc.[OrderToBaseQuantityNmrtr]
         , doc.[ConfdDelivQtyInOrderQtyUnit]
         , doc.[TargetDelivQtyInOrderQtyUnit]
         , doc.[ConfdDeliveryQtyInBaseUnit]
         , doc.[BaseUnit]                       as [BaseUnitID]
         , doc.[ItemGrossWeight]
         , doc.[ItemNetWeight]
         , doc.[ItemWeightUnit]                 as [ItemWeightUnitID]
         , doc.[ItemVolume]
         , doc.[ItemVolumeUnit]                 as [ItemVolumeUnitID]
         , doc.[ServicesRenderedDate]
         , doc.[SalesDistrict]                  as [SalesDistrictID]
         , doc.[CustomerGroup]                  as [CustomerGroupID]
         , doc.[HdrOrderProbabilityInPercent]   as [HdrOrderProbabilityInPercentID]
         , doc.[ItemOrderProbabilityInPercent]  as [ItemOrderProbabilityInPercentID]
         , doc.[SalesDocumentRjcnReason]        as [SalesDocumentRjcnReasonID]
         , doc.[PricingDate]
         , doc.[ExchangeRateDate]
         , doc.[PriceDetnExchangeRate]
         , doc.[StatisticalValueControl]        as [StatisticalValueControlID]
         , doc.[NetAmount]
         , doc.[TransactionCurrency]            as [TransactionCurrencyID]
         , doc.[SalesOrganizationCurrency]      as [SalesOrganizationCurrencyID]
         , doc.[NetPriceAmount]
         , doc.[NetPriceQuantity]
         , doc.[NetPriceQuantityUnit]           as [NetPriceQuantityUnitID]
         , doc.[TaxAmount]
         , doc.[CostAmount]
         , doc.[NetAmount] - doc.[CostAmount]   as [Margin]
         , doc.[Subtotal1Amount]
         , doc.[Subtotal2Amount]
         , doc.[Subtotal3Amount]
         , doc.[Subtotal4Amount]
         , doc.[Subtotal5Amount]
         , doc.[Subtotal6Amount]
         , doc.[ShippingPoint]                  as [ShippingPointID]
         , doc.[ShippingType]                   as [ShippingTypeID]
         , doc.[DeliveryPriority]               as [DeliveryPriorityID]
         , doc.[InventorySpecialStockType]      as [InventorySpecialStockTypeID]
         , doc.[RequestedDeliveryDate]
         , doc.[ShippingCondition]              as [ShippingConditionID]
         , doc.[DeliveryBlockReason]            as [DeliveryBlockReasonID]
         , doc.[Plant]                          as [PlantID]
         , doc.[StorageLocation]                as [StorageLocationID]
         , doc.[Route]                          as [RouteID]
         , doc.[IncotermsClassification]        as [IncotermsClassificationID]
         , doc.[IncotermsVersion]               as [IncotermsVersionID]
         , doc.[IncotermsTransferLocation]      as [IncotermsTransferLocationID]
         , doc.[IncotermsLocation1]             as [IncotermsLocation1ID]
         , doc.[IncotermsLocation2]             as [IncotermsLocation2ID]
         , doc.[MinDeliveryQtyInBaseUnit]
         , doc.[UnlimitedOverdeliveryIsAllowed] as [UnlimitedOverdeliveryIsAllowedID]
         , doc.[OverdelivTolrtdLmtRatioInPct]
         , doc.[UnderdelivTolrtdLmtRatioInPct]
         , doc.[PartialDeliveryIsAllowed]       as [PartialDeliveryIsAllowedID]
         , doc.[BindingPeriodValidityStartDate]
         , doc.[BindingPeriodValidityEndDate]
         , doc.[OutlineAgreementTargetAmount]
         , doc.[BillingDocumentDate]
         , doc.[BillingCompanyCode]             as [BillingCompanyCodeID]
         , doc.[HeaderBillingBlockReason]       as [HeaderBillingBlockReasonID]
         , doc.[ItemBillingBlockReason]         as [ItemBillingBlockReasonID]
         , doc.[FiscalYear]                     as [FiscalYearID]
         , doc.[FiscalPeriod]                   as [FiscalPeriodID]
         , doc.[CustomerAccountAssignmentGroup] as [CustomerAccountAssignmentGroupID]
         , doc.[ExchangeRateType]               as [ExchangeRateTypeID]
         , doc.[Currency]                       as [CurrencyID]
         , doc.[FiscalYearVariant]              as [FiscalYearVariantID]
         , doc.[BusinessArea]                   as [BusinessAreaID]
         , doc.[ProfitCenter]                   as [ProfitCenterID]
         , doc.[OrderID]                        as [OrderID]
         , doc.[ProfitabilitySegment]           as [ProfitabilitySegmentID]
         , doc.[ControllingArea]                as [ControllingAreaID]
         , doc.[ReferenceSDDocument]            as [ReferenceSDDocumentID]
         , doc.[ReferenceSDDocumentItem]        as [ReferenceSDDocumentItemID]
         , doc.[ReferenceSDDocumentCategory]    as [ReferenceSDDocumentCategoryID]
         , doc.[OriginSDDocument]               as [OriginSDDocumentID]
         , doc.[OriginSDDocumentItem]           as [OriginSDDocumentItemID]
         , doc.[OverallSDProcessStatus]         as [OverallSDProcessStatusID]
         , doc.[OverallTotalDeliveryStatus]     as [OverallTotalDeliveryStatusID]
         , doc.[OverallOrdReltdBillgStatus]     as [OverallOrdReltdBillgStatusID]
         , doc.[TotalCreditCheckStatus]         as [TotalCreditCheckStatusID]
         , doc.[DeliveryBlockStatus]            as [DeliveryBlockStatusID]
         , doc.[BillingBlockStatus]             as [BillingBlockStatusID]
         , doc.[TotalSDDocReferenceStatus]      as [TotalSDDocReferenceStatusID]
         , doc.[SDDocReferenceStatus]           as [SDDocReferenceStatusID]
         , doc.[OverallSDDocumentRejectionSts]  as [OverallSDDocumentRejectionStsID]
         , doc.[SDDocumentRejectionStatus]      as [SDDocumentRejectionStatusID]
         , doc.[OverallTotalSDDocRefStatus]     as [OverallTotalSDDocRefStatusID]
         , doc.[OverallSDDocReferenceStatus]    as [OverallSDDocReferenceStatusID]
         , doc.[ItemGeneralIncompletionStatus]  as [ItemGeneralIncompletionStatusID]
         , doc.[ItemBillingIncompletionStatus]  as [ItemBillingIncompletionStatusID]
         , doc.[PricingIncompletionStatus]      as [PricingIncompletionStatusID]
         , doc.[ItemDeliveryIncompletionStatus] as [ItemDeliveryIncompletionStatusID]
         , ZB.[Customer]                        as [ExternalSalesAgentID]
         , ZB.[FullName]                        as [ExternalSalesAgent]
         , D1.[Customer]                        as [GlobalParentID]
         , D1.[FullName]                        as [GlobalParent]
         , C1.[Customer]                        as [LocalParentID]
         , C1.[FullName]                        as [LocalParent]
         , ZP.[Customer]                        as [ProjectID]
         , ZP.[FullName]                        as [Project]
         , VE.[Personnel]                       as [SalesEmployeeID]
         , VE.[FullName]                        as [SalesEmployee]
         , case
               when D1.[Customer] is not null then D1.[Customer]
               else AG.[Customer]
           end                                  as [GlobalParentCalculatedID]
         , case
               when D1.[FullName] is not null then D1.[FullName]
               else AG.[FullName]
          end                                   as [GlobalParentCalculated]
         , case
               when C1.[Customer] is not null then C1.[Customer]
               else AG.[Customer]
          end                                   as [LocalParentCalculatedID]
         , case
               when C1.[FullName] is not null then C1.[FullName]
               else AG.[FullName]
          end                                   as [LocalParentCalculated]
         , doc.[SDoc_ControllingObject]         as [SDoc_ControllingObjectID]
         , doc.[SDItem_ControllingObject]       as [SDItem_ControllingObjectID]
         , case
               when left(doc.[SoldToParty], 2) = 'IC' or left(doc.[SoldToParty], 2) = 'IP'
                   then 'I'
               else 'O'
           end                                  as [InOutID]
         , doc.[t_applicationId]
         , doc.[t_jobId]
         , doc.[t_jobDtm]
         , doc.[t_jobBy]
         , doc.[t_extractionDtm]
         , doc.[t_filePath]
    FROM [base_s4h_cax].[C_SalesDocumentItemDEX] doc
    left join [base_s4h_cax].[C_BillingDocumentPartnerFs] ZB
      on ZB.[SDDocument] = doc.[SalesDocument] and ZB.[PartnerFunction] = 'ZB'
      --  and ZB.[MANDT] = 200 MPS 2021/11/01: commented out due to different client values between dev,qas, and prod
    left join [base_s4h_cax].[C_BillingDocumentPartnerFs] D1
      on D1.[SDDocument] = doc.[SalesDocument] and D1.[PartnerFunction] = '1D'
      --  and D1.[MANDT] = 200 MPS 2021/11/01: commented out due to different client values between dev,qas, and prod
    left join [base_s4h_cax].[C_BillingDocumentPartnerFs] C1
      on C1.[SDDocument] = doc.[SalesDocument] and C1.[PartnerFunction] = '1C'
      --  and C1.[MANDT] = 200 MPS 2021/11/01: commented out due to different client values between dev,qas, and prod
    left join [base_s4h_cax].[C_BillingDocumentPartnerFs] ZP
      on ZP.[SDDocument] = doc.[SalesDocument] and ZP.[PartnerFunction] = 'ZP'
      --  and ZP.[MANDT] = 200 MPS 2021/11/01: commented out due to different client values between dev,qas, and prod
    left join [base_s4h_cax].[C_BillingDocumentPartnerFs] VE
      on VE.[SDDocument] = doc.[SalesDocument] and VE.[PartnerFunction] = 'VE'
      --  and VE.[MANDT] = 200 MPS 2021/11/01: commented out due to different client values between dev,qas, and prod
    left join [base_s4h_cax].[C_BillingDocumentPartnerFs] AG
      on AG.[SDDocument] = doc.[SalesDocument] and AG.[PartnerFunction] = 'AG'
      --  and AG.[MANDT] = 200 MPS 2021/11/01: commented out due to different client values between dev,qas, and prod
    -- WHERE doc.[MANDT] = 200 MPS 2021/11/01: commented out due to different client values between dev,qas, and prod
    left join [edw].[vw_Brand] DimBrand
          on DimBrand.[BrandID] = doc.[AdditionalMaterialGroup1]
),
EuroBudgetExchangeRate as (
    select
         SourceCurrency
        ,ExchangeRateEffectiveDate
        ,ExchangeRate
    from
        edw.dim_ExchangeRates
    where
        ExchangeRateType = 'ZAXBIBUD'
        and
        TargetCurrency = 'EUR'
)
SELECT 
      -- [TS_SEQUENCE_NUMBER]
      --,[ODQ_CHANGEMODE]
      --,[ODQ_ENTITYCNTR]
       CONCAT_WS('¦', [SalesDocument] collate SQL_Latin1_General_CP1_CS_AS, [SalesDocumentItem] collate SQL_Latin1_General_CP1_CS_AS, CR.[CurrencyTypeID]) as [nk_fact_SalesDocumentItem]
      ,[SalesDocument]
      ,[SalesDocumentItem]
      ,CR.[CurrencyTypeID]
      ,CR.[CurrencyType]
      ,[TransactionCurrencyID] as [CurrencyID]
      ,1.0 as [ExchangeRate]
      ,[SDDocumentCategoryID]
      ,[SalesDocumentTypeID]
      ,[SalesDocumentItemCategoryID]
      ,[IsReturnsItemID]
      ,[CreationDate]
      ,[CreationTime]
      ,[LastChangeDate]
      ,[SalesOrganizationID]
      ,[DistributionChannelID]
      ,[DivisionID]
      ,[SalesGroupID]
      ,[SalesOfficeID]
      ,[InternationalArticleNumberID]
      ,[BatchID]
      ,[MaterialID]
      ,[OriginallyRequestedMaterialID]
      ,[MaterialSubstitutionReasonID]
      ,[MaterialGroupID]
      ,[BrandID]
      ,[Brand]
      ,[AdditionalMaterialGroup2ID]
      ,[AdditionalMaterialGroup3ID]
      ,[AdditionalMaterialGroup4ID]
      ,[AdditionalMaterialGroup5ID]
      ,[SoldToPartyID]
      ,[AdditionalCustomerGroup1ID]
      ,[AdditionalCustomerGroup2ID]
      ,[AdditionalCustomerGroup3ID]
      ,[AdditionalCustomerGroup4ID]
      ,[AdditionalCustomerGroup5ID]
      ,[ShipToPartyID]
      ,[PayerPartyID]
      ,[BillToPartyID]
      ,[SDDocumentReasonID]
      ,[SalesDocumentDate]
      ,[OrderQuantity]
      ,[OrderQuantityUnitID]
      ,[TargetQuantity]
      ,[TargetQuantityUnitID]
      ,[TargetToBaseQuantityDnmntr]
      ,[TargetToBaseQuantityNmrtr]
      ,[OrderToBaseQuantityDnmntr]
      ,[OrderToBaseQuantityNmrtr]
      ,[ConfdDelivQtyInOrderQtyUnit]
      ,[TargetDelivQtyInOrderQtyUnit]
      ,[ConfdDeliveryQtyInBaseUnit]
      ,[BaseUnitID]
      ,[ItemGrossWeight]
      ,[ItemNetWeight]
      ,[ItemWeightUnitID]
      ,[ItemVolume]
      ,[ItemVolumeUnitID]
      ,[ServicesRenderedDate]
      ,[SalesDistrictID]
      ,[CustomerGroupID]
      ,[HdrOrderProbabilityInPercentID]
      ,[ItemOrderProbabilityInPercentID]
      ,[SalesDocumentRjcnReasonID]
      ,[PricingDate]
      ,[ExchangeRateDate]
      ,[PriceDetnExchangeRate]
      ,[StatisticalValueControlID]
      ,[NetAmount]
      ,[TransactionCurrencyID]
      ,[SalesOrganizationCurrencyID]
      ,[NetPriceAmount]
      ,[NetPriceQuantity]
      ,[NetPriceQuantityUnitID]
      ,[TaxAmount]
      ,[CostAmount]
      ,[Margin]
      ,[Subtotal1Amount]
      ,[Subtotal2Amount]
      ,[Subtotal3Amount]
      ,[Subtotal4Amount]
      ,[Subtotal5Amount]
      ,[Subtotal6Amount]
      ,[ShippingPointID]
      ,[ShippingTypeID]
      ,[DeliveryPriorityID]
      ,[InventorySpecialStockTypeID]
      ,[RequestedDeliveryDate]
      ,[ShippingConditionID]
      ,[DeliveryBlockReasonID]
      ,[PlantID]
      ,[StorageLocationID]
      ,[RouteID]
      ,[IncotermsClassificationID]
      ,[IncotermsVersionID]
      ,[IncotermsTransferLocationID]
      ,[IncotermsLocation1ID]
      ,[IncotermsLocation2ID]
      ,[MinDeliveryQtyInBaseUnit]
      ,[UnlimitedOverdeliveryIsAllowedID]
      ,[OverdelivTolrtdLmtRatioInPct]
      ,[UnderdelivTolrtdLmtRatioInPct]
      ,[PartialDeliveryIsAllowedID]
      ,[BindingPeriodValidityStartDate]
      ,[BindingPeriodValidityEndDate]
      ,[OutlineAgreementTargetAmount]
      ,[BillingDocumentDate]
      ,[BillingCompanyCodeID]
      ,[HeaderBillingBlockReasonID]
      ,[ItemBillingBlockReasonID]
      ,[FiscalYearID]
      ,[FiscalPeriodID]
      ,[CustomerAccountAssignmentGroupID]
      ,[ExchangeRateTypeID]
      ,[CurrencyID] as [CompanyCodeCurrencyID]
      ,[FiscalYearVariantID]
      ,[BusinessAreaID]
      ,[ProfitCenterID]
      ,[OrderID]
      ,[ProfitabilitySegmentID]
      ,[ControllingAreaID]
      ,[ReferenceSDDocumentID]
      ,[ReferenceSDDocumentItemID]
      ,[ReferenceSDDocumentCategoryID]
      ,[OriginSDDocumentID]
      ,[OriginSDDocumentItemID]
      ,[OverallSDProcessStatusID]
      ,[OverallTotalDeliveryStatusID]
      ,[OverallOrdReltdBillgStatusID]
      ,[TotalCreditCheckStatusID]
      ,[DeliveryBlockStatusID]
      ,[BillingBlockStatusID]
      ,[TotalSDDocReferenceStatusID]
      ,[SDDocReferenceStatusID]
      ,[OverallSDDocumentRejectionStsID]
      ,[SDDocumentRejectionStatusID]
      ,[OverallTotalSDDocRefStatusID]
      ,[OverallSDDocReferenceStatusID]
      ,[ItemGeneralIncompletionStatusID]
      ,[ItemBillingIncompletionStatusID]
      ,[PricingIncompletionStatusID]
      ,[ItemDeliveryIncompletionStatusID]
      ,SDI.[ExternalSalesAgentID]
      ,[ExternalSalesAgent]
      ,[GlobalParentID]
      ,[GlobalParent]
      ,[LocalParentID]
      ,[LocalParent]
      ,[ProjectID]
      ,[Project]
      ,[SalesEmployeeID]
      ,[SalesEmployee]
      ,[GlobalParentCalculatedID]
      ,[GlobalParentCalculated]
      ,[LocalParentCalculatedID]
      ,[LocalParentCalculated]
      ,[SDoc_ControllingObjectID]
      ,[SDItem_ControllingObjectID]
      ,[InOutID]
      ,SDI.[t_applicationId]
      ,SDI.[t_jobId]
      ,SDI.[t_jobDtm]
      ,SDI.[t_jobBy]
      ,SDI.[t_extractionDtm]
      ,SDI.[t_filePath]
  FROM [C_SalesDocumentItemDEXBase] SDI
 CROSS JOIN [edw].[dim_CurrencyType] CR
 WHERE CR.[CurrencyTypeID] = '00'
  UNION ALL
SELECT 
      -- [TS_SEQUENCE_NUMBER]
      --,[ODQ_CHANGEMODE]
      --,[ODQ_ENTITYCNTR]
       CONCAT_WS('¦', [SalesDocument] collate SQL_Latin1_General_CP1_CS_AS, [SalesDocumentItem] collate SQL_Latin1_General_CP1_CS_AS, CR.[CurrencyTypeID]) as [nk_fact_SalesDocumentItem]
      ,[SalesDocument]
      ,[SalesDocumentItem]
	  ,CR.[CurrencyTypeID]
      ,CR.[CurrencyType]
      ,[CurrencyID]
      ,(CASE
			 WHEN ER.[ExchangeRate] IS NOT NULL
			 THEN ER.[ExchangeRate]
			 ELSE 1
			 END) as [ExchangeRate]
      ,[SDDocumentCategoryID]
      ,[SalesDocumentTypeID]
      ,[SalesDocumentItemCategoryID]
      ,[IsReturnsItemID]
      ,[CreationDate]
      ,[CreationTime]
      ,[LastChangeDate]
      ,[SalesOrganizationID]
      ,[DistributionChannelID]
      ,[DivisionID]
      ,[SalesGroupID]
      ,[SalesOfficeID]
      ,[InternationalArticleNumberID]
      ,[BatchID]
      ,[MaterialID]
      ,[OriginallyRequestedMaterialID]
      ,[MaterialSubstitutionReasonID]
      ,[MaterialGroupID]
      ,[BrandID]
      ,[Brand]
      ,[AdditionalMaterialGroup2ID]
      ,[AdditionalMaterialGroup3ID]
      ,[AdditionalMaterialGroup4ID]
      ,[AdditionalMaterialGroup5ID]
      ,[SoldToPartyID]
      ,[AdditionalCustomerGroup1ID]
      ,[AdditionalCustomerGroup2ID]
      ,[AdditionalCustomerGroup3ID]
      ,[AdditionalCustomerGroup4ID]
      ,[AdditionalCustomerGroup5ID]
      ,[ShipToPartyID]
      ,[PayerPartyID]
      ,[BillToPartyID]
      ,[SDDocumentReasonID]
      ,[SalesDocumentDate]
      ,[OrderQuantity]
      ,[OrderQuantityUnitID]
      ,[TargetQuantity]
      ,[TargetQuantityUnitID]
      ,[TargetToBaseQuantityDnmntr]
      ,[TargetToBaseQuantityNmrtr]
      ,[OrderToBaseQuantityDnmntr]
      ,[OrderToBaseQuantityNmrtr]
      ,[ConfdDelivQtyInOrderQtyUnit]
      ,[TargetDelivQtyInOrderQtyUnit]
      ,[ConfdDeliveryQtyInBaseUnit]
      ,[BaseUnitID]
      ,[ItemGrossWeight]
      ,[ItemNetWeight]
      ,[ItemWeightUnitID]
      ,[ItemVolume]
      ,[ItemVolumeUnitID]
      ,[ServicesRenderedDate]
      ,[SalesDistrictID]
      ,[CustomerGroupID]
      ,[HdrOrderProbabilityInPercentID]
      ,[ItemOrderProbabilityInPercentID]
      ,[SalesDocumentRjcnReasonID]
      ,[PricingDate]
      ,[ExchangeRateDate]
      ,[PriceDetnExchangeRate]
      ,[StatisticalValueControlID]
      ,CONVERT(decimal(19,6), CASE WHEN ER.[ExchangeRate] IS NOT NULL THEN [NetAmount] * ER.[ExchangeRate] ELSE [NetAmount] END) as [NetAmount]
      ,[TransactionCurrencyID]
      ,[SalesOrganizationCurrencyID]
	  ,CONVERT(decimal(19,6), CASE WHEN ER.[ExchangeRate] IS NOT NULL THEN [NetPriceAmount] * ER.[ExchangeRate] ELSE [NetPriceAmount] END) as [NetPriceAmount]
      ,[NetPriceQuantity]
      ,[NetPriceQuantityUnitID]
	  ,CONVERT(decimal(19,6), CASE WHEN ER.[ExchangeRate] IS NOT NULL THEN [TaxAmount] * ER.[ExchangeRate] ELSE [TaxAmount] END) as [TaxAmount]
	  ,CONVERT(decimal(19,6), CASE WHEN ER.[ExchangeRate] IS NOT NULL THEN [CostAmount] * ER.[ExchangeRate] ELSE [CostAmount] END) as [CostAmount]
	  ,CONVERT(decimal(19, 6), CASE WHEN ER.[ExchangeRate] IS NOT NULL THEN [Margin] * ER.[ExchangeRate] ELSE [Margin] END)
	  ,CONVERT(decimal(19,6), CASE WHEN ER.[ExchangeRate] IS NOT NULL THEN [Subtotal1Amount] * ER.[ExchangeRate] ELSE [Subtotal1Amount] END) as [Subtotal1Amount]
	  ,CONVERT(decimal(19,6), CASE WHEN ER.[ExchangeRate] IS NOT NULL THEN [Subtotal2Amount] * ER.[ExchangeRate] ELSE [Subtotal2Amount] END) as [Subtotal2Amount]
	  ,CONVERT(decimal(19,6), CASE WHEN ER.[ExchangeRate] IS NOT NULL THEN [Subtotal3Amount] * ER.[ExchangeRate] ELSE [Subtotal3Amount] END) as [Subtotal3Amount]
	  ,CONVERT(decimal(19,6), CASE WHEN ER.[ExchangeRate] IS NOT NULL THEN [Subtotal4Amount] * ER.[ExchangeRate] ELSE [Subtotal4Amount] END) as [Subtotal4Amount]
	  ,CONVERT(decimal(19,6), CASE WHEN ER.[ExchangeRate] IS NOT NULL THEN [Subtotal5Amount] * ER.[ExchangeRate] ELSE [Subtotal5Amount] END) as [Subtotal5Amount]
	  ,CONVERT(decimal(19,6), CASE WHEN ER.[ExchangeRate] IS NOT NULL THEN [Subtotal6Amount] * ER.[ExchangeRate] ELSE [Subtotal6Amount] END) as [Subtotal6Amount]
      ,[ShippingPointID]
      ,[ShippingTypeID]
      ,[DeliveryPriorityID]
      ,[InventorySpecialStockTypeID]
      ,[RequestedDeliveryDate]
      ,[ShippingConditionID]
      ,[DeliveryBlockReasonID]
      ,[PlantID]
      ,[StorageLocationID]
      ,[RouteID]
      ,[IncotermsClassificationID]
      ,[IncotermsVersionID]
      ,[IncotermsTransferLocationID]
      ,[IncotermsLocation1ID]
      ,[IncotermsLocation2ID]
      ,[MinDeliveryQtyInBaseUnit]
      ,[UnlimitedOverdeliveryIsAllowedID]
      ,[OverdelivTolrtdLmtRatioInPct]
      ,[UnderdelivTolrtdLmtRatioInPct]
      ,[PartialDeliveryIsAllowedID]
      ,[BindingPeriodValidityStartDate]
      ,[BindingPeriodValidityEndDate]
      ,[OutlineAgreementTargetAmount]
      ,[BillingDocumentDate]
      ,[BillingCompanyCodeID]
      ,[HeaderBillingBlockReasonID]
      ,[ItemBillingBlockReasonID]
      ,[FiscalYearID]
      ,[FiscalPeriodID]
      ,[CustomerAccountAssignmentGroupID]
      ,[ExchangeRateTypeID]
      ,[CurrencyID] as [CompanyCodeCurrencyID]
      ,[FiscalYearVariantID]
      ,[BusinessAreaID]
      ,[ProfitCenterID]
      ,[OrderID]
      ,[ProfitabilitySegmentID]
      ,[ControllingAreaID]
      ,[ReferenceSDDocumentID]
      ,[ReferenceSDDocumentItemID]
      ,[ReferenceSDDocumentCategoryID]
      ,[OriginSDDocumentID]
      ,[OriginSDDocumentItemID]
      ,[OverallSDProcessStatusID]
      ,[OverallTotalDeliveryStatusID]
      ,[OverallOrdReltdBillgStatusID]
      ,[TotalCreditCheckStatusID]
      ,[DeliveryBlockStatusID]
      ,[BillingBlockStatusID]
      ,[TotalSDDocReferenceStatusID]
      ,[SDDocReferenceStatusID]
      ,[OverallSDDocumentRejectionStsID]
      ,[SDDocumentRejectionStatusID]
      ,[OverallTotalSDDocRefStatusID]
      ,[OverallSDDocReferenceStatusID]
      ,[ItemGeneralIncompletionStatusID]
      ,[ItemBillingIncompletionStatusID]
      ,[PricingIncompletionStatusID]
      ,[ItemDeliveryIncompletionStatusID]
      ,[ExternalSalesAgentID]
      ,[ExternalSalesAgent]
      ,[GlobalParentID]
      ,[GlobalParent]
      ,[LocalParentID]
      ,[LocalParent]
      ,[ProjectID]
      ,[Project]
      ,[SalesEmployeeID]
      ,[SalesEmployee]
      ,[GlobalParentCalculatedID]
      ,[GlobalParentCalculated]
      ,[LocalParentCalculatedID]
      ,[LocalParentCalculated]
      ,[SDoc_ControllingObjectID]
      ,[SDItem_ControllingObjectID]
      ,[InOutID]
      ,SDI.[t_applicationId]
      ,SDI.[t_jobId]
      ,SDI.[t_jobDtm]
      ,SDI.[t_jobBy]
      ,SDI.[t_extractionDtm]
      ,SDI.[t_filePath]
  FROM [C_SalesDocumentItemDEXBase] SDI
  LEFT JOIN [edw].[dim_ExchangeRates] ER
  ON ER.[ExchangeRateEffectiveDate] =
	   (SELECT TOP(1) [edw].[dim_ExchangeRates].[ExchangeRateEffectiveDate]
		FROM [edw].[dim_ExchangeRates]
		WHERE [edw].[dim_ExchangeRates].[ExchangeRateEffectiveDate] <= SDI.[CreationDate]
		  AND [ExchangeRateType] = 'M'
          AND [SourceCurrency] = SDI.[TransactionCurrencyID]
		ORDER BY [ExchangeRateEffectiveDate] DESC)
 AND SDI.[TransactionCurrencyID] = ER.[SourceCurrency]
 AND SDI.[CurrencyID] = ER.[TargetCurrency]
 AND ER.[ExchangeRateType] = 'M'
 CROSS JOIN [edw].[dim_CurrencyType] CR
 WHERE CR.[CurrencyTypeID] = '10'
 UNION ALL
SELECT 
      -- [TS_SEQUENCE_NUMBER]
      --,[ODQ_CHANGEMODE]
      --,[ODQ_ENTITYCNTR]
       CONCAT_WS('¦', [SalesDocument] collate SQL_Latin1_General_CP1_CS_AS, [SalesDocumentItem] collate SQL_Latin1_General_CP1_CS_AS, CR.[CurrencyTypeID]) as [nk_fact_SalesDocumentItem]
      ,[SalesDocument]
      ,[SalesDocumentItem]
	  ,CR.[CurrencyTypeID]
      ,CR.[CurrencyType]
      ,[CurrencyID]
      ,EuroBudgetExchangeRate.[ExchangeRate] as [ExchangeRate]
      ,[SDDocumentCategoryID]
      ,[SalesDocumentTypeID]
      ,[SalesDocumentItemCategoryID]
      ,[IsReturnsItemID]
      ,[CreationDate]
      ,[CreationTime]
      ,[LastChangeDate]
      ,[SalesOrganizationID]
      ,[DistributionChannelID]
      ,[DivisionID]
      ,[SalesGroupID]
      ,[SalesOfficeID]
      ,[InternationalArticleNumberID]
      ,[BatchID]
      ,[MaterialID]
      ,[OriginallyRequestedMaterialID]
      ,[MaterialSubstitutionReasonID]
      ,[MaterialGroupID]
      ,[BrandID]
      ,[Brand]
      ,[AdditionalMaterialGroup2ID]
      ,[AdditionalMaterialGroup3ID]
      ,[AdditionalMaterialGroup4ID]
      ,[AdditionalMaterialGroup5ID]
      ,[SoldToPartyID]
      ,[AdditionalCustomerGroup1ID]
      ,[AdditionalCustomerGroup2ID]
      ,[AdditionalCustomerGroup3ID]
      ,[AdditionalCustomerGroup4ID]
      ,[AdditionalCustomerGroup5ID]
      ,[ShipToPartyID]
      ,[PayerPartyID]
      ,[BillToPartyID]
      ,[SDDocumentReasonID]
      ,[SalesDocumentDate]
      ,[OrderQuantity]
      ,[OrderQuantityUnitID]
      ,[TargetQuantity]
      ,[TargetQuantityUnitID]
      ,[TargetToBaseQuantityDnmntr]
      ,[TargetToBaseQuantityNmrtr]
      ,[OrderToBaseQuantityDnmntr]
      ,[OrderToBaseQuantityNmrtr]
      ,[ConfdDelivQtyInOrderQtyUnit]
      ,[TargetDelivQtyInOrderQtyUnit]
      ,[ConfdDeliveryQtyInBaseUnit]
      ,[BaseUnitID]
      ,[ItemGrossWeight]
      ,[ItemNetWeight]
      ,[ItemWeightUnitID]
      ,[ItemVolume]
      ,[ItemVolumeUnitID]
      ,[ServicesRenderedDate]
      ,[SalesDistrictID]
      ,[CustomerGroupID]
      ,[HdrOrderProbabilityInPercentID]
      ,[ItemOrderProbabilityInPercentID]
      ,[SalesDocumentRjcnReasonID]
      ,[PricingDate]
      ,[ExchangeRateDate]
      ,[PriceDetnExchangeRate]
      ,[StatisticalValueControlID]
      ,CONVERT(decimal(19,6), [NetAmount] * EuroBudgetExchangeRate.[ExchangeRate]) as [NetAmount]
      ,[TransactionCurrencyID]
      ,[SalesOrganizationCurrencyID]
      ,CONVERT(decimal(19,6), [NetPriceAmount] * EuroBudgetExchangeRate.[ExchangeRate]) as [NetPriceAmount]
      ,[NetPriceQuantity]
      ,[NetPriceQuantityUnitID]
	  ,CONVERT(decimal(19,6), [TaxAmount] * EuroBudgetExchangeRate.[ExchangeRate]) as [TaxAmount]
	  ,CONVERT(decimal(19,6), [CostAmount] * EuroBudgetExchangeRate.[ExchangeRate]) as [CostAmount]
      ,CONVERT(decimal(19, 6), [Margin] * EuroBudgetExchangeRate.[ExchangeRate])          as [Margin]
	  ,CONVERT(decimal(19,6), [Subtotal1Amount] * EuroBudgetExchangeRate.[ExchangeRate]) as [Subtotal1Amount]
	  ,CONVERT(decimal(19,6), [Subtotal2Amount] * EuroBudgetExchangeRate.[ExchangeRate]) as [Subtotal2Amount]
	  ,CONVERT(decimal(19,6), [Subtotal3Amount] * EuroBudgetExchangeRate.[ExchangeRate]) as [Subtotal3Amount]
	  ,CONVERT(decimal(19,6), [Subtotal4Amount] * EuroBudgetExchangeRate.[ExchangeRate]) as [Subtotal4Amount]
	  ,CONVERT(decimal(19,6), [Subtotal5Amount] * EuroBudgetExchangeRate.[ExchangeRate]) as [Subtotal5Amount]
      ,CONVERT(decimal(19,6), [Subtotal6Amount] * EuroBudgetExchangeRate.[ExchangeRate]) as [Subtotal6Amount]
      ,[ShippingPointID]
      ,[ShippingTypeID]
      ,[DeliveryPriorityID]
      ,[InventorySpecialStockTypeID]
      ,[RequestedDeliveryDate]
      ,[ShippingConditionID]
      ,[DeliveryBlockReasonID]
      ,[PlantID]
      ,[StorageLocationID]
      ,[RouteID]
      ,[IncotermsClassificationID]
      ,[IncotermsVersionID]
      ,[IncotermsTransferLocationID]
      ,[IncotermsLocation1ID]
      ,[IncotermsLocation2ID]
      ,[MinDeliveryQtyInBaseUnit]
      ,[UnlimitedOverdeliveryIsAllowedID]
      ,[OverdelivTolrtdLmtRatioInPct]
      ,[UnderdelivTolrtdLmtRatioInPct]
      ,[PartialDeliveryIsAllowedID]
      ,[BindingPeriodValidityStartDate]
      ,[BindingPeriodValidityEndDate]
      ,[OutlineAgreementTargetAmount]
      ,[BillingDocumentDate]
      ,[BillingCompanyCodeID]
      ,[HeaderBillingBlockReasonID]
      ,[ItemBillingBlockReasonID]
      ,[FiscalYearID]
      ,[FiscalPeriodID]
      ,[CustomerAccountAssignmentGroupID]
      ,[ExchangeRateTypeID]
      ,[CurrencyID] as [CompanyCodeCurrencyID]
      ,[FiscalYearVariantID]
      ,[BusinessAreaID]
      ,[ProfitCenterID]
      ,[OrderID]
      ,[ProfitabilitySegmentID]
      ,[ControllingAreaID]
      ,[ReferenceSDDocumentID]
      ,[ReferenceSDDocumentItemID]
      ,[ReferenceSDDocumentCategoryID]
      ,[OriginSDDocumentID]
      ,[OriginSDDocumentItemID]
      ,[OverallSDProcessStatusID]
      ,[OverallTotalDeliveryStatusID]
      ,[OverallOrdReltdBillgStatusID]
      ,[TotalCreditCheckStatusID]
      ,[DeliveryBlockStatusID]
      ,[BillingBlockStatusID]
      ,[TotalSDDocReferenceStatusID]
      ,[SDDocReferenceStatusID]
      ,[OverallSDDocumentRejectionStsID]
      ,[SDDocumentRejectionStatusID]
      ,[OverallTotalSDDocRefStatusID]
      ,[OverallSDDocReferenceStatusID]
      ,[ItemGeneralIncompletionStatusID]
      ,[ItemBillingIncompletionStatusID]
      ,[PricingIncompletionStatusID]
      ,[ItemDeliveryIncompletionStatusID]
      ,[ExternalSalesAgentID]
      ,[ExternalSalesAgent]
      ,[GlobalParentID]
      ,[GlobalParent]
      ,[LocalParentID]
      ,[LocalParent]
      ,[ProjectID]
      ,[Project]
      ,[SalesEmployeeID]
      ,[SalesEmployee]
      ,[GlobalParentCalculatedID]
      ,[GlobalParentCalculated]
      ,[LocalParentCalculatedID]
      ,[LocalParentCalculated]
      ,[SDoc_ControllingObjectID]
      ,[SDItem_ControllingObjectID]
      ,[InOutID]
      ,sdi_er_date.[t_applicationId]
      ,sdi_er_date.[t_jobId]
      ,sdi_er_date.[t_jobDtm]
      ,sdi_er_date.[t_jobBy]
      ,sdi_er_date.[t_extractionDtm]
      ,sdi_er_date.[t_filePath]
  FROM (
  SELECT
	   --[TS_SEQUENCE_NUMBER]
    --  ,[ODQ_CHANGEMODE]
    --  ,[ODQ_ENTITYCNTR]
       [SalesDocument]
      ,[SalesDocumentItem]
	  ,'EUR' as [CurrencyID]
      ,[SDDocumentCategoryID]
      ,[SalesDocumentTypeID]
      ,[SalesDocumentItemCategoryID]
      ,[IsReturnsItemID]
      ,[CreationDate]
      ,[CreationTime]
      ,[LastChangeDate]
      ,[SalesOrganizationID]
      ,[DistributionChannelID]
      ,[DivisionID]
      ,[SalesGroupID]
      ,[SalesOfficeID]
      ,[InternationalArticleNumberID]
      ,[BatchID]
      ,[MaterialID]
      ,[OriginallyRequestedMaterialID]
      ,[MaterialSubstitutionReasonID]
      ,[MaterialGroupID]
      ,[BrandID]
      ,[Brand]
      ,[AdditionalMaterialGroup2ID]
      ,[AdditionalMaterialGroup3ID]
      ,[AdditionalMaterialGroup4ID]
      ,[AdditionalMaterialGroup5ID]
      ,[SoldToPartyID]
      ,[AdditionalCustomerGroup1ID]
      ,[AdditionalCustomerGroup2ID]
      ,[AdditionalCustomerGroup3ID]
      ,[AdditionalCustomerGroup4ID]
      ,[AdditionalCustomerGroup5ID]
      ,[ShipToPartyID]
      ,[PayerPartyID]
      ,[BillToPartyID]
      ,[SDDocumentReasonID]
      ,[SalesDocumentDate]
      ,[OrderQuantity]
      ,[OrderQuantityUnitID]
      ,[TargetQuantity]
      ,[TargetQuantityUnitID]
      ,[TargetToBaseQuantityDnmntr]
      ,[TargetToBaseQuantityNmrtr]
      ,[OrderToBaseQuantityDnmntr]
      ,[OrderToBaseQuantityNmrtr]
      ,[ConfdDelivQtyInOrderQtyUnit]
      ,[TargetDelivQtyInOrderQtyUnit]
      ,[ConfdDeliveryQtyInBaseUnit]
      ,[BaseUnitID]
      ,[ItemGrossWeight]
      ,[ItemNetWeight]
      ,[ItemWeightUnitID]
      ,[ItemVolume]
      ,[ItemVolumeUnitID]
      ,[ServicesRenderedDate]
      ,[SalesDistrictID]
      ,[CustomerGroupID]
      ,[HdrOrderProbabilityInPercentID]
      ,[ItemOrderProbabilityInPercentID]
      ,[SalesDocumentRjcnReasonID]
      ,[PricingDate]
      ,[ExchangeRateDate]
      ,[PriceDetnExchangeRate]
      ,[StatisticalValueControlID]
      ,[NetAmount]
      ,[TransactionCurrencyID]
      ,[SalesOrganizationCurrencyID]
      ,[NetPriceAmount]
      ,[NetPriceQuantity]
      ,[NetPriceQuantityUnitID]
      ,[TaxAmount]
      ,[CostAmount]
      ,[Margin]
      ,[Subtotal1Amount]
      ,[Subtotal2Amount]
      ,[Subtotal3Amount]
      ,[Subtotal4Amount]
      ,[Subtotal5Amount]
      ,[Subtotal6Amount]
      ,[ShippingPointID]
      ,[ShippingTypeID]
      ,[DeliveryPriorityID]
      ,[InventorySpecialStockTypeID]
      ,[RequestedDeliveryDate]
      ,[ShippingConditionID]
      ,[DeliveryBlockReasonID]
      ,[PlantID]
      ,[StorageLocationID]
      ,[RouteID]
      ,[IncotermsClassificationID]
      ,[IncotermsVersionID]
      ,[IncotermsTransferLocationID]
      ,[IncotermsLocation1ID]
      ,[IncotermsLocation2ID]
      ,[MinDeliveryQtyInBaseUnit]
      ,[UnlimitedOverdeliveryIsAllowedID]
      ,[OverdelivTolrtdLmtRatioInPct]
      ,[UnderdelivTolrtdLmtRatioInPct]
      ,[PartialDeliveryIsAllowedID]
      ,[BindingPeriodValidityStartDate]
      ,[BindingPeriodValidityEndDate]
      ,[OutlineAgreementTargetAmount]
      ,[BillingDocumentDate]
      ,[BillingCompanyCodeID]
      ,[HeaderBillingBlockReasonID]
      ,[ItemBillingBlockReasonID]
      ,[FiscalYearID]
      ,[FiscalPeriodID]
      ,[CustomerAccountAssignmentGroupID]
      ,[ExchangeRateTypeID]
      ,[CurrencyID] as [CompanyCodeCurrencyID]
      ,[FiscalYearVariantID]
      ,[BusinessAreaID]
      ,[ProfitCenterID]
      ,[OrderID]
      ,[ProfitabilitySegmentID]
      ,[ControllingAreaID]
      ,[ReferenceSDDocumentID]
      ,[ReferenceSDDocumentItemID]
      ,[ReferenceSDDocumentCategoryID]
      ,[OriginSDDocumentID]
      ,[OriginSDDocumentItemID]
      ,[OverallSDProcessStatusID]
      ,[OverallTotalDeliveryStatusID]
      ,[OverallOrdReltdBillgStatusID]
      ,[TotalCreditCheckStatusID]
      ,[DeliveryBlockStatusID]
      ,[BillingBlockStatusID]
      ,[TotalSDDocReferenceStatusID]
      ,[SDDocReferenceStatusID]
      ,[OverallSDDocumentRejectionStsID]
      ,[SDDocumentRejectionStatusID]
      ,[OverallTotalSDDocRefStatusID]
      ,[OverallSDDocReferenceStatusID]
      ,[ItemGeneralIncompletionStatusID]
      ,[ItemBillingIncompletionStatusID]
      ,[PricingIncompletionStatusID]
      ,[ItemDeliveryIncompletionStatusID]
	  ,[ExternalSalesAgentID]
	  ,[ExternalSalesAgent]
	  ,[GlobalParentID]
	  ,[GlobalParent]
	  ,[LocalParentID]
	  ,[LocalParent]
	  ,[ProjectID]
	  ,[Project]
	  ,[SalesEmployeeID]
	  ,[SalesEmployee]
	  ,[GlobalParentCalculatedID]
	  ,[GlobalParentCalculated]
	  ,[LocalParentCalculatedID]
	  ,[LocalParentCalculated]
      ,[SDoc_ControllingObjectID]
      ,[SDItem_ControllingObjectID]
      ,[InOutID]
      ,SDI.[t_applicationId]
      ,SDI.[t_jobId]
      ,SDI.[t_jobDtm]
      ,SDI.[t_jobBy]
      ,SDI.[t_extractionDtm]
      ,SDI.[t_filePath]
	  ,MAX([ExchangeRateEffectiveDate]) as [ExchangeRateEffectiveDate]
  FROM
    C_SalesDocumentItemDEXBase SDI
  LEFT JOIN
    EuroBudgetExchangeRate
        on SDI.TransactionCurrencyID = EuroBudgetExchangeRate.SourceCurrency
  where
    [ExchangeRateEffectiveDate] <= [BillingDocumentDate]
  group by
      -- [TS_SEQUENCE_NUMBER]
      --,[ODQ_CHANGEMODE]
      --,[ODQ_ENTITYCNTR]
       [SalesDocument]
      ,[SalesDocumentItem]
      ,[SDDocumentCategoryID]
      ,[SalesDocumentTypeID]
      ,[SalesDocumentItemCategoryID]
      ,[IsReturnsItemID]
      ,[CreationDate]
      ,[CreationTime]
      ,[LastChangeDate]
      ,[SalesOrganizationID]
      ,[DistributionChannelID]
      ,[DivisionID]
      ,[SalesGroupID]
      ,[SalesOfficeID]
      ,[InternationalArticleNumberID]
      ,[BatchID]
      ,[MaterialID]
      ,[OriginallyRequestedMaterialID]
      ,[MaterialSubstitutionReasonID]
      ,[MaterialGroupID]
      ,[BrandID]
      ,[Brand]
      ,[AdditionalMaterialGroup2ID]
      ,[AdditionalMaterialGroup3ID]
      ,[AdditionalMaterialGroup4ID]
      ,[AdditionalMaterialGroup5ID]
      ,[SoldToPartyID]
      ,[AdditionalCustomerGroup1ID]
      ,[AdditionalCustomerGroup2ID]
      ,[AdditionalCustomerGroup3ID]
      ,[AdditionalCustomerGroup4ID]
      ,[AdditionalCustomerGroup5ID]
      ,[ShipToPartyID]
      ,[PayerPartyID]
      ,[BillToPartyID]
      ,[SDDocumentReasonID]
      ,[SalesDocumentDate]
      ,[OrderQuantity]
      ,[OrderQuantityUnitID]
      ,[TargetQuantity]
      ,[TargetQuantityUnitID]
      ,[TargetToBaseQuantityDnmntr]
      ,[TargetToBaseQuantityNmrtr]
      ,[OrderToBaseQuantityDnmntr]
      ,[OrderToBaseQuantityNmrtr]
      ,[ConfdDelivQtyInOrderQtyUnit]
      ,[TargetDelivQtyInOrderQtyUnit]
      ,[ConfdDeliveryQtyInBaseUnit]
      ,[BaseUnitID]
      ,[ItemGrossWeight]
      ,[ItemNetWeight]
      ,[ItemWeightUnitID]
      ,[ItemVolume]
      ,[ItemVolumeUnitID]
      ,[ServicesRenderedDate]
      ,[SalesDistrictID]
      ,[CustomerGroupID]
      ,[HdrOrderProbabilityInPercentID]
      ,[ItemOrderProbabilityInPercentID]
      ,[SalesDocumentRjcnReasonID]
      ,[PricingDate]
      ,[ExchangeRateDate]
      ,[PriceDetnExchangeRate]
      ,[StatisticalValueControlID]
      ,[NetAmount]
      ,[TransactionCurrencyID]
      ,[SalesOrganizationCurrencyID]
      ,[NetPriceAmount]
      ,[NetPriceQuantity]
      ,[NetPriceQuantityUnitID]
      ,[TaxAmount]
      ,[CostAmount]
      ,[Margin]
      ,[Subtotal1Amount]
      ,[Subtotal2Amount]
      ,[Subtotal3Amount]
      ,[Subtotal4Amount]
      ,[Subtotal5Amount]
      ,[Subtotal6Amount]
      ,[ShippingPointID]
      ,[ShippingTypeID]
      ,[DeliveryPriorityID]
      ,[InventorySpecialStockTypeID]
      ,[RequestedDeliveryDate]
      ,[ShippingConditionID]
      ,[DeliveryBlockReasonID]
      ,[PlantID]
      ,[StorageLocationID]
      ,[RouteID]
      ,[IncotermsClassificationID]
      ,[IncotermsVersionID]
      ,[IncotermsTransferLocationID]
      ,[IncotermsLocation1ID]
      ,[IncotermsLocation2ID]
      ,[MinDeliveryQtyInBaseUnit]
      ,[UnlimitedOverdeliveryIsAllowedID]
      ,[OverdelivTolrtdLmtRatioInPct]
      ,[UnderdelivTolrtdLmtRatioInPct]
      ,[PartialDeliveryIsAllowedID]
      ,[BindingPeriodValidityStartDate]
      ,[BindingPeriodValidityEndDate]
      ,[OutlineAgreementTargetAmount]
      ,[BillingDocumentDate]
      ,[BillingCompanyCodeID]
      ,[HeaderBillingBlockReasonID]
      ,[ItemBillingBlockReasonID]
      ,[FiscalYearID]
      ,[FiscalPeriodID]
      ,[CustomerAccountAssignmentGroupID]
      ,[ExchangeRateTypeID]
      ,[CurrencyID]
      ,[FiscalYearVariantID]
      ,[BusinessAreaID]
      ,[ProfitCenterID]
      ,[OrderID]
      ,[ProfitabilitySegmentID]
      ,[ControllingAreaID]
      ,[ReferenceSDDocumentID]
      ,[ReferenceSDDocumentItemID]
      ,[ReferenceSDDocumentCategoryID]
      ,[OriginSDDocumentID]
      ,[OriginSDDocumentItemID]
      ,[OverallSDProcessStatusID]
      ,[OverallTotalDeliveryStatusID]
      ,[OverallOrdReltdBillgStatusID]
      ,[TotalCreditCheckStatusID]
      ,[DeliveryBlockStatusID]
      ,[BillingBlockStatusID]
      ,[TotalSDDocReferenceStatusID]
      ,[SDDocReferenceStatusID]
      ,[OverallSDDocumentRejectionStsID]
      ,[SDDocumentRejectionStatusID]
      ,[OverallTotalSDDocRefStatusID]
      ,[OverallSDDocReferenceStatusID]
      ,[ItemGeneralIncompletionStatusID]
      ,[ItemBillingIncompletionStatusID]
      ,[PricingIncompletionStatusID]
      ,[ItemDeliveryIncompletionStatusID]
	  ,[ExternalSalesAgentID]
	  ,[ExternalSalesAgent]
	  ,[GlobalParentID]
	  ,[GlobalParent]
	  ,[LocalParentID]
	  ,[LocalParent]
	  ,[ProjectID]
	  ,[Project]
	  ,[SalesEmployeeID]
	  ,[SalesEmployee]
	  ,[GlobalParentCalculatedID]
	  ,[GlobalParentCalculated]
	  ,[LocalParentCalculatedID]
	  ,[LocalParentCalculated]
      ,[SDoc_ControllingObjectID]
      ,[SDItem_ControllingObjectID]
      ,[InOutID]
      ,SDI.[t_applicationId]
      ,SDI.[t_jobId]
      ,SDI.[t_jobDtm]
      ,SDI.[t_jobBy]
      ,SDI.[t_extractionDtm]
      ,SDI.[t_filePath]
) sdi_er_date
left join
    EuroBudgetExchangeRate
    ON
        sdi_er_date.[TransactionCurrencyID] = EuroBudgetExchangeRate.[SourceCurrency]
        AND
        sdi_er_date.[ExchangeRateEffectiveDate] = EuroBudgetExchangeRate.[ExchangeRateEffectiveDate]
CROSS JOIN
    [edw].[dim_CurrencyType] CR
WHERE
    CR.[CurrencyTypeID] = '30'
