CREATE VIEW [dq].[vw_BP_2_1_3_ThirdParty]
  AS  

SELECT
        Customer.[Customer]
    ,   Customer.[CustomerName]
    ,   Customer.[CustomerFullName]
    ,   Customer.[CreatedByUser]
    ,   Customer.[CreationDate]
    ,   Customer.[AddressID]
    ,   Customer.[CustomerClassification]
    ,   Customer.[VATRegistration]
    ,   Customer.[CustomerAccountGroup]
    ,   Customer.[AuthorizationGroup]
    ,   Customer.[DeliveryIsBlocked]
    ,   Customer.[PostingIsBlocked]
    ,   Customer.[BillingIsBlockedForCustomer] 
    ,   Customer.[OrderIsBlockedForCustomer]
    ,   Customer.[InternationalLocationNumber1]
    ,   Customer.[IsOneTimeAccount]
    ,   Customer.[TaxJurisdiction]
    ,   Customer.[Industry]
    ,   Customer.[TaxNumberType]
    ,   Customer.[TaxNumber1]
    ,   Customer.[TaxNumber2]
    ,   Customer.[TaxNumber3]
    ,   Customer.[TaxNumber4]
    ,   Customer.[TaxNumber5]
    ,   Customer.[CustomerCorporateGroup]
    ,   Customer.[Supplier]
    ,   Customer.[NielsenRegion]
    ,   Customer.[IndustryCode1]
    ,   Customer.[IndustryCode2]
    ,   Customer.[IndustryCode3]
    ,   Customer.[IndustryCode4]
    ,   Customer.[IndustryCode5]
    ,   Customer.[Country]
    ,   Customer.[OrganizationBPName1]
    ,   Customer.[OrganizationBPName2]
    ,   Customer.[CityName]
    ,   Customer.[PostalCode]
    ,   Customer.[StreetName]
    ,   Customer.[SortField]
    ,   Customer.[FaxNumber]
    ,   Customer.[BR_SUFRAMACode]
    ,   Customer.[Region]
    ,   Customer.[TelephoneNumber1]
    ,   Customer.[TelephoneNumber2]
    ,   Customer.[AlternativePayerAccount]
    ,   Customer.[DataMediumExchangeIndicator]
    ,   Customer.[VATLiability]
    ,   Customer.[IsBusinessPurposeCompleted]
    ,   Customer.[ResponsibleType]
    ,   Customer.[FiscalAddress]
    ,   Customer.[NFPartnerIsNaturalPerson]
    ,   Customer.[DeletionIndicator]
    ,   Customer.[Language]
    ,   Customer.[TradingPartner]
    ,   Customer.[TaxInvoiceRepresentativeName]
    ,   Customer.[BusinessType]
    ,   Customer.[IndustryType]
    ,   '2.1.3_ThirdParty' AS [RuleID]
    ,   1 AS [Count]
FROM   
    [base_s4h_cax].[I_Customer] Customer
INNER JOIN
   [base_s4h_cax].[I_CustomerCompany] CustCompany
   ON
   Customer.[Customer] = CustCompany.[Customer] 
LEFT JOIN
   [base_s4h_cax].[I_CompanyCode] CompanyCode
   ON
   CustCompany.[CompanyCode] = CompanyCode.[CompanyCode] 
WHERE
    (CustCompany.[CashPlanningGroup]<>'E2'
    AND
    Customer.[Country]<>CompanyCode.[Country])
    OR
    (CustCompany.[CashPlanningGroup]<>'E3'
    AND
    Customer.[Country]=CompanyCode.[Country])
GROUP BY
        Customer.[Customer]
    ,   Customer.[CustomerName]
    ,   Customer.[CustomerFullName]
    ,   Customer.[CreatedByUser]
    ,   Customer.[CreationDate]
    ,   Customer.[AddressID]
    ,   Customer.[CustomerClassification]
    ,   Customer.[VATRegistration]
    ,   Customer.[CustomerAccountGroup]
    ,   Customer.[AuthorizationGroup]
    ,   Customer.[DeliveryIsBlocked]
    ,   Customer.[PostingIsBlocked]
    ,   Customer.[BillingIsBlockedForCustomer] 
    ,   Customer.[OrderIsBlockedForCustomer]
    ,   Customer.[InternationalLocationNumber1]
    ,   Customer.[IsOneTimeAccount]
    ,   Customer.[TaxJurisdiction]
    ,   Customer.[Industry]
    ,   Customer.[TaxNumberType]
    ,   Customer.[TaxNumber1]
    ,   Customer.[TaxNumber2]
    ,   Customer.[TaxNumber3]
    ,   Customer.[TaxNumber4]
    ,   Customer.[TaxNumber5]
    ,   Customer.[CustomerCorporateGroup]
    ,   Customer.[Supplier]
    ,   Customer.[NielsenRegion]
    ,   Customer.[IndustryCode1]
    ,   Customer.[IndustryCode2]
    ,   Customer.[IndustryCode3]
    ,   Customer.[IndustryCode4]
    ,   Customer.[IndustryCode5]
    ,   Customer.[Country]
    ,   Customer.[OrganizationBPName1]
    ,   Customer.[OrganizationBPName2]
    ,   Customer.[CityName]
    ,   Customer.[PostalCode]
    ,   Customer.[StreetName]
    ,   Customer.[SortField]
    ,   Customer.[FaxNumber]
    ,   Customer.[BR_SUFRAMACode]
    ,   Customer.[Region]
    ,   Customer.[TelephoneNumber1]
    ,   Customer.[TelephoneNumber2]
    ,   Customer.[AlternativePayerAccount]
    ,   Customer.[DataMediumExchangeIndicator]
    ,   Customer.[VATLiability]
    ,   Customer.[IsBusinessPurposeCompleted]
    ,   Customer.[ResponsibleType]
    ,   Customer.[FiscalAddress]
    ,   Customer.[NFPartnerIsNaturalPerson]
    ,   Customer.[DeletionIndicator]
    ,   Customer.[Language]
    ,   Customer.[TradingPartner]
    ,   Customer.[TaxInvoiceRepresentativeName]
    ,   Customer.[BusinessType]
    ,   Customer.[IndustryType]