CREATE TABLE [base_tx_halfen_2_dwh].[DIM_INVENTDIM]
(
	[DW_Id] 			BIGINT NOT NULL,
	[INVENTDIMID]		NVARCHAR(20) NULL,
	[INVENTSITEID] 		NVARCHAR(10) NULL,
	[INVENTLOCATIONID] 	NVARCHAR(10) NULL,
	[CONFIGID] 			NVARCHAR(24) NULL,
	[INVENTBATCHID] 	NVARCHAR(20) NULL,
	[WMSLOCATIONID] 	NVARCHAR(25) NULL,
	[WMSPALLETID]   	NVARCHAR(18) NULL,
	[INVENTSIZEID]  	NVARCHAR(10) NULL,	
	[DW_Batch] 			BIGINT NULL,
	[DW_SourceCode] 	VARCHAR(15) NOT NULL,
	[DW_TimeStamp] 		DATETIME NOT NULL,
	[t_applicationId]   VARCHAR    (32)  NULL,
    [t_jobId]           VARCHAR    (36)  NULL,
    [t_jobDtm]          DATETIME,
    [t_jobBy]           NVARCHAR  (128)  NULL,
    [t_extractionDtm]   DATETIME,
    [t_filePath]        NVARCHAR (1024)  NULL,
    CONSTRAINT [PK_DIM_INVENTDIM] PRIMARY KEY NONCLUSTERED (
        [DW_Id] ASC
    ) NOT ENFORCED
)
WITH(
	HEAP,
	DISTRIBUTION = REPLICATE
);
