CREATE TABLE [base_tx_halfen_2_dwh].[FACT_CUSTPACKINGSLIPTRANS_Archive]
(
    [DW_Id]                                     BIGINT          NOT NULL,
    [DATAAREAID]                                NVARCHAR(4)     NULL,
    [ORIGSALESID]                               NVARCHAR(20)    NULL,
    [PACKINGSLIPID]                             NVARCHAR(20)    NOT NULL,
    [DLVCOUNTRYREGIONID]                        NVARCHAR(10)    NULL,
    [DELIVERYDATE]                              DATETIME        NULL,
    [DeliveryDate_RunningDayNumber]             BIGINT          NULL,
    [HPLDLVMODEID]                              NVARCHAR(10)    NULL,
    [INVENTTRANSID]                             NVARCHAR(24)    NOT NULL,
    [ITEMID]                                    NVARCHAR(20)    NULL,
    [INVENTDIMID]                               NVARCHAR(20)    NULL,
    [ORDERACCOUNT]                              NVARCHAR(20)    NULL,
    [SalesTaker]                                NVARCHAR(20)    NULL,
    [DLVTerm]                                   NVARCHAR(10)    NULL,
    [Payment]                                   NVARCHAR(10)    NULL,
    [DIMENSION]                                 NVARCHAR(10)    NULL,
    [HPLCOSTPRICE]                              DECIMAL(38, 12) NULL,
    [QTY]                                       DECIMAL(38, 12) NULL,
    [AMOUNTCUR_CZ]                              DECIMAL(38, 12) NULL,
    [CURRENCYCODE_CZ]                           NVARCHAR(3)     NULL,
    [SHIPPINGDATEREQUESTED]                     DATETIME        NULL,
    [ShippingSiteRequested_RunningDayNumber]    BIGINT          NULL,
    [SHIPPINGDATECONFIRMED_tf]                  DATETIME        NULL,
    [ShippingDateConfirmed_tf_RunningDayNumber] BIGINT          NULL,
    [RECID]                                     BIGINT          NULL,
    [INVENTSITEID]                              NVARCHAR(10)    NULL,
    [INVENTLOCATIONID]                          NVARCHAR(10)    NULL,
    [DeliveryDateDiff]                          DECIMAL(38, 0)  NULL,
    [Reliability01]                             BIGINT          NULL,
    [DeliveryDateDiff2]                         DECIMAL(38, 0)  NULL,
    [Reliability201]                            BIGINT          NULL,
    [CategoryId]                                BIGINT          NULL,
    [ExtendedCategoryId]                        BIGINT          NULL,
    [bomlines]                                  BIGINT          NULL,
    [SalesLine_Dw_Id]                           BIGINT          NULL,
    [CountryRegion_DW_Id]                       BIGINT          NULL,
    [DateKey_DeliveryDate]                      BIGINT          NULL,
    [CustPackingslipJour_DW_Id]                 BIGINT          NULL,
    [ReqItemTable_DW_Id]                        BIGINT          NULL,
    [SameDeliveryDate_SalesLine]                BIGINT          NULL,
    [Reliability_Stock_Items]                   BIGINT          NULL,
    [HLFSEGMENTID]                              NVARCHAR(4)     NULL,
    [Segment_DW_Id]                             BIGINT          NULL,
    [SALESGROUP]                                NVARCHAR(10)    NULL,
    [SalesPerson_DW_Id]                         BIGINT          NULL,
    [DW_Id_Itemid]                              BIGINT          NULL,
    [DW_Batch]                                  BIGINT          NULL,
    [DW_SourceCode]                             VARCHAR(15)     NOT NULL,
    [DW_TimeStamp]                              DATETIME        NOT NULL,
    [t_applicationId]                           VARCHAR(32)       NULL,
    [t_jobId]                                   VARCHAR(36)       NULL,
    [t_jobDtm]                                  DATETIME,
    [t_jobBy]                                   NVARCHAR(128)     NULL,
    [t_extractionDtm]                           DATETIME,
    [t_filePath]                                NVARCHAR(1024)    NULL,
    CONSTRAINT [PK_FACT_CUSTPACKINGSLIPTRANS_Archive] PRIMARY KEY NONCLUSTERED ([PACKINGSLIPID], [INVENTTRANSID]) NOT ENFORCED
)
    WITH  
(
	DISTRIBUTION = HASH ([INVENTDIMID]),
	CLUSTERED COLUMNSTORE INDEX
);