CREATE TABLE [base_tx_halfen_2_dwh].[FACT_CUSTPACKINGSLIPTRANS]
(
    [DW_Id]                                     [bigint]          NOT NULL,
    [DATAAREAID]                                [nvarchar](4)     NULL,
    [ORIGSALESID]                               [nvarchar](20)    NULL,
    [PACKINGSLIPID]                             [nvarchar](20)    NOT NULL,
    [DLVCOUNTRYREGIONID]                        [nvarchar](10)    NULL,
    [DELIVERYDATE]                              [datetime]        NULL,
    [DeliveryDate_RunningDayNumber]             [bigint]          NULL,
    [HPLDLVMODEID]                              [nvarchar](10)    NULL,
    [INVENTTRANSID]                             [nvarchar](24)    NOT NULL,
    [ITEMID]                                    [nvarchar](20)    NULL,
    [INVENTDIMID]                               [nvarchar](20)    NULL,
    [ORDERACCOUNT]                              [nvarchar](20)    NULL,
    [SalesTaker]                                [nvarchar](20)    NULL,
    [DLVTerm]                                   [nvarchar](10)    NULL,
    [Payment]                                   [nvarchar](10)    NULL,
    [DIMENSION]                                 [nvarchar](10)    NULL,
    [HPLCOSTPRICE]                              [decimal](38, 12) NULL,
    [QTY]                                       [decimal](38, 12) NULL,
    [AMOUNTCUR_CZ]                              [decimal](38, 12) NULL,
    [CURRENCYCODE_CZ]                           [nvarchar](3)     NULL,
    [SHIPPINGDATEREQUESTED]                     [datetime]        NULL,
    [ShippingSiteRequested_RunningDayNumber]    [bigint]          NULL,
    [SHIPPINGDATECONFIRMED_tf]                  [datetime]        NULL,
    [ShippingDateConfirmed_tf_RunningDayNumber] [bigint]          NULL,
    [RECID]                                     [bigint]          NULL,
    [INVENTSITEID]                              [nvarchar](10)    NULL,
    [INVENTLOCATIONID]                          [nvarchar](10)    NULL,
    [DeliveryDateDiff]                          [decimal](38, 0)  NULL,
    [Reliability01]                             [bigint]          NULL,
    [DeliveryDateDiff2]                         [decimal](38, 0)  NULL,
    [Reliability201]                            [bigint]          NULL,
    [CategoryId]                                [bigint]          NULL,
    [ExtendedCategoryId]                        [bigint]          NULL,
    [bomlines]                                  [bigint]          NULL,
    [SalesLine_Dw_Id]                           [bigint]          NULL,
    [CountryRegion_DW_Id]                       [bigint]          NULL,
    [DateKey_DeliveryDate]                      [bigint]          NULL,
    [CustPackingslipJour_DW_Id]                 [bigint]          NULL,
    [ReqItemTable_DW_Id]                        [bigint]          NULL,
    [SameDeliveryDate_SalesLine]                [bigint]          NULL,
    [Reliability_Stock_Items]                   [bigint]          NULL,
    [HLFSEGMENTID]                              [nvarchar](4)     NULL,
    [Segment_DW_Id]                             [bigint]          NULL,
    [SALESGROUP]                                [nvarchar](10)    NULL,
    [SalesPerson_DW_Id]                         [bigint]          NULL,
    [DW_Id_Itemid]                              [bigint]          NULL,
    [DW_Batch]                                  [bigint]          NULL,
    [DW_SourceCode]                             [varchar](15)     NOT NULL,
    [DW_TimeStamp]                              [datetime]        NOT NULL,
    [t_applicationId]                           VARCHAR(32)       NULL,
    [t_jobId]                                   VARCHAR(36)       NULL,
    [t_jobDtm]                                  DATETIME,
    [t_jobBy]                                   NVARCHAR(128)     NULL,
    [t_extractionDtm]                           DATETIME,
    [t_filePath]                                NVARCHAR(1024)    NULL,
    CONSTRAINT [PK_FACT_CUSTPACKINGSLIPTRANS] PRIMARY KEY NONCLUSTERED ([PACKINGSLIPID], [INVENTTRANSID]) NOT ENFORCED
)
    WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);