CREATE TABLE [intm_axbi].[CUSTTABLE](
	[DATAAREAID] [nvarchar](8) NOT NULL,
	[ACCOUNTNUM] [nvarchar](100) NOT NULL,
	[NAME] [nvarchar](200) NOT NULL,
	[INOUT] [nvarchar](1) NOT NULL,
	[CUSTOMERPILLAR] [nvarchar](20) NOT NULL,
	[COMPANYCHAINID] [nvarchar](60) NOT NULL,
	[DIMENSION3_] [nvarchar](20) NOT NULL,
	CONSTRAINT [PK_CUSTTABLE] PRIMARY KEY NONCLUSTERED 
	(
        [DATAAREAID], [ACCOUNTNUM]
    ) NOT ENFORCED
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);