CREATE TABLE [intm_axbi].[dim_ITEMGROUP](
	[DATAAREAID] [nvarchar](8) NOT NULL,
	[ITEMGROUPID] [nvarchar](60) NOT NULL,
	[ITEMGROUPNAME] [nvarchar](100) NOT NULL
) WITH (HEAP, DISTRIBUTION = REPLICATE);